### ISSUE TITLE
Media player, music assistant

### ISSUE THREAD

**Issue by luckyzor** [Blackymas/NSPanel_HA_Blueprint#1]
Hello,
Have you tried to add music assistant or media player to nspanel?

Btw I will try your project in my nspanel, it looks amazing, thanks for your work.

**Comment by Blackymas** [comment]
Hi yes that is possible.

The project is not quite finished yet. 

The hard thing was to create a basic building module with which I can implement very flexible different things

**Comment by Blackymas** [comment]
and thanks :)

**Comment by Blackymas** [comment]
is in the roadmap ;)
