### ISSUE TITLE
Nextion Display not turning on after unsucessful install of panel tft

### ISSUE THREAD

**Issue by trinitrion** [Blackymas/NSPanel_HA_Blueprint#1000]
Hi all,

As announced in a previous report my display is neither working (not even backlit) nor unresponsive to several attempts to flash a working firmware to it.

Some logs and info are still missing here as I need to reconnect the display again. Will follow.

Appreciate any help! 

## Images

Here are some pictures of its current state.

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/105319980/0f5f2023-b574-4908-8d6a-e406b159b27f)

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/105319980/c24c59a0-13d6-4d98-8d3d-07bdc69eb886)

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/105319980/da15e2e0-53b4-4abb-b457-a75a181f7cd4)

### Flashing ESPHome successful, but...
Why first attempt to install ESPHome to the nspanel was successful. Flashing went through fine and the device appeared duly in HomeAssistant.

### ...flashing nspanel_eu.tft not so
However, the next step did not work. 

At first, I tried to install the nspanel_eu.tft right away and not the blank. When the flashing process finally started (after some exit reparses) it got stuck after 5% and did not move on after 12h. This was when I decided to unplug the panel from the wall connector and to try again. No joy. I then tried  and to even flash ESPHome again and to try the blank tft instead afterwards. This was when I was not even able to start the display flashing any more.

At some point, the display never came back to live again. On one occasion its backlight just flashed on and off, but nothing else.

Now the display is just dead, not even the flashing backlight. The rest of the panel is working though.

### ESP Log

I need to connect the panel to power to provide the log and the current report on the nextion display. I will do this this evening.

> [Placeholder for ESP Log file].

### Installed Tasmota and tried to flash from there

I then flashed Tasmota due to reports that its display-flashing implementation of nextion display works better. No difference.

I cannot remember the exact response from the Tasmota console but I will try again and paste it here.

[Update 14:27 CET+2]
I now took my lunch break to flash Tasmota back to the device, connect the display to the rest of it and and power it up via 5V. After setting up Tasmota, I ran `FlashNextion http://nspanel.pky.eu/lui-release.tft` with the following result:

```
00:00:00.002 HDW: ESP32-D0WD-V3 
00:00:00.046 UFS: FlashFS mounted with 288 kB free
00:00:00.077 CFG: Loaded from File, Count 10
00:00:00.086 QPC: Count 1
00:00:00.185 BRY: Berry initialized, RAM used=4438 bytes
00:00:00.202 TFS: File '.drvset003' not found
00:00:00.212 Project tasmota - Tasmota Version 13.1.0(tasmota32)-2_0_11(2023-08-15T08:00:54)
00:00:00.611 NXP: Initializing Driver
00:00:00.618 BRY: Successfully loaded 'autoexec.be'
00:00:01.246 WIF: Connecting to AP1 ***REDACTED*** Channel 1 BSSId 5C:49:79:D2:F3:57 in mode 11n as tasmota-FA6A70-2672...
00:00:04.040 WIF: Connected
00:00:04.301 HTP: Web server active on tasmota-FA6A70-2672 with IP address 10.0.12.81
13:24:51.194 RSL: INFO1 = {"Info1":{"Module":"NSPanel","Version":"13.1.0(tasmota32)","FallbackTopic":"cmnd/DVES_FA6A70_fb/","GroupTopic":"cmnd/tasmotas/"}}
13:24:51.209 RSL: INFO2 = {"Info2":{"WebServerMode":"Admin","Hostname":"tasmota-FA6A70-2672","IPAddress":"10.0.12.81","IP6Global":"","IP6Local":"fe80::c249:efff:fefa:6a70"}}
13:24:51.222 RSL: INFO3 = {"Info3":{"RestartReason":"Software reset CPU","BootCount":5}}
13:24:51.224 RSL: RESULT = {"POWER1":"OFF"}
13:24:51.236 RSL: POWER1 = OFF
13:24:51.237 RSL: RESULT = {"POWER2":"OFF"}
13:24:51.238 RSL: POWER2 = OFF
13:24:52.899 QPC: Reset
13:24:55.897 RSL: STATE = {"Time":"2023-08-30T13:24:55","Uptime":"0T00:00:10","UptimeSec":10,"Heap":103,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":194,"MqttCount":0,"Berry":{"HeapUsed":16,"Objects":217},"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"***REDACTED***","BSSId":"5C:49:79:D2:F3:57","Channel":1,"Mode":"11n","RSSI":100,"Signal":-45,"LinkCount":1,"Downtime":"0T00:00:05"}}
13:24:55.936 RSL: SENSOR = {"Time":"2023-08-30T13:24:55","ANALOG":{"Temperature1":29.4},"TempUnit":"C"}
13:25:35.146 CMD: FlashNextion http://nspanel.pky.eu/lui-release.tft
13:25:35.157 RSL: RESULT = {"FlashNextion":"Done"}
13:25:35.193 FLH: host: nspanel.pky.eu, port: 80, get: /lui-release.tft
13:29:55.897 RSL: STATE = {"Time":"2023-08-30T13:29:55","Uptime":"0T00:05:10","UptimeSec":310,"Heap":82,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":999,"MqttCount":0,"Berry":{"HeapUsed":21,"Objects":222},"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"Bundeskanzleramt","BSSId":"5C:49:79:D2:F3:57","Channel":1,"Mode":"11n","RSSI":100,"Signal":-47,"LinkCount":1,"Downtime":"0T00:00:05"}}
13:29:55.937 RSL: SENSOR = {"Time":"2023-08-30T13:29:55","ANALOG":{"Temperature1":29.9},"TempUnit":"C"}
13:34:44.891 APP: Serial logging disabled
13:34:55.897 RSL: STATE = {"Time":"2023-08-30T13:34:55","Uptime":"0T00:10:10","UptimeSec":610,"Heap":90,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":999,"MqttCount":0,"Berry":{"HeapUsed":21,"Objects":222},"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"Bundeskanzleramt","BSSId":"5C:49:79:D2:F3:57","Channel":1,"Mode":"11n","RSSI":100,"Signal":-50,"LinkCount":1,"Downtime":"0T00:00:05"}}
13:34:55.905 RSL: SENSOR = {"Time":"2023-08-30T13:34:55","ANALOG":{"Temperature1":30.0},"TempUnit":"C"}

```
Nothing happened afterwards, a couple of minutes later the console just echoed the STATE and SENSOR messages. No progress on the FlashNextion command.

### Connected the display to another working unit

I also connected only the display to another working unit and tried uploading the TFT, did not work either.

### Nextion Editor

I then tried the Nextion Editor, soldering the RX and TX to the corresponding pads as show in the uploaded image above and as discussed in #166 . Of course, I connected RX to RX and TX to TX as suggested for firmware flashing and ensured 5V supply and GND connection.

When htting the upload button, Nextion Editor just kept trying the ports but timed-out in the end. I tried this several times with several UART adadapters and it never worked. 

This is what I get from the Nextion Editor upon Upload to Nextion device:

```
Connection failed
Forced interrupt!
```
However, at least I now managed to connect, but the upload is till not working. See [my comment below (link)](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1000#issuecomment-1699087470).

**Comment by edwardtfn** [comment]
It sad to hear about your so far unsuccessful journey. It shouldn't be that hard to just upload a file to this displays.

Anyways, I saw on your pictures you disconnected the screen from the panel's board... Have you connected it back before trying to transfer the TFT?

**Comment by trinitrion** [comment]
> It sad to hear about your so far unsuccessful journey. It shouldn't be that hard to just upload a file to this displays.

No worries, I can approach this with a sporty attitude. At least I got another panel working right from the start. However, there I first installed Tasmota and flashed the blackmas panel tft from its console and then switched to ESPHome. Worked like a charme.

> Anyways, I saw on your pictures you disconnected the screen from the panel's board... Have you connected it back before trying to transfer the TFT?
Yes, I had everything connected when I tried to to transfer the TFT. Afterwards I disconnected the panel and stored everything in a box, just took the pictures this morning to illustrate the setup.

**Comment by trinitrion** [comment]
Just took the lunchbreak to give it another try with tasmota and flash nextion, please see the corresponding section in my initial post.

What should I do from here? Is there any way to show whether Tasmota at least sees the nextion or should I flash ESPHome and proceed from there?

**Comment by trinitrion** [comment]
Quick Update: 

Nextion Editor still shows the same as above:

<img width="442" alt="image" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/105319980/46ca56b6-bb24-44e7-9aac-48a0755e7204">

I have seen screenshots where the Editor would be showing the Upload progress (remaining file sizes and remaining estimated time). 

Here, it just stays at "Start Uploading", without any progress.

**Comment by edwardtfn** [comment]
Have you tried 9600bps?

**Comment by trinitrion** [comment]
Yes, tried that, no progress with 9600 baud either. 

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/105319980/fabf5ec1-5365-4f6d-a02c-997f37fc8d74)

**Comment by trinitrion** [comment]
Okay, can you maybe point me to a reliable source where I may finde the original firmware?

I guess I should try to return the unit as defect.

**Comment by edwardtfn** [comment]
Unfortunately I got out of ideas for this situation you are facing... 😩

I've posted about going back to stock firmware here: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/972#issuecomment-1673164989

**Comment by trinitrion** [comment]
Yeah, it also appears as if I reached the end of the internet with this issue. ;)

Somehow, the first flash via TFT update in ESP home has gone awfully wrong. 

Or there was something wrong with the whole unit from the start.

Thanks for looking into this.

I have now ordered a new unit.

**Comment by Doughboy68** [comment]
If you are adventurous, try installing the display of your working panel into the bad unit to see if it works. Depending if it works or not may indicate if it is an issue with the panel or the unit itself. Also can try the "bad" panel in a different unit to see if can flash it.
There is a chance that a bad panel may damage the display or vice-versa so keep this in mind.

**Comment by Kleinheribert** [comment]
> Normally, yes, when you want communication with the display. But when uploading firmware you want RX to RX and TX to TX.
> 
> And yes, I now have tried all selectable baud rates, that is how desperate I am. ;)

Sorry for my late reaction, what are you trying to do? Upload Firmware to the Display itself or to the ESP of the Panel?

**Comment by trinitrion** [comment]
> If you are adventurous, try installing the display of your working panel into the bad unit to see if it works. Depending if it works or not may indicate if it is an issue with the panel or the unit itself. Also can try the "bad" panel in a different unit to see if can flash it. There is a chance that a bad panel may damage the display or vice-versa so keep this in mind.

Excellent idea. Already tried the not working panel with the working board (no success though), but not the other way around. Will see whether I feel adventurous enough for this next week. ;)

I am still wondering whether you can actually brick the nextion panel with a flash gone wrong, as it appears this is what happened when I started the NSPANEL Update via the blueprint.

Found nothing about bricked nextion display.

**Comment by trinitrion** [comment]
> > Normally, yes, when you want communication with the display. But when uploading firmware you want RX to RX and TX to TX.
> > And yes, I now have tried all selectable baud rates, that is how desperate I am. ;)
> 
> Sorry for my late reaction, 
No worries, since I ordered a new unit, fixing this one has now become a hobby and less an urgency. ;)

> what are you trying to do? Upload Firmware to the Display itself or to the ESP of the Panel?

I tried both, when uploading the tft to the panel via esphome not worked and the display had gone black I tried directly uploading the firmware to the display itself via the two soldering pads.

In nextion editor, I now never get beyond this: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1000#issuecomment-1703850495

Googled around a lot and found no such experiences so far. However, I understand that nextion editor should display some kind of progress when uploading the new tft, right?

**Comment by edwardtfn** [comment]
> I am still wondering whether you can actually brick the nextion panel with a flash gone wrong, as it appears this is what happened when I started the NSPANEL Update via the blueprint.

I think this is very unlikely, however, when wiring for flashing there's always a risk of shortwiring things as the metal protection of Nextion is right behind the pins. 😩

> Found nothing about bricked nextion display excecpt for the advice to insert an SD-card (but where?!).

The screen is glued quite hard to the plastic, blocking the access to the place where the SD slot is supposed to be, so I've never seen that slot, but it should be there.

https://cdn.nextion.tech/wp-content/uploads/2017/09/3.5_Nextion_Dimension.pdf

**Comment by Kleinheribert** [comment]
You definitely need to use the Two solder pads to upload a firmware to the display controller itself. Tx to rx and Rx to tx.  Only the supply voltage over the mainboard itself.

**Comment by trinitrion** [comment]
Yes, that's what I did and where I get stuck in the upload process in nextion editor (see screenshots above). 


Anyways, ordered one of the cheaper black nspanels and will try to connect the new display to the old board to see what happens. 

Will keep you posted.
