### ISSUE TITLE
Feature Request: Climate set heating and cooling range. Set touch points for + and - further away from slider.

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#1006]
Define in blueprint min/max ranges for heating, cooling setpoints.

When pressing the - on nspanel climate page, I often press the touch screen and end up with a setting of 7.5C for example. With my Ecobee I can set the min/max setpoints so it will help solve this, but ability to set on NSPanel will allow other thermostats that may not have this protection. It looks like this is being done with the standalone thermostat modes, but is it possible to do on regular mode where nspanel is controlling a thermostat entity?

Also, please make a touchpoint gap between the slider and + - buttons, and maybe make them a bit vertically thicker than the slider itself so can touch a bit above the slider and they are more defined.

**Comment by edwardtfn** [comment]
The max/min temperatures used in the slider comes from the attributes from your climate entity. We have hard coded default values in case the climate entity doesn't include this info, and those are probably defined based in a heater, so it might need some improvement for coolers.

Are you asking for a way to override your climate settings or isn't your climate setting providing this info?

I try to avoid adding new inputs as much as possible. That is already too big. 😩

**Comment by edwardtfn** [comment]
I've played a bit with this. Please update your TFT and let me know your thoughts.

**Comment by Doughboy68** [comment]
May be a bit better now, its my fat fingers on the small touch points that is issue - when mounted on wall often I am looking a NSPanel from a light angle the way I stand and it is easy (for me anyways) to not hit the - key on left. Moving the buttons on a different vertical plane would help maybe but don't spend too much work redesigning this.

**Comment by fordcrews** [comment]
What would be really cool is when on climate screen, make the left hard button temp down, and right hard button temp up.

**Comment by fordcrews** [comment]
Well yes, guess it would confuse some, but as long as the labels changed.   Would be cool other places also.   Alarm panel they could set home/away when that is implemented.    Each of the button pages, it could give 2 more buttons allowing bigger icons with same number of buttons.     

None of my panels actually have anything hooked to the relays, I power the with 5v dc, don't have the relays even connected   I had an old intercom system running to every room that didn't work any more.   So I 3d printed a panel to hold a speaker, a small amp, and the ns panel.   And used the intercom wire to run 5v and audio to each.     Now I have whole home music, and cool little displays everywhere.  So I may not be normal use case.

**Comment by plasterer41** [comment]
Love that idea +1 from me 👍🏼Sent from my iPhoneOn 7 Sep 2023, at 18:48, fordcrews ***@***.***> wrote:﻿
What would be really cool is when on climate screen, make the left hard button temp down, and right hard button temp up.

**Comment by edwardtfn** [comment]
> guess it would confuse some

We could have a toggle in the Blueprint settings with something like "Adaptative Hardware buttons", so when enabled it will adapt to the page, otherwise (default) it would be a fix/global functionality.

**Comment by edwardtfn** [comment]
I'm not promising anything... 😉

**Comment by edwardtfn** [comment]
May I ask you to create anither isue/feature request specifically for that?

**Comment by edwardtfn** [comment]
#1014

**Comment by edwardtfn** [comment]
Duplicated: #909

**Comment by edwardtfn** [comment]
I've implemented this into `dev` and will be included in the next release soon.
Please feel free to try that before the release and give me some feedback.

**Comment by Doughboy68** [comment]
I installed dev on a test panel and button page icons are all messed up. Long press button (ie. light) does not bring up light page (hard button assigned to same entity works on long press).
On startup, panel shows all as 4.2dev4 
using esp-idf

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16811687/4ff00fe3-d547-47d7-956e-d136425f61b6)

**Comment by Doughboy68** [comment]
Oh and climate is also pretty broken for me.
The scale goes up very high for example I can set to 146.5 C
Don't think I need to set that high.. normal temp 21C is way over to left.
I am using Ecobee and has been pretty good until now.

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16811687/8a6b150d-47d1-4cd5-9e27-6341bea3bf72)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16811687/c12916a8-072f-4082-8b51-edcafe462bc5)
I also see no way to change to dual mode.. eg. here is screenshot from HA to set Heat/Cool
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16811687/6fccfdaf-6512-43df-86b0-8a33f3908bb1)

**Comment by Doughboy68** [comment]
Follow-up: I tried the landscape us tft and icons are correct looking... seems there is issue with the regular us tft.
But long press on buttons does not bring up the advanced entity page... eg. Fan, dimmable/rgb light etc.

**Comment by edwardtfn** [comment]
- #1556
