### ISSUE TITLE
DEV: ESPHome 2023.8.3 issue - RESOLVED

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#1008]
I updated one of my dev panels remotely from work. After update, I cannot connect to it. 

I can ping the IP, re-install with ESPHome, but still  does not respond or connect to Home Assistant (cannot switch relays for example). I also cannot access its web page interface (eg. direct IP, VISIT from ESPHome or access LOGS).

I updated another ESPHome device and works fine.

Not sure if this is related to dev version, or all version. Therefore recommend do others not update until looked into.
I will hard reboot when I get home and see if that fixes it.

**Comment by edwardtfn** [comment]
Fixed!
But you might have to power cycle your panel if re-flashing ESPHome isn't working. 😞 
Sorry for that.

**Comment by Doughboy68** [comment]
Ahh ok so this wasn't an ESPHome issue and was coincidence and I didn't notice an updated tft when updating panel.
Anyways thanks for fast fix!

**Comment by edwardtfn** [comment]
I still running some tests, but I have pushed a code that was failing if you flash ESPHome with an older TFT. It took me half an hour to detect the issue and come with a fix, but looks like ESPHome 2023.8.3 came at that exactly same time and you updated your system right away.

**Comment by edwardtfn** [comment]
I've then updated my system to ESPHome 2023.8.3 and after a quick test everything looks to be working fine.

**Comment by Doughboy68** [comment]
Yes mine seems to work now again. Actually rethinking now it was a big issue since how would one reflash new tft file then. Glad you found what was wrong.
