### ISSUE TITLE
Rename "turned on" into "pressed"

### ISSUE THREAD

**Issue by Rob65** [Blackymas/NSPanel_HA_Blueprint#1009]
It would be good to rename the trigger names that are exposed to HA in line with common names used.

Currently, an automation shows the triggers "Left Button turned on" and "Left Button turned off". These triggers are in fact "Button pressed" and "Button released".

For me, turn on/off relate to a state change (like turning a lamp on or off) and that made me believe these buttons have an on/off state like a toggle, whereas press and release refer to the actual action of pressing and releasing a button.

**Comment by edwardtfn** [comment]
This text is coming from Home Assistant, not from this project. As that is a sensor with two possible states, `on` or `off`, we are using the [Binary Sensor component from Home Assistant](https://www.home-assistant.io/integrations/binary_sensor/), which is the one defining the text shown on HA user's interface. And in fact, from HA point of view, that sensor is "turning on" or "turning off".
We can play with [Device Class](https://www.home-assistant.io/integrations/binary_sensor/#device-class) to find something that suit better your case, but we hardly will find something that fits to all.
Home Assistant have introduced an [Event entity](https://www.home-assistant.io/blog/2023/08/02/release-20238/#introducing-the-event-entity) a month ago and that was designed to help with this kind of case, so from our side, in v4.0 those buttons will generate `short_click` and `long_click` events (in addition to the sensor as it is today) and you will be able to play with this either in an Event entity or directly in your automation, although I don't think this will help in your specific case.

Why are using an external automation with that button as a trigger? Why not use the capabilities already existing in the Blueprint?
Maybe if I understand better your case I will be able to propose something.

**Comment by Rob65** [comment]
The button is used as an additional trigger for an already existing automation, so I was adding it as an additional trigger.
I could debate that using the button component might have been a better choice since it is a button. H.A. uses the names switch and button for stateless items that are pressed/released and do not have an on/off state. That would also allow the use of double click or long press.
But this has a high impact on existing installations so I guess it is best to leave it as is and close this issue

**Comment by edwardtfn** [comment]
> The button is used as an additional trigger for an already existing automation, so I was adding it as an additional trigger.

I got it. You know you can assign a scrip to the button in the blueprint and then the script will be triggered with the click of the button, right?

> I could debate that using the button component might have been a better choice since it is a button.

It could be, but then in this case it would be possible to press that button from Home Assistant, which might not be a problem really, and users will lose the info about the state of those buttons, which are user by some people to detect long press like in a dimmer control, which I don't think we could be done if using button component.
Also, we will have to think about how to deal with someone press the button on Home Assistant at the same time someone else is long pressing the physical button, etc.

> H.A. uses the names switch and button for stateless items that are pressed/released and do not have an on/off state.

Well, I agree about button, but for switches, they call the physical buttons as switches, which is stateless, but HA also have a switch component, and this on have a state (like `on`/`off` or `enabled`/`disabled`, etc.). Using that with physical buttons will have the same issue about how to replicate in the hardware a change made on HA (although this is a question only in the rare cases where both happens at the same time).
