### ISSUE TITLE
FR: Screen sleep after inactive

### ISSUE THREAD

**Issue by waltersenekal** [Blackymas/NSPanel_HA_Blueprint#1010]
Hi
I think it would be a nice feature if you could set the timeout for inactivity on the screen and then set the dim level so I can set it to dim to 0% after 3minutes of inactivity. Or a way to set sleep mode, so the screen can switch off during the nights/ predetermined times

Thanks
Walter

**Comment by edwardtfn** [comment]
Dimming time is hard coded right now, but sleep mode is available and you can set the screen timeout (when it will fall back to home page and then sleep).
These settings are under the device page in Home Assistant (Settings > Devices and Services > ESPHome).

**Comment by waltersenekal** [comment]
Hi

Thanks for letting me know, I have enabled sleep mode and it is working nicely for me.

Thanks for creating this component, it works so much better that the screens that I tried to design 😃

 

Best regards

Walter
