### ISSUE TITLE
DEV: Fan Page doesn't have all icons updated correctly when entering page.

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#1017]
If Fan is on  and going into fan page, the down button and off buttons are grayed out but still can be pressed. Once any button is pressed, all icons update correctly, but only for that page session. Exiting and going back in (ie. long press fan button) is same issue.

This is US Panel Portrait I am using.

**Comment by edwardtfn** [comment]
What about the slider? Is that showing correct value when you open the page?

**Comment by Doughboy68** [comment]
Yes. Here is a screenshot when it is in low and I enter. 
![IMG_0993](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16811687/38c400ad-f123-4472-937a-a4767e68eea9)

**Comment by Doughboy68** [comment]
Oh and if fan is on high the up button not grated out too
![Uploading image.jpg…]()

**Comment by edwardtfn** [comment]
Fixed.
You have to update the blueprint. No need to update TFT or ESPHome for this.

**Comment by Doughboy68** [comment]
Confirmed fixed. :)
