### ISSUE TITLE
DEV: Climate not showing fan or humidity modes with Ecobee thermostat

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#1019]
Been a while since I noticed this but my Ecobee has never shown these modes in thermostat page as selectable so thought I would report this.

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16811687/d4d48132-2fdd-417e-b864-a8f525c006d1)

Here is screenshot for HA where I can change these.

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16811687/8b073f69-d286-40eb-8eb0-594ea73b113e)

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16811687/0840a919-b2c7-4b38-84e0-7d110c965f1f)

Oh ignore those x and fan buttons on button of panel, was a workaround test to make fan turn on via entities.

**Comment by Doughboy68** [comment]
Maybe this is new feature in 2023.9, can't really remember now if old card was same LOL but would be nice to have this feature.

**Comment by edwardtfn** [comment]
I don't think this is a bug. Those buttons will reflect the HVAC modes, and looks right.

Looks like your climate also works as an humidifier, however that is not one of the climate entity supported modes (`dry` is supported 🤔 ).

Support for fan modes should be a new feature request (for the future, I want to release v4.0 asap). 😆 

Could you please add those as new feature requests?

**Comment by Doughboy68** [comment]
Ok, i also checked and there is an Eco+ mode I can enable that adjusts for humidity but I don't like eco+ since last time I enabled, the utility company was able to take control of my thermostat during peak power AC usage.
I will make a new feature request for the fan mode.

**Comment by edwardtfn** [comment]
Thanks a lot for all the tests you are running and giving feedback. :)

**Comment by edwardtfn** [comment]
I'm closing this one as we have #1021 for the feature request.
