### ISSUE TITLE
Translation into native language

### ISSUE THREAD

**Issue by pepe59** [Blackymas/NSPanel_HA_Blueprint#102]
What all needs to be translated so that the entire NSpanel is in my native language (Czech uses diacritics)?
I assume that the description of the screens in the HMI, the names in the yaml esp and the entire menu and names in the blueprint.
Or will there be an easier way?
Thank you

**Comment by Blackymas** [comment]
we need translation for

Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
Today
Tomorrow
in 2 Days
in 3 Days
in 4 Days
on
off
heat

**Comment by pepe59** [comment]
Here is the requested translation. Was that all that needed to be translated? If so, it was simple.

```
Monday     =  Pondělí
Tuesday    =  Úterý
Wednesday  =  Středa
Thursday   =  Čtvrtek
Friday     =  Pátek
Saturday   =  Sobota
Sunday     =  Neděle
Today      =  Dnes
Tomorrow   =  Zítra
in 2 Days  =  za 2 dny
in 3 Days  =  za 3 dny
in 4 Days  =  za 4 dny
on         =  zapnuto
off        =  vypnuto
heat       =  topení
```

**Comment by deku-m** [comment]
**Dutch:**

```
Monday     =  Maandag
Tuesday    =  Dinsdag
Wednesday  =  Woensdag
Thursday   =  Donderdag
Friday     =  Vrijdag
Saturday   =  Zaterdag
Sunday     =  Zondag
Today      =  Vandaag
Tomorrow   =  Morgen
in 2 Days  =  in 2 dagen
in 3 Days  =  in 3 dagen
in 4 Days  =  in 4 dagen
on         =  aan
off        =  uit
heat       =  verwarm
```

**Comment by Howardno** [comment]
Norwegian:

> Monday     =  Mandag
Tuesday    =  Tirsdag
Wednesday  =  Onsdag
Thursday   =  Torsdag
Friday     =  Fredag
Saturday   =  Lørdag
Sunday     =  Søndag
Today      =  I dag
Tomorrow   =  I morgen
in 2 Days  =  om 2 dager
in 3 Days  =  om 3 dager
in 4 Days  =  om 4 dager
on         =  på
off        =  av
heat       =  varme

**Comment by aferraz** [comment]
Italian

Monday = Lunedì
Tuesday = Martedì
Wednesday = Mercoledì
Thursday = Giovedì
Friday = Venerdì
Saturday = Sabato
Sunday = Domenica
Today = Oggi
Tomorrow = Domani
in 2 Days = in 2 giorni
in 3 Days = in 3 giorni
in 4 Days = in 4 giorni
on = on
off = off
heat = caldo

**Comment by quikote** [comment]
Spanish:

Monday = Lunes
Tuesday = Martes
Wednesday = Miércoles
Thursday = Jueves
Friday = Viernes
Saturday = Sábado
Sunday = Domingo
Today = Hoy
Tomorrow = Mañana
in 2 Days = en 2 días
in 3 Days = en 3 días
in 4 Days = en 4 días
on = on
off = off
heat = calor

**Comment by yoyanec** [comment]
**Slovak:**
```
Monday     =  Pondelok
Tuesday    =  Utorok
Wednesday  =  Streda
Thursday   =  Štvrtok
Friday     =  Piatok
Saturday   =  Sobota
Sunday     =  Nedeľa
Today      =  Dnes
Tomorrow   =  Zajtra
in 2 Days  =  o 2 dni
in 3 Days  =  o 3 dni
in 4 Days  =  o 4 dni
on         =  zapnuté
off        =  vypnuté
heat       =  kúrenie

**Comment by ffnystrom** [comment]
**Swedish:**
```
Monday	   = Måndag
Tuesday	   = Tisdag
Wednesday  = Onsdag
Thursday   = Torsdag
Friday     = Fredag
Saturday   = Lördag
Sunday     = Söndag
Today      = Idag
Tomorrow   = Imorgon
in 2 Days  = om 2 dagar
in 3 Days  = om 3 dagar
in 4 Days  = om 4 dagar
on         = på
off        = av
heat       = värme
```

**Comment by jrvrcd** [comment]
French

Monday	   = Lundi
Tuesday	   = Mardi
Wednesday  = Mercredi
Thursday   = Jeudi
Friday     = Vendredi
Saturday   = Samedi
Sunday     = Dimanche
Today      = Aujourd'hui
Tomorrow   = Demain
in 2 Days  = Dans 2 jours
in 3 Days  = Dans 3 jours
in 4 Days  = Dans 4 jours
on         = ON
off        = OFF
heat       = Chaleur

**Comment by edwardtfn** [comment]
Portuguese:

Monday = Segunda-feira
Tuesday = Terça-feira
Wednesday = Quarta-feira
Thursday = Quinta-feira
Friday = Sexta-feira
Saturday = Sábado
Sunday = Domingo
Today = Hoje
Tomorrow = Amanhã
in 2 Days = em 2 dias
in 3 Days = em 3 dias
in 4 Days = em 4 dias
on = ligar
off = desligar
heat = aquecer

*on/off can have different contexts:
When used to show status:
on = ligado
off = desligado
When used as an action:
on = ligar
off = desligar

*heat
Like in "heat" system/substantive: aquecimento
Action/verb: aquecer
Noum: calor

**Comment by Blackymas** [comment]
hi @ all

done in v2.2.0 https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.2.2.0

**Comment by WildeRNS** [comment]
Some modifications to Ukrainian translation (don't fit correctly):
in 2 Days = через 2 дні
in 3 Days = через 3 дні
in 4 Days = через 4 дні
on = увімк.
off = вимк.
heat = нагрів.

**Comment by Blackymas** [comment]
Hi - i will change it.

but it is best to create a new ticket for the next topic - otherwise it might get lost.
