### ISSUE TITLE
BUG (DEV): Long Press hardware button twice for light entity.

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#1022]
If I assign a light entity which has RGB, dim etc. to a hardware button, long pressing brings up the settings page. If I long press again before settings page times out, just shows another page with just a dimmer which doesn't do anything. This is non-critical, more of a cosmetic bug. 

Same with fan page, although page looks same buttons don't do anything to control actual fan.

Do not have a cover to test, presume probably same issue.

**Comment by edwardtfn** [comment]
The bug was fixed. You have to update all the 3 parts (ESPHome, Blueprint and TFT).
It wasn't a small change, hopefully I haven't broken anything else. Tomorrow I will clean up the code after these changes.

**Comment by Doughboy68** [comment]
Loaded on my test panel and seems to be fixed. I tested light entity and fan with hard buttons and they work as expected now.
I will try tomorrow when you clean up the code.
Will stop looking for more bugs so you can release 4.0 haha!

**Comment by edwardtfn** [comment]
> Will stop looking for more bugs so you can release 4.0 haha!

Please don't stop... 😂
This is not what is holding v4.0. We are still some people on vacations, so will wait a bit to have a "Go!" from all sides.

**Comment by edwardtfn** [comment]
Meanwhile...

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/bf8b0a3d-a121-4bdd-81dc-22515405f33f)

😉

**Comment by Doughboy68** [comment]
Ohhh is that making it in next version ?

**Comment by edwardtfn** [comment]
Yeah, I don't think it will be ready for v4.0. It's not on the top of my priorities as I wanna clean up the code before jumping on that Media Player.
