### ISSUE TITLE
After home assistant update / device power-on/off stuck on initial blue screen

### ISSUE THREAD

**Issue by beachie13** [Blackymas/NSPanel_HA_Blueprint#1025]
Device is stock on its initial blue screen after either updating home assistant or device/home assistant server was restarted. Shows IP address, TFT 3.3, ESPhome 3.4.1 and no reference to blueprint. Device relays are responsive via esphome and can update TFT from esphome.

**Comment by edwardtfn** [comment]
You got the latest ESPHome, but with an older TFT (and I bet an older Blueprint).
You shall go to GitHub and get the latest Blueprint and paste it into your Home Assistant, then reload automations.
For the TFT, download it, upload to your local server, and then press "Upload TFT" again.

**Comment by edwardtfn** [comment]
Hi @beachie13 , any progress with this?

**Comment by DozoG** [comment]
Hi Edward,

I have a similar problem. I have reloaded TFT (but just the old one as indicated in the yaml)
To say it short. My ESPHome is 4.0 but TFT 3.3 and Blueprint 3.3.
The NSPanel gets an IP address, it beeps and then starts the main page but keeps "loading" (never finish)

I have another NSPanel that works correctly with ESPHome4.0 , TFT3.3 and Blueprint3.3

I am ok to update, but is there a short update manual.
I found some new files but the YAML is far more complicated than the YAML that is currently running 

I have updated before but I think I am confused between how all the software hangs together between ESPHome yaml files, local and on GitHub and the blueprints.
There was also some confusion earlier with ESPHome telling me to enter a new api-key...  my yaml file did not have one, so I gave it a new one and re-uploaded.

**Comment by DozoG** [comment]
Ok.. I have downloaded the new nspanel_eu.tft file and placed it in the appropriate folder of my config.
It uploaded successfully to the NSPanel.
So now I have ESPHome 4.0, TFT 4.0 .

How do i get the new version of blueprint without losing all the entities I already configured in the old blueprint?
(If that is at all possible)

**Comment by DozoG** [comment]
Oh My.  I am so proud of you.. LoL (and a little proud of myself)
The procedure is a little complicated because I don't really understand how the versions interact .. etc etc

And a little more complicated because i have two NSPanels (so  have to be careful to update everything with its own panel name (not the default names)

But it works again .. Thank you for all the effort you put into this
