### ISSUE TITLE
Regenerate .tft files for new Nextion display revision

### ISSUE THREAD

**Issue by johnkozan** [Blackymas/NSPanel_HA_Blueprint#1028]
I recently purchased an NSPanel and flashed the NSPanel_HA_Blueprint firmware.

But when I attempted to flash the display with the .tft file, the screen displayed the error:

```
Model does not match
Device Model:
NX4832F035_011C
```

Thinking this might be a new revision of the display (revision C?), I download the Nextion editor, imported the .HMI file and re-exported the .tft.

Uploading the new .tft file was successful.

**Comment by edwardtfn** [comment]
Thanks for sharing your journey.
In the end, is everything working fine now?

**Comment by johnkozan** [comment]
Hi, Thanks, Yes everything worked great once I regenerated the .tft file using the Nextion editor.

**Comment by edwardtfn** [comment]
v4.0 (now in `beta`) will replace all the `tft` files by new ones, built with latest Nextion editor.

**Comment by SmartHomeAu** [comment]
I am getting the same error.. "Model does not match". I am using the latest V4 (now not in Beta).  Any ideas?

**Comment by edwardtfn** [comment]
1. Have you tried transferring `nspanel_blank.tft` and then the big file again?
2. What about power cycle the device?
3. Flash ESPHome again
