### ISSUE TITLE
fresh installation 3.4, but no buttons on home page visible & working

### ISSUE THREAD

**Issue by okionka** [Blackymas/NSPanel_HA_Blueprint#1034]
On a fresh installation (TFT 3.4, ESPHome 3.4.1, Blueprint 3.4) i figured out following strange things:
* the 7 Buttons on home page can't be configured via blueprint 3.4. the related documentation here is outdated and shows other configuration items in Blueprint as I can see.
* the settings button only works every second time.
* disabling the upper left icons on home page via changing the configuration in blueprint don't work. as workaround, only updating firmware via ESP OTA hides the icons again.

**Comment by edwardtfn** [comment]
> On a fresh installation (TFT 3.4, ESPHome 3.4.1, Blueprint 3.4)

Nice. Welcome! 😃 
The harder part was gone.

> the 7 Buttons on home page can't be configured via blueprint 3.4.

Currently, 3 of those buttons are implemented:
- Notifications: You have to call service `esphome.xxxxx_show_notification` to send a notification to your panel, then the icon will be visible until the notification is cleared.
- Entities: There's a toggle in the blueprint settings to enable the entities pages. That will enable the button on the Home page.
- QRcode: Also a toggle on the blueprint settings.

With version 4.0 (coming soon), you will be able to set an Alarm entity into the blueprint settings and that will be the 4th "fix" button. You will also have 3 additional custom buttons, for which you can assign an entity and by click in the button the entity page will be shown.

> the related documentation here is outdated and shows other configuration items in Blueprint as I can see.

It's an open source project where we invest our free time and we will love if you add a PR or at least a issue if you find something wrong. 😉 

> the settings button only works every second time.

I'm not sure what you mean here. We don't have a settings button anymore, and the settings page is opened by a long click on the time area.
Isn't that working properly?

> disabling the upper left icons on home page via changing the configuration in blueprint don't work. as workaround, only updating firmware via ESP OTA hides the icons again.

Again, I'm not sure if I got which icons you are talking about.
Could you please share some picture?

**Comment by Doughboy68** [comment]
> With version 4.0 (coming soon), you will be able to set an Alarm entity into the blueprint settings and that will be the 4th "fix" button. You will also have 3 additional custom buttons, for which you can assign an entity and by click in the button the entity page will be shown.
> 
Is it possible to make these custom buttons be assigned to more entity type like regular buttons? I would like to be able to call a script for example. I can type in the entity and it takes, but I am not at home now to see if it actually shows up on panel and works. This could actually solve my other request in the meantime for custom buttons on alarm page and I could use these buttons for bypass, jumping to an entity screen showing zone status etc. (still would like custom buttons on alarm page though).

**Comment by edwardtfn** [comment]
> Is it possible to make these custom buttons be assigned to more entity type like regular buttons?

Yes, it is possible, but I'm afraid this could look odd, as those 3 buttons will have a different behavior when compared to other buttons on that page (always opening another page).
And I don't wanna to implement more complex thing (change colors, etc.). At least not right now as this could increase complexity and delay with v4.0.
But it is possible.

**Comment by Doughboy68** [comment]
That is fine, as long as I can trigger a script or something I don't care about them updating colors for that purpose. I was going to attempt to make a script to open a button page or one of the entity list pages anyways that contained my alarm bypasses... wonder if this would make sense to have an option for those buttons as shortcuts to direct button/entity pages? Maybe there is room elsewhere on home page to do this for these shortcut buttons instead of using these buttons?

I think I understand the purpose of those buttons now, I will experiment with them later when at home.

**Comment by edwardtfn** [comment]
Add a button page to that makes sense... It would be odd in the Blueprint settings, but the behavior (opening a page) will be consistent.
I will think about it.
By the way, is climate working for you?
I want to wrap up for a release.

**Comment by Doughboy68** [comment]
> Add a button page to that makes sense... It would be odd in the Blueprint settings, but the behavior (opening a page) will be consistent. I will think about it. By the way, is climate working for you? I want to wrap up for a release.

Climate was working last time I checked, but I only use with my ecobee and a zwave thermostat that only is set for heat and controls a gas fireplace. I do not use the local climate feature if that is what you are asking. I will confirm climate later when home. in a few hours and make sure I download all current files to my test panel.

**Comment by Doughboy68** [comment]
I will answer here quickly that pressing the temperature on home screen launches a blank climate screen.
If I assign my climate entity to a button on a button screen, then long pressing it works.

**Comment by edwardtfn** [comment]
Could you please update your system and try again?

**Comment by Doughboy68** [comment]
One minor issue, relating to the new three custom buttons on home page. It is possible to put a fan or a light that does not have any controls that would bring up an entity page on one of those buttons, then the button does nothing. Probably difficult to resolve and prevent someone from putting this in there, so I suggest simply make it clearer in the instructions that these are designed to work for entities that have entity pages. For example, I have some switch entities that control on/off ceiling fans and I am able to place in those buttons, which do nothing, but my ceiling fan that has speed controls works.

And I tried script and does not call the script, (which is not surprising because it tries to call a page)

**Comment by edwardtfn** [comment]
I'm thinking about this and maybe it would be easier to support all the elements supported in other buttons... But that will require some rework. I will try to find some time later today.

**Comment by edwardtfn** [comment]
I put some words about this on the Release Notes, but probably not enough.

https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/dev/ReleaseNotes.md#16-custom-buttons-on-home-page

**Comment by edwardtfn** [comment]
Investigating a bit more, I can filter the entities based on the supported features, except by lights, where the info used is on `supported_color_modes` instead. 😞

**Comment by Doughboy68** [comment]
Those notes look enough.. I was meaning also the notes in the blueprint section as well where you configure the buttons could have an additional note that only functional with those entities supporting advanced settings.

**Comment by edwardtfn** [comment]
I've just pushed a change extending the supported domains (and including script 😉 ).

Please let me know your thoughts and if it is working fine, as I couldn't test now.

**Comment by Doughboy68** [comment]
Ok, I will load it up and test when home.

**Comment by Doughboy68** [comment]
one more thing if possible and you have time, could you make the media player delay currently 10 seconds adjustable? I would like to try different timings eg. 5 seconds, 3 seconds etc. to see if performs better.  I could probably just paste in the entire yaml but this would be quicker to make changes.

**Comment by edwardtfn** [comment]
I've added that. You have to update your blueprint and you will see the settings at the very end.
Unfortunately I couldn't test yet, but please let me know if you find better settings.
I've done some clean-up on duplicated calls to update, which was probably just spamming the system, so hopefully that also helps.

By the way, the 10s is not a delay to call for actions, it is a refresh interval for that page. Unless I've made some mistake. 😆 
I've added also an input for a delay that comes right after the call to update the entities. That delay could affect the page load, but is was 500msec only.

Please let me know your findings.

**Comment by Doughboy68** [comment]
Yes sorry my description is not exact. The refresh interval of 10 seconds is what I was referring to which I wanted quicker.
I will test this shortly and let you know.

**Comment by Doughboy68** [comment]
I tested it and media player update interval set to 3000 milliseconds seems a much better experience for me and when I press play, stop, skip track etc. it updates much nicer.

I did however notice a bug when on the media player that the page timeout does not seem to reset on every press.. I can test this easily by setting the page dim less than the time out and I have to spam-press the panel (tapping repeatedly) until it goes to regular brightness. If I was to guess, it is either not registering keypresses during the update interval, or only for a brief time after the update interval (hard to tell which but you should be able to figure out in the code). 

I tested the custom buttons and they work fine with switches, scripts, and show the page with other ones... light, fan, climate I tested. I would save anything else for the next version (eg. maybe colors, confirmation etc.).

A serious bug though is I cannot arm/disarm alarm anymore via nspanel. It does update correctly in nspanel when armed/disarmed via HA.

**Comment by edwardtfn** [comment]
It's out for `beta` now: #1046

**Comment by edwardtfn** [comment]
I'm closing this as the topic was "hijacked". 😆 
@okionka, could you please open another issue in case you still having trouble?
