### ISSUE TITLE
DEV: Climate page not launching correctly home screen.

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#1036]
Latest Dev update.
Cannot launch climate page from home screen. When pressing the temperature, it launches climate screen with no values.
Same climate entity works if launched from a button screen button, or one of the three home page cutom buttons (You should update blueprint docs to indicate that climate entities also work on these buttons also).

**Comment by edwardtfn** [comment]
Could you please update your system and try again?

**Comment by edwardtfn** [comment]
I've added some additional log on ESPHome, so if it still failing, could you please send me some logs?

**Comment by Doughboy68** [comment]
Working now. Can can mark as closed.
