### ISSUE TITLE
DEV: Sleep time issue

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#1037]
Latest Dev version.
Sleep is handled differently now. Was changing my automation to put panel to sleep at night.

Setting number.nspanelxx_timeout_sleep  to a value of 0 disables sleep and wakes up panel, even if panel is idle/not used. This is expected.

Setting number.nspanelxx_timeout_sleep to a value >0 (eg 5 seconds)  does not sleep the panel unless the panel is operated manually eg. screen touched, or the sleep time is changed to another value>0 or same value again.

For example:
If not touching panel at all...

set timeout sleep to 0
panel stays on or wakes up instantly if asleep
set timeout sleep to 5
panel stays awake doesn't sleep
set timeout sleep to 5 again
panel sleeps after the set amount of seconds (eg. 5)

**Comment by edwardtfn** [comment]
Could you please update ESPHome and try again?

**Comment by Doughboy68** [comment]
Seems to be working as expected now.
Can mark this as resolved.
