### ISSUE TITLE
`DEV` Alarm panel commands do not work from NSPanel

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#1039]
Latest update... cannot arm or disarm alarm with NSPanel.
Alarm icons on home screen and panel do update colors etc. when alarm is armed/disarmed externally via home assistant.

**Comment by edwardtfn** [comment]
Fixed!
You have to update ESPHome.

**Comment by Doughboy68** [comment]
Confirm is fixed.
