### ISSUE TITLE
Alarm Panel

### ISSUE THREAD

**Issue by fastender** [Blackymas/NSPanel_HA_Blueprint#104]
Great expansion. I congratulate you on your work. 

Will there also be an extension for the alarm system?

**Comment by Blackymas** [comment]
yes we have thought about it but is not yet on the roadmap

**Comment by quikote** [comment]
+1
Please, make it compatible with Alarmo addon.
Congratulations for this really nice project

**Comment by fugazzy** [comment]
I would like to see this feature also, as it is essential at the position, where my panel ist installed.

**Comment by formatBCE** [comment]
+1 for this, Alarmo is great, and i would use this Blueprint for it no doubt.

**Comment by robgough1970** [comment]
another +1 for alarmo - this is a perfect device for this use case. Great work - loving it so far... 12 months waiting for an easy to impliment interface for these panels. You have enabled me to take them out of the drawer and get them on the wall!

**Comment by phaeton82** [comment]
Using Alarmo as well. This device is very suitable to replace my ugly alarm panel. So following this thread with anticipation. I have both eu and us nspanels

**Comment by xcentric7881** [comment]
+1 for supporting a keypad to disable alarm

**Comment by Fonzie66** [comment]
Great work so far! Another +1 for the Alarmo integration.

**Comment by Blackymas** [comment]
The feature is on the roadmap and we are working on it.

I'm closing the ticket that there is already another ticket about it.

Look here

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/66
