### ISSUE TITLE
`DEV` Media player time out not updating

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#1040]
Media player page timeout, dim timeout etc. does not get reset when pressing panel or buttons all the time, so the page will dim or exit even though may have recently pressed the panel.

Seems that this is related to the Media player update interval not recognizing keypress during this time.

**Comment by edwardtfn** [comment]
I've just pushed an update that hopefully will help with that.
You will have to update ESPHome. No need to update other components this time.

**Comment by Doughboy68** [comment]
Your update seems to have fixed the issue.

**Comment by Doughboy68** [comment]
I also tested everything else I could think of and nothing seems broken. The color change indicators on Home Screen is nice. 

Seems almost ready for release.
