### ISSUE TITLE
indoor temperature

### ISSUE THREAD

**Issue by lecrams** [Blackymas/NSPanel_HA_Blueprint#105]
Feature request: allow the display of a configurable temperature sensor instead of the NSpanel temperature.
NSpanel temperature is not the actual room temperature as the case is heated up

**Comment by Blackymas** [comment]
You have the possibility to make a Temp correction.

Go to Devices -> ESPhome Devices.

The temperature correction is not only a correction for the display but also rewrites the system value.

![Bildschirmfoto 2022-12-13 um 08 40 45](https://user-images.githubusercontent.com/41958506/207255361-66c3f036-3765-49dd-99f0-0731e97e66c1.png)

**Comment by lecrams** [comment]
That is a possibility however it doesn't solve it as the housing temperature changes depending on external conditions and the load of the panel. Therefor allow selecting an alternative sensor is imo the best solution

**Comment by Blackymas** [comment]
I cannot confirm this. I have 5 NSpanel here in the house and with the temp correction run all perfect.

Yes there is now and then times 0.2 degrees difference. The difference I have but with all other measurement units also.

I write it on my list but so far no one else has described a similar problem.

Therefore, other topics currently have priority. 

But as I said I have noted it
