### ISSUE TITLE
On screen notifications

### ISSUE THREAD

**Issue by VanFlipsen** [Blackymas/NSPanel_HA_Blueprint#106]
Feature request:

Is it possible to get fullscreen notifications on the screen. With rttl sound/music. Or a part of the screen just like it is already integrated in the lovelace-ui version from joBr99. 

Use cases from home assistant.
- Washing machine is done
- Tomorrow/today garbage container
- Etc.

**Comment by Blackymas** [comment]
Hello,

sktuell no but is already on the rodmap and should not be a problem.

I laben your request immediately with roadmap.

The problem is rather that we have 100 ideas but do not know what is the best variant.


Can you briefly describe what your ideas are or how it is with lovelace -ui

**Comment by VanFlipsen** [comment]
Copy paste from another page.[sairon](https://github.com/sairon/esphome-nspanel-lovelace-ui) 

notify_on_screensaver: show a notification on the screensaver with 2 lines, it can receive both lines. The notification will disappear when you tap on the screensaver
notify_fullscreen: show a full-screen notification with title description and 2 buttons, and it plays a sound on the buzzer. The buttons are not actionable yet.


Both as a send as service 
- both playing a short rttl sound
- fullscreen version got a Timer (seconds before automatically disappearing)
- without buttons is just fine

**Comment by w00ter** [comment]
Would absolutely love this feature. 

An added bonus to the notification would be to include an image or thumbnail so that it may also show a person standing at the front-door when a doorbell press is triggered.

**Comment by Blackymas** [comment]
short update - we are already working on it and will be available in the next update 2.3.0 :)

**Comment by w00ter** [comment]
> short update - we are already working on it and will be available in the next update 2.3.0 :)

SWEET!!

**Comment by Blackymas** [comment]
hi @ all

added in https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.0.0

**Comment by MarkuZP** [comment]
![Bildschirm­foto 2023-01-19 um 22 51 53](https://user-images.githubusercontent.com/109298227/213571306-f909534c-cecf-4231-903b-2985d0283e36.jpg)
