### ISSUE TITLE
Media Player not displaying information.

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#1062]
Didn't notice  this before release due to tz differences and busy last couple days. 

It does control the player, just no updates on screen.
Here is log.

2023-09-20 19:54:07.181 ERROR (MainThread) [homeassistant.components.automation.nspanel_05_configuration] NSPanel 05 Configuration: Main choices: NSPanel event: Choose at step 2: Page changed: Error executing script. Invalid data for choose at pos 1: required key not provided @ data['media_position_delta']
2023-09-20 19:54:07.184 ERROR (MainThread) [homeassistant.components.automation.nspanel_05_configuration] NSPanel 05 Configuration: Main choices: NSPanel event: Error executing script. Invalid data for choose at pos 2: required key not provided @ data['media_position_delta']
2023-09-20 19:54:07.187 ERROR (MainThread) [homeassistant.components.automation.nspanel_05_configuration] NSPanel 05 Configuration: Error executing script. Invalid data for choose at pos 1: required key not provided @ data['media_position_delta']
2023-09-20 19:54:07.196 ERROR (MainThread) [homeassistant.components.automation.nspanel_05_configuration] Error while executing automation automation.nspanel_05_configuration: required key not provided @ data['media_position_delta']

volume_level: 0.1
media_content_type: music
media_duration: 404
media_position: 46
media_position_updated_at: '2023-09-21T02:54:17.343272+00:00'
media_title: Shine Away
media_artist: Tesla
media_album_name: Bust a Nut
app_id: com.apple.Music
app_name: AirMusic
shuffle: true
repeat: 'off'
entity_picture: >-
  /api/media_player_proxy/media_player.homepod_family_room?token=cbead821eblabladeleted
friendly_name: HomePod Family Room
supported_features: 448439

**Comment by edwardtfn** [comment]
Looks like you don't have the latest Blueprint. Could you please double check?

**Comment by Doughboy68** [comment]
I just recompiled esphome, copied over blueprint again and updated tft.
Restarted panel, restarted HA.

I get this error now.

Logger: homeassistant.components.automation.nspanel_05_configuration
Source: helpers/script.py:420
Integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 9:19:29 PM (1 occurrences)
Last logged: 9:19:29 PM

NSPanel 05 Configuration: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Media player settings page: Refresh page in a loop: Error executing script. Error for call_service at pos 4: Error rendering data template: ValueError: Template error: as_timestamp got invalid input 'None' when rendering template '{{ (now() | as_timestamp - media_player.media_position_updated_at | as_timestamp | default(now() | as_timestamp)) }}' but no default was specified

**Comment by Doughboy68** [comment]
Ok, I just played it from HA, was showing blank there, now seems to work. Maybe was in a weird state where HA was not updated correctly from apple homepod which caused this. Something to debug further probably. Will keep an eye open on this.

**Comment by edwardtfn** [comment]
I will try to replicate this issue here and let you know.

**Comment by Doughboy68** [comment]
Ok Just got it in that state again after restarting HA and when I press play in NSPanel it works now. So not sure, maybe was just a weird combination that caused this. But I never remember seeing it with just the play button before like this.

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16811687/34744ef8-c644-434d-ad24-a03c78a559f1)

**Comment by edwardtfn** [comment]
I think it could happen.
The error before is related to your media player entity not providing the duration of a media. I'm sure this will happen from time to time and the Blueprint should handle that situation nicely and not crash.
It's probably am easy fix, but then will require all the painful release e process again. 😩

**Comment by Doughboy68** [comment]
I will download that blueprint and try on all my panels... doesn't appear anything else significantly changed.
Will let you know if resolves.

**Comment by edwardtfn** [comment]
It is available for testing on beta: https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1046#discussioncomment-7093668

I will wait for some feedback and then go to the release.
