### ISSUE TITLE
Incomplete update instructions [EN]

### ISSUE THREAD

**Issue by Rob65** [Blackymas/NSPanel_HA_Blueprint#1064]
I think the update instructions are incomplete.
In step 3 "Update ESPHome", the English version tells I have to click on "Update all" but there is no such item in the ESPHome integration.
The German version has better instructions and it would be enough to add the following to the English instructions for me to correctly update the panel:

`In the ESPHome integration, Validate the integration for your panel. When done, a green tick mark will show at the top of the page. After this click on Install and install the new ESPHome version in the panel using your preferred method (which is most likely wireless)
`

In step 4 "Update TFT" instructions are missing to manually upload the new .tft file to the www folder
That got me confused for a few minutes since just updating the update TFT button of course updates to the same old version.

**Comment by edwardtfn** [comment]
Thanks for catching that.
I've done a quick update to the instructions as many people might be looking at that now with the new release, but will come back to that later.
Please take a look and let me know your thoughts.
https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#3-update-esphome

**Comment by Rob65** [comment]
Wow, that's a nice piece of work.
Looks very good
