### ISSUE TITLE
Feature Request: Screensaver customization

### ISSUE THREAD

**Issue by Jimmyboy83** [Blackymas/NSPanel_HA_Blueprint#1065]
Hi!
Thank You for this awesome work!!!
It will be cool to add customization to screensaver. Not just screen off, but some information, like time or outside temperature.
I have tried to add time to screensaver page in Nextion Editor (copy from home page),  but it only left blank rectangle without time
I have also edited dimming settings for screensaver page, added int brightness=100,brightness_dim=40 and replace font 6 with bigger one

Can You help me with time object on screensaver?

**Comment by Jimmyboy83** [comment]
I added timer on screensaver page and event trigger screensaver.clock.txt=home.time.txt 
It didn't work

**Comment by edwardtfn** [comment]
Do you have any error message?
Is the timer enabled?
On attributes, make sure `en` is 1.

**Comment by Jimmyboy83** [comment]
Error in esphome logs? when enable screensaver:

19:07:02][E][nextion:535]: ERROR: Received numeric return but next in queue "set_component_value" is not a valid sensor type 0
[19:07:02][E][nextion:260]: Nextion queue is empty!
[19:07:02][W][component:204]: Component nextion.display took a long time for an operation (0.10 s).
[19:07:02][W][component:205]: Components should block for at most 20-30ms.
[19:07:12][W][nextion:345]: Nextion reported picture ID invalid!

Timer is enabled

**Comment by edwardtfn** [comment]
Do you mind sharing your HMI file or an export of page screensaver?

**Comment by Jimmyboy83** [comment]
It doesn't matter now, after updating esphome to latest version tft file update again starts freeze at 23%
Cleanup build files did not help :-)

**Comment by edwardtfn** [comment]
Sounds like this one: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1061#issue-1905619363

**Comment by Jimmyboy83** [comment]
After several attempts, and alternation between blank and nspanel files, it works again (no logic)
I upload my hmi and page files to github
https://github.com/Jimmyboy83/nspanel/

**Comment by plasterer41** [comment]
Really cool idea. +1 from me 👍🏼Sent from my iPadOn 21 Sep 2023, at 12:02, Jimmyboy83 ***@***.***> wrote:﻿
Hi!
Thank You for this awesome work!!!
It will be cool to add customization to screensaver. Not just screen off, but some information, like time or outside temperature.
I have tried to add time to screensaver page in Nextion Editor (copy from home page),  but it only left blank rectangle without time
I have also edited dimming settings for screensaver page, added int brightness=100,brightness_dim=40 and replace font 6 with bigger one
Can You help me with time object on screensaver?

**Comment by edwardtfn** [comment]
Please take a look: https://github.com/Jimmyboy83/nspanel/pull/1

**Comment by Jimmyboy83** [comment]
![IMG_20230921_223547](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/90217866/b35f481c-d4b9-4409-ac95-fc94ef6506cc)
Looks great, 176 bold ubuntu don't
Make it configurable and add as a feature!

**Comment by Jimmyboy83** [comment]
Maybe outdoor temperature sensor will be good to add.

**Comment by Jimmyboy83** [comment]
Thank You!!!

**Comment by Jimmyboy83** [comment]
The panel is on the bedside table and at night my wife can't see small text without glasses. Time and temperature outside, that's all she need at night and in the morning. 
I planned to turn on the screensaver mode at night through automation, but in version 4 the mechanism has changed and now it's not very convenient to do it

**Comment by ondras76** [comment]
Hello, can you tell me how can I switch-off the screensaver? Thank you.

**Comment by edwardtfn** [comment]
Set Timeout Sleep to 0s.

**Comment by Jimmyboy83** [comment]
Hi!
Everything working fine, and i bought second NSPanel personally for myself.
There are two little questions:
1. For updating to new version of tft is enough to simply import home and screensaver pages in new HMI from my config and upload it to panel?
2. Can you add refreshing of outdoor sensor on home page fo using it on screensaver page. I have added it on screensaver page like home.time.txt  and in timer, but it only updates on start of screensaver

**Comment by edwardtfn** [comment]
> For updating to new version of tft is enough to simply import home and screensaver pages in new HMI from my config and upload it to panel?

It should be. The Home page can be a bit more complex, as the changes of we changing something in an update are quite big, so maybe you want to just adjust your changes again (based on what changed).
GitHub offers quite nice tools to see what changed from one version to other, so you might have to take a look at that on each release:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/3231a1a0-dfdf-4985-a4b1-40a63b446e88)

For the screensaver page, the chances of a change from our side are really low, so you probably will be good.

Just make sure you don't change page's names and pages ids, as we use those in the code.

**Comment by edwardtfn** [comment]
> 2\. Can you add refreshing of outdoor sensor on home page fo using it on screensaver page. I have added it on screensaver page like home.time.txt  and in timer, but it only updates on start of screensaver

I've added that change to `dev`. It would be included in the next release.

**Comment by Jimmyboy83** [comment]
Thank you!
I've already use your fix.  It work even on version 4.0.
Replacing screensaver page also works fine, on home page I made only some cosmetics changes, so I can edit it again. 
Cannot find how export import txt files :-)

**Comment by edwardtfn** [comment]
> Cannot find how export import txt files :-)

We use this: https://github.com/MMMZZZZ/Nextion2Text

**Comment by thstorm** [comment]
> Set Timeout Sleep to 0s.

Can you tell me where to set this?
Can't find it in the blueprint, do I have to set it in esphome?

**Comment by edwardtfn** [comment]
On Home Assistant, under Settings > Devices and Services > ESPHome.

**Comment by edwardtfn** [comment]
- #1556
