### ISSUE TITLE
timezone is not considered in 4.0v

### ISSUE THREAD

**Issue by leranp** [Blackymas/NSPanel_HA_Blueprint#1067]
Hi,

Thanks for this project,
The new version 4.0 have a problem with the clock time, it takes the clock from HA without the timezone.
I had to add the line for timezone same like in this doc https://esphome.io/components/time/

**Comment by edwardtfn** [comment]
Good point...

Until v3.4 (including), the time was coming from Home Assistant with it's timezone, so the Blueprint was sending the info with no transformation, to the panel.
From v4.0, the time reference still coming from HA (or optionally from a time server), but is calculated in ESPHome, which will try to detect the timezone from the server.
If your system is not showing the time in the correct timezone, it's probabily ESPHome not succeeding on finding your time zone.
You can easily force a timezone by adding this to your ESPHome settings:

```yaml
time:
  - id:!extend time_provider
    timezone: "America/Cancun"
```

I will add this to the customizations instruction.

**Comment by leranp** [comment]
This is exactly what i did to handle the wrong time on my panel 🤣

**Comment by edwardtfn** [comment]
I've added this to the customizations instructions which will be included in the next release.
