### ISSUE TITLE
No Current Page sensor available

### ISSUE THREAD

**Issue by Lama131** [Blackymas/NSPanel_HA_Blueprint#1069]
I just updated to version 4.

After updating all files i got a blueprint error.
_The sensor "Current Page" (sensor.wandpaneel_current_page) is unavailable._

I can't find the sensor anywhere in the list of the device.
I have allready reinstalled the blueprint, the ESPhome add-on and the ESPhome firmware

![Schermafbeelding 2023-09-21 194847](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/137107243/4b5ccd04-a33c-416c-a1d4-fff734db6bec)

![Schermafbeelding 2023-09-21 195004](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/137107243/a7f8d613-13ed-4bd4-b8b7-1df36a12598e)

![Schermafbeelding 2023-09-21 195020](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/137107243/298b4e62-bdf0-4d65-b624-63e289e8b9ce)

I'm using ESP version 2023.8.3 
Home assistant version:
supervisor: 2023.09.2
Operating System: 10.5

NSpanel Automation:

alias: NSPanel Slaapkamer
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: 058abecaac6babc06fc294efda819659
    language: nl
    left_button_name: Aan/Uit
    right_button_name: Scene
    indoortemp: sensor.slaapkamer_temperatuur_temperature
    chip01_icon: mdi:window-open
    left_button_hold_custom_action: []
    left_button_hold_select: Default
    entity01: light.slaapkamer_1
    entity02: light.slaapkamer_2
    entity04: light.slaapkamer
    entity04_name: Alle Lampen
    entities_entity01: light.slaapkamer
    entitypages_enabled: false
    home_value01: sensor.slaapkamer_temperatuur_humidity
    home_value02: sensor.current_power_usage
    home_value01_icon: mdi:water-percent
    home_value02_icon: mdi:lightning-bolt
    chip02_icon: ""
    climate_value01_icon: mdi:lightning-bolt
    home_button05_icon: ""
    qrcode_enabled: true
    qrcode_label: Wifi
    qrcode_value: WIFI:T:WPA;S:Michiel de Router;P:Focus2020;;
    relay_1_local_fallback: true
    left_button_entity: light.slaapkamer
    right_button_entity: script.1691646017362
    climate: climate.airco_slaapkamer
    entity02_icon: ""
    entity03: light.slaapkamer_3
    chip05_icon: ""
    entity02_name: Bed
    entity03_name: Schilderij
    entity01_name: Kast
    entity05: scene.slaapkamer_laag
    entity05_name: Zacht
    entity05_icon: mdi:bed-king-outline
    entity06: scene.slaapkamer_hoog
    entity06_name: Fel
    entity06_icon: mdi:bed-king
    entity01_icon: ""
    climate_value02_icon: ""
    climate_button08_icon: mdi:speedometer-slow
    weather_entity: weather.buienradar
    climate_button09: input_boolean.airco_auto
    climate_button09_icon: mdi:fan-auto
    climate_value04_icon: ""
    climate_button08: input_boolean.airco_laag
    climate_value01: sensor.airco_slaapkamer_energy_current
    hold_delay: 3
    chip03_icon: ""
    button_page01_label: Lampen
    show_while_loading: false
    chip01: binary_sensor.raam_slaapkamer_opening
    entity26_icon: ""
    date_format: "%A, %d/%m"
    home_custom_button01: media_player.slaapkamer

**Comment by edwardtfn** [comment]
Take a look at your device's page (Settings > Devices & Services > ESPHome) and look for "Entities not shown" in the "Sensor" area:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/f6ddc3f1-4bc2-4994-a5b7-00ce69f730ea)

It's probably there.

Those are the entities disabled. You have to enable that sensor.

**Comment by edwardtfn** [comment]
> ![Schermafbeelding 2023-09-21 195020](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/137107243/298b4e62-bdf0-4d65-b624-63e289e8b9ce)

This message is related to a different error. Looks like you haven't updated the ESPHome part.

https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#3-update-esphome

**Comment by edwardtfn** [comment]
> Thanks for the quick reply,
> 
> I allready checked the sensors page, It doesn't show up. ![Schermafbeelding 2023-09-21 200430](https://user-images.githubusercontent.com/137107243/269713490-4db18087-c250-4a8b-a0ab-7ec72e44c930.png)

Yeah, I can see you still have the old NSPanel Event sensor, which means your ESPHome still v3.x.

**Comment by Lama131** [comment]
I've tried updating esphome several times.


![IMG20230921201944](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/137107243/1119b618-821f-4cb4-bdac-dd3dcbd2b3c2)

![Screenshot_2023-09-21-20-15-04-42_c3a231c25ed346e59462e84656a70e50](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/137107243/a88c0a32-8bb6-4bb7-9ec9-63c5fc629427)
![Screenshot_2023-09-21-20-17-32-76_c3a231c25ed346e59462e84656a70e50](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/137107243/20a84776-fe5c-4a7a-a153-1bb3bf2c45d6)

**Comment by edwardtfn** [comment]
Try cleaning up your build files...

On the ESPHome dashboard, on the 3-dot menu of your device, then click "Clean build files".
After that, try to flash it again. If it still on v3.4,1, please share your ESPHome settings. Please remove any private info (Wifi, etc.) before sharing.

**Comment by Lama131** [comment]
I've tried cleaning the build files and re-installing ESPhome, still no luck though.

Here's my ESPhome settings:
substitutions:

###### CHANGE ME START ######

  device_name: "wandpaneel" 
  wifi_ssid: ""
  wifi_password: ""

#  nextion_update_url: "http://HA_IP:8123/local/nspanel_eu.tft" # URL to local tft File
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

**Comment by edwardtfn** [comment]
This is weird... everything looks right.

Do you have more than 1 panel? If that is the case, are you sure you are updating the right one?

**Comment by Lama131** [comment]
This is the only panel i have at the moment.

**Comment by edwardtfn** [comment]
On the `remote_package` area, try changing from `ref: main` to `ref: beta` and try again, please.

**Comment by Lama131** [comment]
That seems to have fixed the issue.
The panel succesfully updated and came back to life again.

Thanks for the quick support

**Comment by edwardtfn** [comment]
Remember to change that back to `ref: main`, otherwise you will receive the updates from `beta`.
