### ISSUE TITLE
Updating the TFT-file takes forever.

### ISSUE THREAD

**Issue by magne74** [Blackymas/NSPanel_HA_Blueprint#1073]
After updating to V4.0, 2 of 3 panels almost totalt stops updating the TFT-file. One from local and directly from GitHub. The same behavior. Just me? Have I done something wrong? Anyone have a quick-fix?

<img width="1321" alt="Skjermbilde 2023-09-22 kl  09 43 52" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/111948595/b4ea54dd-23ce-46bc-b8ab-91b32dda53d1">

**Comment by edwardtfn** [comment]
So, as I understood, you are upgrading from v3.x to v4.0, so this is not a new installation, right?

The upload shouldn't take more than 15 to 20min. If it is too slow and taking more than 30min, I would suggest to cancel it and start over. I've never seen those life time uploads ending successfully. And typically it is safe to interrupt in the middle of that process and then start again.

Also, power cycle the device, flash ESPHome again and/or upload `nspanel_blank.tft` could help.

**Comment by edwardtfn** [comment]
> Just me?

Take a look at this one: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1061

**Comment by magne74** [comment]
Hi.

Yes, upgrade. I will try it out.

**Comment by edwardtfn** [comment]
In a normal tft upload, the log should look like this:

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/e80c7a1d-def7-44ab-9e61-f09b2204ad14)

That message `Nextion is not connected!` is an indication of something wrong in the communication between ESPHome and the Display. A reboot will probably help.

**Comment by magne74** [comment]
Reboot is not doing the trick. Done that and also re-powered the unit. But uploading the blank.tft file seems to do the trick:-) I will come back and confirm that whet all is good.

**Comment by magne74** [comment]
Everything is now working again. Thanks!

But: Where did the sleep mode-button go?

**Comment by edwardtfn** [comment]
> Everything is now working again. Thanks!

🥳 

> Where did the sleep mode-button go?

Please take a look at this one: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1060

**Comment by magne74** [comment]
Ok. The problem is that when you set the time to 0 when the panel is in screensaver-mode. I doesn’t wait up again before you touch it...

**Comment by magne74** [comment]
I must make an automation that first set sleep time to 0 and then do a restart to awake the display. So please reconsider the sleep mode button in the next update. But besides that, great work!
And again: Thank you for the help with the tft-update😊

**Comment by edwardtfn** [comment]
> So please reconsider the sleep mode button in the next update.

Yeah, I'm thinking about this... It would be inconsistent with other timers, but you are not the first one asking for this, so maybe I'm missing something.



> I must make an automation that first set sleep time to 0 and then do a restart to awake the display.

You can call the service `esphome.xxxxx_wake_up` from your automation:
```yaml
service: esphome.xxxxx_wake_up
data:
  reset_timer: false
```

This will wake-up if it is sleeping and reset the timers for dim and sleep. If you use `reset_timer: true` then it will also reset the page timer.

**Comment by magne74** [comment]
That works for me. Perfect!

**Comment by quenthal** [comment]
Upgraded today 6 panels. 1 of them required more fiddling than ever before. 

I had to switch to Tasmota, push blank.tft over there and then return to ESPHome/NSPanel Blueprint. Tried using all the tricks I've done before, and had similar messages as the original post in this thread. There was some timeout on the connection usually around 10-20%, but managed to circumvent that by using Tasmota. Hopefully next update goes smoother, not fan of taking it from the wall anymore :)

**Comment by Razsmithii** [comment]
For me, this was the easiest solution and the only working one after hours of fiddeling around:
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/166

**Comment by edwardtfn** [comment]
It shouldn't be that hard to update TFT, but it always look challenging with ESPHome.
I will look again at some ways to improve that or at least improve documentation around that.
Thanks a lot!

**Comment by HKUser1** [comment]
same here 2 NS Panels without a Problem the 3. makes really hard Trouble an is still not working :). The only Solution that I not have tried yet is the soldering Version :). The confusing thing is that is not possible to install the blank.tft
:)

**Comment by edwardtfn** [comment]
@HKUser1, as I understood, everything is working now, right?
If that is not the case, could you please create another issue and provide more details?
