### ISSUE TITLE
Mute and volume control in Media Player

### ISSUE THREAD

**Issue by quenthal** [Blackymas/NSPanel_HA_Blueprint#1079]
Having some issues here. I understand the volume control is not instant, but it is somewhat "dangerous" as well.

While tapping more volume it is relatively easy to tap accidentally at the end of the volume bar causing volume to get up to 100%.

I think some buttons - if it is not possible to have it more responsive - would be better than volume bar. Same may be with time when song is playing.

In addition to those useability suggestions I'm having an issue with mute. For me clicking mute does not do anything. 

I'm using Sonos.

**Comment by edwardtfn** [comment]
Ok, please correct me if I'm wrong, but I can see 3 different issues from your message:

1. Volume control is not very responsive
2. Volume +/- buttons are too close to the slider
3. Mute is not working

In addition, you gave feedback about the usability of the volume and progress bars.

I will take a look at all of those points. Thanks a lot!  😉 

May I ask which model are you using? EU, US or US Landscape?

**Comment by edwardtfn** [comment]
I believe this is fixed in `dev`...
Feel free to try before we release to a wider public. 😉

**Comment by edwardtfn** [comment]
It is available for testing on beta: https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1046#discussioncomment-7093668

I will wait for some feedback and then go to the release.
