### ISSUE TITLE
Cant update esphome

### ISSUE THREAD

**Issue by pbranly** [Blackymas/NSPanel_HA_Blueprint#1084]
Hi
I try to update the esp.
the validate gives "no error" but when I use the install, it hangs during several minutes on the "main.cpp.o line then definitively on the firmware.elf link.
I tried to reinstall another esp that I have and it works.
here is my configuration:
`substitutions:

###### CHANGE ME START ######

  device_name: "nspanel" 
  wifi_ssid: !secret SSID
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.1.8:8088/local/nspanel_us.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####`

and here is the esphome screen after at least 10 minutes:

`INFO ESPHome 2023.8.3
INFO Reading configuration /config/nspanel.yaml...
INFO Detected timezone 'Europe/Paris'
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing nspanel (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- WiFiClientSecure @ 2.0.0
|-- HTTPClient @ 2.0.0
Compiling .pioenvs/nspanel/src/main.cpp.o
Linking .pioenvs/nspanel/firmware.elf`

What should I do ?

Thanks
Phil

**Comment by pbranly** [comment]
Edit: it seems that despite of any message, the esp was upgraded as nspanel report version 4.0.
I could then put the last blueprint and the last tft file without error but there is a mismatch in the screens .
I have the following strange message:

There's a version mismatch between NSPanel_HA_Blueprint components. Please update all the components to the same version.

    Panel: nspanel
    TFT:
    ESPHome: 4.0
    Blueprint: 4.0 (expected 4.0)

i dont have any menu for dcreen light adjustment or restart as with previous versions and none of the strange menu for light and covers dont react 

![IMG_5313](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/22018509/7a9dfebc-a774-4877-b7a2-129868984902)

**Comment by edwardtfn** [comment]
Could you please share the specifications of the hardware running ESPHome server? It could be something related to that...

What happens after that last log message you shared? Looks like it still processing...

Have you tried cleaning the build files (3-dot menu at ESPHome dashboard).

**Comment by edwardtfn** [comment]
You have an older TFT.

Are you sure you have the right file v4.0 at this url? http://192.168.1.8:8088/local/nspanel_us.tft

**Comment by pbranly** [comment]
> You have an older TFT.
> 
> Are you sure you have the right file v4.0 at this url? http://192.168.1.8:8088/local/nspanel_us.tft

You are right ! the file was not at the good place. this is working fine now after a new full tft upgrade
Thanks a lot for quick answer
Phil

**Comment by pbranly** [comment]
> Could you please share the specifications of the hardware running ESPHome server? It could be something related to that...
> 
> What happens after that last log message you shared? Looks like it still processing...
> 
> Have you tried cleaning the build files (3-dot menu at ESPHome dashboard).

Hi
I have cleaned the files as proposed and restart the install process.
This is now hung at the "wifi_component_esp8266.cpp.o" line after more than 5 minutes

`INFO ESPHome 2023.8.3
INFO Reading configuration /config/nspanel.yaml...
INFO Detected timezone 'Europe/Paris'
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing nspanel (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
Library Manager: Installing esphome/AsyncTCP-esphome @ 1.2.2
INFO Installing esphome/AsyncTCP-esphome @ 1.2.2
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Library Manager: AsyncTCP-esphome@1.2.2 has been installed!
INFO AsyncTCP-esphome@1.2.2 has been installed!
Library Manager: Installing esphome/ESPAsyncWebServer-esphome @ 2.1.0
INFO Installing esphome/ESPAsyncWebServer-esphome @ 2.1.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Library Manager: ESPAsyncWebServer-esphome@2.1.0 has been installed!
INFO ESPAsyncWebServer-esphome@2.1.0 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing bblanchon/ArduinoJson @ 6.18.5
INFO Installing bblanchon/ArduinoJson @ 6.18.5
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Library Manager: ArduinoJson@6.18.5 has been installed!
INFO ArduinoJson@6.18.5 has been installed!
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- WiFiClientSecure @ 2.0.0
|-- HTTPClient @ 2.0.0
Compiling .pioenvs/nspanel/src/esphome/components/adc/adc_sensor.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/binary_sensor/automation.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/binary_sensor/binary_sensor.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/binary_sensor/filter.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/button/button.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/display/display.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/display/display_buffer.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/display/rect.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/esp32/core.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/esp32/gpio.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/esp32/preferences.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/gpio/switch/gpio_switch.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/homeassistant/time/homeassistant_time.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/json/json_util.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/ledc/ledc_output.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/md5/md5.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/mdns/mdns_component.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/mdns/mdns_host.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/network/util.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/nextion/binary_sensor/nextion_binarysensor.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/nextion/nextion.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/nextion/nextion_commands.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/nextion/nextion_component.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/nextion/nextion_upload.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/nextion/sensor/nextion_sensor.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/nextion/text_sensor/nextion_textsensor.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/ntc/ntc.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/number/automation.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/number/number.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/number/number_call.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/number/number_traits.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/ota/ota_backend_arduino_rp2040.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/ota/ota_component.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/output/automation.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/output/float_output.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/resistance/resistance_sensor.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/restart/button/restart_button.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/rtttl/rtttl.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/script/script.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/select/select.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/select/select_call.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/select/select_traits.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/sensor/automation.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/sensor/filter.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/sensor/sensor.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/socket/bsd_sockets_impl.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/socket/lwip_raw_tcp_impl.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/socket/socket.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/status/status_binary_sensor.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/switch/automation.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/switch/switch.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/template/binary_sensor/template_binary_sensor.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/template/number/template_number.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/template/select/template_select.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/template/sensor/template_sensor.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/template/switch/template_switch.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/template/text_sensor/template_text_sensor.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/text_sensor/filter.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/text_sensor/text_sensor.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/time/automation.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/time/real_time_clock.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/uart/uart.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/uart/uart_component.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/uart/uart_component_esp32_arduino.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/uart/uart_component_esp8266.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/uart/uart_component_esp_idf.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/uart/uart_component_rp2040.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/uart/uart_debugger.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/uptime/uptime_sensor.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/version/version_text_sensor.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/web_server/list_entities.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/web_server/web_server.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/web_server_base/web_server_base.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/wifi/wifi_component.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/wifi/wifi_component_esp32_arduino.cpp.o
Compiling .pioenvs/nspanel/src/esphome/components/wifi/wifi_component_esp8266.cpp.o`

My hardware is a NUC6CAYS under Ubuntu.
ESPhome is intallled under a docker

`  esphome:
    container_name: ESPHome
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./esphome:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    restart: always
    network_mode: host
#    image: esphome/esphome:beta
    image: esphome/esphome:latest
#    image: esphome/esphome:dev
#    devices:
#      - /dev/ttyUSB0:/dev/ttyUSB1`

**Comment by edwardtfn** [comment]
But you already have Esphome v4.0 installed, you don't have to flash it again.

**Comment by pbranly** [comment]
> But you already have Esphome v4.0 installed, you don't have to flash it again.

Yes that's true but this behavior is abnormal; 
i had to stop and restart the compilation 3 times ; I did not have any message after the firmware.elf message, no upgrade message toward the esp, but esp was flashed again;
 this seems specific to your program because with my esp, everything works as expected.
let it under observation ....
thnks
Phil

**Comment by edwardtfn** [comment]
> this seems specific to your program because with my esp

It could be... This project is quite complex compared to a typical ESPHome project, so it's expected it taking more resources when compiling...
