### ISSUE TITLE
mismatch between thermostat pages and cover pages

### ISSUE THREAD

**Issue by pbranly** [Blackymas/NSPanel_HA_Blueprint#1085]
Hi
all versions to 4.0:

When I make a long press on any of the cover icons, I do have the possibility to adjust its pecentage
But when I do the same for thermostat, it opens a cover menu
please see file:
`alias: NSPanel
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: 76520303a8cbc905d522e79f6a527b5e
    language: fr
    date_format: "%d/%m"
    time_format: "%-H:%M"
    entitypages_enabled: true
    button_page01_label: ECLAIRAGE
    entity01: light.lampe_cuisine
    entity01_name: Cuisine
    entity01_icon_color:
      - 255
      - 255
      - 0
    entity01_icon: mdi:lightbulb-on
    entity02: light.prise_salon
    entity02_name: Salon
    entity02_icon: mdi:power-socket-eu
    entity02_icon_color:
      - 255
      - 255
      - 0
    entity03: light.prise_bureau
    entity03_name: Bureau
    entity03_icon: mdi:power-socket-eu
    entity03_icon_color:
      - 255
      - 255
      - 0
    button_page02_label: VOLETS
    entity09: cover.volet_cuisine
    entity09_name: Cuisine
    entity09_icon: mdi:window-shutter
    entity10_icon: mdi:window-shutter
    entity10_name: Salon
    entity11_name: Parents
    entity11: cover.volet_parents
    entity11_icon: mdi:window-shutter
    entity12_name: Marie
    entity12_icon: mdi:window-shutter
    entity12: cover.volet_marie
    entity13_name: Nicolas
    entity13_icon: mdi:window-shutter
    entity13: cover.volet_chambre_nicolas
    entity14: cover.volet_bureau_nicolas
    entity14_name: Bur. Nicolas
    entity14_icon: mdi:window-shutter
    button_page03_label: THERMOSTATS RDC
    entity17: climate.thermostat_nest
    entity17_name: Nest
    entity17_icon: mdi:thermostat-auto
    entity18: climate.vanne_entree
    entity18_name: Entrée
    entity18_icon: mdi:radiator
    entity19: climate.vanne_cuisine
    entity19_name: Cuisine
    entity19_icon: mdi:radiator
    entity20_name: Salon
    entity20_icon: mdi:radiator
    entity21: climate.vanne_salon_droit
    entity21_name: Salon Droit
    entity21_icon: mdi:radiator
    entity22: climate.vanne_salon_gauche
    entity22_name: Salon Gauche
    entity22_icon: mdi:radiator
    button_page04_label: THERMOSTATS ETAGE
    entity25: climate.vanne_chambre_parents
    entity25_name: Parents
    entity25_icon: mdi:radiator
    entity26: climate.vanne_salle_de_bain
    entity26_name: Salle de bain
    entity26_icon: mdi:radiator
    entity27: climate.vanne_chambre_nicolas
    entity27_name: Nicolas
    entity27_icon: mdi:radiator
    entity28: climate.vanne_thermo_bureau_nicolas
    entity28_name: Bur. Nicolas
    entity28_icon: mdi:radiator
    weather_entity: weather.openweathermap_vve
    indoortemp: sensor.netatmo_netatmo_module_interieur_temperature
    entities_entity01_icon: mdi:globe-light-outline
    home_value01: sensor.netatmo_netatmo_module_interieur_humidity
    home_value01_icon: mdi:water-percent
    home_value01_icon_color:
      - 255
      - 255
      - 255
    home_value01_label_color:
      - 255
      - 255
      - 255
    home_value02: sensor.netatmo_netatmo_module_interieur_pressure
    chip01_icon: ""
    chip01_icon_color:
      - 40
      - 95
      - 244
    outdoortemp: sensor.netatmo_netatmo_module_exterieur_temperature
    entity10: cover.volet_salon
`

Phil

**Comment by edwardtfn** [comment]
> another issue is that screen dimed value does not work; after some time, screen fully stop

Do you mind creating another topic specifically for this and then provide more details (which are all your timeout settings, what do you mean by "screen fully stop", etc.)?

I'd like to investigate both cases and would be easier if they are split.

**Comment by edwardtfn** [comment]
> But when I do the same for thermostat, it opens a cover menu

I couldn't duplicate this.

Could you please let me know which TFT model are you using? EU, US or US Landscape?

**Comment by pbranly** [comment]
> > But when I do the same for thermostat, it opens a cover menu
> 
> I couldn't duplicate this.
> 
> Could you please let me know which TFT model are you using? EU, US or US Landscape?
> 
> Is the same issue happening to all the buttons where you have a climate entity or just to a specific one?

Hi I have an US "picture size" screen.

In fact it happens only for thermostats that are in the " BUTTON PAGE 03":
A long press on any thermostats give detail adjustments for covers that is the "BUTTON page 02" 

But thermostats that are in the "BUTTON PAGE 04" work fine
So this seems to be linked only with PAGE03

Phil

**Comment by pbranly** [comment]
@edwardtfn 
I think I found;
Please refer to attached nextion editor screen;
The page 3 refers to page 2 for the long press
![2023-09-23_17-35](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/22018509/92c24b11-47cc-490e-8a9e-eec680e0f267)
![2023-09-23_17-37](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/22018509/fad88ad6-20e4-48eb-b753-338f9e490f9e)
![2023-09-23_17-36](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/22018509/0c3e969e-69ed-4b8c-81d0-ee2a9703324b)

**Comment by pbranly** [comment]
I have verified : EU version and US Land version are correct

**Comment by edwardtfn** [comment]
Good catch! Thanks a lot for digging into the cause.
It looks like a critical bug. I will work in a patch as soon I get home and let you know when available.

**Comment by edwardtfn** [comment]
I could duplicate the issue when using `nspanel_us.tft`.
Working in a fix right now.

**Comment by edwardtfn** [comment]
It is available for testing on beta: https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1046#discussioncomment-7093668

I will wait for some feedback and then go to the release.

**Comment by pbranly** [comment]
Hi with the beta (tft and blueprint) it is working now thanks
just the same compilation issue : 
I changes  to   ref: beta in the nspanel.yaml and started install
it was again stuck at the end of the firmware.elf linking without further messages
the nspanel screen sho beta version for both tft and blueprint but 4.0 for nspanel. Was it uploaded or not ? is it normal to keep the same software name ?
There is definitively an issue withe compilation

Phil

**Comment by edwardtfn** [comment]
All the parts should be showing "4.0.1beta".
They are all compatible with v4.0, so if you update just or two components, you shouldn't get any error message.

**Comment by pbranly** [comment]
Hi
Despite many tries, I cant compile the nspanel with the beta; Each tentative is stopped in the meddle of the process.
Between 3.2 and 4.0 I could succeed after 2 retries but this time the process always stick somewhere
I even tried to restart my linux and stop all the dockers except the esphome in order to have the maximum amount of memory without success
What do you use for compilation ?
Phil
