### ISSUE TITLE
Screen Dimer does not work

### ISSUE THREAD

**Issue by pbranly** [Blackymas/NSPanel_HA_Blueprint#1087]
Hi
I have a US NSPANEL in picture mode
All versions are 4.0
I have adjusted LUMINOSITEE
Clair 100 %
Sombre 56 %

When  i click the screen, luminosity is 100 % (I think !)
After some time, the screen is fully black while it should reduce to 56 %
If I click the screen, it awakes à 100 %

Phil

**Comment by edwardtfn** [comment]
How are set Timeout Sleep and Timeout Dim?

**Comment by pbranly** [comment]
Hi
I let the standard values 

Phil
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/22018509/d52064b9-1e66-4f77-aaf8-87118ba02297)

**Comment by edwardtfn** [comment]
I could duplicate the issue.
Working in a fix...

**Comment by pbranly** [comment]
Perfecto !
Thanks
Phil

**Comment by edwardtfn** [comment]
The fix is already on `dev`.
I will run some test and probably will have a release to `main` tomorrow.

**Comment by edwardtfn** [comment]
It is available for testing on beta: https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1046#discussioncomment-7093668

I will wait for some feedback and then go to the release.

**Comment by pbranly** [comment]
I think that it is working
after 30 sec it goes to dimming value the after additional 30 sec to blank screen
Thgere was many messages about the behavior that I did not properly read;
If I dont want the black screen state, do I have to set "Timeout sleep timer" to 0 ?
If yes, the adjustment screen should have an additional line I think
Phil

**Comment by edwardtfn** [comment]
> If I dont want the black screen state, do I have to set "Timeout sleep timer" to 0 ?

Exactly.

**Comment by edwardtfn** [comment]
> the adjustment screen should have an additional line I think

I fully agree. I've removed that sleep mode switch at last minute before releasing v4.0 and couldn't find time to rearrange settings page to fit the new timer selector (number) as that requires a bit more work in the UI.
I'm planing to work at that soon.

**Comment by pbranly** [comment]
Excellent
Thanks for this great development

**Comment by pbranly** [comment]
Hi
Sorry but it does not work
I have set timeout sleep to 0 and it never dims while it should after 30 sec
this is my configuration:
![2023-09-24_18-29](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/22018509/380c3391-9bac-4daf-b992-ea6c18506215)

**Comment by pbranly** [comment]
Hi
With esphome beta it works 
Thanks
Phil
