### ISSUE TITLE
Allow group switching as button action

### ISSUE THREAD

**Issue by lecrams** [Blackymas/NSPanel_HA_Blueprint#110]
currently ONLY light, switch, cover, input_boolean, automation, button , input_button, scene , person can be assigned directly to a button.
Adding groups as possible entity would be a good addition

**Comment by deejaybeam** [comment]
Hi
If you talking about "Old style groups" see: https://www.home-assistant.io/integrations/group/#old-style-groups
Group-Switching is not directly supported, and depends on the memers of the group itself - so this is not possible to implement in a usefull way. If you want to switch a group of lights, or switches, please use the new groups, wich are created as helper - this creates entities with the correct domain e.g. light. for a group of lights and can be assigned this way with full support including e.g. dimmig

**Comment by lecrams** [comment]
That explain. Thx for this note.
