### ISSUE TITLE
Error when trying validat NSPAnel to version 4.0

### ISSUE THREAD

**Issue by Zealand67** [Blackymas/NSPanel_HA_Blueprint#1102]
Hello 
I am getting the following error when trying to validat the NSPanel to version 4.0. The screeen "hangs" now on th eblue screen with the message "Please wait":

INFO ESPHome 2023.8.3
INFO Reading configuration /config/esphome/nspanel1.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Detected timezone 'America/Los_Angeles'
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing nspanel1 (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- WiFiClientSecure @ 2.0.0
|-- HTTPClient @ 2.0.0
Compiling /data/nspanel1/.pioenvs/nspanel1/src/main.cpp.o
xtensa-esp32-elf-g++: fatal error: Killed signal terminated program as
compilation terminated.
*** [/data/nspanel1/.pioenvs/nspanel1/src/main.cpp.o] Error 1
========================= [FAILED] Took 117.98 seconds =========================

My Yaml is as follow:
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel1" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

#  nextion_update_url: "https://50.53.186.96:8123/local/nspanel_us.tft" # URL to local tft File
  nextion_update_url: https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft # URL to Github

##### DO NT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

I am running:
Home Assistant 2023.9.3
Supervisor 2023.09.2
Operating System 10.5
Frontend 20230911.0 - latest

Hardware is a Raspberry 4 with 2 GMN Memory.

Thanks for any hlep to get my beloved NSPanel back to life.

Urs

**Comment by edwardtfn** [comment]
> The screeen "hangs" now on th eblue screen with the message "Please wait":

On that blue screen, what is shown for TFT, ESPHome and Blueprint versions?

**Comment by Zealand67** [comment]
TFT Version 4.0
ESPHome 3.4.1
Blueprint: Retrv9

I updated the blueprint YAML with the new version 4.0, deleted and recreated the blueprint again but with no success

**Comment by edwardtfn** [comment]
> I updated the blueprint YAML with the new version 4.0, deleted and recreated the blueprint again but with no success

The Blueprint won't be able to connect and publish it's version until ESPHome is v4.0,so focus on ESPHome issue first...

**Comment by edwardtfn** [comment]
I'd suggest to clean your build files and try again...

**Comment by Zealand67** [comment]
Did that already twice; the error just comes a a later stage:

el1.yaml
INFO ESPHome 2023.8.3
INFO Reading configuration /config/esphome/nspanel1.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Detected timezone 'America/Los_Angeles'
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing nspanel1 (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
Library Manager: Installing esphome/AsyncTCP-esphome @ 1.2.2
INFO Installing esphome/AsyncTCP-esphome @ 1.2.2
Unpacking  [####################################]  100%
Library Manager: AsyncTCP-esphome@1.2.2 has been installed!
INFO AsyncTCP-esphome@1.2.2 has been installed!
Library Manager: Installing esphome/ESPAsyncWebServer-esphome @ 2.1.0
INFO Installing esphome/ESPAsyncWebServer-esphome @ 2.1.0
Unpacking  [####################################]  100%
Library Manager: ESPAsyncWebServer-esphome@2.1.0 has been installed!
INFO ESPAsyncWebServer-esphome@2.1.0 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing bblanchon/ArduinoJson @ 6.18.5
INFO Installing bblanchon/ArduinoJson @ 6.18.5
Unpacking  [####################################]  100%
Library Manager: ArduinoJson@6.18.5 has been installed!
INFO ArduinoJson@6.18.5 has been installed!
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- WiFiClientSecure @ 2.0.0
|-- HTTPClient @ 2.0.0
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/adc/adc_sensor.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/api/api_connection.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/api/api_frame_helper.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/api/api_pb2.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/api/api_pb2_service.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/api/api_server.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/api/list_entities.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/api/proto.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/api/subscribe_state.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/api/user_services.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/binary_sensor/automation.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/binary_sensor/binary_sensor.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/binary_sensor/filter.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/button/button.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/display/display.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/display/display_buffer.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/display/rect.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/esp32/core.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/esp32/gpio.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/esp32/preferences.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/gpio/switch/gpio_switch.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/homeassistant/time/homeassistant_time.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/json/json_util.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/ledc/ledc_output.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/logger/logger.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/md5/md5.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/mdns/mdns_component.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/mdns/mdns_host.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/network/util.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/nextion/binary_sensor/nextion_binarysensor.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/nextion/nextion.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/nextion/nextion_commands.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/nextion/nextion_component.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/nextion/nextion_upload.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/nextion/sensor/nextion_sensor.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/nextion/text_sensor/nextion_textsensor.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/ntc/ntc.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/number/automation.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/number/number.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/number/number_call.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/number/number_traits.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/ota/ota_backend_arduino_rp2040.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/ota/ota_component.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/output/automation.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/output/float_output.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/resistance/resistance_sensor.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/restart/button/restart_button.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/rtttl/rtttl.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/script/script.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/select/select.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/select/select_call.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/select/select_traits.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/sensor/automation.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/sensor/filter.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/sensor/sensor.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/socket/bsd_sockets_impl.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/socket/lwip_raw_tcp_impl.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/socket/socket.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/status/status_binary_sensor.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/switch/automation.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/switch/switch.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/template/binary_sensor/template_binary_sensor.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/template/number/template_number.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/template/select/template_select.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/template/sensor/template_sensor.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/template/switch/template_switch.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/template/text_sensor/template_text_sensor.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/text_sensor/filter.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/text_sensor/text_sensor.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/time/automation.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/time/real_time_clock.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/uart/uart.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/uart/uart_component.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/uart/uart_component_esp32_arduino.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/uart/uart_component_esp8266.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/uart/uart_component_esp_idf.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/uart/uart_component_rp2040.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/uart/uart_debugger.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/uptime/uptime_sensor.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/version/version_text_sensor.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/web_server/list_entities.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/web_server/web_server.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/web_server_base/web_server_base.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/wifi/wifi_component.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/wifi/wifi_component_esp32_arduino.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/wifi/wifi_component_esp_idf.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/wifi/wifi_component_pico_w.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/wifi_info/wifi_info_text_sensor.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/components/wifi_signal/wifi_signal_sensor.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/core/application.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/core/color.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/core/component.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/core/component_iterator.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/core/controller.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/core/entity_base.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/core/helpers.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/core/log.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/core/scheduler.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/core/string_ref.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/core/time.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/esphome/core/util.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/src/main.cpp.o
Building /data/nspanel1/.pioenvs/nspanel1/bootloader.bin
Creating esp32 image...
Successfully created esp32 image.
Generating partitions /data/nspanel1/.pioenvs/nspanel1/partitions.bin
Compiling /data/nspanel1/.pioenvs/nspanel1/lib759/AsyncTCP-esphome/AsyncTCP.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/lib64d/WiFi/WiFi.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/lib64d/WiFi/WiFiAP.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/lib64d/WiFi/WiFiClient.cpp.o
Archiving /data/nspanel1/.pioenvs/nspanel1/lib759/libAsyncTCP-esphome.a
Compiling /data/nspanel1/.pioenvs/nspanel1/lib64d/WiFi/WiFiGeneric.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/lib64d/WiFi/WiFiMulti.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/lib64d/WiFi/WiFiSTA.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/lib64d/WiFi/WiFiScan.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/lib64d/WiFi/WiFiServer.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/lib64d/WiFi/WiFiUdp.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/lib01c/FS/FS.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/lib01c/FS/vfs_api.cpp.o
Archiving /data/nspanel1/.pioenvs/nspanel1/lib64d/libWiFi.a
Compiling /data/nspanel1/.pioenvs/nspanel1/libbc6/Update/HttpsOTAUpdate.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/libbc6/Update/Updater.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/lib8c6/ESPAsyncWebServer-esphome/AsyncEventSource.cpp.o
Archiving /data/nspanel1/.pioenvs/nspanel1/lib01c/libFS.a
Compiling /data/nspanel1/.pioenvs/nspanel1/lib8c6/ESPAsyncWebServer-esphome/AsyncWebSocket.cpp.o
Archiving /data/nspanel1/.pioenvs/nspanel1/libbc6/libUpdate.a
Compiling /data/nspanel1/.pioenvs/nspanel1/lib8c6/ESPAsyncWebServer-esphome/WebAuthentication.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/lib8c6/ESPAsyncWebServer-esphome/WebHandlers.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/lib8c6/ESPAsyncWebServer-esphome/WebRequest.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/lib8c6/ESPAsyncWebServer-esphome/WebResponses.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/lib8c6/ESPAsyncWebServer-esphome/WebServer.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/lib333/DNSServer/DNSServer.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/lib915/ESPmDNS/ESPmDNS.cpp.o
Archiving /data/nspanel1/.pioenvs/nspanel1/lib8c6/libESPAsyncWebServer-esphome.a
Compiling /data/nspanel1/.pioenvs/nspanel1/libb0f/WiFiClientSecure/WiFiClientSecure.cpp.o
Archiving /data/nspanel1/.pioenvs/nspanel1/lib333/libDNSServer.a
Compiling /data/nspanel1/.pioenvs/nspanel1/libb0f/WiFiClientSecure/esp_crt_bundle.c.o
Archiving /data/nspanel1/.pioenvs/nspanel1/lib915/libESPmDNS.a
Compiling /data/nspanel1/.pioenvs/nspanel1/libb0f/WiFiClientSecure/ssl_client.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/lib2f0/HTTPClient/HTTPClient.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/Esp.cpp.o
Archiving /data/nspanel1/.pioenvs/nspanel1/libb0f/libWiFiClientSecure.a
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/FirmwareMSC.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/FunctionalInterrupt.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/HWCDC.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/HardwareSerial.cpp.o
Archiving /data/nspanel1/.pioenvs/nspanel1/lib2f0/libHTTPClient.a
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/IPAddress.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/IPv6Address.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/MD5Builder.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/Print.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/Stream.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/StreamString.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/Tone.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/USB.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/USBCDC.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/USBMSC.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/WMath.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/WString.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/base64.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/cbuf.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-adc.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-bt.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-cpu.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-dac.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-gpio.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-i2c-slave.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-i2c.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-ledc.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-matrix.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-misc.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-psram.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-rgb-led.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-rmt.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-sigmadelta.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-spi.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-time.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-timer.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-tinyusb.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-touch.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/esp32-hal-uart.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/firmware_msc_fat.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/libb64/cdecode.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/libb64/cencode.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/main.cpp.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/stdlib_noniso.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/wiring_pulse.c.o
Compiling /data/nspanel1/.pioenvs/nspanel1/FrameworkArduino/wiring_shift.c.o
Archiving /data/nspanel1/.pioenvs/nspanel1/libFrameworkArduino.a
xtensa-esp32-elf-g++: fatal error: Killed signal terminated program as
compilation terminated.
*** [/data/nspanel1/.pioenvs/nspanel1/src/main.cpp.o] Error 1
========================= [FAILED] Took 319.89 seconds =========================

**Comment by edwardtfn** [comment]
The logs shows your ESPHome compiler crashing, so if cleaning the build files isn't helping, I'd suggest restarting the host system.
This is a quite complex code, but I wouldn't expect any issue with a RPi4.

**Comment by edwardtfn** [comment]
This last crash was almost at the end of the process... 😩

**Comment by Zealand67** [comment]
Yah, just right now crashed again at the same line.

Let me restart the whole system and check again.....

**Comment by edwardtfn** [comment]
You can also try adding this at the end of your yaml:

```yaml
esphome:
  compile_process_limit: 1
```

This will probably make the compiling process take longer, but will use less resources of your server.

- https://esphome.io/changelog/2022.11.0.html#running-esphome-on-lower-powered-machines
- https://community.home-assistant.io/t/compilation-fails-xtensa-lx106-elf-g-fatal-error-killed-signal-terminated-program-cc1plus/463184/4

**Comment by Zealand67** [comment]
Thanks for you help. After a full reboot of the Raspberry and HA, the compiling went trough and the NSPAnel is online again.
