### ISSUE TITLE
Smart Light on 3rd page

### ISSUE THREAD

**Issue by gvhomeassistant** [Blackymas/NSPanel_HA_Blueprint#1103]
Hi
I tried to add smart bulbs (tuya) and smart led ribbon on (tuya) on the NSPanel 
on 1st page, everything is working fine
on 2rd page, long press never open the option page, only able to switch on and off with short press

**Comment by edwardtfn** [comment]
This is already fixed in v4.0.1.
You have to update your TFT. 😩

https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v4.0.1

**Comment by gvhomeassistant** [comment]
I will do it right now, will get back to you !

**Comment by gvhomeassistant** [comment]
You are correct, it is already solved ! Thanks
