### ISSUE TITLE
Weather forecast 1day offset

### ISSUE THREAD

**Issue by prigorus** [Blackymas/NSPanel_HA_Blueprint#1105]
I was using Accuweather forecast at first but it is not accurate for my location. I then switched to pirateweather but had a 1 day offset on the NSPanel (the first day of the forecast dispalyed the actual weather), it was delayed for 1 day. I now have my own weather station and use the Weatherflow integration and have again the same issue, one day offset. The weather entity and forecast is displayed correctly in HA. Is there anything that could be missing for providers other than Accuweather? Or would it be possible to add a manual offset option to calibrate other providers?

**Comment by edwardtfn** [comment]
When you go to Developer Tools > States and select the weather entity you wanna use, what you see on the attributes?
Could you please share it here so I can try to understand the issue?

**Comment by prigorus** [comment]
This is the entity:

temperature_unit: °C
pressure_unit: hPa
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast:
  - datetime: '2023-09-25T22:00:00+00:00'
    conditions: Clear
    condition: sunny
    temperature: 23
    templow: 14
    precipitation: 0
    precipitation_probability: 10
    precip_icon: chance-rain
    precip_type: rain
    wind_speed: 5.9
    wind_bearing: 74
    wind_direction_cardinal: ENE
  - datetime: '2023-09-26T22:00:00+00:00'
    conditions: Rain Possible
    condition: rainy
    temperature: 23
    templow: 11
    precipitation: 0
    precipitation_probability: 20
    precip_icon: chance-rain
    precip_type: rain
    wind_speed: 5.2
    wind_bearing: 206
    wind_direction_cardinal: SSW
  - datetime: '2023-09-27T22:00:00+00:00'
    conditions: Clear
    condition: sunny
    temperature: 23
    templow: 10
    precipitation: 0
    precipitation_probability: 10
    precip_icon: chance-rain
    precip_type: rain
    wind_speed: 5.5
    wind_bearing: 230
    wind_direction_cardinal: SW
  - datetime: '2023-09-28T22:00:00+00:00'
    conditions: Clear
    condition: sunny
    temperature: 22
    templow: 9
    precipitation: 0
    precipitation_probability: 10
    precip_icon: chance-rain
    precip_type: rain
    wind_speed: 4.7
    wind_bearing: 230
    wind_direction_cardinal: SW
  - datetime: '2023-09-29T22:00:00+00:00'
    conditions: Rain Possible
    condition: rainy
    temperature: 23
    templow: 11
    precipitation: 0
    precipitation_probability: 30
    precip_icon: chance-rain
    precip_type: rain
    wind_speed: 5.7
    wind_bearing: 220
    wind_direction_cardinal: SW
  - datetime: '2023-09-30T22:00:00+00:00'
    conditions: Rain Possible
    condition: rainy
    temperature: 21
    templow: 12
    precipitation: 0
    precipitation_probability: 20
    precip_icon: chance-rain
    precip_type: rain
    wind_speed: 4.8
    wind_bearing: 179
    wind_direction_cardinal: S
  - datetime: '2023-10-01T22:00:00+00:00'
    conditions: Rain Possible
    condition: rainy
    temperature: 24
    templow: 11
    precipitation: 0
    precipitation_probability: 20
    precip_icon: chance-rain
    precip_type: rain
    wind_speed: 4.7
    wind_bearing: 226
    wind_direction_cardinal: SW
  - datetime: '2023-10-02T22:00:00+00:00'
    conditions: Rain Likely
    condition: rainy
    temperature: 23
    templow: 12
    precipitation: 1.7
    precipitation_probability: 60
    precip_icon: chance-rain
    precip_type: rain
    wind_speed: 5
    wind_bearing: 234
    wind_direction_cardinal: SW
  - datetime: '2023-10-03T22:00:00+00:00'
    conditions: Rain Likely
    condition: rainy
    temperature: 21
    templow: 13
    precipitation: 6.56
    precipitation_probability: 60
    precip_icon: chance-rain
    precip_type: rain
    wind_speed: 5.4
    wind_bearing: 199
    wind_direction_cardinal: SSW
  - datetime: '2023-10-04T22:00:00+00:00'
    conditions: Rain Likely
    condition: rainy
    temperature: 20
    templow: 12
    precipitation: 7.4
    precipitation_probability: 60
    precip_icon: chance-rain
    precip_type: rain
    wind_speed: 5.1
    wind_bearing: 198
    wind_direction_cardinal: SSW
attribution: Powered by Home Assistant
friendly_name: Lokalno vreme - dnevna napoved
supported_features: 0

**Comment by edwardtfn** [comment]
Ok, when you say it is showing 1day offset, that means it showing tomorrow's data but with today's date?
Could you please send more details about this offset? Maybe a couple of pictures from your weather pages so I can compare to the data you just shared.

**Comment by edwardtfn** [comment]
And maybe share a screenshot from Home Assistant showing the data, so we can compare that also?

**Comment by prigorus** [comment]
All the data is below. It is in slovenian but there are dates beside. The photos from the panel are in rewerse order. Thanks for your fast replies and all the work!!


temperature_unit: °C
pressure_unit: hPa
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast:
  - datetime: '2023-09-25T22:00:00+00:00'
    conditions: Clear
    condition: sunny
    temperature: 15
    templow: 14
    precipitation: 0
    precipitation_probability: 0
    precip_icon: ''
    precip_type: ''
    wind_speed: 3.6
    wind_bearing: 132
    wind_direction_cardinal: SE
  - datetime: '2023-09-26T22:00:00+00:00'
    conditions: Rain Possible
    condition: rainy
    temperature: 23
    templow: 10
    precipitation: 0
    precipitation_probability: 20
    precip_icon: chance-rain
    precip_type: rain
    wind_speed: 5.2
    wind_bearing: 208
    wind_direction_cardinal: SSW
  - datetime: '2023-09-27T22:00:00+00:00'
    conditions: Clear
    condition: sunny
    temperature: 23
    templow: 10
    precipitation: 0
    precipitation_probability: 10
    precip_icon: chance-rain
    precip_type: rain
    wind_speed: 5.2
    wind_bearing: 231
    wind_direction_cardinal: SW
  - datetime: '2023-09-28T22:00:00+00:00'
    conditions: Clear
    condition: sunny
    temperature: 22
    templow: 9
    precipitation: 0
    precipitation_probability: 10
    precip_icon: chance-rain
    precip_type: rain
    wind_speed: 4.7
    wind_bearing: 233
    wind_direction_cardinal: SW
  - datetime: '2023-09-29T22:00:00+00:00'
    conditions: Rain Possible
    condition: rainy
    temperature: 23
    templow: 11
    precipitation: 0
    precipitation_probability: 30
    precip_icon: chance-rain
    precip_type: rain
    wind_speed: 5.5
    wind_bearing: 206
    wind_direction_cardinal: SSW
  - datetime: '2023-09-30T22:00:00+00:00'
    conditions: Rain Possible
    condition: rainy
    temperature: 22
    templow: 12
    precipitation: 0
    precipitation_probability: 20
    precip_icon: chance-rain
    precip_type: rain
    wind_speed: 4.7
    wind_bearing: 195
    wind_direction_cardinal: SSW
  - datetime: '2023-10-01T22:00:00+00:00'
    conditions: Rain Possible
    condition: rainy
    temperature: 24
    templow: 11
    precipitation: 0
    precipitation_probability: 40
    precip_icon: chance-rain
    precip_type: rain
    wind_speed: 4.7
    wind_bearing: 226
    wind_direction_cardinal: SW
  - datetime: '2023-10-02T22:00:00+00:00'
    conditions: Rain Likely
    condition: rainy
    temperature: 24
    templow: 12
    precipitation: 2.38
    precipitation_probability: 70
    precip_icon: chance-rain
    precip_type: rain
    wind_speed: 4.8
    wind_bearing: 237
    wind_direction_cardinal: WSW
  - datetime: '2023-10-03T22:00:00+00:00'
    conditions: Rain Likely
    condition: rainy
    temperature: 20
    templow: 13
    precipitation: 6.74
    precipitation_probability: 70
    precip_icon: chance-rain
    precip_type: rain
    wind_speed: 5
    wind_bearing: 196
    wind_direction_cardinal: SSW
  - datetime: '2023-10-04T22:00:00+00:00'
    conditions: Rain Likely
    condition: rainy
    temperature: 19
    templow: 12
    precipitation: 8.13
    precipitation_probability: 60
    precip_icon: chance-rain
    precip_type: rain
    wind_speed: 5.1
    wind_bearing: 181
    wind_direction_cardinal: S
attribution: Powered by Home Assistant
friendly_name: Lokalno vreme - dnevna napoved
supported_features: 0


![Screenshot_20230926_203218_Home Assistant](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/108299847/5bbb2717-c5db-4c52-868d-a6df853ec718)
![20230926_203145](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/108299847/a25c51e5-362d-4e88-9ec3-36dd06ad3cc4)
![20230926_203142](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/108299847/ddc76d31-09f6-4683-8e4d-86cf31d3968e)
![20230926_203138](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/108299847/b5f16477-bdc0-4d1e-840b-894c059b4146)
![20230926_203135](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/108299847/c5d1d251-da5f-4f27-9708-eef7f71aecc3)
![20230926_203129](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/108299847/adb8a965-1975-4f05-863a-3f9a3dcac92e)

**Comment by edwardtfn** [comment]
I could duplicate the issue with PirateWeather and I can confirm is related to the way it reports it's datetime field.
Working in a fix...

**Comment by edwardtfn** [comment]
I've just pushed a potential fix to `dev`. It would be nice if you can update your Blueprint with that one in `dev` and let us know if the problem is solved, otherwise I can run some tests myself tomorrow.

**Comment by prigorus** [comment]
It's fixed. Thank you very much for the fast response and fix!

**Comment by edwardtfn** [comment]
Hopefully I haven't broken for everyone else... 😂

I will run some tests later today and hopefully I can release it to `main` later today or at least before the weekend.
