### ISSUE TITLE
Nest - Unable to use Climate page

### ISSUE THREAD

**Issue by gvhomeassistant** [Blackymas/NSPanel_HA_Blueprint#1106]
When connecting the climate page to my nest, nest is set to Clim + Heat ... I have no way to adjust the set point for each (clim or heat) 

![PXL_20230926_115419971](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/121770746/19a37473-ea50-4ec6-ab82-f39b5643b2f6)

**Comment by edwardtfn** [comment]
I believe this is the same as #909 where the climate entity have 2 target temps (min & max) and the current climate page isn't prepared to this.
Basically, the limitation is on the slider component provided by the Nextion display, which can't support two setpoints.
I will try to find some time to work in a solution for this.

**Comment by edwardtfn** [comment]
I've implemented this into `dev` and will be included in the next release soon.
Please feel free to try that before the release and give me some feedback.

**Comment by edwardtfn** [comment]
- #1556
