### ISSUE TITLE
Entity 3rd Screen

### ISSUE THREAD

**Issue by gvhomeassistant** [Blackymas/NSPanel_HA_Blueprint#1108]
Hi

If I short press on 2nd entity of 3rd page, it activates and deactivate the 1st entity 

Everything is in 4.0.1 version

**Comment by edwardtfn** [comment]
Which TFT file are you using? EU, US or US land?

**Comment by gvhomeassistant** [comment]
sorry US in portrait mode


Le mar. 26 sept. 2023, à 13 h 01, Edward Firmo ***@***.***> a
écrit :

**Comment by edwardtfn** [comment]
Thanks!
I will try to duplicate here.

**Comment by edwardtfn** [comment]
I can duplicate the issue. :(

Working in a fix...

**Comment by edwardtfn** [comment]
I have a fix already on `dev`. It would be great if you can try that and let us know the results, otherwise I will try to play a bit more with that tomorrow before going to a release.

You have to update the TFT file only. The new one have `v4.0.2dev` for now. No need to update Blueprint or ESPHome for this bug.

**Comment by gvhomeassistant** [comment]
I can do that easily within the NSPanel Web dashboard ?

**Comment by edwardtfn** [comment]
You have to download the new TFT file from this url: https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/dev/nspanel_us.tft
Then upload it to your device.

**Comment by gvhomeassistant** [comment]
That's the point, I don't know exactly how and where I can upload, I just usually use the "Update TFT display" feature in the web config

**Comment by edwardtfn** [comment]
The upload TFT will download from the url set in your settings...
Never mind, I can test a bit more by myself and then go for a release.

**Comment by gvhomeassistant** [comment]
Looks like I broke everything now : (my NSPanel only display an error message : Model does not match ...)

<html>
<body>


14:50:52 | [D] | [main:1558] | Button pressed: Update TFT display
-- | -- | -- | --
14:50:52 | [D] | [nextion_upload:169] | Connected
14:50:52 | [D] | [nextion_upload:175] | Requesting URL: https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft
14:50:53 | [D] | [nextion_upload:209] | Updating Nextion ...
14:50:53 | [D] | [nextion_upload:235] | Waiting for upgrade response
14:50:53 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:53 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:53 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:53 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:53 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:53 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:54 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:54 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:54 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:54 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:54 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:54 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:54 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:54 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:54 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:54 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:55 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:55 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:55 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:55 | [E] | [uart:015] | Reading from UART timed out at byte 0!
14:50:55 | [D] | [nextion_upload:239] | Upgrade response is  20
14:50:55 | [D] | [nextion_upload:242] | Available 0 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 1 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 2 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 3 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 4 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 5 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 6 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 7 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 7 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 8 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 9 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 10 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 11 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 12 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 13 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 14 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 15 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 16 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 17 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 18 : 0x00
14:50:55 | [D] | [nextion_upload:242] | Available 19 : 0x00
14:50:55 | [D] | [nextion_upload:248] | preparation for tft update failed 0 ""
14:50:55 | [D] | [nextion_upload:310] | Restarting Nextion
14:50:56 | [D] | [nextion_upload:313] | Restarting esphome


</body>
</html>

**Comment by edwardtfn** [comment]
> Looks like I broke everything now : (my NSPanel only display an error message : Model does not match ...)


No panic! Just try again... Power cycling the device or maybe installing the `nspanel_blank.tft` might help.
You are trying to upload the TFT directly from GitHub, which makes it even more vulnerable for errors like this, but if it worked before, it should work again.
By the way, your log shows its trying to get the file from `main`. That one still not updated with this fix.

**Comment by gvhomeassistant** [comment]
<html>
<body>


5:43:07 | [D] | [nextion_upload:175] | Requesting URL: https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/dev/nspanel_us.tft
-- | -- | -- | --
15:43:09 | [W] | [nextion_upload:186] | HTTP Request failed; URL: https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/dev/nspanel_us.tft; Error: , retrying (1/5)
15:43:09 | [W] | [nextion_upload:186] | HTTP Request failed; URL: https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/dev/nspanel_us.tft; Error: , retrying (2/5)
15:43:10 | [W] | [nextion_upload:186] | HTTP Request failed; URL: https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/dev/nspanel_us.tft; Error: , retrying (3/5)
15:43:10 | [W] | [nextion_upload:186] | HTTP Request failed; URL: https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/dev/nspanel_us.tft; Error: , retrying (4/5)
15:43:10 | [W] | [nextion_upload:186] | HTTP Request failed; URL: https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/dev/nspanel_us.tft; Error: , retrying (5/5)
15:43:11 | [D] | [nextion_upload:310] | Restarting Nextion


</body>
</html>

**Comment by edwardtfn** [comment]
Do you have any error message related to Nextion? Like "Nextion is not connected"?

You can restart the system and try again, our try transferring the `nspanel_blank.tft` first, but as I mentioned before, is always more stable if you store the tft file in your local server and try to transfer from there.

- https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-First-Steps---Installation-and-Setup#2-you-have-to-download-the-file-nspanel_ustft-or-nspanel_eutft-from-github
- https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload

**Comment by gvhomeassistant** [comment]
I was able to restore the 4.0.1, but I have the errors for the Dev version

**Comment by edwardtfn** [comment]
Dev version is v4.0.2dev, so you are probably running `main` instead.
I will try it tomorrow.
