### ISSUE TITLE
not using weather default or accuweather

### ISSUE THREAD

**Issue by chpego** [Blackymas/NSPanel_HA_Blueprint#111]
i'm using a an another weather integration (Meteo France), how it's possible to set an other sensor ?

**Comment by pepe59** [comment]
It works, but you have to change the weather entity in the blueprint to the one you use.

```
  weather: !input "weather"
  ha_weather: "weather.???????"
  accuweather: !input "accuweather"
  accuweather_value: "weather.{{ accuweather }}"
  weather_entity: >-
    {%- if weather == "Default" -%} {{ ha_weather }}
    {%- elif weather == "AccuWeather" -%} {{ accuweather_value }}
    {%- endif -%} 
```

**Comment by Blackymas** [comment]
currently no other weather integration is possible.

Of course you are welcome to customize the blueprint file.

But in the future we will surely add new weather integrations. :)
