### ISSUE TITLE
Warning: Do not update TFT via esphome

### ISSUE THREAD

**Issue by trinitrion** [Blackymas/NSPanel_HA_Blueprint#1115]
I had two running panels (3.4.1) and installed the 4.0 update on both of them the day before yesterday. 

While, fortunately, one got updated without any troubles, the other one took more than 50 hours to arrive at 100 % only to return

```
update failed: check error!
```

When I restarted the panel I got this 

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/105319980/cc9497c3-868a-40f2-ae53-0ba4e39a722d)

Nevertheless I tried another round of updating the TFT via esphome button and am now stuck at 0 % for 10 minutes or so, complemented with this log output:

```
[13:56:47][E][uart:015]: Reading from UART timed out at byte 0!
[13:56:47][W][nextion:072]: Nextion is not connected! 
[13:56:47][W][component:204]: Component nextion.display took a long time for an operation (0.11 s).
[13:56:47][W][component:205]: Components should block for at most 20-30ms.
[13:56:48][E][uart:015]: Reading from UART timed out at byte 0!
```

This leads me to say that the TFT firmware installation with ESPHOME on nextion and also its upgrade Process is seriously flawed and should be avoided. **The only solid way to install the nextion firmware and to prevent you from wasting hours is the tasmota way described by many others here.**

I am now left with one bricked panel (#1000) and another one that probably needs many more hours of attention to get it running again (hopefully the tasmota firmware update still works). 

You should clearly label the nextion firmware installation via esphome as "experimental" to say the least and recommend the nextion uodate with tasmota.

**Comment by edwardtfn** [comment]
> Nevertheless I tried another round of updating the TFT via esphome button and am now stuck at 0 % for 10 minutes or so, complemented with this log output:
[13:56:47][E][uart:015]: Reading from UART timed out at byte 0!
[13:56:47][W][nextion:072]: Nextion is not connected! 
[13:56:47][W][component:204]: Component nextion.display took a long time for an operation (0.11 s).
[13:56:47][W][component:205]: Components should block for at most 20-30ms.
[13:56:48][E][uart:015]: Reading from UART timed out at byte 0!

You can cancel this and start again. This transfer shouldn't take more than 15 to 20min. If after half hour you are not close to the end, you should stop and start again. Those life-time transfers always fails at the end and unfortunately ESPHome cannot realize the display is disconnected (even I can see that info in your logs) to automatically handle the situation. 😞 

 > hopefully the tasmota firmware update still works

I believe that works just fine.

> I am now left with one bricked panel

Cycle power your panel and then upload tft again, or try uploading the `nspanel_blank.tft` and it will come back to life.

**Comment by trinitrion** [comment]
Thanks, will try, and in the future, I will absolutely avoid the nextion tft update with esphome. I am so done with that! ;)

**Comment by edwardtfn** [comment]
I will focus on improving that... Maybe I cannot change things that are on ESPHome, but I can try to reduce the file size and play a bit with baud rates, etc...

**Comment by trinitrion** [comment]
Resolved, thank you. Installed blank and then the eu TFT. Progress looks good. 

What I did was rearranging the WiFi router for the update. Cannot stress enough how crucial a good signal is here even though the connection was not bad at all. 

Anyways, tasmota obviously handles the nextion update way more reliably than esphome.

**Comment by edwardtfn** [comment]
We will get there... 😉 

https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1117
