### ISSUE TITLE
No more sleep Modus in 4.0.2

### ISSUE THREAD

**Issue by Lice2** [Blackymas/NSPanel_HA_Blueprint#1122]
Since I installed the new version 4.0.2.
There is no sleep mode, nspanel_nspanel_event, nspanel_settings_entity, nspanel_confirmation_message, nspanel_page_timeout, nspanel_relay_1_local_fallback, nspanel_relay_2_local_fallback more.
New additions include nspanel_timeout_dimming, nspanel_timeout_page and nspanel_timeout_sleep

I had written an automation that puts the panel display into sleep mode at 11 p.m.
Is it now intentional that there is no longer a sleep mode?

**Comment by edwardtfn** [comment]
Please take a look at #1060

**Comment by edwardtfn** [comment]
Duplicated.
