### ISSUE TITLE
TFT Upload get stuck at 27%

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [Blackymas/NSPanel_HA_Blueprint#1125]
After doing update to version 4.2 my TFT upload get stuck at 27% I did do following steps to update

1. download latest version 4.2
2. replaced the nspanel_blueprint file in config/blueprints folder
3. restart automations in developer tools
4. replaced nspanel_esphome file in config/esphome
5. validate and installed the new config in ESPhome
6. replaced nspanel_eu.tft file in my config/www folder
7. Go to my device (nspanel) in ESPhome
8. pressed "Update TFT display"

till 27% it all did go smooth and relativly quick, after that it stopped

EDIT: I now see it still update the TFT but very very slow, anything I can do about this?

**Comment by smarthomefamilyverrips** [comment]
@edwardtfn how do I cancel the update and start over again?

**Comment by Azimuth0r** [comment]
The only way I've seen to start over is to use a reset pin in the reset hole. Don't panic when it boots back to a System Data error.

**Comment by smarthomefamilyverrips** [comment]
In the end I did power cycle, after this I upload the nspanel_blank.tft with developer tools>services>esphome upload tft url out of my local (www) folder, and after this was succesful done I did use same method to upload the nspanel_eu.tft and it uploaded succesful.... now all works as expected again 👍
