### ISSUE TITLE
Issues with installing and updating TFT display.

### ISSUE THREAD

**Issue by TeDeVPrime** [Blackymas/NSPanel_HA_Blueprint#1126]
Hi,
i have installed the blueprint (just installed it)
i have flashed the device with the following settings....

`substitutions:

###### CHANGE ME START ######

  device_name: "nspanelwhite" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  
  #nextion_update_url: "http://10.10.1.128:8123/local/nspanel_eu.tft" # URL to local tft File
  #nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github
  nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/custom_configuration/nspanel_blank.tft" # URL to Github
  

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####`

then when i get in the device settings... the ONLY thing that i can do is toggle the relays on and off (i can't do it on the device anymore).

i cannot update the TFT and i can't even restart the device.
i have see different posts and different people saying the exact same thing, but no-one with a solution.

i am trying to wirelessly "install" at the device (after the usb flash) and these are some log files i get after the upload....

[component:204]: Component nextion.display took a long time for an operation (0.11 s).
[01:03:42][W][component:205]: Components should block for at most 20-30ms.
[01:03:43][E][uart:015]: Reading from UART timed out at byte 0!
[01:03:43][W][nextion:072]: Nextion is not connected! 
[01:03:43][W][component:204]: Component nextion.display took a long time for an operation (0.11 s).
[01:03:43][W][component:205]: Components should block for at most 20-30ms.
[01:03:43][D][sensor:094]: 'nspanelwhite Uptime seconds': Sending state 39.27200 s with 0 decimals of accuracy
[01:03:43][E][uart:015]: Reading from UART timed out at byte 0!
[01:03:43][W][nextion:072]: Nextion is not connected! 
[01:03:43][W][component:204]: Component nextion.display took a long time for an operation (0.11 s).
[01:03:43][W][component:205]: Components should block for at most 20-30ms.
[01:03:44][E][uart:015]: Reading from UART timed out at byte 0!
[01:03:44][W][nextion:072]: Nextion is not connected! 
[01:03:44][W][component:204]: Component nextion.display took a long time for an operation (0.11 s).
[01:03:44][W][component:205]: Components should block for at most 20-30ms.
[01:03:44][D][sensor:094]: 'nspanelwhite RSSI': Sending state -49.00000 dBm with 0 decimals of accuracy
[01:03:45][E][uart:015]: Reading from UART timed out at byte 0!

any ideas?

**Comment by edwardtfn** [comment]
What is in the panel's screen? The original Sonoff page?

**Comment by Anders-Falk** [comment]
Hi I had the same problem. 3.4.x versions all worked fine but ver 4 took forever to download the tft part. Used an RPI4 for serving the file. Had to unplug the panel to get it rebooted. Tried several times. Moved the file to another webserver, IIS, and then it worked for me.

**Comment by TeDeVPrime** [comment]
> What is in the panel's screen? The original Sonoff page? If that is the case, I would suggest taking a look at this: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload#10-use-an-older-nextion-library-for-esphome
> 
> If you got rid of the Sonoff page already, then it's about trying the `nspanel_blank.tft`, however I highly recommend you download that file to your local http server (Home Assistant?) and try to transfer from there.
> 
> It would be nice if you can capture the logs from ESPHome from right before you press the "Upload TFT" until like 10 or 15secs after that and then share it here, so we can understand better what is happening.

Thank you beautiful human!
it was driving me nuts. not it is working just fine!

question.... how do we change the ugly background? are there files with better images?

**Comment by edwardtfn** [comment]
> how do we change the ugly background?

Isn't that hard, but do you have to use the Nextion editor, which as far as I know is available only for Windows.
With the editor, select the tab related to pictures and replace the picture 0, which is the one used in most of the pages.
Please let me know if you get blocked.

**Comment by TeDeVPrime** [comment]
> > how do we change the ugly background?
> 
> Isn't that hard, but do you have to use the Nextion editor, which as far as I know is available only for Windows. With the editor, select the tab related to pictures and replace the picture 0, which is the one used in most of the pages. You will find in the repository the HMI files, which you can open the Editor and then generate a new TFT files. Please let me know if you get blocked.

ok this was my first time but i figured it out. i noticed that you haven't set the sta to "cop_image" so when i changed the image... there were black boxes all over the place. i changed them now so they look transparent for the background.

can you tell me how i could change the font style? i would like to go closer to the NSPANEL Pro official interface with font styles, sizes, etc.

i have to say that this is the first time that i am starting to like my nspanels..... even more than the NSPanel Pro that i have

**Comment by edwardtfn** [comment]
Changing fonts is very similar to changing pictures. You will find a tab for fonts in the same area and each component have a font id.
You can either replace a font, so all componentes using that font will be affected, or add a new font and then assigning it to specific components.
The fonts are in a Nextion format, but if you go to Tools > Font generator you can convert your system's fonts to the Nextion format. It's a bit cumbersome at the beginning, but you get used of that quickly.
Be aware that fonts are one of the biggest parts of a TFT file, so keep close eyes on file size and you may have more issues with bigger files.

**Comment by TeDeVPrime** [comment]
> Changing fonts is very similar to changing pictures. You will find a tab for fonts in the same area and each component have a font id. You can either replace a font, so all componentes using that font will be affected, or add a new font and then assigning it to specific components. The fonts are in a Nextion format, but if you go to Tools > Font generator you can convert your system's fonts to the Nextion format. It's a bit cumbersome at the beginning, but you get used of that quickly. Be aware that fonts are one of the biggest parts of a TFT file, so keep close eyes on file size and you may have more issues with bigger files.

i would like to change things to Roboto or Open Sans maybe with bold and so on.

any ideas about the weather icons that show black behind the image?

**Comment by edwardtfn** [comment]
> any ideas about the weather icons that show black behind the image?

Unfortunately this version of Nextion display doesn't support transparent color, so you will have to export each one of those pics, edit it's background, then replace in the HMI.
One option would be replacing that by icon font with bigger size, but in that case you will lose the multi-colour, as icons in fonts are monochromatic, and have to do some code change in the Blueprint (I would love to go this way if you find a nice fit).

**Comment by huubke80** [comment]
For some reason, I have the same type of problems updating the tft file. 

- used default config, esp home is flashed with 4.0.2 
- after updating the nspanel_blank.tft file there is some improvement installing the tft file. After a while a error occurs, then the panel reboots and stops.


![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/56635793/75f0bb77-7a28-4c9a-9bf9-b6b0c0384642)

**Comment by edwardtfn** [comment]
Could you please change your ESPHome yaml, on the `remote_package`, from `ref: main` to `ref: dev`, flash your panel again and then try to upload?
This have a new engine and will also collect more logs. I would appreciate if you can share the results here.

After that test, please revert back to `ref: main` otherwise it won't work with the new tft. 😉

**Comment by huubke80** [comment]
> Could you please change your ESPHome yaml, on the `remote_package`, from `ref: main` to `ref: dev`, flash your panel again and then try to upload? This have a new engine and will also collect more logs. I would appreciate if you can share the results here.
> 
> After that test, please revert back to `ref: main` otherwise it won't work with the new tft. 😉
[logs_nspanel-badkamer_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/12796832/logs_nspanel-badkamer_run.txt)

- upload from tft file was successful now
- logs attached.
