### ISSUE TITLE
Take default device icon if no icon is specified. 

### ISSUE THREAD

**Issue by bkbartk** [Blackymas/NSPanel_HA_Blueprint#1127]
Now. When no icon is specified. For switches a switch icon is shown and for lights a light bulb.
Is it possible to get de device icon specified in ha. 
I configured those so I always have the same icons in Lovelace. But unfortunately it doesn’t work on my Nspanel. 
I now have 2lightbulbs on my home screen.

**Comment by edwardtfn** [comment]
Could you please take a look at Developer Tools > States, pick some of those entities, can you see your selected icons on the attributes?
I would expect that one to have preference over the default icon.

**Comment by bkbartk** [comment]
![IMG_4707](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/17070805/d2c83fa0-ea69-46df-99bb-c1be39d3b0eb)
I can see the icon. 
but at least on the homepage is shows a bulb. I know I can overrule. But I didn’t yet. 
I believe this is also the case for the overview pages. But to be honest I have to check when I get home.

**Comment by bkbartk** [comment]
I use v4. 
if this is different in v4.0.2. I need to update.

**Comment by edwardtfn** [comment]
No, v4.0.2 works with icons exactly the same as v4.0.

**Comment by edwardtfn** [comment]
The icon engine was rebuilt for v4.2 (still on `dev`) so I believe this will be solved with that release.

**Comment by bkbartk** [comment]
thnx,
I was still planning on creating a fix for the single entity page but maybe now this isn't needed anymore.

**Comment by edwardtfn** [comment]
The new version is targeting ESPHome 2023.12.0, which may be released latter this week. It would be great if you can try v4.2dev when the new ESPHome is available and let me know if you still finding issues with icons. I will have some time next week and wanna use that to wrap up v4.2 and maybe we can release even before the end of the year.

**Comment by bkbartk** [comment]
I'm planning to update to v4.2dev for 2 weeks now and haven't found the time yet.

And with the upcoming holidays I won't be home much, So I will try to find some time but can't promise anything.
I noticed the new default is `esp-idf` which is great, but I will check `arduino` as I use an external component which is not `esp-idf` compatible yet.

I see in the release notes of esphome you have done a lot of work improving the nextion component(nicely done). I assume all this new/improved stuff is used in v4.2, so using esphome 2023.11.x probably will fail.

**Comment by edwardtfn** [comment]
> I'm planning to update to v4.2dev for 2 weeks now and haven't found the time yet.
> And with the upcoming holidays I won't be home much, So I will try to find some time but can't promise anything.

No rush. And wait a couple of days more until ESPHome 2023.12.0 is released (probably as that is required for v4.2.

> I noticed the new default is esp-idf which is great, but I will check arduino as I use an external component which is not esp-idf compatible yet.

That is the default for new users, but if you have serial flashed with arduino you should stay there. Everything in this project is supposed to work (and tested) in both, so you should be good.

**Comment by edwardtfn** [comment]
- #1556
