### ISSUE TITLE
Add MQTT Client config?

### ISSUE THREAD

**Issue by intersector** [Blackymas/NSPanel_HA_Blueprint#113]
Hello, first of all great job, i loved it from the first sight.
I would like to ask if you are going to add MQTT client configuration support, via blueprint ? Or with any other way?
Thanks

**Comment by Blackymas** [comment]
Thanks :)

you mean MQTT for esphome?

**Comment by intersector** [comment]
Yes, I am referring to this https://esphome.io/components/mqtt.html
I read to your documentation that is possible to manually create the .yaml file in order to have advanced configuration but i do not "see" how should i proceed. 
IS is possible have some guidance about it?
Thanks again!

**Comment by Blackymas** [comment]
copy the full code from here to you're esphome device

https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/nspanel_esphome.yaml

now you can change what you need. But we will not take over any support from here on
