### ISSUE TITLE
Update to 4.0 error when import new blueprint

### ISSUE THREAD

**Issue by patrick-foubert-56770** [Blackymas/NSPanel_HA_Blueprint#1130]
Hello, when i import new blueprint: 

Invalid blueprint: Unknown selector type language found for dictionary value @ data['blueprint']['input']['language']['selector']. Got OrderedDict([('language', OrderedDict([('languages', ['en', 'bg', 'hr', 'cs', 'da', 'nl', 'et', 'fi', 'fr', 'de', 'el', 'he', 'hu', 'id', 'it', 'lv', 'lt', 'nb', 'pl', 'pt', 'ro', 'ru', 'sk', 'sl', 'es', 'sv', 'tr', 'uk'])]))]) extra keys not allowed @ data['blueprint']['input']['alarm']['selector']['filter']. Got None extra keys not allowed @ data['blueprint']['input']['chip01']['selector']['filter']. Got None extra keys not allowed @ data['blueprint']['input']['chip02']['selector']['filter']. Got None extra keys not allowed @ data['blueprint']['input']['chip03']['selector']['filter']. Got None extra keys not allowed @ data['blueprint']['input']['chip04']['selector']['filter']. Got None extra keys not allowed @ data['blueprint']['input']['chip05']['selector']['filter']. Got None extra keys not allowed @ data['blueprint']['input']['chip06']['selector']['filter']. Got None extra keys not allowed @ data['blueprint']['input']['chip07']['selector']['filter']. Got None extra keys not allowed @ data['blueprint']

**Comment by edwardtfn** [comment]
Which version of Home Assistant are you running?

**Comment by patrick-foubert-56770** [comment]
Hi, probably to old (2023.2.5) :( i try update it and retry

**Comment by edwardtfn** [comment]
V4.0 requires at least Home Assistant v2023.5.0.
You have to either upgrade your Home Assistant (recommended) or downgrade to v3.4.1.

**Comment by patrick-foubert-56770** [comment]
Thanks, downgrade done, i will update :)

**Comment by patrick-foubert-56770** [comment]
Up and running after all HA updates :)
