### ISSUE TITLE
Panels all dead after 4.0/4.01 and 4.02 updates

### ISSUE THREAD

**Issue by noobey** [Blackymas/NSPanel_HA_Blueprint#1133]
Hi all,
Over the past week, I've been continuously flashing my 4 panels to update them to 4.0.

HA and ESP are up to day.

I've tried wirelessly (via ESPhome), and via wired today, but no matter what I do the panels either say "system data ERROR" or have a blank white screen.

I have a feeling I'm doing something wrong with the HMI as I'm not using it for anything (that I can tell).
My TFT update URL is https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft and seems to pull the TFT, but not sure what to do with the HMI, if that is even the issue.
<img width="455" alt="Screenshot 2023-10-01 at 13 23 18" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/24723294/6b1c9860-8335-489b-81d9-eb07327369ac">

They appear in HA, but have repeated UART errors and a TFT refresh took nearly 3 days on each.

Any help would be appreciated, thanks.

**Comment by WarMasterNL** [comment]
I have this same issue. For some reason updating the TFT takes a really long time (36 hours approximately) and you end up with a white screen. When reset (power cycled) you end up with the System Data Error again.

I've followed the upgrading instructions step by step but this situation is the result.

**Comment by oozimok** [comment]
Exactly the same problem. Tried to reset the cache. Upload an empty tft file and re-upload nspanel_eu.tft. I tried to download from the local machine and from the Internet. The result is the same - a very long data loading. I'm at 10 percent for now.
I'm thinking of rolling back to version 3 of nspanel.

**Comment by edwardtfn** [comment]
If after half an hour it isn't about to finish, just cancel it and start again. Those life-long transfers always fails at the end.

Have you succeeded transferring `nspanel_blank.tft`?

**Comment by pozek** [comment]
After 3 days same problem here, try to upload blank tft and after 1 hour nothing. tft dead. power up, nothing. all the steps described. nothing. 1 day and white screen after upload completed. 


20:57:08 | [W] | [nextion:396] | Nextion reported variable name invalid!
-- | -- | -- | --
20:57:08 | [W] | [nextion:396] | Nextion reported variable name invalid!
20:57:08 | [W] | [nextion:396] | Nextion reported variable name invalid!


20:59:10 | [D] | [nextion_upload:235] | Waiting for upgrade response
-- | -- | -- | --
20:59:10 | [E] | [uart:015] | Reading from UART timed out at byte 0!
20:59:11 | [E] | [uart:015] | Reading from UART timed out at byte 0!
20:59:11 | [E] | [uart:015] | Reading from UART timed out at byte 0!
20:59:11 | [D] | [nextion_upload:239] | Upgrade response is  4
20:59:11 | [D] | [nextion_upload:242] | Available 0 : 0x00
20:59:11 | [D] | [nextion_upload:242] | Available 1 : 0x00
20:59:11 | [D] | [nextion_upload:242] | Available 2 : 0x00
20:59:11 | [D] | [nextion_upload:242] | Available 3 : 0x05
20:59:11 | [D] | [nextion_upload:246] | preparation for tft update done
20:59:11 | [D] | [nextion_upload:274] | Allocating buffer size 65536, Heap size is 110640
20:59:11 | [D] | [nextion_upload:291] | Updating tft from "https://192.168.0.179:8123/local/nspanel_eu.tft" with a file size of 7442752 using 65536 chunksize, Heap Size 48560
20:59:11 | [D] | [nextion_upload:048] | Requesting range: bytes=0-16383
20:59:12 | [E] | [uart:015] | Reading from UART timed out at byte 0!
20:59:12 | [E] | [uart:015] | Reading from UART timed out at byte 0!
20:59:12 | [E] | [uart:015] | Reading from UART timed out at byte 0!
20:59:12 | [E] | [uart:015] | Reading from UART timed out at byte 0!
20:59:12 | [E] | [uart:015] | Reading from UART timed out at byte 0!
20:59:12 | [E] | [uart:015] | Reading from UART timed out at byte 0!

goodbye nspanel!

**Comment by pozek** [comment]
> Exactly the same problem. Tried to reset the cache. Upload an empty tft file and re-upload nspanel_eu.tft. I tried to download from the local machine and from the Internet. The result is the same - a very long data loading. I'm at 10 percent for now. I'm thinking of rolling back to version 3 of nspanel.

i try, nothing

**Comment by pozek** [comment]
> I have this same issue. For some reason updating the TFT takes a really long time (36 hours approximately) and you end up with a white screen. When reset (power cycled) you end up with the System Data Error again.
> 
> I've followed the upgrading instructions step by step but this situation is the result.

confirm same problem

**Comment by wolframkorth** [comment]
I have exactly the same problem. I've tried it several times. extremely long transmission times. And if you let it run anyway, you have a “white screen”.
Waste of life...

**Comment by edwardtfn** [comment]
We are working in a new code to replace ESPHome original TFT upload code, but it still on `dev`.

If you wanna try, change your ESPHome yaml, from `ref: main` to `ref: dev`, flash your panel and then try upload TFT again.
After that, please don't forget to change it back to `ref: main`.

**Comment by edwardtfn** [comment]
> Updating tft from "https://192.168.0.179:8123/local/nspanel_eu.tft" with a file size of 7442752 using 65536 chunksize, Heap Size 48560

@pozek, don't you have an "http" server? This transfer is pretty bad with "httpS".

**Comment by edwardtfn** [comment]
> My TFT update URL is https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft and seems to pull the TFT

@noobey, I hardly recommend using a local http server.

> but not sure what to do with the HMI, if that is even the issue.

Don't worry about HMI file. That is used only if you want to create a custom TFT file.

**Comment by WarMasterNL** [comment]
>  don't you have an "http" server? This transfer is pretty bad with "httpS".

The update TFT plainly fails when using http in stead of https.  A quick flash of the screen and reboot of the ESP. No loading.

**Comment by edwardtfn** [comment]
Could you please share your ESPHome logs from right before you press the upload button to the moment it restarts? It shouldn't be more than a few seconds if it is failing.

**Comment by oozimok** [comment]
On the `main` branch I tried to use the `nginx` web server running on port 80 (http).
The result was the same - slow loading.

----

The luck happened on branch `dev`:
  - Changed the ESPHome settings (nspanel) to the dev branch:
  ```
  packages:
    remote_package:
      url: https://github.com/Blackymas/NSPanel_HA_Blueprint
      ref: dev
      files: [nspanel_esphome.yaml]
      refresh: 300s
  ```
  - Downloaded the latest `nspanel_eu.tft` from the `dev` branch and uploaded it to nginx.
  - Cleared the cache (Clean Build Files) in the ESPHome settings (nspanel).
  - Uploaded the latest compiled firmware to nspanel.
  - Removed power from the panel and applied it again after a few seconds
  - Clicked on the "Update TFT display" button
  
After a quick update, NSPanel came to life. 

@edwardtfn thanks a lot!
@edwardtfn спасибо большое!

**Comment by pozek** [comment]
> 
> * Changed the ESPHome settings (nspanel) to the dev branch:
> 
> ```
> packages:
>   remote_package:
>     url: https://github.com/Blackymas/NSPanel_HA_Blueprint
>     ref: dev
>     files: [nspanel_esphome.yaml]
>     refresh: 300s
> ```
> 
> * Downloaded the latest `nspanel_eu.tft` from the `dev` branch and uploaded it to nginx.
> * Cleared the cache (Clean Build Files) in the ESPHome settings (nspanel).
> * Uploaded the latest compiled firmware to nspanel.
> * Removed power from the panel and applied it again after a few seconds
> * Clicked on the "Update TFT display" button
> 
> After a quick update, NSPanel came to life.
> 
> @edwardtfn thanks a lot! @edwardtfn спасибо большое!

I confirm, the procedure works for me too.
Good job !
Thank you

**Comment by WarMasterNL** [comment]
> Could you please share your ESPHome logs from right before you press the upload button to the moment it restarts? It shouldn't be more than a few seconds if it is failing.

[08:28:48][D][button:010]: 'wandpaneel Update TFT display' Pressed.
[08:28:48][D][main:1556]: Button pressed: Update TFT display
[08:28:48][D][binary_sensor:036]: 'wandpaneel Nextion display': Sending state OFF
[08:28:48][D][nextion_upload:169]: Connected
[08:28:48][D][nextion_upload:175]: Requesting URL: http://192.168.1.8/nspanel_eu.tft
WARNING wandpaneel.local: Connection error occurred: [Errno 104] Connection reset by peer
INFO Processing unexpected disconnect from ESPHome API for wandpaneel.local
WARNING Disconnected from API
INFO Successfully connected to wandpaneel.local

Nothing useful as far as I can determine.  And before you ask; Yes the nspanel_eu.tft is valid and accessable.

**Comment by noobey** [comment]
> > Could you please share your ESPHome logs from right before you press the upload button to the moment it restarts? It shouldn't be more than a few seconds if it is failing.
> 
> [08:28:48][D][button:010]: 'wandpaneel Update TFT display' Pressed. [08:28:48][D][main:1556]: Button pressed: Update TFT display [08:28:48][D][binary_sensor:036]: 'wandpaneel Nextion display': Sending state OFF [08:28:48][D][nextion_upload:169]: Connected [08:28:48][D][nextion_upload:175]: Requesting URL: http://192.168.1.8/nspanel_eu.tft WARNING wandpaneel.local: Connection error occurred: [Errno 104] Connection reset by peer INFO Processing unexpected disconnect from ESPHome API for wandpaneel.local WARNING Disconnected from API INFO Successfully connected to wandpaneel.local
> 
> Nothing useful as far as I can determine. And before you ask; Yes the nspanel_eu.tft is valid and accessable.

Exact same output here too.

**Comment by edwardtfn** [comment]
Have you tried `dev` a described [here](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1133#issuecomment-1742171643)?

**Comment by noobey** [comment]
> Have you tried `dev` as described [here](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1133#issuecomment-1742171643)?

Yes, sorry forgot to add that.
Here's the output and on the panel, I still have the same error message except now it's sideways, but I am 100% certain I have flashed with the EU TFT and not the US, so I'm not sure why its rotated the text.
<img width="781" alt="Screenshot 2023-10-02 at 07 57 55" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/24723294/33ac24ee-e8da-4c8f-b1d6-58851ee9a720">

**Comment by WarMasterNL** [comment]
> On the `main` branch I tried to use the `nginx` web server running on port 80 (http). The result was the same - slow loading.
> 
> The luck happened on branch `dev`:
> 
> * Changed the ESPHome settings (nspanel) to the dev branch:
> 
> ```
> packages:
>   remote_package:
>     url: https://github.com/Blackymas/NSPanel_HA_Blueprint
>     ref: dev
>     files: [nspanel_esphome.yaml]
>     refresh: 300s
> ```
> 
> * Downloaded the latest `nspanel_eu.tft` from the `dev` branch and uploaded it to nginx.
> * Cleared the cache (Clean Build Files) in the ESPHome settings (nspanel).
> * Uploaded the latest compiled firmware to nspanel.
> * Removed power from the panel and applied it again after a few seconds
> * Clicked on the "Update TFT display" button
> 
> After a quick update, NSPanel came to life.
> 
> @edwardtfn thanks a lot! @edwardtfn спасибо большое!

This worked for me with the distinct addition that I first had to load the nspanel_blank.tft (nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/dev/custom_configuration/nspanel_blank.tft") after which the definitive tft would load correctly.  (nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/dev/nspanel_eu.tft")

This would NOT work on main branch nor would http (local) downloads in neither case. 

What a shit show.

In any case; My NSpanel is operational again using the dev branch.

**Comment by noobey** [comment]
> > On the `main` branch I tried to use the `nginx` web server running on port 80 (http). The result was the same - slow loading.
> > The luck happened on branch `dev`:
> > 
> > * Changed the ESPHome settings (nspanel) to the dev branch:
> > 
> > ```
> > packages:
> >   remote_package:
> >     url: https://github.com/Blackymas/NSPanel_HA_Blueprint
> >     ref: dev
> >     files: [nspanel_esphome.yaml]
> >     refresh: 300s
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * Downloaded the latest `nspanel_eu.tft` from the `dev` branch and uploaded it to nginx.
> > * Cleared the cache (Clean Build Files) in the ESPHome settings (nspanel).
> > * Uploaded the latest compiled firmware to nspanel.
> > * Removed power from the panel and applied it again after a few seconds
> > * Clicked on the "Update TFT display" button
> > 
> > After a quick update, NSPanel came to life.
> > @edwardtfn thanks a lot! @edwardtfn спасибо большое!
> 
> This worked for me with the distinct addition that I first had to load the nspanel_blank.tft (nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/dev/custom_configuration/nspanel_blank.tft") after which the definitive tft would load correctly. (nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/dev/nspanel_eu.tft")
> 
> This would NOT work on main branch nor would http (local) downloads in neither case.
> 
> What a shit show.
> 
> In any case; My NSpanel is operational again using the dev branch.

Whats the best method to load a blank TFT? (I'm hoping there's a wireless way as I'm tired off continually popping off 4 different panels from the wall)

**Comment by edwardtfn** [comment]
"system data ERROR" means a corrupt TFT was loaded.

Are you still trying to transfer from GitHub directly?
Could you please share the yaml used for ESPHome settings? Please remove any sensitive information before sharing.

**Comment by WarMasterNL** [comment]
> > > On the `main` branch I tried to use the `nginx` web server running on port 80 (http). The result was the same - slow loading.
> > > The luck happened on branch `dev`:
> > > 
> > > * Changed the ESPHome settings (nspanel) to the dev branch:
> > > 
> > > ```
> > > packages:
> > >   remote_package:
> > >     url: https://github.com/Blackymas/NSPanel_HA_Blueprint
> > >     ref: dev
> > >     files: [nspanel_esphome.yaml]
> > >     refresh: 300s
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > * Downloaded the latest `nspanel_eu.tft` from the `dev` branch and uploaded it to nginx.
> > > * Cleared the cache (Clean Build Files) in the ESPHome settings (nspanel).
> > > * Uploaded the latest compiled firmware to nspanel.
> > > * Removed power from the panel and applied it again after a few seconds
> > > * Clicked on the "Update TFT display" button
> > > 
> > > After a quick update, NSPanel came to life.
> > > @edwardtfn thanks a lot! @edwardtfn спасибо большое!
> > 
> > 
> > This worked for me with the distinct addition that I first had to load the nspanel_blank.tft (nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/dev/custom_configuration/nspanel_blank.tft") after which the definitive tft would load correctly. (nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/dev/nspanel_eu.tft")
> > This would NOT work on main branch nor would http (local) downloads in neither case.
> > What a shit show.
> > In any case; My NSpanel is operational again using the dev branch.
> 
> Whats the best method to load a blank TFT? (I'm hoping there's a wireless way as I'm tired off continually popping off 4 different panels from the wall)

I all did it wirelessly yes. Just replace the nextion_update_url in the esphome yaml file with the line I provided in my previous post. Then click install, wait for it to finish. Then click the Update TFT display after which the nspanel_blank.tft will load. If it's succesful a QR code will be displayed on the panel. After which you can repeat the entire procedure with the final tft file.

**Comment by WarMasterNL** [comment]
> I all did it wirelessly yes. Just replace the nextion_update_url in the esphome yaml file with the line I provided in my previous post. Then click install, wait for it to finish. Then click the Update TFT display after which the nspanel_blank.tft will load. If it's succesful a QR code will be displayed on the panel. After which you can repeat the entire procedure with the final tft file.

After this entire process you can then revert back to the main branch for the ESP config for the ESP config itself and the TFT file. Thus downgrading your version to 4.02 (the originally targeted version anyway). This works well.

**Comment by edwardtfn** [comment]
I've just pushed new code to `dev` adding more log, so if you still having issues, please use that one and share here the new logs, please.

**Comment by gravy72** [comment]
I have had the same issues and over the past 4 days have been trying all the suggestions above.  Got to the QR screen using the blank tft file, but it still would not update to the nspanel_eu.tft downloaded from the main branch.  That was until I pulled the TFT file directly from the (https) github rather than  downloaded copy (http) in my local folder.  It now works great.  At first I thought that maybe there was an issue with my Home Assistant directory, but that would not explain why a lot of people were having the same issue.

**Comment by edwardtfn** [comment]
Thanks for sharing your journey. In fact, we are investigating many things, but so far I got a feeling that both the ESPHome firmware and also the TFT files got much bigger with v4.x and this is when the problems started.
The test I'm running right now is to reduce the size of the chunk when reading from the http server and then sending to Nextion display, and this looks to be helping a lot, so I wouldn't eliminate the chances of a hardware limitation on either side (including Home Assistant side, as many times the logs are showing ESPHome disconnecting from API).
It's hard to get all the details from everyone, so I couldn't find any pattern. This transfer works quite solid for me, even when simulating a slow wifi, etc., but as I have a quite powerful HA server, I might not be facing issues on HA side that others could have.
Apart of rebuilding this transfer process, I've also cleaned-up the TFT and could reduce it size quite a lot, but with a loss as the biggest icon font was removed, but I still believe this can come back without big change on file size.
Next I will clean-up the ESPHome size. I'm sure we have a lot to save there.

**Comment by wolframkorth** [comment]
I also have no success with http server and switching from main to dev.
The upload starts quickly.
But it is never finished. No matter whether nspanel_us.tft or blank...
Always at the last chunk I have the following error:

[18:28:10][D][script.upload_tft.upload_by_chunks:2478]: Uploaded 88.6 %, remaining 30020 bytes
[18:28:11][D][script.upload_tft.upload_by_chunks:2478]: Uploaded 90.2 %, remaining 25924 bytes
[18:28:11][D][script.upload_tft.upload_by_chunks:2478]: Uploaded 91.7 %, remaining 21828 bytes
[18:28:11][D][script.upload_tft.upload_by_chunks:2478]: Uploaded 93.3 %, remaining 17732 bytes
[18:28:11][D][script.upload_tft.upload_tft:2660]: Heap Size 123952, Bytes left 17732
[18:28:11][D][script.upload_tft.upload_by_chunks:2419]: Requesting range: bytes=245760-263492
[18:28:11][W][script.upload_tft.upload_by_chunks:2440]: HTTP Request failed; URL: http://192.168.2.101/www/nspanelus.tft; Error: , retries(2/5)
WARNING nspanelflur.local: Connection error occurred: [Errno 104] Connection reset by peer
INFO Processing unexpected disconnect from ESPHome API for nspanelflur.local
WARNING Disconnected from API

**Comment by edwardtfn** [comment]
Ok. I will try to duplicate this here and come back to you.

**Comment by edwardtfn** [comment]
If you click [this link](http://192.168.2.101/www/nspanelus.tft) you should have the file downloaded (using the same server as your panel).
Is the file downloaded correctly to your computer? How big (in bytes) is the downloaded file?

**Comment by edwardtfn** [comment]
You can use this to have two upload tft buttons (one pointing to blank): https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/en/customization.md#button-to-upload-nspanel_blanktft

Also, you can go Developer Tools > Services and call the service `esphome.xxxxx_upload_tft_url` so you can type the url manually without the need to re-flash.

By the way, may I ask you to try that service using this url? https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/custom_configuration/nspanel_blank.tft

Usually I wouldn't recommend transferring directly from GItHub, but let's try that to try finding the root cause of this issue.

**Comment by wolframkorth** [comment]
The Download via GitHub worked sometimes Yesterday for the blank File. I got the white Screen. But then the Download from the nspanel_us.tft was very slowly and IT ends with system Error. Then i tryd the http Method. Maybe i should try another http Server...

**Comment by edwardtfn** [comment]
> The Download via GitHub worked sometimes Yesterday for the blank File. I got the white Screen.

Unless you are using a very old file, `nspanel_blank.tft` should display a QR code.

> Then i tryd the http Method. Maybe i should try another http Server...

Yeah.
Have you tried your Home Assistant embedded http server?

**Comment by adri123** [comment]
How do you set up the HA http embedded server ? 
My google searches was unsuccesful.

**Comment by wolframkorth** [comment]
today`s trial:
1. used "https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/custom_configuration/nspanel_blank.tft" --> works --> got the QR Code
2. used "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" --> works (yippieh!!!) --> got the blue boot screen. (btw: the upload was less fast but constantly. maybee it takes 10mins --> did you already reduce the chunk size?)
3. after some seconds: i got a black screen and HA give me the message: NSPanel component version mismatch, Panel: nspanelflur
TFT: 4.0.2
ESPHome: 4.1dev3

OK--> seems that ESPHome is to new because of all my trials???


Blueprint: 4.0.2 (expected 4.0.2)

**Comment by deejaybeam** [comment]
> How do you set up the HA http embedded server ? My google searches was unsuccesful.

https://www.home-assistant.io/integrations/http/#hosting-files
https://esphome.io/components/display/nextion.html#uploading-a-tft-file

**Comment by deejaybeam** [comment]
> today`s trial:
> 
> 1. used "https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/custom_configuration/nspanel_blank.tft" --> works --> got the QR Code
> 2. used "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" --> works (yippieh!!!) --> got the blue boot screen. (btw: the upload was less fast but constantly. maybee it takes 10mins --> did you already reduce the chunk size?)
> 3. after some seconds: i got a black screen and HA give me the message: NSPanel component version mismatch, Panel: nspanelflur
>    TFT: 4.0.2
>    ESPHome: 4.1dev3
> 
> OK--> seems that ESPHome is to new because of all my trials???
> 
> Blueprint: 4.0.2 (expected 4.0.2)

you have sucessfully installed the esphome-config from current dev-branch, but the blueprint and the tft-file itself are from the main-branch.
You have to install the tft and the blueprint also from dev-branch

**Comment by edwardtfn** [comment]
As you have installed the TFT successfully, I would suggest you to switch back to `ref: main` and then flash your ESPHome again, so you be all good with the latest stable version.

**Comment by wolframkorth** [comment]
works now with ref: main.

TANK YOU!!

**Comment by noobey** [comment]
Im dying trying to figure this out.

Here's my code that I'm using in ESP home for this panel to upload the blank TFT.
I've tried local and hosted, neither work. Meaning they all result in the panel still displaying the "system data ERROR" message after a reboot.

Can anyone advise what I'm doing wrong please? (apologies if its obvious!)

<img width="1166" alt="Screenshot 2023-10-04 at 09 40 43" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/24723294/2936501c-0d86-49a2-a62c-ff147ab73c2b">

**Comment by noobey** [comment]
> Im dying trying to figure this out.
> 
> Here's my code that I'm using in ESP home for this panel to upload the blank TFT. I've tried local and hosted, neither work. Meaning they all result in the panel still displaying the "system data ERROR" message after a reboot.
> 
> Can anyone advise what I'm doing wrong please? (apologies if its obvious!)
> 
> <img alt="Screenshot 2023-10-04 at 09 40 43" width="1166" src="https://user-images.githubusercontent.com/24723294/272517540-2936501c-0d86-49a2-a62c-ff147ab73c2b.png">

Ok update.
I changed method to using Developer Tools in HA and called the TFT Upload via URL service.

Good news = 2 of my panels now work fine.
Bad news = 2 of them display "stackbot error". Using the same TFT files as the other 2 that work fine.
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/24723294/12f246dd-dd3e-4c09-846c-938c80c1f079)


Open to suggestions......!
Once I get this resolved, I don't think I'll ever willingly update these panels again though. This has been a total pain.

**Comment by edwardtfn** [comment]
On your settings, in remote packages area, please change `ref: main ` to `ref: dev`, flash your panel and try transfer again. Please capture the ESPHome logs and share here. That version will provide more logs.

After this test, please change back to `ref: main` and flash it again.

**Comment by EBME2** [comment]
I had a similar issue upgrading from v3.4 to v4.02 for me I upgraded ESPHome, blueprint and then tried to update the TFT. It would get to about 20-40% of the TFT transfer then just drop to a really slow pace which I would have to abort and flash with nspanel_blank.tft to recover.

The fix for me was to roll back the NSPanel ESPHome to version 3.4 yaml  and recompile and flash via Wi-Fi, this allowed me to upgrade the TFT to v4.02 normally. Once the TFT was uploaded with version 4.02 and I recompiled the NSPanel ESPHome with V4.02 and flashed that normally and all was good.

Looks like 4.02 for some has issues with transferring the TFT for some of us.

**Comment by edwardtfn** [comment]
> Looks like 4.02 for some has issues with transferring the TFT for some of us.

The Upload TFT engine in 4.0 is exactly the same used in 3.4, what changes is the amount of memory available in ESPHome.
On v4.1 (still in `dev`) we rebuilt this engine using smaller chunk sizes to transfer, requiring less memory available. It looks way more stable than what it was in v3.4.
I still working in other fronts to reduce the size of memory used by the rest of the code and also to reduce the size of the TFT file, which certainly will be a huge improvement.
Unfortunately these days I'm quite out of time to finalise that, but I'm quite optimistic we will soon have something much smoother.

**Comment by EBME2** [comment]
Really appreciate the amount of effort that goes into this. For me personally a cut down version NSPanel that is compiled and used just for the TFT transfer before would be OK, I know it is a bit more work for us to do with a two step upgrade, but we should all expect a bit of pain.

Thanks again for all the work that goes into this.

**Comment by edwardtfn** [comment]
That is not a bad idea. The Upload TFT itself probably takes around 15% of the whole memory available.

**Comment by edwardtfn** [comment]
@noobey, have you had a chance to try the `ref: dev`?

**Comment by edwardtfn** [comment]
I can understand.
I will close this for now, but please get in contact again when you want to try again and I will be more than happy to help.

**Comment by mtk1976** [comment]
Same issue, Stackbot, I tried to reboot and returns again

**Comment by edwardtfn** [comment]
Do you mind opening a new issue and sharing your panels yaml and, if you can collect those, some logs when booting up?

**Comment by mtk1976** [comment]
[logs_nspanel_logs.txt](https://github.com/user-attachments/files/24314981/logs_nspanel_logs.txt)

No boot

**Comment by mtk1976** [comment]
[logs_nspanel_run.txt](https://github.com/user-attachments/files/24316056/logs_nspanel_run.txt)

More log trying to install again, nspanel don't start

**Comment by mtk1976** [comment]
Esp Builder: install wifi OK
Esp Builder: clear ok
Devices: Update TFT OK
Blueprint: updated OK
Now it's working.
Great job, update process is traumatic, but when it works your work are great. Thanks
