### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by NielsG24** [Blackymas/NSPanel_HA_Blueprint#1134]
is it posible to change the background of th ehome page ?

**Comment by edwardtfn** [comment]
Well, there's no way to change this with as a setting in the blueprint, but you can still editing the HMI file and generate a new tft only for you.
You will have to update every time you get a new version, but as this is not more than 5min work, you probably will be fine.

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/78ca1583-4799-404c-9d90-399cc7e20406)

You need [Nextion Editor](https://nextion.tech/nextion-editor/#_section1) to be able to do those changes.

**Comment by grigi** [comment]
Is there's some way of automating nextion tft files? Because then you could optionally override the background, and it would build the tft file to your specifications...
Looking at the desktop app there, I'm not seeing a way to just setup a CI that could run on the typical Linux system that ESPHome tends to be installed on...

**Comment by edwardtfn** [comment]
I don't think this is possible. Nextion is a quite closed system for this.
But we definitely can make the main HMI file more friendly to that, so you just have to change the background pic when a new release come...
Also, if you want to share your background to everyone we probably could think about a way to have a user selectable background on the Blueprint.
Why don't you share your background so I can play a bit with it?

**Comment by ghostridernrw40** [comment]
![20231018_103452](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/117640399/c3ec1c36-4af7-49df-a46d-c515ccb55220)
![wuppertaler-schwebebahn-andreas-henk](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/117640399/40cceacd-7911-408d-bac9-99da8b77a142)

Hi, I'm having a similar problem. Changing the background is not a problem, but all icons etc. are displayed with black backgrounds. If possible, transparency should be set here, because this is the only way to make the backgrounds look good. At this point, we would like to thank you again for your work.

**Comment by edwardtfn** [comment]
The challenge here comes from the Nextion display used by NSPanel. Those displays can't support transparency, so you must create the pictures with the same background.
The is basically the reason we haven't used the wave background in some pages (like button pages, where each button is a picture).
For text and icons, however, the background can be set as a "crop picture" and if it matches the pic in the background it will behaves like a transparent text.
We can do some task force to make all text and icon transparent to it's background, but unfortunately you still have to deal with the pics from your side. 😩

**Comment by edwardtfn** [comment]
I've changed the "crop picture" in all the different pages I found those. The new HMI are on `dev` and hopefully will be included in the coming release.
Could you please let me know if that is better than before. 😉

**Comment by ghostridernrw40** [comment]
![20231110_065335](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/117640399/510b7f46-26a8-40e3-8e24-d4524c577ff4)

Hi Edward, I used the new HMI and replaced the image, but the blueprint settings are not adopted and therefore I don't see e.g. the key labeling etc. Regards

**Comment by edwardtfn** [comment]
Have you updated the ESPHome and Blueprint for your test or only TFT?

**Comment by ghostridernrw40** [comment]
Hi, I have everything on the current DEV version. 

Now it works very well, but the button pages are all empty. On the homepage and the weather pages, only the big icon is still a problem. Here are a few photos for you and an error message from Home Assistant.

![error](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/117640399/9682df42-9e70-4e65-a069-455e75b2c831)
![20231110_104318](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/117640399/12f391a3-9853-4669-839a-b61fe7242fec)
![20231110_104520](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/117640399/3adecda1-307a-48a8-9de3-6611dc113084)
![20231110_104527](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/117640399/c89a4ef4-b6ec-4ab1-b6a6-16edc773c3de)
![20231110_104507](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/117640399/0aa5b680-f7cb-49a0-bc3c-a972b93147da)

**Comment by ghostridernrw40** [comment]
Changed to new nspanel_blueprint.yaml and now the button pages show everything :-) 

If you can fix the problem with the weather icon it would be great. Then i will check everything else again.

![20231110_111641](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/117640399/e648ecd0-3d86-465a-b4f1-8780610744e3)

**Comment by ghostridernrw40** [comment]
On the settings page the "button_back" crop image has to be removed. Correct is "image" with pic 33.

**Comment by ghostridernrw40** [comment]
If you set the chip font size to 32 px the images were cut. 

Perfect with 24px
![20231110_114511](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/117640399/56fa5deb-0f87-4307-a447-0d2b26eff301)

Cut with 32px
![20231110_114440](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/117640399/1bc1ac5e-546b-42a1-a510-ca067ec1fb7a)

**Comment by edwardtfn** [comment]
You have to update your TFT. 😞

**Comment by ghostridernrw40** [comment]
I am using the latest files from the dev rep. The TFT and HMI files are from yesterday.

**Comment by edwardtfn** [comment]
I've bumped versions to 4.1dev6 to avoid confusion.
Will double check the icons... Thanks for finding that.

> If you can fix the problem with the weather icon it would be great.

That one is really challenging. As I mentioned earlier, this Nextion can't handle transparency on pics, so the alternative here would be replace those by real icons. This will require adding another font (which will probably increase the file a lot, unless we work to create a font with only the selected icons - I've never done that) and we will lose the multi-color icons (like when the cloud is white and the rain drops are blue, sun yellow). We can work in change colors, but font-based icons will always be 1-color.

**Comment by edwardtfn** [comment]
> If you set the chip font size to 32 px the images were cut.

Could you please confirm if you still have that with v4.1dev6?

**Comment by ghostridernrw40** [comment]
Hi, with Dev 6 it works now. 32px is displayed correctly. However, I discovered a new problem on the button pages. I have various lamps there, among other things, and as soon as you switch off a lamp in Dev 6, the brightness information in percent remains until you leave the page. This problem does not exist in the current main version. A photo is attached. The lamp in the library is turned off, but you can still see the brightness.

![20231110_155102](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/117640399/32dfe098-f02a-420a-94a0-37e6a825aa47)

**Comment by andyyyy2306** [comment]
Hi all !
Is it possible to remove the background picture ?
I would likt to have a nice black background. :-)

Andyyyy

**Comment by edwardtfn** [comment]
This is not impossible, but it requires some work every time a new version is available. A black background wouldn't be that hard, as most of the pictures have black in the back, but still some work.

This model of Nextion cannot support transparent color, so all the components, like the buttons, have that same picture in the back. If you edit those pictures and import again with Nextion Editor, you will be fine.
For black it will not be that much.

**Comment by pics195** [comment]
Hello, could you please detail how to change the background.

**Comment by edwardtfn** [comment]
You will have to use the [Nextion Editor](https://nextion.tech/nextion-editor/) to edit the HMI files your can download from our repo ([/advanced/hmi](https://github.com/Blackymas/NSPanel_HA_Blueprint/tree/main/advanced/hmi)) and then generate a new TFT file, which could be uploaded to your device.

To edit the background with Nextion Editor, you will have to export the picture, edit it with your preferred picture editor, then replace it into the picture list.
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/7e2baaaf-01c3-4cb2-b732-13f96586e5d2)

Then export it as TFT:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/ed517096-688d-4adf-9b79-fb6a35b754b0)

**Comment by pics195** [comment]
It works fine, thank you very much.

**Comment by N0edL** [comment]
How did you guys managed to upload the new tft to the display!

**Comment by edwardtfn** [comment]
> How did you guys managed to upload the new tft to the display!

Do you mind creating a new issue specifically for this and sharing a bit more details on what you are trying to achieve?
