### ISSUE TITLE
`notification_clear` does not update home page

### ISSUE THREAD

**Issue by bkbartk** [Blackymas/NSPanel_HA_Blueprint#1136]
it took me a while to find it,
but I think I did now.
```
service: esphome.xxxx_send_command_printf
data:
  cmd: is_alarm=1
```
or `is_entities` or 'is_qrcode' or 'is_notification=0'
does not update the homepage,

it only updates if you leave the homepage and come back.

maining

```
service: esphome.xxxx_notification_clear
data: {}

```
does not remove the message icon from the homepage until you go to some other page,

I tried, but couldn't get it it work in esphome, I don't actually know it this should be in the tft file or not.

**Comment by edwardtfn** [comment]
What are you trying to achieve?

`is_alarm` will be used only when loading the page home to decide if the alarm button should be shown or not.
During the boot, the Blueprint send to ESPHome if an alarm entity is assigned to the home page and, if so, will set this variable to `1`, so when the home page is loaded, the icon is show.
You shouldn't be setting this via service call, as this also requires an alarm entity to be assigned.

**Comment by edwardtfn** [comment]
> does not remove the message icon from the homepage until you go to some other page,

This looks like a bug.

**Comment by edwardtfn** [comment]
`service: esphome.xxxx_send_command_printf` is not intended to refresh any page. If you want to update components using this service call, you have to handle the necessary updates.

**Comment by bkbartk** [comment]
The only thing I actually wanted to do was notification_clear. 
and then I checked the behavior of other icons. And they all worked the same way. 

But then only. 
notification_clear does not remove the icon, only change color until the home page is reloaded.

**Comment by edwardtfn** [comment]
So, I believe I've a fix to this. It will be included in the next release.

**Comment by bkbartk** [comment]
check
I don't think you need this one
```
id(disp1).send_command_printf("is_notification=1");
            if (id(current_page).state.c_str() == "home") id(disp1).show_component("bt_notific");
            id(disp1).goto_page("notification");
            id(disp1).set_component_text_printf("notification.notifi_label", "%s", label.c_str());
```
as the notification opens the line after,
if the notification closes it's ok.

so only this on
```
        - &notification_clear
          lambda: |-
            id(disp1).send_command_printf("is_notification=0");
            if (id(current_page).state.c_str() == "home") id(disp1).hide_component("bt_notific");
            id(notification_label).publish_state("");
            id(notification_text).publish_state("");
        - switch.turn_off: notification_unread
```

and some code cleanup I see ;)
if I have time I will test tonight

**Comment by bkbartk** [comment]
not sure what `.c_str()` does, if I would guess, convert to string,
but when it is in the code it doesn't work but if you remove it.
```
if (id(current_page).state == "home") id(disp1).hide_component("bt_notific");
```
it works

**Comment by edwardtfn** [comment]
Yeah, I've already seen that and removed. I always mess up with this thing of strings being pointers in c++. 😞

**Comment by edwardtfn** [comment]
I believe this issue is already resolved on `dev`, so I will close this and we reopen if needed.
