### ISSUE TITLE
After ESPhome update screen stuck in white display

### ISSUE THREAD

**Issue by Sliver88** [Blackymas/NSPanel_HA_Blueprint#1137]
Hi,

After the latest update in ESPHome on my Home Assistance installation i got a white screen. I reboot it, rebooted the Home Assistance, checked all the settings (for possible naming issue) and i even reverted to pre-ESPHome update but still the issue was there.
Home assistant was passing commands (eg. i could open and close the switches from the lovelace button).

I thought to restage the whole panel from scratch. When i firstly tried to install it i had some issues which finally were resolved with the help of the [edwardtfn](https://github.com/edwardtfn).
The case was: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/645

Of course i tried everything step by step with the files that were attached and worked then, but now when i install nspanel_nextion_pr2956-factory.bin or nspanel-factory.bin the panel lights up in black with a vertical message: "Data corrupt" so i can't proceed with anything.

Is there a new file i could use and might lost in my 5 hour now trying? 
Please spare me, my wife can not open the bathroom light and we all know what that means............ 🗡️ 

Thank you in advance,
Jim

**Comment by edwardtfn** [comment]
So, as I understood right now you have a pure white screen with nothing written on that, is that correct?

**Comment by edwardtfn** [comment]
Could you please share the yaml used for ESPHome settings? Please remove any sensitive information before sharing.

**Comment by edwardtfn** [comment]
I would propose one new thing...
There's a new code on `dev` now which will have a different routine for uploading TFT but, most important, will collect more logs.
So if you wanna try that, please change in your setting, on the `remote_package` area, from `ref: main` to `ref: dev`, then flash your device again and try the Upload TFT, but this time with an eye in your ESPHome logs.
Please share the logs here when it fails (or when it finishes successfully but in the end you didn't got the right thing in your panel.

**Comment by Sliver88** [comment]
> So, as I understood right now you have a pure white screen with nothing written on that, is that correct?

Hi edwardfn... I hope you are doing great. No at this moment i have this:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/23452507/d333e6e2-accb-4682-9928-b0b49c664889)

after flashing the device with this: nspanel_nextion_pr2956-factory.bin

The rest like nspanel-factory.bin and nspanel_nextion_pr2956.bin are giving me just a black screen.

So what file should i flash the device with? 

Thank you in advance once more and sorry for late reply i was out of town.

**Comment by edwardtfn** [comment]
I still think you should try this: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1137#issuecomment-1744187168

I don't know from where you got `nspanel_nextion_pr2956.bin` but, anyways, this is most likely the ESPHome firmware. With that suggestion above you will be using the code from our dev brach, which will provide more logs, so it might be easier to figure out how to handle the TFT transfer.

Try to install that one from `dev`, press the button Upload TFT and capture the logs... I'm sure that will help.

**Comment by Sliver88** [comment]
Ok thanks.. i truly cant remember where i found it. i had in my folder of ESPHome after the resolution. i might had put it there by mistake. I will try your suggestion and i ll return with news..

**Comment by Sliver88** [comment]
Well i cant install it like this.. i guess i ll need to flash with a .bin file. but the ones you had uploaded on the other case are not working :P

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/23452507/82f96d39-3953-4c29-93f2-acffabbc2649)

**Comment by edwardtfn** [comment]
Why don't you select the "wirelessly" install?

**Comment by Sliver88** [comment]
> Why don't you select the "wirelessly" install?

Tried but the device is not even connected to the wifi most probably. It is in the above state and the message from ESP:

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/23452507/5c629289-65e9-434f-9d86-081c23feea9f)

**Comment by edwardtfn** [comment]
Understood.
Look, I can see it took 941 seconds to compile... this is the time it will take on that "Preparing for download"... you have to wait.
Or you can use the option "Manual download". The process (and time to wait) is the same, but at least you have some visual feedback. You will be able to download the file and then you can go https://web.esphome.io/ to transfer the file.

**Comment by Sliver88** [comment]
Well still the same. The .bin file was created i flashed it successfully and still i get the same screen with the Data Error... Any ideas?

**Comment by Sliver88** [comment]
> Well still the same. The .bin file was created i flashed it successfully and still i get the same screen with the Data Error... Any ideas?

I now have the panel opened via IP and i can control it. Also Home Assistant found it again. But i keep getting the issue i initially posted. with dev it had the same screen error but didn't connect to wifi. With the usual one at least i got it working from Hass

**Comment by edwardtfn** [comment]
I want the logs from when you press the button Upload TFT

**Comment by Sliver88** [comment]
I retried everything and it just worked this time. Mysterious but i won't complain. Sorry for the false alarm as it seems and thank you very much for the instant replies and willingness to help.

Cheers
