### ISSUE TITLE
No blueprint in boot page after updating TFT display

### ISSUE THREAD

**Issue by LucGft** [Blackymas/NSPanel_HA_Blueprint#1140]
After updating TFT display, the boot page is showing Please wait...
TFT: 4.0.2
ESPHome: 4.0.2
Blueprint:

Blueprint stays empty for a few minutes and after it shows Retry 1, 2, ....9 ...

Rebooting or upadting another time doesn't change anything.

Anybody has this issue ?
Any help will be much appreciated.

And thanks for this project!

**Comment by edwardtfn** [comment]
Have you updated the Blueprint?

https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#2-update-blueprint

**Comment by LucGft** [comment]
I've followed all the steps.
In the folder config/blueprints/automation/Blackymas:
nspanel_blueprint.yaml is 497.8Kb (date: today)

Do I have to change something in this file?

Thx

**Comment by edwardtfn** [comment]
It looks a bit smaller than I expected, but anyways, try to go Developer Tools > Yaml and click to reload automations, then go to Settings > System > Logs and take a look for any error connected to that automation.
You can also open the automation (Settings > Automation & Script) and look for the version number in the text at the top. It should be v4.0.2.
If everything looks good, try to restart your Home Assistant.

**Comment by LucGft** [comment]
In (Settings > Automation & Script) NSPanel Configuration, the version is v4.0.2

But NSPanel device (REQUIRED) is empty.
I'm sure I've selected when installing.

Something is wrong here, I select the NSPanel device, click on the blue button "Save".
A popup opens called "Rename", I click the button "Rename". I quit and come back to the configuration, the NSPanel device is empty again.

**Comment by LucGft** [comment]
And finaly it's working, I don't know if it happened when I saved the configuration and changed the name?

**Comment by edwardtfn** [comment]
What about home assistant logs?

**Comment by LucGft** [comment]
No error, only warning:

Logger: aioesphomeapi.connection
Source: runner.py:179
First occurred: 21:30:00 (15 occurrences)
Last logged: 22:52:31

nspanel @ 192.168.86.39: Connection error occurred: Ping response not received after 90.0 seconds
nspanel @ 192.168.86.39: Connection error occurred: [Errno 104] Connection reset by peer
nspanel @ 192.168.86.39: Connection error occurred: nspanel @ 192.168.86.39: Connection lost

**Comment by LucGft** [comment]
It works very great now. 

Many thanks for your help and support Edward 👍
