### ISSUE TITLE
Long press on cover/shutter item does not show the panel page

### ISSUE THREAD

**Issue by Zylazy** [Blackymas/NSPanel_HA_Blueprint#1142]
When you long press a cover/shutter entity, you got a panel with open and close buttons and a slider.
Tis feature does not work since I have upgraded to v4.0.2.

**Comment by Blackymas** [comment]
Hi,
I have tried it with my Ikea blinds but could not find any problem

**Comment by edwardtfn** [comment]
This is duplicated. Please take a look at #1063 .

**Comment by Zylazy** [comment]
Oh, I am sorry. I missed that issue.
I have checked the latest post, and tried it. I have downloaded and replaced my v4.0.2 blueprint with v4.1dev3, but it did not help.
What else should I do to test it?

**Comment by edwardtfn** [comment]
So, about 4.1, is the short click working as expected?
When you said it isn't working, how you expect it to work and how it is working?
The more details the better. 😉

**Comment by Zylazy** [comment]
I am expecting the same functionality as it was before, so after a long press on the cover item it should display the confiure panel like this:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/8330252/aa15f9b1-9590-46f5-b34e-55bc053f854f)
But either I do a short click or double click it just moves the cover up or down.
Currently I am running the following versions:
TFT: 4.0.2
ESPHome: 4.0.2
Blueprint: 4.1dev3 (expected 4.1dev3)

**Comment by edwardtfn** [comment]
> Currently I am running the following versions:
TFT: 4.0.2
ESPHome: 4.0.2
Blueprint: 4.1dev3 (expected 4.1dev3)

You shoukd have all the 3 components at the same version. It is very likely to have issues when micin different versions.

As we haven't changed anything related to this since v4.0.2 I would suggest to return your blueprint to that version.

**Comment by edwardtfn** [comment]
> If I do a long press, then it does not do anything

Look, this changed on v4.0.
Before, the long press was always opening the detailed page, regardless if the entity support the setting or not.
With v4.0 we changed this to show on the detailed page only the features that are supported by that entity specifically. For covers, that means the cover should support the `set_position` feature.

With the short click you should be able to close, stop or open your cover, so all the 3 buttons should be covered.

Just to understand the issue you are reporting, could you please open Developer Tools, go to States tab and find your cover, then let me know what is the value for the attribute `supported_features`.

Also, I wanna know if the short click is working to start or stop the move ente of your cover. Could you please double check?

And, you mentioned before you got the detailed page with the long press. Was you able to select the position using the slider before?

**Comment by Zylazy** [comment]
You must be right Edward, the supported features value is 11
Th short click works fine, but sometimes the cover does not repond to the first command, so I should force to open/close/stop it by pressing again the button. But with the short click it changes all the time. So for example I want to close it, I click once, but it does react becase of some bug or so, I click again, but the it sends a stop command, I click it againg but it will try to open it in stead of closing it. It is irritaing and thats way i miss so much that panel. :(
I am not sure if I was using the slider earlier, but i did defenately the buttons.

**Comment by edwardtfn** [comment]
11 contains `set_speed`, so I would expect the detailed screen to open with the long press.
Looks like a bug. I will take a look.

```
 SET_SPEED = 1
 OSCILLATE = 2
 DIRECTION = 4
 PRESET_MODE = 8
```

**Comment by edwardtfn** [comment]
> Th short click works fine, but sometimes the cover does not repond to the first command, so I should force to open/close/stop it by pressing again the button

This is probably due to your cover taking too long to leave the transitory states (`opening` or `closing`).
Take a look at its state on the same Developer Tools screen where you got the attributes values... If that state is `opened` or `closed`, it will send the command to open or close, but if that is not the case, the panel will send a `stop` first, which might be interpreted by you as not responding to the first click.

By the way, which integration are you using for this cover?

**Comment by Zylazy** [comment]
It is a template entity. It has value_template property and open_cover, close_cover and stop_cover services.

**Comment by edwardtfn** [comment]
Do you mind sharing the yaml you used to create this template? I wanna try to replicate this issue here.
Please remove any private info before sharing.

**Comment by geni0602** [comment]
I have to revise my replay from #1063 my covers still don't react on long press(no additional menu) and short press is only up and down( no stop) current blueprint 4.1dev3

If you want to test you can create a matt cover with some payload for up down and stop. Mqtt covers don't have set position per default

**Comment by Zylazy** [comment]
Dear Edward!
Sorry, I missed your reply. Sure. Here you are.

(configuration.yaml)
...
cover: !include cover.yaml
...

(cover.yaml)
- platform: template
  covers:
    living_room_window:
      device_class: blind
      friendly_name: Living room window
      value_template: "..."
      open_cover:
        service: script.control_shutter_living_room_window_up
      close_cover:
        service: script.control_shutter_living_room_window_down
      stop_cover:
        service: script.control_shutter_living_room_window_stop

**Comment by edwardtfn** [comment]
I believe this issue is already resolved on `dev`, so I will close this and we reopen if needed.
