### ISSUE TITLE
NSPanel Wont connect to WiFi

### ISSUE THREAD

**Issue by akj501** [Blackymas/NSPanel_HA_Blueprint#1143]
Hi,

I have been banging my head trying to get this working. I have installed ESPHome onto my home assistant, have followed the guide and flashed the board. However when I power the board on I get lots of errors where it can't connect to my SSID (Pretty-Fly-For-A-WiFi).

I have checked my config and it all seems correct including the SSID and password which are held in the secrets file. My Wifi units are ubiquiti unifi and the nspanel is close to the unit.

Can anyone shed some light on this? - error logs from the nspanel are below:

[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[D][wifi:443]: Found networks:
[I][wifi:487]: - 'Pretty-Fly-For-A-WiFi' [redacted]▂▄▆█
[D][wifi:488]:     Channel: 1
[D][wifi:489]:     RSSI: -51 dB
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[I][wifi:277]: WiFi Connecting to 'Pretty-Fly-For-A-WiFi'...
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[W][wifi_esp32:465]: Event: Disconnected ssid='Pretty-Fly-For-A-WiFi' bssid=[redacted] reason='4-Way Handshake Timeout'
[W][wifi:612]: WiFi Unknown connection status 0
[I][wifi:277]: WiFi Connecting to 'Pretty-Fly-For-A-WiFi'...
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[W][wifi_esp32:465]: Event: Disconnected ssid='Pretty-Fly-For-A-WiFi' bssid=[redacted] reason='4-Way Handshake Timeout'
[W][wifi:612]: WiFi Unknown connection status 0
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[D][wifi:428]: Starting scan...
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[D][wifi:443]: Found networks:
[I][wifi:487]: - 'Pretty-Fly-For-A-WiFi' [redacted]▂▄▆█
[D][wifi:488]:     Channel: 6
[D][wifi:489]:     RSSI: -87 dB
[I][wifi:487]: - 'Pretty-Fly-For-A-WiFi' [redacted]▂▄▆█
[D][wifi:488]:     Channel: 1
[D][wifi:489]:     RSSI: -54 dB
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[I][wifi:277]: WiFi Connecting to 'Pretty-Fly-For-A-WiFi'...
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[W][wifi_esp32:465]: Event: Disconnected ssid='Pretty-Fly-For-A-WiFi' bssid=[redacted] reason='4-Way Handshake Timeout'
[W][wifi:612]: WiFi Unknown connection status 0
[I][wifi:277]: WiFi Connecting to 'Pretty-Fly-For-A-WiFi'...
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[W][wifi_esp32:465]: Event: Disconnected ssid='Pretty-Fly-For-A-WiFi' bssid=[redacted] reason='4-Way Handshake Timeout'
[W][wifi:612]: WiFi Unknown connection status 0
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[D][wifi:428]: Starting scan...
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[D][wifi:443]: Found networks:
[I][wifi:487]: - 'Pretty-Fly-For-A-WiFi' [redacted]▂▄▆█
[D][wifi:488]:     Channel: 1
[D][wifi:489]:     RSSI: -89 dB
[I][wifi:487]: - 'Pretty-Fly-For-A-WiFi' [redacted]▂▄▆█
[D][wifi:488]:     Channel: 1
[D][wifi:489]:     RSSI: -54 dB
[I][wifi:487]: - 'Pretty-Fly-For-A-WiFi' [redacted]▂▄▆█
[D][wifi:488]:     Channel: 6
[D][wifi:489]:     RSSI: -86 dB
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[I][wifi:277]: WiFi Connecting to 'Pretty-Fly-For-A-WiFi'...
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[D][sensor:094]: 'ntc_source': Sending state 1.95100 V with 2 decimals of accuracy
[D][resistance:039]: 'resistance_sensor' - Resistance 16198.1Ω
[D][sensor:094]: 'resistance_sensor': Sending state 16198.07324 Ω with 1 decimals of accuracy
[D][ntc:026]: 'frontroompanel Temperature' - Temperature: 14.5°C
[D][sensor:094]: 'frontroompanel Temperature': Sending state 14.52710 °C with 1 decimals of accuracy
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[W][wifi:601]: WiFi network can not be found anymore.
[W][wifi_esp32:462]: Event: Disconnected ssid='Pretty-Fly-For-A-WiFi' reason='Probe Request Unsuccessful'
[W][wifi:627]: Restarting WiFi adapter...
[I][wifi:277]: WiFi Connecting to 'Pretty-Fly-For-A-WiFi'...
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[D][sensor:094]: 'frontroompanel Uptime seconds': Sending state 37.93300 s with 0 decimals of accuracy
[W][wifi_esp32:462]: Event: Disconnected ssid='Pretty-Fly-For-A-WiFi' reason='Probe Request Unsuccessful'
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[D][wifi:428]: Starting scan...
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[D][wifi:443]: Found networks:
[I][wifi:487]: - 'Pretty-Fly-For-A-WiFi' [redacted]▂▄▆█
[D][wifi:488]:     Channel: 1
[D][wifi:489]:     RSSI: -56 dB
[I][wifi:487]: - 'Pretty-Fly-For-A-WiFi' [redacted]▂▄▆█
[D][wifi:488]:     Channel: 6
[D][wifi:489]:     RSSI: -87 dB
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[D][wifi:492]: - [redacted] [redacted]▂▄▆█
[I][wifi:277]: WiFi Connecting to 'Pretty-Fly-For-A-WiFi'...
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[W][wifi:591]: Error while connecting to network.
[W][wifi:627]: Restarting WiFi adapter...
[W][wifi_esp32:465]: Event: Disconnected ssid='Pretty-Fly-For-A-WiFi' bssid=[redacted] reason='Authentication Failed'
[I][wifi:277]: WiFi Connecting to 'Pretty-Fly-For-A-WiFi'...
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[W][wifi_esp32:465]: Event: Disconnected ssid='Pretty-Fly-For-A-WiFi' bssid=[redacted] reason='4-Way Handshake Timeout'
[W][wifi:612]: WiFi Unknown connection status 0
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected! 
[E][uart:015]: Reading from UART timed out at byte 0!
[W][nextion:072]: Nextion is not connected!

**Comment by edwardtfn** [comment]
Could you please share your ESPHome settings? Please make sure to remove any private info before sharing.

**Comment by akj501** [comment]
> Could you please share your ESPHome settings? Please make sure to remove any private info before sharing.

Sure,

**This is the yaml for the panel:**

substitutions:

###### CHANGE ME START ######


  device_name: "frontroompanel" 
  wifi_ssid: !secret wifi_ssid
  wifi_pass: !secret wifi_password

  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft"

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

**This is the secrets yaml:**

# Your Wi-Fi SSID and password
wifi_ssid: "Pretty-Fly-For-A-WiFi"
wifi_password: "Changed2018"

**Comment by edwardtfn** [comment]
I see 2 different issues in your logs:

1. The network rejected the connection:
```
[W][wifi_esp32:465]: Event: Disconnected ssid='Pretty-Fly-For-A-WiFi' bssid=[redacted] reason='Authentication Failed'
```

Don't you have any MAC address filter or other filter in your network that could be preventing this connection?

2. Nextion is not connected
This is the screen itself, which is not visible to ESPHome. Which makes me wonder if your system is powered by line (110/220VAC) or only by your serial interface.

**Comment by akj501** [comment]
> I see 2 different issues in your logs:
> 
> 1. The network rejected the connection:
> 
> ```
> [W][wifi_esp32:465]: Event: Disconnected ssid='Pretty-Fly-For-A-WiFi' bssid=[redacted] reason='Authentication Failed'
> ```
> 
> Don't you have any MAC address filter or other filter in your network that could be preventing this connection?
> 
> 2. Nextion is not connected
>    This is the screen itself, which is not visible to ESPHome. Which makes me wonder if your system is powered by line (110/220VAC) or only by your serial interface.

I have checked the credentials in secrets.yaml and they are correct.

There is currently no mac address filtering setup, or any other kind of filtering.

The screen is currently being powered by a usb to serial adapter (5v pin)

**Comment by edwardtfn** [comment]
Your settings looks OK.

The only thing I would recommend is to use a local url for TFT instead of pointing to GitHub. This is not related to the problem you described now, but can be an issue later.

```
nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft"
```

**Comment by akj501** [comment]
> Your settings looks OK.
> 
> The only thing I would recommend is to use a local url for TFT instead of pointing to GitHub. This is not related to the problem you described now, but can be an issue later.
> 
> ```
> nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft"
> ```

have tried both to see if it makes any difference and it doesn't

**Comment by edwardtfn** [comment]
> The screen is currently being powered by a usb to serial adapter (5v pin)

Have you tried assembling the device and powering via it's back plate (110/220VAC)? That would be my suggestion if you haven't tried yet.

**Comment by akj501** [comment]
> > The screen is currently being powered by a usb to serial adapter (5v pin)
> 
> Have you tried assembling the device and powering via it's back plate (110/220VAC)? That would be my suggestion if you haven't tried yet.

I did try this late last night, but will try again now and report back. I assume if it does work it will appear in home assistant.

**Comment by akj501** [comment]
I have plugged it into the mains and it's powered on. In the top right corner there is a WiFi symbol which has a ! mark next to it.

I have checked within my unifi console and it hasn't connected

**Comment by akj501** [comment]
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/129897021/299efff7-0e5f-48a3-953e-6b1ac2487412)

Theses are the Wifi setting currently.

**Comment by edwardtfn** [comment]
> In the top right corner there is a WiFi symbol which has a ! mark next to it.

Could you please send a picture of this screen so we can understand better what you have installed?

**Comment by akj501** [comment]
Sure, here it is below:

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/129897021/334894e0-87ba-4eec-a3de-f39428336e8d)

**Comment by akj501** [comment]
I have also tried disabling 5Ghz on my units and that hasn't made any difference.

**Comment by edwardtfn** [comment]
Ok, this screen is probably the original one from Sonoff, so please ignore any info there as this isn't being updated by ESPHome.
As I can understand, you still cannot see your device on Home Assistant on in your Wi-Fi router, right?

**Comment by akj501** [comment]
I have also created a network called "esp" with the password as "esphome1" and setting it as a 2.4Ghz network only and this has made no difference. Before flashing with ESPHome I did successfully connect to the Wifi on the stock firmware and all worked fine.

Running out of ideas to try next.

**Comment by akj501** [comment]
> Ok, this screen is probably the original one from Sonoff, so please ignore any info there as this isn't being updated by ESPHome. As I can understand, you still cannot see your device on Home Assistant on in your Wi-Fi router, right?

Correct, looking at the logs it doesn't connect at all. I have also confirmed this in the unifi system and it's not connecting

**Comment by edwardtfn** [comment]
And I believe you have already double checked your password...

Have you tried restarting your router?

https://community.home-assistant.io/t/solved-esphome-disconnected-ssid-wifinetworkname-reason-4-way-handshake-timeout/388563/3

**Comment by akj501** [comment]
I have double checked my password and even created a new network but no luck. I have reset my unifi units but not my router - will try if you think that would help?

**Comment by edwardtfn** [comment]
> ![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/129897021/299efff7-0e5f-48a3-953e-6b1ac2487412)
> 
> 
> 
> Theses are the Wifi setting currently.

Which authentication type are you using? WPA?

**Comment by edwardtfn** [comment]
> I have reset my unifi units but not my router - will try if you think that would help?

I don't know if that will help, but if you see that link I shared a couple of people mentioned it was fixed with a restart.

**Comment by akj501** [comment]
> > I have reset my unifi units but not my router - will try if you think that would help?
> 
> I don't know if that will help, but if you see that link I shared a couple of people mentioned it was fixed with a restart.

Restarted router and unifi units, still the same issue.

Just a thought, currently the nspanel is unable to connect it creates a hotspot - however I am unable to connect to it as I don't know what the password is. Is there anyway to specify that password in the yaml file?

**Comment by akj501** [comment]
Something else I have just tried, I made a hotspot on my phone with the same SSID and password and the unit is still reporting the same issue when logging.

**Comment by akj501** [comment]
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/129897021/7b5ab5ba-9d4f-46c1-938b-6eea594b9881)

The nspanel is showing it own WiFi, but if I try and connect to it and put the Wi-Fi password in it doesn't connect

**Comment by akj501** [comment]
> Look, the password should be the same, so if it isn't working, this password is losing somewhere in the process.
> 
> So, I would try to create some very simple ESPHome code just for the initial flash, then when you have your panel connected, go for the full ESPHome yaml from this project. My only tip is to use as OTA the final wifi password, otherwise you will have to follow the process to change it later.
> 
> Just a moment and I will propose some basic code.

Hey, after much faffing around I think I have managed to get it working on my test wifi network. I copied the code down the "nspanel_esphome.yaml" file locally and edited the wifi setting directly in there. That seems to have worked, however I am just going to test on my primary WiFi and will report back.

**Comment by edwardtfn** [comment]
Try this:

```yaml
esphome:
  name: frontroompanel

esp32:
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret wifi_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "frontroompanel Fallback Hotspot"
    password: "UgiRCUvk150h"

captive_portal:
```

**Comment by akj501** [comment]
ok, so I have narrowed it down to the secrets file, for whatever reason if I edit the "nspanel_esphome.yaml" and put the WiFi credentials directly in there the nspanel connects without any issues.

I can only assume the secrets file is causing the issue?

**Comment by edwardtfn** [comment]
Do you have a blank space in your password?

**Comment by akj501** [comment]
No spaces in the password, I gave up in the end and just entered the password details "nspanel_esphome.yaml" file - not sure how this will impact me security wise.

**Comment by edwardtfn** [comment]
You just should remember that this file contains your password before sharing it. Secret files maks harder to share by accident.
May I ask you to try one thing around the password?
On the original `nspanel_esphome.yaml`, in the `substitutions`, add `wifi_password: !secret wifi_password` just like it was before, but in the `wifi` area, use `password: "${wifi_password}"`. Note that I've added `"` when compared to before.

**Comment by edwardtfn** [comment]
So, any progress with this?

**Comment by akj501** [comment]
Hi Edward,

Haven't got round to looking at this, will keep you posted when I do :)

**Comment by maxtheobald** [comment]
Hot the Same issue on 3 of 8 Panel, Maybe more cause i don't have set them all up for now.

**Comment by edwardtfn** [comment]
> Hot the Same issue on 3 of 8 Panel, Maybe more cause i don't have set them all up for now.

Could you please share more details? Maybe it would be better if you create another issue for your case.

**Comment by edwardtfn** [comment]
@akj501, I'm reading your messages again and come one question to my mind...
Is your secrets file inside the ESPHome folder or are you trying to use the same file from Home Assistant?
If you don't have a secrets file into esphome folder, create one (`secrets.yaml`) with the following:
```yaml
<<: !include ../secrets.yaml 
```
This will instruct ESPHome to use the same secrets file from Home Assistant.

**Comment by edwardtfn** [comment]
Please take a look at this: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1238#issuecomment-1804644825
