### ISSUE TITLE
Unable to update TFT

### ISSUE THREAD

**Issue by akj501** [Blackymas/NSPanel_HA_Blueprint#1144]
Hi,

I have managed to get my nspanel to connect to the WiFi and it has now appeared in HA and in ESPHome as online. However when I click on update TFT the nspanel reports the following errors:

<html>
<body>

18:22:45 | [D] | [nextion_upload:169] | Connected
-- | -- | -- | --
18:22:45 | [D] | [nextion_upload:175] | Requesting URL: https://192.168.0.10:8123/local/nspanel_eu.tft
18:22:46 | [D] | [nextion_upload:209] | Updating Nextion ...
18:22:46 | [D] | [nextion_upload:235] | Waiting for upgrade response
18:22:46 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:46 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:47 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:47 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:47 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:47 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:47 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:47 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:47 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:47 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:47 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:47 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:48 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:48 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:48 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:48 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:48 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:48 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:48 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:48 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:22:48 | [D] | [nextion_upload:239] | Upgrade response is  20
18:22:48 | [D] | [nextion_upload:242] | Available 0 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 1 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 2 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 3 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 4 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 5 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 6 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 7 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 8 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 9 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 10 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 11 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 12 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 12 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 13 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 13 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 14 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 15 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 16 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 17 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 18 : 0x00
18:22:48 | [D] | [nextion_upload:242] | Available 19 : 0x00
18:22:48 | [D] | [nextion_upload:248] | preparation for tft update failed 0 ""
18:22:48 | [D] | [nextion_upload:310] | Restarting Nextion
18:22:50 | [D] | [nextion_upload:313] | Restarting esphome

</body>
</html>

**Comment by edwardtfn** [comment]
I need more detailed log...

Please do this:
1. In your ESPHome yaml, on the `remote_package` area, change from `ref: main` to `ref: dev`.
2. Flash (ESPHome) your panel again
3. Click again Upload TFT.
4. You will notice a more detailed log. Please capture that and share here.
5. After the transfer (or failure), change it back to `ref: main` and flash it again.

**Comment by akj501** [comment]
I ended up uploading a blank TFT file and then uploaded the nspanel_eu.tft again and it seems to be a lot quicker, although it is still uploading after an hours or so...

**Comment by edwardtfn** [comment]
> still uploading after an hours or so...

It shouldn't take that long...
Could you please share the ESPHome logs?

**Comment by akj501** [comment]
> > still uploading after an hours or so...
> 
> It shouldn't take that long... Could you please share the ESPHome logs?

From the nspanel?

**Comment by akj501** [comment]
> I need more detailed log...
> 
> Please do this:
> 
> 1. In your ESPHome yaml, on the `remote_package` area, change from `ref: main` to `ref: dev`.
> 2. Flash (ESPHome) your panel again
> 3. Click again Upload TFT.
> 4. You will notice a more detailed log. Please capture that and share here.
> 5. After the transfer (or failure), change it back to `ref: main` and flash it again.

I don't have this in my nspanel_esphome.yaml file??

**Comment by edwardtfn** [comment]
So please try with this one: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/dev/nspanel_esphome.yaml

**Comment by akj501** [comment]
ok will do but can't see "remote_package" in there?

**Comment by akj501** [comment]
Uploaded as you said and it seems to be uploading much much quicker, will keep you posted on the results.

**Comment by akj501** [comment]
ok, its booted up but nothing works - for example if I touch the screen it doesn't do anything. It looks like there is some form of mismatch:

[21:56:21][D][script.timer_dim:1731]: Dimming the display to 100%
[21:56:32][D][sensor:094]: 'ntc_source': Sending state 1.46600 V with 2 decimals of accuracy
[21:56:32][D][resistance:039]: 'resistance_sensor' - Resistance 8952.7Ω
[21:56:32][D][sensor:094]: 'resistance_sensor': Sending state 8952.67188 Ω with 1 decimals of accuracy
[21:56:32][D][ntc:026]: 'frontroompanel Temperature' - Temperature: 27.5°C
[21:56:32][D][sensor:094]: 'frontroompanel Temperature': Sending state 27.51072 °C with 1 decimals of accuracy
[21:56:49][D][text_sensor:064]: 'frontroompanel NSPanel event': Sending state '{"page": "boot", "event": "timeout", "value": 1, "version": "4.0.2", "display_mode": "1"}'
[21:56:49][E][text_sensor.nspanelevent:1231]: Starting
[21:56:49][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[21:56:49][E][text_sensor.nspanelevent:1239]: page: boot
[21:56:49][E][text_sensor.nspanelevent:1240]: component: null
[21:56:49][E][text_sensor.nspanelevent:1241]: value: 1
[21:56:49][E][text_sensor.nspanelevent:1242]: entity: 
[21:56:49][D][nextion_textsensor:014]: Processed text_sensor "nspanelevent" state "{"page": "boot", "event": "timeout", "value": 1, "version": "4.0.2", "display_mode": "1"}"
[21:56:49][W][component:204]: Component nextion.display took a long time for an operation (0.07 s).
[21:56:49][W][component:205]: Components should block for at most 20-30ms.
[21:56:53][D][script.check_versions:2202]: ESPHome version: 4.1dev3
[21:56:53][D][script.check_versions:2203]: TFT version: 4.0.2
[21:56:53][E][script.check_versions:2204]: TFT version mismatch!
[21:56:53][D][script.check_versions:2205]: Blueprint version: 4.0.2
[21:56:53][E][script.check_versions:2206]: Blueprint version mismatch!

**Comment by edwardtfn** [comment]
You finally have TFT at version 4.0.2 🎉
Now you have to revert your ESPHome to the previous one from main: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/nspanel_esphome.yaml

Don't try to transfer TFT again. You already have the right one.
With the right ESPHome everything should work.

**Comment by akj501** [comment]
Hi, managed to get it all working.

Thanks for all your help
