### ISSUE TITLE
TFT Update: Model does not match

### ISSUE THREAD

**Issue by rwagoner** [Blackymas/NSPanel_HA_Blueprint#1145]
When updating the TFT display on the US model it switches to a white screen with the below in red. I'm using the nspanel_us.tft file with a file size of 7,340KB.

https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/nspanel_us.tft

Model does not match
Device Model:
NX4832F035_011C

**Comment by edwardtfn** [comment]
Have you tried a power cycle in your device?

**Comment by rwagoner** [comment]
I have power cycled it. It switch to the GitHub URL for nspanel_us.tft vs using the Home Assistant URL. I was able to flash it, but now I have a black screen with "System Data ERROR!"

**Comment by rwagoner** [comment]
Finally got it up and running! What worked was switching nextion_update_url to a http URL with IP address and changing "ref: main" to "ref: dev".

**Comment by edwardtfn** [comment]
Remember to change it back to `ref: main`.
