### ISSUE TITLE
Alarm panel

### ISSUE THREAD

**Issue by chadfaurie** [Blackymas/NSPanel_HA_Blueprint#1146]
I use a Sia protocol alarm (ajax), which does not update with on the nspanel, all control buttons are disabled and no matter the state it does not update the icon on the home screen

My workaround was to create a template alarm panel in home assistant and setup dummy arm_away, arm_home and disarm actions for the panel to work correctly even though service calls will fail (you can't arm or disarm an ajax alarm system via home assistant)

Hope this helps someone else and possibly becomes a fix in one of the next releases

**Comment by edwardtfn** [comment]
Could you please go to Developer Tools, tab States, then find your alarm entity and share here it's state and Attributes? That will help to understand why it isn't working.
Please make sure to hide any sensitive information.

**Comment by chadfaurie** [comment]
State is `armed_away`

Current attributes:
```
code_format: null
changed_by: null
code_arm_required: true
last_zone: '1'
last_code: CL
last_message: '2'
last_id: null
last_timestamp: '2023-10-05T04:00:10+00:00'
friendly_name: Home Alarm
supported_features: 0
```

**Comment by edwardtfn** [comment]
Ok. The fact that all buttons are unavailable is connected to your alarm not supporting any feature, which is expected in a listen-only integration, however the state is available, so you should be able to see its state on the home page.
One point to discuss is if it should (and how) show the related button in a different color oj the detailed page or even if that page should be shown (or just an icon at home page as other domains).

**Comment by chadfaurie** [comment]
So thats one of the strage parts is that even though as you mentioned it is listen-only the icon does not change, I have had to enable buttons for it to change, hence my workaround

I dont really care to be able to arm and disarm from my nspanel or home assistant, but I do use it as an indicator for certain rooms that will be armed when I am home

I can have a look at the code as well, would you mind pointing me in the right direction? I am assuming it would be in the automation blueprint?

**Comment by edwardtfn** [comment]
> I can have a look at the code as well, would you mind pointing me in the right direction? I am assuming it would be in the automation blueprint?

That would be great!
I'm pretty busy on finding a replacement for the Upload TFT engine provided by Nextion component on ESPHome, so any help would be very welcome.

It would be better if you work with `dev`, as I've already started (and pending finishing) some clean-up and as part of that I've moved the page constructor to a different place, so it would be easier for me if you look at that in it's final place.

Basically, the Blueprint only reads the states and attributes from the alarm entity and send that info to ESPHome, where the page is then created.

On ESPHome you will find the alarm settings service around https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/dev/nspanel_esphome.yaml#L157
That service should update the icon on home page and then, if alarm page is visible, should update that page.
On the blueprint you will find a call for that service around https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/dev/nspanel_blueprint.yaml#L7948 (when the page is opened) or https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/dev/nspanel_blueprint.yaml#L9293 (when the alarm state changes - the case you mentioned isn't working).
As the blueprint only reads data and send to ESPHome, I bet the issue is on ESPHome side.

**Comment by edwardtfn** [comment]
The problem with nothing shown on the Alarm page is probably related to your entity having `supported_features=0`, and on ESPHome side you will find in the code that is used to gray out all the buttons.

**Comment by edwardtfn** [comment]
> I am very new to home assistant

Welcome!!  😃 

> The issue I have is I can't set or disarm my alarm (Alarmo) via the NSpanel the status updates when the alarm is set and disarmed. if I try to set the alarm I press the alarm home mode button a keypad pops up and I can enter the arm code I then press the tick button and the alarm will net set its also the same if the alarm is set I can't disarm the alarm the same thing happens.

Could you please check if "[Allow the device to make Home Assistant service calls](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/en/alarm.md#allow-the-device-to-make-home-assistant-service-calls)" is enabled in your ESPHome device? It must be enabled if your alarm use a pin code.

**Comment by eddiebullman** [comment]
> > I am very new to home assistant
> 
> Welcome!! 😃
> 
> > The issue I have is I can't set or disarm my alarm (Alarmo) via the NSpanel the status updates when the alarm is set and disarmed. if I try to set the alarm I press the alarm home mode button a keypad pops up and I can enter the arm code I then press the tick button and the alarm will net set its also the same if the alarm is set I can't disarm the alarm the same thing happens.
> 
> Could you please check if "[Allow the device to make Home Assistant service calls](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/en/alarm.md#allow-the-device-to-make-home-assistant-service-calls)" is enabled in your ESPHome device? It must be enabled if your alarm use a pin code.

Have check this which was on and still no joy

**Comment by eddiebullman** [comment]
ignore the last comment it is now working with Alamo thanks edwardtfn

**Comment by eddiebullman** [comment]
The issue has now returned after updating to HA 11 can't via set Alarmo via NSpanel but status is updated correctly

**Comment by eddiebullman** [comment]
The issue has now returned after updating to HA 11 can't via set Alarmo via NSpanel but status is updated correctly

**Comment by edwardtfn** [comment]
@eddiebullman, could you please share the attributes of your alarm's entity? You can find it under Developer Tools, tab States.
Please make sure you removed any private info before sharing.

**Comment by eddiebullman** [comment]
> @eddiebullman, could you please share the attributes of your alarm's entity? You can find it under Developer Tools, tab States. Please make sure you removed any private info before sharing.

Sorry for late reply but Wifi has me rebuilding the bathroom bath the so not allowed to play with my toys

so I think this is what you asked for 

code_format: number
changed_by: Home
code_arm_required: true
arm_mode: null
open_sensors: null
bypassed_sensors: null
delay: null
icon: mdi:shield-home
friendly_name: Alarmo
supported_features: 11

Thanks

**Comment by edwardtfn** [comment]
@chadfaurie, I believe this is solved in `dev`. Please let me know if you have a chance to test it as I cannot duplicate the issue here.

**Comment by eddiebullman** [comment]
have update HA and NSpanel to the latest and once again can't set or unset alarmo via NSpanel but it will update status to show if set and un set via a Zigbee keypad

**Comment by eddiebullman** [comment]
Ok so updated to 4.1.3 for blueprint & ESP but can't get TFT to update to 4.1.3 still 4.1.1. I can now set Alarmo from the NSPanel :)

**Comment by edwardtfn** [comment]
By the way, TFT v4.1.3 is exactly the same as v4.1.1. The only change is the version number. 😉
