### ISSUE TITLE
question: control backlight through automation

### ISSUE THREAD

**Issue by lecrams** [Blackymas/NSPanel_HA_Blueprint#1148]
Is there a way to turn the panel into sleep? I see a wake up service but no sleep service.
Or is there a way to directly control the backlight

**Comment by lecrams** [comment]
Answered already in different issue

**Comment by edwardtfn** [comment]
I've just added some ideas to the customization docs (which is still in `dev`): https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/dev/docs/en/customization.md#sleep--wake-up-buttons
Please take a look and let me know, or maybe we can add the other solution you found.
