### ISSUE TITLE
Keine TFT version

### ISSUE THREAD

**Issue by Satzende** [Blackymas/NSPanel_HA_Blueprint#1149]
Hallo, 

mein homeass sagt mir das ich keine tft version habe. 

`[D][sensor:094]: 'ntc_source': Sending state 1.58100 V with 2 decimals of accuracy
[D][resistance:039]: 'resistance_sensor' - Resistance 10300.9Ω
[D][sensor:094]: 'resistance_sensor': Sending state 10300.87305 Ω with 1 decimals of accuracy
[D][ntc:026]: 'testpanel Temperature' - Temperature: 24.3°C
[D][sensor:094]: 'testpanel Temperature': Sending state 24.33437 °C with 1 decimals of accuracy
[W][nextion:396]: Nextion reported variable name invalid!
[D][sensor:094]: 'testpanel Uptime seconds': Sending state 297.15601 s with 0 decimals of accuracy
[W][nextion:396]: Nextion reported variable name invalid!
[W][nextion:396]: Nextion reported variable name invalid!
[W][nextion:396]: Nextion reported variable name invalid!
[D][sensor:094]: 'testpanel RSSI': Sending state -52.00000 dBm with 0 decimals of accuracy
[W][nextion:396]: Nextion reported variable name invalid!
[W][nextion:396]: Nextion reported variable name invalid!
[W][nextion:396]: Nextion reported variable name invalid!`

![Bildschirmfoto vom 2023-10-05 15-20-44](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/6745567/311ba9c3-da48-41dd-8af3-b34291d8e50c)

habe das vidoe befolgt https://www.youtube.com/watch?v=3afPFg6kUdc&ab_channel=SmartHomeyourself

wo bekomme ich die tft version her?

**Comment by kroessig** [comment]
Hast du die Datei nspanel_eu.tft  im rdner www gespeichert? 
Falls nein, hier downloaden und ab in den Ordner damit. (https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/nspanel_eu.tft)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/139384422/e0664548-2946-47f6-9d9a-73c219a438c3)

Anschließend unter Geräte --> ESPHome --> Panel auswählen und "update TFT" drücken.
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/139384422/7a555392-b807-43e7-a087-5f654aa4a63a)

Hoffe das Hilft.

**Comment by Satzende** [comment]
@kroessig danke für deine Antwort.
Das lest sich bei mir nicht hochladen. Nahm an das es wegen der fehlenden version sei. 

`[05:42:47][E][uart:015]: Reading from UART timed out at byte 0!
[05:42:47][W][nextion:072]: Nextion is not connected! 
[05:42:47][W][component:204]: Component nextion.display took a long time for an operation (0.11 s).
[05:42:47][W][component:205]: Components should block for at most 20-30ms.`

**Comment by kroessig** [comment]
Ich hatte am Anfang auch Probleme, in den Foren hieß es immer, man braucht ein stabiles WLan etc. 
Hatte alles nichs geholfen.  Unter esphome, steht dort dein Panel als online?
Dann habe ich die [LoveLaceUI Alternative](https://github.com/joBr99/nspanel-lovelace-ui) versuchen wollen und in den Foren dadurch den Hinweis bekommen, zuerst das ["nspanel_blank.tft"](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/421dc7127416dfc86626a7e8bb28999e56c04bcb/custom_configuration/nspanel_blank.tft) zu flashen. 
Das ging und anschließend ging auch das nspanel_eu.tft.

**Comment by Satzende** [comment]
geschafft :  5v von usbuart and die Platine angeschlossen, siehe bild https://github.com/arendst/Tasmota/discussions/15034.

esphome: 
`

substitutions:

###### CHANGE ME START ######

  device_name: "testpanel" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://192.168.10.53:8123/local/nspanel_eu.tft"
  #nextion_update_url: "http://192.168.10.53:8123/local/small.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

uart:
  tx_pin: 16
  rx_pin: 17
  baud_rate: 115200
  id: tf_uart

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####`

den uplodedes tft  starte ich von HA aus mit dem "tft_uplaod"(oder so änlich) button.

zuerst die blank.tft dann die normale. beide habe ich mit esphome geflasht. 

während des upload wahr kein log offen.
