### ISSUE TITLE
Where to put the url in the developer tools?

### ISSUE THREAD

**Issue by Rayeliint** [Blackymas/NSPanel_HA_Blueprint#115]
Following your instructions for a previous install of nspanel-lovelace-ui with-

now go to the item "Developer tools --> Services" and search there for the services  
"ESPHome: DEVICE_NAME_upload_tft" --> (esphome.device_name_upload_tft)
under URL you have to enter the path to your file nspanel_blank.tft. This could look like this "http://IP_HOME_ASSISTANT:8123/local/nspanel_blank.tft"

Where do you put the url?
On mine it finds the device ok and so I select this, after that I dont know where to put the url?

**Comment by Blackymas** [comment]
hi have a look here pls

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/76

**Comment by Rayeliint** [comment]
Sorry Blackymas but that  is all over my head. 
Currently I have the NSPanel circle of waiting for content showing.
i have a ESPHOME webserver open that I can do an OTA update or turn on off relays
Where I am stuck is not being able to load the http://IP_HOME_ASSISTANT:8123/local/nspanel_blank.tft through the "call service upload"
Sorry to be a dummy at this.

**Comment by Blackymas** [comment]
hi . I hope it is working now.

if not see 

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/107
