### ISSUE TITLE
Climate adjustment - increments/precision of only half degree eg. 0.5

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#1150]
Whenever I adjust my climate on nspanel, it does not stay on the half degrees.
For example, it may be at 22C and I press the - button and changes to something weird like 21.2, 21.7 etc.. 
I would like it to round to only use only 0.5 increments so the only possible values would end with a 0 or .5 eg. 20.0, 20.5, 21.0, 21.5, 22.0 etc.
I notice that since I updated to later version of HA, they seem to have "fixed" this in the climate card now and is hardcoded to half degree increments, but that does not have anything to do with NSPanel climate control.

Here is my state attributes for ecobee thermostat climate.hallway
```
hvac_modes:
  - 'off'
  - heat
  - cool
  - heat_cool
min_temp: 7.2
max_temp: 33.3
min_humidity: 20
max_humidity: 50
fan_modes:
  - 'on'
  - auto
current_temperature: 21.7
temperature: 21.5
target_temp_high: null
target_temp_low: null
current_humidity: 41
humidity: 36
fan_mode: auto
hvac_action: idle
friendly_name: Hallway
supported_features: 15
```
I did some research and notice in the generic thermostat instructions for Home Assistant there is an optional precision value...

> precision float (optional)
> The desired precision for this device. Can be used to match your actual thermostat’s precision. Supported values are 0.1, 0.5 and 1.0. This value is also used as the step size for setting the target temperature.
> 
> Default: 0.1 for Celsius and 1.0 for Fahrenheit.

I added following in my configuration.yaml and reloaded customizations, and now I see the additional precision: 0.5 in states for this entity at end as above... so will restart nspanels and try later when home and update here.
```
homeassistant:
  customize:
    climate.hallway:
      precision: 0.5
```
I have also something similar for my gas fireplace thermostat so it will only display heat option, don't need no cool or fan.

**Comment by plasterer41** [comment]
I use an automation in home assistant to round mine with a data_template.....

`alias: Kitchen Heating on or plus 1
description: ""
trigger:
  - platform: state
    entity_id:
      - input_button.heat_plus_1
    to: null
condition: []
action:
  - if:
      - condition: state
        entity_id: climate.kitchen_thermo
        state: "off"
    then:
      - service: climate.set_temperature
        **data_template:
          entity_id: climate.kitchen_thermo
          temperature: >-
            {{(state_attr('climate.kitchen_thermo',
            'current_temperature',)|round(0)) + 1 }}**
      - service: climate.turn_on
        data: {}
        target:
          entity_id: climate.kitchen_thermo
    else:
      - service: climate.set_temperature
        **data_template:
          entity_id: climate.kitchen_thermo
          temperature: >-
            {{(state_attr('climate.kitchen_thermo', 'temperature',)|round(0)) +
            1 }}**
mode: single`

**Comment by Doughboy68** [comment]
After more research, seems to be a bug in way Home Assistant handles temperatures.
I will look at the rounding @plasterer41 posted.

**Comment by edwardtfn** [comment]
The blueprint will try to find an attribute `target_temp_step`, then will try `target_temperature_step` and if none of those are found, it will use `0.5` as default:
So based on the attributes you shared before, I would expect the default value (0.5) to be used. On my tries, it's working as expected when these attributes are not provided.

I have a couple of questions:
When you press +/-, the value is updated instantaneously at your panel, but then after a second it adds the degree signal. Basically, the first value is what the panel sends to Home Assistant, and then the update a second later is based on the response from Home Assistant to the panel.
Could you please confirm if the first value shown when you press the buttons (or move the slider) are all multiple of "0.5"?

**Comment by edwardtfn** [comment]
> I did some research and notice in the generic thermostat instructions for Home Assistant there is an optional precision value...

`precision` is for the temperature (measured). For the target temperature `target_temperature_step` should be used, although I see `target_temp_step` way more popular and is even used on the ESPHome implementation.
https://developers.home-assistant.io/docs/core/entity/climate/

**Comment by Doughboy68** [comment]
Test: I set to 21.0C in HA, confirm that states in developer tools temperature: 21 on NSPanel first value shown is 21, I press + and changes to 21.7, and after subsequent changes using +/- does change in increments of 0.5 ie. 22.2, 21.2 etc. Confirm in developer tools that temperature matches what is on NSPanel eg 21.7.

I notice above that my current_temperature: 21.7 which is coincidental to my issue, can you confirm you are using the state temperature:   and not current_temperate ?

In my thermostat, the current_temperature: is the room temperature from sensors, the temperature: is the setpoint.

**Comment by Doughboy68** [comment]
I am home now and did testing... still same issue.

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16811687/903278c0-7944-4399-9d3c-29a2f4ae3224)


https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16811687/52abb8b0-7648-4b09-be56-c6ebfda4f590

**Comment by Doughboy68** [comment]
Ok, I figured out the issue and a workaround.
Was these values min_temp: 7.2 and max_temp: 33.3
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16811687/34d711dc-2d92-49b1-bb52-d0413f80f575)

In the code it must derive the steps based on these  min and max, so they get put into a value that is not an nice dividable by 0.5. Maybe this can be fixed in code eg. rounded to 0.5.

Ecobee for some reason sends these values with a weird precision decimal value (eg 7.2). Even though I try to set different in Ecobee app, I believe that is for something else since it handles ranges separate for heat and coold... I think that the ecobee handles this limit internally... therefor these settings in home assisant are not adjustable from ecobee software.

Fortunately I was able to fix by the following using override in configuration.yaml.
```
homeassistant:
    climate.hallway:
      min_temp: 7
      max_temp: 33
```
Reload and now I get this, panel operates properly now changing temperate at even 0.5 increments.

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16811687/d3ba97ab-d364-44b3-a008-1d0388be1a0a)

This also resolves issue I had setting the min/max range II asked elsewhere
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1006

**Comment by edwardtfn** [comment]
Good catch. I can fix that later.

**Comment by edwardtfn** [comment]
A question here... as your climate won't support temperature bellow 7.2C, shouldn't have you set the minimum to 8C?
What happens if you select 7C in your panel with your current settings?

**Comment by Doughboy68** [comment]
I just picked 7 since that seemed standard with other z wave thermostat I have but 8 would also work fine. I will try selecting 7 in the morning and see what happens on ecobee since not near a panel now. My ecobee app can go as low as 7 however. I think this is a quirk  how HA integration reads ecobee or ecobee gives wrong info.

**Comment by edwardtfn** [comment]
Fixed in `dev`. It will be available in the next release.

**Comment by Doughboy68** [comment]
Not using dev just my overrides - When I changed panel to 7 it adjusted to 7.2 on  panel and HA so  7.2 must be the limit in ecobee even though it shows as 7 in app. But when I pressed + it changed to 7.5. If I set to 7 on ecobee thermostat directly  it shows as 7.2 in home assistant so definitely ecobee issue.

**Comment by edwardtfn** [comment]
Ok. I think my fix will not allow 7.0 in this case, the minimum will be 7.5. That is probably ok, right?

**Comment by Doughboy68** [comment]
Yes that is fine. Not sure why someone would set heat that low anyways.

**Comment by edwardtfn** [comment]
I don't know... Maybe someone leaving home for 3 months, let's say, depending on how the house is constructed woukd be fine to have heating set to about 7°C just to make sure nothing will freeze. I know many of those smart TRVs have a "frozen protection" about 5°C.
But probably 0.5°C difference won't be any issue in that case.

**Comment by edwardtfn** [comment]
I believe this issue is already resolved on `dev`, so I will close this and we reopen if needed.
