### ISSUE TITLE
Nach Update von HA geht das Display nicht mehr

### ISSUE THREAD

**Issue by Henning1982** [Blackymas/NSPanel_HA_Blueprint#1151]
Hallo seit dem Update von HA auf:
Supervisor 2023.10.0 
Frontend 20231002.0 - latest
kommt immer die Fehlermeldung:
Die Automatisierung „Gamingzimmer Panel“ (automation.nspanel_wohnzimmer) hat eine Aktion, die einen unbekannten Dienst aufruft: esphome.nspanel1_send_command_font_color.

Dieser Fehler verhindert, dass die Automatisierung ordnungsgemäß ausgeführt wird. Vielleicht ist dieser Dienst nicht mehr verfügbar oder vielleicht hat ein Tippfehler ihn verursacht.

Um diesen Fehler zu beheben, [bearbeite die Automatisierung](http://home-assistant:8123/config/automation/edit/1690395157078) und entferne die Aktion, die diesen Dienst aufruft.

Drücke unten auf SENDEN, um zu bestätigen, dass du diese Automatisierung korrigiert hast.

Ich weiß nicht was ich machen soll, habe jetzt schon in der Automatisierung geschaut aber finde dort nichts.

**Comment by beeldubz** [comment]
I got this error too after I updated the NSPanel firmware. I found the line of code in the automation and removed it but then I was unable to access buttons or see any of the entities on my panel. When the line is back in my panel is stuck on initializing.

**Comment by beeldubz** [comment]
It was on line 12041 on the nspanel_blueprint.yaml

**Comment by edwardtfn** [comment]
This error is due to a version mismatch. If you restart you panel, on the blue boot screen, please take note of TFT, ESPHome and Blueprint versions.
Those should be all the same. Is somecomponrnt is in an earlier version, update that.
Latest version is 4.0.2vat this moment.

**Comment by beeldubz** [comment]
Sorry for being a noob but how do I update the tft and blueprint? It appears my esphome is on 4.0.2 while the others are at 3.4.

**Comment by edwardtfn** [comment]
https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#2-update-blueprint

**Comment by edwardtfn** [comment]
@Henning1982, are you still facing this issue or should we close this?
