### ISSUE TITLE
Alarm Panel doesn't do anything

### ISSUE THREAD

**Issue by akj501** [Blackymas/NSPanel_HA_Blueprint#1156]
Hi,

I have setup my alarm in the blueprint config and this shows on the panel. However I am able to select the options but nothing happens, the buttons just turn yellow and nothing else?

I am using a ring alarm system - any help would be much welcomed.

**Comment by nasser43a** [comment]
the same issue

**Comment by edwardtfn** [comment]
Have you set your ESPHome to call Home Assistant services?

https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/en/alarm.md#allow-the-device-to-make-home-assistant-service-calls

**Comment by Quinpe** [comment]
I had the same problem.
I checked the alarm panel and it had the open sensors message. This was blocking the arming

**Comment by edwardtfn** [comment]
I need more details in order to propose a change...

What happens when you open the alarm entity in Home Assistant? And what happens when you try to change it's status?

Also, can you find any error in Home Assistant logs (Settings > System > Logs) when you try changing the alarm from your panel?

**Comment by akj501** [comment]
> Have you set your ESPHome to call Home Assistant services?
> 
> https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/en/alarm.md#allow-the-device-to-make-home-assistant-service-calls

Hey,

Sorry for the delay in coming back to you. This worked a treat - thanks so much for your help once again!
