### ISSUE TITLE
nxpanel to blueprint

### ISSUE THREAD

**Issue by Anakinnuvisan** [Blackymas/NSPanel_HA_Blueprint#1159]
Hello,

I have a problem I try to install blueprint but I'm on nxpanel from now flashed with tasmota do you know if there is a sollution to do it without reflash by esphome ? 

Thank you

**Comment by edwardtfn** [comment]
First, I would suggest you upload the new TFT from this project before leaving Tasmota.

You can use Flash Nextion as described here: https://docs.nspanel.pky.eu/prepare_nspanel/#upload-berry-driver-to-tasmota

Then you can create the settings and compile the ESPHome file selecting the "Download" option. That will give you a `.bin` file. Then connect via web to your Tasmota and find the option to upload firmware, where you can use the file you created.

**Comment by Anakinnuvisan** [comment]
THank you I reflash everything and it works perfectly. I have no idea if it's write somewhere but before to flash the nspanel with blueprint we need to have hacs and HA updated. I got so many problem because mine wasn't up to date. After that everything works very well thank you for your job this is amazing !!!!!
