### ISSUE TITLE
Entity page not showing

### ISSUE THREAD

**Issue by holm420** [Blackymas/NSPanel_HA_Blueprint#1162]
Hi, after the last update my entity pages are not showing up.
The Icon on the homescreen is not showing up too.

Versions are:

TFT: 3.4
ESPHome: 4.0.2
Blueprint 4.0.2

**Comment by edwardtfn** [comment]
You have to upload the latest TFT which is v4.0.2.

**Comment by holm420** [comment]
Yes, I did.
I had to update the tft file within the developer tools and call the service update tft file manually.

Thanks!
