### ISSUE TITLE
Missing service

### ISSUE THREAD

**Issue by kristianolofsson** [Blackymas/NSPanel_HA_Blueprint#1163]
Doing the same thing with upgrade like I always do.
Move the new blueprint 
Restart HA
Update the esphome using validate and install
The panel is not starting up and error shows in HA.

service esphome.nspanel1_page_home not available. 

Checking the blueprint and I’m not using any service calls.

very plain install with weather and entity for the 2 hardware buttons only.

How to get the service back?

**Comment by edwardtfn** [comment]
> The panel is not starting up and error shows in HA.
> 
> service esphome.nspanel1_page_home not available.

This is due to a version mismatch.
Probably ESPHome still behind.

Can you see the blue boot screen? You should be able to see all the versions there. All should be 4.0.2.

**Comment by kristianolofsson** [comment]
It all shows Tft 3.4 and esphome 3.4.1. Blueprint blank.

tried to update esphome and I thought the files goes from GitHub? Only did local upon first firmware

**Comment by edwardtfn** [comment]
Try to click the 3-dot menu on your ESPHome dashboard and select "Clean build files", then you compile again.

By the way, on `remote_package` is it pointing to `ref: main`?

**Comment by edwardtfn** [comment]
You can upload the new TFT v4.0.2 using the version you have (3.4.1).

**Comment by kristianolofsson** [comment]
How to do a local upload of the Tft?

Tried the cleanup wo luck. It’s still on 3.4

Kristian Olofsson
________________________________
Från: Edward Firmo ***@***.***>
Skickat: Sunday, October 8, 2023 6:48:51 PM
Till: Blackymas/NSPanel_HA_Blueprint ***@***.***>
Kopia: Kristian O ***@***.***>; Author ***@***.***>
Ämne: Re: [Blackymas/NSPanel_HA_Blueprint] Missing service (Issue #1163)


You can upload the new TFT v4.0.2 using the version you have (3.4.1).

**Comment by edwardtfn** [comment]
Could you please share the yaml used for ESPHome settings?
Please make sure you removed any private info before sharing.

**Comment by kristianolofsson** [comment]
Using std from GitHub with name and password for ssid only.

But I now see this after compile and upload.

"
INFO Uploading /config/.esphome/build/nspanel1/.pioenvs/nspanel1/firmware.bin (1271232 bytes)
ERROR Error auth result: Error: Authentication invalid. Is the password correct?"

What password am I missing in the secret file?

**Comment by edwardtfn** [comment]
I see 2 points where this message could be related to:

#### API key
In our project, the API isn't using any key, so if you are using a device for the first time with our code but this device was used with ESPHome (other project) before, you could have this error. Also, if you change the API key for some reason.
Removing the device from Home Assistant and adding again could fix.

#### OTA password
Again, if you have changed the OTA password (or your Wi-Fi password, as that is used as OTA password in this project) or are trying to connect to a new device (1st time in this project).
Trying to transfer via cable might be the more reliable way to solve this, but if you know it's previous OTA password you can try to use this: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/en/customization.md#custom-ota-password

**Comment by kristianolofsson** [comment]
Trying now again but the ttf update is now in progress for 10h. Extremely slow. Let’s see

**Comment by kristianolofsson** [comment]
Thanks a lot for your help but still struggling.
- Cut the power to the panel and reboot. 
- Using the following esp home config:
-`substitutions:
  ###### CHANGE ME START ######
  device_name: "nspanel1" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####
##### My customization - End #####`

- Validation is fine
- The install goes OK
- But then when I try to tft update it goes very slow again...

**Comment by edwardtfn** [comment]
> But then when I try to tft update it goes very slow again...

Please try the following:

1. On the `remote_package` area, change from `ref: main` to `ref: dev`, then flash your device again. This will enable a new transfer engine with much more logs.
2. Try to Upload TFT again, but this time please try to capture the logs from ESPHOME and share here.
Again, if it's not about to finish after 30min, you can cancel it.
3. Change it back to `ref: main` and flash your device again.

**Comment by kristianolofsson** [comment]
- Update of config done
- Validation OK
- install with error [E][uart:015]: Reading from UART timed out at byte 0!
- Display shows System data ERROR

**Comment by edwardtfn** [comment]
Could you please share the log when you transfer with `ref: dev`?
Not just one line or two, it's important to see from when you press the Upload button to the point it fails.

**Comment by kristianolofsson** [comment]
https://pastebin.com/SsRdD6vV

This is the install

**Comment by edwardtfn** [comment]
I couldn't find in the log the moment where you pressed the Upload TFT button, however I could see that your panel took 23 secs to establish the connection between ESPHome and the Nextion Display, which is quite a long time and is probably due to the error message in your screen.
That version from `dev` should detect this state and power cycle the display itself, so please wait a minute from the time you start your panel to the moment you press the Upload button, so it will have time for all this checkup on the boot.

**Comment by edwardtfn** [comment]
No nees to restart again if you haven't done since you collected the latest log. Just try Upload TFT and capture the log, please.

**Comment by kristianolofsson** [comment]
Finaly some progress. The panel is up and running. It’s showing time and date. :)

but the time is 2h behind and the text for the 2 hardware buttons are blank. (Despite added into the BP).

restarted HA wo luck
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7191232/730af93d-de46-4577-bdec-96ae58f845b1)

**Comment by edwardtfn** [comment]
On the blue boot screen, which versions you see for TFT, ESPHome and Blueprint?

**Comment by edwardtfn** [comment]
From the beginning of your log, I see this:

```

INFO ESPHome 2023.9.3
INFO Reading configuration /config/nspanel1.yaml...
INFO Detected timezone 'Etc/UTC'
```

So looks like ESPHome isn't providing the timezone correctly.
You can force your timezone adjusting your config like this:

https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/en/customization.md#enforce-time-zone

**Comment by kristianolofsson** [comment]
Blueprint is blank
![IMG_1171](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7191232/eeb4d7ab-18b5-4a91-8a3c-2a50f55fa7bf)

**Comment by kristianolofsson** [comment]
It seems like the blueprint is not assigned?
I now got retry 1 on blueprint during startup
Even this message in HA
![IMG_1172](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7191232/b900501d-03c8-4f08-a9a5-27b0ed893e04)

**Comment by edwardtfn** [comment]
You have to return your ESPHome settings to `ref: main` and then flash your device again.

**Comment by kristianolofsson** [comment]
- Panel was up and running except the blueprint link
- Changed it back to ref: main
- Did a new update all (Success)
- Update the tft and it gets stuck (87% and barely moving)

**Comment by edwardtfn** [comment]
Change it back to `ref: dev`, flash it and then do the TFT upload. The `dev` is used only for TFT upload, so after a successful upload, you have to change it back to `ref: main` in order to have it working with the TFT and Blueprint v4.0.2. There's no need to transfer TFT again as it is already in the right version (4.0.2).
At the end, TFT, ESPHome and Blueprint should all be on v4.0.2. Focus only on the things with incorrect version and trying to install it again won't help.
If after everything is on v4.0.2 and it still not working, please let me know and we start from there.

**Comment by kristianolofsson** [comment]
ok, did the following:
- Changed the config back to ref: dev
- Did an install, the install goes on forewer. New log entries all the time. But after a while did proceed with next step.
- Updated the tft
- The screen show but incorrect time, no weather and no names of buttons. Hardware buttons works so all connected and some connection to blueprint.
- Changed to ref: main and did a new install
- No tft update ( did not dare)

Now all shows again. Weather, texts and time.... :)

So finally it all seems OK!

Thank you so much!
-
