### ISSUE TITLE
Temperature sensor and self-heating

### ISSUE THREAD

**Issue by fra87** [Blackymas/NSPanel_HA_Blueprint#1164]
Hello

I'm experiencing a lot of self heating (the internal sensor shows 2-3 degrees more than the actual temperature)

How did you cope with this? Is there a way to compensate? I'm using this also for the heat climate, so solving on home assistant through a template sensor is not an optimal solution

**Comment by edwardtfn** [comment]
Under the device's page (Settings > Devices and Services > ESPHome) adjust the "Temperature correction".
Give it a few seconds to a minute until you have a new reading with the adjustments.

**Comment by quenthal** [comment]
> Under the device's page (Settings > Devices and Services > ESPHome) adjust the "Temperature correction". Give it a few seconds to a minute until you have a new reading with the adjustments.

This works also for "fallback" thermostat?

**Comment by edwardtfn** [comment]
Yeap

**Comment by fra87** [comment]
Thank you a lot; I did not know this was already selectable in the ESPHome node

Closing since solved
