### ISSUE TITLE
Nspanel not dimming after update

### ISSUE THREAD

**Issue by julianvdh** [Blackymas/NSPanel_HA_Blueprint#1165]
After updating the blueprint and the other files to 4.0.2 the screen is not dimming anymore, but it just goes black. After touching it is is back on, but after a while it just goes back to black again. Changing the setting for dimming doesn't affect it. Restarting also doesn't help.

**Comment by edwardtfn** [comment]
What are the times for Timeout Dim and timeout sleep?

**Comment by julianvdh** [comment]
Timeout dim = 30 seconds
Timeout sleep = 60 seconds
Should sleep be 0?

**Comment by julianvdh** [comment]
Fixed by changing sleep to 0
