### ISSUE TITLE
one button to make a scene ? 

### ISSUE THREAD

**Issue by Anakinnuvisan** [Blackymas/NSPanel_HA_Blueprint#1166]
Hello, 

I don't know if it's possible to create one buton to make a scene in blueprint ? For example I click sur one icon and it close everything light tv shutter ... ?

**Comment by edwardtfn** [comment]
That's possible. You can create scenes, scrips or automations in Home Assistant and assign it to any button on your panel. When you press the button the scene/script/automation will be triggered.

**Comment by Anakinnuvisan** [comment]
THank you this is perfect
