### ISSUE TITLE
Blueprint version mismatch

### ISSUE THREAD

**Issue by fraggle68** [Blackymas/NSPanel_HA_Blueprint#1167]
Hi guys,
I am struggling with the installation process of NS Panel. 
I followed the instructions and imported blueprint from the website, flashed the ESP32 successfully but was unable to download the Nextion tft file. 
Since I am familiar with the Nextion editor, I decided to download it via a serial connection. This worked so far so good.
I created a NS panel configuration in Homeassistant with exactly the same name as in ns-panel.yaml.
But the display kept getting stuck during the initialization process. The only thing I found in the nspanel log was the message "Blueprint version mismatch". 

Any help is appreciated.
Best regards Peter....

[logs_ns-panel_run(4).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/12848675/logs_ns-panel_run.4.txt)
![IMG_7471](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/77545595/b3a03cc5-469e-440b-a6af-c4453412184a)

**Comment by edwardtfn** [comment]
> I created a NS panel configuration in Homeassistant with exactly the same name as in ns-panel.yaml.

When you open the automation related to the Blueprint, can you see the same version (4.0.2)?

**Comment by edwardtfn** [comment]
> But the display kept getting stuck during the initialization process. The only thing I found in the nspanel log was the message "Blueprint version mismatch".

What about Home Assistant logs (Settings > System > Logs)? Anything related to this?

**Comment by ragesoft** [comment]
Same here. Just today i started the update of ESPHome to new Version 
Output of the boot log:

`[19:20:34][D][script.check_versions:2240]: ESPHome version: 4.0.2
[19:20:34][D][script.check_versions:2241]: TFT version: 4.0.2
[19:20:34][D][script.check_versions:2243]: Blueprint version:
[19:20:34][E][script.check_versions:2244]: Blueprint version mismatch!`

I updated the blueprint in my home assistant with the new from github. i see the version is correct.
I restartet home assistant (just in case new blueprint is not loaded correctly)
I deleted the blueprint and readded it from github url
I deleted the automation and recreated it with new NSPanel blueprint

Still:
After booting the panel, error version mismatch

:(

**Comment by edwardtfn** [comment]
What about Home Assistant logs?

**Comment by ragesoft** [comment]
No logging visible.

BUT:
After a few more trial-and-error i finaly get it working again.
I was in the automation settings, removed the device from the option and re-added it. click save and NOW it works!
I've done it 10 times before, but now... :/ dono why...

:(

**Comment by fraggle68** [comment]
> > I created a NS panel configuration in Homeassistant with exactly the same name as in ns-panel.yaml.
> 
> When you open the automation related to the Blueprint, can you see the same version (4.0.2)?

Yes it´s 4.0.2

**Comment by fraggle68** [comment]
> What about Home Assistant logs?

Logger: aioesphomeapi.reconnect_logic
Source: runner.py:186
First occurred: 9. Oktober 2023 um 19:55:27 (1 occurrences)
Last logged: 9. Oktober 2023 um 19:55:27

Can't connect to ESPHome API for nspanel1 @ 192.168.10.167: Error connecting to ('192.168.10.167', 6053): [Errno 113] Connect call failed ('192.168.10.167', 6053) (SocketAPIError)

**Comment by edwardtfn** [comment]
1. This says your panel is not connected. Could you please double check by going to the device's page (Settings > Devices & Services > ESPHome) and see if the controls and sensors there are working properly?

2. By the way, have you renamed any entity from your panel?

3. Maybe removing the panel from Home Assistant and then adding again might help

4. On the automation used to configure your panel (using the Blueprint), is the panel properly selected?

**Comment by PHHortonww** [comment]
Okay, I have tried the following. After observing that the panel sporadically goes offline I placed it near the router without success. After that I decided to start from scratch. Deleted Blueprint, Automation and ESP Config. Reinstalled everything. Same condition. Shit. Out of desperation I started TFT Update and saw the display showing 100% loaded, that was it. Since then the display shows System Error and is in a boot loop. I've had enough for now. Thanks for your support.

**Comment by edwardtfn** [comment]
> display shows System Error and is in a boot loop.

This is a different issue, so let's talk about this one on

**Comment by edwardtfn** [comment]
> After I entered the IP address instead of the panel name in the panel automation

Where exactly have you added the IP?

**Comment by fraggle68** [comment]
NSPanel Configuration Sheet


![grafik](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/77545595/925e2de4-081c-4065-ba56-a90df24e965e)
