### ISSUE TITLE
Funktionsumfang nach Update auf 4.0.2 stark eingeschränkt

### ISSUE THREAD

**Issue by DoubleD1921** [Blackymas/NSPanel_HA_Blueprint#1168]
Hallo Liebes Blackymas-Team,

ich habe gemäß eurer Anleitung das Update auf allen meiner vier Sonoff NSPanels durchgeführt. Folgende Fehler sind mir direkt aufgefallen welche ich bis jetzt nicht beheben konnte:

Das Display geht nach einer gewissen Zeit komplett aus. Ich habe es eigentlich so eingestellt, dass das Display nach 30 Sekunden auf 10 % gedimmt wird. Stattdessen geht es ganz aus. 
![IMG_1221](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/144054047/de80f6f9-3973-4e1c-b44e-56649585122d)

Die Buttonpages zeigen nur noch einen Teil der Buttons an. Die Buttons an sich lasen sich leider nicht mehr anwählen (Siehe Bild im Anhang).

Der QR-Code für mein Wifi wird nicht mehr angezeigt. 

Über eure Hilfe bei der Problembeseitigung würde ich mich sehr freuen. 

Liebe Grüße

DD

Systeminformationen:

### ESP Home:
Current version: 2023.9.3 

### Home Assistant 2023.10.1
Supervisor 2023.10.0
Operating System 10.5
Frontend 20231005.0 - latest

### YAML Code der Automation:
alias: NSPanel Configuration Wintergarten
description: Sonoff NSPanel Wintergarten Konfiguration
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: ff6b40750f26f304f239e258314863dd
    language: de
    weather_entity: weather.forecast_home
    left_button_entity: scene.essen
    left_button_name: Essen
    right_button_entity: scene.nachtlicht_2
    right_button_name: Nachtlicht
    left_button_hold_select: Custom Action
    left_button_hold_custom_action:
      - service: scene.turn_on
        target:
          entity_id: scene.licht_aus
        metadata: {}
    right_button_hold_select: Custom Action
    right_button_hold_custom_action:
      - service: scene.turn_on
        target:
          entity_id: scene.licht_aus
        metadata: {}
    button_page01_label: Szenen
    entity01: scene.essen
    entity01_name: Essen
    entity01_icon: mdi:food
    entity01_confirm: false
    entity02: scene.spielen
    entity02_icon: mdi:nintendo-game-boy
    entity02_name: Spielen
    entity03: scene.nachtlicht_2
    entity03_name: Nachtlicht
    entity03_icon: mdi:weather-night
    entity03_icon_color:
      - 255
      - 64
      - 255
    entity04: scene.licht_aus
    entity04_name: Licht aus
    entity04_icon: mdi:lightbulb-spot-off
    button_page02_label: Lampensteuerung
    entity09: light.hue_centura_spot_7
    entity09_name: Spot 1
    entity09_icon: mdi:lightbulb-spot
    entity10: light.hue_centura_spot_8
    entity10_name: Spot 2
    entity10_icon: mdi:lightbulb-spot
    entity11: light.hue_centura_spot_9
    entity11_name: Spot 3
    entity11_icon: mdi:lightbulb-spot
    entity12: light.hue_centura_spot_10
    entity12_name: Spot 4
    entity12_icon: mdi:lightbulb-spot
    entity13: scene.licht_aus
    entity13_name: Licht aus
    entity13_icon: mdi:lightbulb-spot-off
    button_page03_label: Musik
    home_outdoor_temp_label_color:
      - 255
      - 247
      - 107
    qrcode_enabled: true
    qrcode_label: WLAN
    qrcode_value: WIFI:S:Double D Gast;T:WPA;P:;
    show_while_loading: true
    climate: climate.wintergarten
    home_button05_icon: mdi:wifi-plus
    entity05: light.wintergarten
    entity05_name: Wintergarten
    entity05_icon: mdi:lightbulb-group

**Comment by marcelloceschia** [comment]
@DoubleD1921 das mit dem Ausschalten des Displays lässt sich einfach lösen "Timeout sleep" auf 0s stellen, dann geht es nicht mehr aus

**Comment by DoubleD1921** [comment]
> Sorry, I cannot write in German.
> 
> The picture with incomplete buttons makes me believe you have a version mismatch with an outdate TFT. You can confirm this looking at the versions (TFT, ESPHome and Blueprint) on the blue boot screen. If you have different versions or if some component isn't reporting it's version, please update that one.
> 
> https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#2-update-blueprint

Hallo edwardtfn,

ich habe nun mehrfach auf Update TFT geklickt (bei mir sieht der Knopf etwas anders aus als bei dir). Der Updateprozess beginnt immer bei ca. 90%. Anbei ein Screenshot der Versionen auf dem Bootscreen. Was mache ich falsch?

Hello edwardtfn,

I have now clicked on Update TFT several times (the button looks a little different for me than it does for you). The update process always starts at around 90%. Attached is a screenshot of the versions on the boot screen. What am I doing wrong?
![IMG_1222](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/144054047/cd2d696a-7c3e-4faa-aeaf-42343832541a)

<img width="370" alt="Bildschirmfoto 2023-10-09 um 21 38 06" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/144054047/5013c084-c43f-4065-8039-c8ccc2aba3c2">

**Comment by edwardtfn** [comment]
> I have now clicked on Update TFT several times (the button looks a little different for me than it does for you). The update process always starts at around 90%. Attached is a screenshot of the versions on the boot screen. What am I doing wrong?

Start from 90% isn't a problem.
But looks like you have an older version of the file in your local http server. You have to download the latest version from GitHub and update your local server, then click Upload TFT again.

**Comment by DoubleD1921** [comment]
> > I have now clicked on Update TFT several times (the button looks a little different for me than it does for you). The update process always starts at around 90%. Attached is a screenshot of the versions on the boot screen. What am I doing wrong?
> 
> Start from 90% isn't a problem. But looks like you have an older version of the file in your local http server. You have to download the latest version from GitHub and update your local server, then click Upload TFT again.
> 
> https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#4-update-tft

Thank you! That was it. I didn't think about uploading the new TFT file. Now everything works as expected

**Comment by DoubleD1921** [comment]
> @DoubleD1921 das mit dem Ausschalten des Displays lässt sich einfach lösen "Timeout sleep" auf 0s stellen, dann geht es nicht mehr aus

Perfekt! Funktionert! Vielen Dank für deinen Tipp! :-)
