### ISSUE TITLE
Display shows System Error and is in a boot loop.

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1169]
Okay, I have tried the following. After observing that the panel sporadically goes offline I placed it near the router without success. After that I decided to start from scratch. Deleted Blueprint, Automation and ESP Config. Reinstalled everything. Same condition. Shit. Out of desperation I started TFT Update and saw the display showing 100% loaded, that was it. Since then the display shows System Error and is in a boot loop. I've had enough for now. Thanks for your support.

_Originally posted by @PHHortonww in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1167#issuecomment-1756093964_

**Comment by edwardtfn** [comment]
First let's fix the "System error" message by installing the TFT. Once you have TFT 4.0.2 installed, please don't try to install TFT again... 😜

1. Edit your ESPHome yaml settings in the area `remote_package` changing from `ref: main` to `ref: dev`, then flash your panel again. It will show version 4.1dev, which have a new TFT transfer engine and way more logs.
2. Try to Upload TFT again, but please capture the ESPHome logs from the moment right before you press the Upload TFT button to when if finishes (successfully or with an error) and share the logs here.
3. Change it back to `ref: main` and flash your panel again. That will return to v4.0.2, which is the latest stable version.

**Comment by fraggle68** [comment]
Hi Edward, please find attached log file
[logs_ns-panel_logs(3).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/12871357/logs_ns-panel_logs.3.txt)

**Comment by jdmevo123** [comment]
I have the same issue, I tried Dev with no luck, my screen shows error and then after restarting it I have a system data error.
![IMG_7557](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/6053506/79b1ee0f-9f54-43c7-9cd7-abd2a12d21ff)

confirmed I’m on v4.02 for blueprint and tft and esp home is 2013-9-3
![IMG_7558](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/6053506/b563c957-c084-45c0-96f1-00c4d485ddc7)
onfirmed

**Comment by edwardtfn** [comment]
>  I tried Dev with no luck,

Could you please share the logs?

**Comment by edwardtfn** [comment]
So, I got a bit lost here... anyone still having this issue or should we close this?

**Comment by 35aportal** [comment]
> First let's fix the "System error" message by installing the TFT. Once you have TFT 4.0.2 installed, please don't try to install TFT again... 😜
> 
> 1. Edit your ESPHome yaml settings in the area `remote_package` changing from `ref: main` to `ref: dev`, then flash your panel again. It will show version 4.1dev, which have a new TFT transfer engine and way more logs.
> 2. Try to Upload TFT again, but please capture the ESPHome logs from the moment right before you press the Upload TFT button to when if finishes (successfully or with an error) and share the logs here.
> 3. Change it back to `ref: main` and flash your panel again. That will return to v4.0.2, which is the latest stable version.

This worked perfectly for me - many thanks.

**Comment by edwardtfn** [comment]
I believe this issue is already resolved on `dev`, so I will close this and we reopen if needed.
