### ISSUE TITLE
Show buttons instead of weather/time on home screen

### ISSUE THREAD

**Issue by naofireblade** [Blackymas/NSPanel_HA_Blueprint#117]
If you want to use your NSPanel to control things instead of reading the clock/weather it would be nice to optionally show 4 or 8 buttons on the home screen instead of the weather/time.

**Comment by Blackymas** [comment]
maybe later because this would mean a complete rebuild of the HMI file in Nextion Editor and currently other functions are in the foreground

**Comment by Blackymas** [comment]
I add the tag "new feature request" - I close the issue

**Comment by edwardtfn** [comment]
Hi, we are having a discussion about new design for the panel and would be nice to get your comments there: https://discord.com/channels/1464682227068698724/1479900732273721514
