### ISSUE TITLE
Displaying incorrect time

### ISSUE THREAD

**Issue by rici44** [Blackymas/NSPanel_HA_Blueprint#1172]
My local timezone inside Debian host is Europe/Prague, Home Assistant got this timezone also as local time. Both are working great. Inside ESPHome of NSPANEL is also the correct one. Display on ESPHome NSPANEL is showing UTC timezone so this time -2 hours than the host and home assistant time. Could you please help me to solve this issue/setup? Thank you.

**Comment by edwardtfn** [comment]
This may help you: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/en/customization.md#enforce-time-zone

**Comment by rici44** [comment]
Thx for help. I added it into yaml but had mapping problem. Please add space into your code, behind **id:** 

`time:
  - id: !extend time_provider
    timezone: "Europe/Bratislava"`

**Comment by edwardtfn** [comment]
Sorry, looks like a typo in the docs. We will fix that later.

Please try this:
```yaml
time:
  - id: !extend time_provider
    timezone: "Europe/Bratislava"
```

**Comment by rici44** [comment]
I found it so I sent you info about space addition needed. Customisations already works great thx.
