### ISSUE TITLE
Upload TFT new flash

### ISSUE THREAD

**Issue by Doser86** [Blackymas/NSPanel_HA_Blueprint#1174]
I bought 4 more panels and strugle to upload TFT on all of them. Process do not start.
Tried changing to ref: dev, but then I can not flash.

Is the problem with uploading TFT going to be fixed soon?

**Comment by edwardtfn** [comment]
> Tried changing to ref: dev, but then I can not flash.

Why can't you flash? Which error message are you getting?

**Comment by Doser86** [comment]
The panels only restart when trying to flash TFT.

**Comment by Doser86** [comment]
/data/packages/891b50f5/nspanel_esphome.yaml: In lambda function:
/data/packages/891b50f5/nspanel_esphome.yaml:2473:18: error: 'class esphome::nextion::Nextion' has no member named 'set_protocol_reparse_mode'
               id(disp1).set_protocol_reparse_mode(false);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
Compiling .pioenvs/nspanel_sov2_seng/lib64d/WiFi/WiFiSTA.cpp.o
Compiling .pioenvs/nspanel_sov2_seng/lib64d/WiFi/WiFiScan.cpp.o
Compiling .pioenvs/nspanel_sov2_seng/lib64d/WiFi/WiFiServer.cpp.o
Compiling .pioenvs/nspanel_sov2_seng/lib64d/WiFi/WiFiUdp.cpp.o
Compiling .pioenvs/nspanel_sov2_seng/lib01c/FS/FS.cpp.o
Compiling .pioenvs/nspanel_sov2_seng/lib01c/FS/vfs_api.cpp.o
Archiving .pioenvs/nspanel_sov2_seng/lib64d/libWiFi.a
Compiling .pioenvs/nspanel_sov2_seng/libbc6/Update/HttpsOTAUpdate.cpp.o
*** [.pioenvs/nspanel_sov2_seng/src/main.cpp.o] Error 1
========================= [FAILED] Took 29.87 seconds =========================

**Comment by edwardtfn** [comment]
> The panels only restart when trying to flash TFT. 

Could you please try to capture the logs and share here?

**Comment by Doser86** [comment]
Just did

**Comment by edwardtfn** [comment]
Have you tried cleaning the build files?

**Comment by Doser86** [comment]
How I do that?

**Comment by edwardtfn** [comment]
On the ESPHome dashboard, click on the 3-dot menu related to your device and then select "Clean build files".

**Comment by Doser86** [comment]
Same thing: 

/data/packages/891b50f5/nspanel_esphome.yaml: In lambda function:
/data/packages/891b50f5/nspanel_esphome.yaml:2473:18: error: 'class esphome::nextion::Nextion' has no member named 'set_protocol_reparse_mode'
               id(disp1).set_protocol_reparse_mode(false);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
Compiling .pioenvs/nspanel_sov2_seng/lib64d/WiFi/WiFiSTA.cpp.o
Compiling .pioenvs/nspanel_sov2_seng/lib64d/WiFi/WiFiScan.cpp.o
Compiling .pioenvs/nspanel_sov2_seng/lib64d/WiFi/WiFiServer.cpp.o
Compiling .pioenvs/nspanel_sov2_seng/lib64d/WiFi/WiFiUdp.cpp.o
Compiling .pioenvs/nspanel_sov2_seng/lib01c/FS/FS.cpp.o
Compiling .pioenvs/nspanel_sov2_seng/lib01c/FS/vfs_api.cpp.o
Archiving .pioenvs/nspanel_sov2_seng/lib64d/libWiFi.a
Compiling .pioenvs/nspanel_sov2_seng/libbc6/Update/HttpsOTAUpdate.cpp.o
*** [.pioenvs/nspanel_sov2_seng/src/main.cpp.o] Error 1
Compiling .pioenvs/nspanel_sov2_seng/libbc6/Update/Updater.cpp.o
========================= [FAILED] Took 31.50 seconds =========================

**Comment by edwardtfn** [comment]
This is weird. Have you changed anything else in your ESPHome yaml settings?

**Comment by Doser86** [comment]
No, nothing

**Comment by Doser86** [comment]
You helped me with me with my old panels some days ago. Now I am trying with some new. There is obviously some problem with esp and your code uploading tft now

**Comment by Doser86** [comment]
This is ESP file:

substitutions:
  ###### CHANGE ME START ######
  device_name: "nspanel_sov1_seng" 
  wifi_ssid: Hove
  wifi_password: hovenett1234

  nextion_update_url: "http://192.168.86.47.local:8123/local/nspanel_eu.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####
##### My customization - End #####

**Comment by edwardtfn** [comment]
> This is ESP file:

OK, as I understood, this one (pointing to `main`) builds successfully, but then fails when transferring TFT. If you change to `dev` with no other changes, it fails compiling.
Is that correct?

**Comment by Doser86** [comment]
Yes

**Comment by edwardtfn** [comment]
Please try changing from `refresh: 300s` to `refresh: 3s` and try compiling with `ref: dev` again.

**Comment by Doser86** [comment]
Where is refresh: 300S?

substitutions:
  ###### CHANGE ME START ######
  device_name: "nspanel_sov1_seng" 
  wifi_ssid: Hove
  wifi_password: hovenett1234

#  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft" # URL to local tft File
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####
##### My customization - End #####

**Comment by Doser86** [comment]
Found it:)

**Comment by Doser86** [comment]
Same:

/data/packages/891b50f5/nspanel_esphome.yaml: In lambda function:
/data/packages/891b50f5/nspanel_esphome.yaml:2473:18: error: 'class esphome::nextion::Nextion' has no member named 'set_protocol_reparse_mode'
               id(disp1).set_protocol_reparse_mode(false);

**Comment by Doser86** [comment]
You can close this case. I fixed it. Looks like sometimes when you generate the esp.bin file it give you the options to create for web flasher. Then it works changing to dev and I get to upload the tft. Dont't know for shure, but worked on all my 4 new panels.
