### ISSUE TITLE
Icon Temperature

### ISSUE THREAD

**Issue by sheaur** [Blackymas/NSPanel_HA_Blueprint#1179]
The default icon doesn't appear in the temperature
Version: 4.0.2

**Comment by sheaur** [comment]
![20231016_155049](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/66822103/ae6ef12d-a1a2-4c2e-a38b-5b482dcc4493)

**Comment by sheaur** [comment]
![Uploading 20231016_155840.jpg…]()

**Comment by sheaur** [comment]
![20231016_155840](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/66822103/8f31e1e3-9932-4f88-ba63-c600b55dc0be)

**Comment by edwardtfn** [comment]
It's fixed on `dev` and will be included in the coming release.

**Comment by sheaur** [comment]
Now this problem @

**Comment by sheaur** [comment]
Now the manual temperature bar does not work, it indicates the minimum temperature
![20231019_182233](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/66822103/5ba08d24-30ea-48a8-bed7-d92d6f014514)
