### ISSUE TITLE
Support sensor/binary_sensor entity

### ISSUE THREAD

**Issue by naofireblade** [Blackymas/NSPanel_HA_Blueprint#118]
It would be nice to see sensor values (e.g. window is open).

**Comment by Blackymas** [comment]
as an icon in the topbar?

**Comment by naofireblade** [comment]
As a normal icon/button on one of the 4 pages

**Comment by w00ter** [comment]
Similar question to #128 

This would be nice as a replacement for button, or perhaps it is easier to show entity data within the button image. One could create screens with buttons and sensor stats and have them show together with buttons.

**Comment by Blackymas** [comment]
close the ticket and it is on the roadmap

**Comment by Blackymas** [comment]
added in https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.0.0
