### ISSUE TITLE
Update TFT display very slow and not succesfull

### ISSUE THREAD

**Issue by rivellablau** [Blackymas/NSPanel_HA_Blueprint#1181]
Hi

First: thanks for all the work! Very cool project and I learned a lot. I own 4 Panels and to be honest every update was ... a lot of try and error ^^. 

My problems are the same as discussed in [1144](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1144).
Different ways did not work. First blank TFT didn't work as well. Notice: I placed the setup direct near the router. The Signal strength is shown different when working in the logs. Sometimes very poor connection quality as in the logs shown below. Could this be part of the problem?

After the failed upload the display shows now "System data ERROR!". Last update i could solve with blank tft first and then the real tft. This time this does not work.

Your advice to do:
1.  In your ESPHome yaml, on the remote_package area, change from ref: main to ref: dev.
2: Flash (ESPHome) your panel again
3. Click again Upload TFT.
4. You will notice a more detailed log. Please capture that and share here.
5. After the transfer (or failure), change it back to ref: main and flash it again.

Did not work.

Edit:

Solution below

**Comment by edwardtfn** [comment]
Could you please capture the logs while flashed with `ref: dev` and then share it again?

**Comment by rivellablau** [comment]
Thanks for the very fast reply.
I made the update work. The display was positioned 3 meters away from the router in direkt sight. Thenk blank tft by service upload_tft_url. Hard disconnect. Flash the real tft by service upload_tft_url.
Could there be a wifi connection problem within the display? Otherwise my wifi works without any problems.

**Comment by edwardtfn** [comment]
> Could there be a wifi connection problem within the display?

Yes, it could be. The upload TFT included with the Nextion component from ESPHome is quite fragile and any issue with the network or the http server will cause a failure in the transfer.
With `dev: ref` you are using a new version where we are reducing chunk size and adding some retries to make it more robust. So far the results are looking good, however we still need more test...

**Comment by rivellablau** [comment]
Panel 2 stil stands still. Ill try ref and give feedback. But could be during the weekend. Thanks :)

**Comment by rivellablau** [comment]
Could not wait ^^
It worked on the second try! The first stuck at 1% I guess i should change the dev back to main once finished? I can update the other panels and send you the logs if you can benefit? Do you need the logs when it succeeded or failed?
Big thanks!

**Comment by edwardtfn** [comment]
> Could not wait ^^

😂

> It worked on the second try!

Nice!

>The first stuck at 1%

Next time, please capture the logs. I wanna know why it didn't completed each try, the times, etc.

> I guess i should change the dev back to main once finished?

That's correct. Please change it back to `ref: main` and flash it again, but as you already transferred the TFT there's no need to repeat this process until next version.

> I can update the other panels and send you the logs if you can benefit?
Do you need the logs when it succeeded or failed?

Only if you are having trouble uploading with `main`. If your panel is operational, there's no need to run this.
If you run, yes, both successful and failed transfers are of my interest for logs.
