### ISSUE TITLE
Won't boot to bootloader

### ISSUE THREAD

**Issue by Chaaaaaaaaarlie** [Blackymas/NSPanel_HA_Blueprint#1182]
I'm quite sure my wiring is correct, and I have 3.3Vdc. Using this Adapter: https://www.amazon.de/UART-TTL-Adapter-Konverter-Jumperkabel-kompatibel/dp/B0B7RHPMT7/
When I power it on without IO1 on GND, it boots into the normal ewelink screen.
As soon as I try to boot with the bridge, it stays black.

Got it yesterday and did not set it up with the ewelink app yet.
Just tried to set it up with the app, and it's still not booting to bootloader.

**Comment by edwardtfn** [comment]
Try to send a photo showing your wiring...

**Comment by Chaaaaaaaaarlie** [comment]
![16976964155447930656949275017278](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/10680114/9afc6278-8e22-498b-b416-eff5b53f4951)
I tried it via Edge and esphome in home assistant.

**Comment by edwardtfn** [comment]
It looks fine.
Which error are you getting when you try to transfer the file via https://web.esphome.io/?

**Comment by Chaaaaaaaaarlie** [comment]
![grafik](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/10680114/6a11dde7-3c01-4282-b838-778e37f0880e)

**Comment by edwardtfn** [comment]
What happens after the 100%?

**Comment by Chaaaaaaaaarlie** [comment]
Just edited my post, sorry. 
"Configuration installed"

**Comment by edwardtfn** [comment]
Have you clicked "Install" or "Prepare for the first use"?

**Comment by Chaaaaaaaaarlie** [comment]
Prepare for first use

**Comment by Chaaaaaaaaarlie** [comment]
just to make sure I don't screw it up, I need to replace all of these "${wifi_ssid}" and so on with the real input?

**Comment by Chaaaaaaaaarlie** [comment]
I can't get the yaml into a bin file.

I got this [logs_nspanel1_validate (1).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13039632/logs_nspanel1_validate.1.txt) when I tried to use the yaml like this [nspanel_esphome.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13039648/nspanel_esphome.txt) (renamed to txt).


And this when I try to load the downloaded raw file without changes: [logs_nspanel1_validate.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13039634/logs_nspanel1_validate.txt)

**Comment by Chaaaaaaaaarlie** [comment]
I think I know where my fault was ...

**Comment by edwardtfn** [comment]
Any progress?

**Comment by Chaaaaaaaaarlie** [comment]
I actually retried the whole process.

Connect > Prepare for first use > Install > Installing > Configuration installed! > Close > Connecting > An error occurred. Improv Wi-Fi Serial not detected > Close >Install > [nspanel1-factory.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13044675/nspanel1-factory.txt) (.bin > .txt to upload) > Install > Connecting > Erasing > Installing > Configuration installed!

**Comment by Chaaaaaaaaarlie** [comment]
To me, it looks like everything but the display is updated.

**Comment by Chaaaaaaaaarlie** [comment]
I got it working ...
Using the "Exit reparse" function as mentioned here https://community.home-assistant.io/t/nspanel-esphome-nextion-is-not-connected/482588/16 I got it to connect to the display. Then I just had to push the update and it worked.
Thanks a ton for your help though!

**Comment by edwardtfn** [comment]
Great to hear it worked.
