### ISSUE TITLE
ICON/ICON-COLOR based on a SENSOR state

### ISSUE THREAD

**Issue by AubreyKloppers** [Blackymas/NSPanel_HA_Blueprint#1184]
Please could we have an option to change an ICON/ICON-COLOR based on a SENSOR state?

ICON EXAMPLE:
icon: |- [[[ if(states['sensor.<BLAH-alarm_entity-BLAH>'].state == 'Disarmed') return "mdi:alarm-light-off"; else if(states['<BLAH-alarm_entity-BLAH>'].state == 'Away Armed') return "mdi:alarm-light"; ]]]

**Comment by double1968** [comment]
This is a really good idea!

**Comment by Doughboy68** [comment]
This is similar to my request setting color of a light entity button to its actual RGB color.

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/935

In your example though you give an alarm entity... the home screen icon already shows different colors based on status for alarm.

**Comment by edwardtfn** [comment]
The icon engine was rebuilt for v4.2 (still on `dev`) so I believe this will be solved with that release.

**Comment by edwardtfn** [comment]
- #1556
