### ISSUE TITLE
After updating to ESP home 10,0 and 10,1 I can't disarm Alarm panel 

### ISSUE THREAD

**Issue by HolmbomDK** [Blackymas/NSPanel_HA_Blueprint#1187]
Alarm panel button disarm just turns yellow, after press, but does not open til number pad, it worked before upgrading to ESP home  ver.10 

running 

TFT 4.0.2
ESPhome 4.0.2
Blueprint 4.0.2

**Comment by edwardtfn** [comment]
Can you see anything on Home Assistant logs (Settings > System > Logs) or ESPHome logs?

**Comment by Doughboy68** [comment]
I updated one of my panels and do not experience any of these issues.
NSPanel updates info on Home Screen, and if happen to be in a button screen an I turn on/off entity elsewhere.
Alarm I can arm/disarm from NSPanel. Both arm and Disarm opens the numberpad (arm does not need a code for mine, I just press check mark).

I will update rest of my panels now.

**Comment by edwardtfn** [comment]
The way a change in the alarm is called is a bit different depending on the need of a pin or not, so maybe you gave me some indication with your message. 😉

> Both arm and Disarm opens the numberpad (arm does not need a code for mine, I just press check mark).

It shouldn't open the keypad when a pin is not required... Could you please share the attributes of your alarm entity?

**Comment by Doughboy68** [comment]
I was meaning that there are no differences for me in latest ESPHome.  My alarm always needs a code because I have it set that way in Home Assistant integration to require PIN, and works same on NSPanel. As a side-effect the keyboard in NSPanel pops up and I have press check mark only but this doesn't bother me.

**Comment by edwardtfn** [comment]
> I was meaning that there are no differences for me in latest ESPHome.

Yeah, I got your point... and said is good to know, as now I know one of the paths to change alarm (when no pin is set) is working, while the other path (when a pin is entered) isn't.
I could duplicate the issue described by @HolmbomDK when I've enabled a pin for my alarm, so now I know where to focus. 😉

**Comment by edwardtfn** [comment]
Forget my last message... it was my fault.
I cannot duplicate the issue.

**Comment by edwardtfn** [comment]
@HolmbomDK, do you have ["Allow the device to make Home Assistant service calls"](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Alarm-Control-Panel#allow-the-device-to-make-home-assistant-service-calls) enabled for your panel?

**Comment by edwardtfn** [comment]
> With the latest version of esphome 2023.10.1 there are no status changes from nspanel to homeassistant

@sheaur, could you please give more details on "there are no status changes from nspanel to homeassistant"? If this is not specific to not being able to disarm and Alarm, I would suggest we create another issue to track this one.

**Comment by HolmbomDK** [comment]
@HolmbomDK, do you have ["Allow the device to make Home Assistant service calls"](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Alarm-Control-Panel#allow-the-device-to-make-home-assistant-service-calls) enabled for your panel? 

YES 

Armed panel:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/60605847/44c2a7c1-54dd-4926-940b-20547d057833)

Panel after pressing disarm :
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/60605847/73f09efe-d744-4a8f-8d19-930181c6419c)


Troubleshooting :

1. Turn alarm pin off - set alarm - disarm = Alarm off  NO PROBLEMS.

1 Turn alarm pin on - set alarm - disarm - and now i get the the keyboard - and the disarm works. 

There is a "tiny bug" somewhere but I can't tell you where


Before troubleshooting only this line fired in the log and ONLY this:
  
[13:48:21][D][nextion_textsensor:014]: Processed text_sensor "localevent" state "{"page": "alarm", "key": "disarm", "value": "click", "mui": "disarm", "code_format": "number", "code_arm_req": "0"}"

After troubleshooting this 2 interesting lines fires in the log:

[13:56:24][D][nextion_textsensor:014]: Processed text_sensor "localevent" state "{"page": "alarm", "key": "disarm", "value": "click", "mui": "disarm", "code_format": "number", "code_arm_req": "0"}"
[13:56:24][D][text_sensor:064]: 'entrancenspanel NSPanel event': Sending state '{"page": "keyb_num", "component": "currentpage", "value": "pagechange"}'

Hack found - but it would be nice to do with out the problem - and it is stil a hack. Need further please write.

**Comment by HolmbomDK** [comment]
Follow up - no problems when updating to 2032.10.3

**Comment by sheaur** [comment]
Idem
