### ISSUE TITLE
Can’t start tft upload

### ISSUE THREAD

**Issue by rhyshf** [Blackymas/NSPanel_HA_Blueprint#1188]
I can flash my NSPanel from Home Assistant but I can’t get it to load the tft file. The update switch in the device is says PRESS rather than being a switch.

I have added a picture.

![IMG_5822](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/9252674/9c1abd00-ea72-490d-96e9-478af8b80fa1)

**Comment by edwardtfn** [comment]
> The update switch in the device is says PRESS rather than being a switch.

This is correct. The switch was replaced by a button since a while ago.

> I can flash my NSPanel from Home Assistant but I can’t get it to load the tft file.

What happens when you press that button? Could you please share the logs from ESPHome from when you press the button and to the moment when the panel restarts?

**Comment by TeDeVPrime** [comment]
use this....
https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload#10-use-an-older-nextion-library-for-esphome

i had the same issue

**Comment by rhyshf** [comment]
@TeDeVPrime Thanks, that worked perfectly, the tft update has worked and I now have a fully functioning NSPanel with ESPHome
