### ISSUE TITLE
Custom room temperature sensor

### ISSUE THREAD

**Issue by naofireblade** [Blackymas/NSPanel_HA_Blueprint#119]
The inbuild temperature sensor is really bad. Setting a custom temperature entity for the room would be nice.

**Comment by Blackymas** [comment]
we will do - but only after translating and notifications

**Comment by naofireblade** [comment]
Maybe I will find some time over the holidays to do this

**Comment by Blackymas** [comment]
added in https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.0.0
