### ISSUE TITLE
NSPanel component version mismatch

### ISSUE THREAD

**Issue by indyjonesuk** [Blackymas/NSPanel_HA_Blueprint#1194]
Hi all,

I have had a bit of a buggy run to 4.x versions, basic functions are working but I don't think everything is right. 

The biggest issue is I am getting a constant notification in home assistant for NSPanel component version mismatch.

![nspanel](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/109390376/4ae60fe4-a6a2-485d-9aee-a974b5ac01df)

I have tried deleted the blueprint out and copied over it again, like I have ben doing since the 1.x versions but it still gives me the error. Thank you!

**Comment by edwardtfn** [comment]
You must update your TFT to v4.0.2.

**Comment by indyjonesuk** [comment]
> You must update your TFT to v4.0.2.
> 
> https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#4-update-tft

I did do that, and shows that version on the boot screen.  Will try again thanks

**Comment by edwardtfn** [comment]
If you are uploading TFT from a local server, make sure you updated the server with the latest file from GitHub.
On the blue boot screen in your panel you should be able to see the TFT version currently installed. You need file v4.0.2.

**Comment by indyjonesuk** [comment]
Yeah was uploading from my server, but was just not pushing it. 
Glad to say I fixed it with the baud rate limit. I did upload the the blank first but might have been unnecessary. 

Thank you 👍

**Comment by indyjonesuk** [comment]
Yeah was uploading from my server, but was just not pushing it.
Glad to say I fixed it with the baud rate limit. I did upload the the blank first but might have been unnecessary.

Thank you 👍
