### ISSUE TITLE
NS Panel Config uses an Unknown service error.

### ISSUE THREAD

**Issue by Kipperking** [Blackymas/NSPanel_HA_Blueprint#1208]
Hi, I have two NSPanels which were working beautifully until I started receiving the following errors in HA:

<img width="454" alt="image" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/134694837/882c1a08-c9fc-48d7-b022-f4aa76e00dd5">

_NSPanelOne Configuration uses an unknown service
The automation "NSPanelOne Configuration" (automation.nspanelone_configuration) has an action that calls an unknown service: esphome.nspanelone_send_thermostat_cycle_state.

This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](http://homeassistant.local:8123/config/automation/edit/1684776891932) and remove the action that calls this service.

Click on SUBMIT below to confirm you have fixed this automation._

This is preventing anything displaying on the NSPanels. The relay physical buttons still work and they flash fine. I've checked they have access to the correct nspanel_eu.tft and have tried changing the dev branch to main and back but each time they reboot they go back to a blank screen. Touching the panel brings up 'loading....'

I've searched for the _thermostat_cycle_state but can only find it in the YAML of Blackymas automation. I tried commenting it out, I also tried disabling the entities in HA that are associated but neither worked.

What else can I try? Many thanks in advance for your attention.

**Comment by edwardtfn** [comment]
You probably got ESPHome updated while other parts are still with an older version.

Try to restart your panel and in the blue boot screen, take a look for versions of TFT, ESPHome and Blueprint. Those should all be with the same version.

**Comment by Kipperking** [comment]
Yes that appears to be the case,

I'm on TFT: 3.3
ESPHome: 4.0.2
Blueprint: 3.3

Can I roll back ESPHome? Will go have a google...

**Comment by edwardtfn** [comment]
> Can I roll back ESPHome? Will go have a google...

You can. It would be easier if you have v3.4 or higher, but is still possible with an older version.

**Comment by Kipperking** [comment]
Thanks for this-

Should I be updating the TFT and Blueprint instead then? does 4.02 exist for each?

Apologies for the newb questions!

**Comment by edwardtfn** [comment]
Well, this is up to you... Latest version have more features and better support, but if you are happy with v3.3 it would probably be easier to just downgrade ESPHome using the steps above, as the upload of TFT is always the part with more chances to have trouble.

If you decide to go v4.0.2, just follow the instructions here: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#2-update-blueprint

**Comment by Kipperking** [comment]
Apologies I jsut realised my issue is being way off on the Blackymas version. I'll update accordingly first of all! Hadn't realised I needed to update the files manually!

**Comment by Kipperking** [comment]
I took the plunge and updated everything to 4.0.2. I’d completely missed all the updates in between so now I get to play with shiny new features, thank you! 

Both panels updated happily OTA so quick and easy process once the issue was known! Now I just need to watch for ESPHome updating ahead of me!

**Comment by edwardtfn** [comment]
You can change from `ref: main` to `ref: v4.0.2` so instead of using latest version, you will force v4.0.2. If for some reason you compile again, it wont update to the latest code until you change that manually.
