### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by Mar1usW3** [Blackymas/NSPanel_HA_Blueprint#121]
Hi,

i tried today to flash the panel with your config but during the preparation of the image i get a an error

```
Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/adc/adc_sensor.cpp.o
In file included from src/esphome/components/adc/adc_sensor.h:4,
                 from src/esphome/components/adc/adc_sensor.cpp:1:
src/esphome/core/hal.h:14:10: fatal error: esp_attr.h: No such file or directory

******************************************************************
* Looking for esp_attr.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_attr.h"
* Web  > https://registry.platformio.org/search?q=header:esp_attr.h
*
******************************************************************

 #include <esp_attr.h>
          ^~~~~~~~~~~~
compilation terminated.
*** [/data/nspanel/.pioenvs/nspanel/src/esphome/components/adc/adc_sensor.cpp.o] Error 1
========================= [FAILED] Took 10.20 seconds =========================
```

Thats the first time i use ESPHome, did i something miss?

**Comment by Blackymas** [comment]
the flash from esphome worked but the upload of the TFT file did not or the esphome flash did not work already

**Comment by Mar1usW3** [comment]
any suggestions to fix this?

**Comment by deejaybeam** [comment]
It is very difficult to answer, because there is too less information. I am very sure, that you don´t have installed esphome as addon in HA and it´s on the latest version. If this would be the case, than all required dependencies should be installed and compiling would work as expected.

**Comment by Mar1usW3** [comment]
i have ESPHome 2022.12.3 installed via the Addon Store in HA
since you said that maybe there is an issue on the installation i uninstalled and installed ESP Home again but now i get this error:
```
Compiling /data/nspaneltest/.pioenvs/nspaneltest/src/esphome/components/adc/adc_sensor.cpp.o
Compiling /data/nspaneltest/.pioenvs/nspaneltest/src/esphome/components/api/api_connection.cpp.o
Compiling /data/nspaneltest/.pioenvs/nspaneltest/src/esphome/components/api/api_frame_helper.cpp.o
Compiling /data/nspaneltest/.pioenvs/nspaneltest/src/esphome/components/api/api_pb2.cpp.o
xtensa-esp32-elf-g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
*** [/data/nspaneltest/.pioenvs/nspaneltest/src/esphome/components/api/api_pb2.cpp.o] Error 1
========================= [FAILED] Took 565.45 seconds =========================
```

**Comment by deejaybeam** [comment]
Regarding to this
https://community.home-assistant.io/t/compilation-fails-xtensa-lx106-elf-g-fatal-error-killed-signal-terminated-program-cc1plus/463184
It is possible that the device you use to compile has too less power (ram/cpu) - but you can try to set ```compile_process_limit: 1``` see: https://esphome.io/changelog/2022.11.0.html#running-esphome-on-lower-powered-machines

**Comment by Mar1usW3** [comment]
thank you. i have currently installed HA in a Pi 3+ i tried the key but this wasn´t also not working.
So i installed HA (and ESPHome) on a VM and the compiling worked fine.
