### ISSUE TITLE
Stil strungling to update to 4.0.2

### ISSUE THREAD

**Issue by adri123** [Blackymas/NSPanel_HA_Blueprint#1213]
Hi,
Since my first of update to 4.0 I broke my pannel and still make it work again. Thats really sad.
I have the problem of slow transfer. I tried several times to update 2 or 3 day long but it field at the end.
I tried to share the tft on a http (not secured) server but it still slow to transfer.

I followed the issues talking about improve the TFT transfer but I'm not good enough to install a dev version, moreover I prefer stay on stable realeses.

My question is : when will be update the new version with the fixed upload tft ?

Thanks for your work on this project.
Best

**Comment by edwardtfn** [comment]
>  I tried several times to update 2 or 3 day long but it field at the end.

Those life long transfers always fails at the end. It shouldn't take more than 15 to 20 min, so if after 30 min it isn't getting close to the end, you should cancel and try again.

> I followed the issues talking about improve the TFT transfer but I'm not good enough to install a dev version

This should be only a single change to your yaml, on the `remote_packages` area, changing from `ref: main` to `ref: dev`.

> moreover I prefer stay on stable realeses.

I fully understand, but be aware that in this case you will run `dev` only for this upload, then you will go back to `ref: main` and everything will be working with the stable code.

> My question is : when will be update the new version with the fixed upload tft ?

I've just uploaded some important changes to the Upload TFT process and changing the ESP framework, which is quite a big change...
It will require tests... Any help here would be very welcome. 😉

**Comment by adri123** [comment]
Thank you for your response !

I can test the `ref: main` to `ref: dev` and I let you know

**Comment by denniskoenders** [comment]
Same problem here with the TFT update.
Tried to change the ref: main to ref: dev, but get an error while compiling and uploading.
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/69755275/5304edbe-a572-4008-8192-ce70314ea595)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/69755275/b7ddb65f-c6f3-4d70-a392-408d4a268ec1)
Please help.
Thanks very much.

**Comment by edwardtfn** [comment]
Could you please try again?

**Comment by denniskoenders** [comment]
> Could you please try again?

Hi Edward,

All working now, dev flash no problem and TFT update went well.
Flashed the NSpanel back to main and display working again, great!!!
Thanks very much for your support and quick fix.
Really appreciate it, great work.

**Comment by adri123** [comment]
Hi Edward, you made my nspanel back to life.
Thanks for your amazing work !
