### ISSUE TITLE
ESPHome 10.5 may break some Automations?

### ISSUE THREAD

**Issue by fordcrews** [Blackymas/NSPanel_HA_Blueprint#1217]
I upgraded to ESPHome 10.5, and suddenly all my automations broke, not sure it's not just me, but random devices device id's can't be found.   Delete them and recreate them with same settings they work.   It happened to all 15 of my nspanels.   

Automation is unavailable
Message malformed: Unknown device 'c13112c51c5565f0c82c97d882904311'

**Comment by edwardtfn** [comment]
Which version of files (TFT, ESPHome and Blueprint) are you running?

You cen see this in the blue boot screen after a restart.

**Comment by fordcrews** [comment]
v4.0.2, 2023.10.5, 4.0.2.   They all seemed to be confused about the left_button_hold_custom_action: and right_button_hold_custom_action: deviceid's and eventid's that it can't find.   Just thought I would give you a heads up if someone else had the problem.   I left a couple unfixed in case it you wanted me to test something check something if it's not just a one off for me.

**Comment by edwardtfn** [comment]
> v4.0.2, 2023.10.5, 4.0.2.

This is not looking correct.
Please press the "Reset" button and take the version numbers from the blue boot screen.

> Just thought I would give you a heads up if someone else had the problem. I left a couple unfixed in case it you wanted me to test something check something if it's not just a one off for me.

I haven't seen anyone reporting this issue. I've running ESPHome 2023.10.5 also, with the project files (TFT, ESPHome and Blueprint) all on v4.0.2 and everything worked fine with me after the update.

> left_button_hold_custom_action: and right_button_hold_custom_action: deviceid's and eventid's that it can't find.

I don't use custom hold actions... I can give a try later, but anyway, it wouldn't be exactly the same as your case as I haven't had this before the latest updates.

**Comment by fordcrews** [comment]
> > v4.0.2, 2023.10.5, 4.0.2.
> 
> This is not looking correct. Please press the "Reset" button and take the version numbers from the blue boot screen.
> 
> > Just thought I would give you a heads up if someone else had the problem. I left a couple unfixed in case it you wanted me to test something check something if it's not just a one off for me.
> 
> I haven't seen anyone reporting this issue. I've running ESPHome 2023.10.5 also, with the project files (TFT, ESPHome and Blueprint) all on v4.0.2 and everything worked fine with me after the update.
> 
> > left_button_hold_custom_action: and right_button_hold_custom_action: deviceid's and eventid's that it can't find.
> 
> I don't use custom hold actions... I can give a try later, but anyway, it wouldn't be exactly the same as your case as I haven't had this before the latest updates.

I'm not home, so I can't look at them, but 4.02 ttf is the one in the upload directory, the blueprint is 4.02, and the esphome does say 10.5 in ui.    

I don't use the hold, they just got set in the automation I copied to all the others.   It just broke all my panels.   Really strange.

**Comment by edwardtfn** [comment]
> I'm not home, so I can't look at them, but 4.02 ttf is the one in the upload directory, the blueprint is 4.02, and the esphome does say 10.5 in ui.

Yeah, I understand you have all the files with v4.0.2, but on that screen is where you can confirm the version loaded to the panel. 
I'm expecting you will see ESPHome v4.0.2 there. 😉

Please take a look at this: https://community.home-assistant.io/t/sonoff-nspanel-blueprint-configure-your-own-custom-nspanel-easy-via-a-blueprint/500577/585?u=edwardtfn
You are informing the version of item 5, on that screen you will see the version of item 6. Both items 5 and 6 are ESPHome.

**Comment by edwardtfn** [comment]
Some people is reporting devices changing it's `devuce_id` with Home Assistant 2023.11. Could be that the case here?
https://community.home-assistant.io/t/2023-11-to-do-add-release-title/634647/76?u=edwardtfn

**Comment by fordcrews** [comment]
That could be it.  I didn't notice it until I upgraded esphome, but I did update HA to 23.11 the day before.

All mine were 4.02, 4.02, 4.02, except one, and it had 4.0 ttf, I tried to flash it, it failed, failed again, then I tried to put blank on it through the _upload_tft_url, picked the wrong one, blanked one that was at 4.02, when I tried to put 4.02 back on it, it failed.    Now I have 2 I have to get reflashed.    This hasn't been my best week with nspanel.

**Comment by edwardtfn** [comment]
We are working on improving the TFT upload engine, but the latest code still on `dev`. It would be nice if you could give a try (just for upload, then you turn back to the stable version) and give some feedback.
In order to do that, please follow this:
1. On your yaml, in the `remote_package` area, change from `ref: main` to `ref: dev`
2. Install it in your device (wirelessly is fine)
3. Click on "Upload TFT" button. Please record the ESPHome logs this time.
4. After completed (or failed), change it back to `ref: main`
5. Install it in your device (wirelessly is fine)

Please let me know your results.

**Comment by edwardtfn** [comment]
Hey @fordcrews, was this week any better? 😃

**Comment by fordcrews** [comment]
I switched the 2 that were messed up to dev, and they loaded right up, some how I failed to get the flashing in the logs I downloaded, so I didn't post them, they just seemed to have the last reboot after the flash.
