### ISSUE TITLE
ESPHome devices list (esp32 ones) but not the new NS Panel device

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1219]
I managed to get everything installed.  ESP Home install went fine.  Then I managed to get the TFT panel stuff uploaded, again no real issues.  The device shows up in ESPHome without issues and I can trace the logs wirelssly.

The Panel itself shows the home screen with "Please wait..." along with the TFT and ESPHome version set to 4.0.2

The issue I have is that when I try to configure a new automation from the blueprint, I am not able to select the device.  Other ESPHome devices list (esp32 ones) but not the new NS Panel device.  I have tried rebooting things and reloading automations etc.  But I cannot select the NS Panel device as it is not in the list.

Any ideas?

_Originally posted by @adtinnis in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/443#issuecomment-1791785531_

**Comment by edwardtfn** [comment]
@adtinnis, can you see and control the device from it's page under Settings > Devices and Services > ESPHome?

**Comment by adtinnis** [comment]
Thanks for the quick reply.  Interestingly it isn't.  I hadn't thought to check there.  Do you know of a reason why it wouldn't be in there.  I can delete and reflash from scratch again, if that is likely to work.

**Comment by edwardtfn** [comment]
Try to add it manually.
Click on "Add integration", select "ESPHome" then type the host name or IP address.

**Comment by adtinnis** [comment]
That worked.  Thanks.  Looking good now.
