### ISSUE TITLE
Vacuum Integration

### ISSUE THREAD

**Issue by T-abr** [Blackymas/NSPanel_HA_Blueprint#122]
Is it possible to use the vacuum integration also on the buttons to trigger the functions like start, stop room cleaning?

**Comment by Blackymas** [comment]
yes you should put the function on the keys.

An alternative is to create a helper that you place on the keys and the helper then starts an automation.

With this varinate you can build what you want - just try it out

**Comment by T-abr** [comment]
I can't put the vacuum Entität direct to the buttons.

But I will try the other way with the helper. Thanks for your help.

**Comment by Blackymas** [comment]
ok - welcome
