### ISSUE TITLE
`Feature request` Open climate page with short press

### ISSUE THREAD

**Issue by artem82** [Blackymas/NSPanel_HA_Blueprint#1220]
Everything worked perfectly before the update. I clicked on the icon, climate control appeared: on/off temperature adjustment and selection. 
Right now, stupidly nothing is happening. I press and there is no response. Only the light works.
ALL 4.0.2
![A9DB465D-200A-4A24-8E1A-941E49DD699D](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/23581497/5412223d-0b55-4646-b5cb-01747f8df8ce)
![Uploading A9DB465D-200A-4A24-8E1A-941E49DD699D.jpeg…]()

![D14EDC47-E25A-41A2-B02C-7D15F7A4CFF9](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/23581497/7542736d-5ce1-4e69-8a0a-e52f2b0d7c9d)

**Comment by edwardtfn** [comment]
Can you see anything on ESPHome logs or Home Assistant logs (Settings > System > Logs)?

**Comment by artem82** [comment]
> Can you see anything on ESPHome logs or Home Assistant logs (Settings > System > Logs)?
> 
> What was the previous version (before the update)?
I honestly don't remember the ESP version and the current project. Everything worked fine in August. Updated esp plus the current project and stopped working. Maybe esp 10.3 and blueprint = 4.0

[home-assistant_2023-11-03T09-31-06.425Z.log](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13248621/home-assistant_2023-11-03T09-31-06.425Z.log)

**Comment by edwardtfn** [comment]
I see hundreds of instances of error `Invalid data for repeat at pos 17: expected a list for dictionary value @ data['foreground']`. This is related to the color selection which was changed from v3.4 to v4.0.
Please take a look at the item 13 on the "Breaking changes" of that "Release notes": https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v4.0

Could you please share the yaml of one of these automations so we can double check if that is really the case? Please make sure to hide any sensitive info before sharing.

**Comment by artem82** [comment]
> Could you please share the yaml of one of these automations so we can double check if that is really the case? Please make sure to hide any sensitive info before sharing.
yaml to log. Dont upload ))
[automations.log](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13248981/automations.log)

**Comment by artem82** [comment]
I deleted all the automation, created a new one and the same thing, climate.xxxx does not work

**Comment by bkbartk** [comment]
I just found that you have to long press now instead of short. 

also it would be cool if the current and set temperature could be shown in the overview.

**Comment by edwardtfn** [comment]
> I just found that you have to long press now instead of short.

Wasn't that the case since ever?

**Comment by bkbartk** [comment]
Not sure. I do not remember it like this. But it’s been a while since I have used my heating. 
but as shortpress doesn’t do anything it can look like it doesn’t work.

**Comment by artem82** [comment]
> I just found that you have to long press now instead of short.
> 
> also it would be cool if the current and set temperature could be shown in the overview.

yes, long retention began to work! thank you!
But there is a new glitch, if you make several objects in the card, for example, air conditioner 1 and air conditioner 2, then when you select air conditioner 1 after a certain time, the card changes to air conditioner 2 and so on in a circle every 2 - 5 seconds ((
In version 3.4 everything worked fine (

**Comment by edwardtfn** [comment]
The opening with a short click is now implemented in `dev` and hopefully will be available with the coming release.
