### ISSUE TITLE
nspanel is not permitted to call Home Assistant services

### ISSUE THREAD

**Issue by MKme** [Blackymas/NSPanel_HA_Blueprint#1222]
I get this with the new NSpanel install and I cant seem to find a way to enable it.  It is indeed unable to command IO in HA but seems to display all data just fine. I dont see any posts or issues so maybe its just me so far?  Thoughts?

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/13653062/36dca841-9886-466f-910e-b1897bef525a)

**Comment by edwardtfn** [comment]
This is related to permissions on your ESPHome configuration.
Please take a look at this: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Alarm-Control-Panel#allow-the-device-to-make-home-assistant-service-calls

**Comment by MKme** [comment]
Fixed!  Thanks so much.  Only available from the device menu and not the sidebar ESPHome menu.  Fixed!  Closer er up.  Maybe worthy of an FAQ entry.  Cheers
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/13653062/11b62736-987d-4d0c-9408-749ea1b7e0a9)

**Comment by edwardtfn** [comment]
> Maybe worthy of an FAQ entry.

The page I've shared to you is from the Wiki:  😉
![IMG_6526](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/fe84d6fa-8a07-4951-b8b3-c177e1069b14)
