### ISSUE TITLE
Button pages stay black

### ISSUE THREAD

**Issue by FrankBakkerNl** [Blackymas/NSPanel_HA_Blueprint#1223]
Problem: The button pages do not show anything 

After some problems getting the nspanel_eu.tft file flashed, my NSPanel now shows the home screen with the clock and temperature.
However the button pages are all black (Except for the close button and page-indicator), the weather indication is sometimes visible and sometimes not.

It does seem to pick up the blueprint, because I can change the language which is then refelcted in the clock settings. When I navigate to the blank button pages the `sensor.esp_kitchen_panel_current_page` entity in HA does show `buttonpage01`. So there is communication between the panel and HA and it knows on what page I am. Just the page itself stays empty regardless of what I put in my blueprint configuration.

I first suspected there was a problem with the tft file upload so I re flashed it a few times, tried to flash nspanel_blank.tft and then nspanel_eu.tft again, I still get the same result.

Any help / suggestions are welcome

**Comment by FrankBakkerNl** [comment]
![IMG20231103145038.jpg](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/13922018/fcc2c735-fd94-408d-b373-6401aab25efb)

![IMG20231103145049.jpg](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/13922018/a4a53b20-6cc3-42e4-9d45-230676d6c5a3)

**Comment by edwardtfn** [comment]
On the blue boot page (after a reset), which versions you see for TFT, ESPHome and Blueprint?
Can you see anything related to this in the ESPHome logs or Home Assistant logs (Settings > System > Logs)?

**Comment by FrankBakkerNl** [comment]
![IMG20231103145038.jpg](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/13922018/fcc2c735-fd94-408d-b373-6401aab25efb)

![IMG20231103145049.jpg](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/13922018/a4a53b20-6cc3-42e4-9d45-230676d6c5a3)

The versions are all 4.0.2. Sometimes it takes a long time to show the ESPHome and Bluetooth version. Sometimes it will get stuck in retry of the blueprint. After a new reboot it does startup again

**Comment by FrankBakkerNl** [comment]
Sorry about reposting the images, seems like a bug in the GitHub mobile app

**Comment by FrankBakkerNl** [comment]
The kHA logs do show this, but that seems to be because I power cycled the device

2023-11-03 18:32:36.936 WARNING (MainThread) [aioesphomeapi.connection] esp_kitchen_panel @ 192.168.xxx: Connection error occurred: Ping response not received after 90.0 seconds
2023-11-03 18:33:37.019 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp_kitchen_panel @ 192.168.xxxx: Timeout while connecting to ('192.168.xxx', 6053) (SocketAPIError)
2023-11-03 18:55:40.656 WARNING (MainThread) [aioesphomeapi.connection] esp_kitchen_panel @ 192.168.xxxx: Connection error occurred: [Errno 104] Connection reset by peer

**Comment by FrankBakkerNl** [comment]
It seems like after I cycled the power of the device it al;ways gets stuck on the initialisation screen until I trigger a reset of  ESP device from HA

**Comment by FrankBakkerNl** [comment]
Also some of the sensors are not available 

![Screenshot_2023-11-03-19-54-41-62.jpg](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/13922018/8c8911bb-ecd7-485d-ad25-f1fd0223c72d)

**Comment by edwardtfn** [comment]
> [19:02:08][W][nextion:072]: Nextion is not connected!

There is a watch dog who should rpower cycle the display after a minute after a start. Can you see this message even after that time?

**Comment by edwardtfn** [comment]
> Also some of the sensors are not available

Those sensors have been deprecated from previous versions. Maybe removing this device from Home Assistant and then adding it back will clean up that device's page.

**Comment by FrankBakkerNl** [comment]
I just created a new automation from the blueprint (and renamed the device of the exisiting one) and now most things seem to work, button pages show, climate, weather pages etc. So it seems the automation config was somehow corrupted.

The boot problem still persists. after a power cycle it keeps logging these messages after a few minutes and initialisation screen still hangs
`
[22:01:53][W][nextion:072]: Nextion is not connected! 
[22:01:53][W][nextion:072]: Nextion is not connected! 
[22:01:54][D][sensor:094]: 'esp_kitchen_panel Uptime seconds': Sending state 179.43500 s with 0 decimals of accuracy
[22:01:54][W][nextion:072]: Nextion is not connected!
[22:01:54][W][nextion:072]: Nextion is not connected! 
[22:01:54][I][ota:113]: Boot seems successful, resetting boot loop counter.
`

**Comment by edwardtfn** [comment]
Let's work with this other issue in #1224...
