### ISSUE TITLE
Climate control page switches randomly between climate entities

### ISSUE THREAD

**Issue by ra-kal** [Blackymas/NSPanel_HA_Blueprint#1225]
Hi,

I'm trying to configure control for multiple thermostats. On a button page I have a button for each climate entity. On along press a climate control screen is shown. But instead of showing the one I clicked, it randomly switches between all climate entities. It looks like once a climate entity is updated (temperature changes), this climate is immediately shown.

HA Blueprint version 4.0.2.

**Comment by edwardtfn** [comment]
When you restart your panel, in the blue boot page, which version is shown for TFT?

**Comment by ra-kal** [comment]
Version 4.0.2.
I switched do devel version 4.1dev3 and it seems to work correctly there. But once I reboot or switch off/on the panel, it shows ESPHome version 4.0.2 on the boot screen and does not load Blueprint - obviously, because the version does not match. But why the FW version is after reset reverted back to 4.0.2? Is this intended behavior for devel version?

**Comment by ra-kal** [comment]
Update: After changing OTA password the boot screen shows ESPHome version 4.1dev3 and blueprint is loaded even after reset.

**Comment by FrankBakkerNl** [comment]
I did see this as well. I also have a 'default'climate and a;so added onother one on a button page. When the page for the default was opened it sometimes just switched to the other one, or maybe it was just the text. It happened to me just a few times

**Comment by edwardtfn** [comment]
- 4.1devX is `dev` branch. This is the playground of developers, so please be prepared for some bugs. 😉 
- 4.0.2 is `main` branch. This is the stable version.

Are you sure you are working on the intended branch?

By the way, from 4.0 to 4.1 we are changing the framework from `arduino` to `esp-idf` and some other users reported the ESPHome switching between those two. More info on https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1111#issuecomment-1793830605.
We are investigating this.

**Comment by ra-kal** [comment]
Hi, I hope so :-) I'm using option "rev: dev", TFT + Blueprint from the dev branch.

I'm aware it is dev branch. I'm just playing with my NS Panel. I'm tring to figure out, how to best use it. My intention is to replace boiler remote thermostat with the NS Panel one day.

**Comment by edwardtfn** [comment]
Anyone available to test if this error was fixed on `dev`?

**Comment by FrankBakkerNl** [comment]
I just tried latest dev and got some errors when saving the blueprint

Message malformed: Integration '' not found

I did not see the issue with the climate. Then I went back to latest release branch and the issue with saving the blueprint was resolved. Not 100% sure it was related to the dev version.  I did get the climate page issue back when on dev.

**Comment by edwardtfn** [comment]
> Message malformed: Integration '' not found

Mmmm... I haven't seen that.
Where did you got this message? In a pop-up? Do you have a screenshot?
Which version of Home Assistant are you running? That will require v2023.9.0 or later.

> I did not see the issue with the climate.
> I did get the climate page issue back when on dev.

So, as I understood, you haven't seen the climate issue (jumping between entities) when in `dev`, but then when you went back to `main` you got that issue back, is that correct?

**Comment by FrankBakkerNl** [comment]
Seems like the error was because I added a custom action to one of the buttons and then partially removed it via the UI.

Indeed as far as I can see the error did not occur when I was on dev and now on main I got it back, so it seems to be fixed. I even see it now when I press a light button sometimes the climate comes over it. Maybe I will go back to dev for this

**Comment by edwardtfn** [comment]
You can find more about what is in `dev` on this discussion: https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1240

Any feedback will be very welcome. 😃
