### ISSUE TITLE
Button for climate entity

### ISSUE THREAD

**Issue by ra-kal** [Blackymas/NSPanel_HA_Blueprint#1226]
Hi,

would it be possible to display the indoor temperature with decimal point on the button card? And show climate card by pressing the button instead of long press?

**Comment by edwardtfn** [comment]
This is similar to #1220

**Comment by Jack187** [comment]
Would also like to see that behavior. Also current and set temperature displayed would be nice.

**Comment by edwardtfn** [comment]
> Also current and set temperature displayed would be nice.

We are quite limited in space on those buttons, so display two temps might be challenging.

**Comment by edwardtfn** [comment]
> And show climate card by pressing the button instead of long press?

This is already available in `dev` and hopefully will be part of the next release.

**Comment by edwardtfn** [comment]
> would it be possible to display the indoor temperature with decimal point on the button card?

This is already implemented in `dev` and hopefully will be available on the next release.
It would be nice if you could give a try on `dev` and let us know the results. 😉
