### ISSUE TITLE
Brightness bar flickering

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1229]
> I noticed something faster at 921600... when moving the brightness up and down in light page, the percent bar doesn't flicker anymore after setting a level... I honestly didn't check this prior at 115200 (maybe something else in dev makes it work different), but this has been something I have noticed for a while on panels. I will flash back to 115200 and check to confirm.

I noticed the bar flickering now after the baud update. it's like the brightness bar is getting updated too fast for the system to keep up, and getting synchronisation issues.

_Originally posted by @grigi in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1111#issuecomment-1794439699_

**Comment by edwardtfn** [comment]
I could duplicate this issue and got even ESPHome crashing when the brightness bar is changed continuously.

**Comment by edwardtfn** [comment]
@grigi, I believe this is fixed in `dev`, so I will close it for now, but I would appreciate if you can have a change to try (you must update your TFT) and let me know the results.

**Comment by grigi** [comment]
Can confirm that just updating the TFT image fixes the brightness bar flickering for me :+1:
