### ISSUE TITLE
Any chance to support Tasmota insteady of ESPhome?

### ISSUE THREAD

**Issue by TroLoos** [Blackymas/NSPanel_HA_Blueprint#123]
Hi, I have 4 nspanels configured for joBr99 nspanel-lovelace-ui.

They work quite ok, I am almost happy with it. Almost.

When I look at this project's GUI, it looks much better.

Is there any chance that you support Tasmota as a base os for nspanel? I can easily flash nextion display from Tasmota console. But I am not sure about next step - how this Blueprint would recognize the device? In joBr99 AppDeamon uses MQTT for it.

**Comment by naofireblade** [comment]
I flashed the tft file via tasmota and changed the esp to esphome afterwards because I couldn’t flash the tft from esphome as well.
End result works fine.

**Comment by Blackymas** [comment]
not sure if you can create a file - I never tried because esphome is so simple

**Comment by Blackymas** [comment]
I close the issue - you can try but it is developed for esphome
