### ISSUE TITLE
Energieverteilung

### ISSUE THREAD

**Issue by wobi07** [Blackymas/NSPanel_HA_Blueprint#1231]
Hallo!
Gibt es eine Möglichkeit auf dem NS-Panel aus Homeassistant die Energieverteilung darzustellen?
Als Beispiel ein screenshot (was ich meine / sieht cool aus)

![Energie](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/36563046/0c5e1534-97d3-4c11-8f44-161d2a91ce21)

**Comment by edwardtfn** [comment]
This is not available yet, but it is on our plans.
Please share your thoughts on this discussion: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/168

**Comment by wobi07** [comment]
Thanks, that's great!
Unfortunately I hadn't seen that there was already something about this 
🫣

**Comment by edwardtfn** [comment]
No problem at all.
🙂
