### ISSUE TITLE
Custom button images

### ISSUE THREAD

**Issue by FrankBakkerNl** [Blackymas/NSPanel_HA_Blueprint#1234]
I would like to have a button page with my favorite radio stations / playlists. It would be awesome if those would have custom images that I can somehow upload. 

I think this is also possible by making my own version of the HMI, But I am afraid this will make it hard to adopt future updates.

**Comment by edwardtfn** [comment]
Unfortunately the model of Nextion display used by NSPanel requires all images to be added at the design time, by editing the HMI file.
It is practical when we wanna have images that fits all users, but quite unpractical for individual cases.
