### ISSUE TITLE
Won't connect to Wifi

### ISSUE THREAD

**Issue by roderickton** [Blackymas/NSPanel_HA_Blueprint#1238]
Hi there,
I have watched the clips of Mark and got enthousiast so tried to flash my NSPanel
But I'm stuck. I saw someone else had the same problem. But even his solution didn't help me.
My NSPannel won't connect to my wifi. I can connect to it via my iPhone or Mac, but when I'm connected I don't know what to do.

I've added a part of the log file, it like 10 times longer, but more of the same..

Hopefully someone can help me

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
[I][logger:326]: Log initialized
[C][ota:473]: There have been 0 suspected unsuccessful boot attempts.
[D][esp32.preferences:114]: Saving 1 preferences to flash...
[D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[C][uart.arduino_esp32:077]: Setting up UART...
[D][ledc.output:055]: Calculating resolution bit-depth for frequency 1000.000000
[D][ledc.output:060]: Resolution calculated as 16
[D][binary_sensor:034]: 'nsgrey Nextion display': Sending initial state OFF
[C][switch.gpio:011]: Setting up GPIO Switch 'nsgrey Screen Power'...
[D][switch:012]: 'nsgrey Screen Power' Turning ON.
[D][switch:055]: 'nsgrey Screen Power': Sending state ON
[D][switch:012]: 'nsgrey Screen Power' Turning ON.
[D][number:012]: 'nsgrey Display Brightness': Sending state 1.000000
[D][number:012]: 'nsgrey Display Brightness Dimdown': Sending state 1.000000
[D][number:012]: 'nsgrey Temperature Correction': Sending state 0.000000
[D][number:012]: 'nsgrey Timeout Page': Sending state 15.000000
[D][number:012]: 'nsgrey Timeout Dimming': Sending state 30.000000
[D][number:012]: 'nsgrey Timeout Sleep': Sending state 60.000000
[D][template.select:014]: Setting up Template Select
[D][template.select:023]: State from initial (could not load stored index): home
[D][select:015]: 'nsgrey Wake-up page': Sending state home (index 0)
[C][switch.gpio:011]: Setting up GPIO Switch 'nsgrey Relay 1'...
[D][switch:016]: 'nsgrey Relay 1' Turning OFF.
[D][switch:055]: 'nsgrey Relay 1': Sending state OFF
[D][switch:016]: 'nsgrey Relay 1' Turning OFF.
[C][switch.gpio:011]: Setting up GPIO Switch 'nsgrey Relay 2'...
[D][switch:016]: 'nsgrey Relay 2' Turning OFF.
[D][switch:055]: 'nsgrey Relay 2': Sending state OFF
[D][switch:016]: 'nsgrey Relay 2' Turning OFF.
[D][binary_sensor:034]: 'nsgrey Left Button': Sending initial state OFF
[D][binary_sensor:034]: 'nsgrey Right Button': Sending initial state OFF
[D][template.switch:046]:   Restored state OFF
[D][switch:016]: 'nsgrey Notification sound' Turning OFF.
[D][switch:055]: 'nsgrey Notification sound': Sending state OFF
[D][template.switch:046]:   Restored state OFF
[D][switch:016]: 'nsgrey Relay 1 Local' Turning OFF.
[D][switch:055]: 'nsgrey Relay 1 Local': Sending state OFF
[D][main:1859]: Relay 1 Local turned Off!
[D][template.switch:046]:   Restored state OFF
[D][switch:016]: 'nsgrey Relay 2 Local' Turning OFF.
[D][switch:055]: 'nsgrey Relay 2 Local': Sending state OFF
[D][main:1913]: Relay 2 Local turned Off!
[D][template.switch:046]:   Restored state OFF
[D][switch:016]: 'nsgrey Notification unread' Turning OFF.
[D][switch:055]: 'nsgrey Notification unread': Sending state OFF
[C][adc:047]: Setting up ADC 'ntc_source'...
[C][adc:093]: ADC 'ntc_source' setup finished!
[D][text_sensor:064]: 'nsgrey ESPhome Version': Sending state '2023.10.6 Nov  8 2023, 15:55:55'
[D][binary_sensor:034]: 'nsgrey Status': Sending initial state OFF
[C][wifi:038]: Setting up WiFi...
[C][wifi:051]: Starting WiFi...
[C][wifi:052]:   Local MAC: 3C:E9:0E:87:C3:FC
ets Jul 29 2019 12:21:46

**Comment by edwardtfn** [comment]
You have stopped the log exactly at the moment it is trying to connect to WiFi. Is there anything after that?

**Comment by edwardtfn** [comment]
How is your panel now? Have you tried assembling it to it's back pane and then power it with 110/220VAC or are your tried only with panel disassembled and wired to the serial interface?

**Comment by edwardtfn** [comment]
Can you see anything on its display?

**Comment by roderickton** [comment]
Many thanks for your fast reply. Sorry. I will add a bigger part.

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
[I][logger:326]: Log initialized
[C][ota:473]: There have been 3 suspected unsuccessful boot attempts.
[D][esp32.preferences:114]: Saving 1 preferences to flash...
[D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[E][ota:480]: Boot loop detected. Proceeding to safe mode.
[I][app:029]: Running through setup()...
[C][wifi:038]: Setting up WiFi...
[C][wifi:051]: Starting WiFi...
[C][wifi:052]:   Local MAC: 3C:E9:0E:87:C3:FC
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
[I][logger:326]: Log initialized
[C][ota:473]: There have been 0 suspected unsuccessful boot attempts.
[D][esp32.preferences:114]: Saving 1 preferences to flash...
[D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[C][uart.arduino_esp32:077]: Setting up UART...
[D][ledc.output:055]: Calculating resolution bit-depth for frequency 1000.000000
[D][ledc.output:060]: Resolution calculated as 16
[D][binary_sensor:034]: 'nsgrey Nextion display': Sending initial state OFF
[C][switch.gpio:011]: Setting up GPIO Switch 'nsgrey Screen Power'...
[D][switch:012]: 'nsgrey Screen Power' Turning ON.
[D][switch:055]: 'nsgrey Screen Power': Sending state ON
[D][switch:012]: 'nsgrey Screen Power' Turning ON.
[D][number:012]: 'nsgrey Display Brightness': Sending state 1.000000
[D][number:012]: 'nsgrey Display Brightness Dimdown': Sending state 1.000000
[D][number:012]: 'nsgrey Temperature Correction': Sending state 0.000000
[D][number:012]: 'nsgrey Timeout Page': Sending state 15.000000
[D][number:012]: 'nsgrey Timeout Dimming': Sending state 30.000000
[D][number:012]: 'nsgrey Timeout Sleep': Sending state 60.000000
[D][template.select:014]: Setting up Template Select
[D][template.select:023]: State from initial (could not load stored index): home
[D][select:015]: 'nsgrey Wake-up page': Sending state home (index 0)
[C][switch.gpio:011]: Setting up GPIO Switch 'nsgrey Relay 1'...
[D][switch:016]: 'nsgrey Relay 1' Turning OFF.
[D][switch:055]: 'nsgrey Relay 1': Sending state OFF
[D][switch:016]: 'nsgrey Relay 1' Turning OFF.
[C][switch.gpio:011]: Setting up GPIO Switch 'nsgrey Relay 2'...
[D][switch:016]: 'nsgrey Relay 2' Turning OFF.
[D][switch:055]: 'nsgrey Relay 2': Sending state OFF
[D][switch:016]: 'nsgrey Relay 2' Turning OFF.
[D][binary_sensor:034]: 'nsgrey Left Button': Sending initial state OFF
[D][binary_sensor:034]: 'nsgrey Right Button': Sending initial state OFF
[D][template.switch:046]:   Restored state OFF
[D][switch:016]: 'nsgrey Notification sound' Turning OFF.
[D][switch:055]: 'nsgrey Notification sound': Sending state OFF
[D][template.switch:046]:   Restored state OFF
[D][switch:016]: 'nsgrey Relay 1 Local' Turning OFF.
[D][switch:055]: 'nsgrey Relay 1 Local': Sending state OFF
[D][main:1859]: Relay 1 Local turned Off!
[D][template.switch:046]:   Restored state OFF
[D][switch:016]: 'nsgrey Relay 2 Local' Turning OFF.
[D][switch:055]: 'nsgrey Relay 2 Local': Sending state OFF
[D][main:1913]: Relay 2 Local turned Off!
[D][template.switch:046]:   Restored state OFF
[D][switch:016]: 'nsgrey Notification unread' Turning OFF.
[D][switch:055]: 'nsgrey Notification unread': Sending state OFF
[C][adc:047]: Setting up ADC 'ntc_source'...
[C][adc:093]: ADC 'ntc_source' setup finished!
[D][text_sensor:064]: 'nsgrey ESPhome Version': Sending state '2023.10.6 Nov  8 2023, 15:55:55'
[D][binary_sensor:034]: 'nsgrey Status': Sending initial state OFF
[C][wifi:038]: Setting up WiFi...
[C][wifi:051]: Starting WiFi...
[C][wifi:052]:   Local MAC: 3C:E9:0E:87:C3:FC
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
[I][logger:326]: Log initialized
[C][ota:473]: There have been 1 suspected unsuccessful boot attempts.
[D][esp32.preferences:114]: Saving 1 preferences to flash...
[D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[C][uart.arduino_esp32:077]: Setting up UART...
[D][ledc.output:055]: Calculating resolution bit-depth for frequency 1000.000000
[D][ledc.output:060]: Resolution calculated as 16
[D][binary_sensor:034]: 'nsgrey Nextion display': Sending initial state OFF
[C][switch.gpio:011]: Setting up GPIO Switch 'nsgrey Screen Power'...
[D][switch:012]: 'nsgrey Screen Power' Turning ON.
[D][switch:055]: 'nsgrey Screen Power': Sending state ON
[D][switch:012]: 'nsgrey Screen Power' Turning ON.
[D][number:012]: 'nsgrey Display Brightness': Sending state 1.000000
[D][number:012]: 'nsgrey Display Brightness Dimdown': Sending state 1.000000
[D][number:012]: 'nsgrey Temperature Correction': Sending state 0.000000
[D][number:012]: 'nsgrey Timeout Page': Sending state 15.000000
[D][number:012]: 'nsgrey Timeout Dimming': Sending state 30.000000
[D][number:012]: 'nsgrey Timeout Sleep': Sending state 60.000000
[D][template.select:014]: Setting up Template Select
[D][template.select:023]: State from initial (could not load stored index): home
[D][select:015]: 'nsgrey Wake-up page': Sending state home (index 0)
[C][switch.gpio:011]: Setting up GPIO Switch 'nsgrey Relay 1'...
[D][switch:016]: 'nsgrey Relay 1' Turning OFF.
[D][switch:055]: 'nsgrey Relay 1': Sending state OFF
[D][switch:016]: 'nsgrey Relay 1' Turning OFF.
[C][switch.gpio:011]: Setting up GPIO Switch 'nsgrey Relay 2'...
[D][switch:016]: 'nsgrey Relay 2' Turning OFF.
[D][switch:055]: 'nsgrey Relay 2': Sending state OFF
[D][switch:016]: 'nsgrey Relay 2' Turning OFF.
[D][binary_sensor:034]: 'nsgrey Left Button': Sending initial state OFF
[D][binary_sensor:034]: 'nsgrey Right Button': Sending initial state OFF
[D][template.switch:046]:   Restored state OFF
[D][switch:016]: 'nsgrey Notification sound' Turning OFF.
[D][switch:055]: 'nsgrey Notification sound': Sending state OFF
[D][template.switch:046]:   Restored state OFF
[D][switch:016]: 'nsgrey Relay 1 Local' Turning OFF.
[D][switch:055]: 'nsgrey Relay 1 Local': Sending state OFF
[D][main:1859]: Relay 1 Local turned Off!
[D][template.switch:046]:   Restored state OFF
[D][switch:016]: 'nsgrey Relay 2 Local' Turning OFF.
[D][switch:055]: 'nsgrey Relay 2 Local': Sending state OFF
[D][main:1913]: Relay 2 Local turned Off!
[D][template.switch:046]:   Restored state OFF
[D][switch:016]: 'nsgrey Notification unread' Turning OFF.
[D][switch:055]: 'nsgrey Notification unread': Sending state OFF
[C][adc:047]: Setting up ADC 'ntc_source'...
[C][adc:093]: ADC 'ntc_source' setup finished!
[D][text_sensor:064]: 'nsgrey ESPhome Version': Sending state '2023.10.6 Nov  8 2023, 15:55:55'
[D][binary_sensor:034]: 'nsgrey Status': Sending initial state OFF
[C][wifi:038]: Setting up WiFi...
[C][wifi:051]: Starting WiFi...
[C][wifi:052]:   Local MAC: 3C:E9:0E:87:C3:FC
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184

**Comment by roderickton** [comment]
> Can you see anything on its display?

I just see the standard display. But nothing works. Clock isn't working. All 0's.

**Comment by edwardtfn** [comment]
Ok, looks like ESPHome is crashing when trying to connect to Wi-Fi.

Could you please share the yaml you've used to setup the device in ESPHome? Please make sure to remove any sensitive info before sharing.

**Comment by roderickton** [comment]
![Afbeelding](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/78367520/1f6d40a1-baae-49e4-8f79-46336c98d903)

**Comment by edwardtfn** [comment]
Os the panel currently powered by its 110/220VAC back panel or via serial port?

**Comment by roderickton** [comment]
> Ok, looks like ESPHome is crashing when trying to connect to Wi-Fi.
> 
> Could you please share the yaml you've used to setup the device in ESPHome? Please make sure to remove any sensitive info before sharing.

substitutions:
  ###### CHANGE ME START ######
  device_name: "nsgrey" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####
##### My customization - End #####

**Comment by roderickton** [comment]
> Is the panel currently powered by its 110/220VAC back panel or via serial port?

220VAC

**Comment by edwardtfn** [comment]
🤔

Everything looks fine.

Was the panel detected by your ESPHome dashboard or by Home Assistant?

**Comment by edwardtfn** [comment]
By the way, do you have a `secrets.yaml` file inside /config/esphome folder or are you intend to use the same secrets file from Home Assistant?

**Comment by roderickton** [comment]
> 🤔
> 
> Everything looks fine.
> 
> Was the panel detected by your ESPHome dashboard or by Home Assistant?

No unfortunately nothing happens.

**Comment by edwardtfn** [comment]
I'm far from my computer now, so I will have limited resources and will use my limited memory now... 😉 

I believe this version have `captive_portal` and the fallback wifi, so you should be able to see a wifi network related to your panel (could be with your phone)?

**Comment by roderickton** [comment]
> I'm far from my computer now, so I will have limited resources and will use my limited memory now... 😉
> 
> I believe this version have `captive_portal` and the fallback wifi, so you should be able to see a wifi network related to your panel (could be with your phone)?

Yep I can see the wifi network called "nsgrey" and I can connect to it

**Comment by edwardtfn** [comment]
When using that network, you should be able to connect to it's Web interface (http://192.168.4.1/) and set the connection to your Wi-Fi network. I wanna know if it works from there. In that case you will be able to flash over the air and your life will be easier in the next tries.

**Comment by roderickton** [comment]
Thanks! When connecting directly to its Web Interface it works. But only when I connect it to my iPhone via a Hotspot, there seems to be a connection. When I try to connect it to my wifi it fails. I mean I can't find it in my unify or HA.

**Comment by edwardtfn** [comment]
Do you have 2.4GHz enable in your router? ESP cannot connect to 5GHz.

**Comment by roderickton** [comment]
INFO ESPHome 2023.10.6
INFO Reading configuration /config/esphome/nsgrey.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Detected timezone 'Europe/Amsterdam'
INFO Starting log output from nsgrey.local using esphome API
WARNING Can't connect to ESPHome API for nsgrey.local: Error resolving IP address: [Errno -5] No address associated with hostname (APIConnectionError)
INFO Trying to connect to nsgrey.local in the background

**Comment by roderickton** [comment]
When I try to integrate it my self via Settings etc. I get the following error:
Can't make a connection with ESP. Make sure your YAML-file contains a line with 'api:'

**Comment by edwardtfn** [comment]
That remote package contains api... But have you got it connected to WiFi?

Is 2.4ghz available?

**Comment by roderickton** [comment]
Yes 2.4ghz is available. I can't connect it to my WiFi, but a hotspot like my phone isn't a problem.

**Comment by edwardtfn** [comment]
S7mikar to #1143

**Comment by ghostridernrw40** [comment]
Hi, I had the same problem with the WIFI. My NSpanels lost the connection to the WLAN in between, but here channel 11 was the problem. Maybe this is also an approach.

**Comment by edwardtfn** [comment]
@roderickton, any progress with this?

Have you tried typing your wifi credentials directly on the yaml file, without the secrets?
By the way, do you have any other ESP32 device working fine on this same wifi?

Googling a bit I found many cases of people reporting issues when connecting ESP32 to Unifi, but those are more related to disconnections after it connected.

**Comment by roderickton** [comment]
> @roderickton, any progress with this?
> 
> 
> 
> Have you tried typing your wifi credentials directly on the yaml file, without the secrets?
> 
> By the way, do you have any other ESP32 device working fine on this same wifi?
> 
> 
> 
> Googling a bit I found many cases of people reporting issues when connecting ESP32 to Unifi, but those are more related to disconnections after it connected.

Yes many thanks for your advice, this evening about 50-60min ago I flashed it again for the 44th time I think, first copied all the files in the main file without any !secret credential or "include file" and after a long wait it worked! Finally!!
Never had problems with ESP32 devices (WLED).
I'm going to check all the log files if I can find something, if so I'll let you know. For now I'm happy. I can finally spend time on adjusting the panel 😉

Cheers!

**Comment by edwardtfn** [comment]
Ok, it's probably something like adding `"` to the password with the substitutions. I will run some tests here...

**Comment by edwardtfn** [comment]
By the way, I'm also using secrets without any issue.

Could you please let me know if in your secret is like this:

```yaml
wifi_ssid: "MyWiFiSSID"
wifi_password: "MyWiFiPass"
```
Or like this:
```yaml
wifi_ssid: MyWiFiSSID
wifi_password: MyWiFiPass
```

**Comment by roderickton** [comment]
> By the way, I'm also using secrets without any issue.
> 
> Could you please let me know if in your secret is like this:
> 
> ```yaml
> wifi_ssid: "MyWiFiSSID"
> wifi_password: "MyWiFiPass"
> ```
> 
> Or like this:
> 
> ```yaml
> wifi_ssid: MyWiFiSSID
> wifi_password: MyWiFiPass
> ```

My secret was the first:
wifi_ssid: "......"
wifi_password: "........"

but I tried them both

**Comment by edwardtfn** [comment]
You can try this:

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: nsgrey 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####
wifi:
  networks:
    - id: !extend wifi_default
      ssid: !secret wifi_ssid
      password: !secret wifi_password
##### My customization - End #####
```

So you will be avoiding the substitutions. If that still not working, try to enter the ssid and pass directly in the customization area.
I don't think the include is the problem in your case.

**Comment by roderickton** [comment]
> You can try this:
> 
> 
> 
> ```yaml
> 
> substitutions:
> 
>   ###### CHANGE ME START ######
> 
>   device_name: nsgrey 
> 
>   wifi_ssid: !secret wifi_ssid
> 
>   wifi_password: !secret wifi_password
> 
> 
> 
>   nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"
> 
> 
> 
>   ##### addon-configuration #####
> 
>   ## addon_climate ##
> 
>   # addon_climate_heater_relay: "1" # possible values: 1/2
> 
> 
> 
>   ##### CHANGE ME END #####
> 
> 
> 
> packages:
> 
>   remote_package:
> 
>     url: https://github.com/Blackymas/NSPanel_HA_Blueprint
> 
>     ref: main
> 
>     files:
> 
>       - nspanel_esphome.yaml # Core package
> 
>       # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
> 
>       # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
> 
>       # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
> 
>     refresh: 300s
> 
> 
> 
> ##### My customization - Start #####
> 
> wifi:
> 
>   networks:
> 
>     - id: !extend wifi_default
> 
>       ssid: !secret wifi_ssid
> 
>       password: !secret wifi_password
> 
> ##### My customization - End #####
> 
> ```
> 
> 
> 
> So you will be avoiding the substitutions. If that still not working, try to enter the ssid and pass directly in the customization area.
> 
> I don't think the include is the problem in your case.

Thank you, just ordered a couple of nspanels because now the fun can start.. I'm going to try it out on the new ones.
I don't want to push my luck with this one!

The only thing I still can't understand is why my iPhone did connect to it without any problems and my WiFi didn't.

**Comment by edwardtfn** [comment]
Well, we can investigate more when you have your new panels. Or maybe not... hopefully those will not have any issue. 😉 
 I'm also curious to understand why is this failing.
I will close this issue, but please feel free to share more info here when you have (I will do the same) or reopen if you wanna keep trying with this.
