### ISSUE TITLE
Expose Screen ON/OFF as Entity?

### ISSUE THREAD

**Issue by Levanterman** [Blackymas/NSPanel_HA_Blueprint#124]
Hi

First, this is amazing and looks like a lot of hardwork, very impressive result ! I have x4 nsPanels and today installed this on them all.  Some baud rate issues with the Nextion but all working now. 

Question / Feature Request :

- Is it possible to turn the screen On and Off via an automation, e.g. a PIR Automation, then I can turn off the screen when the room is empty.
- Can you expose the Screen On/Off as an Entity of the Panel?

Thanks :-)

**Comment by Blackymas** [comment]
yes it is possible 

See here https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/99

wake up page = home
sleep = screensaver

so it is also possible to create a new helper and the helper starts automation. Than you can use the helper for On/OFF

**Comment by edwardtfn** [comment]
And is there a sensor that I can use to detect if the panel is already ON or if it is sleeping, so I don't call this service when someone is navigating on the panel?

**Comment by Levanterman** [comment]
> yes it is possible
> 
> See here #99
> 
> wake up page = home sleep = screensaver
> 
> so it is also possible to create a new helper and the helper starts automation. Than you can use the helper for On/OFF

This is exactly what I was looking for, sorry I didnt see #99 before posting. Thank you !  :-)
