### ISSUE TITLE
`dev` All my button pages are blank

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1242]
Build using Arduino. It certainly boots way faster and I'm not seeing the no_result logs from before.

I am however seeing a bunch of these now:
```
[23:16:20][W][nextion:394]: Nextion reported variable name invalid!
```
And all my button pages are blank for me.

_Originally posted by @grigi in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1241#issuecomment-1802884030_

**Comment by edwardtfn** [comment]
@grigi, could you please try again?

**Comment by grigi** [comment]
Latest build somehow re-introduced this issue:
```
    Panel: nsplanel1
    TFT: 4.1dev5
    ESPHome: 4.1dev5
    Blueprint (reported by ESPHome):
    Blueprint (expected): 4.1dev5
```
Where ESPHome isn't seeing the blueprint version.

Built using ESP-IDF on commit d2f4e01d303ab86618ed978c3d0e57013c693a19

**Comment by grigi** [comment]
force restarting resolved that issue... Let me do more testing

**Comment by grigi** [comment]
Oh, its the espidf/arduino thing again :sob: I'll need more time to test to determine if the issue is isolated to espidf or not. Grrrr

**Comment by grigi** [comment]
Sorry, Didn't update the blueprint. Once doing that it all works well now :-)
