### ISSUE TITLE
Addition of text component in esphome 2023.11 beta break nspanel_esphome_core.yaml

### ISSUE THREAD

**Issue by roblamoreaux** [Blackymas/NSPanel_HA_Blueprint#1247]
I installed esphome 2023.11.0b3 and now lines 367 and 1974 of nspanel_esphome_core.yaml give me an error that text is not allowed for a variable.

I suspect 'text:' needs to be changed to something else like 'ntext:', but I have not had time to investigate. It will likely need to be updated before esphome 2023.11 gets released.

**Comment by edwardtfn** [comment]
Is this with the version in `dev` or `main`?

**Comment by edwardtfn** [comment]
I've tested, it fails on both. 😩
https://beta.esphome.io/changelog/2023.11.0.html

![IMG_6565](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/a312abcc-1fc3-4788-a729-d223bd49754b)

**Comment by edwardtfn** [comment]
Thanks for the heads up.
That will probably force us to accelerate the release of v4.1.

**Comment by edwardtfn** [comment]
v4.1 is out for beta with a fix for this. 😉

**Comment by roblamoreaux** [comment]
cool. thanks for the quick work.
