### ISSUE TITLE
"Check Data..." Loop after Update

### ISSUE THREAD

**Issue by jacky-coke** [Blackymas/NSPanel_HA_Blueprint#1248]
Hi, 

think I followed the recommended update-steps but something got terribly wrong since the device is in a loop:

It starts with this: 
<img width="178" alt="image" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/80129168/030d194c-3838-4e4a-a657-d1d676bc69a0">

After reaching 100% it gives:
<img width="231" alt="image" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/80129168/3313b917-39c8-4d4d-a331-fa2442393c1c">

...and back to start; each cycle is taking approx. 3 seconds.

This is my YAML: 
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/80129168/cb352b96-80af-470e-af01-3cdf95eeddc9)

Please find the logfile here: 
[logs_nik_run (6).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13324993/logs_nik_run.6.txt)

What I already did: 

- downloaded TFT-File from HA and compared file sizes; absolutely identical
- hit "Exit reparse button" after YAML is installed and upfront updating TFT file
- various configurations of yaml file: local TFT file, source from GitHub, ... 
- configured a different wifi from another (a little bit closer) accesspoint

but nothing helped.... Any ideas? 

Best regards, 
Nik

**Comment by edwardtfn** [comment]
Don't worry, this is not as critical as it looks like. 😉 

Please try the following:
1. On the `remote_package` area, change from `ref: main` to `ref: dev`
2. Install in your device again (Wirelessly is ok)
3. On the device's page (Settings > Devices & Services > ESPHome), press the button "Upload TFT". Please copy the logs from ESPHome if you have a chance
4. Change it back to `ref: main` and install it again to your device (Wireless is OK)

No need to change the TFT file you already have in your local server.

**Comment by jacky-coke** [comment]
> Don't worry, this is not as critical as it looks like. 😉
Ok, I'm staying cool. 

> Please try the following:
> 
> 1. On the `remote_package` area, change from `ref: main` to `ref: dev`
CHECK
> 2. Install in your device again (Wirelessly is ok)
CHECK
> 3. On the device's page (Settings > Devices & Services > ESPHome), press the button "Upload TFT". Please copy the logs from ESPHome if you have a chance
[logs_nik_logs.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13325580/logs_nik_logs.txt)
CHECK
> 4. Change it back to `ref: main` and install it again to your device (Wireless is OK)
Log: 
[logs_nik_run (7).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13325607/logs_nik_run.7.txt)

> No need to change the TFT file you already have in your local server.

Great, everything worked well; thank you so much - again ;-)
