### ISSUE TITLE
Pressing button will not run automation 

### ISSUE THREAD

**Issue by rudgej** [Blackymas/NSPanel_HA_Blueprint#1249]
I have set several buttons to run automations. 

Simply they don't! he automation does not trigger.

The YAML for them is below

Entities 28 and 31 

This is either a bug or I am doing something wrong, but I have no idea what as the automation is correctly detailed 

Thanks 

Jeremy
 

    entity28: automation.house_off
    entity28_name: "House Off "
    entity28_confirm: true
    entity29: input_boolean.state_away
    entity29_name: "Away Mode "
    entity29_confirm: true
    entity30: input_boolean.state_suspend_end_of_day
    entity30_name: Suspend End of Day
    entity30_confirm: true
    show_while_loading: true
    entity31: automation.evening_on_no_conditions
    entity31_name: "Evening On "

**Comment by edwardtfn** [comment]
Which version are you running?

**Comment by edwardtfn** [comment]
Ok, I could duplicate the issue.
The button is enabling/disabling the automation. 😞

**Comment by edwardtfn** [comment]
It is solved on `dev` and hopefully will come with the next release.

**Comment by rudgej** [comment]
Thank you

**Comment by edwardtfn** [comment]
Let's discuss about this issue on https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/810#discussioncomment-7596539
