### ISSUE TITLE
more custom buttons and colors with status dependent

### ISSUE THREAD

**Issue by pillemats** [Blackymas/NSPanel_HA_Blueprint#1257]
hi 

thanks for the great blueprint! it is very cool and easy to use.

i am looking for some features:

- 1 more custom button (maybe a second line with 3 more buttons)
- it will be great when i could change the color of the icon by status depending

i hope this will be possible in the next release

thanks

**Comment by edwardtfn** [comment]
> 1 more custom button (maybe a second line with 3 more buttons)

Do you mean another custom button on the Home page? We also have custom buttons on the Climate page, so I wanna make sure we are talking about the same thing.
Currently we have 7 buttons on Home page:
Row 1, Button 1 - Customizable
Row 1, Button 2 - Customizable
Row 1, Button 3 - Customizable
Row 2, Button 4 - Notification
Row 2, Button 5 - QR code
Row 2, Button 6 - Entities pages
Row 2, Button 7 - Alarm

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/c26f8188-4d9c-4695-8a42-3bf33c0fed6e)

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/e3639586-5a5e-4190-b036-8aba46338222)

If you look at the pages, there are some spots where we probably could squeeze some additional buttons. The first row probably will accept an additional button in both cases. And the EU model have some space above the row 1 for some buttons (not sure it would fit 4 of those) while the US model have some space to the left (probably for 4 additional buttons).
We wanna add support to multiple alarm entities soon, and that will allow that alarm button in the second row to be replaced by a custom button. Notification probably should also be replaces by "To-do" entities in the future also.

> it will be great when i could change the color of the icon by status depending

Support a 2-state standard color palette (per domain?) is not a big challenge, but anything more advanced would probably be quite hard to find one solution that fits all.

**Comment by pillemats** [comment]
Thanks for the quick response 
I am using the eu model.

yes I mean to use the custom buttons for my own entities:
Row 2, Button 4 - Notification
Row 2, Button 5 - QR code
Row 2, Button 6 - Entities pages
Row 2, Button 7 - Alarm

I want to use the standard of the blueprint

**Comment by hapklaar** [comment]
I would also very much like to be able to control the color of an icon depending on status. It looks like currently the icon is either grey or white.

**Comment by edwardtfn** [comment]
- #1556
