### ISSUE TITLE
I don't see any icon or forecast information

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1259]
I don't see any icon or forecast information if I click on the weather icon. I'm using OpenWeatherMap here.

_Originally posted by @misery in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1255#discussioncomment-7548273_

**Comment by edwardtfn** [comment]
I ran some test here and looks like OpenWeatherMap isn't supporting the new forecast format yet:
![IMG_6570](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/425f8785-bcc8-4179-bf23-d52c627290e3)

I would expect the system to fallback to the legacy format, so I have to investigate.

By the way, that old format will be dropped by Home Assistant on 2024.3.

**Comment by misery** [comment]
Thanks, I already thought that but I didn't know how to check if OpenWeatherMap supports it. I switched to "Deutsche Wetterdienst" and it works for me now. :-)

**Comment by edwardtfn** [comment]
The new format was implemented a few months ago: https://github.com/home-assistant/core/pull/99002/files

So this is probably a bug. I will take a look tomorrow.

**Comment by edwardtfn** [comment]
I just found that if you go to your integration configuration and selects "onecall_daily" then the service works fine:
![IMG_6571](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/906ea26f-6dd6-462d-855c-1d2a46c96c8f)
![Uploading IMG_6572.jpeg…]()

**Comment by misery** [comment]
Strange... thanks!

**Comment by edwardtfn** [comment]
> Recent policy changes limit the API access for new registered users with a free plan, they should select the hourly mode. The other modes require a paid subscription plan.

Mmmm... That will break the integration, as we only call for daily forecast.
I will have to look at this.
