### ISSUE TITLE
Make a bit bigger the outside temperature display

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#126]
The temperature info is quite small with this implementation:
![DA703B7E-372D-45FD-91F2-243BAAE0A673](https://user-images.githubusercontent.com/94725493/209867770-2c56f0eb-688a-4577-b9ca-d977d14c614d.png)

When compared to the original display:
![C8450B70-FA39-4791-9818-A5044E7FF48A](https://user-images.githubusercontent.com/94725493/209867855-e9fcd0f9-2b8f-45f1-b245-b84570ad8216.jpeg)

Note that I have the display close to my front door and the main idea is to know how is the weather outside before I open the door, so I can get prepared. Temperature is the most important info in this case, and there's plenty of space available.
This is also a great place for an alarm panel (already requested in another item).

**Comment by Blackymas** [comment]
we will rebuild the homepage minimally at the beginning of the new year i will try to include that ;)

**Comment by edwardtfn** [comment]
I've edited the tft file myself and used the font Ubuntu 96px for that and it worked fine, so no rush...
I'm now running in this custom made HMI/TFT, which I don't like, so I would love if you can implement that anyways, then I will be back to the default implementation.

Enjoy the new year celebrations!

**Comment by Blackymas** [comment]
changed the size from 36px to 42 px.

I think it is big enough now - bigger is not possible because otherwise fields will intersect.

Under the weather icon is also no more space because in the new release at the home oage something will change for further functions.

**Comment by Blackymas** [comment]
hi

changed in https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.0.0
