### ISSUE TITLE
Camera feed

### ISSUE THREAD

**Issue by lukeman11** [Blackymas/NSPanel_HA_Blueprint#1260]
Would be nice to display a rtsp stream. Maybe also with PTZ controls?

**Comment by edwardtfn** [comment]
Unfortunately this is not natively supported by the Nextion display used by NSPanel. 😩

**Comment by edwardtfn** [comment]
I've done some tests with drawing on the display but the performance definitely is not sufficient for on demand pictures or videos. 😩
