### ISSUE TITLE
Notifications disappear after 20 seconds or so 

### ISSUE THREAD

**Issue by rudgej** [Blackymas/NSPanel_HA_Blueprint#1261]
There are 2 notification commands 

- display a notification 
- clear notifications 

The notification display with the Green Tick and Red Cross, but then clears after 20 or so seconds. 

I would have expected the notification to clear either 

a. when the clear notification command was given or 
b. when it was acknowledged by pressing the tick or cross

Is this a bug or is there a method to make a notification persist until cleared - or after an extended time such as 8 hours ?

Thanks

**Comment by edwardtfn** [comment]
We probably never though about that. It definitely sounds like a bug to me. Probably an easy one to fix, but would require an TFT update. 😩

**Comment by rudgej** [comment]
If it could go in the next release that would be great. 

Thank you.

**Comment by edwardtfn** [comment]
It is on `dev` and will be included in the coming release or patch.
