### ISSUE TITLE
Not able to use climate entities as custom button under climate.

### ISSUE THREAD

**Issue by hapklaar** [Blackymas/NSPanel_HA_Blueprint#1267]
I'm playing around to see how I could best control my other climate entities (TADO rooms other than living room). Currently I have the other climate entities configured as custom buttons on the home page, which change from grey to white when they are heating and when pressed take me to their respective climate screen, which is awesome 👍 Only would like to be able to change the 'active' color to orange or red to indicate that room is heating (also requested in #1257 )

Also wanted to see how it would look if I added them under Climate as a custom button, but there I am not able to choose any climate entity, even though the description seems to suggest it's supported:

Custom button 01 - ENTITY (Optional)
CLIMATE page
Entity which should be switched (ONLY light | switch | cover | input_boolean | automation | button | input_button | scene | person | script | binary_sensor | fan | **climate** | media_player)

How should this work?

**Comment by edwardtfn** [comment]
> Also wanted to see how it would look if I added them under Climate as a custom button, but there I am not able to choose any climate entity, even though the description seems to suggest it's supported:

>Custom button 01 - ENTITY (Optional)
CLIMATE page
Entity which should be switched (ONLY light | switch | cover | input_boolean | automation | button | input_button | scene | person | script | binary_sensor | fan | climate | media_player)

This is an error on the description for that input. Unfortunately on the way the Blueprint is currently designed we cannot have an climate page opening from another climate page.

**Comment by hapklaar** [comment]
Do you want to keep this issue open to correct the description? Otherwise can be closed!
