### ISSUE TITLE
 Error updating ESPHome

### ISSUE THREAD

**Issue by albertopalotes35** [Blackymas/NSPanel_HA_Blueprint#1280]
I have updated the nspanel_blueprint.yaml file correctly, the tft update has been correct, but when updating ESPHome I get an error, when I click validate in ESPHome the validation appears correct, but when I click install I get the following error:

INFO ESPHome 2023.10.6
INFO Reading configuration /config/alarm.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Detected timezone 'Europe/Madrid'
Failed config

display.nextion: [source /config/.esphome/packages/566b10a3/nspanel_esphome_core.yaml:716]
   id: disp1
   platform: nextion
   uart_id: tf_uart
  
   [start_up_page] is an invalid option for [display.nextion]. Did you mean [wake_up_page]?
   start_up_page: 8
   on_page:
     lambda: |-
       ESP_LOGW("display.disp1.on_page", "NEXTION PAGE CHANGED");
       ESP_LOGW("display.disp1.on_page", "New page: %i", int(x));
   on_setup:
     - script.execute: boot_sequence
   tft_url: http://192.168.1.51:8123/local/nspanel_eu.tft

If I modify the nspanel_esphome_core.yaml file by changing start_up_page to wake_up_page, that error disappears and if I try to install it again I get another error, which is the following:

INFO ESPHome 2023.10.6
INFO Reading configuration /config/alarm.yaml...
INFO Detected timezone 'Europe/Madrid'
INFO Generating C++ source...
INFO Compiling app...
Processing alarm (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
-------------------------------------------------- ---------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
  - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- WiFi @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- Update @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- WiFiClientSecure @ 2.0.0
|-- HTTPClient@2.0.0
Compiling .pioenvs/alarm/src/main.cpp.o
/config/.esphome/packages/566b10a3/nspanel_esphome_addon_upload_tft.yaml: In lambda function:
/config/.esphome/packages/566b10a3/nspanel_esphome_addon_upload_tft.yaml:96:30: error: could not convert 'disp1->esphome::nextion::Nextion::upload_tft()' from 'void' to 'bool'
              if (disp1->upload_tft()) id(restart_nspanel).press();
              ~~~~~~~~~~~~~~~~~~^~
*** [.pioenvs/alarm/src/main.cpp.o] Error 1
========================= [FAILED] Took 12.76 seconds ============ ======

The NSPanel screen stays on the boot screen and the Blueprint version does not appear on the screen

**Comment by drgonz0** [comment]
Same issue, the error I get in notifications says expected version 4.0.2.

**Comment by Doughboy68** [comment]
@albertopalotes35 Post your yaml configuration. Do you have PR#2956 in there? If so remove it.

@drgonz0 You don't seem to have the same issue, looks like you compiled ESPHome correctly to 4.1 but you have to update blueprint and TFT also to 4.1. All three have to match same versions.

**Comment by drgonz0** [comment]
Yeah, just got there on my own chasing it down, had rolled back but TFT still didn't update again.  Just updated blueprint and I'm updating the firmware now. 
Gratitude.

**Comment by drgonz0** [comment]
@Doughboy68 Yeah I just got there on my own as well.  Just finished pushing new firmware about to try TFT

**Comment by albertopalotes35** [comment]
What yaml file do I have to check if it is PR#2956?

**Comment by edwardtfn** [comment]
On your ESPHome dashboard, when you click "Edit" in the device's box related to your panel, you get the yaml @Doughboy68 is talking about.

**Comment by albertopalotes35** [comment]
That was why the configuration related to pr#5016

###### USE THIS ONLY FOR YOUR FIRST TFT UPLOAD, ONCE IT WORKED, REMOVE THESE LINES ######
#external_components:
# - source: github://pr#5016
# components: [nextion]
# refresh: 1h
################################################## #############################

I have deactivated it and it has worked correctly again, I had it activated because the last time I updated the TFT it was not updated until I activated that configuration
