### ISSUE TITLE
TFT version mismatch after upgrade

### ISSUE THREAD

**Issue by mateszddd** [Blackymas/NSPanel_HA_Blueprint#1289]
After upgrade to 4.1 screen is locked on synchronization despite uploading multiple displays

![obraz](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/123839696/efcdd516-65af-4622-bc23-4f40823e2e0c)
![obraz](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/123839696/6dfe3539-2ccf-469e-848f-055ccbc4789c)
![obraz](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/123839696/55905acc-377d-4425-87fa-2ea1362ca1d9)

This might be because i'm a noob but i really can't find what i'm doing wrong

**Comment by marcelloceschia** [comment]
@mateszddd you need to upload the new version of nspanel_eu.tft like you did in the initial setup

**Comment by mateszddd** [comment]
Sorry for late response @marcelloceschia 
it seems that loading from http doesn't work either:
![obraz](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/123839696/cafe5e73-0d67-4d18-aaef-b825ef1ee54c)
(i have port set to 80, so link is correct)
![obraz](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/123839696/a109f5f1-4ea9-46ca-a972-6a5f3f4d1433)
![obraz](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/123839696/486828ce-526d-40b6-a55b-111e275ee972)

There are no errors during install, everything looks correct, yet once started tft version doesn't bump to 4.1.1
Do i have to load file using serial adapter instead of wifi?

**Comment by mateszddd** [comment]
nevermind, i forgot about existance of this button:
![obraz](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/123839696/c7907242-ae9e-466a-8a34-4f5f4b85eaac)
