### ISSUE TITLE
Control of hardware button on/off indicator, automation toggle state

### ISSUE THREAD

**Issue by samjw-nz** [Blackymas/NSPanel_HA_Blueprint#1291]
With the latest update changing how hardware buttons operate "Buttons now will run an automation" I cannot easily see the state of my automation. 
As an example, on 4.0.1 I had a single press toggle a 'Turn the lights on at 7am' automation, and I could see by the color of the indicator whether the automation was on or off.

On v4.1 having created a script to toggle the automation for 'legacy behaviour' the light simply flashes as the script runs, and I have no way of quickly seeing if my automation is enabled or not.

Any suggestions on how to accurately replicate 4.0.1 toggle behaviour with the indicator working?

**Comment by edwardtfn** [comment]
Let's discuss about this issue on https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/810#discussioncomment-7596539

**Comment by edwardtfn** [comment]
I've added a selector to switch between **Toggle** and **Trigger** for button automations. This feature is now in the `dev` branch and will be included in our next release.

**Comment by edwardtfn** [comment]
- #1556
