### ISSUE TITLE
`Feature request` Assign a climate to the hardware buttons

### ISSUE THREAD

**Issue by umognog** [Blackymas/NSPanel_HA_Blueprint#1295]
Setup: Climate included, thermostat created to control heating. Relay 1 is connected to the boiler.

I'm wanting parity between home assistant interface, the panel and UI or physical buttons. When the left hardware button is pressed, i want to toggle the climate thermostat from between off and idle/heat. When toggling to idle/heat I desire the indicator on the NSPanel display above the hardware button to "light up" - change color. When toggling to off, I desire the indicator to shift back to "dull" - change color again.

When I set the hardware button to toggle the relay, this happens without issue but i dont want to toggle the relay - i want to change the HVAC mode.

I tried creating an automation, when left button is pressed, condition: if off toggle to heat otherwise default to off. This behaves with the relay exactly as I want, BUT it does not change the indicator on the NSPanel above the switch.

I've searched through and cannot find the state of the indicator on the homepage settings nor the hardware settings. If I change the hardware to activate the automation, it seems to create a loop and the automation disables itself.

I suspect that what I am missing is a keyword to describe that state indicator and therefore set it, but with searching I cannot seem to find what I am talking about. any advice would be appreciated.

**Comment by edwardtfn** [comment]
Have you tried to assign the climate entity to the hardware button?

**Comment by umognog** [comment]
I think the change to the issue title has answered what I was about to reply: you can't currently assign a climate entity to a hardware button.

I tried calling an automation with no trigger, created a weird bounce HA that causes the automation to be disabled to prevent a never ending loop, because the button is momentary.

In researching, potentially a script would be the right method to do that but not something I've tried yet.

> Have you tried to assign the climate entity to the hardware button?

I think the change to the issue title has answered what I was about to reply: you can't currently assign a climate entity to a hardware button.

I tried calling an automation with no trigger, created a weird bounce HA that causes the automation to be disabled to prevent a never ending loop, because the button is momentary.

In researching, potentially a script would be the right method to do that but not something I've tried yet.

**Comment by edwardtfn** [comment]
Yeah, a script should work, but ideally it should be possible to assign a climate. The only issue is that a climate on any other button opens the climate lá em while you want to toggle the climate.

**Comment by umognog** [comment]
Just created a script that toggles the climate, assigned to left button.

The climate behaves as expected, but the panel tft still doesn't light the blue status indicator. I forced it from idle to heat to activate relay 1 (which controls the heating) and again, the status indicator stayed grey in colour.

It's not the worst thing in the world (oh the 1st world problems) but it improves the ease of use by visitors to the house that use it (child minders mostly) to simply push the button and visually see the indicator tell them it's now on heat mode.

For now, I'll add a service call to notify on the panel.

**Comment by edwardtfn** [comment]
- #1556
