### ISSUE TITLE
Feature Request - Hardware button "local fallback" for lost network connection

### ISSUE THREAD

**Issue by weberjam007** [Blackymas/NSPanel_HA_Blueprint#1296]
It would be great to have the "local fallback" option trigger on a prolonged loss of network/Wi-Fi connection.

I put the touchscreen in place of an existing switch. I use smart bulbs that are constantly powered for that location (actually for all lights). I ran the switch wire through one of the relays on the touchscreen and keep that relay in the on state. I then program the hardware buttons to control the lights in the entire room (via a group helper). If for some crazy reason I lost my Wi-Fi connection the bulbs can react properly to being relay being switched on and off by the touchscreen. 

I know that this situation does not happen very often but if I put one of these keypads in a place where I absolutely must have control of the locally connected light, then I would like to have that rare case supported (e.g., a hallway light wired to the relay). 

It might be nice to have this as a second "local fallback" option. It likely would be implemented to fallback after a user interacts with the touchscreen and it determines that it does not have a network connection.

**Comment by edwardtfn** [comment]
You can set the button to control the smart bulb and enable fallback to that button, so when you have Wi-Fi it will use Home Assistant to send commands to the bulb, but if HA or Wi-Fi are out, it will fallback and the button will be controlling the relay.

**Comment by weberjam007** [comment]
I read this totally wrong then:
<img width="611" alt="image" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/36638740/2ebb7c33-2b22-4d34-9e7f-c97c22330325">
I thought that was telling me that fallback would occur if the LCD panel stopped responding. What you said makes more sense for this feature 😇
