### ISSUE TITLE
The sensor "Current Page" (sensor.nsppanel_current_page) is unavailable.

### ISSUE THREAD

**Issue by arungpillai** [Blackymas/NSPanel_HA_Blueprint#1297]
After the latest ESPHOME update, I'm encountering the following error. Despite enabling and restarting both automation and the system, the error persists, and 'current_page' remains unavailable.

NSPanel sensor unavailable
The sensor "Current Page" (sensor.nspwhite_current_page) is unavailable.

Panel: nsppanel
Blueprint version: 4.0.2
Sensor's expected entity_id: sensor.nspwhite_current_page
How to fix this:

Go to the [device page]

Find the sensor "Current page" under the "Sensors" area (it might be in the "sensors not shown" group)

Enable the sensor

Wait a bit until the sensor starts providing a value (it shouldn't take more than half minute)

**Comment by edwardtfn** [comment]
When you restart your devices, which versions you see for TFT, ESPHome and Blueprint in the blue boot page?

**Comment by arungpillai** [comment]
Thanks, each time after the ESPHOME update do I need to follow these steps? Is there an easy way to automate it :)

**Comment by edwardtfn** [comment]
> Thanks, each time after the ESPHOME update do I need to follow these steps? Is there an easy way to automate it :)

Unfortunately Home Assistant limits the auto update of Blueprints although you will faint in the community some tools that may help you with this task.

**Comment by arungpillai** [comment]
Thanks a lot you have a nice weekend.

**Comment by edwardtfn** [comment]
https://community.home-assistant.io/t/allow-blueprint-upgrades/366939
