### ISSUE TITLE
feature request : US version  portrait display orientation

### ISSUE THREAD

**Issue by kendadk** [Blackymas/NSPanel_HA_Blueprint#130]
can there be a portrait display orientation for the US version NS Panel?

**Comment by Blackymas** [comment]
Hello - generally this is possible. 
Unfortunately I do not have the US version. I need someone who has the US version and just moves the fields in the Nextion editor.

Programming is not necessary, just moving the fields.

Are you interested in changing this - I have uploaded the HMI - if you have any questions I would be happy to help you.

**Comment by kendadk** [comment]
Thank you it will take me some time but I have started adjusting the pages to the portrait orientation I will upload the HMI file when I am done. Sent from my iPhoneOn Dec 29, 2022, at 7:19 PM, Blackymas ***@***.***> wrote:﻿
Hello - generally this is possible.
Unfortunately I do not have the US version. I need someone who has the US version and just moves the fields in the Nextion editor.
Programming is not necessary, just moving the fields.
Are you interested in changing this - I have uploaded the HMI - if you have any questions I would be happy to help you.

**Comment by Blackymas** [comment]
nice big thanks - Maybe you can also contact him he also has the US version.


https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/149

**Comment by willyhabr** [comment]
Hi, I'm interested in the US portrait version too. Is there any hmi file ready? Could I help with something?

**Comment by kendadk** [comment]
I have just barely started and I am new to nextion editor so it could take me awhile before  I could have an HMI file ready .  The thermostat images will need some work to make them usable in the portrait orientation. So that is where I am stuck at the moment. And I am not sure when I will get to that . Sent from my iPhoneOn Jan 5, 2023, at 11:19 AM, willyhabr ***@***.***> wrote:﻿
Hi, I'm interested in the US portrait version too. Is there any hmi file ready? Could I help with something?

**Comment by willyhabr** [comment]
Thanks for your reply. I will be waiting, and if there is something that can help, let me know....
Thanks again

**Comment by willyhabr** [comment]
> Do you know anything about using Nextion editor?? Or any graphics editor for editing the graphics files to be the right dimensions ?? If so I can send you the HMI file so you can extract the images to edit!Sent from my iPhoneOn Jan 5, 2023, at 1:27 PM, willyhabr ***@***.***> wrote:﻿ Thanks for your reply. I will be waiting, and if there is something that can help, let me know.... Thanks again —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

HI Kendadk, I was on a trip. Well, I started at Nextion some days ago, and I designed my home controllers using home remote software.

**Comment by chheiss** [comment]
Has anyone made progress one this? I have the US version, too, and would like to get it into portrait mode as well...
Thanks!

**Comment by Blackymas** [comment]
> 

I don't have a US display - would be great if you take a look at it and I can add it here in Github.

**Comment by Blackymas** [comment]
@all 

A user from the community wrote the following

@remotesHUB wrote "BTW both EU and US versions have the same Nextion displays, just the orientation of US one (same we have for AU) is 90 degrees rotated -> portrait."

https://www.youtube.com/watch?v=b7vW4YtUaTs

**Comment by anuadu** [comment]
Hi I am the same user @remotesHUB who wrote a comment confirming that both EU and US version has the same Nextion display. I have used the Nextion Editor and did some crude modifications to boot, home and buttonpage01,  got working on the US version.  Not pretty looking as I am no graphic person, but works ok. 
One correction, the orientation of the Nexiton display on US version is 180° Vertical 
![Nextion](https://user-images.githubusercontent.com/13360691/213956478-e841da8c-4537-4af2-97e0-6fea93961c5b.JPG)

**Comment by Blackymas** [comment]
hi - can you share the hmi? 
will have a look and upload it here on github

**Comment by jonkatz1** [comment]
looking for ward to this! I can help/test/update, just let me know what is needed

**Comment by miniminne** [comment]
Happy to help test as well, I have the US version

**Comment by electrosparkz** [comment]
Ditto, I just came across this a few days ago and have the US version. Started looking at the HMI myself last night, but didn't have much time to get very far. Would be interested to see the version @anuadu has put together to test/tweak as well

Thanks!

**Comment by anuadu** [comment]
I will share it this afternoon

**Comment by miniminne** [comment]
@Blackymas - I'm not seeing the photos used in the HMI posted in the repo, is it possible to snag those and I can do a rough draft as well?

**Comment by anuadu** [comment]
![IMG_0577](https://user-images.githubusercontent.com/13360691/214251553-723ad829-7c88-4bf0-9662-0fee668872bd.jpg)
![IMG_0578](https://user-images.githubusercontent.com/13360691/214251656-8edd2d29-0b64-4c73-9c48-d76b6e4586dd.jpg)
![IMG_0579](https://user-images.githubusercontent.com/13360691/214251684-4d9fa654-36d0-4a7b-b0df-92c91405fcda.jpg)
[nspanelUS.zip](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10487933/nspanelUS.zip)
here are the files

**Comment by wynies123** [comment]
when trying to flash tft with tasmota console I get this "unsupported operand type(s) for <: 'nil' and 'int' "

**Comment by miniminne** [comment]
![image](https://user-images.githubusercontent.com/8529568/214357878-271635fd-651f-4f8f-a688-86917846e467.jpeg)![image](https://user-images.githubusercontent.com/8529568/214357879-bb2e0cc0-c8c7-410f-83d0-2d470e4e1063.jpeg)

Working for me! I can see some of the funkiness mentioned but there are some good bones here! Great job @anuadu

**Comment by benmartucci** [comment]
> ![IMG_0577](https://user-images.githubusercontent.com/13360691/214251553-723ad829-7c88-4bf0-9662-0fee668872bd.jpg)
> ![IMG_0578](https://user-images.githubusercontent.com/13360691/214251656-8edd2d29-0b64-4c73-9c48-d76b6e4586dd.jpg)
> ![IMG_0579](https://user-images.githubusercontent.com/13360691/214251684-4d9fa654-36d0-4a7b-b0df-92c91405fcda.jpg)
> [nspanelUS.zip](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10487933/nspanelUS.zip)
> here is the file in zip...it is quick and drity work...but it works

Do you have any instructions or steps to get this working ?

**Comment by kendadk** [comment]
You need to use this with the Blueprint . Sent from my iPhoneOn Jan 24, 2023, at 3:48 PM, benmartucci ***@***.***> wrote:﻿




nspanelUS.zip
here is the file in zip...it is quick and drity work...but it works

Do you have any instructions or steps to get this working ?

**Comment by benmartucci** [comment]
@anuadu do you have any instructions or steps to get this working ?

**Comment by miniminne** [comment]
@Be

> > ![IMG_0577](https://user-images.githubusercontent.com/13360691/214251553-723ad829-7c88-4bf0-9662-0fee668872bd.jpg)
> > ![IMG_0578](https://user-images.githubusercontent.com/13360691/214251656-8edd2d29-0b64-4c73-9c48-d76b6e4586dd.jpg)
> > ![IMG_0579](https://user-images.githubusercontent.com/13360691/214251684-4d9fa654-36d0-4a7b-b0df-92c91405fcda.jpg)
> > [nspanelUS.zip](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10487933/nspanelUS.zip)
> > here is the file in zip...it is quick and drity work...but it works
> 
> Do you have any instructions or steps to get this working ?

If you download the zip file and upload to the WWW directory of HomeAssistant, you can call the ESPHome upload_tft_url service to point it to this file and flash the display with the beta firmware.

**Comment by kendadk** [comment]
Yes in the instructions with the mapa el blueprint. Sent from my iPhoneOn Jan 24, 2023, at 3:50 PM, benmartucci ***@***.***> wrote:﻿
@anuadu do you have any instructions or steps to get this working ?

**Comment by benmartucci** [comment]
@anuadu 
[NSpanelUS.pdf](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10495546/NSpanelUS.pdf)


thanks got it working

**Comment by miniminne** [comment]
[nspanelUS.zip](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10495628/nspanelUS.zip)

I did make some changes to the Button Pages & tried some cleanup around weather/climate/settings, but those are gonna need some TLC. 

Little fixes are shown below:

**Comment by miniminne** [comment]
[nspanelUS.zip](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10495935/nspanelUS.zip)
Made some fixes myself regarding placement/organization of buttons. Climate/Settings are gonna need a lot of TLC

**Comment by miniminne** [comment]
Hey @Blackymas ! Is it possible to get the raw background/icon images? i have some time this week I could edit them into the vertical orientation/edit some of the weather icons to not have a black box around them (if possible) so they don't interfere with the current wallpaper chosen with the project.

**Comment by miniminne** [comment]
> Tested your last version @miniminne, is your config button working?
> 
> Also it feels hard to trigger the close button along the pages. Anyone experiencing this?

Do you mean the settings button? Mine is but I know the settings page needs some TLC before its really usable

Hmmm the close button is a little hard to hit sometimes, let me play around with the button area and see if that can fix it. I'll also check the little settings button!

**Comment by dudu631** [comment]
Yep, just confirmed it is working but it's hard to trigger it just as the close icon.

**Comment by miniminne** [comment]
[nspanelUS.zip](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10514341/nspanelUS.zip)

Ok thanks for the feedback @dudu631 ! I did work on making the targets a bit bigger but we are a little constrained by the button sizes for the lights/covers/what-have-you on the button pages.

Settings target should now be bigger too! Clicking it should see a rough first draft of a "fixed" settings page. It should be workable now with some graphical quirks until I hone those. 

I'm also posting these to my repo if anyone wants to pull from there vs random zips.

**Comment by dudu631** [comment]
Nice! I'll test those and give you some input. 

I have no expertise with Nextion Editor, but I might take a look on that as well.

**Comment by miniminne** [comment]
[nspanelUS.zip](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10515276/nspanelUS.zip)

Ok so, I'm feeling creative and redid the settings menu to look better (IMO). Its now horizontal instead of vertical, and I found the same vector icons the project used (I think). I adjusted touch targets for the sliders/reboot & sleep buttons so we should be looking good there!

If anyone is testing this, please let me know if y'all prefer the the settings layout in this little test release or would prefer something different 😅

**Comment by red-centre** [comment]
thanks @miniminne for your work on this - I was tinkering around with my own effort, but hit a snag (somehow got a screensaver screen as a boot screen, and had some trouble updating tft's while testing.  in the mean time, you've done great work.  Will test it out and let you know what I think.

**Comment by red-centre** [comment]
might be a delay in testing - uploaded the new tft and now getting a "system date error" message, so might have to reset the panel and try again

> [nspanelUS.zip](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10515276/nspanelUS.zip)
> 
> Ok so, I'm feeling creative and redid the settings menu to look better (IMO). Its now horizontal instead of vertical, and I found the same vector icons the project used (I think). I adjusted touch targets for the sliders/reboot & sleep buttons so we should be looking good there!
> 
> Oh! And I fixed the boot logo so it looks clean and sleek now!
> 
> If anyone is testing this, please let me know if y'all prefer the the settings layout in this little test release or would prefer something different 😅

**Comment by miniminne** [comment]
> 

Oh weird! I haven't seen that one yet.... 

And yeah, Nextion Editor is not my favorite program to use...thank god Inkscape exists to help plan out some of this!

**Comment by miniminne** [comment]
> might be a delay in testing - uploaded the new tft and now getting a "system date error" message, so might have to reset the panel and try again
> 
> > [nspanelUS.zip](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10515276/nspanelUS.zip)
> > Ok so, I'm feeling creative and redid the settings menu to look better (IMO). Its now horizontal instead of vertical, and I found the same vector icons the project used (I think). I adjusted touch targets for the sliders/reboot & sleep buttons so we should be looking good there!
> > Oh! And I fixed the boot logo so it looks clean and sleek now!
> > If anyone is testing this, please let me know if y'all prefer the the settings layout in this little test release or would prefer something different 😅

Let me know if I can help in any way! I'm still getting used to Nextion Editor's quirks, but nothing I did should break things...mostly just organizing/re-configuring graphics to work for the US models while retaining the same general "vibe" as the EU models

**Comment by red-centre** [comment]
> 

Thanks - got your file working - it looks great - well done!  when it first boots, there is something blocking the top right of the time - but it disappears after a few seconds
![IMG_8197](https://user-images.githubusercontent.com/91818884/215035339-62ca4d19-f989-4469-b2bf-332aed67cc22.jpg)

**Comment by miniminne** [comment]
Weird! I got that glitch too, but once I rebooted it went away. The time wasn't updating either, but I did recently do an ESPHome update so I wonder if thats related.

**Comment by dudu631** [comment]
Made a version with solid black background because I was annoyed by the icons being ugly.

[USpanel.zip](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10523111/USpanel.zip)

The close button still feels weird to trigger, but at least now it's all working for me!

**Comment by miniminne** [comment]
Yeah the black backgrounds are kinda killing me on some of these icons. I'm trying to use the MDI icons whenever I can since those seem pretty standard across this project + HA in general. 

It's also funny you mention that, I just rearranged the icons on the home screen to hide the black backgrounds better but I can always move them back if folks want!

I took a first stab at the climate page here too, but that one we may need @Blackymas or the other devs to help us out because I'm not sure we can make their slider entities fit within the circle unless it becomes cut off (cons of the narrower vertical interface). Sliders aren't working either but I figured I can get the design up and out there and brainstorm how to do the thermostat. 

First stab was taken at weatherpage 1 too. 

@red-centre -
 I figured out what those cutoffs were! Turns out the notification icons were cutting off the time before being hidden. They're moved to the left side's void now so we shouldn't see that issue. Time & date were shifted right to accommodate this

[nspanelUS.zip](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10523355/nspanelUS.zip) (I didn't replace the wallpapers in this one with a black background 😢 )

**Comment by Blackymas** [comment]
Hahaha nextion and pictures XD

Nextion unfortunately can't do graphics with transparent background that makes it mega hard.

I would recommend you to just take a completely black background. I have also taken only black background for some pages.

Then you can freely occupy the positions.

This wave really only fits the eu model because I have also designed weeks so that somehow fits together.


I would first make a version without the wave then you can position everything freely and then you can see if you can incorporate a wave somewhere. Should actually be enough on the home screen.

I have drawn the whole thing with adobe in 1000 individual images until everything fit.


So my suggestion. Take only a black background and simply arrange all as it fits best or optically looks best.

**Comment by Blackymas** [comment]
maybe someone donate me 90 euros then I buy the US version and help you ;)

https://www.amazon.de/NSPanel-Smart-Switch-eWeLink-Schwarz/dp/B0B53Y99TL/ref=sr_1_2?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2XTQ6A5EPHHGX&keywords=nspanel+us&qid=1674860132&sprefix=nspanel+us%2Caps%2C73&sr=8-2

**Comment by dudu631** [comment]
I just realized I am having trouble triggering the X and Settings icons because my touch inputs are not calibrated. It's triggering about 0.5cm above where my finger is touching. 

Could this be a faulty unit, or is this fixable?

**Comment by jonkatz1** [comment]
> maybe someone donate me 90 euros then I buy the US version and help you ;)
> 
> https://www.amazon.de/NSPanel-Smart-Switch-eWeLink-Schwarz/dp/B0B53Y99TL/ref=sr_1_2?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2XTQ6A5EPHHGX&keywords=nspanel+us&qid=1674860132&sprefix=nspanel+us%2Caps%2C73&sr=8-2

Done via PayPal.

**Comment by miniminne** [comment]
> Hahaha nextion and pictures XD
> 
> Nextion unfortunately can't do graphics with transparent background that makes it mega hard.
> 
> I would recommend you to just take a completely black background. I have also taken only black background for some pages.
> 
> Then you can freely occupy the positions.
> 
> This wave really only fits the eu model because I have also designed weeks so that somehow fits together.
> 
> I would first make a version without the wave then you can position everything freely and then you can see if you can incorporate a wave somewhere. Should actually be enough on the home screen.
> 
> I have drawn the whole thing with adobe in 1000 individual images until everything fit.
> 
> So my suggestion. Take only a black background and simply arrange all as it fits best or optically looks best.

These icons are all handmade?! Well damn! Forget $90 you need another 0 at the end of that haha. 

I did wipe the backgrounds out and turned them al black. So, it's looking pretty good! 

[nspanelUS.zip](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10523980/nspanelUS.zip)

**Comment by Blackymas** [comment]
i work with adobe express - maybe i will create a collection and share it here - adobe express is also free.

I almost thought it would be better if you made the background black. that's how I started.

Send me some pictures

If you have a final version I will upload it.

The question is, what do we do with the next versions?

We have just built QR Code and Entity pages XD

**Comment by miniminne** [comment]
Not sure if other folks feel it's ready for a 0.9/1.0 release, but if we want we can go ahead and release it and I can take a look at the dev branch to see what needs updated on those new pages? Then hopefully everything will be synced up going forward. 

![image](https://user-images.githubusercontent.com/8529568/215229831-a05481a0-f616-40c4-b020-94afc89310c3.jpeg) ![image](https://user-images.githubusercontent.com/8529568/215229840-ef7b9861-4cdd-4a6d-b86a-f33142ecdea9.jpeg) ![image](https://user-images.githubusercontent.com/8529568/215229846-fc4d7a02-76b6-49c5-bec5-4a236fabb02e.jpeg) ![image](https://user-images.githubusercontent.com/8529568/215229853-5b16bbef-61d7-4f03-b7ae-6937b5c107d9.jpeg) ![image](https://user-images.githubusercontent.com/8529568/215229857-37ed953d-0ab4-4e93-a5d6-cff7ff31dd25.jpeg) ![image](https://user-images.githubusercontent.com/8529568/215229869-af33bf0f-a812-44b9-bae3-d7dde1f04a05.jpeg) ![image](https://user-images.githubusercontent.com/8529568/215229871-9777a22a-c5bc-49ce-9a2e-27350e9ec4c5.jpeg)

**Comment by anuadu** [comment]
good work @miniminne 
good enough for the NSPanel sitting on my desk since Mar2022 can finally be installed on the wall.

@Blackymas idea of blueprint-based setting up is brilliant, making it easier to maintain and implement changes.

**Comment by nassermahrous** [comment]
well done, It would be nice if we can change the background from the blueprint UI, also will it make a difference if someone needs less pages in the performance of the panel

**Comment by Blackymas** [comment]
@miniminne nice work!

pls add me in discord Blackymas#0129

**Comment by miniminne** [comment]
> @miniminne nice work!
> 
> 
> 
> pls add me in discord 
> 
> ```
> 
> Blackymas#0129
> 
> ```

Sent a request over!

**Comment by Loose-Moose77** [comment]
[nspanelUS.zip](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10530938/nspanelUS.zip)

Huge thanks to @miniminne for all the work put in so far. Wanted to help over the last few days but they've been pumping out such consistent updates I haven't been able to keep up!

The zip file contains my progress so far, I've worked off of the void version, but added back in the ribbon background using @Blackymas advice of orienting the background to miss most of the icons. My updates on background are on the main, settings, and climate pages. I did take some liberties with the hidden icons being moved around on the main page to make it all work. Settings were pretty straight forward, though I did better align the brightness slider. 

Climate is where I spent most of my time, trying to align the temperature dial back to where it was in the everyone but US version, seems to fit now without much issue.

I've also included an updated blueprint for US that uses imperial measurements for precipitation and wind speed. It also includes dates in an US typical Month / Day format and a 12hr clock instead of 24hr. It would have been more professional of me to update the blueprint with an ENG-US language selection, but I didn't go that far yet.

I do believe I need to update the scaling on the climate page yet, as the use of F instead of C completely fills the bar, but I haven't been able to look at this yet - I'm assuming it's in the blueprint somewhere.

Thanks everyone for the work on this so far! This has been sitting on my desk for a year now and with this update I'm finally feeling like it is getting to the point where I can get it on the wall!

**Comment by Blackymas** [comment]
> [nspanelUS.zip](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10530938/nspanelUS.zip)
> 
> Huge thanks to @miniminne for all the work put in so far. Wanted to help over the last few days but they've been pumping out such consistent updates I haven't been able to keep up!
> 
> The zip file contains my progress so far, I've worked off of the void version, but added back in the ribbon background using @Blackymas advice of orienting the background to miss most of the icons. My updates on background are on the main, settings, and climate pages. I did take some liberties with the hidden icons being moved around on the main page to make it all work. Settings were pretty straight forward, though I did better align the brightness slider.
> 
> Climate is where I spent most of my time, trying to align the temperature dial back to where it was in the everyone but US version, seems to fit now without much issue.
> 
> I've also included an updated blueprint for US that uses imperial measurements for precipitation and wind speed. It also includes dates in an US typical Month / Day format and a 12hr clock instead of 24hr. It would have been more professional of me to update the blueprint with an ENG-US language selection, but I didn't go that far yet.
> 
> I do believe I need to update the scaling on the climate page yet, as the use of F instead of C completely fills the bar, but I haven't been able to look at this yet - I'm assuming it's in the blueprint somewhere.
> 
> Thanks everyone for the work on this so far! This has been sitting on my desk for a year now and with this update I'm finally feeling like it is getting to the point where I can get it on the wall!

can you add me in discord?

I will look at this and support you.

It would be good if we make a group in discord together with @miniminne  that we work together on a version.
So that we do not have 2 or 3 versions

**Comment by anuadu** [comment]
Please bear in mind, not all the users of the portrait US version of NSPanel are in the US. We in Australia use the portrait style, but use metric scale and date in DD/MM/YYYY format.

**Comment by Loose-Moose77** [comment]
> Please bear in mind, not all the users of the portrait US version of NSPanel are in the US. We in Australia use the portrait style, but use metric scale and date in DD/MM/YYYY format.

Absolutely. If you just upload the portrait tft file to your nspanel all your units and dates will stay exactly the same. Changes of these need to be done in the blueprint, and if done correctly should be an option selected in the UI as opposed to how I've quickly thrown it together.

**Comment by markuserlacher** [comment]
Hi, a question: whats about a US Landscape Version?

**Comment by Blackymas** [comment]
> Hi, a question: whats about a US Landscape Version?

works with eu version tft

**Comment by garethcheyne** [comment]
This is great, US version from an orientation would suite AU/NZ as generally our switches are in the orientation. I’m sure many other Asian countries have this same orientation

**Comment by carpetrout** [comment]
grabbed the zip from @Loose-Moose77 updated the nspanel_blueprint.yaml with the one provided and then uploaded the nspanel.tft however now my nspanels are all complaining about checking data.. Did I miss a step?

**Comment by Blackymas** [comment]
> This is great, US version from an orientation would suite AU/NZ as generally our switches are in the orientation. I’m sure many other Asian countries have this same orientation

already working on the US version and almost all pages are ready and will come with release 3.1.0

**Comment by Blackymas** [comment]
@all

Thanks to the good work of @miniminne and @Loose-Moose77  - I have now over 3 days and many many hours the complete US version revised and everything adjusted.

The only thing missing is the "wave" on the home page, which I will add later.

The good thing is from version 3.1.0 there will be an official US version - I am curious about your opinion ;)

once again many thanks to @miniminne  and @Loose-Moose77 I hope that you continue to support the project in the future and together with me to maintain the US version.

**Comment by jonkatz1** [comment]
> @ALL
> 
> Thanks to the good work of @miniminne and @Loose-Moose77 - I have now over 3 days and many many hours the complete US version revised and everything adjusted.
> 
> The only thing missing is the "wave" on the home page, which I will add later.
> 
> The good thing is from version 3.1.0 there will be an official US version - I am curious about your opinion ;)
> 
> once again many thanks to @miniminne and @Loose-Moose77 I hope that you continue to support the project in the future and together with me to maintain the US version.

Yes!!!!!!! Thank you all!

**Comment by Blackymas** [comment]
> > @ALL
> > Thanks to the good work of @miniminne and @Loose-Moose77 - I have now over 3 days and many many hours the complete US version revised and everything adjusted.
> > The only thing missing is the "wave" on the home page, which I will add later.
> > The good thing is from version 3.1.0 there will be an official US version - I am curious about your opinion ;)
> > once again many thanks to @miniminne and @Loose-Moose77 I hope that you continue to support the project in the future and together with me to maintain the US version.
> 
> Yes!!!!!!! Thank you all!

feel free to thank me with a donation ;)

**Comment by jonkatz1** [comment]
> > > @ALL
> > > Thanks to the good work of @miniminne and @Loose-Moose77 - I have now over 3 days and many many hours the complete US version revised and everything adjusted.
> > > The only thing missing is the "wave" on the home page, which I will add later.
> > > The good thing is from version 3.1.0 there will be an official US version - I am curious about your opinion ;)
> > > once again many thanks to @miniminne and @Loose-Moose77 I hope that you continue to support the project in the future and together with me to maintain the US version.
> > 
> > 
> > Yes!!!!!!! Thank you all!
> 
> feel free to thank me with a donation ;)

Did you end up ordering the US version with my last?

**Comment by carpetrout** [comment]
> > > @ALL
> > > Thanks to the good work of @miniminne and @Loose-Moose77 - I have now over 3 days and many many hours the complete US version revised and everything adjusted.
> > > The only thing missing is the "wave" on the home page, which I will add later.
> > > The good thing is from version 3.1.0 there will be an official US version - I am curious about your opinion ;)
> > > once again many thanks to @miniminne and @Loose-Moose77 I hope that you continue to support the project in the future and together with me to maintain the US version.
> > 
> > 
> > Yes!!!!!!! Thank you all!
> 
> feel free to thank me with a donation ;)

Just donated!

**Comment by anuadu** [comment]
happy days for US-AU nspanel users

**Comment by miniminne** [comment]
For those watching this issue, here are some examples of the new layout after it's been cooked a bit more! I apologize if the photos aren't *perfect*, the simulator is a bit wacky so I had to improvise. 

The entities page does utilize line breaks for longer entity names, so yay!

Boot (minus IP address): 
![image](https://user-images.githubusercontent.com/8529568/216529126-143731c3-3114-4719-ab45-4f90f4783145.jpeg)

Home Screen:
![image](https://user-images.githubusercontent.com/8529568/216529396-ee180800-5899-498b-8310-2fe7c3b56cfd.jpeg)

Example Button Page:
![image](https://user-images.githubusercontent.com/8529568/216529409-08061190-04dd-4819-a523-22f78933e714.jpeg)

Light Settings Example:
![image](https://user-images.githubusercontent.com/8529568/216529609-2ba1dbe6-48e5-4411-bd65-063b3796384e.jpeg)

Cover settings: 
![image](https://user-images.githubusercontent.com/8529568/216529666-e1f166ef-b8b8-43e6-bf72-b08551379e33.jpeg)

Weather Example: 
![image](https://user-images.githubusercontent.com/8529568/216529740-02a755b6-88e9-4111-952f-4fa92099fdb5.jpeg)

Climate example:
![image](https://user-images.githubusercontent.com/8529568/216529762-9a5fc6ce-6b88-4e95-9fe4-04f937079a22.jpeg)

Entity page with line breaks:
![image](https://user-images.githubusercontent.com/8529568/216529831-fd4b17b7-018c-4ecf-a69e-b0aaa4e75cf5.jpeg)

Entity Page without line breaks:
![image](https://user-images.githubusercontent.com/8529568/216529872-7c3411de-9a41-424b-8801-d7fde42cb1b3.jpeg)

QR code!
![image](https://user-images.githubusercontent.com/8529568/216529901-fd287527-e565-4e4f-8ab6-71b8626fc35b.jpeg)

**Comment by Blackymas** [comment]
@all US version is now in version 3.1.0. :)

In the release notes of 3.1.0 you could see all below how the individual pages look like.

Thanks to all who helped and have fun with your US version.


Of course we would be happy about every donation :)

https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.1.0
