### ISSUE TITLE
Warning on ESPHome 2023.11.2

### ISSUE THREAD

**Issue by techunleadit** [Blackymas/NSPanel_HA_Blueprint#1302]
Hi,
during the update of today's release of ESPHome I noticed the following warning during the build of the update

`Installing collected packages: pyparsing, urllib3, tqdm, six, pyyaml, pycparser, packaging, msgpack, kconfiglib, idna, future, filelock, contextlib2, colorama, click, charset-normalizer, certifi, schema, requests, cffi, requests-toolbelt, requests-file, cryptography, cachecontrol, idf-component-manager
  DEPRECATION: future is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for future: started
  Running setup.py install for future: finished with status 'done'`

If you need, [here](https://pastebin.com/0m6Z29wc) all the log 

Thanks for your work

**Comment by edwardtfn** [comment]
Are you still having that with v4.1.3? If so, could you please share the yaml used for ESPHome? Please remove any sensitive information before sharing.

**Comment by edwardtfn** [comment]
This is a message from ESPHome and we don't have control of it.
