### ISSUE TITLE
Connection problem  no api in yaml

### ISSUE THREAD

**Issue by rolemerel** [Blackymas/NSPanel_HA_Blueprint#1306]
I did everyting at the rules  upload ok    esp home discovers device    when i say config device  conection fails with message no api in yaml  Help please

**Comment by edwardtfn** [comment]
1st: What can you see in your panels screen?
2nd: Could you please share some logs from ESPHome?
3rd: Can you see any error message related to this on the Home Assistant logs (Settings > System > Logs)?
4th: Could you please share your ESPHome yaml?

Please remove any sensitive info before sharing.

**Comment by rolemerel** [comment]
1 original nspanel startup screen


3
Template variable error: No first item, sequence was empty. when rendering '{% if nspanel_entities | count > 0 %}{{ (nspanel_entities | selectattr(None, "search", "_nextion_display") | list | first).split(".")[1].split("_nextion_display")[0] }} {% elif nspanel_deviceid is string %}{{ nspanel_deviceid | replace("-","_") | replace(" ","_") | replace("___","_") | replace("__","_") }} {% endif %}'
4
substitutions:
  ###### CHANGE ME START ######
  device_name: "nspanel1"
  wifi_ssid: H369C1A278
  wifi_password: C5697A49Cxxx

  nextion_update_url: "http://192.168.2.3:8123/local/nspanel_eu.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####
##### My customization - End #####

**Comment by edwardtfn** [comment]
Thanks 
Could you please open ESPHome logs, then in Home Assistant go to Settings > Devices and Services > ESPHome > Your panel page and press "Upload TFT"?
Please share the ESPHome logs here.

**Comment by edwardtfn** [comment]
Ok, just realized you have an issue while building the firmware, so you probable don't have the ESPHome logs...
5. And as you see the original Sonoff screens, I believe you are installing this for the first time, is that right?
6. Based on your message, I understood you could flash the device, but not add as an integration on Home Assistant, is that right?
7. Can you see your panel on the ESPHome dashboard?
8. The API component is there, so please try restarting your Home Assistant host if you haven't tried that yet.

**Comment by edwardtfn** [comment]
Hey @rolemerel, are you still fighting this issue or should we close it?

**Comment by rolemerel** [comment]
Yes , you can close it    there where remains from lovelace installation in my HA who caused trouble.

Thanks for you help.    

Verzonden vanuit Mail voor Windows

Van: Edward Firmo
Verzonden: donderdag 23 november 2023 19:21
Aan: Blackymas/NSPanel_HA_Blueprint
CC: rolemerel; Mention
Onderwerp: Re: [Blackymas/NSPanel_HA_Blueprint] Connection problem no api inyaml (Issue #1306)

Hey @rolemerel, are you still fighting this issue or should we close it?

**Comment by martinkoe09** [comment]
Hi rolemerel,

even if this thread is closed I would ask for somme assistance.
I have the same error.
Errno 104 in runner.py
The nspanel shows up in the esphome webfrontend but it does not hook to Home Assistant.
It complains about a missing api key in the yaml.
I already deinstalled NSPanel Lovalace UI Backend from HACS, but still the same.

Would you be so kind and give me a hint where to look at or what you did exactly?
Thank you
Martin
