### ISSUE TITLE
Media player - No control only volume

### ISSUE THREAD

**Issue by Andy0G0** [Blackymas/NSPanel_HA_Blueprint#1316]
Hi firstly I love the blueprint and integration I'm having a lot of fun getting my panel configured!

I have found an issue with media player which is a sonos device.  
When tapping on the media button I am taken to the media page as expected and can see the track details however I am unable to play / pause or skip track.
I am able to control the volume without issue.

Apologies if this is a simple setting issue, but I think I have everything setup correct!?

**Comment by edwardtfn** [comment]
Could you please go to Developer Tools, tab States, look for your media player entity and let me know the value for the attribute `supported_features`?

**Comment by Andy0G0** [comment]
> se go to Developer Tools, tab St
Thanks for the reply.  
please see the following and let me know if you need anything further: supported_features: 4127295

**Comment by edwardtfn** [comment]
Wow, your Media Player integration supports almost all features available!

`supported_features: 4127295`, means:

```
 => PAUSE = 1
 => SEEK = 2
 => VOLUME_SET = 4
 => VOLUME_MUTE = 8
 => PREVIOUS_TRACK = 16
 => NEXT_TRACK = 32

    TURN_ON = 128
    TURN_OFF = 256
 => PLAY_MEDIA = 512
    VOLUME_STEP = 1024
 => SELECT_SOURCE = 2048
 => STOP = 4096
 => CLEAR_PLAYLIST = 8192
 => PLAY = 16384
 => SHUFFLE_SET = 32768
    SELECT_SOUND_MODE = 65536
 => BROWSE_MEDIA = 131072
 => REPEAT_SET = 262144
 => GROUPING = 524288
 => MEDIA_ANNOUNCE = 1048576
 => MEDIA_ENQUEUE = 2097152
```

So I don't see any clear reason for not be showing the controls.

Some additional questions from my side:

1. Do you see any error message related to this on Home Assistant logs (Settings > System > Logs)?
2. Which Media Player integration are you using for this entity?

**Comment by edwardtfn** [comment]
Hey @Andy0G0, 

I still waiting for some info from your side. 😉 

> Some additional questions from my side:
> 
> 1. Do you see any error message related to this on Home Assistant logs (Settings > System > Logs)?
> 2. Which Media Player integration are you using for this entity?

**Comment by edwardtfn** [comment]
Hey @Andy0G0, I will close this for now, as I don't have the info needed to progress. Please feel free to reopen when you have a chance and I will be happy to support.

**Comment by Lucer61** [comment]
Hi I have the same problem but with Volumio Mediaplayer 
in Homeassistant the source of the music can be selected, but in nspanel this is not possible, the button is not visible.
Can this be changed? i.e. select the music source from nspanel.
This is the code from homeassistant Status Volumio Keller Mediaplayer.

`volume_level: 0.48
is_volume_muted: false
media_content_type: music
media_duration: 132
media_title: Paradise (feat. Modi)
media_artist: Thierry Von Der Warth, Modi
media_album_name: Paradise (feat. Modi)
repeat: off
entity_picture: /api/media_player_proxy/media_player.volumio_keller?token=064aae48bfae6a4e4934f378c6aca33c16f86ac22f18e091671dfe116bdbd57f&cache=c31a4ae1f5ef3041
friendly_name: Volumio_Keller
supported_features: 458303`

![media homeassistant](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/46453406/a0a52733-8859-4397-b325-8c23d53564bf)
![nspanel](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/46453406/3e7e023c-a603-4de1-9e39-19a9a13a1cc1)
![source](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/46453406/d6e8a2dc-74b9-4d7f-ba65-49b2d4ea549f)

**Comment by edwardtfn** [comment]
Hey @Lucer61 , you have described a different issue.

The original post is about controls that have been implemented, like play, stop, next, etc., while you are saying about things that have never been implemented.
Could you please add those in another issue as an enhancement request?
