### ISSUE TITLE
Icons not changing color when on

### ISSUE THREAD

**Issue by iscraigh** [Blackymas/NSPanel_HA_Blueprint#1317]
My icons do not change colour when I turn a light on. Interestingly the motion sensor changes colour on motion detect.

US portrait TFT
Blueprint version 4.1

This is a fresh install 1 week ago
Not sure what other info you need it seems I am alone in this issue.

I pick a custom colour for the entity (light) turn the button on and the button changes to white but the icon does not change to my colour (yellow in my case)

**Comment by Armandogl12** [comment]
Got the exact same issue, was working fine on 4.0 version, issue appears on 4.1 version update.

**Comment by iscraigh** [comment]
Well I am not alone anyway.
A relatively minor issue.

**Comment by edwardtfn** [comment]
I believe this is fixed on `dev` and hopefully will be included in the coming release.
