### ISSUE TITLE
ESPHome Update Breaking Change- Update of ESPHome Killed Display 

### ISSUE THREAD

**Issue by MKme** [Blackymas/NSPanel_HA_Blueprint#1319]
After update of ESPHome on my devices yesterday I have no display on my panel apart from one icon on the mail page.  HA recognizes some problems:

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/13653062/7d4937f3-f3e5-464f-8bc2-ce8c683abc43)

Going in to the device page to enable the "current page" it shows enabled fine:

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/13653062/4df98777-0cdb-47f5-a346-8c43b147c477)

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/13653062/df8725c7-f72f-4f23-8aeb-bf1d7eaf5286)

Another ESPHome update was available this morning which I ran then ran the sutomation again with no change :(

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/13653062/a062ccef-79b5-4618-a600-2abf4b175241)

I figured there would be a flood of people by now but maybe it is somehow just my config?  I dont get it.  

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/13653062/bd666849-8442-463a-a2bf-9d0f0c8fab0f)

I didnt know the panel had voltage measurement either.  Was concerned it was getting crossed with my power monitors but I dont think so.  Im open to ideas.

**Comment by MKme** [comment]
For future Me's:

This can be fixed by updating the Blueprint:

https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#2-update-blueprint

It is a manual process currently but updating the blueprint does not impact your automations (I have one for each panel so it keeps the settings)

Since I'm using the US TFT version I had to manually download the file from git and place here:

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/13653062/b68e1f10-7996-4703-881c-57febd7e0f7e)


so TDLR:
update blueprint by copying file
Run validate in ESPhome once updated (probably already are if you came here)
Manually copy TFT file
Run update tft
Profit

This can be closed.  Thanks devs :)

**Comment by edwardtfn** [comment]
Thanks for sharing this.
