### ISSUE TITLE
Flash eventuell nicht drauf? / Probleme bei der Verbindung zum Display / Nextion queue is empty! / No response from Nextion display

### ISSUE THREAD

**Issue by Karl148** [Blackymas/NSPanel_HA_Blueprint#1320]
Wir haben ein nagelneues Sonof NSpanel eingerichtet und haben es mit dem Blackymas geflasht. Leider gibt es hierbei ein paar Probleme. Anbei einmal meine Konfiguration der .yaml-Datei und auch das Protokoll. Vielleicht kann jemand etwas damit anfangen :(? In den Foren bin ich bisher leider nicht auf eine Lösung gestoßen.
![1](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/127422876/c300934a-6059-4ccc-b933-8f3236c20cd9)
![2](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/127422876/1d568ed4-5463-49c1-a6a1-1d4f8d3b49e1)
![3](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/127422876/979ebb7e-ceab-4d5f-b9ba-6ad76337b7d1)
![4](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/127422876/d11b6889-8a94-4806-b8d0-e7d40dcacb42)
![panelkeller yaml](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/127422876/19c58f7f-8be5-4609-9a11-f1f16d811d74)

**Comment by edwardtfn** [comment]
Those messages from Nextion are probably related to the TFT file not being loaded to your device, so you probably see some error message or the original screens from Sonoff on your display.
Please go to Settings > Devices and Services > ESPHOME, your device's page, then click "Upload TFT".
If that fails, please send again the ESPHome logs from the moment you press that button.

**Comment by Karl148** [comment]
Vielen dank für die schnelle Hilfe.
Es scheint, als sei mein Ablagepfad der lokalen nspanel_eu.tft Datei nicht der korrekte.
![11t](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/127422876/310f034c-7e31-42e4-8084-a26e885feea3)
![12t](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/127422876/92a77023-17cd-4e17-9316-5fd063840ec5)


In den Anleitungen / Foren schreiben alle immer von diesem Pfad "config/www/nspanel_eu.tft"

Wie im Bild aber zu sehen ist, habe ich gar keinen Config/www Pfad bei mir im ESPHome FileEditor.
Hilft es hier, diesen Pfad anzulegen und diese TFT Datei dort abzulegen? 
Oder wie kann ich herausfinden, welche bei dir der richtige Pfad ist?

**Comment by edwardtfn** [comment]
The file `nspanel_eu.tft` should be under `homeassistant\www` and not under `homeassistsnt\esphome` as I see in your picture. The other files looks fine.

About the building error, it looks like an indentation issue with `nextion_update_url`. Could you please share the content of `panelKeller.yaml`? Please hide any sensitive info.

**Comment by Karl148** [comment]
Ich hatte es doch noch mal mit einer anderen Konfiguration der .yaml Datei probiert. Damit hatte es dann auch anschließend mit dem hochladen der TFT datei funktioniert. vielen dank noch einmal für die schnelle Rückmeldung und auch Hilfe. Aktuell funktioniert somit alles :)!
![13t](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/127422876/b63a4e3c-9847-424a-8223-8bbfdb4cf6d8)

**Comment by Karl148** [comment]
Ich schließe es aktuell somit einmal :)! Bei Problemen würde ich mich direkt wieder melden, da man echt schnelle Hilfe bekommt!
