### ISSUE TITLE
Display Settings

### ISSUE THREAD

**Issue by Duese911** [Blackymas/NSPanel_HA_Blueprint#1322]
how do i get to the display settings, the button for the menu is not visible. The display always goes into standby and the presence sensors dosn't seem to work.

**Comment by edwardtfn** [comment]
> how do i get to the display settings

It depend to which settings you are talking about. Most of the settings of what would be displayed (the content) are on the automation you created using the blueprint, while the panel's settings (sleep time, etc.) are on the device's page under Settings > Devices and Services > ESPHome.

> the button for the menu is not visible

Which button are you talking about?

> The display always goes into standby and the presence sensors dosn't seem to work

In fact, there's no presence sensor embedded into the panel. You can use an external presence sensor to trigger an automation in your Home Assistant to wake-up your display, but this is all external to the display itself.

**Comment by Duese911** [comment]
> > how do i get to the display settings
> 
> It depend to which settings you are talking about. Most of the settings of what would be displayed (the content) are on the automation you created using the blueprint, while the panel's settings (sleep time, etc.) are on the device's page under Settings > Devices and Services > ESPHome.
> 
> > the button for the menu is not visible
> 
> Which button are you talking about?
> 
> > The display always goes into standby and the presence sensors dosn't seem to work
> 
> In fact, there's no presence sensor embedded into the panel. You can use an external presence sensor to trigger an automation in your Home Assistant to wake-up your display, but this is all external to the display itself.

![Screenshot_20231122-225224](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/66550258/b39475e7-d8e8-4c91-809c-878f950534e8)

https://youtu.be/b7vW4YtUaTs?si=1wJK4jBaJwxd962Z

es geht um die Einstellungen at thr Display. im Video an minute 1,50

**Comment by Duese911** [comment]
![PXL_20231123_061347984](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/66550258/cb736728-8033-44cf-a2f3-8823dc4bf0c3)

There is no option to set sleep, i don't want the display to turn off completely

**Comment by edwardtfn** [comment]
This screen changed with v4.0 and unfortunately the instructions aren't updated yet (we are working at this).

With the latest versions, tô disable Sleep mode, go to the device's page under Settings > Devices and Services > ESPHome and change Timeout Sleep to 0.
