### ISSUE TITLE
Adapt nspanel_esphome_core.yaml to be able to use hidden wifi network and fixed ip addresses

### ISSUE THREAD

**Issue by user34756361233** [Blackymas/NSPanel_HA_Blueprint#1325]
I would like  to use my NSPanels within my homeautomation wifi network that is hidden and uses fixed ip addresses, however this means that nspanel_esphome_core.yaml has to be adapted:

- to be able to use a hidden wifi network the wifi setup should contain "fast_connect: true". Is it possible to add this in a future version as a substitution?
- to be able to use a fixed ip address the wifi setup shoud contain  "use_address:  www.xxx.yyy.zzz". Is it possible to add this in a future version as a substitution?

Kind regards, Han

**Comment by edwardtfn** [comment]
You can use customizations for both: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#manual-ip

Please let me know if you need additional support to set this.

**Comment by user34756361233** [comment]
Reading goes a long way ;-), thanks for pointing it out. I will be able to handle this!

KR Han
