### ISSUE TITLE
TFT upload doesn't work

### ISSUE THREAD

**Issue by Sissi91** [Blackymas/NSPanel_HA_Blueprint#1337]
I tried to put what you recommend on issue #1326 but no succesful for me.
So my Esp config file is:
`substitutions:
  ###### CHANGE ME START ######
  device_name: "esphomepanel" 
  wifi_ssid: "xxx"
  wifi_password: "xxx"

  nextion_update_url: "https://homeassistant.local:8123/local/nspanel_eu.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
[logs_esphome_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13463800/logs_esphome_run.txt)

    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####
esp32:
  framework:
    type: esp-idf

external_components:
  - source: github://pr#5825
    components: [nextion]
    refresh: 1s

time:
  - id: !extend time_provider
    on_time:
      - seconds: /3
        then:
          - lambda: |-
              ESP_LOGD("DEBUG", "disp1->is_detected(): %s", disp1->is_detected() ? "True" : "False");
              ESP_LOGD("DEBUG", "disp1->is_setup(): %s", disp1->is_setup() ? "True" : "False");
##### My customization - End #####`
the panel is connected and I can turn on/off the relays for example as you can see in the log too. But the update always fail after around 20%. The only tft update I'm able to do is the blank one. I tried now for so long but can't get it work. any ideas? Attached you find the log when I tried to update the tft.
[logs_esphome_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13463806/logs_esphome_run.txt)

**Comment by edwardtfn** [comment]
Please try changing the upload url from HTTPS to HTTP, as the httpS is known to be problematic with ESP and Nextion upload.

`  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"`

**Comment by Sissi91** [comment]
this solved the problem! thank you
