### ISSUE TITLE
Feature request: Enable lock entities

### ISSUE THREAD

**Issue by Ra72xx** [Blackymas/NSPanel_HA_Blueprint#1341]
As stated in the subject: Corrently, lock entities are not supported anywhere in the blueprint. Enabling them would offer the possibility to monitor door status or operate the door opener from the panel.

**Comment by Ladida1** [comment]
This would be a nice feature!

**Comment by edwardtfn** [comment]
I've implemented this in `dev`, however I cannot test it.
If someone can test it and everything goes well this should be part of v4.3 to be released very soon.
I will close this for now, to make easier managing the backlog, but please feel free to add comments here or reopen-it if it isn't solved.
