### ISSUE TITLE
Home screen icons not updated

### ISSUE THREAD

**Issue by Mars2020-Github** [Blackymas/NSPanel_HA_Blueprint#1343]
Since last update the status of several icons are not updated automatically.
I have added Spotify to Custom button 1 on my "_Homepage Custom Buttons_" and the icon is set as the Spotify icon.
If Spotify is active on my Phone or other device, the icon on the homescreen is not updated (no color change). After selecting the button, it is updated.

I have seen a similar issue with the weather icon (clouds/rain etc) are not (always) updated…… To update I need to select the weather button and return to the homescreen.
Currently installed version:

TFT: 4.1
ESPHome: 4.1
Bluepring: 4.1

**Comment by edwardtfn** [comment]
Looks quite important.
I will take a look as soon as possible.

**Comment by bkbartk** [comment]
I found the same issue for custom button "Light" on the homepage.
I did some checks and the issue only occurs for lights without RGB, RGB lights are fine?
To find the correct status you have to navigate away from home page and back.

next to that, I have the feeling, but I can't proof this neither am I sure of this. but that "nextion.color.on" has changed form yellow to some kind of "white", which makes the distinction from on/off harder to see.
maybe this is a design choice, but I think the distinction between on and off is hard to see now.

**Comment by edwardtfn** [comment]
> next to that, I have the feeling, but I can't proof this neither am I sure of this. but that "nextion.color.on" has changed form yellow to some kind of "white", which makes the distinction from on/off harder to see.
maybe this is a design choice, but I think the distinction between on and off is hard to see now.

I haven't changed this intentionality, but I can double check later.

> edit: it could be that my non rgb light is a switch. Meaning my conclusion is not for lights but for switches.
I can check tomorrow.

There were a filter to run the update onky for lights. I've removed that on v4.1.2 (DEV). I will double check if there is filter for RGB.

**Comment by bkbartk** [comment]
> I will double check if there is filter for RGB

there is probably no need for this check, RGB lights are ok, swichtches are not.
some on/off lights I have configured as switched and the confusion about this was on my side.

**Comment by edwardtfn** [comment]
I've tested this on v4.1.3 (still to be released) and everything is working fine for custom buttons (lights, switches, media player, etc), chips, values, time & date, etc.
I will close this for now, but please come back if you find something not working properly after v4.1.3 is released.

**Comment by Mars2020-Github** [comment]
I tested the Spotify icon and it seems to be ok now.
