### ISSUE TITLE
Climate page doesn't react directly to touch

### ISSUE THREAD

**Issue by X-Ryl669** [Blackymas/NSPanel_HA_Blueprint#1351]
It used to work on 3.4 but this doesn't anymore on 4.1.1

When selecting a climate page, and pressing/touching/clicking the "power off" or "heat" icon, I can hear that the HVAC is acknowledging the change but the page doesn't react. If I close the page and reopen, it's changed, so it's really the feedback from button press that's now missing or failing.

**Comment by X-Ryl669** [comment]
It also doesn't work in 4.1.2.

**Comment by edwardtfn** [comment]
Are you using embedded climate control (add-on) or are you controlling some climate entity from your Home Assistant?

**Comment by X-Ryl669** [comment]
I'm using the climate entity from HA. It's in the button section of the Automation. On the first (right) page, I have a button for this entity and when I click it, a climate page open where I can select the mode or change the temperature. Changing the temperature is reactive, but changing the mode isn't (it used to work before). If I press the "Power off" button, I can hear the remote IR's beep from the AC unit, but the display doesn't account for it. If I click on the top right to close the page, I'm back to the button page, and the button is update here. If I click again the button, the climate page opens again, and the icon's state is now valid. 

It's just that it hasn't refreshed upon touch.

**Comment by edwardtfn** [comment]
It is released. Could you please try it with v4.1.3 and let me know if that was solved?
