### ISSUE TITLE
Indoor Humidity Sensor

### ISSUE THREAD

**Issue by dylanpedro** [Blackymas/NSPanel_HA_Blueprint#1352]
I cant see an option to set the entity for the indoor humidity sensor. Was this option removed?

**Comment by edwardtfn** [comment]
It was replaced by 3 sensors which can be used by most type of values, including humidity. 😉

**Comment by andreas-bulling** [comment]
Is this documented somewhere? That is, how to set these sensors to show humidity on the home page as in the screenshots?
