### ISSUE TITLE
Ns panel pro W/O buttons 

### ISSUE THREAD

**Issue by dadalouis** [Blackymas/NSPanel_HA_Blueprint#1364]
Is This also available for de pro version ? 

Or can I follow this for de pro ?

**Comment by edwardtfn** [comment]
No, the Pro uses totally different components and environment, so it's not compatible, unfortunately.

**Comment by dadalouis** [comment]
Oh that’s sad ,

So I need to return it and buy the another one😄

Op wo 29 nov 2023 om 22:49 schreef Edward Firmo ***@***.***>
