### ISSUE TITLE
Inverted Chips status

### ISSUE THREAD

**Issue by rtm-soft** [Blackymas/NSPanel_HA_Blueprint#1365]
Hi all, 

 I seem to have no issues using this software. Very pleased with how it looks and works! Great job everyone!!

I do have a features request. When my door is closed the chip will show up. I would like to have this reversed, so door open chip displays door. So that I can see at the top of my screen which door or window is open. 

Thanks and keep up the great job

**Comment by edwardtfn** [comment]
Implemented on `dev`. It should be included in the next release.

**Comment by edwardtfn** [comment]
- #1556
