### ISSUE TITLE
Manual line break

### ISSUE THREAD

**Issue by denes44** [Blackymas/NSPanel_HA_Blueprint#1367]
Hi,

I see that the multiline support for the buttonpages was introduced, with an automatic line break function, which is great, but sometimes it's not yields the best results, because it is using a fixed line width of 10.
If you use lowercase characters, you can fit more than 10 characters in a row.

For example `Living Room 12345678` will break to three rows, with the bottom row clipped:
```
Living
Room
12345678
```

Howerver `Living Room` even though it's 11 characters has no problem fitting to one row, so it would look like this:
```
Living Room
12345678
```

Because the width of lower case characters is depends on the character itself, it's not reasonable (although possible) to make a function that will work every time.

I think it would be a good enough solution if the user can override this behavior with manually specifying a line break character. So when there is a `\r` in the button label, the wrap text function will do nothing with the text.

**Comment by edwardtfn** [comment]
I saw your comments on the commit... Good point.
I will take a look on how you implemented before with #740 to make sure we are not missing something.
I wanna do something quick to be included on tomorrow's patch, so maybe I will leave as it is and add an additional request for v4.2.

**Comment by edwardtfn** [comment]
v4.1.4 was just released.
Please update your system and try it again.
If the issue persists, please reopen it.
And thanks again for your help here. 😉
