### ISSUE TITLE
Missing api key in the yaml

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1371]
Hi rolemerel,

even if this thread is closed I would ask for somme assistance.
I have the same error.
Errno 104 in runner.py
The nspanel shows up in the esphome webfrontend but it does not hook to Home Assistant.
It complains about a missing api key in the yaml.
I already deinstalled NSPanel Lovalace UI Backend from HACS, but still the same.

Would you be so kind and give me a hint where to look at or what you did exactly?
Thank you
Martin

_Originally posted by @martinkoe09 in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1306#issuecomment-1837450908_

**Comment by edwardtfn** [comment]
Hey @martinkoe09, where do you see this `Errno 104 in runner.py` message?

You probably tried to restart Home Assistant already, right?

**Comment by martinkoe09** [comment]
Yes,

even the host.

**Comment by edwardtfn** [comment]
I'm looking in their repository and I think they don't use an API key also, so this was probably something you have set from your side on the original installation.

**Comment by martinkoe09** [comment]
Yes, of course
`INFO ESPHome 2023.11.6
INFO Reading configuration /config/esphome/nspanfluri.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Detected timezone 'Europe/Berlin'
INFO Starting log output from nspanfluri.local using esphome API
INFO Successfully connected to nspanfluri in 0.268s
WARNING nspanfluri: Connection error occurred: [Errno 104] Connection reset by peer
INFO Processing unexpected disconnect from ESPHome API for nspanfluri
WARNING Disconnected from API
WARNING Can't connect to ESPHome API for nspanfluri: Read failed (ReadFailedAPIError)
INFO Trying to connect to nspanfluri in the background
INFO Successfully connected to nspanfluri in 0.006s
WARNING nspanfluri: Connection error occurred: [Errno 104] Connection reset by peer
INFO Processing unexpected disconnect from ESPHome API for nspanfluri
WARNING Disconnected from API
INFO Successfully connected to nspanfluri in 0.007s
WARNING nspanfluri: Connection error occurred: [Errno 104] Connection reset by peer
INFO Processing unexpected disconnect from ESPHome API for nspanfluri`

**Comment by edwardtfn** [comment]
@rolemerel, you reported a similar thing on #1306...
Do you have any idea that could help here?

**Comment by martinkoe09** [comment]
Hi Edward,

the device was fresh from the factory.

What could be the case is that rolemerel did have something old and nasyt someweher in the HA configs.

I am looking already threrfore I removed th NSPanle Lovelace Backend so far but without any change.

But it is not necessary to include an api key in the conf from Blackymas?

The "Set up new devices" dialog always generates  it.
I do not have a standalone ESPhome instance running, just installed the addon.
As I said in the ESPhome Web Frontend the device is online,

**Comment by edwardtfn** [comment]
> But it is not necessary to include an api key in the conf from Blackymas?

No, the api key is optional.

You can try to add an api key as a customization. Please take a look at this: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#api-encryption

**Comment by martinkoe09** [comment]
Solved.

I changed to main network.
After that I created a VLAN on end0 (named end1) and include it in the Networking Options.

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/118029269/ecd0b2f3-41b9-4342-89ed-fdab20c19d8c)

Everything works fine on VLAN Net (end1).
Thank you
