### ISSUE TITLE
Upload TFT fails with arduino framework

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1383]
Just did my last panel which was arduino, and had to install esd-idf in order to do TFT upload.
Even after reboot and re-install of arduino to make sure, it will not upload TFT. Strange since another panel can do... maybe is some hardware timing variation between.
I will upgrade them all the esp-idf anyways eventually.

_Originally posted by @Doughboy68 in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1255#discussioncomment-7758530_

**Comment by edwardtfn** [comment]
@Doughboy68, which version have you used?

**Comment by edwardtfn** [comment]
v4.1.4 was just released.
Please update your system and try it again.
If the issue persists, please reopen it.

**Comment by BluThunder2k** [comment]
ESP-IDF resolved my tft uploading issue on all 4 of my displays.   Could not even with 4.1.4 get Adruino to take the update.

**Comment by edwardtfn** [comment]
Do you have the logs of any of your tries with Arduino? I would love to take a look at those.

**Comment by BluThunder2k** [comment]
I didn't keep them...    I think I have one more switch (a spare) I can try - see if it also behaves the same....

**Comment by Doughboy68** [comment]
Arduino still not updating TFT.. I have to temporarily install esp-idf and then it works.
After updating to 4.1.4 I tried again with Aurduino and still not working.

**Comment by edwardtfn** [comment]
Quick question, are you using advanced package or any of the add-ons?

**Comment by edwardtfn** [comment]
I believe this is fixed in `dev`. Please let me know if you wanna give it a try.
