### ISSUE TITLE
Page to display a custom image

### ISSUE THREAD

**Issue by Rainerlan** [Blackymas/NSPanel_HA_Blueprint#139]
Would it be possible to add a page where just a custom image is being displayed?
I would love to have an QR code (containing the wifi credentials) for guests to login to my guest wifi.

In the meantime I have created my own nspanel.tft (including a "5th buttonpage" containing just a wifi-QRcode as picture) and uploaded it - works like a charm.

**Comment by Blackymas** [comment]
hi -at the moment it is only possible the way you have done it.

If there are more users, I can put it on the roadmap.

but you can share your project
