### ISSUE TITLE
Help.  nspanel_esphome_core.yaml:747

### ISSUE THREAD

**Issue by steini72** [Blackymas/NSPanel_HA_Blueprint#1390]
display.nextion: [source /config/.esphome/packages/6fb3375d/nspanel_esphome_core.yaml:747]
  id: disp1
  platform: nextion
  uart_id: tf_uart
  
  [start_up_page] is an invalid option for [display.nextion]. Did you mean [wake_up_page]?
  start_up_page: 8
  on_page: 
    lambda: |-
      static const char *const TAG = "display.disp1.on_page";
      ESP_LOGD(TAG, "Nextion page changed");
      ESP_LOGD(TAG, "New page: %s (%i)" , id(page_names)[x].c_str(), x);
  on_setup: 
    - script.execute: boot_sequence

**Comment by geni0602** [comment]
I´ve just got the same, trying to update.

**Comment by geni0602** [comment]
just updated my esphome cli to 2023.11.6 and now is compiling just fine

**Comment by edwardtfn** [comment]
Yeah, that was due to an older ESPHome version.

**Comment by steini72** [comment]
esphome cli to 2023.11.6 and now is compiling just fine
