### ISSUE TITLE
TFT Update fails

### ISSUE THREAD

**Issue by misery** [Blackymas/NSPanel_HA_Blueprint#1391]
Hi, I tried to update from 4.1.1 t o 4.1.4 but both panels fails.
Updates from 4.1.0 to 4.1.1 had no problems.

[logs_nspanelwz_logs.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13592142/logs_nspanelwz_logs.txt)
[logs_nspanelflur_logs.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13592135/logs_nspanelflur_logs.txt)

**Comment by edwardtfn** [comment]
These uploads issues never ends... 😩
I cannot read your logs right now, as I'm with my phone, but could you please try changing the framework and then try the upload again? (With logs again, please, even if successful, so I can compare the different results)

https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload#consider-changing-the-framework

Please come back to the original framework after your tests.

**Comment by misery** [comment]
Ok, I removed uart from config and it works after several retries.

```
uart:
  - id: !extend tf_uart
    baud_rate: 921600
```

[logs_nspanelwz_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13592455/logs_nspanelwz_run.txt)
