### ISSUE TITLE
hvac modes on extra climate screens don't update immediately

### ISSUE THREAD

**Issue by hapklaar** [Blackymas/NSPanel_HA_Blueprint#1394]
I have some extra climate screens configured via the HOME PAGE - CUSTOM BUTTONS section. When I change the temperature, or change the hvac mode, this is not immediately reflected in the hvac mode shown. Only when I leave the page and return I see the updated hvac mode active.

On my dashboard I can see the mode is immediately changed correctly, but it seems this doesn't auto refresh on the nspanel for these climate screens.

**Comment by edwardtfn** [comment]
1. Can you see the same delay to update the icon in the home page as to update the info in the detailed climate page?
2. When you say "don't update immediately", what is your expectation (in seconds) and how long it is taking now (in seconds)?
3. Can you see any error message under Home Assistant logs (Settings > System > Logs)?

**Comment by hapklaar** [comment]
> 1. Can you see the same delay to update the icon in the home/buttons pages as to update the info in the detailed climate page?

I assume you mean the main detailed climate page (accessed from tapping the temperature on the main screen)? There the update happens in about 1-2 seconds.
> 2. When you say "don't update immediately", what is your expectation (in seconds) and how long it is taking now (in seconds)?

I expect it to update the same as in the main climate page, which is in about 2 seconds. Now it's not updating at all and eventually returns to the home page. Only when I enter the climate page again via the button I see the updated status.
> 3. Can you see any error message under Home Assistant logs (Settings > System > Logs)?

I see no errors in the logs when this happens

**Comment by edwardtfn** [comment]
On the blue boot screen, which versions are shown for TFT, ESPHome and Blueprint?

**Comment by hapklaar** [comment]
Was at 4.1, 4.1.2 and 4.1. Now all at 4.1.4, but no change.

**Comment by edwardtfn** [comment]
> Would a vid showing the issue help?

Yeah, that may help me understanding your steps, so I can try to duplicate here.
