### ISSUE TITLE
Weather forecast pages empty except for todays weather

### ISSUE THREAD

**Issue by Rainerlan** [Blackymas/NSPanel_HA_Blueprint#140]
What could be the reason the weather forecast only contains the weather from today? (Other pages are displayed empty)
I tried both settings for the WeatherIntegration: accuweather and default. Same result.

**Comment by naofireblade** [comment]
Rename your weather entity_id in home assistant to „weather.home“ and set the weather to default in the blueprint.

**Comment by Rainerlan** [comment]
@naofireblade: Thanks a lot! Now it works.

**Comment by MarkuZP** [comment]
Thanks a lot! its working!

**Comment by MarkuZP** [comment]
But Accuweather is stilt not working even if its named "weather.home".

**Comment by Blackymas** [comment]
Fixed 
see here: https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.0.0
