### ISSUE TITLE
HOME PAGE - CHIPS More flexabilty 

### ISSUE THREAD

**Issue by McMtech** [Blackymas/NSPanel_HA_Blueprint#1403]
Would be great to have Rooms added to Chips to see if you may have any room lights still on or devices in that room maybe still on.

**Comment by edwardtfn** [comment]
But you can create groups and assign the groups to chips, no?

**Comment by McMtech** [comment]
No you can't only lights/ binary_sensors / Sensors and switches.

**Comment by edwardtfn** [comment]
We can add as a feature request to support the old groups, but you can crate group lights, group switches, etc., and those would be transparent to the Blueprint.

**Comment by McMtech** [comment]
Thank you.
