### ISSUE TITLE
error when i add file climate_cool?

### ISSUE THREAD

**Issue by dkhoa0160** [Blackymas/NSPanel_HA_Blueprint#1407]
when i add file: climate_cool
  ###### CHANGE ME START ######
  device_name: "nspanel" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.31.8:8123/local/nspanel_us.tft"
  nextion_blank_url: "http://192.168.31.8:8123/local/nspanel_blank.tft"

    
  ##### addon-configuration #####
  ## addon_climate ##
  temp_min: "16" #Min supported temperature is 40°F
  temp_max: "32" #Max supported temperature is 80°F
  temp_step: "1" #Temperature granularity is 1°F
    
  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

esp32:
  framework:
    type: esp-idf

=> error:

/data/build/nspanel/src/esphome/components/script/script.h:167: undefined reference to `esphome::thermostat::ThermostatClimateTargetTempConfig::ThermostatClimateTargetTempConfig()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanel/src/main.o: in function `__static_initialization_and_destruction_0':
/data/build/nspanel/src/main.cpp:262: undefined reference to `esphome::thermostat::ThermostatClimateTargetTempConfig::ThermostatClimateTargetTempConfig()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanel/src/esphome/core/controller.o:(.literal._ZN7esphome10Controller16setup_controllerEb+0x38): undefined reference to `esphome::climate::Climate::add_on_state_callback(std::function<void (esphome::climate::Climate&)>&&)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanel/src/esphome/core/controller.o: in function `esphome::Controller::setup_controller(bool)':
/data/build/nspanel/src/esphome/core/controller.cpp:53: undefined reference to `esphome::climate::Climate::add_on_state_callback(std::function<void (esphome::climate::Climate&)>&&)'
collect2: error: ld returned 1 exit status
*** [.pioenvs/nspanel/firmware.elf] Error 1

**Comment by edwardtfn** [comment]
I couldn't duplicate this issue.

Could you please clean the building files, try to compile again and let us know if the issue persists?

By the way, which version of ESPHome are you using?

**Comment by dkhoa0160** [comment]
Thank you for your feedback
I use esphome 2023.11.6
I will try it

**Comment by dkhoa0160** [comment]
thank you very much!
it solved my problem

**Comment by JS1Dev** [comment]
I just wanted to mention that @edwardtfn's solution to clean the building files resolved the compile problem for me too when I tried adding the new [Add‐on: Climate](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Add%E2%80%90on:-Climate) sample configs to my .yaml
