### ISSUE TITLE
Trying to Flash NSPanel

### ISSUE THREAD

**Issue by abbottcam** [Blackymas/NSPanel_HA_Blueprint#1412]
Hello Ive follow your instructions, they differ greatly from Mark Watt Tech's instructions.

Anyway....I get this message when I tried to install the flash....would you be able to help me???

Thanks

James
```log
INFO ESPHome 2023.11.6
INFO Reading configuration /config/esphome/nspanel.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Detected timezone 'Europe/London'
INFO Generating C++ source...
INFO Compiling app...
Processing nspanel (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40405.230623 (4.4.5) 
 - tool-cmake @ 3.16.9 
 - tool-ninja @ 1.10.2 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
AssertionError: Error: Missing Python executable file `/root/.platformio/penv/.espidf-4.4.5/bin/python`:
  File "/usr/local/lib/python3.11/dist-packages/platformio/builder/main.py", line 173:
    env.SConscript("$BUILD_SCRIPT")
  File "/data/cache/platformio/packages/tool-scons/scons-local-4.5.2/SCons/Script/SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/data/cache/platformio/packages/tool-scons/scons-local-4.5.2/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/data/cache/platformio/platforms/espressif32/builder/main.py", line 312:
    target_elf = env.BuildProgram()
  File "/data/cache/platformio/packages/tool-scons/scons-local-4.5.2/SCons/Util/envs.py", line 242:
    return self.method(*nargs, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/platformio/builder/tools/piobuild.py", line 61:
    env.ProcessProgramDeps()
  File "/data/cache/platformio/packages/tool-scons/scons-local-4.5.2/SCons/Util/envs.py", line 242:
    return self.method(*nargs, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/platformio/builder/tools/piobuild.py", line 121:
    env.BuildFrameworks(env.get("PIOFRAMEWORK"))
  File "/data/cache/platformio/packages/tool-scons/scons-local-4.5.2/SCons/Util/envs.py", line 242:
    return self.method(*nargs, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/platformio/builder/tools/piobuild.py", line 342:
    SConscript(env.GetFrameworkScript(name), exports="env")
  File "/data/cache/platformio/packages/tool-scons/scons-local-4.5.2/SCons/Script/SConscript.py", line 662:
    return method(*args, **kw)
  File "/data/cache/platformio/packages/tool-scons/scons-local-4.5.2/SCons/Script/SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/data/cache/platformio/packages/tool-scons/scons-local-4.5.2/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/data/cache/platformio/platforms/espressif32/builder/frameworks/espidf.py", line 1233:
    install_python_deps()
  File "/data/cache/platformio/platforms/espressif32/builder/frameworks/espidf.py", line 1109:
    python_exe_path = get_python_exe()
  File "/data/cache/platformio/platforms/espressif32/builder/frameworks/espidf.py", line 1221:
    assert os.path.isfile(python_exe_path), (
========================== [FAILED] Took 2.16 seconds ==========================
```

**Comment by edwardtfn** [comment]
Try to clean your building files (on the ESPHome dashboard, find your device and click the 3-dot menu, then select "Clean build files") and then install it again.

**Comment by abbottcam** [comment]
Thanks for your reply!I’ll try this tonight. Just double checking, so apologies, I’m still new to this…the basic process. I’ve plugged the NSPanel into my raspberry pi running home assistant via the serial adapter, flash it. Reassemble the Panel, plug it into the mains? Then it should appear on my home assistant, then I can upload the blueprint??Thanks JamesMobile: 07843448046Instagram: www.instagram.com/abbottcamIMDb: www.imdb.com/name/nm2555732/?ref_=rvi_nmOn 11 Dec 2023, at 22:36, Edward Firmo ***@***.***> wrote:﻿
Try to clean your building files (on the ESPHome dashboard, find your device and click the 3-dot menu, then select "Clean build files") and then install it again.

**Comment by edwardtfn** [comment]
> Thanks for your reply!I’ll try this tonight. Just double checking, so apologies, I’m still new to this…

No need for apologies. 🙂

> the basic process.
> 1. I’ve plugged the NSPanel into my raspberry pi running home assistant via the serial adapter, flash it.
> 2. Reassemble the Panel, plug it into the mains? Then it should appear on my home assistant,
> 3. then I can upload the blueprint??

In overall, this is the process.
For step 1, you don't need to connect to your Raspberry Pi, as you should be able to flash it using your computer (Windows, Linux or Mac), but anyways, that's correct.
About step 3, you can setup an automation using the Blueprint, but you won't be able to select a panel until step 2 is completed, so, it's right.

**Comment by abbottcam** [comment]
Thank you so much!I’ll try this tonight, so fingers crossed!Mobile: 07843448046Instagram: www.instagram.com/abbottcamIMDb: www.imdb.com/name/nm2555732/?ref_=rvi_nmOn 12 Dec 2023, at 07:18, Edward Firmo ***@***.***> wrote:﻿

Thanks for your reply!I’ll try this tonight. Just double checking, so apologies, I’m still new to this…

No need for apologies. 🙂

the basic process.

I’ve plugged the NSPanel into my raspberry pi running home assistant via the serial adapter, flash it.
Reassemble the Panel, plug it into the mains? Then it should appear on my home assistant,
then I can upload the blueprint??


In overall, this is the process.
For step 1, you don't need to connect to your Raspberry Pi, as you should be able to flash it using your computer (Windows, Linux or Mac), but anyways, that's correct.
About step 3, you can setup an automation using the Blueprint, but you won't be able to select a panel until step 2 is completed, so, it's right.

**Comment by abbottcam** [comment]
Hi Edward

It worked!!

Thanks so much for your help. To flash the panel I clicked ‘Manual download’ and then used the ESPHome Web to flash it.

Thanks again

James

Mobile: 07843448046
Instagram: www.instagram.com/abbottcam
IMDb: www.imdb.com/name/nm2555732/?ref_=rvi_nm
