### ISSUE TITLE
TFT Upload failed

### ISSUE THREAD

**Issue by as-apps** [Blackymas/NSPanel_HA_Blueprint#1414]
Hi all, 

i have been going through the issues and don't see anything similar to what i am experiencing.

I have followed the step by step guide to precisely and unfortunately am unable to upload the tft file.

I am getting the black screen on the nspanel showing "system data error".

Any help or steps to resolve this would be greatly appreciated. 

just to note, the device is showing online and the sensor data is showing under devices (esphome) in homeassistant.

i have added my logs to help troubleshoot this issue. The tft file i am trying to use is nspanel_eu.tft and it is placed in my local directory in homeassistant. the file downloads in browser using the url.

Thanks in advance for any help.

[
[logs_nspanel_logs (1).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13654069/logs_nspanel_logs.1.txt)
](url)

**Comment by edwardtfn** [comment]
> I am getting the black screen on the nspanel showing "system data error".

This looks more critical than it really is. You will have this when a TFT upload isn't successful, so any successful upload will get rid of that.

Is this the first time you are installing this projects files in this specific panel or are you upgrading from a previous version?
If this is a new one, it was using original Sonoff firmware or something else (Tasmota, etc.)?

`Reading from UART timed out at byte 0!` shows ESPHome cannot communicate with the Nextion display used by NSPanel. The most common possibilities for this are the display cable not being properly connected to the panel's main board or the display is set to a different baud rate.
If you can easily open the device please take a look at the cables, or if you don't have any short circuit in the board, etc... A quick inspection is usually sufficient for find the issue.
Also, please wait 3 minutes for the boot sequence to complete, as the system will take some actions trying to recover from this (in case it isn't a hardware issue).

If after doing that you still having this issue, please come back with this log of the first 3 minutes after a boot (and a tentative to upload) and I will be happy to help.

**Comment by edwardtfn** [comment]
Hey @as-apps, any update on this?

**Comment by edwardtfn** [comment]
I'm closing this as it is quiet here, but please feel free to reopen if you are still facing this issue.
