### ISSUE TITLE
NS Panel time set incorrectly!

### ISSUE THREAD

**Issue by Vicentegz00** [Blackymas/NSPanel_HA_Blueprint#1415]
The NS Panel is displaying an incorrect time! The timezone is set correctly in Home Assistant. Running timedatectl on the linux server returns the correct time. All other values are updating correctly on the NS Panel. Like the weather forecast, states of various lights, etc. 

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/140369675/50ce50b8-17e4-46c4-8d03-46755deb2b2e)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/140369675/07005e00-e5c1-40c3-93a0-782c4be92980)

**Comment by edwardtfn** [comment]
Please try this: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#enforce-time-zone

**Comment by Vicentegz00** [comment]
By ESP home settings do you mean the NS Panel YAML file or my actual ESPHOME docker compose file?

**Comment by edwardtfn** [comment]
NS Panel YAML file

**Comment by Vicentegz00** [comment]
That worked perfectly! Thank you so much!
