### ISSUE TITLE
Increase the txt_maxl

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1419]
thanks @bluefoxlee @edwardtfn for the traditional chinese support. I also added the fonts inside the HMI file, but I also need to double the txt_maxl values in order to display the whole chinese without truncate from the entity page, would it possible to increase the txt_maxl in the v4.2 milestone as well?

_Originally posted by @shing6326 in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1359#issuecomment-1855987610_

**Comment by edwardtfn** [comment]
Do you have a list of fields where this is an issue?
Nextion is limited in memory and we cannot just put a large limit for everything,  but we certainly can do it for some fields.

**Comment by shing6326** [comment]
Hi @edwardtfn , I think the value_0x_label in entitypage01 could be increase because it could be a place that can show more informations from the panel.

**Comment by edwardtfn** [comment]
I'm closing this for now, as the requested changes are already applied on `dev`, but please feel free to reopen it if you find some other field requiring to change the length.

**Comment by edwardtfn** [comment]
- #1556
