### ISSUE TITLE
Will this work if TASMOTA is already on the panel?

### ISSUE THREAD

**Issue by RobertoCravallo** [Blackymas/NSPanel_HA_Blueprint#1420]
Could not find an answer, so I am wondering what happens, if TASMOTA is already on the panel. 

Are all steps the same?

**Comment by edwardtfn** [comment]
This thread can also be a good reference for you: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1422#issuecomment-1858097613

**Comment by edwardtfn** [comment]
I will close it for now, as the original question was answered, but please feel free to reopen it if you still having questions around this or create a new one if you have another issue.
