### ISSUE TITLE
Screen Stuck on loading screen

### ISSUE THREAD

**Issue by dfurnell** [Blackymas/NSPanel_HA_Blueprint#1428]
Hi Guys,

I am having some issues issues with my NS Panels stuck on the loading screen.

Today I have modified my yaml is ESP to match latest, updated the TFT and re-imported a clean blueprint?

The initializing screen shows as:
TFT: 3.3
ESPHome: (Blank)
Blueprint: (Blank)

**Comment by edwardtfn** [comment]
What happens when you press the button Upload TFT on Home Assistant under Settings > Devices and Services > ESPHome?

Could you please share the ESPHome logs?

**Comment by dfurnell** [comment]
it does force the screen to reload but i dont see the blue screen loading the TFT just straight to initializing then onto image screen saying stuck loading.

I think I have attached the log file.

[logs_nspanel_logs.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13692763/logs_nspanel_logs.txt)

**Comment by edwardtfn** [comment]
I got your logs, but couldn't find the moment you pressed the button "Upload TFT".
Could you please start logging again then follow the steps bellow:
1. Restart the device (Un can click on restart button under Settings > Devices and Services > ESPHome)
2. After the display is back, wait 2 minutes for the boot sequence finishes. Please capture logs all this time.
3. While you still capturing logs, press the Upload TFT button on the device's page
4. Wait about 15sec after the system restarts (regardless if the transfer was successful or not)
5. Save all the logs and share here, please.

**Comment by dfurnell** [comment]
Thanks you. 

Pressed @ 14:26

[logs_nspanel_logs (1).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13692854/logs_nspanel_logs.1.txt)

**Comment by edwardtfn** [comment]
The error is in the url you are using for the TFT file: `http://10.1.2.250:8123.local:8123/local/nspanel_eu.tft`

Please try this: `http://10.1.2.250:8123/local/nspanel_eu.tft`

**Comment by dfurnell** [comment]
Pressed TFT 14:46.

Not sure how i managed that one.
The message regarding ip is ok now but still stuck in home screen saying loading and worth noting initializing screen still says tft 3.0?
 

[logs_nspanel_logs (2).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13692905/logs_nspanel_logs.2.txt)

**Comment by edwardtfn** [comment]
Could you please share the yaml used for setting up your device on ESPHome? Please remove any sensitive information before sharing.

**Comment by edwardtfn** [comment]
And please try adding this to your yaml and then repeat the test:

```yaml
esp32:
  framework:
    type: arduino
```

**Comment by dfurnell** [comment]
Sorry Edward, back online.

I managed to push the blank tft out to it, after that it accepted the new one fine.

Yaml, as below: 
substitutions:
  ###### CHANGE ME START ######
  device_name: "nspanel" 
  wifi_ssid: "xxxxx"
  wifi_password: "xxxxx"

  nextion_update_url: "http://10.1.2.250:8123/local/8123/local/nspanel_eu.tft"
  nextion_blank_url: "http://10.1.2.250:8123/local/8123/local/nspanel_blank.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 1s

esp32:
  framework:
    type: esp-idf

##### My customization - Start #####
##### My customization - End #####

**Comment by dfurnell** [comment]
[Yaml file.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13692974/Yaml.file.txt)

**Comment by edwardtfn** [comment]
So, is everything working fine now?

**Comment by dfurnell** [comment]
Yep, All back up and running, thank you and merry christmas.
