### ISSUE TITLE
Enhancement - Support for Entity: remote

### ISSUE THREAD

**Issue by JS1Dev** [Blackymas/NSPanel_HA_Blueprint#1434]
Hi, I'd like to request support for the entity type: remote.   This entity comes from my [Logitech Harmony Hub](https://www.home-assistant.io/integrations/harmony/) integration which I currently use to turn my TV on (mine's called: remote.living_room).  It didn't work when I added it to my button page, though I might want to add it to my home page if supported.

For reference, this was discussed in the topic: [Climate Control Questions](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1418#top)
#1418.

**Comment by edwardtfn** [comment]
Added to `dev` and hopefully it will be included in the next release.

**Comment by JS1Dev** [comment]
Great, thanks so much @edwardtfn, I'll look forward to when it's released 👍
