### ISSUE TITLE
Blueprint version mismatch!

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1436]
I have this problem, I haven't found a solution.  I have uploaded the TFT.  

```

[17:25:13][E][script.check_versions:2179]: Blueprint version mismatch!
[17:25:13][D][script.check_versions:2187]: Framework: esp-idf
[17:25:13][D][script.check_versions:2188]: Baud rate: 115200
[17:25:18][D][text_sensor:064]: 'dougpanel NSPanel event': Sending state '{"page": "boot", "event": "timeout", "value": 1, "version": "4.1.4", "display_mode": "2"}'
[17:25:18][E][text_sensor.disp1_nspanel_event:1452]: Starting
[17:25:18][E][text_sensor.disp1_nspanel_event:1460]: page: boot
[17:25:18][E][text_sensor.disp1_nspanel_event:1461]: component: null
[17:25:18][E][text_sensor.disp1_nspanel_event:1462]: value: 1
[17:25:18][E][text_sensor.disp1_nspanel_event:1463]: entity:
 ```

Originally posted by @omayhemo in: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1271#issuecomment-1861849679

**Comment by edwardtfn** [comment]
Hey @omayhemo,

1. On the blue boot screen in the panel, which versions are shown for TFT, ESPHome and Blueprint?
2. If you open the automation on Home Assistant, which version is shown on the beginning after the introduction?
3. Can you see any error message on Home Assistant logs (Settings > System > Logs)?
4. On ESPHome logs (the ones you shared before), what is shown right before the message about version mismatch? Which versions are shown there for TFT, ESPHome and Blueprint?

**Comment by omayhemo** [comment]
Hi Edward, 

Thanks for helping and your work.

1. On the blue boot screen in the panel, which versions are shown for TFT, ESPHome and Blueprint?
_4.1.4, 
4.1.4
Blueprint: Retry #_

If you open the automation on Home Assistant, which version is shown on the beginning after the introduction?
_v4.1.4_

Can you see any error message on Home Assistant logs (Settings > System > Logs)?
_Nothing that I can find relevant._
On ESPHome logs (the ones you shared before), what is shown right before the message about version mismatch? Which versions are shown there for TFT, ESPHome and Blueprint?
_[17:46:41][D][script.check_versions:2175]: ESPHome version: 4.1.4
[17:46:41][D][script.check_versions:2176]: TFT version: 4.1.4
[17:46:41][D][script.check_versions:2178]: Blueprint version:_

**Comment by omayhemo** [comment]
It appears to be working, I just kept retrying the steps...

**Comment by edwardtfn** [comment]
2 things to try when this happens:
1. Restart Home Assistant
2. Remove the panel from Home Assistant, restart Home Assistant, add the panel again

**Comment by edwardtfn** [comment]
I've made some changes to v4.2 to handle this situation nicely. That still in `dev` but may be released soon.

**Comment by Maddoc42** [comment]
Unsure if helpful or even correct: I had the same issue trying to setup my first NSPanel. While I had imported the blueprint, I had not yet configured it with the panel (my thinking was to have the panel boot first before doing any configuration via the blueprint). Once configuring the blueprint (all default values except the panel) the panel booted successfully.

Thanks for the awesome blueprint and happy new year 🥳

**Comment by edwardtfn** [comment]
Now with the changes I've made the system will wait a bit for the blueprint but then will show the Home page regardless if it gets settings from the blueprint or not. In this case, that page will be basically limited to display time and some other very basic things, but still "nicer" than being stuck on the boot page, specially when the panel is already set and it is just about HA being out.
