### ISSUE TITLE
Screensaver only black

### ISSUE THREAD

**Issue by derpate1989** [Blackymas/NSPanel_HA_Blueprint#1439]
Hi, After "Timeout Sleep" time my Screen Show me a blank black Screen. But in HA Show my "Current Page" a Screensaver Page is activ. Can i configure a Screensaver with Clock or other Infos? And How?

**Comment by edwardtfn** [comment]
Please take a look at this one and let me know if this is a similar request?

#1065

**Comment by edwardtfn** [comment]
> Clock or other Infos?

Short answer is "Not yet", but...

> And How?

This is what #1065 is about.

**Comment by derpate1989** [comment]
Yes thanks. I thought there was already a simpler solution 😅

**Comment by edwardtfn** [comment]
- #1556
