### ISSUE TITLE
Fan Entity not supported?

### ISSUE THREAD

**Issue by Levanterman** [Blackymas/NSPanel_HA_Blueprint#144]
Hi

I have some ceiling fans via eweLink. They are listed in Home Assistant as Fan Entities. 

They dont seem to work in the NSPanel. I can see the Fan is not listed in your supported list Scene | Automation | Switch .... etc.

Will the fan entity be added in future releases?

Thanks again for this awesome update to the NSPANELs

**Comment by Blackymas** [comment]
hi can you share all services and attributes - than we can check

**Comment by Levanterman** [comment]
Hi

[https://www.home-assistant.io/integrations/fan/](url)

Services:
[https://github.com/home-assistant/core/blob/dev/homeassistant/components/fan/services.yaml](url)

I only use fan.turn_on, fan.turn_off , I haven't tried a lot of the other services listed in the link above.

The Attributes are also listed in the link, e.g. EntityID and Speed. The default LoveLace just provides a Speed Slider (mine is Off, Low, Med , High speed) is all the information you need in the link? please let me know if you need more from my HA instance, maybe some fan logs?

Thanks

**Comment by tikismoke** [comment]
Ok adding a fan.toggle seems more easy as I thoughts, except icon creating part in HMI :(
I'll try to test this tomorrow or next day.
As a start I think it will cover 75% of use 👍.
@Levanterman I tell you once it's done.

**Comment by Levanterman** [comment]
@tikismoke hey that's great, thanks . I am not home again until Sunday , I can't try it until then . Ah the HMI makes sense as when I try Fan at the moment , there's no icon , so I'll need to push an update to the Nextion I'm guessing 🙏🙌🙏

**Comment by Blackymas** [comment]
if you only want toggle why don't you create a helper that you can put on the keys

the helper can trigger your fan via automation or you can use the blueprint where two different entities are matched there are several ways to do this

@tikismoke 
if you have the technical implementation ready share it in my dev repo I check it then and take it over. I can then create the image for the HMI :)

**Comment by tikismoke** [comment]
> if you only want toggle why don't you create a helper that you can put on the keys
> 
> the helper can trigger your fan via automation or you can use the blueprint where two different entities are matched there are several ways to do this
> 
> @tikismoke if you have the technical implementation ready share it in my dev repo I check it then and take it over. I can then create the image for the HMI :)

No ready at all. I will look at it tomorrow in the evening. For a start I'd like to just add the toggle part. You could create the both icon on the hmi (fan on / fan off).

**Comment by tikismoke** [comment]
@Levanterman it works with the PR mentioned. Only toggle as any other button but it's done.

**Comment by Blackymas** [comment]
added in https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.0.0
