### ISSUE TITLE
Noob instalation problems.

### ISSUE THREAD

**Issue by IkaSGC** [Blackymas/NSPanel_HA_Blueprint#1440]
Hi, I'm having a few NOOB problems on my first attempt at installation. The first problem is wifi. The device is connecting to wifi with a hidden SSID. But for some reason it can't see the wifi and won't connect. 

The second problem is with the FW itself?? After I load it into the panel the screen stays black. As soon as I press the buttons, I get the non-functional layout from the last installation (different type of integration).

Can anyone advise ? 

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7561343/e67dc8ea-6ca6-4d31-a9f9-df171dc8cdc8)

**Comment by edwardtfn** [comment]
Let's solve the wifi first then we look at the issue with the screen.

Please try this: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#hidden-wi-fi

**Comment by IkaSGC** [comment]
I tried putting it there in every possible format I could think of, but it always ends up with some kind of error. Do you have a sample yaml file where you can see the entire code entry?

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7561343/4a770369-f375-4825-84fb-2723bb9f60ad)

**Comment by edwardtfn** [comment]
> I get the non-functional layout from the last installation (different type of integration).

What have you used before? Knowing what you have on your screen will help with the next steps.

**Comment by IkaSGC** [comment]
Before i try NSPanel Manager..... 

About that wifi, i try multiple inputs, but i gets only errors.... Last try is this, galidation done, no error, but no connection to hidden wifi after reboot.

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7561343/75fe2194-d255-423d-a691-cd6a8df3503e)

**Comment by edwardtfn** [comment]
Next time,please pase as a text and not an image, so it's easier to make the changes. 😉

**Comment by IkaSGC** [comment]
Sorry, my bad.... 😇 But looks like its working, i mean, wifi is working now.... It shows bad hostname, but it is connected. 

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7561343/9bd8a48c-d8e0-4194-ac90-7b9386c9c772)

But screen is stil bad.... I pres some buttons, then touch screen (red errors) and then it jumps into fallback screen as you can see on the screen. 

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7561343/8506f588-4cb3-4394-8f91-0dad58860c81)

**Comment by edwardtfn** [comment]
1. Have you tried the "Upload TFT" button?
2. Could you please send ESPHome logs from when you press that button to the moment the display restarts?

Please take a look at this: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload

**Comment by IkaSGC** [comment]
I'm a little lost on this one. The manual describes that if I have the EU version, I should have the TFT version as well. See the screen I have such a version uploaded in the WWW folder. 

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7561343/1878d6bb-fdf7-4af1-be02-d96e78fa17ab)

If I understand correctly, it is not an "Upload" to the device but only to the HA file system. Which I'm done. The file installation is then listed in the ESPhome code. 

`nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"`

Or is there another button I don't know about?

**Comment by edwardtfn** [comment]
> Or is there another button I don't know about?

There is.
Under **Settings** > ** Devices & Services** > **ESPHome**, you will find what we call your "Device's page". On that page there is a button "Upload TFT". Press that one.

**Comment by edwardtfn** [comment]
What you have done before was to copy the file from GitHub to your local http server (Home Assistant) and informed ESPHome where to find that file (`nextion_update_url´), but to start the upload you must click that button under your device's page.

**Comment by IkaSGC** [comment]
Ok, that was the NOOB problem... Its working now.... But screen is turning of after cca 1 min.... Possible just settings, bud i dont fing it... But i will find it !! :D

**Comment by bentouspam** [comment]
on device page / configuration, you have the timers for dimming and sleep. to unset the sleep timeout, enter 0.
