### ISSUE TITLE
Home Assistanat 2023.12.x breaking changes?

### ISSUE THREAD

**Issue by Floppe** [Blackymas/NSPanel_HA_Blueprint#1449]
Hi,

I updated my HASS and ESPHOME today and all my NS panels cannot find the blueprint after that.

Stupidly I also flashed the ESP before I noticed this. So many points were it could go wrong. However, I suspect HASS and the blueprint.

**Comment by fuzzysb** [comment]
was just about to pull the trigger...... thankyou. and i hope you recover after the downgrade. there is a breaking change in 2023.12 of ESPHome, i wonder if this is the cause?
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16162689/3460c840-24ce-4db5-a091-23e2472d906a)

**Comment by Floppe** [comment]
I will wait a couple of days. Fixes usually comes fast here and I can endure to be without the panels for that time.

**Comment by drgonz0** [comment]
I can confirm rolling back works well, and I'm temporarily skipping the update.  I've got no business messing around with 4 panels before before the holiday festivities.  That's all I need.  I've got great stability in the system, until I decide to update.  :)

**Comment by edwardtfn** [comment]
> I updated my HASS and ESPHOME today and all my NS panels cannot find the blueprint after that.

What do you see in your screen? What about Home Assistant logs (**Settings** > **System** > **Logs**).

> was just about to pull the trigger...... thankyou. and i hope you recover after the downgrade. there is a breaking change in 2023.12 of ESPHome, i wonder if this is the cause?

Nope. That is not the case.
The latest version of this project should be compatible with ESPHome 2023.12.0.
Only the [customization related to `deep_sleep`](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#deep-sleep) is[ failing compiling](https://github.com/Blackymas/NSPanel_HA_Blueprint/actions/runs/7282442170) with another error message, but as far as I know we have only one person using that. So, unless you have manually added `deep_sleep` to your settings, you should be good.

**Comment by GeebotGill** [comment]
upgrading to EspHome 2023.12.1 fixed it for me. It may have been coincidence, as it only caused problems on two of 7 NSPanels.

**Comment by Floppe** [comment]
I can confirm, upgraded ESPHome yet again to 2023.12.2 and now it works.
