### ISSUE TITLE
Component ID disp1 ERROR

### ISSUE THREAD

**Issue by rjing001** [Blackymas/NSPanel_HA_Blueprint#1450]
The following Error is thrown when attempting update after ESPHome update 2023.12.0

File "/esphome/esphome/cpp_helpers.py", line 56, in register_component
    raise ValueError(
ValueError: Component ID disp1 was not declared to inherit from Component, or was registered twice. Please create a bug report with your configuration.

**Comment by CH-Tefi** [comment]
I received the same error on all nsPanels

**Comment by Cody8Bit** [comment]
I have the same error in my nspanel.

**Comment by edwardtfn** [comment]
Try cleaning build files (ESPHome dashboard, 3-dot menu related to your device).
If the error persists, please share your yaml here. Remember to hide any sensitive info before sharing.

**Comment by edwardtfn** [comment]
Similar to:
- #1448

**Comment by rjing001** [comment]
updated to 2023.12.2, cleaned build files.  Same issue.  Here's the yaml file I've been using for probably a year...

#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ADVANCED CONFIG + FULL ESPHOME CODE!                                                      #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################


##### ADVANCED CONFIGURATION - activate only when you know what you do ##############################
substitutions: 
  # ## usage of secrets-file ## -> comment in ###### Change ME ######
  device_name: "nsplivingroom" # Wird im Blueprint benötigt!
  common_name: "NS Panel Living Room"
  wifi_ssid: !secret wifi_ssid # add in your esphome secrets file.
  wifi_password: !secret wifi_password # add in your esphome secrets file. -> per default this is also used for ota_password and web_password
  ota_password: !secret nsplivingroom_ota_password # add in your esphome secrets file. - manual change in code required to activate
  web_password: !secret nsplivingroom_web_password # add in your esphome secrets file. - manual change in code required to activate
  api_encrypt_key: !secret nsplivingroom_api_encrypt_key # add in your esphome secrets file. - manual change in code required to activate
  ap_password: !secret nsplivingroom_ap_password
  nextion_update_url: !secret nsplivingroom_update_url # add in your esphome secrets file. Example: "http://"HOME ASSISTANT IP":8123/local/nspanel/nspanel.tft"

  # ## static ip config ##
  ip: "xxx.xxx.xxx.xxx"
  gw: "xxx.xxx.xxx.xxx"
  subnet: "xxx.xxx.xxx.xxx"
  # dns: "10.0.0.138"
  # domain: ".local"

##### if you rename this file to .nspanel_esphome.yaml then you can activate nested config
##### use the ADVANCED CONFIG-Section as device configuration
##### https://esphome.io/guides/configuration-types.html#yaml-insertion-operator
# <<: !include .nspanel_esphome.yaml

##### END OF ADVANCED CONFIGURATION ##############################################################

##### WIFI SETUP #####
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  power_save_mode: none
  ##### advanced config - uncomment to use static IP-Config #####  
  manual_ip:
    static_ip: ${ip}
    gateway: ${gw}
    subnet: ${subnet}
  #   dns1: ${dns}
  # domain: ${domain}
  ##### Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name}"
    password: ${ap_password}

##### Functionality for the Nextion display #####
external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h

##### ESPHOME CONFIGURATION #####
esphome:
  name: ${device_name}
  comment: ${common_name}
  min_version: 2022.10.2

##### TYPE OF ESP BOARD #####
esp32:
  board: esp32dev

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    # password: ${wifi_password}
    ##### advanced config - change to use web_password ##### 
    password: ${web_password}

##### OTA PASSWORD #####
ota:
  # password: ${wifi_password}
  ##### advanced config - change to use ota_password ##### 
  password: ${ota_password}
  safe_mode: true
  reboot_timeout: 3min
  num_attempts: 3

##### LOGGER #####
logger:
#  baud_rate: 0
#  level: WARN

##### CONFIGURE INTERNAL BUZZER #####
output:
    ##### BUZZER FOR PLAYING RINGTONES #####
  - platform: ledc
    id: buzzer_out
    pin:
      number: 21

##### ENABLE RINGTONE MUSIC SUPPORT #####
rtttl:
  id: buzzer
  output: buzzer_out

##### UART FOR NEXTION DISPLAY #####
uart:
  tx_pin: 16
  rx_pin: 17
  baud_rate: 115200
  id: tf_uart

###### REBOOT BUTTON #####
button:
  - platform: restart
    name: Restart ${device_name} 
    id: restart_nspanel


##### START - API CONFIGURATION #####
api:
  ##### advanced config - activate to use api_encrypt_key ##### 
  encryption:
    key: ${api_encrypt_key}

  services:

    ##### SERVICE TO UPDATE THE HMI FILE #####
    - service: upload_tft
      then:
        - lambda: 'id(disp1)->upload_tft();'

    ##### SERVICE TO UPDATE THE TFT FILE from URL #####
    - service: upload_tft_url
      variables:
        url: string
      then:
        - lambda: 'id(disp1)->set_tft_url(url.c_str());'
        - lambda: 'id(disp1)->upload_tft();'
            
    ##### Service to send a command "printf" directly to the display #####
    - service: send_command_printf
      variables:
        cmd: string
      then:
        - lambda: 'id(disp1).send_command_printf("%s", cmd.c_str());'

    ##### Service to send a command "text_printf" directly to the display #####
    - service: send_command_text_printf
      variables:
        component: string
        message: string
      then:
        - wait_until:
              switch.is_on: nextion_init
        - lambda: 'id(disp1).set_component_text_printf(component.c_str(), "%s", message.c_str());'

    ##### Service to send a command "component_value (Dualstate Button)" directly to the display #####
    - service: send_command_value
      variables:
        component: string
        message: int
      then:
        - wait_until:
              switch.is_on: nextion_init
        - lambda: 'id(disp1).set_component_value(component.c_str(), message);'

    ##### Service to send a command "hide componente" directly to the display #####
    - service: send_command_hide
      variables:
        component: string
      then:
        - wait_until:
              switch.is_on: nextion_init
        - lambda: 'id(disp1).hide_component(component.c_str());'

    ##### Service to send a command "show componente" directly to the display #####
    - service: send_command_show
      variables:
        component: string
      then:
        - wait_until:
              switch.is_on: nextion_init
        - lambda: 'id(disp1).show_component(component.c_str());'

    ##### Service to send a command "font color" directly to the display #####
    - service: send_command_font_color
      variables:
        component: string
        message: int
      then:
        - wait_until:
              switch.is_on: nextion_init
        - lambda: 'id(disp1).set_component_font_color(component.c_str(), message);'
    
    ##### Service to send a command "background color" directly to the display #####
    - service: send_command_background_color
      variables:
        component: string
        message: int
      then:
        - wait_until:
              switch.is_on: nextion_init
        - lambda: 'id(disp1).set_component_background_color(component.c_str(), message);'

    ##### Service to show a notification-message on the screen #####
    - service: notification_show
      variables:
        label: string
        message: string
      then:
        - wait_until:
              switch.is_on: nextion_init
        - lambda: |-
            id(disp1).send_command_printf("page notification");
            id(disp1).set_component_text_printf("notification.notifi_label", "%s", label.c_str());
            id(disp1).set_component_text_printf("notification.notifi_text01", "%s", message.c_str());
            id(notification_label).publish_state(label.c_str());
            id(notification_text).publish_state(message.c_str());
        - switch.turn_on: notification_unread
        - if:
            condition:
              switch.is_on: notification_sound
            then:
              - rtttl.play: "two short:d=4,o=5,b=100:16e6,16e6"

    ##### Service to clear the notification #####
    - service: notification_clear
      then:
        - wait_until:
              switch.is_on: nextion_init
        - lambda: |-
            id(notification_label).publish_state("");
            id(notification_text).publish_state("");
        - switch.turn_off: notification_unread

    ##### Service to play a rtttl tones #####
    # Example tones : https://codebender.cc/sketch:109888#RTTTL%20Songs.ino
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'    

    #### Service to send thermostat cycle state ####
    - service: send_thermostat_cycle_state
      variables:
        value: float
      then:
        - wait_until:
              switch.is_on: nextion_init
        - lambda: |-
            //ESP_LOGD("nextion", "thermostat sendig value %f", value);
            int left=16; // 16 is empty left.
            int mid=17; // 17 is empty mid.
            int right=18; // 18 is empty right.
            if (value < 13.5) {
              left=16;
              mid=17;
              right=18;
            } else if (value >= 13.5 and value < 14) {
              left=19;
              mid=17;
              right=18;
            } else if (value >= 14 and value < 14.5) {
              left=20;
              mid=17;
              right=18;
            } else if (value >= 14.5 and value < 15) {
              left=21;
              mid=17;
              right=18;
            } else if (value >= 15 and value < 15.5) {
              left=22;
              mid=17;
              right=18;
            } else if (value >= 15.5 and value < 16) {
              left=23;
              mid=17;
              right=18;
            } else if (value >= 16 and value < 16.5) {
              left=24;
              mid=17;
              right=18;
            } else if (value >= 16.5 and value < 17) {
              left=25;
              mid=17;
              right=18;
            } else if (value >= 17 and value < 17.5) {
              left=26;
              mid=17;
              right=18;
            } else if (value >= 17.5 and value < 18) {
              left=27;
              mid=17;
              right=18;
            } else if (value >= 18 and value < 18.5) {
              left=28;
              mid=17;
              right=18;
            } else if (value >= 18.5 and value < 19) {
              left=29;
              mid=30;
              right=18;
            } else if (value >= 19 and value < 19.5) {
              left=29; 
              mid=31;
              right=18;
            } else if (value >= 19.5 and value < 20) {
              left=29;
              mid=32;
              right=18;
            } else if (value >= 20 and value < 20.5) {
              left=29;
              mid=33;
              right=18;
            } else if (value >= 20.5 and value < 21) {
              left=29;
              mid=34;
              right=18;
            } else if (value >= 21 and value < 21.5) {
              left=29;
              mid=35;
              right=18;
            } else if (value >= 21.5 and value < 22) {
              left=29;
              mid=36;
              right=18;
            } else if (value >= 22 and value < 22.5) {
              left=29;
              mid=37;
              right=38;
            } else if (value >= 22.5 and value < 23) {
              left=29;
              mid=37;
              right=39;
            } else if (value >= 23 and value < 23.5) {
              left=29;
              mid=37;
              right=40;
            } else if (value >= 23.5 and value < 24) {
              left=29;
              mid=37;
              right=41;
            } else if (value >= 24 and value < 24.5) {
              left=29;
              mid=37;
              right=42;
            } else if (value >= 24.5 and value < 25) {
              left=29;
              mid=37;
              right=43;
            } else if (value >= 25 and value < 25.5) {
              left=29;
              mid=37;
              right=44;
            } else if (value >= 25.5 and value < 26) {
              left=29;
              mid=37;
              right=45;
            } else if (value >= 26 and value < 26.5) {
              left=29;
              mid=37;
              right=46;
            } else if (value >= 26.5 and value < 27) {
              left=29;
              mid=37;
              right=47;
            } else if (value >= 27) {
              left=29;
              mid=37;
              right=48;
            }
            // sends the 3 images to the display
            //ESP_LOGD("nextion", "thermostat left %i", left);
            //ESP_LOGD("nextion", "thermostat mid %i", mid);
            //ESP_LOGD("nextion", "thermostat right %i", right);
            id(disp1).send_command_printf("climate_left.pic=%i", left);
            id(disp1).send_command_printf("climate_middle.pic=%i", mid);
            id(disp1).send_command_printf("climate_right.pic=%i", right);
            // send target-temp
            id(disp1).set_component_text_printf("target_temp", "%.1f°", value);
            id(display_target_temp).publish_state(value);


##### START - GLOBALS CONFIGURATION #####
globals:

  ##### Save Display Brightness for NSPanel reboot #####
  - id: display_brightness_global
    type: int
    restore_value: true
    initial_value: '100'

  ##### Save Display DIM Brightness for NSPanel reboot
  - id: display_dim_brightness_global
    type: int
    restore_value: true
    initial_value: '10'

  ##### Temperature Correction #####
  - id: temperature_correction_global
    type: float
    restore_value: true
    initial_value: '0.0'

  ##### Save Display DIM Brightness for NSPanel reboot
  - id: sleep_modus_global
    type: int
    restore_value: true
    initial_value: '0'

  ##### lastclick_general State #####
  - id: lastclick_general_global
    type: std::string
    restore_value: no
    initial_value: ''

  ##### lastclick_lightsettings State #####
  - id: lastclick_lightsettings_global
    type: std::string
    restore_value: no
    initial_value: ''

  ##### lastclick_coversettings State #####
  - id: lastclick_coversettings_global
    type: std::string
    restore_value: no
    initial_value: ''

  ##### lastclick_climatesettings State #####
  - id: lastclick_climatesettings_global
    type: std::string
    restore_value: no
    initial_value: ''

  ##### lastclick_ccurrentpage State #####
  - id: currentpage_global
    type: std::string
    restore_value: no
    initial_value: ''

##### START - BINARY SENSOR CONFIGURATION #####
binary_sensor:

  ###### LEFT BUTTON BELOW DISPLAY TO TOGGLE RELAY#####
  - platform: gpio
    name: ${device_name} Left Button
    pin:
      number: 14
      inverted: true

  ##### RIGHT BUTTON BELOW DISPLAY TO TOGGLE RELAY #####
  - platform: gpio
    name: ${device_name} Right Button
    pin:
      number: 27
      inverted: true

  ##### Restart NSPanel Button - Setting Page #####
  - platform: nextion
    name: Restart ${device_name}
    page_id: 7
    component_id: 9
    internal: true
    on_click:
      - button.press: restart_nspanel

  ##### Restart NSPanel Button - Boot Page #####
  - platform: nextion
    name: Restart ${device_name}
    page_id: 8
    component_id: 5
    internal: true
    on_click:
      - button.press: restart_nspanel

  ##### Sleep Modus NSPanel Button #####
  - platform: nextion
    name: ${device_name} Sleep Modus
    page_id: 7
    component_id: 4
    internal: true
    on_click:
      - switch.toggle: sleep_modus

  ##### Hotwater Charge #####
  # - platform: nextion
  #   name: ${device_name} Hotwater Charge
  #   page_id: 6
  #   component_id: 20
    # on_click:
    #   - homeassistant.service:
    #       service: switch.toggle
    #       data:
    #         entity_id: ${ha_hotwater_charge}


##### START - SENSOR CONFIGURATION #####
sensor:

  ##### Uptime #####
  - platform: uptime
    name: ${device_name} uptime
    disabled_by_default: true

  ##### WIFI Signal stregth
  - platform: wifi_signal
    name: ${device_name} RSSI
    update_interval: 60s

  ##### INTERNAL TEMPERATUE SENSOR, ADC VALUE #####
  - platform: adc
    id: ntc_source
    pin: 38
    update_interval: 10s
    attenuation: 11db

  ##### INTERNAL TEMPERATUE SENSOR, adc reading converted to resistance (calculation)#####
  - platform: resistance
    id: resistance_sensor
    sensor: ntc_source
    configuration: DOWNSTREAM
    resistor: 11.2kOhm

  ##### INTERNAL TEMPERATUE SENSOR, resistance to temperature (calculation) #####
  - platform: ntc
    name: ${device_name} Temperature
    id: temp_nspanel
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    filters:
      - lambda: return x + id(temperature_correction_global);
#    on_value:
#      then:
#        - wait_until:
#            switch.is_on: nextion_init
#         - lambda: id(disp1).set_component_text_printf("home.current_temp", "%.1f°", id(temp_nspanel).state); # onboard temp (thermostat temp) to home page.
#         - lambda: id(disp1).set_component_text_printf("climate.current_temp", "%.1f", id(temp_nspanel).state);

  ##### current value of page-climate target_temp #####
  - platform: template
    name: ${device_name} Display Target Temperature
    id: display_target_temp
    lambda: return {};
    update_interval: 10s

  ###### Display Brightness GET VALUE FROM NSPanel SLIDER #####
  - platform: nextion
    id: brightslider
    name: ${device_name} brightness Slider
    variable_name: brightslider
    internal: true
    on_value:
      then:
        - wait_until:
            switch.is_on: nextion_init
        - number.set:
            id: display_brightness
            value: !lambda 'return int(x);'
          # send text field percentage of current_lightslider_val  
        - lambda: id(disp1).set_component_text_printf("settings.a03", "%i", id(display_brightness_global));

  ###### Display DIM Brightness GET VALUE FROM NSPanel SLIDER #####
  - platform: nextion
    id: dimslider
    name: ${device_name} dim brightness slider
    variable_name: dimslider
    internal: true
    on_value:
      then:
        - wait_until:
            switch.is_on: nextion_init
        - number.set:
            id: display_dim_brightness
            value: !lambda 'return int(x);'
          # send text field percentage of current_lightslider_val  
        - lambda: id(disp1).set_component_text_printf("settings.a04", "%i", id(display_dim_brightness_global));

  ###### Send current page to HA
  # - platform: nextion
  #   id: current_page
  #   name: "${device_name} Current Page"
  #   variable_name: dp
  #   update_interval: 1s
  #   accuracy_decimals: 0
  #   filters:
  #     - delta: 1.0
  #     - lambda: return int(x);


##### START - TEXT SENSOR CONFIGURATION #####
text_sensor:

  ##### ESPhome version used to compile the app #####
  - platform: version
    name: ${device_name} ESPhome Version
    disabled_by_default: true

  - platform: wifi_info
    ip_address:
      name: ${device_name} IP
      disabled_by_default: true
    ssid:
      name: ${device_name} SSID
      disabled_by_default: true
    bssid:
      name: ${device_name} BSSID
      disabled_by_default: true

  - platform: template
    name: ${device_name} Notification Label
    id: notification_label

  - platform: template
    name: ${device_name} Notification Text
    id: notification_text

  ##### last click sensor, the main action variable - push to HA #####
  - platform: nextion
    nextion_id: disp1
    name: ${device_name} Last Click
    id: disp1_lastclick_general
    update_interval: 50ms
    component_name: lastclick
    internal: false
    filters:
      - lambda: |-
          if (strcmp(x.c_str(), id(lastclick_general_global).c_str()) != 0) {
            return x;
          } else {
            return {};
          }
    on_value:
      then:
        - globals.set:
            id: lastclick_general_global
            value: !lambda return x;
  
  ##### last click lightsettings page, the main action variable - push to HA #####
  - platform: nextion
    nextion_id: disp1
    name: ${device_name} last click lightsettings
    id: disp1_lastclick_lightsettings
    update_interval: 50ms
    component_name: lightsetting
    internal: false
    filters:
      - lambda: |-
          if (strcmp(x.c_str(), id(lastclick_lightsettings_global).c_str()) != 0) {
            return x;
          } else {
            return {};
          }
    on_value:
      then:
        - globals.set:
            id: lastclick_lightsettings_global
            value: !lambda return x;

  ##### last click coversettings page, the main action variable - push to HA #####
  - platform: nextion
    nextion_id: disp1
    name: ${device_name} last click coversettings
    id: disp1_lastclick_coversettings
    update_interval: 50ms
    component_name: coversetting
    internal: false
    filters:
      - lambda: |-
          if (strcmp(x.c_str(), id(lastclick_coversettings_global).c_str()) != 0) {
            return x;
          } else {
            return {};
          }
    on_value:
      then:
        - globals.set:
            id: lastclick_coversettings_global
            value: !lambda return x;

  ##### last click climate page, the main action variable - push to HA #####
  - platform: nextion
    nextion_id: disp1
    name: ${device_name} last click climatesettings
    id: disp1_lastclick_climatesettings
    update_interval: 50ms
    component_name: climatesetting
    internal: false
    filters:
      - lambda: |-
          if (strcmp(x.c_str(), id(lastclick_climatesettings_global).c_str()) != 0) {
            return x;
          } else {
            return {};
          }
    on_value:
      then:
        - globals.set:
            id: lastclick_climatesettings_global
            value: !lambda return x;

  ##### currentpage sensor, the main action variable - push to HA #####
  - platform: nextion
    nextion_id: disp1
    name: ${device_name} currentpage
    id: disp1_currentpage
    update_interval: 50ms
    component_name: currentpage
    internal: false
    filters:
      - lambda: |-
          if (strcmp(x.c_str(), id(currentpage_global).c_str()) != 0) {
            return x;
          } else {
            return {};
          }
    on_value:
      then:
        - globals.set:
            id: currentpage_global
            value: !lambda return x;


##### START - SWITCH CONFIGURATION #####  
switch:

  # ##### Restart switch ######
  # - platform: restart
  #   name: Restart ${device_name}

  # ##### Restart in safe-mode #####
  # - platform: safe_mode
  #   name: Restart ${device_name} (Safe Mode)

  ##### global variable to keep track on whether the Nextion display is ready or not. Delays initial info from HA to the display #####
  - platform: template
    name: ${device_name} Nextion inited
    id: nextion_init
    entity_category: config
    assumed_state: off
    optimistic: true

  ##### Notification unread #####
  - platform: template
    name: ${device_name} Notification unread
    id: notification_unread
    entity_category: config
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true

  ##### Notification sound #####
  - platform: template
    name: ${device_name} Notification sound
    id: notification_sound
    entity_category: config
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true

  ##### Confirmation Message #####
  - platform: template
    name: ${device_name} Confirmation Message
    id: confirmation_message
    entity_category: config
    optimistic: true

  ##### UPDATE TFT DISPLAY #####
  - platform: template
    name: ${device_name} Update TFT display
    id: tft_update
    entity_category: config
    turn_on_action:
      - delay: 16ms
      - lambda: id(disp1).upload_tft();
      - switch.turn_off: tft_update

  ##### PHYSICAL SWITCH 1 #####
  - platform: gpio
    name: ${device_name} Relay 1
    id: relay_1
    pin:
      number: 22

  ##### PHYSICAL SWITCH 2 ######
  - platform: gpio
    name: ${device_name} Relay 2
    id: relay_2
    pin:
      number: 19
      
  ##### DISPLAY ALWAYS ON #####
  - platform: gpio
    name: ${device_name} Screen Power
    id: screen_power
    entity_category: config
    pin:
      number: 4
      inverted: true
    restore_mode: ALWAYS_ON
    internal: true

  ##### Switch Display Sleep Modus #####
  - platform: template
    device_class: switch
    name: ${device_name} Sleep Modus
    id: sleep_modus
    entity_category: config
    restore_mode: RESTORE_DEFAULT_OFF
    assumed_state: false
    optimistic: true
    on_turn_off:
      - lambda: id(disp1).send_command_printf("home.sleepmodus.val=0");
      - globals.set:
            id: sleep_modus_global
            value: '0'
      - lambda:  id(disp1).set_component_value("settings.a02",0);
    on_turn_on:
      - lambda: id(disp1).send_command_printf("home.sleepmodus.val=1");
      - globals.set:
            id: sleep_modus_global
            value: '1'
      - lambda:  id(disp1).set_component_value("settings.a02",1);


##### START - NUMBER CONFIGURATION #####
number:

  ##### SCREEN BRIGHTNESS #####
  - platform: template
    name: ${device_name} Display Brightness
    id: display_brightness
    entity_category: config
    unit_of_measurement: '%'
    min_value: 1
    max_value: 100
    step: 1
    restore_value: true
    optimistic: true
    set_action:
      then:
        - lambda: 'id(disp1).set_backlight_brightness(x/100);'
        - lambda: 'id(disp1).send_command_printf("home.brightness.val=%i", int(x));'
        - globals.set:
            id: display_brightness_global
            value: !lambda 'return int(x);'

  ##### SCREEN BRIGHTNESS DIMMED DOWN #####
  - platform: template
    name: ${device_name} Display Brightness Dimdown
    id: display_dim_brightness
    entity_category: config
    unit_of_measurement: '%'
    min_value: 1
    max_value: 100
    step: 1
    restore_value: true
    optimistic: true
    set_action:
      then:
        - lambda: 'id(disp1).send_command_printf("home.brightdd.val=%i", int(x));'
        - globals.set:
            id: display_dim_brightness_global
            value: !lambda 'return int(x);'

  ##### Temperature Correction #####
  - platform: template
    name: ${device_name} Temperature Correction
    id: temperature_correction
    entity_category: config
    unit_of_measurement: '°C'
    min_value: -10
    max_value: 10
    step: 0.5
    restore_value: true
    optimistic: true
    set_action:
      then:
        - globals.set:
            id: temperature_correction_global
            value: !lambda 'return x;'


##### START - DISPLAY START CONFIGURATION #####
display:
  - platform: nextion
    id: disp1
    uart_id: tf_uart
    tft_url: ${nextion_update_url}
    on_setup:
      then:
        - lambda: id(disp1).send_command_printf("page 8");
        - wait_until:
            api.connected
        - delay: 0.5s
        - number.set:
            id: display_brightness
            value: !lambda 'return id(display_brightness_global);'
        - number.set:
            id: display_dim_brightness
            value: !lambda 'return id(display_dim_brightness_global);'
        - lambda: id(disp1).set_component_text_printf("settings.a03", "%i", id(display_brightness_global));
        - lambda: id(disp1).set_component_text_printf("settings.a04", "%i", id(display_dim_brightness_global));
        - lambda: id(disp1).send_command_printf("settings.brightslider.val=%i", id(display_brightness_global));
        - lambda: id(disp1).send_command_printf("settings.dimslider.val=%i", id(display_dim_brightness_global));
        - lambda: id(disp1).send_command_printf("home.sleepmodus.val=%i", id(sleep_modus_global));
        - lambda: |-
            id(disp1).set_component_value("settings.a02",0);
            if (id(sleep_modus_global) == 1) 
            {
              id(disp1).set_component_value("settings.a02",1);
            }
        - delay: 0.5s
        - switch.template.publish:
            id: nextion_init
            state: on

**Comment by edwardtfn** [comment]
@rjing001, you are using a too old code. It's big the change that was using some feature from ESPHome which got obsolete.
We are maintaining this continuously and have fixed lots of issues, some of those related to recent changes on both ESPHome and Home Assistant.

I would highly suggest you start using the code from our repo and having only the [customizations](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization) in your local yaml file, so we keep the task of maintaining the main code.

Something like this:
```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "nsplivingroom"
  common_name: "NS Panel Living Room"

  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: !secret nsplivingroom_update_url

  ota_password: !secret nsplivingroom_ota_password
  web_password: !secret nsplivingroom_web_password
  api_encrypt_key: !secret nsplivingroom_api_encrypt_key
  ap_password: !secret nsplivingroom_ap_password

  ip: "xxx.xxx.xxx.xxx"
  gw: "xxx.xxx.xxx.xxx"
  subnet: "xxx.xxx.xxx.xxx"
  
  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - advanced/esphome/nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####
esphome:
  comment: ${common_name}

# Custom OTA password
ota:
  password: ${ota_password}
  id: my_ota

# Custom web server credentials
web_server:
  auth:
    username: admin
    password: ${web_password}

# Encrypt the communication between ESPHome and Home Assistant
api:
  encryption:
    key: !secret api_encryption_key

# Set IP address manually
wifi:
  networks:
    - id: !extend wifi_default
      manual_ip:
        static_ip: ${ip}
        gateway: ${gw}
        subnet: ${subnet}
  ap:
    ssid: "${device_name}"
    password: ${ap_password}
##### My customization - End #####
```

**Comment by edwardtfn** [comment]
Hey @rjing001, have you tried the suggestion from my previous message? Please let me know the results.

**Comment by rjing001** [comment]
Sorry, but it took me over a month to get the first panel up and running with custom wallpaper and such.  And I don't remember half of what I had to do just to get it to there.  I'm nervous and honestly scared to just slap new code in there and press update without knowing all the unforeseen issues that I'm about to introduce.  I wish if they were making large major changes like this they would branch it off, so those of us that got this working could just keep what we got, and if we decided later to make the update/change we could.  I'm not an expert at this stuff and sometimes if feels like the community expects that you have unlimited time to learn any new thing they feel like slinging your way.  I'm not meaning to be ungrateful here, I do appreciate your help, but as I said I'm scared that I'm about to "brick" my device...  (or am I just over thinking this and being over dramatic?)

**Comment by edwardtfn** [comment]
By the way, looking t your ode and the error message, I believe the error is on this reference to an older library:
```yaml 
external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h
```

That PR was about removing reparse mode, which is needed only the first time you are installing a TFT, so you should be safe to completely remove those lines, then you will be using the latest Nextion component from ESPHome (which also includes the changed from that PR) and that might solve that specific error.

**Comment by rjing001** [comment]
@edwardtfn, thanks again.  I know you all put a lot of time and effort into these things for free, and I do appreciate it.  I'll copy my yaml off to a notepad and replace it with what you suggest.  I think the worse cast scenario would be me having to manually reflash it if it dies.  I'll try it probably later tonight.  and Sorry again for my skepticism, but my home assistant has been steadily dying sense the beginning of this month, one project after another failing after months or years with no issues and I'm just frustrated as I watch something I put so much time in slowly degrade without any explanations so far.  It's a little heart breaking, ya know?  Anyways, I'll report back once I've made the update, here's hoping for the best.

**Comment by rjing001** [comment]
Additional question, do I need to redownload the blueprint?

**Comment by rjing001** [comment]
Ok, did as you suggested.  Now, the screen keeps blanking out after a few minutes.  It used to stay on all the time.  Lost the labels for the switches that I had.  The bars that appear to indicate each switch is on still show, but the labels are gone.  Several other items that used to be on the screen are also missing.

**Comment by edwardtfn** [comment]
> Now, the screen keeps blanking out after a few minutes

Go to the device page (Settings > Devices and Services > ESPHome) and set Sleep time to 0.

**Comment by edwardtfn** [comment]
> Lost the labels for the switches that I had. The bars that appear to indicate each switch is on still show, but the labels are gone. 

Go to the automation which sets the Blueprint and double check the labels are there. This haven't changed since a long time. Maybe the colors, as that has changed...

**Comment by edwardtfn** [comment]
> Several other items that used to be on the screen are also missing.

Like what?

**Comment by edwardtfn** [comment]
> Additional question, do I need to redownload the blueprint?

Yes. When you update one part you should update the other two parts.
On that blue boot screen you should see TFT, ESPHome and Blueprint all with the same version. The latest is v4.1.4.

**Comment by edwardtfn** [comment]
> and Sorry again for my skepticism

No need to apologise... As I said, I fully understand your feeling.

**Comment by rjing001** [comment]
Ok, Sorry looks like we are working past each other.
So I reinstalled my old yaml and commented out the external components line as you suggested and it installed fine, but now I'm getting a constantly repeating error of "[18:09:45][W][nextion:405]: Nextion reported variable name invalid!".  Any ideas?

**Comment by rjing001** [comment]
> Yes. When you update one part you should update the other two parts.
> On that blue boot screen you should see TFT, ESPHome and Blueprint all with the same version. The latest is v4.1.4.

Ok, so that could be an issue.  I know I highly modified your original TFT files to change out the background and move some stuff around.  If I understand what your saying, I'll need to completely abandon all that effort and resign to using only your displays?

**Comment by edwardtfn** [comment]
> So I reinstalled my old yaml and commented out the external components line as you suggested and it installed fine, but now I'm getting a constantly repeating error of "[18:09:45][W][nextion:405]: Nextion reported variable name invalid!". Any ideas?

You are probably using a new TFT with that old code. You have to revert back to that older TFT you have before. And to the old Blueprint also.

**Comment by edwardtfn** [comment]
> Ok, so that could be an issue. I know I highly modified your original TFT files to change out the background and move some stuff around. If I understand what your saying, I'll need to completely abandon all that effort and resign to using only your displays?

Well, if you edited the TFT, you have to either do the same changes on the latest version or revert all back to the version you have before.

**Comment by rjing001** [comment]
> Well, if you edited the TFT, you have to either do the same changes on the latest version or revert all back to the version you have before.

No, I Hate that editor.  After messing around with it the last time, I swore I would rather throw the panel in the trash rather than going through that again.  Maybe it's best i just use your displays and live with it.  I just liked the look of the updates I had made.

**Comment by edwardtfn** [comment]
This is the issue of staying with an older version... If you keep updating in each version it probably will BA a small work from time to time but if you stay with a code more than an year old, it will be a huge amount of work to get it back.
But staying with old code you have to compromise with support... You can keep your Home Assistant ESPHome, Blueprint, TFT, etc all frozen in that point in time and everything will probably work forever, but as you start updating some parts, other parts may require update also, as something will have changed. This is not only changes from our side.., the original error you reported is due to a change in ESPHome side...

**Comment by rjing001** [comment]
Alright,  I downloaded and install your latest TFT file, updated the blueprint, and changed the yaml back to what you suggested above.  Everything seems to be working, I just need to go update the blueprint to populate all the buttons and try and figure out what "chips" are.  😃 Again, Thanks for all your help and all you do.  I think we can close this out now.  and Merry Christmas (belated)...
