### ISSUE TITLE
Cross-contamination of information from one NSPanel on a different NSPanel. (Different configs, different entities) 

### ISSUE THREAD

**Issue by aminorjourney** [Blackymas/NSPanel_HA_Blueprint#1452]
HA Details: 

Core: 2023.12.3
Supervisor: 2023.12.0
OS 11.2
Frontend: 20231208.2

ESPHome: 2023.12.1 

Experienced problem with setup for one week, before ESPHome 2023.12.x 

Reproducible by: add two different NSPanels to same ESPHome, use different blueprints made from the same template. 

-----
We have two NSPanels running via NSPanel_HA_Blueprint. Each panel is set up for the room it is in, with different chips, sensors, and switches. 

Yet occasionally, we see 'bleed thru' between panels. This manifests as panel A (in the attached file, NSPanel_nikki_office) occasionally displaying information designated for panel B (NSPanel_Master_Bathroom). 

Sometimes, it happens after sleep. Sometimes, it happens after interaction (ie, if I click on one of the home-screen switches, it will temporarily switch to display an element from the OTHER panel). 

I've attached the traces, and the config files, which I copy/pasted from the YAML editor window. Hope it helps.

Note: 

One POTENTIAL issue: I do have a backup template for an NSPanel for development (non-active) which I deleted earlier today in an attempt to see if that caused any issues. I can't tell if it's effective or not, but mentioning in case that's relevant. 

See in attached image how panel seems to show elements from NSPanel_Master_Bathroom config on NSPanel_Nikki_Office (look at switch label). 

![IMG_5378](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/3185443/a649ed44-fd6e-40d2-bfb6-1a8c7ac7bb35)

----

[trace automation.master_bathroom_2 2023-12-21T21_47_32.012836+00_00.json](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13746357/trace.automation.master_bathroom_2.2023-12-21T21_47_32.012836%2B00_00.json)
[trace automation.nspanel_nikki_office 2023-12-21T21_46_38.802267+00_00.json](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13746358/trace.automation.nspanel_nikki_office.2023-12-21T21_46_38.802267%2B00_00.json)
[NSPanel_Nikki_Office.YAML.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13746405/NSPanel_Nikki_Office.YAML.txt)
[NSPanel_Master_Bathroom.yaml.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13746406/NSPanel_Master_Bathroom.yaml.txt)

**Comment by edwardtfn** [comment]
I've never seen this behavior. I'm using 3 panels at home and haven't ever noticed anything similar, and I know some people is using way larger systems... So I will need your help to troubleshoot this.

Anyway, looking at the files you shared, I could see Nikki Office panel have duplicated entitier:
```json
            "nspanel_entities": [
              "device_tracker.nspanel2",
              "update.nspanel_nikki_office_firmware",
              "binary_sensor.nspanel_nikki_office_left_button",
              "binary_sensor.nspanel_nikki_office_right_button",
              "binary_sensor.nspanel_nikki_office_nextion_display",
              "binary_sensor.nspanel_nikki_office_status",
              "sensor.nspanel_nikki_office_temperature",
              "switch.nspanel_nikki_office_notification_unread",
              "switch.nspanel_nikki_office_notification_sound",
              "switch.nspanel_nikki_office_relay_1",
              "switch.nspanel_nikki_office_relay_2",
              "button.nspanel_nikki_office_restart",
              "button.nspanel_nikki_office_update_tft_display",
              "sensor.nspanel_nikki_office_detailed_entity",
              "sensor.nspanel_nikki_office_current_page",
              "sensor.nspanel_nikki_office_notification_label",
              "sensor.nspanel_nikki_office_notification_text",
              "number.nspanel_nikki_office_display_brightness",
              "number.nspanel_nikki_office_display_brightness_dimdown",
              "number.nspanel_nikki_office_temperature_correction",
              "number.nspanel_nikki_office_timeout_page",
              "number.nspanel_nikki_office_timeout_dimming",
              "number.nspanel_nikki_office_timeout_sleep",
              "select.nspanel_nikki_office_wake_up_page",
              "binary_sensor.nspanel_nikki_office_left_button_2",
              "binary_sensor.nspanel_nikki_office_right_button_2",
              "binary_sensor.nspanel_nikki_office_nextion_display_2",
              "binary_sensor.nspanel_nikki_office_status_2",
              "sensor.nspanel_nikki_office_temperature_2",
              "switch.nspanel_nikki_office_notification_unread_2",
              "switch.nspanel_nikki_office_notification_sound_2",
              "switch.nspanel_nikki_office_relay_1_2",
              "switch.nspanel_nikki_office_relay_2_2",
              "button.nspanel_nikki_office_restart_2",
              "button.nspanel_nikki_office_update_tft_display_2",
              "sensor.nspanel_nikki_office_detailed_entity_2",
              "sensor.nspanel_nikki_office_current_page_2",
              "sensor.nspanel_nikki_office_notification_label_2",
              "sensor.nspanel_nikki_office_notification_text_2",
              "number.nspanel_nikki_office_display_brightness_2",
              "number.nspanel_nikki_office_display_brightness_dimdown_2",
              "number.nspanel_nikki_office_temperature_correction_2",
              "number.nspanel_nikki_office_timeout_page_2",
              "number.nspanel_nikki_office_timeout_dimming_2",
              "number.nspanel_nikki_office_timeout_sleep_2",
              "select.nspanel_nikki_office_wake_up_page_2"
            ],
```

I would suggest you remove the panel from Home Assistant (not from ESPHome Dashboard, but only from HA) under **Settings** > **Devices & Services** > **ESPHome**, reboot your HA system (use the option that restarts also the Add-ons), then you add your panel back to Home Assistant on the **Devices & Services** page.
The automation settings should be OK with that, but please go back there after the device was added back and make sure all the selections (specially the ones using entities from that panel) are still intact.

Please let me know if you still having the issues after that.

This should be a harmless process, so feel free to do the same in the other panels just in case. 😉

**Comment by edwardtfn** [comment]
Hey @aminorjourney, have you tried the suggestion from my previous message? Please let me know the results.

**Comment by aminorjourney** [comment]
Apologies, and season's greetings!

Yes, it appears to have worked. I haven't experienced any strange effects, so we can assume things are good again. We can go ahead and close this out.

**Comment by edwardtfn** [comment]
Great! But I will change it (back) on the main code. We changed this on v4.1 to offer support to `bluetooth_proxy `, but as just a minority is using this, it might be better to go back to the previous settings.
If you see this issue again, please reopen this thread.
