### ISSUE TITLE
`DEV` Entities page does not show labels when I have custom names

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1460]
Hi,

Tested current dev branch and some thoughts. 
- Chips icons does not override with selected icons anymore, but a lightbulb or a switch/door is shown now instead.
- Hardware button indicators does not always show correct state if they are triggered from HA or webserver while screen is on.
- Climate heating broke for me, as the setpoint is not the same as target point for my geothermal heater. Perhaps a user setting in ESP? When I want to increase one step from 19 to 20 degrees then it is set to 40-50 degrees which is the target heating water temp. and all goes haywire in the basement and extremely hot in the house :)
- **Entities page does not show labels when I have custom names. #1455**
- Perhaps we could have a default icon based on UOM if none is entered/overiden for entities? Basics like climate, humidity, power?

_Originally posted by @Floppe in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1456_

**Comment by edwardtfn** [comment]
#1455 was merged with some (a lot 😃 ) of changes. Could you please try again and let me know if you still having issues with the Entities pages?

**Comment by edwardtfn** [comment]
Solved by #1455

**Comment by Floppe** [comment]
Still not working

**Comment by Floppe** [comment]
My bad, blueprint did not re-import. Works  as expected
