### ISSUE TITLE
`DEV` Alarm page does not update selected mode when changing

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1462]
Great. Tell me to stop if I test too much :)

- **Alarm page does not update selected mode when changing, but the other panels catches is ASAP on both home & alarm screen** 👍 
- This perhaps not an issue, but also not possible to switch from away to home. Need to disarm first before it accepts a new alarm state. The other way seems to work, home -> away which perhaps is more used.

_Originally posted by @Floppe in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1456#discussioncomment-7927206_

**Comment by edwardtfn** [comment]
I couldn't duplicate this.
Could you please send more info?

**Comment by itsieber** [comment]
Same issue here:

Changes on Webgui, but not not nspanel

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/20435788/cf3c0e96-25fa-4439-b28f-80a3168cd8d5)

**Comment by edwardtfn** [comment]
Are you also trying `dev`?

How are the settings for [Allow the device to make Home Assistant service calls](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Alarm-Control-Panel#allow-the-device-to-make-home-assistant-service-calls)?

**Comment by Floppe** [comment]
> Are you also trying `dev`?
> 
> How are the settings for [Allow the device to make Home Assistant service calls](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Alarm-Control-Panel#allow-the-device-to-make-home-assistant-service-calls)?

I have. On time the alarm page had all buttons grayed out also.

**Comment by edwardtfn** [comment]
1. Was this working fine with previous versions?
2. Do you have more than one alarm entity set to this same panel?
3. Is this happening all the time?
4. Could you please share the attributes of this alarm entity you are using?
5. Anything in your Home Assistant logs (Settings > System > Logs)?
6. Can you see if the automation is triggered when you change it in the panel? Any trace?

**Comment by Floppe** [comment]
1. Yes
2. No
3. Yes
4. `code_format: null
changed_by: Floppe
code_arm_required: false
arm_mode: null
open_sensors: null
bypassed_sensors: null
delay: null
ready_to_arm_modes: away, home
icon: mdi:shield-home
friendly_name: House
supported_features: 11`
5. NSPanel Livingroom: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Alarm settings page: If at step 2: Error executing script. Invalid data for call_service at pos 4: string value is None for dictionary value @ data['code_format']
6. It triggers, but I guess the above message is the culprit when code_format is null.
7. I'm using the "Alarmo" integration. Tried to switch between pincode and password format without success.

**Comment by edwardtfn** [comment]
I've just pushed a fix to this issue on 5. Please update your blueprint and let me know if the main issue reported here was fixed or if you still having something on your logs.

**Comment by Floppe** [comment]
Yes, now it works. Thanks.
