### ISSUE TITLE
`DEV` Not possible to switch from away to home

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1463]
Great. Tell me to stop if I test too much :)

- Alarm page does not update selected mode when changing, but the other panels catches is ASAP on both home & alarm screen 👍 
- **This perhaps not an issue, but also not possible to switch from away to home. Need to disarm first before it accepts a new alarm state. The other way seems to work, home -> away which perhaps is more used.**

_Originally posted by @Floppe in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1456#discussioncomment-7927206_

**Comment by edwardtfn** [comment]
I couldn't duplicate this either.
Are you sure this is not a restriction from your alarm integration?

By the way, have you enabled **[Allow the device to make Home Assistant service calls](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Alarm-Control-Panel#allow-the-device-to-make-home-assistant-service-calls)**?

**Comment by Floppe** [comment]
This seems to be a limitation of Alarmo.
Found in the logs: Cannot go to state armed_home from state arming.

**Comment by edwardtfn** [comment]
So, if that is the case, you should be able to see the same thing with v4.1, not only with v4.2dev.

**Comment by Floppe** [comment]
That's correct. Seems I never tested or noticed that before. My bad.

**Comment by edwardtfn** [comment]
No problem.
Then I will close this, ok? Or still something pending here?
