### ISSUE TITLE
Recover from lost Wi-Fi

### ISSUE THREAD

**Issue by cpw** [Blackymas/NSPanel_HA_Blueprint#1464]
My wifi went down for unrelated reasons a few times today. My NS Panel running v4.0.1 of the blueprint for the past couple of months seems to have _really_ not liked it. I cannot seem to interact with the device in any meaningful fashion - there's no mechanism to restart, reboot or otherwise get the device to start again from the UI on the device. I can't find any documentation on what valid keypresses there might be, but I tried a few of the classics - long press the buttons, etc.

The screen doesn't respond to swipes at all. The time is still updating, but the wifi icon shows an OFFLINE red state. At this point, I think the only viable way to get it to restart is to power down the house, which won't be a popular option and is absurdly untenable in a user product. Perhaps you need to add a default timeout or something so if the WIFI goes away for a short period, it'll reboot after some time? Alternatively, make sure the UI doesn't crash so I can still access things like the settings pages or a reboot button?

Edit: adding HA screenshot - the device is reporting completely offline
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/1217211/8ff4f36f-f764-488f-ac6e-cc42e36b57d9)
![PXL_20231222_200622531.MP.jpg](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/1217211/a9399b07-3ecc-4bbb-8398-2ac49cbde033)

**Comment by edwardtfn** [comment]
If you long press the area where the time is shown, you should get a "Reboot" button.
Could you please try that?

**Comment by edwardtfn** [comment]
By the way, on v4.1, if you hold the right button for 15s it will reboot the panel.

**Comment by cpw** [comment]
Nothing worked for long press. It seems like it was completely frozen. I had to power cycle the breaker to get it to work again..

**Comment by edwardtfn** [comment]
Update to the latest version and you will have the hardware button reset with 15s

**Comment by edwardtfn** [comment]
But I will look for some kind of watchdog also. It's a bit tricky, as ESPHome cannot save all type of data, while we still wanna keep some thing working when the Wi-Fi is out.

**Comment by edwardtfn** [comment]
I've implemented a watchdog system to try to recover from situations like this. This is still in `dev` now, but will be included in the next release soon.
Also, you can use the 15s button press as described above and, as last resource, the reset button bellow the device should work:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/e4a89e11-be46-441c-b3cf-729c16414bfd)

**Comment by edwardtfn** [comment]
- #1556
