### ISSUE TITLE
Validation failed 

### ISSUE THREAD

**Issue by BananaJon** [Blackymas/NSPanel_HA_Blueprint#1467]
Dear all, 

the validation failed, when I tried to Update NASPanel from 4.0 to 4.1.4. 

I have downloaded the latest release of the blueprint from the Github repository.
Then I replaced the existing YAML file "nspanel_blueprint.yaml" in the folder ./config/blueprints/automation/Blackymas with the new version and finally reloaded the automations. 

I then started the validation and the following error occurs: 

````
INFO ESPHome 2023.10.0-dev
INFO Reading configuration /config/esphome/nspanel01.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Detected timezone 'Europe/Berlin'
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

display.nextion: [source /data/packages/566b10a3/./advanced/esphome/nspanel_esphome_core.yaml:753]
  id: disp1
  platform: nextion
  uart_id: tf_uart
  
  [start_up_page] is an invalid option for [display.nextion]. Did you mean [wake_up_page]?
  start_up_page: 8
  on_page: 
    lambda: |-
      static const char *const TAG = "display.disp1.on_page";
      ESP_LOGD(TAG, "Nextion page changed");
      ESP_LOGD(TAG, "New page: %s (%i)" , id(page_names)[x].c_str(), x);
  on_setup: 
    - script.execute: boot_sequence
````

**Comment by edwardtfn** [comment]
```log
INFO ESPHome 2023.10.0-dev
```

Try to update to latest ESPHome.
By the way, we never test against ESPHome dev. 😉

Also, you don't hate to copy `nspanel_esphome.yaml` from GitHub. Just copy this and make the adjustments in the substitutions part: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-First-Steps---Installation-and-Setup#code

**Comment by cis202** [comment]
updating to latest ESPHome solved it for me.

**Comment by BananaJon** [comment]
> updating to latest ESPHome solved it for me.

Yes, for me too. Thx for help
