### ISSUE TITLE
ESPHome version "falling back"

### ISSUE THREAD

**Issue by Der-Sven** [Blackymas/NSPanel_HA_Blueprint#1469]
Hi,
Not sure, if this is an issue or something else, and I have no idea how this is even possible:

I wanted to upgrade from v 4.0.2 to 4.1.4. 
It was not not the first time for me running upgrades on my screen, so everything seemed straight forward.

Only change to previous runs: I used to have a complete .yaml in my esp_home configuration, because of specific wifi settings, which I now included via the !extend command.

In any case: I updated the blueprint, compiled and uploaded the ESPhome. Display showed the correct versions: TFT: 4.0.2, ESPHome: 4.1.4. So I hit the "upload tft" button. It took a while and something got uploaded.
The ESP rebooted and showed:
TTF: 4.0.2, ESPHome: 4.0.2 and could not connect to the blueprint.

This occured mutiple times until I figured out, that it was uploading an old version of the TFT from the old ESPHome config. (different local path)
So I replaced the TFT files in the path of the 4.0.2 version and uploaded:
TFT 4.1.4, ESPHome: 4.0.2

next update of the ESPHome and everyting worked.

Thanks,
Cheers,

Sven

**Comment by edwardtfn** [comment]
I have seen this when the framework is changed using OTA.

Só, as you are coming from a previous version, you probably had `arduino` as framework before. If you find the following lines (recommended for new users), you can either flash via serial or remove those lines and flash it OTA, then the problem will probably be gone.

```yaml
esp32:
  framework:
    type: esp-idf
```

**Comment by edwardtfn** [comment]
Hey @Der-Sven, have you tried the suggestion from my previous message? Please let me know the results.

**Comment by Der-Sven** [comment]
Hey @edwardtfn,

I just updated the panel to the latest ESP-home version, worked without issues.
Also looked into my old yaml, and could not find any reference to the framework (especially not arduino) in there.

As soon as I had the right tft on it and quickly updatedthe ESP, everything was fine.

Solved for me.
