### ISSUE TITLE
Question about setting page remotely or setting wake_up_page

### ISSUE THREAD

**Issue by DozoG** [Blackymas/NSPanel_HA_Blueprint#1471]
Hi Hi,

I am trying to set the display remotely, either from HomeAssistant or in my case through a 'call service' node in node-red.
(So that I can display buttons when someone enters the room, and the home page after a minute or so)

- Is it a suggestion to add a service call to allow HA (N-red) to set a screen?
- I tried to work around it by including a 'customisation' 
 that works, but I would have to add a button for every page I would possibly want my NSPanel to show.
(I am not clever enough to be able to pass a parameter ('home' or 'buttonpage1') to the button call)

My prefered solution would be to have a page_select similar to how we do have a "wake_up page"
You already get the feedback of Current page, why not add a Set-page remote function?

Any other way anyone is doing this?

**Comment by edwardtfn** [comment]
Please take a look at this: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#11-call-certain-pages-directly

**Comment by DozoG** [comment]
My Dear.. that was fast.. I will have a look soon and thank you so much

**Comment by edwardtfn** [comment]
Solved in `dev` with improved documentation.

**Comment by edwardtfn** [comment]
- #1556
