### ISSUE TITLE
Question: Steps to change WiFi

### ISSUE THREAD

**Issue by DaveZoetermeer** [Blackymas/NSPanel_HA_Blueprint#1476]
Ar there steps to change the wifi via de ESP Home integration (with the Blackymas firmware on it). Last time when i changed it in the secrets tab, the panel wouldn't connect anymore and i needed to flash the blackymas firmware on it again, to connect it to the old wifi.

**Comment by edwardtfn** [comment]
Please take a look at this similar case and I can help you if you still needing help: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1465#issuecomment-1868235382

**Comment by DaveZoetermeer** [comment]
I have read them, but here it is only the password. The network name changes also, can I add this to de ota mention and the wifi_ssid like additation?

**Comment by edwardtfn** [comment]
I will add this to the new documentation to be released soon, but you can take a look at that in `dev` and give some feedback: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/dev/docs/howto.md#updating-wi-fi-and-ota-passwords-in-esphome-with-this-project

**Comment by DaveZoetermeer** [comment]
Documentation is good but the issue at my part is that I want to move the device tot another ssid and password. Last time when I changed it in de secrets folder of ESP Home the devices where going offline…

**Comment by edwardtfn** [comment]
I will update the doc to include changing SSID, but the principle is the same, you have to change it and flash to the device while everything is in the old WiFi, otherwise you must flash by serial. 😩

**Comment by edwardtfn** [comment]
Done!
