### ISSUE TITLE
`DEV` The buttons on the climate page apparently no longer exist.

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1481]
so, it looks very good.
At least it looks almost the same as before. The icons now also change

I still have the following questions/suggestions:

- Do you want the custom buttons on the "home" page to be smaller than the predefined buttons below? Many people might also like an adjustment to the item size.
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/139384422/30cd233a-52ed-463a-b1ef-484f3f062a5f)

- **The buttons on the climate page apparently no longer exist. But I think construction is going on there anyway when I look at milestone 4.2.**

- Can you give me the icon-names again, which I can change with the set_component_color service. For the chips it is e.g. icon_top_04. But it also worked for home values 1-3?
```
                                - entity: !input 'home_value03'
                                  icon: !input 'home_value03_icon'
                                  icon_color_rgb: !input 'home_value03_icon_color'
                                  label_color_rgb: !input 'home_value03_label_color'
                                  page: home
                                  component: value03
```

shouldn't it be value03 for example? Unfortunately that doesn't work.

_Originally posted by @kroessig in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/963#issuecomment-1868296186_

**Comment by edwardtfn** [comment]
I've made changes on the page climate on `dev`. Could you please try it again and let me know if you still having this issue?

**Comment by kroessig** [comment]
i tried to install the new dev-version, Validation is OK, but wireless install not:

'''
INFO ESPHome 2023.12.5
INFO Reading configuration /config/esphome/nspanelwoziblueprint.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@dev
INFO Detected timezone 'Europe/Berlin'
INFO Generating C++ source...
INFO Compiling app...
Processing panelwozi (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40405.230623 (4.4.5) 
 - tool-cmake @ 3.16.9 
 - tool-ninja @ 1.10.2 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/panelwozi/src/esphome/components/adc/adc_sensor.o
Compiling .pioenvs/panelwozi/src/esphome/components/api/api_connection.o
Compiling .pioenvs/panelwozi/src/esphome/components/api/api_frame_helper.o
Compiling .pioenvs/panelwozi/src/esphome/components/api/api_pb2.o
Compiling .pioenvs/panelwozi/src/esphome/components/api/api_pb2_service.o
Compiling .pioenvs/panelwozi/src/esphome/components/api/api_server.o
Compiling .pioenvs/panelwozi/src/esphome/components/api/list_entities.o
Compiling .pioenvs/panelwozi/src/esphome/components/api/proto.o
Compiling .pioenvs/panelwozi/src/esphome/components/api/subscribe_state.o
Compiling .pioenvs/panelwozi/src/esphome/components/api/user_services.o
Compiling .pioenvs/panelwozi/src/esphome/components/binary_sensor/automation.o
Compiling .pioenvs/panelwozi/src/esphome/components/binary_sensor/binary_sensor.o
Compiling .pioenvs/panelwozi/src/esphome/components/binary_sensor/filter.o
Compiling .pioenvs/panelwozi/src/esphome/components/button/button.o
Compiling .pioenvs/panelwozi/src/esphome/components/display/display.o
Compiling .pioenvs/panelwozi/src/esphome/components/display/display_buffer.o
Compiling .pioenvs/panelwozi/src/esphome/components/display/rect.o
Compiling .pioenvs/panelwozi/src/esphome/components/esp32/gpio.o
Compiling .pioenvs/panelwozi/src/esphome/components/esp32/preferences.o
Compiling .pioenvs/panelwozi/src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.o
Compiling .pioenvs/panelwozi/src/esphome/components/gpio/switch/gpio_switch.o
Compiling .pioenvs/panelwozi/src/esphome/components/homeassistant/time/homeassistant_time.o
Compiling .pioenvs/panelwozi/src/esphome/components/json/json_util.o
Compiling .pioenvs/panelwozi/src/esphome/components/ledc/ledc_output.o
Compiling .pioenvs/panelwozi/src/esphome/components/logger/logger.o
Compiling .pioenvs/panelwozi/src/esphome/components/md5/md5.o
Compiling .pioenvs/panelwozi/src/esphome/components/mdns/mdns_component.o
Compiling .pioenvs/panelwozi/src/esphome/components/mdns/mdns_esp32.o
Compiling .pioenvs/panelwozi/src/esphome/components/mdns/mdns_esp8266.o
Compiling .pioenvs/panelwozi/src/esphome/components/mdns/mdns_host.o
Compiling .pioenvs/panelwozi/src/esphome/components/mdns/mdns_libretiny.o
Compiling .pioenvs/panelwozi/src/esphome/components/mdns/mdns_rp2040.o
Compiling .pioenvs/panelwozi/src/esphome/components/network/util.o
Compiling .pioenvs/panelwozi/src/esphome/components/nextion/binary_sensor/nextion_binarysensor.o
Compiling .pioenvs/panelwozi/src/esphome/components/nextion/nextion.o
Compiling .pioenvs/panelwozi/src/esphome/components/nextion/nextion_commands.o
Compiling .pioenvs/panelwozi/src/esphome/components/nextion/nextion_component.o
Compiling .pioenvs/panelwozi/src/esphome/components/nextion/nextion_upload_arduino.o
Compiling .pioenvs/panelwozi/src/esphome/components/nextion/nextion_upload_idf.o
Compiling .pioenvs/panelwozi/src/esphome/components/nextion/sensor/nextion_sensor.o
Compiling .pioenvs/panelwozi/src/esphome/components/nextion/text_sensor/nextion_textsensor.o
Compiling .pioenvs/panelwozi/src/esphome/components/ntc/ntc.o
Compiling .pioenvs/panelwozi/src/esphome/components/number/automation.o
Compiling .pioenvs/panelwozi/src/esphome/components/number/number.o
Compiling .pioenvs/panelwozi/src/esphome/components/number/number_call.o
Compiling .pioenvs/panelwozi/src/esphome/components/number/number_traits.o
Compiling .pioenvs/panelwozi/src/esphome/components/ota/ota_backend_arduino_esp32.o
Compiling .pioenvs/panelwozi/src/esphome/components/ota/ota_backend_arduino_esp8266.o
Compiling .pioenvs/panelwozi/src/esphome/components/ota/ota_backend_arduino_libretiny.o
Compiling .pioenvs/panelwozi/src/esphome/components/ota/ota_backend_arduino_rp2040.o
Compiling .pioenvs/panelwozi/src/esphome/components/ota/ota_backend_esp_idf.o
Compiling .pioenvs/panelwozi/src/esphome/components/ota/ota_component.o
Compiling .pioenvs/panelwozi/src/esphome/components/output/automation.o
Compiling .pioenvs/panelwozi/src/esphome/components/output/float_output.o
Compiling .pioenvs/panelwozi/src/esphome/components/resistance/resistance_sensor.o
Compiling .pioenvs/panelwozi/src/esphome/components/restart/button/restart_button.o
Compiling .pioenvs/panelwozi/src/esphome/components/rtttl/rtttl.o
Compiling .pioenvs/panelwozi/src/esphome/components/script/script.o
Compiling .pioenvs/panelwozi/src/esphome/components/select/select.o
Compiling .pioenvs/panelwozi/src/esphome/components/select/select_call.o
Compiling .pioenvs/panelwozi/src/esphome/components/sensor/automation.o
Compiling .pioenvs/panelwozi/src/esphome/components/sensor/filter.o
Compiling .pioenvs/panelwozi/src/esphome/components/sensor/sensor.o
Compiling .pioenvs/panelwozi/src/esphome/components/socket/bsd_sockets_impl.o
Compiling .pioenvs/panelwozi/src/esphome/components/socket/lwip_raw_tcp_impl.o
Compiling .pioenvs/panelwozi/src/esphome/components/socket/lwip_sockets_impl.o
Compiling .pioenvs/panelwozi/src/esphome/components/socket/socket.o
Compiling .pioenvs/panelwozi/src/esphome/components/status/status_binary_sensor.o
Compiling .pioenvs/panelwozi/src/esphome/components/switch/automation.o
Compiling .pioenvs/panelwozi/src/esphome/components/switch/switch.o
Compiling .pioenvs/panelwozi/src/esphome/components/template/binary_sensor/template_binary_sensor.o
Compiling .pioenvs/panelwozi/src/esphome/components/template/number/template_number.o
Compiling .pioenvs/panelwozi/src/esphome/components/template/select/template_select.o
Compiling .pioenvs/panelwozi/src/esphome/components/template/switch/template_switch.o
*** [.pioenvs/panelwozi/src/esphome/components/template/text/template_text.o] Source `src/esphome/components/template/text/template_text.cpp' not found, needed by target `.pioenvs/panelwozi/src/esphome/components/template/text/template_text.o'.
========================= [FAILED] Took 89.16 seconds =========================
'''

**Comment by kroessig** [comment]
ok, update sucessfull.
but.... have you fundamentally changed the function of the two buttons?
I linked an automation to each button and was able to control my offset with the automation (example below).
In the "old" version I was able to change the value between -5 and 5 by pressing the same button multiple times.
Now i deactivate the automation by pressing the button.... 

```
alias: Korrektur Heizung +1
description: ""
trigger: []
condition:
  - condition: numeric_state
    entity_id: number.luxtronik2_heating_target_correction
    below: 5
action:
  - service: number.set_value
    target:
      entity_id: number.luxtronik2_heating_target_correction
    data_template:
      value: >-
        {{ (states('number.luxtronik2_heating_target_correction') |
        float(default=0)) + 1 }}
mode: single
```

**Comment by edwardtfn** [comment]
Yes, the default behavior of automations associated to buttons has changed, but you have a selector on the blueprints to adjust that.

Please take a look at this discussion: https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/810#discussioncomment-7596539

**Comment by edwardtfn** [comment]
Ideally you should use a script for this, as a script is basically an automation without a trigger (like in your case), but is you wanna keep it as an automation, just change the setting in the Blueprint and it will work just like before.

**Comment by kroessig** [comment]
;-)  
Of course I didn't look at the bottom of the blueprint. now everything works fine!!!!
