### ISSUE TITLE
Display entity values on a page

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1483]
> Of course, its impossible to serve every desire.
> 
> Having 4 or 5 generic items would be a great start, but having the possibility to change the main information (the clock for now) could be great.
> 
> In my case, I have this kind of visualisation on my HA instance :
> 
> <img alt="Capture d’écran 2023-12-19 à 18 00 08" width="473" src="https://private-user-images.githubusercontent.com/988914/291659500-1a621706-5e34-47c3-a935-e66512bfbb11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MTMzNTIsIm5iZiI6MTcwMzcxMzA1MiwicGF0aCI6Ii85ODg5MTQvMjkxNjU5NTAwLTFhNjIxNzA2LTVlMzQtNDdjMy1hOTM1LWU2NjUxMmJmYmIxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QyMTM3MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDUxMzRjYzY0NGEwOWM0MWViNTQ5MDM5MTA3ZmZhMjY0ZDJmYWFmMTUwNmI2YTRlYjYyZmY1ZDY1MzRjYzllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kVXBKnIbnnwDf4uIS8_zDM73rqImBRsjlo_k3XJzLL8">
> I see that kind of visualisation really often. Having this as a screen with a way to customize the value inside every bubble would be perfect. But like you said we can't do the dream of every user ;).

This would be great! I have the same board so to have this on a page would be awesome.

**In addition to this, Is it possible to display entity values on a page? For example car battery percentage is an entity. It would show as a button with label and value**

Thanks
Mike

_Originally posted by @matchermike1981 in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/168#issuecomment-1870643668_

**Comment by edwardtfn** [comment]
@matchermike1981, do you mean a page with a single value in the centre?

**Comment by matchermike1981** [comment]
> @matchermike1981, do you mean a page with a single value in the centre?

Well, I have loads of entities that have values. Battery charge percentage. Charging mode (fast, eco, eco+), current electricity cost, kwh exported, kwh solar consumed.

So maybe a way to display multiple of these on a page. As a table, Or Like an entity card in ha, with the entry labels in one column and values in the next.

**Comment by matchermike1981** [comment]
![Screenshot_20231227_220749_Home Assistant](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/132230759/ab62b9fd-30ab-4865-9bfb-525b7eb62281)
![Screenshot_20231227_220904_Home Assistant](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/132230759/3ab84593-c21f-4c2e-a682-a4131c7eb0a9)

**Comment by edwardtfn** [comment]
Duplicated with #1484

**Comment by edwardtfn** [comment]
- #1556
