### ISSUE TITLE
@matchermike1981, do you mean a page with a single value in the centre?

### ISSUE THREAD

**Issue by matchermike1981** [Blackymas/NSPanel_HA_Blueprint#1484]
@matchermike1981, do you mean a page with a single value in the centre?

_Originally posted by @edwardtfn in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1483#issuecomment-1870653391_

Well, I have loads of entities that have values. Battery charge percentage. Charging mode (fast, eco, eco+), current electricity cost, kwh exported,      kwh solar consumed.

So maybe a way to display multiple of these on a page. As a table, Or Like an entity card in ha,  with the entry labels in one column and values in the next.

**Comment by edwardtfn** [comment]
There are entities pages for this:

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/d2844f05-df20-4e42-8f0a-873221b01613)

**Comment by matchermike1981** [comment]
> There are entities pages for this:
> 
> ![image](https://private-user-images.githubusercontent.com/94725493/293108789-d2844f05-df20-4e42-8f0a-873221b01613.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MTgyMDEsIm5iZiI6MTcwMzcxNzkwMSwicGF0aCI6Ii85NDcyNTQ5My8yOTMxMDg3ODktZDI4NDRmMDUtZGYyMC00ZTQyLThmMGEtODczMjIxYjAxNjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDIyNTgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMTUyNDkyODkwOWMzZjJmOWRkNGNlM2MyZTNlY2JkODlkNzI4NTgxYjJiYmVhZDMyYWJlOTMyNjY2ZGM0MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GGrNaVdhde0qH2EwwC0d_9s4_WrojOiwIScLaarsGgc)

Then please ignore my question sorry!

That looks exactly what I want. I clearly haven't dug into the config far enough.

Thanks for your prompt replies

**Comment by edwardtfn** [comment]
I'll update the readme on the front page to include this. 😉

**Comment by edwardtfn** [comment]
- #1556
