### ISSUE TITLE
Pcb speaker

### ISSUE THREAD

**Issue by Gertc555** [Blackymas/NSPanel_HA_Blueprint#1485]
Is it possible to utilise the on board speaker to play notifications? I know its not a good quality speaker but could be useful to get alarms or tunes as notifications

**Comment by edwardtfn** [comment]
Please take a look at this: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#12-play-rtttl-sound

**Comment by edwardtfn** [comment]
Hi @Gertc555, was the what you looked for?
