### ISSUE TITLE
Unavailable climate

### ISSUE THREAD

**Issue by misery** [Blackymas/NSPanel_HA_Blueprint#1486]
Hi,

one of my climate was offline (no battery) and it shows no information about the name. So I have two really minor feature requests. :-)

* Show the name of the climate on the button
* Do not show -999 as tempature if climate is offline

![heating](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/50925/e4549549-7ab8-49fb-8098-16d00e5c611c)
![overview](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/50925/13021de0-c0ce-4ac3-a611-5323ce33d3ff)

**Comment by edwardtfn** [comment]
About the climate page, I believe I've a solution for this in `dev`, but for the button pages, I don't see why the button label isn't shown.
Do you still having an entity on this state or can you force that again? If so, could you please take a screenshot of the attributes on the **Developers Tools** page on the **States** tab?

**Comment by misery** [comment]
Of course. You mean the climate?

![Screenshot_20240101_225429_Home Assistant_1](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/50925/1c175aca-9b52-4fb7-8bb2-583dda973aaa)

**Comment by edwardtfn** [comment]
This is exactly what I've asked for. Thanks!
I cannot duplicate this with v4.2dev... I eill try it with the released version, but most likely this is already fixed in `dev`.

**Comment by edwardtfn** [comment]
Ok, looks like this was fixed on `dev`. I will close it, but please feel  to reopen if you find this error when 4.2 is released (or if you test it earlier).

**Comment by misery** [comment]
Thanks, both is fixed with v4.2 for me!
