### ISSUE TITLE
Firmware  update stop at 5%

### ISSUE THREAD

**Issue by iPROSHOPStudio** [Blackymas/NSPanel_HA_Blueprint#149]
![](https://user-images.githubusercontent.com/87064512/210236442-d75f0890-af3c-404c-9b1c-e3a817e0bd97.jpg)

**Comment by iPROSHOPStudio** [comment]
![Screenshot_20230102_200837_Gallery](https://user-images.githubusercontent.com/87064512/210236442-d75f0890-af3c-404c-9b1c-e3a817e0bd97.jpg)

**Comment by iPROSHOPStudio** [comment]
Now is done after reflash original firmware

**Comment by Blackymas** [comment]
so all is running?

**Comment by iPROSHOPStudio** [comment]
> so all is running?

Yes problem solved
Thank you.

**Comment by Blackymas** [comment]
nice - not sure but you have the youtube channel right?

**Comment by iPROSHOPStudio** [comment]
Yes i will upload video in Thai language

**Comment by Blackymas** [comment]
wow thanks - pls share the Link ;)

**Comment by Blackymas** [comment]
this guy is interested in the US version llt you can finish a version together and I'll include it.


https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/130

**Comment by iPROSHOPStudio** [comment]
> wow thanks - pls share the Link ;)

https://youtu.be/LlZrUMYau_w

**Comment by Blackymas** [comment]
super thanks - i like the video even if i didn't understand a word except "blackymas" ;)

Is it ok if I link the video here on Github?

**Comment by iPROSHOPStudio** [comment]
Alright, no problem, glad you like the video.😍

**Comment by Blackymas** [comment]
vieles scheint aber zu passen in der US version -  siehe hier 

https://www.youtube.com/watch?v=LlZrUMYau_w&t=408s


and thanks for the great Video ;)
