### ISSUE TITLE
`DEV` When I turn on time on screensaver in the blueprint the ns panel resets

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1492]
Tried the new files with the "rebuild upload tft" and now ik can update the tft with dev branch installed.
**Only thing is that the screen saver (time) not working. When i turn it on in the blueprint the ns panel resets.**

_Originally posted by @Mauricewillemstein in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1487#issuecomment-1872470391_

**Comment by edwardtfn** [comment]
Fixed!

**Comment by Mauricewillemstein** [comment]
Thx, Will give it a try

**Comment by Mauricewillemstein** [comment]
Tried it, the ns panel no more resets. That is great, but the display is not showing the time.
My settings are:
Time out dimming: 60s
Time out page: 30s
Time out sleep: 70s

**Comment by edwardtfn** [comment]
On the device page you have to set the brightness for the screen saver page. It must be grater than 0.

**Comment by Mauricewillemstein** [comment]
The brightness sleep is on 83%

**Comment by edwardtfn** [comment]
Ok, what about font color, set on the Blueprint right after the time toggle input? It must be diferent than black (I have to change this)

**Comment by Mauricewillemstein** [comment]
I did change it to blue

**Comment by edwardtfn** [comment]
Can you see the time in the screen now?

**Comment by edwardtfn** [comment]
Which TFT version are you using? And which model (EU, US or US Landscape)?

**Comment by Mauricewillemstein** [comment]
I am using the eu model, and the tft file from the dev branch

**Comment by edwardtfn** [comment]
Could you please update your system and try again?

**Comment by Mauricewillemstein** [comment]
Hi, I tried it and the screensaver is working fine now. It shows the time now.
Thx alot
