### ISSUE TITLE
Garbage collection reminder / Müllkalender Erinnerung auf dem Homescreen als Notfication

### ISSUE THREAD

**Issue by MarkuZP** [Blackymas/NSPanel_HA_Blueprint#150]
Garbage collection reminder / Müllkalender Erinnerung auf dem Homescreen als Notfication wie in Lovelace.

wäre cool!

**Comment by Blackymas** [comment]
hallo Notification ist schon in Arbeit und Extra Müll auf der Roadmap :)

ich schließe das Ticket da es bereits die Anfragen gab :)
