### ISSUE TITLE
Notification Icons Relocation

### ISSUE THREAD

**Issue by Theron21** [Blackymas/NSPanel_HA_Blueprint#1501]
I am using the US Portrait orientation.  When viewing a notification on the screen, the placement of the check and X buttons are directly above the NSPanel physical buttons.  From a useability standpoint, a user unfamiliar with the interface may press the physical button to dismiss the notification.    I have experienced this a few times with users.  Recommend to relocate the icons to another location such as the top of the screen, allow a configuration to customize the icon placement, or redesign the icons so it is clear that those options are buttons.  Thank You

**Comment by edwardtfn** [comment]
That makes total sense. Thanks for the feedback and ideas.
What about the hardware buttons acting like "Check" and "Cancel" when that page is shown? Would that be an option?

**Comment by Theron21** [comment]
I think using the Physical buttons in this case is a great idea.  Thank You for considering this change and creating such an awesome product.  Moving to your platform fixed all my performance issues and made the panels so much more capable and useable.
