### ISSUE TITLE
Display the temperature set in the thermostat on the home screen

### ISSUE THREAD

**Issue by DerT94** [Blackymas/NSPanel_HA_Blueprint#1503]
Hello,

I have installed a panel as a test and also installed the Climate heater addon.
This also works so far.
Now I would like to see the target temperature on the home screen.
How can I achieve this?

**Comment by edwardtfn** [comment]
Do you wanna see the target temperature or the current temperature?

For the current temperature, just assign the new climate entity as the main climate of your panel and that will be shown on the home page.
For the target temperature, you probably have to create a template sensor to extract that info from the attributes and then use that new sensor in one of the 3 values you can display in the Home page.

**Comment by DerT94** [comment]
The Target temp.
How can I create a template sensor and extract the value?

**Comment by edwardtfn** [comment]
On your Home Assistant, go to **Settings** > **Devices & Services**, select the tab **Helpers** and click **Create helper**. then select the type **Template** and fill the template filter with something like this (please replace to your climate entity id accordingly):

`{{ state_attr('climate.kitchen_thermostat', 'temperature') }}`

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/087358c7-35a8-457c-86d6-d08057b03a72)

This is basically extracting the attribute `temperature` from your climate. You can see a preview on the bottom of that dialog.

When you submit, you will have a new sensor in your Home Assistant and you can assign that to any of the values fields on the Home Page.

**Comment by DerT94** [comment]
Thank youm that worked. :)
