### ISSUE TITLE
`DEV` I think there are some weirdness with the chips

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1504]
I have short on time, but a fast test and seems to work quite ok. **I think there are some weirdness with the chips. Chip 4 is blue for me now. Chip 3 perhaps wrong.. seems to trigger for chip 1 instead.**

Entities, QR and Alarm panel okay.

How about the climate page. I did see a commit referencing it (and dual state), but how if possible should I set correct target temp sensor? Now it uses 48.8 for heat when I would want 19. (We have -28 Celsius outside so that's why radiator water is heating to 49)

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/238729/15c69c55-a264-42b1-a76d-f7dfc59909e9)

Later I would want to try dual state also for tap water.

_Originally posted by @Floppe in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1456#discussioncomment-7991082_

**Comment by Floppe** [comment]
Duh, correction.. There was a mistake in my blueprint there for one NS panel which happened to be the one I tested. So the chips 1 & 3 do work at least when triggered from HA. Sorry, my bad (again) =P
