### ISSUE TITLE
NSPanel Brightness slider on nspannel page

### ISSUE THREAD

**Issue by DerT94** [Blackymas/NSPanel_HA_Blueprint#1506]
Hey,

is there a way to add the NSPanel Brightness Setting as an slier to one button page?
Like an dimmable light?

**Comment by andythomas** [comment]
You can do a long press on the time on the home screen to access this setting from the panel. That is (supposedly) even quicker. Could you maybe elaborate on your use case?

**Comment by DerT94** [comment]
Yes and thanknyou :)
