### ISSUE TITLE
Feature request: show hardware button blue indicator from different pages

### ISSUE THREAD

**Issue by shing6326** [Blackymas/NSPanel_HA_Blueprint#1507]
Hello, I have a use case that I always show my entity page as my home page, and would like to know the status of my hardware button, is there any chance to show the hardware button indicator from entity and button pages? Thanks

**Comment by edwardtfn** [comment]
I like the idea, but some pages are quite full and will be quite hard to find space for those bars, even harder if we try to add the label.
But I will take a look at this later.

**Comment by edwardtfn** [comment]
It is available on `dev` and will be part of the next release.
