### ISSUE TITLE
Boot to fallback mode after x retries

### ISSUE THREAD

**Issue by neuhausf** [Blackymas/NSPanel_HA_Blueprint#1508]
Hi @edwardtfn
I owe you a thank you for the good fallback thermostat support!
There is "just" one slight issue:
1. Power outage
2. HA down / wifi down
3. Panel boots up, can't find wifi/HA
4. retries infinitely

Could you **skip to fallback mode after 10 retries**? Or place a button like "fallback" on the init screen (like the button "reboot")?

**Comment by edwardtfn** [comment]
This is already part of v4.2 which still in `dev` but might be released very soon. 😉

**Comment by edwardtfn** [comment]
- #1556
