### ISSUE TITLE
Temperature shows internal tempsensor insteat of  my sensor

### ISSUE THREAD

**Issue by MarkuZP** [Blackymas/NSPanel_HA_Blueprint#151]
Hallo, die Temperatur auf der Startseite zeigt scheinbar den internen ungenauen Sensor an obwohl ich meinen externen Aussenfühler angegeben hatte.

**Comment by Blackymas** [comment]
Ja aktuell ist das so korrekt wir nutzen nur den Internen Sensor für interne Temperatur.

Dein Augen sensor wird neben den Wetter Icon angezeigt.

Aktuell haben wir keine option einen Sensor für die Interne temp zu hinterlegen.


Du kannst aber über HA -> Devices -> NSPanel eine Temperatur Korrektur machen dann passt auch der interne sensor wenn du das anpasst.

Ich habe aktuell 6 Stück im Einsatz und die Werte passen alle im vergleich zu anderen Temp sensor.

Daher einfach die Korrektur machen.

**Comment by MarkuZP** [comment]
Ah, verstehe! Ich hatte das in Deiner Beschreibung so verstanden das der Ausstemp Sensor vorne in gross angezeigt wird.
Würde auch  mehr Sinn ergeben. Danke!

**Comment by Blackymas** [comment]
kein Problem

generell wurde auch hier darüber gesprochen und ist in der roadmap

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/119
