### ISSUE TITLE
`DEV` The entity which doesn't have an icon would automatically assigned

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1512]
there are some mirror issues on my test.
1. **the entity which doesn't have an icon would automatically assigned. I cannot find a way to not show the icon**
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/42719827/430d2b58-f7ec-4637-ab23-dd12a56facfc)

_Originally posted by @shing6326 in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1447#discussioncomment-7998660_

**Comment by edwardtfn** [comment]
This was kind of intentional. It will always use the icon set in the blueprint, but if nothing is set, now it looks for an icon in the attributes and, is still not set, it will use the default icon for that domain (this is new).

Don't you liked that? And can you live with that?

**Comment by shing6326** [comment]
Hello @edwardtfn , this doesn't affect anything, let's leave it. Thanks for your prompt response 👍
