### ISSUE TITLE
`DEV` The temperature mark seems not in a right place

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1514]
2. **the temperature mark seems not in a right place**
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/42719827/10dd4518-71cd-4332-be44-b18a196f15f6)

_Originally posted by @shing6326 in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1447#discussioncomment-7998660_

**Comment by edwardtfn** [comment]
This is intentional. The slider was split in 2, so the higher part will be used for heater, the lower side for cooling and you can have dual systems where both cooling and heating targets/sliders are shown at the same time.

**Comment by shing6326** [comment]
Thanks for the explaination, thats fine
