### ISSUE TITLE
Weather Pages are empty

### ISSUE THREAD

**Issue by MarkuZP** [Blackymas/NSPanel_HA_Blueprint#152]
When I press on Weather icon the forecast are empty°

**Comment by naofireblade** [comment]
See #140

**Comment by Blackymas** [comment]
hi - naofireblade has already sent the correct link.

Siet neusten hat HA das default weather umbenannt und deshalb geht es nicht - wir werden zeitnahe auch dafür eine Lösung finden - sonst wie bereits gepostet einfach umbenennen

If you use Accuweather make sure you use the correct entity name and that weather forcast is enabled.

**Comment by tikismoke** [comment]
@MarkuZP I also need to rename it from weather.maison to weather.hole to make it work.

**Comment by MarkuZP** [comment]
Thanks a lot! its working!

**Comment by Blackymas** [comment]
thanks for feedback :)

**Comment by Blackymas** [comment]
Hallo,

haben im neuen Release das Problem behoben

https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.0.0
