### ISSUE TITLE
Stuck on boot screen after recent update 

### ISSUE THREAD

**Issue by raindog68** [Blackymas/NSPanel_HA_Blueprint#1523]
Hi I'm getting this error in HA and TFT is stuck on loading screen

(automation.******_configuration) has an action that calls an unknown service: esphome.nsentry_send_command_font_color

I've made no changes to the configuration?

**Comment by edwardtfn** [comment]
On that load screen which versions are shown for TFT, ESPHome and Blueprint?

**Comment by raindog68** [comment]
![8514690524681829418](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/40220928/ef230652-536d-48fe-9c43-1c0eca88b88b)

**Comment by edwardtfn** [comment]
Ok.
When you open the automation using the Blueprint, in the comments at the beginning, is it also showing v4.1.4?

**Comment by edwardtfn** [comment]
If blueprint is v4.1.4 and panel selection is correct, please try the following:
1. On Home Assistant, go to **Settings** > **Devices & Services** > **ESPHome** and click the 3-dot menu related to your panel
2. Select **Delete** or **Remove**
3. Restarts Home Assistant
4. Go back to **Settings** > **Devices & Services**
5. Add your panel back to Home Assistant:
    - If your panel is detected, just follow the steps to configure it, otherwise:
    - Click **Add integration**, select **ESPHome** and enter your panel's hostname or IP address.
7. Follow the steps to configure it
8. Go back to the automation and make sure the correct panel is selected (very first input).

**Comment by raindog68** [comment]
Ok thank-you I will try that when I'm home this evening..will let you know either way, cheers
