### ISSUE TITLE
Can't see the NS panel in the blueprint

### ISSUE THREAD

**Issue by spoontamper** [Blackymas/NSPanel_HA_Blueprint#1526]
Hi All,

I installed the blueprint and add a new device in ESPhome but I can choose the spaniel device in the blueprint only my D1 mini that I use for the temperature of my aquarium.

Does any else have this issue?
CHeers
Frans

**Comment by edwardtfn** [comment]
Can you see your panel under **Settings** > **Devices and Services** > **ESPHome **?

**Comment by spoontamper** [comment]
> Can you see your panel under **Settings** > **Devices and Services** > **ESPHome**?

No I can't

**Comment by edwardtfn** [comment]
Try to add it manually:
1. Go to **Settings** > **Devices and Services**
2. Click **Add integration**
3. Select **ESPHome**
4. Add your device hostname or IP address (you should be able to see this on it's boot screen)
5. Follow the steps from Home Assistant

**Comment by spoontamper** [comment]
> Try to add it manually:
> 
> 1. Go to **Settings** > **Devices and Services**
> 2. Click **Add integration**
> 3. Select **ESPHome**
> 4. Add your device hostname or IP address (you should be able to see this on it's boot screen)
> 5. Follow the steps from Home Assistant

So I have to add the device in esphome and flash the panel with the standard firmware and then find it. And after that use the blueprint?

**Comment by edwardtfn** [comment]
> So I have to add the device in esphome and flash the panel with the standard firmware and then find it. And after that use the blueprint?

That's right.

**Comment by edwardtfn** [comment]
Is it working now?

**Comment by spoontamper** [comment]
I haven’t tried it yet. I’ll give it a go this weekend
