### ISSUE TITLE
Cover battery value not shown (I use Ikea roller blind too)

### ISSUE THREAD

**Issue by MarkuZP** [Blackymas/NSPanel_HA_Blueprint#153]
Cover battery value not shown (I use Ikea roller blind too)

**Comment by Blackymas** [comment]
strange - pls open cover setting menu and than open in automation point traces.

See 
https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(DE)-HowTo-%7C-Alle-wichtigen-Dinge-die-man-wissen-sollte

**Comment by MarkuZP** [comment]
Hmm ich verstehe nicht so ganz, was ich tun soll. Sorry! Irgendwo hier?
<img width="1721" alt="Bildschirm­foto 2023-01-03 um 17 00 49" src="https://user-images.githubusercontent.com/109298227/210394480-89c6ad83-8126-46ad-9bb6-16d38b3e4dbe.png">

**Comment by MarkuZP** [comment]
Hilft das?

**Comment by MarkuZP** [comment]
Das ist der Screenshot direkt nach dem ich die Taste gedrückt habe um ins Rollo Menü zu kommen (longpress)
<img width="1787" alt="Bildschirm­foto 2023-01-03 um 19 22 17" src="https://user-images.githubusercontent.com/109298227/210418104-7c7bbb17-21fd-4222-9ef8-786938a88c01.png">

**Comment by Blackymas** [comment]
danke sieht besser aus ist aber noch der falsche Zeitstempel.

- Cover ist der 5 Punkt (erster roter Kasten)

- 2 roter Kasten prüft ob er in der Entity das Attribute Battery findet

- 3 roter Kasten setzt das Baterrie Icon

![Bildschirmfoto 2023-01-03 um 19 44 59](https://user-images.githubusercontent.com/41958506/210421493-8bb2a5b0-7a53-446e-9774-e064b6946e7b.png)


Bitte Prüfe auch ob bei der Entity auch das Attribute da ist kannst du hier machen. Schicke mir dann von beiden ein screen

![Bildschirmfoto 2023-01-03 um 19 48 56](https://user-images.githubusercontent.com/41958506/210422124-b791906c-8332-4c7e-820b-83ce90cd322a.png)

**Comment by MarkuZP** [comment]
Ah, okay jetzt raffe ich es langsam...

Danke!

Hier die Screenshots.
<img width="1509" alt="Bildschirm­foto 2023-01-03 um 20 11 24" src="https://user-images.githubusercontent.com/109298227/210426528-0a0d364f-0f3b-4c9a-aa1c-ffc1eea72966.png">


Meine Ikea Fyrtur Rollos haben ne Batterie Entity aber das Atrribut wird nicht wie bei Dir angezeigt.
<img width="793" alt="Bildschirm­foto 2023-01-03 um 20 14 26" src="https://user-images.githubusercontent.com/109298227/210426503-3fb7f5c7-e92b-4df2-b331-e8d793
<img width="1501" alt="Bildschirm­foto 2023-01-03 um 20 12 16" src="https://user-images.githubusercontent.com/109298227/210426572-9874b381-1c0d-4bd3-8097-bdbe7d1a680b.png">
023c22.png">

**Comment by MarkuZP** [comment]
<img width="793" alt="Bildschirm­foto 2023-01-03 um 20 14 26" src="https://user-images.githubusercontent.com/109298227/210426658-4466d762-6c76-430d-b229-dc24c35eee4c.png">

**Comment by MarkuZP** [comment]
<img width="984" alt="Bildschirm­foto 2023-01-03 um 20 23 07" src="https://user-images.githubusercontent.com/109298227/210426845-2e36639c-44df-4094-9be5-0b683b8d2ac8.png">

**Comment by MarkuZP** [comment]
wird in HA als sensor angezeigt

**Comment by Blackymas** [comment]
genau das ist das Problem - scheint das via ha zigbee anders zu sein. Ehrlich gesagt für mich auch falsch weil sauber und richtig wäre den Batterie Status auch in die Entity unter Attribute zu setzen da es ja ein Attribute des Gerätes ist.


Das bekomme ich auch so auf die schnelle nicht geändert - vllt wäre das aber mal ein request seitens HA Zigbee wert - weil wie gesagt ich finde die Lösung nicht 100% richtig und Z2M löst das besser

**Comment by MarkuZP** [comment]
Verstehe! Und bei Dir läuft es weil Du NICHT HA Zigbee benutzt? Wie machst Du die Anbindung a HA denn?

Danke für die Hilfe!!!

**Comment by MarkuZP** [comment]
Verstehe! Und bei Dir läuft es weil Du NICHT HA Zigbee benutzt? Wie machst Du die Anbindung a HA denn?

Danke für die Hilfe!!!

**Comment by MarkuZP** [comment]
reicht es zigbee2mqtt zu installieren?

**Comment by Blackymas** [comment]
ja du musst es installieren und matt broker danach wird das automatisch an HA übergeben

du musst dann natürlich die Geräte von HA Zigbee löschen und auf Z2m neu anlernen.

Es gibt einige Tolle Videos dazu

https://www.youtube.com/watch?v=z7d0OQjSiOI

auch viele vergleiche wo Z2M am besten abschließt. Wobei das jeder selbst entscheiden sollte


https://www.youtube.com/watch?v=RWzzNe5gm5s

**Comment by MarkuZP** [comment]
Das versuche ich mal! Danke für die vielen Tipps!

**Comment by MarkuZP** [comment]
Hast Du denn einen extra Zigbee USB Stick laufen oder reicht hier auch die Ikea Traedfri Bridge?

**Comment by MarkuZP** [comment]
Hmm. hab jetzt auch den zigbee Stick am Start mit Zigbeee2Mqtt und so. Läuft auch, Rollos erkannt aber im NS Panel werden (obwohl die entitäten neu sind) keine Battery Status angezeigt. Ich habe auch wieder das Problem dass die Seiten unvollständig angezeigt werden...

**Comment by MarkuZP** [comment]
Also ich bekommen das einfach nicht hin! 👎 -( . Ich habe jetzt den Zigbee USB Stick 3 plus von Sonoff und mit der Firmware von koenk geflasht. Zigbee2MQTT am Start und die alten Devices von der Ikea Bridge deaktiviert. Der Batteriestatus wird trotzdem immer als separater Sensor angezeigt und nicht als Attribut wie bei Dir. Welche Zigbee Bridge benutzt du denn?
<img width="1126" alt="Bildschirm­foto 2023-01-09 um 12 40 19" src="https://user-images.githubusercontent.com/109298227/211300549-3571bd55-7cb6-49ba-aec6-b72bd0736e52.png">

**Comment by Blackymas** [comment]
welche Version hast du vin Z2M - ich müsste prüfen ob ich das aktuellste habe und ob sich da was geändert hat

**Comment by MarkuZP** [comment]
Hallo, ich habe die neueste Current version: 1.29.2-1 und gestern noch mal alle Rollos und Ikea Repeater neu erkennen lassen.  

In der Doku zu Z2M steht dazu:
<img width="1571" alt="Bildschirm­foto 2023-01-15 um 20 25 05" src="https://user-images.githubusercontent.com/109298227/212655137-a934d162-5d5b-4dd9-8342-f4992b8c9ede.png">


Es ist einfach KEIN Attribut mehr immer ein extra sensor.
<img width="1213" alt="Bildschirm­foto 2023-01-15 um 20 18 20" src="https://user-images.githubusercontent.com/109298227/212655161-cfe114ab-4e37-45ad-bc22-4c6cd9373672.png">

**Comment by Blackymas** [comment]
sobald ich zeit finde prüfe ich es

**Comment by MarkuZP** [comment]
Danke Dir! Habe erstmal ne kleine Donation gemacht via paypal für die gute Arbeit! Danke!

**Comment by Blackymas** [comment]
Danke habe ich schon gesehen ;)

**Comment by MarkuZP** [comment]
> sobald ich zeit finde prüfe ich es

Hey, hier gibt noch nichts Neues ne?
Läuft wie gesagt mit dem Zigbee2Mqtt auch nicht  bei mir.

**Comment by Blackymas** [comment]
bin leider noch nicht dazu gekommen weil wir release 3.1.0 fertig gemacht haben - ih hoffe ich komme die Tage dazu

**Comment by MarkuZP** [comment]
Kein Problem, das update ist viel wichtiger! Wäre toll wenn es irgendwann mal funktionieren würde.

**Comment by Blackymas** [comment]
@MarkuZP hab mal die aktuellste Version installiert bei mir sieht es trotzdem noch etwas anders aus
![Bildschirmfoto 2023-02-06 um 00 43 12](https://user-images.githubusercontent.com/41958506/216852820-61d360db-e1bc-43e9-af9a-5608682f0431.png)

Hab den wert immer noch

**Comment by MarkuZP** [comment]
Strange, liegt es evtl. an einer andere Version oder Revision der Ikea Rollos? Meine sind schon nen Tick älter. Hast Du auch Fyrtur?

**Comment by Blackymas** [comment]
ja und auch schon eine weile bei uns - weis nicht ob das erst auftritt wenn man es neu anlernt

**Comment by Blackymas** [comment]
also ich konnte nun das problem finden hier Scheit z2m unterschiedliche dinge zu machen. ich habe jetzt auch ein Rollo was battery als extra sensor hat.

ich muss schauen wie ich das einbauen kann, weil das nicht so einfach umsetzbar ist

**Comment by MarkuZP** [comment]
Cool, aber dass Du das aber immer noch verfolgst! Ich habe mir noch zwei weitere Fyrtur gekauft. Mal sehen wie die sich anmelden an Z2M. Evtl ist das ja auch ne Firmwarefrage der Ikea Geräte...!?

**Comment by Blackymas** [comment]
naja es steht immer noch auf meiner Liste XD

**Comment by edwardtfn** [comment]
Sorry for switching to English here, but it would be hard for me to write in German.
Just trying to add to the discussion, I also have a few IKEA covers, all connected thru ZHA, and none of those have battery as attributes.

**Comment by MarkuZP** [comment]
It's working with 3.3 :-).

Es geht jetzt!! Super, danke Euch!!!
