### ISSUE TITLE
`Dev` Button active indicator mismatch for button 1/2 

### ISSUE THREAD

**Issue by bluefoxlee** [Blackymas/NSPanel_HA_Blueprint#1533]
Button active indicator bar mismatch for button 1/2. 
Press button 1, light on button 2 bar.

TFT Nspanel_CJK_us_land ver: 4.2dev4

![IMG_0570](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/894044/161c99de-e8c0-4bec-9f36-af8a255e2751)

_Originally posted by @bluefoxlee in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1453#issuecomment-1874492101_

**Comment by edwardtfn** [comment]
Fixed!
