### ISSUE TITLE
`DEV` Buttons pages 2/3/4 - Long press not working

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1534]
Nspanel US

4. Button page 2/3/4. Cover adjustment (long press) is not working. short click to open/close works fine.
5. Button page 2/3/4. Climate/Fan/Lights adjustment (long press) will jump back to page 1 climate/Fan/Lights.

_Originally posted by @bluefoxlee in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1453#issuecomment-1874490769_

**Comment by edwardtfn** [comment]
@bluefoxlee, can you see any error on the Home Assistant logs (**Settings** > **System** > **Logs**) when you long press the cover button on pages 2/3/4?

The item 5 I could duplicate here, but not the item 4. 😞

**Comment by edwardtfn** [comment]
Ok, I think I found the issue... Working in a fix now.

**Comment by edwardtfn** [comment]
I believe this is fixed now.
Could you please update your system (including TFT) and let me know the results?

**Comment by bluefoxlee** [comment]
Confirm fixed with new CJK tft. Tested on 3 different types. 👍
