### ISSUE TITLE
`DEV` Button page 2/3/4. Climate/Fan/Lights adjustment (long press) will jump back to page 1 climate/Fan/Lights

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1535]
Nspanel US

5. Button page 2/3/4. Climate/Fan/Lights adjustment (long press) will jump back to page 1 climate/Fan/Lights.

_Originally posted by @bluefoxlee in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1453#issuecomment-1874490769_

**Comment by edwardtfn** [comment]
I believe this is fixed now.
Could you please update your system (including TFT) and let me know the results?

**Comment by Doughboy68** [comment]
I confirm the issue is fixed now. Long press now works.

**Comment by bluefoxlee** [comment]
Conform fixed too. Thank you!
