### ISSUE TITLE
Documentation: Install sequence incorrect

### ISSUE THREAD

**Issue by andythomas** [Blackymas/NSPanel_HA_Blueprint#1539]
In [Installation and Setup](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-First-Steps---Installation-and-Setup) and [the German version](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(DE)-Erste-Schritte---Installation-und-Einrichtung) the step sequence has to be 1-7 and then 10, 8, 9. Without the Blueprint, the `update TFT display` button is not available.

**Comment by edwardtfn** [comment]
> Without the Blueprint, the update TFT display button is not available.

It should be available without the Blueprint. This sounds like a bug.

**Comment by andythomas** [comment]
I am on the main (4.1.4) branch.

**Comment by andythomas** [comment]
This bug is solved in 4.2dev.4
