### ISSUE TITLE
api encryption change breaks blueprint detection

### ISSUE THREAD

**Issue by andythomas** [Blackymas/NSPanel_HA_Blueprint#1540]
I installed an NSPanel with a preceding 

```
# Enable Home Assistant API
api:
  encryption:
    key: "9G/n03II5UL ...
```

in esphome and everything works fine. However, if I update OTA with a new firmware _without_ the api encryption the blueprint version cannot be detected. 

```
[18:15:38][D][script.check_versions:2178]: Blueprint version: 
[18:15:38][E][script.check_versions:2179]: Blueprint version mismatch!
```

Deleting the corresponding automation and reconnecting via a newly generated one from the blueprint does not work. However, deleting the esphome device and re-adding it does work. I am almost sure I saw a similar issue of the blueprint not being detected, but cannot find it anymore. Maybe, this would also explain that?!

**Comment by edwardtfn** [comment]
> However, if I update OTA with a new firmware without the api encryption the blueprint version cannot be detected.

But that is a security feature. If HA talked with this device using an API key it won't accept any communication with that seme device if that same key isn't used, unless you remorse the device and add it again with a new key or no key.
