### ISSUE TITLE
Documentation: heater relay

### ISSUE THREAD

**Issue by andythomas** [Blackymas/NSPanel_HA_Blueprint#1541]
The heater relay in [(EN) First Steps Installation and Setup](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-First-Steps---Installation-and-Setup) is setup 

```
##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2
```

but supposedly should be (after uncomment)

`heater_relay: "1"`

**Comment by edwardtfn** [comment]
Solved in `dev`
