### ISSUE TITLE
Can't upload TFT

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1544]
Hello i have the same issue like describe in the first comment. I have flashed my NSPanel and i see it in Homeassistant. When i press the "Update TFT Display" the restart but i have no change of Display.  
I Have tried the following Things:
1. I flashed the Display again and have changed the nextion_update_url von GitHub to local source
2. I have used the ip Adresse in the ESP yaml for the local url 
3. I have Changed the Framenetwork from esp-idf to arduino
4. I have pug of the power supply 

I don't Know what i can do now please Held me !!!!

Below you can see my Log File after pressing Update TFT Display 

[logs_panel1_logs (1).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13847769/logs_panel1_logs.1.txt)

_Originally posted by @MaZ181 in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1497#discussioncomment-8028084_

**Comment by edwardtfn** [comment]
@MaZ181, I have a few questions:
1. Is this a new installation into a panel with original Sonoff firmware or have you tried something else before on this panel?
2. What do you see in your panel's screen now?
3. Could you please share the yaml used for your panel? Please remove any sensitive information before sharing.
4. Could you please share the logs from the moment you press the Update TFT button? The logs you shared before isn't including this.
5. Have you looked our documentation about issues when uploading TFT? This is the link: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload

> I have Changed the Framenetwork from esp-idf to arduino

I would suggest to revert it back to esp-idf.

**Comment by MaZ181** [comment]
Hello @edwardtfn thank you for your answer.
Now i try it again and it works.

the only different was power supply was unpluged over the Night.
