### ISSUE TITLE
Get time from ESP instead of HomeAssistant Automation

### ISSUE THREAD

**Issue by naofireblade** [Blackymas/NSPanel_HA_Blueprint#155]
Is there a reason why the time on the display is set via an automation that triggers every minute instead of from the ESP32 directly (like its done with the internal temperature sensor)?

Otherwise I would try to provide a PR.

**Comment by Blackymas** [comment]
Yes, the main problem is the low memory of the NSPanel.

Therefore, we have outsourced everything that does not need to be in the ESPhome code to save memory.

If you use too much memory after the ESPHome flash the display is no longer accessible or it no longer works OTA.

see there but also no problem other sensors send much more information ;)

**Comment by Blackymas** [comment]
I think all is clear - I close the issue
