### ISSUE TITLE
Bug (DEV) - Relay status shows both on in home screen after a while.

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#1550]
Relay status the square 1 and 2 in upper left where chips are.
I confirm relays are off... but after a while they both appear on indicated by numbers 1 and 2.
When toggling on/off again in HA, the disappear, but eventually come back on, but relay is not actually on.

**Comment by edwardtfn** [comment]
Solved in `dev`
