### ISSUE TITLE
`DEV` Dual mode - once I start moving the sliders, the values do not update anymore

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1551]
This seems to work good now, the range is fine. I test heat and cool and is good, icons change color now depending on mode like before.

**However, the dual mode, although I can adjust the sliders independently (still needs a bit more work I think the are too close - maybe separate +/- for each would help), it doesn't seem to actually adjust the thermostat temperatures correctly all the time. I did not do much testing but it seems that once I start moving the sliders, the values do not update anymore on my thermostat itself.. but if I go into the page and press +/- it seems to update the heat I believe.**

Any plan to put in a fan mode - ie on/off/auto ? (mine only supports on/auto but probably would need an off also to cover all possibilities).

_Originally posted by @Doughboy68 in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1510#issuecomment-1879967586_

**Comment by edwardtfn** [comment]
@Doughboy68, I believe you've already answered this, but are you using the add-on dual climate or is this about some other HA integration?

Could you please share the logs from ESPHome and from HA (if anything related there) from when you move the sliders?

**Comment by edwardtfn** [comment]
Could you please update the blueprint and try again?

And please send logs if you still having issues. :)

**Comment by Doughboy68** [comment]
I tested briefly but didn’t have time to do full test. Main issue is interface seems to jump around and update / refresh too much while sliding.  Having separate large up down arrows to do adjustment in dual mode one unit at a time may work better than using touch. When I use heat or cool mode I never try to use touch slider and always the plus or minus.

**Comment by edwardtfn** [comment]
I understand the need about splitting the +/-, but that will require editing the background picture and as I don't have the original pics from @Blackymas I'd like to wait for next version to implement that with a bit more time.

On the current version, you have one indicator for target temp hight and one for target temp low. When you click those numbers the +/- context should change accordingly. Have you tried that?

**Comment by Doughboy68** [comment]
Yes it sort of works but I think that the numbers are too close to the +/-  so can accidentally can press them instead.
It seems the bottom is Heat and top is Cool, I would indicate which is which visually somehow maybe change color of temperature to indicate.
I also found that the temperature would go real high sometimes eg. over 100 degrees but I don't know exactly what causes this.

**Comment by edwardtfn** [comment]
Could you please try this again with beta 4?
