### ISSUE TITLE
Initial observations for 4.2beta1

### ISSUE THREAD

**Issue by hapklaar** [Blackymas/NSPanel_HA_Blueprint#1557]
- icon color for 'home page - custom buttons' are now orange for active and grey for inactive. Much better than the previous light grey/grey variants. Should it be possible to configure this color?
- icon color for 'home page - sensors' no longer seem to apply, are all grey regardless of what is configured. Indoor temp sensor icon color still works
- 'home page - sensors' icons have been shifted up, probably to allow for more buttons

- After upgrade I see additional icons on home screen: [1] and [2] upper left I haven't seen before. These seem to be for the relay state and disappear after toggling one relay on and off. Already reported in #1550
- and a round meter icon top right. Not sure what this is for.

- In Sensors screen some entities are unavailable (NSPanel event, Settings Entity). Not sure if this is new.
- In Diagnostic screen some entities are unavailable (nspanel, API uptime and Device uptime). Not sure if this is new.

**Comment by edwardtfn** [comment]
> icon color for 'home page - custom buttons' are now orange for active and grey for inactive. Much better than the previous light grey/grey variants. Should it be possible to configure this color?

This is part of the new icon's engine used (almost) everywhere now:
- When off, the icon will be always gray.
- When will be the first happening in this order:
    1. The user's configurable colors (when available - not for custom buttons)
    2. The standard domain color:


          - Lights: The light RGB color, when available


          - Climate: The state correspondent color


          - Alarm: Green when armed, red when triggered, yellow in transition mode


    3. White (just like before)

So, basically, option ii was included between the other 2.


> icon color for 'home page - sensors' no longer seem to apply, are all grey regardless of what is configured. Indoor temp sensor icon color still works

That shouldn't have changed. Could you please double check and create another issue specific for that if you are sure this is happening?

> 'home page - sensors' icons have been shifted up, probably to allow for more buttons

Only buttons and the weather components have been moved.

> After upgrade I see additional icons on home screen: [1] and [2] upper left I haven't seen before. These seem to be for the relay state and disappear after toggling one relay on and off. Already reported in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1550

Fixed in `dev` and will be part of beta 2 soon.

> and a round meter icon top right. Not sure what this is for.

Could you please send a picture? I don't know what you are talking about. 😄 

> In Sensors screen some entities are unavailable (NSPanel event, Settings Entity). Not sure if this is new.
> In Diagnostic screen some entities are unavailable (nspanel, API uptime and Device uptime). Not sure if this is new.

Those sensors have been removed in an earlier version.

**Comment by hapklaar** [comment]
Icon: 
![20240108_195459](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7703320/8e454446-f8dd-4a63-861a-fbb9e6ae6493)

**Comment by edwardtfn** [comment]
That's the icon for sensor value 3... it haven't changed since a while.

**Comment by hapklaar** [comment]
Ah I see now. It's the icon belonging to the entity shown there. Never seen it before :)
