### ISSUE TITLE
v4.2b1: icon color for 'home page - sensors' no longer seem to apply, are all grey regardless of what is configured.

### ISSUE THREAD

**Issue by hapklaar** [Blackymas/NSPanel_HA_Blueprint#1558]
Configured:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7703320/b5bca898-f227-4f84-a2bc-33edb440e4de)

Looks like:
![20240108_201803](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7703320/2b09e550-7b8b-456b-b98b-d4a366bc0d25)

**Comment by edwardtfn** [comment]
Thanks!!
Could you please try beta 2?

**Comment by hapklaar** [comment]
Works
