### ISSUE TITLE
White Screen after Update TFT Display

### ISSUE THREAD

**Issue by ghostfight1337** [Blackymas/NSPanel_HA_Blueprint#156]
Ich hab folgendes Probelm nachdem ich  auf Update TFT Display geklickt habe  dauert es ca 24 Stunden bis das Update fertig ist. Dann habe ich aber nur einen weissen Bildschirm. Ich kann dann über ESP Home das NSPanel neustarten und höre auch wie das piept und neu hochfährt aber der Bildschirm ist trozdem nur weiss wenn es neu hochgefahren ist. Wenn ich dann die Stromverbindung trenne ist der Bildschirm danach schwarz und zeigt Data Error an. Habe das jetzt schon dreimal probiert und immer das selbe Ergebniss. Habe auch im ESP Home den Code nochmal neu reinkopiert und per WLan installiert hat auch nix gebracht. Kann mir wer weiterhelfen?

**Comment by Blackymas** [comment]
Hallo,

wann hast du den ersten flash versuch gemacht? Brauche bitte den Tag und die ungefähre Uhrzeit.


Generell war das verbunden mit der baud rate - wir haben aber gestern eine neue TFT hochgeladen - mit der das Problem nicht mehr auftreten sollte. Deshalb würde ich gern wissen wann du das gemacht hast

**Comment by Blackymas** [comment]
Das Problem wurde auch hier schon besprochen und gelöst

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/107

**Comment by ghostfight1337** [comment]
Innerhalb der letzten 4 Tage. Habe gestern bevor ich das Problem hier gepostet habe nochmal nen neuen versuch gestarten mit dem neuen Update von euch. Werde hier dann berichten ob es funktioniert hat.

**Comment by Blackymas** [comment]
alles klar da hattest du beim ersten versuch noch das alte File.

Sonst muss du die baud Rate auf 9600 stellen im esphome - warum das nur bei einigen passiert ist mir noch nicht klar.

Generell haben wir aber seit gestern eine neue Version wo beim ersten flash das nicht mehr passiert

**Comment by Blackymas** [comment]
ich schließe das Ticket da wir kein weiteres feedback bekommen haben sonst schau bitte hier
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/166
und
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/177

**Comment by TanPau1412** [comment]
> all right because you still had the old file on the first attempt.
> 
> Otherwise you have to set the baud rate to 9600 in esphome - why this only happens with some is not yet clear to me.
> 
> In general, however, we have a new version since yesterday where this does not happen with the first flash

Hi, I am really having a hard time getting my tft file uploaded. tried blank file. How do I chnage the baud rate to 9600 in ESPhome? I even tried flashing a blank tft with 9600 baud rate in prgram.s
