### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by KBW18** [Blackymas/NSPanel_HA_Blueprint#1560]
When compiling based on blueprint 4.1.4 on ESPHome 2023.12.5, I get a consistent error compiling "main.o", "host_file_io.o" and "libapp_update.a", stating missing characters. The initial part compiles correctly, this occurs at the end. See truncated log (selected from bottom, all above compiling correctly) below. Last successful compile was on 2023.11.6, NSPanel currently operating OK. 
Validating in ESPHome first doesn't reveal any problems, cleaning build files also don't solve things.

HA 2024.1.0 running on VirtualBox VM op Mac Mini, 4GB RAM allocated

Any suggestions on how to fix?

Truncated compile log:

Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/src/esphome/core/scheduler.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/src/esphome/core/string_ref.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/src/esphome/core/time.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/src/esphome/core/util.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/src/main.o
<unicode string>:46:75: warning: missing terminating " character
<unicode string>:46:75: error: missing terminating " character
<unicode string>:70:111: warning: missing terminating " character
<unicode string>:70:111: error: missing terminating " character
Generating LD script .pioenvs/ga-30-zld-230v-wifi-ctr01/memory.ld
<unicode string>: In lambda function:
<unicode string>:46:75: error: expected ')' before '}' token
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/app_trace/app_trace.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/app_trace/app_trace_util.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/app_trace/host_file_io.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/app_trace/gcov/gcov_rtio.o
<unicode string>: In lambda function:
<unicode string>:70:111: error: expected ';' before 'upload_tft'
Archiving .pioenvs/ga-30-zld-230v-wifi-ctr01/esp-idf/app_trace/libapp_trace.a
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/app_update/esp_ota_ops.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/app_update/esp_app_desc.o
Archiving .pioenvs/ga-30-zld-230v-wifi-ctr01/esp-idf/app_update/libapp_update.a
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/bootloader_support/src/bootloader_common.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/bootloader_support/src/bootloader_common_loader.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/bootloader_support/src/bootloader_clock_init.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/bootloader_support/src/bootloader_flash.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/bootloader_support/src/bootloader_mem.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/bootloader_support/src/bootloader_random.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/bootloader_support/src/bootloader_random_esp32.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/bootloader_support/src/bootloader_utility.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/bootloader_support/src/esp_image_format.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/bootloader_support/src/flash_encrypt.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/bootloader_support/src/secure_boot.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/bootloader_support/src/flash_partitions.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/bootloader_support/src/flash_qio_mode.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/bootloader_support/src/bootloader_flash_config_esp32.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/bootloader_support/src/bootloader_efuse.o
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/bootloader_support/src/idf/bootloader_sha.o
Archiving .pioenvs/ga-30-zld-230v-wifi-ctr01/esp-idf/bootloader_support/libbootloader_support.a
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/cbor/tinycbor/src/cborencoder_close_container_checked.o
*** [.pioenvs/ga-30-zld-230v-wifi-ctr01/src/main.o] Error 1
Compiling .pioenvs/ga-30-zld-230v-wifi-ctr01/cbor/tinycbor/src/cborencoder.o
========================= [FAILED] Took 96.24 seconds =========================

**Comment by edwardtfn** [comment]
Could you please share your yaml? Please remove any sensitive info before sharing.

**Comment by KBW18** [comment]
Of course, here it is (the Nextion update URL's are using the local path):

substitutions:
  ###### CHANGE ME START ######
  device_name: "ga-30-zld-230v-wifi-ctr01" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: http://....:8123/local/nspanel_eu.tft"
  nextion_blank_url: "http://....:8123/local/nspanel_blank.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 1s

esp32:
  framework:
    type: esp-idf

##### My customization - Start #####
##### My customization - End #####

**Comment by edwardtfn** [comment]
```yaml
  nextion_update_url: http://....:8123/local/nspanel_eu.tft"
```

Your `nextion_update_url` is missing `"` at the beginning. Please either add that at the beginning or remove at the end.

**Comment by KBW18** [comment]
OK.... This is is a bit embarrassing (for me), but that was the whole solution. Don't know how I missed that.
Many thanks for the quick help!
