### ISSUE TITLE
`DEV` When changing min/max temps, then celsius icon is removed

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1569]
Side note and small UI issue: When changing min/max temps, then celsius icon is removed

_Originally posted by @Floppe in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1556#discussioncomment-8065746_

**Comment by edwardtfn** [comment]
Fixed in `dev`

**Comment by Floppe** [comment]
Tested TFT 4.2beta.5, still same thing for me. Icon disappears. It comes back first when setpoint changed in geothermal pump, so this is a minor issue.

**Comment by edwardtfn** [comment]
Ok, I will take a look at this again, but I'm not gonna hold the release for this...
