### ISSUE TITLE
Screen hang on Boot Screen

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1571]
I have the Same issue. My screen hang on Boot Screen. Have you Info what can i do? I flashed with the blank.tft and then with the eu.tft but the screen is the same. 🤕 In the Home Assistant dashboard i can See data. 
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/39754636/488bb888-abf6-4696-a606-505426fdf9de)
![IMG_1034](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/39754636/d9800b91-4188-41a6-9cb3-52ce23ec7555)

_Originally posted by @Daniel167 in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1468#issuecomment-1883023946_

**Comment by edwardtfn** [comment]
@Daniel167, is this a new instalation or are you upgrading from a previous version?

**Comment by edwardtfn** [comment]
Please install the `nspanel_eu.tft` back, as the issue is not with the TFT.

On the Blueprint side, could you please open the automation and confirm your blueprint is v4.1.4 and if it isn't, could you please update that? The version is shown at the end of the introduction text, right before the panel selection.

Talking about panel selection, could you please double check if it is right in the Blueprint settings?

**Comment by edwardtfn** [comment]
And, if the error persists, try to remove/delete your panel's integration from **Settings** > **Devices and Services** > **ESPHome**, restart Home Assistant and then add your panel again in that same page.
There's no need to remove it from ESPHome Dashboard.

**Comment by andythomas** [comment]
@Daniel167 I had this issue, because I (unintentionally) changed the API encryption from on to off or vice versa or used a new key. Please see (https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1540#issue-2067776843) The view on the screen would be the same. It is a far stretch, since it can have many more reasons, but maybe you are lucky...@edwardtfn 's previous comment would fix it.
