### ISSUE TITLE
set points for internal thermostat heater

### ISSUE THREAD

**Issue by andythomas** [Blackymas/NSPanel_HA_Blueprint#1574]
I am running 4 NSPanels to replace all regular thermostats and must say that I enjoy them a lot :) I am running the 'generic thermostat' from home assistant on 2 and the embedded one on the two others. Since we utilize underfloor water heating, the response when starting to heat is quite slow. Therefore, I have to adjust the [hot_tolerance](https://www.home-assistant.io/integrations/generic_thermostat/#hot_tolerance) and [cold_tolerance](https://www.home-assistant.io/integrations/generic_thermostat/#cold_tolerance) from the generic thermostat called `heat_deadband` and `heat_overrun` in [ESPHome](https://esphome.io/components/climate/thermostat.html). 

I implemented this functionality in this [PR](https://github.com/Blackymas/NSPanel_HA_Blueprint/pull/1573)

**Comment by edwardtfn** [comment]
If you open the conversation on the PR you should be able to see, no?

Anyways, my main question is why not use the same names as from ESPHome so it would be easier to standardize between `addon_climate_heat`, `addon_climate_cool` and `addon_climate_dual`. At this moment all the features are common between all those versions.

> In addition to the set points, hysteresis values determine how far the temperature may vary from the set point value(s) before an [action](https://esphome.io/guides/automations#config-action) (cooling, heating, etc.) is triggered. They each default to 0.5 °C. They are:
>
> - **cool_deadband:** The minimum temperature differential (temperature above the set point) before engaging cooling
> - **cool_overrun:** The minimum temperature differential (cooling beyond the set point) before disengaging cooling
> - **heat_deadband:** The minimum temperature differential (temperature below the set point) before engaging heat
> - **heat_overrun:** The minimum temperature differential (heating beyond the set point) before disengaging heat

**Comment by andythomas** [comment]
Sorry, I see no conversation.

But to answer the question: I was also torn between HA and esphome terminology. Since the package is supposed to enable the configuration without programming, I found the HA terms more fitting/understandable and you have used, e.g., `temp_max` and not `max_temperature`. Personally, I would have used the `...deadband` and `...overun` ones from esphome. So please change it, if you think it will be more fitting.
