### ISSUE TITLE
`DEV`  Is it intended that a "No" is displayed for entities without a unit?

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1576]
hey, 
good job. Thank you very much.

**One question: is it intended that a "No" is displayed for entities without a unit? It's not a bug, rather than a question. "no --> no icon there"**

a wish perhaps for 4.3:
Unfortunately I can only specify sensors on the home-/climatepage not numbers. So I created a template sensor as an interim solution depented an the number_value.

_Originally posted by @kroessig in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1556#discussioncomment-8070947_

**Comment by edwardtfn** [comment]
I believe this is fixed in `dev` now

**Comment by kroessig** [comment]
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/139384422/670d5812-7a12-4784-bb45-ff629586f230)
I expressed myself incorrectly. I just meant the icon and it's not "no" , it's "Non".

My templatesensor is defined as:
```
#Sensor fur NSPanel --> Heiz-Ziel Korrektur            
      - name: "Heizung_Ziel_Korrektur"
        unique_id: Heizung_Ziel_Korrektur
        state: >-
            {{ float(states('number.luxtronik2_heating_target_correction') | float(0))  }}  
```
Ah, you may fixed it already. Unfortunately I can only test it this evening.

**Comment by kroessig** [comment]
it works! great!
