### ISSUE TITLE
Ability to customize icons

### ISSUE THREAD

**Issue by kalagan55** [Blackymas/NSPanel_HA_Blueprint#158]
Ability to customize switch icons | cover | input_boolean | automated | button | input_button | stage | person | script

**Comment by Blackymas** [comment]
at the moment this is not possible and also provided via Blueprint.

Maybe in a few weeks, but currently has no priority.

But you can download the HMi file and replace the images and create a TFT from it.

**Comment by kalagan55** [comment]
Thanks
