### ISSUE TITLE
BUTTON page buttons malfunction (?)

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1598]
I just installed HA and NSPanel_HA_Blueprint. I use Sonoff Basic switches (via eWelink extension) and own hw. boards based on ESP01 (via ESPHome extension).
Settings were made on NSPanel page according to the Blueprint's description.
But I have issues with BUTTON page functionality:
Displaying the actual status of an entity - like a Sonoff switch - works fine. But switching a device by pressing the specific icon on NSPanel's touchscreen works just in case of ESP module and does not work on Sonoff devices.

_Originally posted by @gdercze in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1592_

**Comment by edwardtfn** [comment]
Hi @gdercze,
1. How is this entity you are trying to control (the one from your Sonoff devices)? I mean, it is `light.xxxx`, `switch.xxxx`?
2. On the boot page, which versions you see for TFT, Blueprint and ESPHome?
3. Can you see any error message related to this under your Home Assistan logs (Settings > System > Logs)?

**Comment by gdercze** [comment]
> Hi @gdercze,
> 
> 1. How is this entity you are trying to control (the one from your Sonoff devices)? I mean, it is `light.xxxx`, `switch.xxxx`?
> 2. On the boot page, which versions you see for TFT, Blueprint and ESPHome?
> 3. Can you see any error message related to this under your Home Assistan logs (Settings > System > Logs)?

1. These entities are shown as switch.xxxx but without unique ID.
2. Ver. 4.1.4  for all.
3. Nothing.

**Comment by edwardtfn** [comment]
Missing unique_id shouldn't be an issue.

Could you please go to Developer Tools, tab States, select this entity and share here it's attributes?

**Comment by edwardtfn** [comment]
As you are on that area, please go also to the tab Services, find the service `switch.toggle`, select that entity and then press the button "Call Service"? What happens?

**Comment by gdercze** [comment]
> Missing unique_id shouldn't be an issue.
> 
> Could you please go to Developer Tools, tab States, select this entity and share here it's attributes?

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/51111490/c96545fc-b32d-488a-bac5-0122ba8aa143)

**Comment by gdercze** [comment]
> As you are on that area, please go also to the tab Services, find the service `switch.toggle`, select that entity and then press the button "Call Service"? What happens?


https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/51111490/6ef941ae-37a9-4e9f-a85e-02352e34085a

**Comment by gdercze** [comment]
Pushing "Call Service" button has no effect on real status of switch.

**Comment by edwardtfn** [comment]
Well, if the service call isn't working, then it is something on Home Assistant side. The blueprint calls this service when you press the button on the screen.

If you can try another approach, please go to the [Helpers](https://my.home-assistant.io/redirect/helpers/) area, click "Create helper", go to "Change a device type of a Switch" and change this switch to a light, then assign that new light entity to the panel and let me know the results.
You can also repeat the test on the services area, but now using service `light.toggle`.

**Comment by gdercze** [comment]
Thanks for your help. Changing the device type resulted switches working by using NSPanel.
I am curious about this situation; as you wrote, there is "something on Home Assistant side". I have installed HA on RPi 4 and followed the specific instructions step by step. I have not faced any issues using HA until the integration of NSPanel.
This issue with the switches is not the only problem I am facing, but others should be the subjects of independent topics.

**Comment by edwardtfn** [comment]
> I am curious about this situation; as you wrote, there is "something on Home Assistant side". I have installed HA on RPi 4 and followed the specific instructions step by step. I have not faced any issues using HA until the integration of NSPanel.

I don't think it is something with your HA installation, but with the Ewelink integration. The `switch.toggle` is basic for switch domain in HA and not even that is supported by Sonoff's "Official" integration, which wasn't updated since almost an year.
They have some recommendation on their docs, but I haven't tested that myself as I don't have any Sonoff device with original firmware anymore. This is the link: https://github.com/CoolKit-Technologies/ha-addon/blob/master/eWeLink_Smart_Home/README.md
