### ISSUE TITLE
When keeping it pressed, I still don't get the option to dim

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1599]
@edwardtfn Came here to report the same. 

Turning it off now also works again for me with the current beta blueprint, but when keeping it pressed, I still don't get the option to dim. It's now just an on off switch. 

PS the blueprint now shows ℹ️ Version: v4.2 and no longer beta
PPS attributes for the entity
```
supported_color_modes: brightness
color_mode: brightness
brightness: 136
off_with_transition: false
off_brightness: null
icon: mdi:radiator
friendly_name: Desk heater dimmer Light
supported_features: 40
```

_Originally posted by @hapklaar in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1556#discussioncomment-8098114_

**Comment by edwardtfn** [comment]
@hapklaar, can you see any related error on your Home Assistant logs (Settings > System > Logs)?

**Comment by hapklaar** [comment]
Yes, these errors in HA logs appear when I long press and the entity is on:

```
Error while executing automation automation.np: expected int @ data['page_icon_color'][0]
18:58:12 – (ERROR) Automation - message first occurred at 18:34:14 and shows up 3 times
NSPanel: Main choices: NSPanel event: Choose at step 2: Button click: Choose at step 1: Buttons pages: Choose at step 7: Long click: Error executing script. Invalid data for call_service at pos 2: expected int @ data['page_icon_color'][0]
18:58:12 – (ERROR) Automation - message first occurred at 18:34:14 and shows up 15 times
```

Only happens when the entity is on. When it's off it works as intended.

**Comment by edwardtfn** [comment]
I believe this is fixed on `dev` now and will be included in the next patch.
Feel free to test the version from `dev` and share your results. You only have to update the blueprint side in this case.

**Comment by hapklaar** [comment]
Works!
