### ISSUE TITLE
Another TFT upload fail

### ISSUE THREAD

**Issue by misery** [Blackymas/NSPanel_HA_Blueprint#1604]
### ESPHome Version

4.2

### Blueprint Version

4.2

### What is the bug?

TFT upload fails

### Steps to Reproduce

I have two nspanels and both cannot update the TFT. It tries to upload and stopped at 20, 40 and 60 % percent and restarted esphome. I tried several times at both nspanels. But both stops at some percent level.
Now it won't start an upload anymore. Not even a blank file gets uploaded.

### Your panel's YAML

```yaml
substitutions:
  device_name: "nspanelflur" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://caddy.local/nspanel_eu.tft"


##### DO NOT EDIT
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
##### DO NOT CHANGE ANYTHING! #####


wifi:
  domain: .lan

text_sensor:
  - name: ${device_name} ESPhome Version
    platform: version
    disabled_by_default: true

  - platform: wifi_info
    ip_address:
      name: ${device_name} IP
      disabled_by_default: true
      id: ip_address

captive_portal:

web_server:
  id: web_server_std
  port: 80

time:
  - id: !extend time_provider
    timezone: "Europe/Berlin"
```

**Comment by misery** [comment]
[logs_nspanelflur_logs.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13908870/logs_nspanelflur_logs.txt)

**Comment by bkbartk** [comment]
I have the same thing for framework aruino
2 of my 3 panels I could swap to esp-idf for a short while and to upgrade went fine.
but the other panel I cannot update because of this
https://github.com/esphome/feature-requests/issues/2488

I don't know why I can swap 2 of my panels between frameworks and not the other one.
But if you have to possibility, the esp-idf upload works perfect.

I think I have to serial flash my 3th panel.
hopefully, if I serial flash with esp-idf I will be able to move around between the frameworks.

**Comment by edwardtfn** [comment]
```log
[22:52:48][D][addon_upload_tft.script.upload_tft.upload_tft_arduino:878]: Connected
[22:52:48][D][addon_upload_tft.script.upload_tft.upload_tft_arduino:884]: Requesting URL: http://caddy.local/nspanel_eu.tft
[22:52:48][D][addon_upload_tft.script.upload_tft.upload_tft_arduino:916]: Updating Nextion
[22:52:48][D][addon_upload_tft.script.upload_tft.upload_tft_arduino:925]: Clear serial receive buffer: 1
[22:52:48][D][addon_upload_tft.script.upload_tft.send_nextion_command:650]: Sending: whmi-wris 274936,115200,1
```
This is reporting `nspanel_eu.tft` is only 275kb. Have you renamed the `nspanel_blank.tft` or is this a corrupt file?

One thing you could try is to temporarily [remove your customizations](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/tft_upload.md#remove-customizations) during the upload process and then enable it back, however what I would try if I was facing this myself would be [switching to `esp-idf`](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/tft_upload.md#consider-changing-the-framework) just for the upload process, as it works much better on that framework (even that local hosted file isn't needed with that) and, after the upload, revert back to `arduino` (unless you wanna do a serial flash, then I would stay in `esp-idf` in definitive).

**Comment by edwardtfn** [comment]
> but the other panel I cannot update because of this
> [esphome/feature-requests#2488](https://github.com/esphome/feature-requests/issues/2488)

Some people is working in a change that might solve that issue: https://github.com/esphome/esphome/pull/5535

**Comment by misery** [comment]
> ```
> [22:52:48][D][addon_upload_tft.script.upload_tft.upload_tft_arduino:878]: Connected
> [22:52:48][D][addon_upload_tft.script.upload_tft.upload_tft_arduino:884]: Requesting URL: http://caddy.local/nspanel_eu.tft
> [22:52:48][D][addon_upload_tft.script.upload_tft.upload_tft_arduino:916]: Updating Nextion
> [22:52:48][D][addon_upload_tft.script.upload_tft.upload_tft_arduino:925]: Clear serial receive buffer: 1
> [22:52:48][D][addon_upload_tft.script.upload_tft.send_nextion_command:650]: Sending: whmi-wris 274936,115200,1
> ```
> 
> This is reporting `nspanel_eu.tft` is only 275kb. Have you renamed the `nspanel_blank.tft` or is this a corrupt file?
> 
> One thing you could try is to temporarily [remove your customizations](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/tft_upload.md#remove-customizations) during the upload process and then enable it back, however what I would try if I was facing this myself would be [switching to `esp-idf`](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/tft_upload.md#consider-changing-the-framework) just for the upload process, as it works much better on that framework (even that local hosted file isn't needed with that) and, after the upload, revert back to `arduino` (unless you wanna do a serial flash, then I would stay in `esp-idf` in definitive).

Yes, I renamed `blank` on server side as it is much faster than flashing esphome again for the url. ;-)

I downgraded to 4.1.4 and it successfully uploaded 4.1.4 TFT file without problems. After upgrade to 4.2 I have the same problem again.

```
[23:31:09][D][nextion.upload.arduino:113]: Uploaded 58.71 %; 3018928 bytes remaining
[23:31:09][D][nextion.upload.arduino:113]: Uploaded 58.77 %; 3014832 bytes remaining
[23:31:09][D][nextion.upload.arduino:113]: Uploaded 58.82 %; 3010736 bytes remaining
[23:31:09][D][nextion.upload.arduino:113]: Uploaded 58.88 %; 3006640 bytes remaining
[23:31:09][D][nextion.upload.arduino:113]: Uploaded 58.93 %; 3002544 bytes remaining
[23:31:09][D][nextion.upload.arduino:113]: Uploaded 58.99 %; 2998448 bytes remaining
[23:31:09][D][nextion.upload.arduino:113]: Uploaded 59.05 %; 2994352 bytes remaining
[23:31:09][D][nextion.upload.arduino:113]: Uploaded 59.10 %; 2990256 bytes remaining
[23:31:09][D][nextion.upload.arduino:113]: Uploaded 59.16 %; 2986160 bytes remaining
[23:31:09][D][nextion.upload.arduino:113]: Uploaded 59.21 %; 2982064 bytes remaining
[23:31:10][D][nextion.upload.arduino:320]: Heap Size 59928, Bytes left 2982064
[23:31:10][D][nextion.upload.arduino:049]: Requesting range: bytes=4329472-4382719
```

It hangs....

**Comment by misery** [comment]
> I have the same thing for framework aruino 2 of my 3 panels I could swap to esp-idf for a short while and to upgrade went fine. but the other panel I cannot update because of this [esphome/feature-requests#2488](https://github.com/esphome/feature-requests/issues/2488)
> 
> I don't know why I can swap 2 of my panels between frameworks and not the other one. But if you have to possibility, the esp-idf upload works perfect.
> 
> I think I have to serial flash my 3th panel. hopefully, if I serial flash with esp-idf I will be able to move around between the frameworks.

Thanks, but I didn't swapped the framework. I think I will downgrade to 4.1.4 and serial flash esp-idf in next days.

**Comment by edwardtfn** [comment]
You can use v4.1.4 to upload TFT v4.2, then flash ESPHome with v4.2. 😉

**Comment by edwardtfn** [comment]
> serial flash esp-idf in next days.

That is a good idea. The whole TFT transfer is much easier. You don't have even to keep a copy o TFT locally or flash your panel every time you change the file... it's all in the UI when using ESP-IDF:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/pics/ha_device_configuration_tft_upload_model.png?raw=true)

It will download the files directly from GitHub.

**Comment by misery** [comment]
> You can use v4.1.4 to upload TFT v4.2, then flash ESPHome with v4.2. 😉

Good idea... that worked. Looks like 4.1.4 had a better upload mechanism than 4.2.
First panel upload was fast but tooks AGES until "nextion not connected" disappeared and show the interface.
Second panel upload was terrible slow but worked immediately after re-flashing.

Yes, the upload dialog looks good. I will switch to esp-idf soon.

**Comment by edwardtfn** [comment]
> Looks like 4.1.4 had a better upload mechanism than 4.2.

We changed that due to errors with v4.1: https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1255#discussioncomment-7758530

It's hard to say what exactly is the issue. Sometimes a version works fine with me, but hen we get hundreds reporting issues with that, then sometimes it fails for me but not to others...
The process in Arduino deserves some care. I'm just using the library from ESPHome, but the one for idf I have done from scratch based on the experience here... Maybe I should do  the same with Arduino, but this means a lot of work and arduino is pretty bad with https anyways, so I think the way to go is `esp-idf`.
ESPHome people is talking about this thing of changing to idf for more than a year now. They are now trying idf v5 and hopefully with that they will support more components. Our project was already done all needed to support idf v5 also, so we are prepared for that.

**Comment by bkbartk** [comment]
> Some people is working in a change that might solve that issue: [esphome/esphome#5535](https://github.com/esphome/esphome/pull/5535)

Sorry, can't get this to work,
I think this is more for migrating from Tasmota if I read correctly, this one might help with an issue I have on another device,

I see we can migrate esp-idf to arduino, so If I serial flash esp-idf I can swap without issues( if I understand correctly)

**Comment by misery** [comment]
Yeah, esp-idf uploads without any problems!
Just one panel takes 5 minutes after flash and reboot and hangs on "nextion not connected" in the "boot screen" and "retry esphome" (I can connect with browser to web_server without problems). The right corner shows 921600 on the "boot screen" even I selected 115200. Is it normal? Another panel shows 115200 and has no startup problems.

**Comment by edwardtfn** [comment]
> Just one panel takes 5 minutes after flash and reboot and hangs on "nextion not connected" in the "boot screen" and "retry esphome" (I can connect with browser to web_server without problems).

Was it showing any value for ESPHome version?

> The right corner shows 921600 on the "boot screen" even I selected 115200. Is it normal? Another panel shows 115200 and has no startup problems.

This is like this since v4.1 when we added compatibility to 921600bps (which I don't recommend to use). If ESPHome didn't establishes a communication with the display, the display will alternate itself between 115200bps and 921600bps every 30s.

**Comment by misery** [comment]
> > Just one panel takes 5 minutes after flash and reboot and hangs on "nextion not connected" in the "boot screen" and "retry esphome" (I can connect with browser to web_server without problems).
> 
> Was it showing any value for ESPHome version?

It shows "Retry #NUMBER"

> 
> > The right corner shows 921600 on the "boot screen" even I selected 115200. Is it normal? Another panel shows 115200 and has no startup problems.
> 
> This is like this since v4.1 when we added compatibility to 921600bps (which I don't recommend to use). If ESPHome didn't establishes a communication with the display, the display will alternate itself between 115200bps and 921600bps every 30s.

I do not set a custom speed. Also 115200bps is shown in web_server. But the boot screen shows 921600. Even if I deinfed 115200 as custom setting in yaml.

**Comment by edwardtfn** [comment]
The web server shows the info from ESPHome, and it looks correct.
The info shown in the screen is from the TFT. It will switch between 921600bps and 115200bps every 30sec until ESPHome can establish a connection. So it looks normal also.

The watchdog should try to resolve this situation you are facing, but pressing the reset button bellow the device should also take care of that:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/pics/eu_reset_button.png?raw=true)

We have a bit about this in our docs: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/error_initializing.md

If that isn't working, please try adding this to your yaml as a customization:
```yaml
switch:
  # Exposes display power switch
  - id: !extend screen_power
    internal: false
```
Then install it. It will expose a switch in your device's page in Home Assistant where you will be able to turn off the power supply for your screen, then turn on... Please let me know if that helps.

**Comment by misery** [comment]
> The web server shows the info from ESPHome, and it looks correct. The info shown in the screen is from the TFT. It will switch between 921600bps and 115200bps every 30sec until ESPHome can establish a connection. So it looks normal also.

I do not see that it tries 115200bps. Should it be displayed after 30 seconds on the display? I always shows 921600bps. Even it shows it if I force it with "id: !" override.
It takes way more than 30 seconds to connect.


> The watchdog should try to resolve this situation you are facing, but pressing the reset button bellow the device should also take care of that: ![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/pics/eu_reset_button.png?raw=true)

> Then install it. It will expose a switch in your device's page in Home Assistant where you will be able to turn off the power supply for your screen, then turn on... Please let me know if that helps.


I tried to press the reset button and the display off switch. There is no difference. The display is just turned off for a while and the same starts again after it is on.

**Comment by edwardtfn** [comment]
v4.2.3 was released.
Please let me know if that was fixed, otherwise we can reopen this.

**Comment by misery** [comment]
Tried 4.2.3 and has the same problem. Also I cannot flash 4.2.3 to TFT at the moment with it.

[logs_nspanelflur_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13967848/logs_nspanelflur_run.txt)

**Comment by misery** [comment]
Maybe it is related to #1667

**Comment by edwardtfn** [comment]
Could you please create another issue specifically about this initialising issue?
It's hard to keep track when we have multiple different issues in the same ticket.

**Comment by misery** [comment]
Ok: #1674
