### ISSUE TITLE
`BUG` Can't upload TFT

### ISSUE THREAD

**Issue by eddiebullman** [Blackymas/NSPanel_HA_Blueprint#1605]
### Question

Can't upload TFT

### Additional Details

I have one Sonoff NSPanel working fine tried add a second on but can't get it to upload the TFT still showing Sonoff screen but I can control the relays via esphome .

I have noticed that the "Nextion display" showing as disconnected in the esphome 
![Screenshot 2024-01-12 at 03 27 20](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/78513296/15dce616-c84f-4cf2-9d2c-21940cf17c1f)

**Comment by andythomas** [comment]
Please see the discussion [here](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1604). Maybe, one suggestion there works for you as well.

**Comment by edwardtfn** [comment]
@eddiebullman, could you please share the yaml used for set your panel in ESPHome?

**Comment by eddiebullman** [comment]
Hi this is the .yaml file

I have stared out my Wifi detail

substitutions:

###### CHANGE ME START ######

  device_name: "entrancensp"
  wifi_ssid: "**********"
  wifi_password: "*********"

  nextion_update_url: "http://10.10.0.201:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: nspanel_esphome.yaml
    refresh: 300s
esp32:
  framework:
    type: esp-idf
##### DO NOT CHANGE ANYTHING! #####

**Comment by edwardtfn** [comment]
This is odd. Your yaml indicates you are using `esp-idf` framework (which is good), but your screenshot show your device is missing some components that are expected with `esp-idf`.

I can see in your screenshot that right bellow the selection for wake-up page your have "**+1 entity not shown**". Could you please expand that and let me know which entity is that?

And could you please start collecting ESPHome logs from your device, restart it (there's a component for this on that page you took the screenshot, then when it's back, wait like 15s, then press the **Update TFT display**, wait until the system reboots again, save all the log and share it here?

**Comment by eddiebullman** [comment]
latest screen shot
![Screenshot 2024-01-12 at 12 45 21](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/78513296/76f45200-ef15-4c33-9e78-8ecbbc585d96)
Log file 
[logs_entrancensp_logs.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13919236/logs_entrancensp_logs.txt)

Is this the yaml file I should be using

![Screenshot 2024-01-12 at 12 51 27](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/78513296/28bf99c1-6dfd-4ca1-92a5-ac2023d76e63)

**Comment by edwardtfn** [comment]
Could you please try the following?

1. On your yaml, in the `remote_package` area, change from `ref: main` to `ref: v4.1.4`
2. Flash your device again (wirelessly is fine)
3. When your device is back, press **Upload TFT display** (capturing the logs, please)
4. After your device restarts, please change it back to `ref: main` and flash it again.

Please let me know the results.

**Comment by eddiebullman** [comment]
when change the yaml file to this

ubstitutions:

###### CHANGE ME START ######

  device_name: "entrancensp"
  wifi_ssid: "****"
  wifi_password: "****"

  nextion_update_url: "http://10.10.0.201:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####
s


##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: v4.1.4
    files: nspanel_esphome.yaml
    refresh: 300s
esp32:
  framework:
    type: esp-idf
##### DO NOT CHANGE ANYTHING! #####

It stops have attached the log

[logs_entrancensp_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13920630/logs_entrancensp_run.txt)

Hope this helps

**Comment by eddiebullman** [comment]
ok kept bashing at and now it working 
all on 
TFT 4.2.1
ESPhome 4.2.1
Blueprint 4.2.1

with following yaml

substitutions:

###### CHANGE ME START ######

  device_name: "entrancensp"
  wifi_ssid: "network@net19.me"
  wifi_password: "homenetworkme"

  nextion_update_url: "http://10.10.0.201:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: nspanel_esphome.yaml
    refresh: 300s
esp32:
  framework:
    type: esp-idf
##### DO NOT CHANGE ANYTHING! #####

Thanks for your assistance 😀👍

**Comment by eddiebullman** [comment]
I understand that there blueprint has been updated and the alarm area has been removed to allow for multiple alarm panels but I have tried setting my alarm (Alarmo) as a chip and a custom button but it doesn't aper on the display any where what am I doing wrong.

I have another NSPanel on a different HA server and running blue print v4.1.3 and it works fine with the alarmo on the home page

**Comment by edwardtfn** [comment]
Could you please report that as another bug? I will take a look later.

**Comment by eddiebullman** [comment]
will do
