### ISSUE TITLE
Feature Request: Show static image on event

### ISSUE THREAD

**Issue by ctschach** [Blackymas/NSPanel_HA_Blueprint#1619]
### Enhancement Summary

Ability to upload a static image on an „image page“ and show this when event is triggered

### Detailed Description

Is it possible to upload a static image (like a snapshot from a ip camera) to the display and show it when an event is triggered?

Let‘s say the motion sensor in my backyard is triggered, I would like to see a static image of the outdoor camera on the panel. Same thing could be used when the doorbell rings.

Not sure if the Esp32 in the nspanel is able to handle this task and how long the upload of an image would take….

…But I still like the idea….

**Comment by plasterer41** [comment]
Not possible

**Comment by edwardtfn** [comment]
Please take a look at this: https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1270#discussioncomment-7686610
