### ISSUE TITLE
Black icons not visible after update to 4.2.1

### ISSUE THREAD

**Issue by geni0602** [Blackymas/NSPanel_HA_Blueprint#1624]
### TFT Version

4.2.1

### ESPHome Version

4.2.1

### Blueprint Version

4.2.1

### Panel Model

NSPanel EU Model

### What is the bug?

Black icons home page custom buttons and button pages 

### Steps to Reproduce

After update the the icons custom buttons are not visible because of the black color. The color is not changeable in the blueprint.
![PXL_20240113_135551094~2](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/62853417/40bd4653-3922-4ed4-98d0-184a746deb5f)
![PXL_20240113_135541145~2](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/62853417/221a9485-1358-4c17-9801-ed15ba55f575)

**Comment by geni0602** [comment]
i´ve changed back to 4.1.4. There were a lof of bugs on my panel. 
- the dark icons 
- no Nextion connection for a long time after restart. same as #1614 May be the issue was the change from arduino to esp-idf. Serial-Flash didn´t solve the problem. Display gets a connection after restart after 5-6 min. 
- Sleep mode active even the timer is set to 0,0

**Comment by Daniel167** [comment]
@geni0602 Hello, i have same a many problems with the new software. How can i downgrade to 4.1.4? Thanks for help

**Comment by geni0602** [comment]
you have to change the ref. Back to v4.1.4 In your yaml file
![Screenshot_20240113-182203~2](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/62853417/c31b8b6e-65a0-44b1-8be1-d71992f3aeb0)

And of course, you have to update the TFT to 4.1.4 and blueprint back to 4.1.4. you can find the files in the repo

**Comment by geni0602** [comment]
https://github.com/Blackymas/NSPanel_HA_Blueprint/tree/v4.1.4

**Comment by geni0602** [comment]
as i wrote int #1614 the booting is know ok. but the dark icons are stil there. (s. my screenshot) on the dark background they almost not visible. @edwardtfn: did you made any correction in v4.2.2 patch. Could you reproduce it, or is it just me?

**Comment by edwardtfn** [comment]
I could reproduce that and wanna find a color for that that fits well so I can implement in v4.2.2.

**Comment by edwardtfn** [comment]
Fixed in `dev` and will be part of v4.2.2
