### ISSUE TITLE
Alexa

### ISSUE THREAD

**Issue by ucakca** [Blackymas/NSPanel_HA_Blueprint#1625]
### Question

Hi, is there any way to connect the hardware buttons after flashing to blackymas to Alexa?

**Comment by edwardtfn** [comment]
I'm not sure if I understood what you are trying to achieve. What do you wanna the hardware button to do with Alexa?

**Comment by ucakca** [comment]
> I'm not sure if I understood what you are trying to achieve. What do you wanna the hardware button to do with Alexa?

I want to controll the hardware buttons with Alexa too. In this case it is only controllable manual by pressing it or via HA. Not with Alexa over voice control.

**Comment by edwardtfn** [comment]
That's correct, but the buttons state (whatever pressed or not) will be exposed to Home Assistant as Binary Sensors and the relays are exposed as switches, so if you have Alexa integrated with Home Assistant you can use that to control what you want.

**Comment by ucakca** [comment]
> That's correct, but the buttons state (whatever pressed or not) will be exposed to Home Assistant as Binary Sensors and the relays are exposed as switches, so if you have Alexa integrated with Home Assistant you can use that to control what you want.

OK, how are the buttons connected to Alexa?

**Comment by edwardtfn** [comment]
They are not connected to Alexa. They are connected to Home Assistant.
If you have your Home Assistant integrated to Alexa, you can do the integration for those buttons (and relays) in the same way you have integrated other sensors and switches from Home Assistant to Alexa.

Of what you are looking for is a way to integrate Home Assistant to Alexa, I woukd recommend you look at Home Assistant Community as you will find people with more experience on that.

**Comment by edwardtfn** [comment]
https://www.home-assistant.io/integrations/alexa/

**Comment by ucakca** [comment]
> https://www.home-assistant.io/integrations/alexa/

I did solve it with emulated_hue, it works fine!
https://www.home-assistant.io/integrations/emulated_hue/
