### ISSUE TITLE
How to flash firmware when coming from NSPanelManager firmware? `QUESTION` 

### ISSUE THREAD

**Issue by WEBudoGT** [Blackymas/NSPanel_HA_Blueprint#1626]
### Question

How to flash firmware when coming from NSPanelManager firmware?

### Additional Details

I tried flashing without noticing that if comming from another firmware some other steps should be done first.
I was using NSPanelManager firmware from this project: https://github.com/NSPManager/NSPanelManager/tree/main
After flashing with standard procedure if I check logs on ESPhome I get the following:

rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6608
load:0x40078000,len:15060
ho 0 tail 12 room 4
load:0x40080400,len:3816
entry 0x40080698
I (56) boot: ESP-IDF 4.4.5 2nd stage bootloader
I (56) boot: compile time 13:17:47
I (56) boot: chip revision: v3.0a         01 00 00009000 00002000
I (97) boot:  1 phy_init         RF data          01 01 0000b000 00001000
I (105) boot:  2 app0             OTA app          00 10 00010000 001c0000
I (112) boot:  3 app1             OTA app          00 11 001d0000 001c0000
I (120) boot:  4 nvs              WiFi data        01 02 00390000 0006d000
I (128) boot: End of partition table
I (132) boot: No factory image, trying OTA 0
I (137) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=2fbb4h (195508) map
E (216) esp_image: invalid segment length 0xffffffff
E (216) boot: OTA app partition slot 0 is not bootable
E (216) esp_image: image at 0x1d0000 has invalid magic byte (nothing flashed here?)
E (225) boot: OTA app partition slot 1 is not bootable
E (230) boot: No bootable app partitions in the partition table
ets Jul 29 2019 12:21:46

Please advise (hope have not bricked it?)

**Comment by edwardtfn** [comment]
What if you go to ESPHome Dashboard, can you see a box related to your device? Is the device reporting as "online"?
Can you get the logs from that page?

**Comment by WEBudoGT** [comment]
It shows as offline right after flashing, and going to logs shows nothing.
I remove the GND to IO jumper and restart the unit and the logs are what I
posted initially.

**Comment by WEBudoGT** [comment]
I ran another test and got this:

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:6988
load:0x40078000,len:13100
ho 0 tail 12 room 4
load:0x40080400,len:3884
entry 0x40080688
I (31) boot: ESP-IDF HEAD-HASH-NOTFOUND 2nd stage bootloader
I (31) boot: compile time 11:39:04
I (31) boot: chip revision: 3
I (35) boot_comm: chip revision: 3, min. bootloader chip revision: 0
I (42) boot.esp32: SPI Speed      : 40MHz
I (47) boot.esp32: SPI Mode       : DIO
I (51) boot.esp32: SPI Flash Size : 4MB
I (56) boot: Enabling RNG early entropy source...
I (61) boot: Partition Table:
I (65) boot: ## Label            Usage          Type ST Offset   Length
I (72) boot:  0 nvs              WiFi data        01 02 00009000 00010000
I (79) boot:  1 otadata          OTA data         01 00 0001d000 00002000
I (87) boot:  2 phy_init         RF data          01 01 0001f000 00001000
I (94) boot:  3 ota_0            OTA app          00 10 00020000 001f0000
I (102) boot:  4 ota_1            OTA app          00 11 00210000 001f0000
I (110) boot: End of partition table
I (114) boot_comm: chip revision: 3, min. application chip revision: 0
I (121) esp_image: segment 0: paddr=0x00020020 vaddr=0x3f400020 size=0x38144 (229700) map
I (217) esp_image: segment 1: paddr=0x0005816c vaddr=0x3ffbdb60 size=0x042d4 ( 17108) load
I (225) esp_image: segment 2: paddr=0x0005c448 vaddr=0x40080000 size=0x00404 (  1028) load
I (226) esp_image: segment 3: paddr=0x0005c854 vaddr=0x40080404 size=0x037c4 ( 14276) load
I (239) esp_image: segment 4: paddr=0x00060020 vaddr=0x400d0020 size=0x11e190 (1171856) map
I (688) esp_image: segment 5: paddr=0x0017e1b8 vaddr=0x40083bc8 size=0x165e0 ( 91616) load
I (743) boot: Loaded app from partition at offset 0x20000
I (743) boot: Disabling RNG early entropy source...
�������ets Jul 29 2019 12:21:46

**Comment by WEBudoGT** [comment]
Sorry... It was the 5v power source.
Now it works like a charm.

Thanks for your support @edwardtfn
