### ISSUE TITLE
Not connect to hidden SSID?

### ISSUE THREAD

**Issue by r719git** [Blackymas/NSPanel_HA_Blueprint#1629]
### TFT Version

4.2.1

### ESPHome Version

4.2.1

### Blueprint Version

4.2.1

### Panel Model

NSPanel EU Model

### What is the bug?

I have used hidden wifi SSID. After 4.2.1 NSpanel connect only to unhidden Wi-Fi!

### Steps to Reproduce

![20240114_102259](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/73180312/99bceebf-bdc5-4353-b4c6-9b7b5d99ca7f)

**Comment by edwardtfn** [comment]
Could you please share your panel's yaml? Please remove sensitive info before sharing (like you WiFi password).

Have you looked at this customization required for hidden networks?
https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/customization.md#hidden-wi-fi

**Comment by r719git** [comment]
Thank You for Your help. I added this customization and it worked:

_wifi:
  networks:
    - id: !extend wifi_default
      hidden: true
  fast_connect: true_

I must mention that earlier versions of 4.1.x did not require this change in the panel's yaml.
