### ISSUE TITLE
Initial installation doesn't work - Nspanel EU

### ISSUE THREAD

**Issue by tech2mar** [Blackymas/NSPanel_HA_Blueprint#1634]
I recently bought a second panel, but i fail to flash it for the first time.

Is there a different method to put the panel in flashing mode?

Is there a difrence between Panels? My new one says 1.8.1 update version 2023.
I can't see how it fails other than that.

Thanks

**Comment by edwardtfn** [comment]
I'm not aware about any difference, but maybe if you send some pictures of your panel and it's board we can try to help you.

Is your wiring like this one?
https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/install.md#flashing-the-device-for-the-first-time

**Comment by geni0602** [comment]
> I recently bought a second panel, but i fail to flash it for the first time.
> 
> Is there a different method to put the panel in flashing mode?
> 
> Is there a difrence between Panels? My new one says 1.8.1 update version 2023. I can't see how it fails other than that.
> 
> Thanks

Are you getting an error while flashing, or it is not possible to flash dou to failing to connect to esp? 

To boot in flash mode you have to connect IO0 with GND during powering up. Chack your cables and connectors. Maybe there was no contact and the panel was not in flash mode

**Comment by geni0602** [comment]
If you have esp tool.py you can run to check the flash_id. You have to check the correct serial port
esptool.py --port /dev/ttyUSB0 flash_id

**Comment by tech2mar** [comment]
I will check that on time, it's only a thing to boot into flash that's for sure.

**Comment by edwardtfn** [comment]
Hey @tech2mar, are you still facing this issue or should we code this thread?

**Comment by tech2mar** [comment]
I’ve tried everything with this device, and it’s clear it’s just not working right. I'm done wasting time on it and have decided to stop trying to get it to work. It seems to be defective. I'll be looking to get a new one instead.
