### ISSUE TITLE
Klimasteuerung Automatik Modus

### ISSUE THREAD

**Issue by T-abr** [Blackymas/NSPanel_HA_Blueprint#164]
Hi Blackymas,

nochmal vielen dank für das echt gelungene Projekt. Es macht spaß damit zu arbeiten.
Wäre es möglich bei der Raumtemperatursteuerung nicht nur ein/aus zu schalten sondern auch in den Automatikmodus umzuschalten?

Gruß

**Comment by Blackymas** [comment]
Hallo,

danke das freut uns ;)


Climate ist leider ein schweres Thema wie die Geräte sehr träge sind zum anderen macht das auch gefühlt jeder anders.

Die Anfrage hatten wir auch schon einmal, ich finde nur das Ticket gerade nicht mehr.

Aktuell ist es nicht möglich und steht auch nicht weit oben auf der Roadmap - wir haben das Thema aber im Hinterkopf.

ich gehe davon aus wenn wir jetzt die anderen wichtigen Themen und Request bearbeitet haben, werden wir noch einmal einen Blick darauf werfen. Das wird aber nicht in den nächsten Tagen oder Wochen passieren

**Comment by MarkuZP** [comment]
Würde mich auch sehr interessieren. Bei Lovelace geht das.

**Comment by Blackymas** [comment]
Das es technisch geht wissen wir nur ist das nicht eben in 5 min gemacht und wir arbeiten gerade an anderen wichtigen punkten. Daher hab ich es als "New Feature Request" gekennzeichnet.

Leider ist das Thema Climate eins der schwersten bei der Umsetzung - wenn wir die Zeit finden werden wir es prüfen.

Aktuell arbeiten wir am nächsten Release was folgendes beinhalten wird
- Notification 
- Button Bestätigung - sprich soll die Aktion wirklich ausgeführt werden zb für Haustür, Rolltore oder auch für kleine Kinder bzw ältere Menschen
- einen eigenen indoor sensor zu hinterlegen
- und ein paar andere kleiner Sachen

**Comment by MarkuZP** [comment]
Darauf freue ich mich sehr! Das Projekt ist wirklich sehr gelungen! Weiter so und vielen Dank für Eure gute Arbeit!

**Comment by Blackymas** [comment]
Hi,

ich schließe das Ticket, weil es einen weiteren Request dazu gibt.

Da der andere Request auf EN ist macht es wahrscheinlich mehr sinn den En Request offen zu lassen also den Deutschen.

ich werde dort diesen Beitrag verlinken.

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/213
