### ISSUE TITLE
`BUG` getting "NSPanel component version mismatch" after ESPHOME update 2023.12.5?

### ISSUE THREAD

**Issue by cs13368** [Blackymas/NSPanel_HA_Blueprint#1642]
### ESPHome Version

2023.12.5

### Blueprint Version

4.2.1

### Panel Model

NSPanel US Model

### What is the bug?

NSPanel component version mismatch and Notification: 

### Steps to Reproduce

NSPanel component version mismatch
There's a version mismatch between NSPanel_HA_Blueprint components. Please update all the components to the same version.

Panel: nspanel1
TFT: 4.1.3
ESPHome: 4.2.1
Blueprint: 4.2.1 (expected 4.2.1)

**Comment by andythomas** [comment]
Did you [upload](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/install.md#upload-tft) the new TFT version?

**Comment by edwardtfn** [comment]
## Update TFT

1. (**Arduino only**) Download from our [GitHub repository](https://github.com/Blackymas/NSPanel_HA_Blueprint/) the latest version of the TFT file relative to your panel's model.
2. (**Arduino only**) Upload this file to your local www (http) server. Please use the same URL as indicated by the substitution `nextion_update_url` in your device's YAML.
3. Go to ***Settings --> Devices & Services --> Integrations***, select the display under the ESPHome integration.
4. Press the switch "**Update TFT Display**" under **Configuration**.
5. The display starts the update process and then restarts.

**Comment by wobi07** [comment]
Gleiches Problem bei mir. Nach dem heutigen Update hatte ich obige Fehlermeldung TFT Display 4.1 
Ich habe dann wie beschrieben die neue Version 4.2 geladen. Nun habe ich auf dem Display NSPanel stehen "Sytem Data Error" Logs kommt "Nextion ist nicht verbunden" 

---------------------------------------

Same problem for me.
After today's update I had the above error message TFT Display 4.1
I then loaded the new version 4.2 as described.
Now I have "System Data Error" on the display NSPanel 
Logs comes "Nextion is not connected"

**Comment by synack666** [comment]
I have the same problem as wobi07, tft re-upload does not seem to work, in the log of ESPHome it says that I have pressed "upload" but nothing changes on the display.
[logs_nspanel_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13949503/logs_nspanel_run.txt)

**Comment by wobi07** [comment]
Ich habe 2 NSPanel und habe an beiden die blank.tft geladen und danach wieder auf ...eu.tft
Auf beiden NSPanel wird bis zu einer bestimmten %geladen (zB. 26% / 28% / 86%) dann bleibt es stehen und passiert nichts mehr!
Mehrfach versucht!

---------------------------------------------

I have 2 NSPanels and have loaded blank.tft on both and then reloaded ...eu.tft
On both NSPanels it loads up to a certain % (e.g. 26% / 28% / 86%) then it stops and nothing happens!
Tried several times!

**Comment by edwardtfn** [comment]
@wobi07, could you please try switching to `esp-idf` just for the upload, then you switch back to your original settings?
Please see more details here: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/tft_upload.md#consider-changing-the-framework

**Comment by edwardtfn** [comment]
@synack666, could you please collect logs again, but this time make sure it includes from the moment your device starts (your can force a reboot from the device's page in HA), then wait 15s, press the "Upload TFT display", wait until the system reboots and like 15s after that.
Send all the logs and we will take a look on what happens here.

**Comment by edwardtfn** [comment]
@synack666, could you please try switching to `esp-idf` framework just for this upload?
https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/tft_upload.md#consider-changing-the-framework

If you do this framework change wirelessly, please remember to revert back after the upload is successful.

**Comment by synack666** [comment]
> @synack666, could you please try switching to `esp-idf` framework just for this upload? https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/tft_upload.md#consider-changing-the-framework
> 
> If you do this framework change wirelessly, please remember to revert back after the upload is successful.

try to insert but result is failure, guess i try it wrong, where exact please?

substitutions:

###### CHANGE ME ######

  device_name: "nspanel" 
  wifi_ssid: xxxxxxxxx
  wifi_password: xxxxxxxx

##### CHANGE ME #####


##### DO NOT CHANGE ANYTHING! #####

  nextion_update_url: "http://192.168.0.171:8123/local/nspanel_eu.tft" # URL to local tft File
packages:
  ##### download esphome code from Github
 remote_package:
  url: https://github.com/Blackymas/NSPanel_HA_Blueprint
  ref: main
  files: [nspanel_esphome.yaml]
  refresh: 300s

**Comment by wobi07** [comment]
nfortunately, I cannot change the framework.
This gives me more errors! (see picture)

I noticed that I can't load the tft in blank.tft or eu.tft locally e.g. nextion_update_url: "http://192.168.178.3:8123/local/nspanel_blank.tft" but via nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" I get at least the blank.tft loaded and with eu.tft it hangs.
![Bildschirmfoto 2024-01-16 um 14 39 52](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/36563046/c48b432f-e40d-4278-87b8-7cbef2750a85)

**Comment by wobi07** [comment]
my mistake i had put the framework direct at the beginning and got the error message.
Now I have the addition
esp32:
  framework:
    type: esp-idf
at the very end and it went through.
However, it took a very long time until the run was completed!
Also the initialization! Had already thought that the display was now hanging here, but after a long wait it worked and everything is running again!
Thank you!!!
Problems are solved for me!
![Uploading tempImage7zALKp.gif…]()

**Comment by synack666** [comment]
update: eu.tft online is loading!!!

Display comes back, very slow and some measurements still missing, will wait a litle bit...

**Comment by edwardtfn** [comment]
@cs13368, what about you? Still stuck with this?

**Comment by cs13368** [comment]
> @cs13368, what about you? Still stuck with this?
I downloaded the newest versions of everything and now it is working.

**Comment by cs13368** [comment]
Thanks to everyone for their comments...  It gave me ideas what to try...
