### ISSUE TITLE
Chips , homepage custom buttons and icon visibility

### ISSUE THREAD

**Issue by DozoG** [Blackymas/NSPanel_HA_Blueprint#1647]
### Question

3 Questions

### Additional Details

Dear all,
Thanks for making the update process far less troublesome than before.

In the new version 4.2.1 I have the following issues

1) A switch used as chip does not appear on front page until after it has toggled of and on again.
(that is, it does not check state when starting the display or the page)

2) Homepage custom buttons do not show (at all) on front page until after they have been toggled 

3) Homepage custom button icons are almost invisible against the dark background (when off)
The same is true for all icons on button pages. The icons are almost invisible against the dark background of the buttons (when off)

Hope you can address those in future release or have a workaround.

**Comment by edwardtfn** [comment]
I believe all those issues are fixed already on v4.2.2.
Could you please update and let me know?
There's no need to update the TFT files, if you don't want, as those are exactly the same as v4.2.1, so if you update the Blueprint and ESPHome side you should be able to test that.

**Comment by rudgej** [comment]
THANK YOU!

I have put something on discussions as I have tried for the first time to use these today and I could not get anything to display. Toggle and they appear.

**Comment by DozoG** [comment]
Dear Edward,

Yes.. all three issues solved. Looks much better


I do notice a little difference in the way color is used between a "button" and a "switch" as the entity of a button on a button page.

- if the entity of a button on a button-page is a **button** ..
     When the page is opened, the icon has the assigned colour on a dark  button background.
     When the button is pressed, the background goes white for a bit, keeping the icon colour, then back to dark and the icon 
     turns grey 

- if the entity of a button on a button-page is a **switch** ..  (or an input_boolean)
    When the page is opened, the switches that are off have the grey icon on a dark button background
   The switches that are on have a coloured icon on a white background
(This is of course fully expected)


Thanks so much.
