### ISSUE TITLE
Activate Relay an boot (no Home Assistant available)

### ISSUE THREAD

**Issue by ghostridernrw40** [Blackymas/NSPanel_HA_Blueprint#1654]
### Question

Activate Relay an boot (no Home Assistant available)

### Additional Details

Hello Edward,

today we talked to other colleagues about the NSpanels and identified the following problem. In the event of a power outage or similar scenarios, Home Assistant is not immediately available, sometimes only very late, and the NSpanels wait for the blueprint. Now there is a need for the relays (1/2) to activate either relay 1 or 2 or both independently when starting the NSpanel. The background is, among other things, connected lamps and heaters (underfloor heating). How can you control this via the ESP Home configuration? The examples in the customizing area refer to times and not to events, e.g. boot. Greetings from Germany

**Comment by edwardtfn** [comment]
For an underfloor heating, you can set it using the [add-on Climate](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/addon_climate.md) and that will handle this situation when HA or Wi-Fi is not available.
In case of a power failure, it will return off, but with the first temperature update (which happens every minute), it will trigger the whole process and the relay will be automatically turned on when all the conditions are met. (current temperature, target temperature, min times, overrun, etc.).

For other things, let's say a light, it will be controlled locally if you are using the left button to control relay 1 or right button to relay 2, or if you have set fallback mode on the Blueprint settings.
However, working locally doesn't means it will return with the same state.
In fact, it always return with `OFF` state, however you can set this as a customization. Something like this:

```yaml
switch:
  - id: !extend relay_1  # Or relay_2
    restore_mode: RESTORE_DEFAULT_OFF
```

The available `restore_mode` options are:
- **RESTORE_DEFAULT_OFF** (default for panel's relays 1 and 2) - Attempt to restore state and default to OFF if not possible to restore.
- **RESTORE_DEFAULT_ON** - Attempt to restore state and default to ON.
- **RESTORE_INVERTED_DEFAULT_OFF** - Attempt to restore state inverted from the previous state and default to OFF.
- **RESTORE_INVERTED_DEFAULT_ON** - Attempt to restore state inverted from the previous state and default to ON.
- **ALWAYS_OFF** - Always initialize the switch as OFF on bootup.
- **ALWAYS_ON** - Always initialize the switch as ON on bootup.
- **DISABLED** - Does nothing and leaves it up to the downstream platform component to decide. For example, the component could read hardware and determine the state, or have a specific configuration option to regulate initial state.

**Comment by ghostridernrw40** [comment]
Hi Edward,

that worked perfect :-)

switch:
  - id: !extend relay_1  # Or relay_2
    restore_mode: ALWAYS_ON
