### ISSUE TITLE
`BUG` Climate Airco entity not working after upgrade from 4.1.4 to 4.2.2

### ISSUE THREAD

**Issue by rbr101** [Blackymas/NSPanel_HA_Blueprint#1656]
### TFT Version

4.2.2

### ESPHome Version

4.2.2

### Blueprint Version

4.2.2

### Panel Model

NSPanel EU Model

### What is the bug?

After upgrade the climate airco entity is not working anymore

### Steps to Reproduce

1) Click on the temperature sensor on the homescreen and it shows the climate entity, but lots of options are missing and i'm not able to change temperature. It only shows the entity name and temperature bar. 
2) if i add the same climate entity as a button to a button page the whole page is not displayed anymore and shows empty screen 

This only occurs for climate airco entities (4 airco's and 4 nspanels) For normal climate entity it works fine
I'm using several Mitsubishi airco's using the MHI-AC-Ctrl lib with esphome.

This used to work fine in version 4.1.4  before the upgrade, but now it's broken.
Or am i missing a breaking change ?

Cheers!

**Comment by edwardtfn** [comment]
Could you please share the entities attributes from Developer Tools, tab States?

**Comment by edwardtfn** [comment]
Probably related to this:
- #1649

**Comment by rbr101** [comment]
Seems indeed related to the bug's you're referring to.
Here the attributes for climate entities:

```
hvac_modes: off, heat_cool, cool, heat, fan_only, dry
min_temp: 18
max_temp: 30
target_temp_step: 0.5
fan_modes: auto, low, medium, high, quiet
swing_modes: off, both, vertical, horizontal
current_temperature: 13
temperature: 20
fan_mode: auto
swing_mode: off
icon: mdi:air-conditioner
friendly_name: Airco Nanoux
supported_features: 41
```

**Comment by feinadam** [comment]
I have tried it now it is working at me. Thank you!

**Comment by edwardtfn** [comment]
And using the blueprint from `dev` is the hard part, as you have to do the old way, manually copying the content of the file from the branch and pasting into your local system over the existing code. 😞

**Comment by rbr101** [comment]
Hmmm.. I will wait for the next release, if I break the panels my family starts complaining as they are mandatory for some tasks.  I have 6 panels so will be a lot of work to fix everything again...

**Comment by rbr101** [comment]
Thanks edwardtfn,

For releasing the fix so quickly, everything works fine now.

Keep up doing this great stuff!

/R
