### ISSUE TITLE
Error: Model does not match-Nextion Display bricked-Solution

### ISSUE THREAD

**Issue by Kleinheribert** [Blackymas/NSPanel_HA_Blueprint#166]
Scroll down for the english version!

Hallo zusammen!

Ich habe bei mir 6 Panels im Einsatz, momentan mit der Lösung Tasmota/joBR99, welche auch tadellos funktioniert. Um jetzt hier aber umzustellen, muss ich das Nextion ja flashen, damit die neue TFT Datei hochgeladen werden kann. Hier habe ich das über Tasmota versucht, scheitere aber an der Meldung des Displays "Model does not match". Sprich er lädt die FW hoch, aber das Display selbst lehnt diese ab. Ich habe jede der TFT Dateien probiert, es kommt immer die selbe Meldung.

![20230107_102941](https://user-images.githubusercontent.com/93861805/211144249-878c63b7-cf0c-4820-89d4-b5a4d9663a3f.jpg)

Edit: ich habe hier ein neues Topic aufgemacht, da ich nun etwas weiter bin. Da ich -egal bei welcher Version der TFT Datei (Selbst Original)- den Error bekommen habe, musste ich mir selbst eine "blank-tft" erstellen. Also den Nextion Editor runtergeladen und drauf los. Und natürlich das Nextion Display so gebrickt, dass es keinerlei andere TFT Datei mehr angenommen hat.  Nach einiger Recherche bin darauf gestoßen dass es einen Weg gibt das Nextion direkt zu flashen, über die Lötpunkte "TF -RX" und "TF_TX". Hier kann man zwei Leitungen anlöten.

![20230108_164952](https://user-images.githubusercontent.com/93861805/211206361-18c32ff0-8092-4f9f-903c-c5b15a99367c.jpg)

Nun die beiden Leitungen mit dem USB/TTL Konverter verbinden, das Panel selbst über den Connector unten mit 5V versorgen (KEINESFALLS 5V an J1 anlegen!!) und das Nextion Display mit der aktuellen HMI über den Nextion Editor direkt flashen. 
Nun funktioniert es endlich! Vielen Dank an Blackymas (+Team) für die exzellente Arbeit!
 
![20230108_165308](https://user-images.githubusercontent.com/93861805/211206370-0ad46f91-520d-47ff-8150-abbe1bffd6cb.jpg)

English:

Hi@all

I've got 6 Panels working with the solution of jobr99 which works excellent. But if I want to use the version from blackymas, I need to flash the Panel with "blank-tft". So I tried to upload "blank.tft" via tasmota and get the error above. I tried to make my own "blank.tft" with Nextion Editor while chosing the correct display model. And of course, I bricked it. So I can't upload any .tft file to my Nextion Display anymore.

So, after some research, I figured out that you can flash the Nextion Display direct via ttl and Nextion Editor. All you need is solder two wires on the Points "TF -RX" and "TF_TX". Then you support the Panel with 5V via the main connector (DO NOT USE J1 with 5V!!).
Flash the Nextion Display directly via Nextion Editor and blackymas' .HMI file and all works excellent!

**Comment by tikismoke** [comment]
Dis you try uploading the blank TFT before?

**Comment by Kleinheribert** [comment]
> Dis you try uploading the blank TFT before?

Hi, I've updated my Comment :)

**Comment by gris74** [comment]
hi,
I have the same error message when I try to upload the nspanel-blanck.tft, so I glad and full of hope when I read you.

I dont understand 100% your wiring, do you connect ground (you miss it) and 5v on the J2 connector and Tf-Tx and Tf-Rx (as you show) all 4 coming from the FT232 ? 
Can you make a picture of your setup ttl / nextion screen plug on ?

**Comment by Kleinheribert** [comment]
> hi, I have the same error message when I try to upload the nspanel-blanck.tft, so I glad and full of hope when I read you.
> 
> I dont understand 100% your wiring, do you connect ground (you miss it) and 5v on the J2 connector and Tf-Tx and Tf-Rx (as you show) all 4 coming from the FT232 ? Can you make a picture of your setup ttl / nextion screen plug on ?

Yes of course:
You connect the tx and rx from youtr ttl converter to the two solder pads. +5V and GND on the J2 Connector as shown. Then you can flash via Nextion Editor.
![20230108_190909](https://user-images.githubusercontent.com/93861805/211212391-079dd1a9-19bd-4b9c-8505-245b70e5b61b.jpg)
![20230108_190914](https://user-images.githubusercontent.com/93861805/211212397-aa1ca473-373d-4c4c-a9b1-2a80102d241f.jpg)
![20230108_190928](https://user-images.githubusercontent.com/93861805/211212402-f74f3447-eba7-424b-81f9-be22e06152c6.jpg)

**Comment by deejaybeam** [comment]
Thank you for sharing your solution!

**Comment by Blackymas** [comment]
@Kleinheribert 

WOW - danke für die Mühe und besonders fürs teilen!!!!

**Comment by gris74** [comment]
So many thanks for your solution, it is indeed **THE ultimate solution**, I was stuck with Model does not match for 3 days after an initial setup via the tutorial from Blackymas in a new NSPanel.

I use to upload first a blank nspanel creation in Nextion Edition and finally successfully upload the NSPanel from Blackymas.

My mistake was the connection to J2 I use the outside pin ground and 5V and when I plugin as your picture the MAGIC appear.

**Comment by Blackymas** [comment]
ja sollte eigentlich so sein - zumindest für die EU Version.


Du brauchst da shier oder NX4832F035_0110

**Comment by Kleinheribert** [comment]
> ja sollte eigentlich so sein - zumindest für die EU Version.
> 
> Du brauchst da shier oder NX4832F035_0110

Ja, letztere habe ich, wie oben im Bild auch erkennbar. Was mir gerade einfällt: Es kann sein, dass ich das blank.tft File bei Github mit Rechtsklick=> Speichern unter heruntergeladen habe, nicht über die Github Funktion. Hier gibt es auch Probleme, das HMI File beispielsweise ist nach der Aktion korrupt. Ich teste das noch einmal bei einem anderen Panel.

**Comment by deejaybeam** [comment]
Das könnte sein, die .gitattributes berücksichtigt meines wissens nur die tft und hmi files im root

**Comment by naofireblade** [comment]
Wer nicht löten mag, kann die Kabel an TX/RX auch temporär ran kleben. Hat bei mir auch prima funktioniert. Nur nicht am Tisch wackeln während des Flashens, sonst muss man erneut starten ;)

**Comment by Blackymas** [comment]
@Kleinheribert 
hast du es getestet? ich kann mir nicht vorstellen das du ein anderes Display hast bzw ein anderes File brauchst

**Comment by joBr99** [comment]
>Was mir gerade einfällt: Es kann sein, dass ich das blank.tft File bei Github mit Rechtsklick=> Speichern unter heruntergeladen habe, nicht über die Github Funktion. Hier gibt es auch Probleme, das HMI File beispielsweise ist nach der Aktion korrupt. Ich teste das noch einmal bei einem anderen Panel.

@Kleinheribert damit lädst du die Webseite runter, nicht die Datei da steht dann also `<html> ...` drin.

Das Nextion Display schaut beim flashen in den Header von der Datei, wenn da nicht das richtige Model steht kommt die Fehlermeldung; spielt keine Rolle ob es ein tft file ist oder irgendein ander Datenmüll.

**Comment by Blackymas** [comment]
Ich habe es gestern auch noch über einen anderen Weg versucht der auch ging. Hate im Display auch die Fehler Meldung Syntax Error. Solange ESPhome läuft kannst du via OTA das nspanel updaten und in esphome die Zeile einfügen

nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/dev/custom_configuration/nspanel_blank.tft"

Danach NSpanel flashen und via HA Devices TFT updaten.

Danach die Zeile wieder raus aus ESPhome neu via OTA flashen und wieder über HA Device tft upload machen.

Wie gesagt solange ESPHome funktioniert

**Comment by MarkuZP** [comment]
> nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/dev/custom_configuration/nspanel_blank.tft"

Habe es exakt so gemacht und bekomme dann auch diese Model does not match Meldung.

**Comment by Blackymas** [comment]
> > > Was mir gerade einfällt: Es kann sein, dass ich das blank.tft File bei Github mit Rechtsklick=> Speichern unter heruntergeladen habe, nicht über die Github Funktion. Hier gibt es auch Probleme, das HMI File beispielsweise ist nach der Aktion korrupt. Ich teste das noch einmal bei einem anderen Panel.
> > 
> > 
> > @Kleinheribert damit lädst du die Webseite runter, nicht die Datei da steht dann also `<html> ...` drin.
> > Das Nextion Display schaut beim flashen in den Header von der Datei, wenn da nicht das richtige Model steht kommt die Fehlermeldung; spielt keine Rolle ob es ein tft file ist oder irgendein ander Datenmüll.
> 
> > @Kleinheribert hast du es getestet? ich kann mir nicht vorstellen das du ein anderes Display hast bzw ein anderes File brauchst
> 
> Ihr habt beide recht, es lag am Download über Rechtsklick..Habe es heute noch einmal getestet, sobald man artig auf Download File geht, funktioniert es.
> 
> Zur Rettung meiner Ehre: Ich bin immerhin selbst drauf gekommen 🥇
> 
> Also: Don't drink and drive & don't download via right mouse button!

@MarkuZP

**Comment by loadamasta** [comment]
> und das Nextion Display mit der aktuellen HMI über den Nextion Editor direkt flashen.

Vielen Dank für die Lösung, habe dasselbe Problem. Die blank.tft ist drauf, Display bleibt nun aber permanent weiss. Beim Versuch die richtige .tft raufzuladen kommt dann wieder der Fehler. 

Nun möchte ich die hier beschriebene Lösung probieren. Was mir noch fehlt bzw. was ich noch nicht verstehe ist dieser Schritt der Lösung: "und das Nextion Display mit der aktuellen HMI über den Nextion Editor direkt flashen." Was genau muss man da machen? Danke.

**Comment by sparkydave1981** [comment]
Any tips for flashing the TFT with Nextion Editor?  I have it connect as per your instructions but I get the error:
```
Connection failed
Forced interrupt!
```

**Comment by HKUser1** [comment]
Hallo ich habe eine eu Panel erfolgreich geflasht nachdem ich die Blank Datei mit Lötaktion direkt aufgespielt habe.
Jetzt wollte ich das gleiche mit einer us Version machen, alles perfekt das Dispaly steht hier und der QR Code ist zu sehen.... jetzt drücke ich auf update tft display. dann zuckt der QR Code kurz aber das wars dann.
Wo könnte der Fehler sein...

**Comment by wobi07** [comment]
> Ich habe es gestern auch noch über einen anderen Weg versucht der auch ging. Hate im Display auch die Fehler Meldung Syntax Error. Solange ESPhome läuft kannst du via OTA das nspanel updaten und in esphome die Zeile einfügen
> 
> nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/dev/custom_configuration/nspanel_blank.tft"
> 
> Danach NSpanel flashen und via HA Devices TFT updaten.
> 
> Danach die Zeile wieder raus aus ESPhome neu via OTA flashen und wieder über HA Device tft upload machen.
> 
> Wie gesagt solange ESPHome funktioniert

👍Super ❗️
So hat es endlich geklappt.
Habe seit über 3 Tage geflash / montiert / auseinander genommen und verzweifelt 🤬🤯
Aber jetzt ist er am Leben 🤩 Du bist mein Held❗️

Nur kann ich ich kein Licht schalten 🤔 wenn ich die Glühbirne 💡 rausschraube ist NSpanel aus. Glühbirne ist OK leuchtet aber nicht (keine Birnen)

**Comment by HKUser1** [comment]
Dann hast Du kein N- in der Schalterdose bzw. die Zuleitung zur Birne/Leuchte an den N- Anschluss des NS Panels angeschlossen…Am 17.09.2023 um 15:27 schrieb wobi07 ***@***.***>:﻿

Ich habe es gestern auch noch über einen anderen Weg versucht der auch ging. Hate im Display auch die Fehler Meldung Syntax Error. Solange ESPhome läuft kannst du via OTA das nspanel updaten und in esphome die Zeile einfügen
nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/dev/custom_configuration/nspanel_blank.tft"
Danach NSpanel flashen und via HA Devices TFT updaten.
Danach die Zeile wieder raus aus ESPhome neu via OTA flashen und wieder über HA Device tft upload machen.
Wie gesagt solange ESPHome funktioniert

👍Super ❗️
So hat es endlich geklappt.
Habe seit über 3 Tage geflash / montiert / auseinander genommen und verzweifelt 🤬🤯
Aber jetzt ist er am Leben 🤩 Du bist mein Held❗️
Nur kann ich ich kein Licht schalten 🤔 wenn ich die Glühbirne 💡 rausschraube ist NSpanel aus. Glühbirne ist OK leuchtet aber nicht (keine Birnen)

**Comment by DavidWicks** [comment]
> Any tips for flashing the TFT with Nextion Editor? I have it connect as per your instructions but I get the error:
> 
> ```
> Connection failed
> Forced interrupt!
> ```

Did you get it to work ?  I get the same error.

**Comment by DavidWicks** [comment]
> > Any tips for flashing the TFT with Nextion Editor? I have it connect as per your instructions but I get the error:
> > ```
> > Connection failed
> > Forced interrupt!
> > ```
> 
> Did you get it to work ? I get the same error.

I found using my US panel the tx rx pads need to be connected directly to my ftdi adapter.  tx-tx    rx-rx.

**Comment by wobi07** [comment]
![NSpanel 1](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/36563046/c767c63f-8098-4703-a0a5-b06c043bf2c4)
![NSpanel 2](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/36563046/9c81f5d6-3c99-4bfc-81a2-ded8a717fe58)

**Comment by wobi07** [comment]
Top❗️
Danke hat wieder super alles geklappt🤗👍

**Comment by Buddeli** [comment]
Ich habe noch einen weiteren Lösungsansatz...

**Ausgangslage:**
Ich hatte auch Tasmota mit der Lovelace UI auf dem NSPanel installiert. Als ich auf  ESPHome wechseln wollte, kam auch die Meldung "Model does not match". Da ich in einer kompletten Apple-Umgebung wohne, war der gezeigte Ansatz von @Kleinheribert nicht möglich (kein Windows-PC). Das hat mich zum weitersuchen angetrieben  (gezwungenermassen). Ich habe aktuell die Homeassistant-Umgebung auf einem RasperryPi4. 

**Am Schluss erkanntes Problem:** 
Ich war zu faul für den File-download und Upload und hatte einfach den Code der [nspanel_blank.tft](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/nspanel_blank.tft) kopiert, in config einen "www" Ordner erstellt und darin eine nspanel_blank.tft Datei erstellt und den Code eingefügt. Das sah eigentlich gut aus aber wenn ich die beiden Files verglichen habe, war es doch nicht der selbe Code. 

**Lösung:**

1.  In Config ein Ordner Names "www" erstellen, und darin mittels HA And-on "File Editor" die beiden Dateien [nspanel_blank.tft](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/nspanel_blank.tft) und [nspanel_eu.tft](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/nspanel_eu.tft) hochladen
2. tasmota32-nspanel.bin auf das Panel Flashen, dann auf das Wlan vom Panel zugreifen und dann da Eigene Wlan einstellen.
3. Dann auf die IP zugreifen von dem Panel und auf der Tasmota Oberfläche
4. Configuration -> Configure Other in Template
`{"NAME":"NSPanel","GPIO":[0,0,0,0,3872,0,0,0,0,0,32,0,0,0,0,225,0,480,224,1,0,0,0,33,0,0,0,0,0,0,0,0,0,0,4736,0],"FLAG":0,"BASE":1,"CMND":"ADCParam 2,11200,10000,3950 | Sleep 0 | BuzzerPWM 1"}` Eintragen und **Activate** an klicken.

5. Dann auf Console -> Console
`Backlog UrlFetch https://raw.githubusercontent.com/joBr99/nspanel-lovelace-ui/main/tasmota/autoexec.be; Restart 1`
6. Enter
7. `FlashNextion http://homeassistant.local:8123/local/nspanel_blank.tft`
8.  Enter (nun sollte der QR-Code auf dem Display ersichtlich sein. Sonst hat es nicht geklappt)
9. ESP-Home wie in der Doc beschrieben auf das NSPanel flashen
