### ISSUE TITLE
`Question`  After Updating today I get a problem in HAs

### ISSUE THREAD

**Issue by whitexichigo** [Blackymas/NSPanel_HA_Blueprint#1679]
### Question

i updated today and since then i get no pages or anything on the screen

### Additional Details

I also get that 
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/48635440/0125bb27-5f35-43c5-a040-500776810c1f)

**Comment by dkvhin** [comment]
Having the same issue, after update, I can no longer open any pages ( button pages, entity etc. )

**Comment by edwardtfn** [comment]
> Having the same issue, after update, I can no longer open any pages ( button pages, entity etc. )

This is a different thing. Could you please create another bug report so we can try to solve that?

**Comment by edwardtfn** [comment]
@whitexichigo, you have to update the Blueprint: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/howto.md#update-blueprint

**Comment by dkvhin** [comment]
> > Having the same issue, after update, I can no longer open any pages ( button pages, entity etc. )
> 
> This is a different thing. Could you please create another bug report so we can try to solve that?

Pardon, I have the same issue as above screenshot. HA notification with invalid blueprint version, even though I have followed all the update steps : (re-import blueprint, restart automation, restart HA, update the TFT file )

**Comment by edwardtfn** [comment]
> Pardon, I have the same issue as above screenshot. HA notification with invalid blueprint version, even though I have followed all the update steps : (re-import blueprint, restart automation, restart HA, update the TFT file )

Could you please share a screenshot with the notification?

**Comment by bugtoo** [comment]
Hello everybody, this is the same issue as the crash due to missing climate entity: it is fixed in the dev branch an due for 4.2.4 (tested working).

**Comment by edwardtfn** [comment]
Hi @bugtoo,

At least the picture in the original post here shows a different thing. In this case here, the Blueprint is v4.1.4 while the other components (ESPHome and TFT) are on v4.2.3.

**Comment by dkvhin** [comment]
> > Pardon, I have the same issue as above screenshot. HA notification with invalid blueprint version, even though I have followed all the update steps : (re-import blueprint, restart automation, restart HA, update the TFT file )
> 
> Could you please share a screenshot with the notification?

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7764035/50e5ea0a-8245-4ca9-8cef-0347ea7ad470)

**Comment by edwardtfn** [comment]
Ok, this case is not the same as the original post here, as in your case all the 3 versions are the same. Most likely you have the issue mentioned by @bugtoo related to a crash when a climate entity isn't used.
I will push a fix for this in a few minutes.

**Comment by dkvhin** [comment]
> Ok, this case is not the same as the original post here, as in your case all the 3 versions are the same. Most likely you have the issue mentioned by @bugtoo related to a crash when a climate entity isn't used. I will push a fix for this in a few minutes.

Cool. Thank you very much

**Comment by edwardtfn** [comment]
v4.2.4 was released.

**Comment by dkvhin** [comment]
> v4.2.4 was released.

Working now. thank you

**Comment by edwardtfn** [comment]
@whitexichigo, what about you? Still stuck with this?

**Comment by whitexichigo** [comment]
> @whitexichigo, what about you? Still stuck with this?

i just did the blueprint re-import, it solved my problem directly thank you very much,
sorry for late respone.

thanks for your amazing work here
