### ISSUE TITLE
Specify motion sensor to wake up the display

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1687]
Hi,

I now have a node red automation to wake up the display when motion is detected.
Would be nice if you can specify this in the blueprint.

just an idea.

regards,
R

_Originally posted by @rbr101 in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1684_

**Comment by flex420** [comment]
that would be awesome for home assistant too

**Comment by edwardtfn** [comment]
Please tell me more about your current automation... It wakes up the panel and then you leave to the panel's routine to sleep again or do you have a command to sleep in your routine?

I think if we create this, the panel should be awake while the movement/presence persists, or at least have an option for this, but this makes it a bit more complex, as the sleep process will have to change. Which is not that hard, but then we will have two places to set sleep time and one will be ignored.
Any ideas?

**Comment by rbr101** [comment]
Please tell me more about your current automation... It wakes up the panel and then you leave to the panel's routine to sleep again --> Yes it does that exactly.

So if I walk into a room the sensor detect motion and the display turns on, then after the normal timeout (60 sec) the display goes into sleep mode again.  This is enough time to read the time /temperature etc from the display. I have this in most rooms.  I also have node red automations for:

- If I switch on/off the lights with a wall switch/phone the display shows the specific light settings
- If i'm playing media and the media title changes (so you can see the artists/song name)


/R

**Comment by edwardtfn** [comment]
Nice.
I will look at that. Maybe start with something very simple, then we improve over time.

**Comment by rbr101** [comment]
Yes, just keep it simple to start with,  it think it will be  a good start. 

/r

**Comment by edwardtfn** [comment]
Implemented in `dev`. Pending some tests...

**Comment by rbr101** [comment]
That's great to hear. Amazing how fast !

Thanks,

**Comment by flex420** [comment]
that is an absolutly beautiful commit @edwardtfn - Thank you - cant wait to patch it and try out!

**Comment by edwardtfn** [comment]
I will close this for now and we can reopen if it isn't working well when released.

**Comment by edwardtfn** [comment]
We just released a patch with solves this: [v4.2.5 - Celebrating 1000 Stars with Enhanced Functionality and UI Improvements](https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v4.2.5)
Could you please update your system and let me know if the issue was solved?
