### ISSUE TITLE
Adjustable size of Clock (Home and Screensaver)

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1689]
Hi, i flashed my NsPanel today and i am very thankful for your hard work you have put into this!
I have one Feature Request: Please make the Size of the Clock adjustable.
I would prefer to see a bigger clock on my "home screen".

Also for Screensaver it would be perfect, if the Clock would be able to "fill" the screen.
Theank you!

_Originally posted by @iamthe1st in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1657_

**Comment by Daniel167** [comment]
Hello, have you a picture from screen saver. I very interessted. Thanks

**Comment by iamthe1st** [comment]
Hi, i opened the HMI File in the nextion Editor -- at first glance it seems, that that for each font every character is created/rendered. 
But the available characters can be defined - so for the selectable "Clock Fonts" numbers 0 to 9 and ":" would be enough.
This would save memory i guess.

**Comment by edwardtfn** [comment]
> But the available characters can be defined - so for the selectable "Clock Fonts" numbers 0 to 9 and ":" would be enough.
This would save memory i guess.

That's almost right... A bit more chars for the equivalent to those number on other languages, and also for "AM"/"PM", some separators (`:`, `-`, `,`, etc.) but it's right, we can reduce the number of chars. They have done something on this direction for the CJK languages.

**Comment by iamthe1st** [comment]
> Hello, have you a picture from screen saver. I very interessted. Thanks

Hi, i edited the HMI File by myself, and included a huge Font ( size 192 ) with only numbers and  :  so the size of the Nextion File only increased 230kB.

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/11601070/db7eb7b3-ea2a-4902-95b6-44e64fa7ac56)

So for my the "Screensaver" topic can be closed, because of i the availabilty of the source files the HMI File can be edited to o the individual needs.

**Comment by edwardtfn** [comment]
That looks nice!
I will keep this open as I'd like to look at a way to implement this for everyone.
I have to look at the minimum amount of chars to be able to display the time in all the supported languages... and have to find a place for the "AM/PM" string.

**Comment by plasterer41** [comment]
I just realised the clock screensaver has been implemented - brilliant! 
Would be great to have it larger as @iamthe1st has done. Well done mate!

**Comment by edwardtfn** [comment]
### 72px
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/030ba092-69d4-467d-b5ab-52979c94e742) ![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/ae56276f-10be-420c-a156-87f33d1fc322) ![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/0aecb76b-c7b1-4257-b2eb-caed513a1f06)

### 112px
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/689f7fa3-afe5-43e0-839c-a16ca32d0657) ![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/077e637c-4cbe-4f61-adb7-98631d24b17e) ![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/5093d1e7-be6b-4042-8e2d-84bf10d0bd2f)


### 192px
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/f00a61ef-3afe-4e3d-8431-cccec66e69a5) ![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/5d73a792-200d-4997-ac12-7392ce624e3d) ![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/3060bea9-4804-45d3-940e-64767e1f3577)

**Comment by plasterer41** [comment]
That would be excellent @edwardtfn

**Comment by plasterer41** [comment]
Which dev version is it in Edward?

**Comment by plasterer41** [comment]
I found it Edward but I will need to flash with esp-idf I assume to enable me to use v4.3 in dev.

I will try this when I get a chance this evening and feedback here.
Thanks again for your awesome work.

**Comment by edwardtfn** [comment]
You can add this to your yaml enforcing the arduino framework, so you can try v4.3:
```yaml 
esp32:
  framework:
    type: Arduino
```

**Comment by plasterer41** [comment]
I must be putting that code in the wrong place on my substitution file. I will try to flash with idf later this evening.

**Comment by plasterer41** [comment]
Hi Edward, I got esp-idf installed on all 4 panels tonight however when I then try to update them with the dev branch I immediately receive this....
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/47918336/f46d10b3-e15a-42a0-920c-e86231def86d)

**Comment by plasterer41** [comment]
any ideas what I am doing wrong?

much appreciated.

**Comment by plasterer41** [comment]
ignore me - got it sorted - I just had to remove the esp-idf from the yaml file again and the download has started :-)

**Comment by plasterer41** [comment]
Edward, I installed esp-idf successfully on all 4 panels and I installed the dev successfully on one panel that I wanted to test. The font increase worked perfectly. I reverted the panel back to 4.2.6 though as there were chips missing etc. I just wanted to confirm that the dev worked for the increased font of the clock on screensaver

**Comment by timeames85** [comment]
This might well count as a separate enhancement, but are there any plans to allow the hardware button labels on the screensaver page too? Especially with the hw buttons still being active while asleep/showing the screensaver (probably wouldn't need the on/off state indicators as pressing either hw button would wake the screen and show this anyway.) Might help as a button locator in the night :)

**Comment by edwardtfn** [comment]
> This might well count as a separate enhancement, but are there any plans to allow the hardware button labels on the screensaver page too? Especially with the hw buttons still being active while asleep/showing the screensaver (probably wouldn't need the on/off state indicators as pressing either hw button would wake the screen and show this anyway.) Might help as a button locator in the night :)

Why don't you create another enhancement request.
I don't think this is hard to implement, however it will add a few steps to create the US Landscape model, as part of the procedure is use a display with EU model and rotate those bars.
But it is totally feasible.

**Comment by edwardtfn** [comment]
This is available on `dev` and will be part of the v4.3 release. I will close this for now, so it makes easier to control the backlog, but please feel free to keep the discussion here or to reopen-it if the issue persists.
