### ISSUE TITLE
Feature Request: Remote wake screen

### ISSUE THREAD

**Issue by oliveramays** [Blackymas/NSPanel_HA_Blueprint#170]
Maybe there already is a way? I can't figure out how to wake the screen with a command.

I would love to make an automation that wakes the screen when the motion sensor near my nspanel is triggered.
Looks like I can remotely set sleep mode when the room is clear so the display goes off after a while but it doesn't wake up when sleep mode is remotely disabled.

Potentially useful feature for those who want to be greeted by their nspanel automatically?

But please do correct me if this is already doable.

Thanks!

**Comment by pehovorka** [comment]
Hi, you can do that quite easily, it was already answered here: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/99#issuecomment-1345538330

Here is how I use it when the motion sensor is trigerred:
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/36507549/211422256-5a661354-e1b5-475c-918f-a534d2b7abcf.png">

**Comment by Blackymas** [comment]
Thanks @pehovorka 

@oliveramays I think I can close the ticket or is there still a question?

**Comment by oliveramays** [comment]
I think Pehovorka nailed it to be honest, I hadn't thought at all about triggering a service to change the page!

Thanks for the response.

**Comment by Blackymas** [comment]
perfect :)
