### ISSUE TITLE
`Bug` ESPHome cannot provide a valid Blueprint version.

### ISSUE THREAD

**Issue by luckyzor** [Blackymas/NSPanel_HA_Blueprint#1703]
### TFT Version

4.1.1

### ESPHome Version

4.2.2

### Blueprint Version

4.1.1

### Panel Model

NSPanel EU Model

### What is the bug?

Can't use blueprint

### Steps to Reproduce

updated esphome of nspanel

### Home Assistant logs

```logs
NSPanel invalid Blueprint version
ESPHome cannot provide a valid Blueprint version.

Panel: nsp01
TFT: 4.1.1
ESPHome: 4.2.2
Blueprint (reported by ESPHome):
Blueprint (expected): 4.1.1
```

**Comment by illuzn** [comment]
We need your yaml please.

**Comment by edwardtfn** [comment]
```
NSPanel invalid Blueprint version
ESPHome cannot provide a valid Blueprint version.

Panel: nsp01
TFT: 4.1.1
ESPHome: 4.2.2
Blueprint (reported by ESPHome):
Blueprint (expected): 4.1.1
```

You have a version mismatch. Please update all components to the latest version.
https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/howto.md#update-blueprint

**Comment by luckyzor** [comment]
So, I didn't know I needed to update the blueprint manually.
As I had issues with the tft file it was with a local link, so not updated neither.
Update all of them and it works.
Sorry folks.

**Comment by roynasser** [comment]
Forgot about having to update the blueprints (though I've done it in the past), thanks for this post!
