### ISSUE TITLE
`Bug` alarm keypad cannot arm disarm alarm 4.2.4

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#1705]
### TFT Version

4.2.4

### ESPHome Version

4.2.4

### Blueprint Version

4.2.4

### Panel Model

NSPanel US Model

### What is the bug?

Cannot alarm or disarm from nspanel 

### Steps to Reproduce

Press alarm icon
Select arm (alarm is disarmed)
Press check mark nothing happens stays on keypad
Enter code and check nothing happens
(My alarm requires a code but previously I could arm without entering one)

Select disarm (alarm is armed)
Enter code and checkmark does not disarm panel. 

nspanel does correctly show status of alarm when I ale disarm through HA. 
Arming disarming with HA works as before - nothing seems to have changed in HA.

**Comment by Doughboy68** [comment]
Yes I have that set.

**Comment by edwardtfn** [comment]
So, can you see any error message related to this automation on your Home Assistant logs (Settings > System > Logs)?

**Comment by edwardtfn** [comment]
And could you please go to Developer Tools, tab States, find the entity related to this alarm and share it's state and attributes?
Please make sure there's no sensitive info being shared.

**Comment by Doughboy68** [comment]
I could not find anything in HA logs.
Here is State attributes:

code_format: number
changed_by: null
code_arm_required: true
friendly_name: Home Alarm
supported_features: 15

Later on I can try the nspanel_us landscape... maybe is a bug in the tft.

**Comment by edwardtfn** [comment]
Have you had any success from your side? I couldn't duplicate this issue. 😞

**Comment by Doughboy68** [comment]
No same issue. I have five panels and none work with alarm code. I am not using encryption in ESPHome devices if this matters now?

**Comment by edwardtfn** [comment]
Do you know if that was working properly in a previous version?

**Comment by Doughboy68** [comment]
Sorry for late reply, have been busy.
Yes it was working before.
I just tried US Landscape and works fine. The regular US tft has the issue.

**Comment by edwardtfn** [comment]
I believe this is solved in `v4.2.5dev`.

**Comment by edwardtfn** [comment]
We just released a patch with solves this: [v4.2.5 - Celebrating 1000 Stars with Enhanced Functionality and UI Improvements](https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v4.2.5)
Could you please update your system and let me know if the issue was solved?
