### ISSUE TITLE
Mdi icon missing

### ISSUE THREAD

**Issue by bkbartk** [Blackymas/NSPanel_HA_Blueprint#1709]
### Question

is this a limitation of the screen or is it possible to add?

### Additional Details

Hello
I'm using this mdi icon `mdi:television-speaker`
It's not in the list and also not in the blueprint.
is it possible to add this one? or is the list on hmi a limited set?

**Comment by edwardtfn** [comment]
It is a limitation of the screen and it's fonts. Only the icons from this list are supported: https://htmlpreview.github.io/?https://github.com/jobr99/Generate-HASP-Fonts/blob/master/cheatsheet.html
