### ISSUE TITLE
`Enhancement` Climate addon use sensor from HA or internal as fallback

### ISSUE THREAD

**Issue by XtracT** [Blackymas/NSPanel_HA_Blueprint#1710]
### Enhancement Summary

Climate addon add external sensor as default or internal as fallback

### Detailed Description

Hello!

First of all, many thanks for this project! It is working great so far :dagger: 

Until this last update I was basically using Home Assitant's thermostat, but now I wanted to add the climate addon as a fallback. Main drawback I have is that while in HA's thermostat I can specify an average of multiple temperature sensors, the climate addon is fixed to the internal NSPanel sensor. 

As far as I understood it from ESPHome's thermostat, it should be possible to use any sensor by adding `sensor: my_temperature_sensor` . However, I do not know if it is possible or it if will actually work, as well as if the fallback would be the internal temperature sensor. 

Is this something that I am missing how to configure, something that could be added or just maybe not a good idea?

BR;

/Xtract

**Comment by edwardtfn** [comment]
Please take a look at this:
- #1446

**Comment by XtracT** [comment]
I missed that ticket, sorry for that! Maybe it could be added to the advanced configuration docs? I am pretty sure we are not going to be the only ones setting up this config...

Just one comment, the lambda function in #1446 is missing some brackets. I just leave here my full configuration on how I have made it work (v4.2.4):

`
substitutions:
  ###### CHANGE ME START ######
  device_name: "nspanel" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  ##### addon-configuration #####
  ## addon_climate ##
  heater_relay: "1"
  #temp_units: "°F"      # Temperatures in Fahrenheit
  temp_min: "16"        # Min supported temperature is 40°F
  temp_max: "24"        # Max supported temperature is 80°F
  temp_step: "0.5"        # Temperature granularity is 1°F
  heat_deadband: "0.5"  # Temperature delta before engaging heat
  heat_overrun: "0.2"   # Temperature delta before disengaging heat
  min_off_time: "0"
  min_run_time: "0"
  min_idle_time: "0"

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      - nspanel_esphome_addon_climate_heat.yaml    
    refresh: 300s

esp32:
  framework:
    type: esp-idf

time:
  - id: !extend time_provider
    timezone: "Europe/Berlin"

##### My customization - Start #####
sensor:
  - id: ha_temperature
    platform: homeassistant
    entity_id: sensor.home_temperature   # Please change this by the entity_id of your temperature sensor in Home Assistant

  - id: ha_humidity
    platform: homeassistant
    entity_id: sensor.home_humidity   # Please change this by the entity_id of your temperature sensor in Home Assistant

  - id: combined_temperature
    platform: template
    lambda: |-
      if (wifi_component->is_connected() and api_server->is_connected()) { // Testing both as WiFi is faster to detect issues
        return ha_temperature->state;
      } else {
        return temp_nspanel->state;
      }

climate:
  - id: !extend thermostat_embedded
    sensor: combined_temperature
    humidity_sensor: ha_humidity
    preset:
      - name: Home
        default_target_temperature_low: 20 °C
      - name: ECO
        default_target_temperature_low: 18 °C
      - name: Boost
        default_target_temperature_low: 22 °C

##### My customization - End #####
`
