### ISSUE TITLE
Fehler beim Kompilieren

### ISSUE THREAD

**Issue by corradodave** [Blackymas/NSPanel_HA_Blueprint#172]
Nachdem ich in ESP Home ein neues Device erstellt habe, den alten Code entfernt habe und den neuen eingefügt und die Datan geändert habe bekomme ich diese Meldung:

Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/adc/adc_sensor.cpp.o
In file included from src/esphome/components/adc/adc_sensor.h:4,
                 from src/esphome/components/adc/adc_sensor.cpp:1:
src/esphome/core/hal.h:14:10: fatal error: esp_attr.h: No such file or directory

**Comment by deejaybeam** [comment]
#121 hatten wir schon: Der Host auf dem du esphome installiert hast ist einfach zu schwach. Entweder zu wenig RAM oder CPU-Power. Du kannst nur das versuchen: https://esphome.io/changelog/2022.11.0.html#running-esphome-on-lower-powered-machines oder auf eine stärkere Maschine ausweichen.

**Comment by corradodave** [comment]
Danke hab es hinbekommen

**Comment by deejaybeam** [comment]
wie konntest du es dann lösen?

**Comment by corradodave** [comment]
Ich habe esphome deinstalliert, dann esphome (beta) installiert und den pi neu gestartet, dann ging es hat aber auch 1300 sekunden gedauert

**Comment by Jarnsen** [comment]
bei mir bringt er

`INFO Reading configuration /config/esphome/nspanel.yaml...
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing nspanel (board: esp32dev; framework: arduino; platform: platformio/espressif32 @ 5.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- WiFiClientSecure @ 2.0.0
|-- HTTPClient @ 2.0.0
Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/adc/adc_sensor.cpp.o
xtensa-esp32-elf-g++: error trying to exec 'cc1plus': execvp: No such file or directory
Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_connection.cpp.o
xtensa-esp32-elf-g++: error trying to exec 'cc1plus': execvp: No such file or directory
Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_frame_helper.cpp.o
xtensa-esp32-elf-g++: error trying to exec 'cc1plus': execvp: No such file or directory
Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_pb2.cpp.o
xtensa-esp32-elf-g++: error trying to exec 'cc1plus': execvp: No such file or directory
Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_pb2_service.cpp.o
xtensa-esp32-elf-g++: error trying to exec 'cc1plus': execvp: No such file or directory
*** [/data/nspanel/.pioenvs/nspanel/src/esphome/components/adc/adc_sensor.cpp.o] Error 1
Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_server.cpp.o
*** [/data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_connection.cpp.o] Error 1
*** [/data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_frame_helper.cpp.o] Error 1
*** [/data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_pb2.cpp.o] Error 1
*** [/data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_pb2_service.cpp.o] Error 1
xtensa-esp32-elf-g++: error trying to exec 'cc1plus': execvp: No such file or directory
*** [/data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_server.cpp.o] Error 1
========================== [FAILED] Took 4.03 seconds ==========================`

zu schwach ist der Host nicht, ist ein Odriod N2+

jemand ne idee?

**Comment by deejaybeam** [comment]
hast du das schon versucht - egal ob das Ding zu schwach ist oder nicht?
https://esphome.io/changelog/2022.11.0.html#running-esphome-on-lower-powered-machines
