### ISSUE TITLE
`Enhancement` Entity Cards: Adjust the font size based on the number of chars to be shown.

### ISSUE THREAD

**Issue by neuhausf** [Blackymas/NSPanel_HA_Blueprint#1728]
### Enhancement Summary

Entity Cards: Adjust the font size based on the number of chars to be shown.

### Detailed Description

For the representation of entity values there are the new entity cards.
The values can currently have a maximum of 10 characters. This is sufficient for most use cases. BUT:

To be able to display longer/combined values, I propose the following change:
Adjust the font size based on the number of chars to be shown. This makes the best use of the available space and the display is also appealing (used this way in HA in the weather view for example, see screenshot).

Pros:

- Combined display of temperature / humidity (see screenshot, yes this is my usecase 😉 )
- Wind speed and direction (see screenshot, "11.5 km/h (NNO)")
- Status as strings (location of persons "Grandparents", date with day "Montag 14.12.2023")

### Additional Context

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7963239/9ff931f3-31ee-4f61-9cd1-834909acc002)
See comment in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/307#discussioncomment-8243637

**Comment by edwardtfn** [comment]
So, the challenge here will be to decide the number of chars when the font size should be reduced:

### Font 3 - 26px (Current)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/79c211b5-56b1-4fb7-9699-31a610ca6b49)

### Font 2 - 22px
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/9011dabf-d0d7-4527-a47a-5fb050770eef)

### Font 1 - 18px
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/bb8b248a-ee1e-4335-8e4b-ce646be240d3)

### Font 0 - 16px
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/6065c807-4a74-46e2-851c-fb25eeafabb9)

We have also to evaluate if that will really help, as the gain is not that big. Adding another smaller font is also an option, but I'm afraid it could start getting hard to read in the panel.

Any thoughts?

**Comment by edwardtfn** [comment]
Before you ask, my idea is to find the limit of chars for each font size and adjust only the values that exceed that to the smaller font, so you will have different fonts in the same page, just the longer values will be using a smaller font, while the others will keep the original font.
We probably have to play on a way to align with the labels when one of the fonts is reduced, but I can work on this as soon we have a definition for how this feature should be.

**Comment by edwardtfn** [comment]
And by the way, I cannot get the size a string will take on the screen. What I have is only it's length. 😞

**Comment by edwardtfn** [comment]
My suggestion:
- Count the number of chars, counting the blank spaces (and I could add some other exceptions here) as half char.
- If up to 8 chars, use font 26px (current)
- If 9 to 12 chars, use font 18px
- If more than 12 chars, use font 16px

There's space for one more step (9-10 22px, 11-12 18px) but I'm not sure if this will make real difference or it will just increase the chances of an error as we don't know the size of each char.

**Comment by neuhausf** [comment]
I appreciate your suggestions!
Personally, I would give more area to the values and less to the labels.
Can‘t you right align the value strings, an probably even overlap with the labels section?

If not possible/desired, then your last suggestion would be a good compromise.

**Comment by edwardtfn** [comment]
Overlap is not possible, as the empty area is also plotted over the component in the back.

Reduce the are for the entity name/label is possible, but I'm not sure that would be a consensus.

**Comment by edwardtfn** [comment]
I've implemented this in `dev` and hopefully it will be part of the next release.
