### ISSUE TITLE
`Enhancement`  Entity to control internal nspanel buzzer

### ISSUE THREAD

**Issue by dinde** [Blackymas/NSPanel_HA_Blueprint#1729]
### Enhancement Summary

Add entity to support internal buzzer

### Detailed Description

Hello,

I'd like to use nspanel buzzer on some automations.
I only found some entities related to enable/disable notification sound.
Thanks for inputs

**Comment by grigi** [comment]
There's a service call you can do:
https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/howto.md#play-rtttl-sound

**Comment by dinde** [comment]
Silly me i didn't search with this keywords 🙄😅
Thanks for pointing me to the right direction @grigi
