### ISSUE TITLE
Installation issue - CMake Error: Could not find CMAKE_ROOT !!!

### ISSUE THREAD

**Issue by byronward85** [Blackymas/NSPanel_HA_Blueprint#1741]
### TFT Version

nspanel_eu.tft

### ESPHome Version

2023.12.9

### Blueprint Version

4.0.2

### Panel Model

NSPanel EU Model

### What is the bug?

CMake Error: Could not find CMAKE_ROOT !!!

### Steps to Reproduce

I'm following the installation steps in all the tutorials. Whenever I try flash the device I get the CMake Error.

PS - I've succesfully flashed two devices last year which I use without issue. This issue has only just transpired. 

### Your panel's YAML

```yaml
I've read that the esp32 framework 'esp-idf' might cause this issue so I've changed the framework to arduino which doesnt work either.. it flashes without the CMake error but doesnt work after
```

### ESPHome logs

```logs
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
/data/cache/platformio/packages/tool-cmake/share/cmake-3.16
CMake Error: Error executing cmake::LoadCache(). Aborting.
```

**Comment by edwardtfn** [comment]
Please take a look at this guide and let us know if you still having issues after following the instructions there: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/error_compiling.md

I believe the issue you're reporting is related to the cleaning build files.

**Comment by byronward85** [comment]
Thanks for quick response.. tried cleaning up build files, adding compile_process_limit : 1 to yaml. Rebooted the system in advanced options. Turned off all non-essential add-ons. Cleaned up build files again..

 

Got a lot further on this time but still same error –

 

Installing collected packages: pyparsing, urllib3, tqdm, six, pyyaml, pycparser, packaging, msgpack, kconfiglib, idna, future, filelock, contextlib2, colorama, click, charset-normalizer, certifi, schema, requests, cffi, requests-toolbelt, requests-file, cryptography, cachecontrol, idf-component-manager DEPRECATION: future is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559 Running setup.py install for future: started Running setup.py install for future: finished with status 'done' Successfully installed cachecontrol-0.13.1 certifi-2023.11.17 cffi-1.16.0 charset-normalizer-3.3.2 click-8.1.7 colorama-0.4.6 contextlib2-21.6.0 cryptography-3.4.8 filelock-3.13.1 future-0.18.3 idf-component-manager-1.4.1 idna-3.6 kconfiglib-13.7.1 msgpack-1.0.7 packaging-23.2 pycparser-2.21 pyparsing-2.3.1 pyyaml-6.0.1 requests-2.31.0 requests-file-1.5.1 requests-toolbelt-1.0.0 schema-0.7.5 six-1.16.0 tqdm-4.66.1 urllib3-1.26.18 Reading CMake configuration... CMake Error: Could not find CMAKE_ROOT !!! CMake has most likely not been installed correctly. Modules directory not found in /data/cache/platformio/packages/tool-cmake/share/cmake-3.16 CMake Error: Error executing cmake::LoadCache(). Aborting. ========================= [FAILED] Took 45.29 seconds =========================

 

I’ll have to have a go at compiling using computer.. looks pretty complicated.

 

Is it worth me re-installing ESPHome? I’ve only got around 8 devices so wont be too difficult to start again?

 

Thanks

Byron

**Comment by byronward85** [comment]
Using ESPhome on PC not as complicated as I thought.. it all went swimmingly until the following error –

 

Verbose mode can be enabled via `-v, --verbose` option

CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html

PLATFORM: Espressif 32 (5.4.0) > Espressif ESP32 Dev Module

HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash

DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)

PACKAGES:

- framework-espidf @ 3.40405.230623 (4.4.5)

- tool-cmake @ 3.16.4

- tool-esptoolpy @ 1.40400.0 (4.4.0)

- tool-idf @ 1.0.1

- tool-mconf @ 1.4060000.20190628 (406.0.0)

- tool-ninja @ 1.9.0

- toolchain-esp32ulp @ 2.35.0-20220830

- toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5

ModuleNotFoundError: No module named 'pkg_resources':

  File "C:\Users\byron\AppData\Local\Programs\Python\Python312\Lib\site-packages\platformio\builder\main.py", line 173:

    env.SConscript("$BUILD_SCRIPT")

  File "C:\Users\byron\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\Script\SConscript.py", line 598:

    return _SConscript(self.fs, *files, **subst_kw)

  File "C:\Users\byron\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\Script\SConscript.py", line 285:

    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)

  File "C:\Users\byron\.platformio\platforms\espressif32\builder\main.py", line 312:

    target_elf = env.BuildProgram()

  File "C:\Users\byron\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\Util\envs.py", line 242:

    return self.method(*nargs, **kwargs)

  File "C:\Users\byron\AppData\Local\Programs\Python\Python312\Lib\site-packages\platformio\builder\tools\piobuild.py", line 61:

    env.ProcessProgramDeps()

  File "C:\Users\byron\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\Util\envs.py", line 242:

    return self.method(*nargs, **kwargs)

  File "C:\Users\byron\AppData\Local\Programs\Python\Python312\Lib\site-packages\platformio\builder\tools\piobuild.py", line 121:

    env.BuildFrameworks(env.get("PIOFRAMEWORK"))

  File "C:\Users\byron\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\Util\envs.py", line 242:

    return self.method(*nargs, **kwargs)

  File "C:\Users\byron\AppData\Local\Programs\Python\Python312\Lib\site-packages\platformio\builder\tools\piobuild.py", line 342:

    SConscript(env.GetFrameworkScript(name), exports="env")

  File "C:\Users\byron\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\Script\SConscript.py", line 662:

    return method(*args, **kw)

  File "C:\Users\byron\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\Script\SConscript.py", line 598:

    return _SConscript(self.fs, *files, **subst_kw)

  File "C:\Users\byron\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\Script\SConscript.py", line 285:

    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)

  File "C:\Users\byron\.platformio\platforms\espressif32\builder\frameworks\espidf.py", line 29:

    import pkg_resources

 

I’ve looked into it and it looks like a config issue? I’m no expert though…

 

Cheers

Byron

**Comment by byronward85** [comment]
Final update before I turn off for the night.. I used ESPhome BETA and managed to compile a manual download without issue…

 

======================== [SUCCESS] Took 1169.36 seconds ======================== INFO Successfully compiled program.

 

However when I flashed the device with ESP webtool it didn’t have any results. ESP web tool reported a successful installation but the device is still named as ‘ESP Device’ with nothing in any logs, so, in short it didn’t work

 

Any help greatly appreciated.. after successfully flashing two devices last October without issue, I’ve just bought 8 NS Panels to go in a few rooms so not being able to get them working is very frustrating. 

 

Thanks

Byron

**Comment by byronward85** [comment]
Got it working… not sure if it was a fluke but I flashed a new NS panel with the old YAML file from a device I flashed in October last year. It worked.. then it let me flash the new YAML over to it. I did all this with the BETA version of ESPhome. 

 

 

From: ***@***.*** ***@***.***> 
Sent: Saturday, January 27, 2024 9:56 PM
To: 'Blackymas/NSPanel_HA_Blueprint' ***@***.***>; 'Blackymas/NSPanel_HA_Blueprint' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [Blackymas/NSPanel_HA_Blueprint] Installation issue - CMake Error: Could not find CMAKE_ROOT !!! (Issue #1741)

 

Final update before I turn off for the night.. I used ESPhome BETA and managed to compile a manual download without issue…

 

======================== [SUCCESS] Took 1169.36 seconds ======================== INFO Successfully compiled program.

 

However when I flashed the device with ESP webtool it didn’t have any results. ESP web tool reported a successful installation but the device is still named as ‘ESP Device’ with nothing in any logs, so, in short it didn’t work

 

Any help greatly appreciated.. after successfully flashing two devices last October without issue, I’ve just bought 8 NS Panels to go in a few rooms so not being able to get them working is very frustrating. 

 

Thanks

Byron

**Comment by edwardtfn** [comment]
This is odd. ESPHome BETA should be exactly the same as the released version at this moment. Maybe it is something related to the addon settings in your environment.

**Comment by byronward85** [comment]
No idea.. I’ve flashed 2x more NSPanels using BETA today. I tried the released version but it still crashed on CMAKE_ROOT. Maybe it is my config but anyone reading this should try BETA

**Comment by edwardtfn** [comment]
I'm closing this as it is quiet since a while and as I understood you found a work around (compiling with beta), right?
Please feel free to re-open this if the problem persists.
