### ISSUE TITLE
The "button " pages will accept a booleen helper as an entity, but will not toggle it as expected 

### ISSUE THREAD

**Issue by rudgej** [Blackymas/NSPanel_HA_Blueprint#1745]
### TFT Version

4.14

### ESPHome Version

4.14

### Blueprint Version

4.14

### Panel Model

NSPanel EU Model

### What is the bug?

I would expect a Boolean helper to be toggled when assigned to a button but it does not 

### Steps to Reproduce

Add a Boolean helper to a button, press the button on the panel. the state does not change 

### ESPHome logs

```logs
Logs
```

### Home Assistant logs

```logs
Logs
```

**Comment by edwardtfn** [comment]
Is the entity of domain `input_boolean.`?

**Comment by rudgej** [comment]
fault was mine. I inadvertently had 2 copies of the automation. One turned it on one off. Apologise
