### ISSUE TITLE
`Enhancement` display the current time on each page 

### ISSUE THREAD

**Issue by shing6326** [Blackymas/NSPanel_HA_Blueprint#1748]
### Enhancement Summary

Display the current time (eg hh:mm) from the upper screen for each page

### Detailed Description

Hello,
I am now using the entitypage01 as my home page, it would be fantastic if i can show the current time in that page or even the temperature if possible. Thanks.

**Comment by rudgej** [comment]
as a user this just takes up real estate that adds little in the way of value. the time you can get form anywhere. smart him info is only on the panel

**Comment by edwardtfn** [comment]
- #1755
