### ISSUE TITLE
Page timeout

### ISSUE THREAD

**Issue by lecrams** [Blackymas/NSPanel_HA_Blueprint#175]
Is it possible to set the timeout value (or disable) for getting back to the home page?

Idea is that I want to allow to stay eg in page 4 till the X is pressed 
Another one is to allow modification of the time for returning to home per every button page (setting it to zero woould then disable the timeout

**Comment by Blackymas** [comment]
currently the times are fixed in the hmi.

Not sure if we can pass this variable

**Comment by Blackymas** [comment]
we have looked at theme and have an idea how we could implement it.

I'll put the ticket on the roadmap. When we implement it we do not know exactly yet :)

**Comment by lecrams** [comment]
Great to have it in the roadmap. Yet an other feature to make this great project even better as it is

**Comment by Blackymas** [comment]
@lecrams 

the function was added in version 3.1.0 and available from today.

Have fun ;)

**Comment by lecrams** [comment]
Already noted it. Thanks for the great work and support. 100% working as I needed
