### ISSUE TITLE
`Bug`  Notification icon (envelope) empty when clicked

### ISSUE THREAD

**Issue by dinde** [Blackymas/NSPanel_HA_Blueprint#1751]
### TFT Version

4.2.4

### ESPHome Version

4.2.4

### Blueprint Version

4.2.4

### Panel Model

NSPanel EU Model

### What is the bug?

When I press the envelope to check notifications on screen page is empty

### Steps to Reproduce

1. Send some notifications via service: ESPHome: nspanel_notification_show
2. Go to nspanel after the notification popup is gone
3. Press the envelope
4. Screen is empty you can accept or discard

**Comment by edwardtfn** [comment]
I couldn't replicate exactly the same thing, but I didn't got the envelope visible. When clicking the in envelope area, I got the notification normally.
Need investigation.

**Comment by edwardtfn** [comment]
I believe I have a fix for this in `dev` and it will be included in the next release.
I will close it for now and we open it again if the error persists.

**Comment by edwardtfn** [comment]
We just released a patch with solves this: [v4.2.5 - Celebrating 1000 Stars with Enhanced Functionality and UI Improvements](https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v4.2.5)
Could you please update your system and let me know if the issue was solved?
