### ISSUE TITLE
`Enhancement` Direct relay control and Relay renaming - Needed for replacing existing ESPhome double light switch

### ISSUE THREAD

**Issue by theone11** [Blackymas/NSPanel_HA_Blueprint#1765]
### Enhancement Summary

Replace functionality of exising ESPhome double light switch that includes Direct control and specific light switches names

### Detailed Description

I have an exising ESPHome double light switch that I would like to replace with the NSPanel.

For that I need to be able to control the relays directly from the switch (even when WIFI exists - I do not want to go through HA - I would need to define addtional automations)

In addition I would like to name the relays as I see fit (maybe through substitutions in the YAML file) and not "Relay 1" and "Relay 2"
In the below example Top and Bottom

My exsiting light switch is:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/3348953/8e411647-ce20-49c4-bdc3-26dfc9735d44)

**Comment by edwardtfn** [comment]
This is possible with the current implementation. The relays are already controlled locally and will work when the Wi-Fi is out. Just assign the relays to the respective buttons and the panel will be set to control it locally.
The only thing that might cause an issue is renaming the `entity_id` or your relays... I will have to take a look in the code about the consequences of renaming that, but probably nothing critical. But anyways, you can change it's friendly name (the one visible for users).

**Comment by theone11** [comment]
I have tried it and I can't get it to work (with panel connected to WIFI).

I have turned on the option for relay control in the Blueprint for both relays
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/3348953/64ad48a7-866c-4309-914a-68725b21121d)

When I toggle the relay control in HA under the ESPHome device page **I can hear** them switching (clicking) inside the panel
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/3348953/9f7f2603-ed48-44a6-8099-530bdaf2c275)

When I press the left and right physical buttons on the panel they **do change** the state of the Entities that are defined in Blueprint **_but_** **I do not hear** the relays switching and also **do not see** the relays changing state in HA under the ESPHome device page. 

Am I missing something?

**Comment by edwardtfn** [comment]
You have to assign relay 1 and relay 2 to the buttons if you wanna control the relays when the wifi is available.

**Comment by theone11** [comment]
I want to use the relays **directly** with the buttons even when **WIFI is available** - not through HA.
If it is not possible now then can it be added? That is why I opened this  enhancement request.

**Comment by edwardtfn** [comment]
That is possible now. In order to setup that, you must assign the relays to the buttons using the blueprint.

**Comment by theone11** [comment]
But doesn't that make the control go through HA and directly on the panel?

**Comment by edwardtfn** [comment]
No. In that case HA will be needed only the first time to send that configuration to the panel, then the panel will be able to control it local independently of HA.

**Comment by edwardtfn** [comment]
Hey @theone11, have you progressed with this? Should we close this issue?
