### ISSUE TITLE
Notification icon still shown when notification is cleared 

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1776]
In my opinion hiding (not deleting) notifications is the right behaviour.
Now with nspanel_notification_clear the message disappears. But there is a notification icon on the Home screen. If you tap on it, an empty message opens.

_Originally posted by @panason in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1775#discussioncomment-8407372_

**Comment by edwardtfn** [comment]
Fixed in `dev`.

**Comment by edwardtfn** [comment]
We just released a patch with solves this: [v4.2.5 - Celebrating 1000 Stars with Enhanced Functionality and UI Improvements](https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v4.2.5)
Could you please update your system and let me know if the issue was solved?

**Comment by panason** [comment]
Yes, it works correctly now. Thk
