### ISSUE TITLE
Lovelace ui and NSPanel_HA_Blueprint  together ?

### ISSUE THREAD

**Issue by willyhabr** [Blackymas/NSPanel_HA_Blueprint#178]
I already have a three NSPanel working very well with lovelace UI, but I wanna try and use Blueprint. Is it possible to use the both together on the same home assistant? I would like to use some NSPanel with lovelace UI and some with blueprint.

**Comment by deejaybeam** [comment]
Yes of course!
Why not?

**Comment by Blackymas** [comment]
sure :)

**Comment by willyhabr** [comment]
Thanks guys
