### ISSUE TITLE
Labels for entities on HOME PAGE - SENSORS?

### ISSUE THREAD

**Issue by zlodei2000** [Blackymas/NSPanel_HA_Blueprint#1782]
### Question

How to add label to entities on HOME PAGE - SENSORS?

### Additional Details

I see "Sensor 01 - LABEL COLOR (Optional)" but I can't find field for label. May be it's a stupid question...

**Comment by edwardtfn** [comment]
That is probably not the best text from the blueprint’s side. The label color in that case is the color user to display the value of the sensor.

**Comment by edwardtfn** [comment]
I've improved the wording and the changes will be included in the next release.
Thanks for highlighting this.

**Comment by edwardtfn** [comment]
We just released a patch with solves this: [v4.2.5 - Celebrating 1000 Stars with Enhanced Functionality and UI Improvements](https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v4.2.5)
Could you please update your system and let me know if the issue was solved?
