### ISSUE TITLE
`Bug` Text sensor are display but with `NONE` text

### ISSUE THREAD

**Issue by gn33** [Blackymas/NSPanel_HA_Blueprint#1790]
### TFT Version

4.1.5

### ESPHome Version

4.1.5

### Blueprint Version

4.1.5

### Panel Model

US (Landscape)

### What is the bug?

Strange Chip and text sensor with NONE

### Steps to Reproduce

 i have always the strange chipin home page and now in entity pages, text sensor are display but with NONE text previously it was not the case

https://private-user-images.githubusercontent.com/37216119/304327134-8395c6d0-23c3-44b5-b525-474369d54044.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTY4MDUsIm5iZiI6MTcwNzgxNjUwNSwicGF0aCI6Ii8zNzIxNjExOS8zMDQzMjcxMzQtODM5NWM2ZDAtMjNjMy00NGI1LWI1MjUtNDc0MzY5ZDU0MDQ0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDA5MjgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxOTZjYmUwM2Y2ZWVmMDM4YmE1OGIxYzkyOWQxMmNjMjNiMzNhNzUxZGEyOTM1M2M2ODhmN2M4NzI0Y2FmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a-DWvQJlbGal4NkWvGBvxhU5yQKQLxHZ9EZmVCK4mHo

**Comment by misery** [comment]
Same problem here...
A simple sensor shows "None" after the value.

![photo_2024-02-13_12-18-04](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/50925/96cd18b0-1b8d-45bf-b126-c899cb212c37)

![Screenshot_20240213_121835](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/50925/fd490562-7eb2-4473-93d0-2bd3301ebe41)

**Comment by edwardtfn** [comment]
I believe this is solved in `dev` and it will be included in the next release.
I will close it for now, but please feel free to share additional info and even re-open if the issue persists after the update.
