### ISSUE TITLE
`Bug` Sensor Entities append 'None"

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#1792]
### TFT Version

4.2.5

### ESPHome Version

4.2.5

### Blueprint Version

4.2.5

### Panel Model

US

### What is the bug?

Sensors have the word "None" appended

### Steps to Reproduce

Visual, nothing special to reproduce... look at an entity either on home page.
This seems to be for sensor that have text, not value like the other two shown on home page eg. humidity and pm25

**Comment by Doughboy68** [comment]
Here are some screenshots...

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16811687/2d058c5c-7b0f-4030-990f-ce4d93794953)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16811687/dd541d67-6762-4ad1-a953-0382cf0adecc)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16811687/1a1c5539-212a-430c-8820-f1945dba496d)

**Comment by edwardtfn** [comment]
- #1790

**Comment by edwardtfn** [comment]
I believe this is solved in `dev` and it will be included in the next release.
I will close it for now, but please feel free to share additional info and even re-open if the issue persists after the update.
