### ISSUE TITLE
No config times for screensaver in 4.2.5/cannot disable screensaver. 

### ISSUE THREAD

**Issue by stalakerob** [Blackymas/NSPanel_HA_Blueprint#1796]
### TFT Version

4.2.5

### ESPHome Version

4.2.5

### Blueprint Version

4.2.5

### Panel Model

EU

### What is the bug?

I could disable the screensaver in 4.2.4 using time = 0. In 4.2.5 there are no time settings.

### Steps to Reproduce

![nspanel screensaver](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/44496615/3249344f-957c-41db-900e-0a7af435d3b4)

**Comment by stalakerob** [comment]
Just realized that screensaver is not working at all. The screen always goes blank. Enabling/disabling screensaver does not change this.

**Comment by edwardtfn** [comment]
The screensaver brightness is defined under the device's page (Settings > Devices & Services > ESPHome), together with other brightness values. Please make sure you have "Sleep brightness" higher than 0, otherwise the clock won't be visible.
