### ISSUE TITLE
`Bug` I have now a red vertical line on the right side of the button pages

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1798]
It is working now. This what I did: I moved the device back to the test instance and updated everything. To my surprise it was working again. In the meantime the version number of the blueprint was changed! Then I moved it back to the Prod instance and it was working also! I'm lost but happy that it is working! 

**Only one remark I have now a red vertical line on the right side of the button pages (only there). I can live with it but if there is solution I would like to know. Thanks you for all your help.**

_Originally posted by @Pheerink in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1738#issuecomment-1944058833_

**Comment by edwardtfn** [comment]
@Pheerink, which model are you using? EU, US or US Landscape?

**Comment by edwardtfn** [comment]
Are you using `nspanel_eu.tft` in a NSPanel US model? Could you please provide more details?

**Comment by Eisenhauer1987** [comment]
Hi, I have the same issue. NSPanel EU in White. I Am using the nspanel_eu.tft directly flashed from the repo.

**Comment by Eisenhauer1987** [comment]
I did solve this by my self. I was still using the old blueprint version 4.2.4. After upgrade to 4.2.5 the problem is gone

**Comment by edwardtfn** [comment]
That's right... Old Blueprint have a command which will show those hidden elements. V4.2.5 is required.
But anyways, if you are using a NSPanel EU model I wouldn't expect that to be visible. Only on NSPanel US in landscape mode should have that.

**Comment by Pheerink** [comment]
I update also the blueprint to 4.2.5 but now I lost all the icons and devices on the pages.

**Comment by Pheerink** [comment]
I updates the firmware also. Everything fine now. Thanks
