### ISSUE TITLE
Inefficient ESP32 code

### ISSUE THREAD

**Issue by X-Ryl669** [Blackymas/NSPanel_HA_Blueprint#180]
In this code: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/bd5fb7adc6381d41070f10fb2335d43d10fa1ddc/nspanel_esphome.yaml#L246

The variable can be computed from a formula, instead of doing such a huge if/elseif block. The formula is:
```cpp
int v = int(2 * min(max(value - 13.5, 0.0), 5.0));
left = v + (v ? 19 : 16); 
v = int(2 * min(max(value - 18.0, 0), 4.0));
mid = v + (v ? 29 : 17);
v = int(2 * min(max(value - 21.5, 0), 5.5));
right = v + (v ? 37 : 18);
```

Also, this code: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/bd5fb7adc6381d41070f10fb2335d43d10fa1ddc/nspanel_esphome.yaml#L899
Should read instead in a single line:
```cpp
- lambda: id(disp1).set_component_value("settings.a02",id(sleep_modus_global) == 1);
```

**Comment by deejaybeam** [comment]
looks awesome!
pull-request into dev?
We are looking for guys like you!

**Comment by Blackymas** [comment]
hi - thanks
we will check and test it

**Comment by deejaybeam** [comment]
https://github.com/Blackymas/NSPanel_HA_Blueprint/pull/207
