### ISSUE TITLE
Home Page - Sensors - Entity Sensors is showing value+none

### ISSUE THREAD

**Issue by madtoko** [Blackymas/NSPanel_HA_Blueprint#1804]
### TFT Version

4.2.5

### ESPHome Version

4.2.5

### Blueprint Version

4.2.5

### Panel Model

US

### What is the bug?

Home Page - Sensors - Entity Sensors is showing value+none when entity no have unit of measurement 

### Steps to Reproduce

Blueprint Version 4.2.5

On HOME PAGE - SENSORS, set an entity without unit of measurement, on NSPanel the sensor will show sensor value+none. For exemple: Air quality (good**none**), correct is good

**Comment by edwardtfn** [comment]
- #1790 
- #1792 
Already fixed on dev and will be part of next release.
