### ISSUE TITLE
Assign Background image to Panel dynamically via URL

### ISSUE THREAD

**Issue by bartbakels** [Blackymas/NSPanel_HA_Blueprint#1805]
### Enhancement Summary

Assign Bckground image to Panel ndynamically via URL

### Detailed Description

I use abou 6 NSPAnels, and i would like to assign a background image to the HMI of the NSPANELS.  I would like to have a image of the room were i use it. I know i can edit the HMI file per nspanel, but this means i need to do the per NSPANEL and every time a new  version is released. Is there a more simple way to do this. For example to point the location of the background image to the Homeassistant webserver? This can also be usefull for signalling alerts

**Comment by edwardtfn** [comment]
Unfortunately this is a limitation of this display model used by NSPanel, which only supports pics at the building time of the TFT.
Some time ago I've played with drawing at runtime using the basic plot functions available for Nextion, but it is too slow, making it unusable.

**Comment by edwardtfn** [comment]
- #1270
