### ISSUE TITLE
`Bug` After upgrading tft and blueprint from 4.2.4 to 4.2.6, the button page went blank

### ISSUE THREAD

**Issue by deepjia** [Blackymas/NSPanel_HA_Blueprint#1810]
### TFT Version

4.2.6

### ESPHome Version

4.2.4

### Blueprint Version

4.2.6

### Panel Model

EU

### What is the bug?

After upgrading tft and blueprint from 4.2.4 to 4.2.6, the button page went blank

### Steps to Reproduce

1 upgrade tft and blueprint from 4.2.4 to 4.2.6（tft file: CJK_EU）
2 check nspanel button page

**Comment by ilevac** [comment]
I can confirm.
I happened to me as well.

**Comment by edwardtfn** [comment]
Could you please look at your Home Assistant logs (Settings > System > Logs) for any error message related to this?

**Comment by ilevac** [comment]
> Could you please look at your Home Assistant logs (Settings > System > Logs) for any error message related to this?

I'm upgrading again Nextion display for all my nspanel. As soon as it's done I'll test again and report logs.

**Comment by edwardtfn** [comment]
I've tried even with CJK_EU and couldn't duplicate the issue, so I will need your support for troubleshooting this. 😞

**Comment by deepjia** [comment]
I searched in ha core log, only to find a "Can't connect to ESPHome API for nssr @ 10.0.0.17: Hello timed out (TimeoutAPIError)" warning.

Switched from CJK_EU 4.2.6 to EU 4.2.6, and the same is true.

Seem to have nothing to do with CJK, only 4.2.6

**Comment by deepjia** [comment]
Downgraded to CJK_EU 4.2.5, still blank. 
Downgraded to CJK_EU 4.2.4, still blank.
Downgraded to Blueprint 4.2.5, still blank.
Downgraded to Blueprint 4.2.4, and both CJK_EU 4.2.4 and CJK_EU 4.2.6 works.
So it is introduced in Blueprint 4.2.5.
I only have two buttons, both in first button page; No page title or buttons are visible, like other 3 pages which are supposed to be blank.
The entity's state is 'open', and still blank when switched to closed.

**Comment by edwardtfn** [comment]
What type of entity is that? And what are it's attributes?

**Comment by deepjia** [comment]
> What type of entity is that? And what are it's attributes?

Cover

current_position: 3
friendly_name: 书房窗帘 Cover
supported_features: 15

Not only the entity but also the title of the button page is not dispalyed

**Comment by prohinig** [comment]
The same thing is happening for me after the update:

- Regular EU TFT
- All 4 button pages are blank (No title, no buttons)
- Nothing suspicious in logs other than what @deepjia mentioned

**Comment by edwardtfn** [comment]
Do you also have a cover in the button pages?

**Comment by edwardtfn** [comment]
> > What type of entity is that? And what are it's attributes?
> 
> Cover
> 
> current_position: 3 friendly_name: 书房窗帘 Cover supported_features: 15
> 
> Not only the entity but also the title of the button page is not dispalyed

This is interesting... The `supported_features` includes `set_position`, however the position info isn't available from your cover's attributes.

```
 => OPEN = 1
 => CLOSE = 2
 => SET_POSITION = 4
 => STOP = 8
    OPEN_TILT = 16
    CLOSE_TILT = 32
    STOP_TILT = 64
    SET_TILT_POSITION = 128
```

**Comment by deepjia** [comment]
> SET_POSITION

The cover is actually a curtain motor imported via Zigbee Home Automation, and only current_position is available in attributes.
I just reviewed the doc of cover entity, and I think set_position may only indicate the ability of 'setting' position, so maybe ZHA ignores position info in attributes which are not required.

**Comment by prohinig** [comment]
> Do you also have a cover in the button pages?
> 
> 

Yes, I have covers as well. Also two via ZHA.

**Comment by edwardtfn** [comment]
I also have covers via ZHA and it's all working fine here, so this alone isn't the issue, so my interest about the attributes, as in my case all my covers have a `current_position` in the attributes:
![IMG_6711](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/d92e4123-a253-401c-b18a-990f1cd6111e)

I don't know if this is related to the issue, but trying to find patterns between the ones where it works and the ones where it didn't works could help me finding the issue, as I cannot duplicate it so far.

**Comment by edwardtfn** [comment]
You also mentioned you don't even get the page title shown, so maybe the issue is not even related to the buttons itself... 😩

**Comment by edwardtfn** [comment]
Talking about this, if you open your automation and select to edit via yaml, what do you see for `button_page01_label`?

![IMG_6712](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/46b5ab33-d60b-4588-ae83-efb4f9b4d222)

**Comment by edwardtfn** [comment]
And on the device's page (Settings > Devices and Services > ESPHome) what is shown for `current_page` when that button page is shown in the panel?

**Comment by edwardtfn** [comment]
And one more... What happens if you wait more in that button page? I mean, isn't that just slow?

**Comment by deepjia** [comment]
Blueprint 4.2.4
button_page01_label: 窗帘
Current page: buttonpage01

Blueprint 4.2.6
button_page01_label: 窗帘
Current page: buttonpage01
not just slow,  kept blank for 15 seconds, the return home page

**Comment by deepjia** [comment]
It's indroduced in this commit:
[Deprecate "Show while loading"](https://github.com/Blackymas/NSPanel_HA_Blueprint/commit/083936b1a5230b8e1d4d38181de9be016401049f)

**Comment by deepjia** [comment]
```
      ##### Show while loading #####
          show_while_loading:
            name: Show pages while loading?
            description: >
              *SYSTEM settings*

              *When this is enable (default), the pages will be shown earlier, but some information might not be visible from the begining and will be shown when available.*
              *When disabled, the pages will be shown when all the data is loaded and ready to be displayed.*

              **This may be useful when your pages takes too long to load and can help you identifying the elements slowing down the page construction.**
            default: true
            selector:
              boolean:
```

```
                              ###### Display page while other elements are still loading #####
                              - variables:
                                  show_while_loading: !input 'show_while_loading'
                              - if: '{{ show_while_loading }}'
                                then:
                                  - *delay-default
                                  - service: '{{ nextion.command.show }}'
                                    data:
                                      component: '255'  # all components
                                    continue_on_error: true
```
I added the above snippets back and it works

**Comment by edwardtfn** [comment]
Mmmmm.
This shouldn't be required... But you gave great info, I will look at that.

**Comment by edwardtfn** [comment]
What if you update the ESPHome side to v4.2.6?

**Comment by deepjia** [comment]
> What if you update the ESPHome side to v4.2.6?

I am not sure how to update esphome to 4.2.6, since there are no updates in esphome webgui (2023.12.9 which supposed to be the lastest)

**Comment by Der-Sven** [comment]
Just re-install the Panel via ESPHome integration. 
Please cleanup build-files before, otherwise, it might fail while building.

It is a bit misleading, as the ESPHome version ist officially 2023.12.9, whereas the NS-Panel build running on ESPHome is 4.2.6

**Comment by deepjia** [comment]
> What if you update the ESPHome side to v4.2.6?

It works 🤦
