### ISSUE TITLE
Jazyk

### ISSUE THREAD

**Issue by MichalUngr23** [Blackymas/NSPanel_HA_Blueprint#1812]
### Enhancement Summary

Sel by dat Český jazyka 

### Detailed Description

Sel by dat návod jak firmware přeložit do českého jazyka ?

**Comment by edwardtfn** [comment]
In your automation using the Blueprint, the second input is related to language. Just select "Czech" there.
![IMG_6714](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/e2d40332-80e2-4bc9-ae41-ca514272718b)

**Comment by MichalUngr23** [comment]
Perfektní moc děkuji :) Prispeji nejaky 💸
