### ISSUE TITLE
Display bug since 4.2.4

### ISSUE THREAD

**Issue by gn33** [Blackymas/NSPanel_HA_Blueprint#1813]
### TFT Version

4.2.6

### ESPHome Version

4.2.6

### Blueprint Version

4.2.6

### Panel Model

US (Landscape)

### What is the bug?

Display bug

### Steps to Reproduce

Since 4.2.4 i have a strange chip
![IMG_20240218_210154](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/37216119/b8d806d8-8477-4cd0-8a43-ccd606a63a29)

**Comment by edwardtfn** [comment]
Could you please go to Developer Tools, tab States, find the entity used form climate in your panel and then share its states and Attributes for when this icon is shown?

**Comment by feinadam** [comment]
Same behaviour at me.

My climate entity states:
hvac_modes: auto, cool, dry, heat, fan_only, off
min_temp: 16
max_temp: 30
target_temp_step: 1
fan_modes: auto, high, medium, low, silent
preset_modes: none, eco, sleep, boost
swing_modes: off, vertical, horizontal, both
current_temperature: 24
temperature: 23
fan_mode: auto
preset_mode: none
swing_mode: off
follow_me: false
friendly_name: Midea AC 16492674434018
supported_features: 441

**Comment by gn33** [comment]
My climate :

hvac_modes: heat, off
min_temp: 15
max_temp: 22
target_temp_step: 0.1
preset_modes: none, away, comfort, home, sleep, activity
current_temperature: 19.8
temperature: 20
hvac_action: off
preset_mode: comfort
icon: mdi:fire
friendly_name: Chauffage de la maison
supported_features: 401

**Comment by edwardtfn** [comment]
So, I believe this is fixed in `dev` and will be included on the release of v4.3.
I will close it for now, to make easier the backlog management, but please feel free to re-open if the problem persists.
And comments are always welcome. 😉

**Comment by edwardtfn** [comment]
Hi, have you got a chance to try the fix for this currently in beta? If so, please let me know if that was effective.

**Comment by gn33** [comment]
Hi Edward,



I have this issue when i compil eshome:



*** [.pioenvs/nspanel/src/esphome/components/status/status_binary_sensor.o] Source `src/esphome/components/status/status_binary_sensor.cpp' not found, needed by target `.pioenvs/nspanel/src/esphome/components/status/status_binary_sensor.o'. ========================== [FAILED] Took 4.24 seconds ==========================


De : Edward Firmo ***@***.***>
À : Blackymas/NSPanel_HA_Blueprint ***@***.***>
Sujet : Re: [Blackymas/NSPanel_HA_Blueprint] Display bug since 4.2.4 (Issue #1813)
Date : 12/03/2024 05:49:39 Europe/Paris
Copie à : gn33 ***@***.***>;
   Author ***@***.***>


Hi, have you got a chance to try the fix for this currently in beta? If so, please let me know if that was effective.

**Comment by gn33** [comment]
After cleaning build, now i have that :



In file included from src/esphome/components/sensor/sensor.h:3, from src/esphome/components/adc/adc_sensor.h:6, from src/esphome.h:3, from src/main.cpp:3: /config/esphome/nspanel.yaml: In lambda function: /config/esphome/nspanel.yaml:83:49: error: format '%i' expects argument of type 'int', but argument 5 has type 'double' [-Werror=format=] ESP_LOGD("script.set_brightness(custom)", "brightness: %i%%", brightness); ^~~~~~~~~~~~~~~~~~ src/esphome/core/log.h:72:36: note: in definition of macro 'ESPHOME_LOG_FORMAT' #define ESPHOME_LOG_FORMAT(format) format ^~~~~~ src/esphome/core/log.h:152:28: note: in expansion of macro 'esph_log_d' #define ESP_LOGD(tag, ...) esph_log_d(tag, __VA_ARGS__) ^~~~~~~~~~ /config/esphome/nspanel.yaml:83:7: note: in expansion of macro 'ESP_LOGD' ESP_LOGD("script.set_brightness(custom)", "brightness: %i%%", brightness); ^ ~~~~


De : Edward Firmo ***@***.***>
À : Blackymas/NSPanel_HA_Blueprint ***@***.***>
Sujet : Re: [Blackymas/NSPanel_HA_Blueprint] Display bug since 4.2.4 (Issue #1813)
Date : 12/03/2024 09:15:41 Europe/Paris
Copie à : gn33 ***@***.***>;
   Author ***@***.***>


Please try cleaning the build files.
