### ISSUE TITLE
Cannot update panels with ESPhome - OTA Authentication Invalid

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1820]
Since two weeks I have problems to update the NSpanels with the new ESPHome version. On every device I get this error:

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/49752333/2247d33b-fd16-42a7-bf70-a9b3e9408c1b)

I have all my keys in my secrets in ESPhome and those are not changed. Any idea how to resolve this? 

I am running latest HA.

_Originally posted by @rploeg in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1816_

**Comment by rploeg** [comment]
As addition my yaml file (all the 6 nspanels I have the same setup)

`#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ADVANCED CONFIG + FULL ESPHOME CODE!                                                      #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################


##### ADVANCED CONFIGURATION - activate only when you know what you do ##############################
substitutions: 
  baud_rate: "115200"
  # ## usage of secrets-file ## -> comment in ###### Change ME ######
  device_name: "nspanel01" # Wird im Blueprint benötigt!
  wifi_ssid: !secret wifi_ssid # add in your esphome secrets file.
  wifi_password: !secret wifi_password
  ota_password: !secret ota_pwd
  web_password: !secret wifi_password 
  api_password: !secret api_pwd 
  nextion_update_url: !secret ns_nextion_update_url
  version: "4.1.4"

##### ESPHOME CONFIGURATION #####
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 1s

esp32:
  framework:
    type: esp-idf`

the secrets are really in the secrets file that not has been changed for months

**Comment by edwardtfn** [comment]
Look, I believe the issue is related to the substitution `ota_password: !secret ota_pwd`, as that would be ignored before, as there were no code to use that, but it is used now, so you are basically send a diferent ota now.

If you comment out that line you should be able to flash your device, then you can follow [these instructions to change your ota](https://esphome.io/components/ota.html#updating-the-password) and then you can use in that way again.

**Comment by edwardtfn** [comment]
The web passwords woukd be changing also, but that shouldn't be an issue.

Just the API won't work in the way you are using it. Please follow this customization instead: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/customization.md#api-encryption

**Comment by edwardtfn** [comment]
Hey @rploeg, are you still having this issue or should we close this?
