### ISSUE TITLE
`Enhancement` Toggle Light Button on Light Settings Page

### ISSUE THREAD

**Issue by arielwulkan** [Blackymas/NSPanel_HA_Blueprint#1822]
### Enhancement Summary

Add Button to Toggle Light on Light Entity Settings Page

### Detailed Description

The Light Settings Page is missing a button to toggle the light. This is a missing feature cause as it is now you can control all aspects of light on its page, but not turn on/off. A button for that would be very appreciated and practical. Would make the page much more complete and functional

**Comment by edwardtfn** [comment]
Solved in `dev` and will be part of the next release.
