### ISSUE TITLE
The automation has an action that calls an unknown service

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1830]
I have tried to upgrade my NSPanels to the latest release this week and it didn't go well! 
I'm focusing on one at the moment and after much trial and error I was able to get the TFT installed however, the blueprint is causing errors to appear and no changes are being made to the panel. 

What I think caused this issue is that at some point in TFT upload attempts I renamed the device from "nspanelfbstudy" to "Fionnans Study Panel". This caused issues so I reverted the change and the panel in HA and ESPHome is now back to "nspanelfbstudy" but it appears that the old name is cached somewhere. 

When I create a new blueprint and select "nspanelfbstudy" as the device and make no other changes / configs to the blueprint I get these errors in HA:

```
`FBStudy - NSPanel Config uses an unknown service
The automation "FBStudy - NSPanel Config" (automation.fbstudy_nspanel_config) has an action that calls an unknown service: esphome.fionnans_study_panel_page_home.

This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](http://192.168.2.48:8123/config/automation/edit/1708619182523) and remove the action that calls this service.

Click on SUBMIT below to confirm you have fixed this automation.`

```
In Developer Tools, there are no services "esphome.fionnans_study_panel", only for "esphome.nspanelfbstudy"

I have removed the device from the ESPHome integration, made sure all entities are deleted and rebooted HA but when I add the device back it will always come in as "Fionnans Study Panel". 

As a result of these issues, the NSPanel can't be configured, I can't get anything to show on the screen except the time and this little red HA icon to the right. 
![nspanel](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/19493718/4a49f67f-9ed2-4af7-9297-ad1905e421ad)

And this is what I see in HA:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/19493718/2806b269-795a-4ebb-87c0-75177dd7f0ba)

My ESP Config:

```substitutions:
  # Settings - Editable values
  device_name: "nspanelfbstudy"
  wifi_ssid: "----"
  wifi_password: "----"
  #nextion_update_url: "http://192.168.2.48:8123/local/nspanel_eu.tft"  # Optional
  nextion_update_url: "http://192.168.1.199/nspanel_eu.tft"
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf

##### LOGGER #####
#logger:
#  baud_rate: 0
#  level: WARN

wifi:
  networks:
    - manual_ip:
        static_ip: 192.168.2.225
        gateway: 192.168.2.0
        subnet: 255.255.255.0
  power_save_mode: none
```

Has anybody seen this before? Any advice?

_Originally posted by @fionnanburke in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1828_

- #1828

**Comment by edwardtfn** [comment]
@fionnanburke, could you please double check and make sure you don't have `friendly_name` set. There's a bug with friendly name with exactly these symptoms.

Also, when you remove the panel's integration from Settings > Devices and Services > ESPHOME, please make sure you restart Home Assistant before adding the panel  back to make sure it cleans up entry from the previous one.

**Comment by fionnanburke** [comment]
> @fionnanburke, could you please double check and make sure you don't have `friendly_name` set. There's a bug with friendly name with exactly these symptoms.
> 
> Also, when you remove the panel's integration from Settings > Devices and Services > ESPHOME, please make sure you restart Home Assistant before adding the panel back to make sure it cleans up entry from the previous one.

@edwardtfn , I did have friendly name set at one point but I have since removed it from the ESPHome config. I've cleaned the build file and reinstalled but I still get the same issue. 

I have rebooted HA after removing the device from the integration. I can see the entities have been removed but when I add the device again, I get the same result.

**Comment by edwardtfn** [comment]
Could you please go to Developer Tools, tab Templates and paste this and let me know the results.
(please adjust the sensor id in the first line):

```yaml
{%- set nspanel_deviceid = device_id("sensor.nspanelfbstudy_current_page") %}
nspanel_deviceid: {{ nspanel_deviceid }}
{%- set nspanel_entities = device_entities(nspanel_deviceid) %}
nspanel_entities: {{ nspanel_entities }}
nspanel_entities count: {{ nspanel_entities | count }}
device_attr name: {{ device_attr(nspanel_deviceid, "name") }}
device_attr name_by_user: {{ device_attr(nspanel_deviceid, "name_by_user") }}

nspanel_name (v4.2.5): {{
    device_attr(nspanel_deviceid, "name")
    | regex_replace('[^a-zA-Z0-9]', '_')
    | regex_replace('_+', '_')
    | lower
  }}

nspanel_name (v4.2.4): 
  {%- if nspanel_entities | count > 0 %}
    {{ (nspanel_entities | selectattr(None, "search", "_nextion_display") | list | first).split(".")[1].split("_nextion_display")[0] }}
  {%- elif nspanel_deviceid is string %}
    {{ nspanel_deviceid | replace("-","_") | replace(" ","_") | replace("___","_") | replace("__","_") }}
  {%- endif %}
```

**Comment by fionnanburke** [comment]
I hope this helps! 

`Result type: string
nspanel_deviceid: 1508b20938c02ce4f37b9ecb1a14c396
nspanel_entities: ['sensor.nspanelfbstudy_uptime', 'update.nspanelfbstudy_firmware', 'binary_sensor.nspanelfbstudy_left_button', 'binary_sensor.nspanelfbstudy_right_button', 'binary_sensor.nspanelfbstudy_nextion_display', 'binary_sensor.nspanelfbstudy_status', 'sensor.nspanelfbstudy_blueprint', 'sensor.nspanelfbstudy_temperature', 'sensor.nspanelfbstudy_display_current_brightness', 'sensor.nspanelfbstudy_display_mode', 'sensor.nspanelfbstudy_display_charset', 'sensor.nspanelfbstudy_rssi', 'switch.nspanelfbstudy_notification_unread', 'switch.nspanelfbstudy_notification_sound', 'switch.nspanelfbstudy_relay_1', 'switch.nspanelfbstudy_relay_2', 'button.nspanelfbstudy_restart', 'button.nspanelfbstudy_update_tft_display', 'sensor.nspanelfbstudy_detailed_entity', 'sensor.nspanelfbstudy_current_page', 'sensor.nspanelfbstudy_notification_label', 'sensor.nspanelfbstudy_notification_text', 'sensor.nspanelfbstudy_version_blueprint', 'sensor.nspanelfbstudy_version_esphome', 'sensor.nspanelfbstudy_version_tft', 'number.nspanelfbstudy_display_brightness', 'number.nspanelfbstudy_display_brightness_dimdown', 'number.nspanelfbstudy_display_brightness_sleep', 'number.nspanelfbstudy_temperature_correction', 'number.nspanelfbstudy_timeout_page', 'number.nspanelfbstudy_timeout_dimming', 'number.nspanelfbstudy_timeout_sleep', 'select.nspanelfbstudy_wake_up_page', 'select.nspanelfbstudy_update_tft_display_model', 'device_tracker.nspanelfbstudy']
nspanel_entities count: 35
device_attr name: Fionnans Study Panel
device_attr name_by_user: nspanelfbstudy

nspanel_name (v4.2.5): fionnans_study_panel

nspanel_name (v4.2.4):
    nspanelfbstudy`

**Comment by fionnanburke** [comment]
I got this resolved this morning. I've done so much tweaking that I'm not 100% sure what resolved it but I've copied my esphome config from another panel and just changed the IP address. Cleaned the build files and redeployed. 
I also removed my automations and deleted and re-installed the blueprint. 

My current / working config :

`substitutions:
  # Settings - Editable values
  device_name: "nspanelfbstudy"
  wifi_ssid: "----"
  wifi_password: "----"
  nextion_update_url: "http://192.168.1.199/nspanel_eu.tft"
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

wifi:
  networks:
    - manual_ip:
        static_ip: 192.168.2.225
        gateway: 192.168.2.0
        subnet: 255.255.255.`
