### ISSUE TITLE
`DEV` Chips missing

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1833]
Edward, I installed esp-idf successfully on all 4 panels and I installed the dev successfully on one panel that I wanted to test. The font increase worked perfectly. **I reverted the panel back to 4.2.6 though as there were chips missing etc.** I just wanted to confirm that the dev worked for the increased font of the clock on screensaver

_Originally posted by @plasterer41 in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1689#issuecomment-1960619445_

**Comment by edwardtfn** [comment]
The more you test the lower will be the chances of having issues with the next release, but don't worry too much about this. 😉 

And please always report when you find things on `DEV`.

I believe this with the chips is fixed now. 😃

**Comment by dpetrovichev** [comment]
![photo_2024-03-16_02-43-55](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/18519389/bba0f333-4b5e-4fa0-aa50-234fb3961d86)

HOME PAGE - CHIPS are missing.
HOME PAGE - ENTITIES STATES are missing too.

I see only 7 HOME PAGE - CUSTOM BUTTONS.

Version 4.3.0 (ref:beta)

**Comment by edwardtfn** [comment]
> HOME PAGE - CHIPS are missing.
> HOME PAGE - ENTITIES STATES are missing too.
> I see only 7 HOME PAGE - CUSTOM BUTTONS.

Could you please report this in another issue and add the logs from Home Assistant?
