### ISSUE TITLE
Add a hardware button label option to screensaver page `Enhancement` 

### ISSUE THREAD

**Issue by timeames85** [Blackymas/NSPanel_HA_Blueprint#1835]
### Enhancement Summary

Add an option to show hardware button labels on the screensaver page

### Detailed Description

This is a request to add the option of hardware button labels on the screensaver page, to act as a button locator in low light and for consistency in labelling logic as the hardware buttons are still usable on the screensaver page.

If easier, they possibly wouldn't need the on/off state indicators for their intended use as static labels/locators, though might be nice to have for button feedback if the screen is set not to return home with the hardware buttons.

**Comment by edwardtfn** [comment]
I've added the button indicator bars. Let's wait for feedback and if needed we create a new request to add the labels again.
