### ISSUE TITLE
Extra Sensor on main page

### ISSUE THREAD

**Issue by lloydbayley** [Blackymas/NSPanel_HA_Blueprint#1838]
### Enhancement Summary

Add an outdoor humidity sensor

### Detailed Description

Here's a thought. I'd like (and therefore it's possible other people would like) an outdoor humidity sensor field under the outdoor temperature one. If I want the indoor humidity, I can put it in the homepage sensors (01 would be best) but if I put the outdoor there, it looks like it belongs to the indoor temp. I've checked the HMI and there is room, however, I don't know if the on-chip memory is an issue in adding another sensor and if I did it myself, the new TFT would overwrite it and I'd have to do it again. What do you think as a new feature?

**Comment by edwardtfn** [comment]
I don't think memory would be an issue. My concern is mainly with space on the screen (both EU and US models), but if you have found space, please share that (it's coordinates at least) so I can take a look.

**Comment by edwardtfn** [comment]
I think we can make it into the EU version. 😉 
I will take a look at this later.

**Comment by lloydbayley** [comment]
It's tricky, isn't it? Works for one and not the other. Leave it with you! :)

**Comment by edwardtfn** [comment]
This was implemented in `dev` and will be included in the next release.

**Comment by lloydbayley** [comment]
Wow! I really didn't expect that. Many thanks indeed!

**Comment by edwardtfn** [comment]
Hi, have you got a chance to try the solution for this currently in beta? If so, please let me know if that was effective.

**Comment by lloydbayley** [comment]
Hi,

I’m sorry, I didn’t get to it because I hadn’t had time to take the panel down as I needed to serially program the new framework, however, have now done that and it seems to be working fine! The new sensor is brilliant!
Still looking at all the other new stuff too!

Thanks!
