### ISSUE TITLE
getting a "index file corrupt." in ESPHOME 

### ISSUE THREAD

**Issue by michis0806** [Blackymas/NSPanel_HA_Blueprint#1848]
### TFT Version

4.2.6

### ESPHome Version

4.2.6

### Blueprint Version

unkown

### Panel Model

EU

### What is the bug?

my panel stopped working after updating it to 4.2.5. I'm trying to recompile the file, I'm getting a "index file is corrupt." in ESPHome

### Steps to Reproduce

- Deleting old ESPHome Device
- Creating a new device
- Copy the code from https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/README.md
- replacing device_name / friendly_name with custom values
- trying to validate code

I'm Getting the error message 
```
INFO ESPHome 2024.2.1
INFO Reading configuration /config/esphome/eg-panel-garderobe.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
Failed config

packages: [source /config/esphome/eg-panel-garderobe.yaml:9]
  
  index file corrupt.
  remote_package: 
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: 
      - nspanel_esphome.yaml
    refresh: 300s
```

### Your Panel's YAML

```yaml
substitutions:
  device_name: "EG Panel Garderobe"
  friendly_name: "eg-panel-garderobe"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft"

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf
```

**Comment by edwardtfn** [comment]
Have you tried the steps from the [Compiling Errors Guide](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/error_compiling.md)?
