### ISSUE TITLE
FR: Reduce TFT File back to ~2MB

### ISSUE THREAD

**Issue by T3mplate-wow** [Blackymas/NSPanel_HA_Blueprint#185]
It was mentioned in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/169 that the TFT File went from ~2MB to ~8MB, because of the language support.
I would prefer if there will be 2 files (one standard and one with full language support) and this will be a configuration within the ESPHome configuration. 

May it would be also good to describe that it is also an option to change the `nextion_update_url:`to a local address. (in the documentation)

**Comment by Blackymas** [comment]
hi :)

1. Unfortunately, I have to decline, because then I have to make every change in Nextion Editor twice.
What exactly bothers you about the size?
The first upload on a new NSPanel takes me about 10 minutes and the subsequent uploads when no new graphics are added take 2-3 minutes.

2. In the new update v.3.0.0 comes a new HA service that makes it easier to upload different TFT. Please wait until the update and we will include it in the documentation.

**Comment by T3mplate-wow** [comment]
Hey ;D

The upload doesn’t take 10 minutes, it is at 57% after 14hours at the moment. 
And I am not the only person with this problem: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/169
So I thought it would be much faster, with a file that is only a quarter of the size.

If you have any other solution, like to document the fast way with a local web server or anything else, this would be great. But for me it looks like that the language pack is also one of the problems. 

But I understand you completely, when you don’t want to do changes twice.

**Comment by Blackymas** [comment]
hi 
For all those who have this problem, we have added a new service in version v.3.0.0 to move the TFT from the local HA to the NSPanel.

You can find it here

https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.0.0

 - if you have any questions, please contact us. A detailed documentation will follow, but should be clear so far.

**Comment by Chleba** [comment]
Hi,
I had the same issues:
- system DATA error
- very long upload time when updating TFT
What Helped:
- store the TFT file (blank and full size) in a local network
- using a new service: nspanel_upload_url where I put a local address (http://homeassistant.local:8123/local/nspanel.tft)
- first uploaded a new blank TFT file (for higher baud rate)
- then set nextion_update_url in nspanel.yaml to a local address
- then updating TFT goes quickly and everything works well

Thanks to everyone in the team. Good work.
