### ISSUE TITLE
`Bug`  `Dev` Climate chip sync issues

### ISSUE THREAD

**Issue by Floppe** [Blackymas/NSPanel_HA_Blueprint#1864]
### TFT Version

4.3dev3

### ESPHome Version

4.3dev3

### Blueprint Version

4.3dev3

### Panel Model

EU

### What is the bug?

Climate chip not shown

### Steps to Reproduce

Opening climate page and then closing it again will show the climate chip in home screen for 1 second. Then it's removed again. although climate is heating.

climate.heat states below

### Your Panel's YAML

```yaml
hvac_modes:
  - "off"
  - auto
min_temp: 10
max_temp: 40
target_temp_step: 1
current_temperature: 35.2
temperature: 18
hvac_action: heating
friendly_name: Heat
supported_features: 385
```

### ESPHome Logs

08:54:48 | [D] | [text_sensor:064] | 'Current Page': Sending state 'climate'
08:54:48 | [D] | [script.page_changed:2155] | New page: climate
08:54:48 | [D] | [script.page_changed:2157] | Entity shown: climate.heat
08:54:48 | [D] | [script:077] | Script 'timer_dim' restarting (mode: restart)
08:54:48 | [D] | [script:077] | Script 'timer_sleep' restarting (mode: restart)
08:54:48 | [D] | [sensor:094] | 'Page Id': Sending state 6.00000  with 0 decimals of accuracy
08:54:48 | [D] | [text_sensor:064] | 'Detailed Entity': Sending state 'climate.heat'
08:54:50 | [D] | [nextion:446] | Got touch event:
08:54:50 | [D] | [nextion:447] | page_id:      6
08:54:50 | [D] | [nextion:448] | component_id: 37
08:54:50 | [D] | [nextion:449] | event type:   PRESS
08:54:50 | [D] | [script:077] | Script 'timer_page' restarting (mode: restart)
08:54:50 | [D] | [script:077] | Script 'timer_dim' restarting (mode: restart)
08:54:50 | [D] | [script:077] | Script 'timer_sleep' restarting (mode: restart)
08:54:50 | [D] | [nextion:464] | Got new page: 0
08:54:50 | [D] | [text_sensor:064] | 'Current Page': Sending state 'home'
08:54:50 | [D] | [text_sensor:064] | 'Detailed Entity': Sending state ''
08:54:50 | [D] | [script.page_changed:2155] | New page: home
08:54:50 | [D] | [script:077] | Script 'timer_page' restarting (mode: restart)
08:54:50 | [D] | [script:077] | Script 'timer_dim' restarting (mode: restart)
08:54:50 | [D] | [script:077] | Script 'timer_sleep' restarting (mode: restart)
08:54:50 | [D] | [sensor:094] | 'Page Id': Sending state 0.00000  with 0 decimals of accuracy
08:54:50 | [W] | [nextion:405] | Nextion reported variable name invalid!
08:54:50 | [W] | [nextion:405] | Nextion reported variable name invalid!

### Home Assistant Logs

None

**Comment by edwardtfn** [comment]
I believe this is fixed in `dev`
