### ISSUE TITLE
Does changing the colours of Chips for anyone else?

### ISSUE THREAD

**Issue by bertybassett** [Blackymas/NSPanel_HA_Blueprint#1866]
### TFT Version

4.2.6 and lastest dev

### ESPHome Version

4.2.6 and latest dev

### Blueprint Version

4.2.6 and latest dev

### Panel Model

EU

### What is the bug?

Changing the colours of the chip in automation has not reflection on the panel

### Steps to Reproduce

Changing the colours of the chip in automation has not reflection on the panel

**Comment by edwardtfn** [comment]
I believe this was fixed with v4.3.2.
Please update your system and let me know (and reopen the issue) if this persists.
