### ISSUE TITLE
`Bug`, very minor: notification icon quickly flickers when waking panel

### ISSUE THREAD

**Issue by quenthal** [Blackymas/NSPanel_HA_Blueprint#1867]
### TFT Version

4.2.5

### ESPHome Version

4.2.5

### Blueprint Version

4.2.6

### Panel Model

EU

### What is the bug?

When waking screen, notification icon brights up unnecessarily

### Steps to Reproduce

Screen is dark
Touch screen to wake it
For extremely short time (frame or two, 50-100ms) notification icon (default mdi:email) lights brightly), even when there is no need for notification.

**Comment by edwardtfn** [comment]
This was fixed in `dev` and will be part of the next release.
