### ISSUE TITLE
One page containing an "entities card" as in NsPanel Lovelace UI Docs would be great

### ISSUE THREAD

**Issue by Rainerlan** [Blackymas/NSPanel_HA_Blueprint#187]
To display my trash pickup dates, I have senor entities defined, containing the remaining days until the trash cans are being picked up.
This I would like to display - Preferrably in configurable icon colors (pickup today: red,....)
This is super easy in [NsPanel Lovelace UI Docs](https://github.com/jobr99/nspanel-lovelace-ui), but the UI is by far not so nice as the NSPanel_HA_Blueprint - That is really an eye-candy!
Could you add such a page: One the contains (sensor) entities with selectable icons and dynamic color?
![nspanel](https://user-images.githubusercontent.com/179617/212496623-2e10c4a4-6ee9-40f1-99dd-6be134f6ca38.png)

**Comment by Blackymas** [comment]
Hi

Everything is already in the planning and also on the roadmap

See here:
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/128

We will lay the foundation for further functions with the next update v.3.0.0 (probably coming tomorrow).

We didn't manage to integrate everything directly in the short time available - because we first had to find the space for the new buttons.

However, we have now managed to do this and are now working on the new functions.

Have you used the rubbish plan from SmartHomeYourself?

**Comment by Rainerlan** [comment]
Great to hear the feature will be coming soon - Can't wait to use it. I love the looks your UI and its intuitive and easy to use.

Actually I am using the "Waste Collection Schedule" from HACS. With this, just a few lines of config need to be added in configuration.yaml to get going.

**Comment by Blackymas** [comment]
can you share the state an attributes -> Developer tools

**Comment by MarkuZP** [comment]
I use that too!

**Comment by MarkuZP** [comment]
Hey @Rainerlan, You can do it like i did till this entitiescard function is availiable.
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/201
I use waste collection too and send notfications to all panels and Alexas, smartphones one day before Wasteday.

**Comment by Rainerlan** [comment]
@MarkuZP Absolut geile Idee - Danke für den Input! - Jetzt muss ich nur noch rausfinden warum mein panel aktuell immer im boot-screen hängen bleibt - und ich es nach jedem reboot manuell daraus befreien muss :)

**Comment by Blackymas** [comment]
könnte auch bald in der entity Card Pages die Sensoren genau anzeigen - ich bin mir noch nicht ganz sicher ob wir dann wirklich noch eine extra seite für Müll brauchen werden.

Prüft das dann bitte mal mit version 3.1.0 ob euch das dann reicht

**Comment by Rainerlan** [comment]
Einen entity card ist imho sehr universell anwendbar - eine extra Müllkarte hatte ich eigentlich auch überhaupt nicht gewollt - Das Foto aus [NsPanel Lovelace UI Docs](https://github.com/jobr99/nspanel-lovelace-ui) ist auch genau eine so eine universelle Entiry-card.

Was allerdings super wäre, ist das was ich bisher immer selbst im UI (.hmi-File) hinzubasteln musste: Eine 5. Buttonpage mit meinem WLAN QR-code :)
Das [NsPanel Lovelace UI Docs](https://github.com/jobr99/nspanel-lovelace-ui) liefert hierfür auch eine gutes Besipiel. - Aber ehrlich: Ich liebe das Design von [Blackymas](https://github.com/Blackymas)

**Comment by deejaybeam** [comment]
QR-Code-page ist bereits in 3.1.0 implementiert.
Es kann ein "fixer" QR-Code über einen eigenen Button auf der home-page aufgerufen werden, oder jederzeit ein "temporärer" QR-Code via Service ans Panel gesendet werden (oder z.b. über scripte via buttons auch beliebige "fixe")

**Comment by Rainerlan** [comment]
@deejaybeam absolut Klasse! - Vielen Dank dafür!
Da ich das Ding an der Wand haben möchte, habe ich eben wieder meine eigene Wifi-page hinzugebastelt :)
![nspanel2](https://user-images.githubusercontent.com/179617/216471334-f9758801-97ed-413a-9800-8c6c9fee5f7d.png)

**Comment by Blackymas** [comment]
@all

in the new version 3.1.0 you have 4 pages with a total of 32 entities at your disposal 

Have fun with it ;)

**Comment by Rainerlan** [comment]
Wow, that really great! Having immediate access to the entities & Wifi QR code from the screensaver is awesome!
Is there any description of which icons can be used? (I have tried eg. this one 🗑 - and got a lock-symbol instead)
Also not a must have but a nice to have feature would be to color the icons using a service;)
So eg. I could color open windows in red, or upcoming trash pickup

**Comment by Blackymas** [comment]
Hello,

in the release notes is a link to all icons you can use. More than the 6898 icons are not possible. 

You can't change color yet. Maybe we will add this - technically possible

**Comment by Rainerlan** [comment]
Many thanks - One just need to know were to look :)

Here would be some ideas for future improvements (Don't get me wrong - The currently solution already is amazing)
- icon+text to be left aligned, while the entities state may be right aligned.
- Icon color (or status?) to be changed using a service
- Some more "advanced" (impossible?) features:
  - Entity-state of the nspanel (icon, slider, ...) in-sync with the lovelace-ui entities card (eg. icon == bulb for lights - yellow for "on", etc.) - i.e. a "mimikry" of the lovelace-ui entities
  - When touching an entity, open the nspanel page, matching the entity (lights, switches, lids), to actually remote control them
