### ISSUE TITLE
`Bug` Homepage chips shown when leaving utilities page

### ISSUE THREAD

**Issue by oliv43** [Blackymas/NSPanel_HA_Blueprint#1870]
### TFT Version

4.3dev3

### ESPHome Version

4.3dev3

### Blueprint Version

4.3dev3

### Panel Model

EU

### What is the bug?

homepage chips are shown for a second when leaving utilities page

### Steps to Reproduce

Open utilities page
Close it
Chips are shown for a second then disappear on home page

**Comment by edwardtfn** [comment]
Do you have any error message related to this automation on your Home Assistant logs (Settings > System > Logs)?

**Comment by oliv43** [comment]
Nothing.
I just found that it hapens when the home screen is displayed from sleep too.

**Comment by oliv43** [comment]
Hi,
I just installed dev4 and I don't have this issue anymore.

**Comment by bertybassett** [comment]
Update tft and now everything is working
