### ISSUE TITLE
4.3dev4 QR keeps poping up

### ISSUE THREAD

**Issue by bkbartk** [Blackymas/NSPanel_HA_Blueprint#1876]
### TFT Version

4.3dev4

### ESPHome Version

4.3dev4

### Blueprint Version

4.3dev4

### Panel Model

EU

### What is the bug?

QR code is in the homepage while QR is disabled in the blueprint. the qr searches of '[]' in google

### Steps to Reproduce

disable QR,
update to dev.

**Comment by edwardtfn** [comment]
Could you please try again with v4.3.0b2?

**Comment by bkbartk** [comment]
this seems to be fixed, thnx
