### ISSUE TITLE
[Fan page] consider to merge the on and off buttons into single power button which similar to the light page.

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1886]
Hello @edwardtfn , thanks for your great efforts to always give the NSPanel_HA_Blueprint users with tones of new features and enhancement. I have a few suggestions that would like to share which based on my own opinion and use case only.
1. [Button and Entity pages] able to disable the page selector (dot) when there is only one page from button/entity pages.
2. [Entity page] enable the option to switch the automatic font size adjustment for entity page values on and off. My entity page values are highly related each others and it may contains some CJK characters which hard to calculate the width of the string, it is good to have the switch so that my entities may look consistent with all values.
3. [Entity page] allow users to disable the entity icons from entity pages
4. **[Fan page] consider to merge the on and off buttons into single power button which similar to the light page.**

_Originally posted by @shing6326 in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1875#discussioncomment-8759510_

**Comment by shing6326** [comment]
Thanks so much !!
