### ISSUE TITLE
`Bug` NSPanel update TFT display not working 

### ISSUE THREAD

**Issue by McMtech** [Blackymas/NSPanel_HA_Blueprint#1897]
### TFT Version

4.1.4

### ESPHome Version

2024.2.2 

### Blueprint Version

v4.2.6

### Panel Model

EU

### What is the bug?

When updated ESPhome and the blueprint tried to update the TFT and would not update so now missing all my icons, but they are all still in the blueprint. 

https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/117125598/878bfbaa-75ac-4f5b-9da1-9fc826e58cf4

**Comment by KoKolaj** [comment]
Apparently a similar problem to me.
Helped advice with the transition to esp-idf
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1896#issuecomment-1992603140


https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/tft_upload.md#esp-idf

**Comment by McMtech** [comment]
I have changed it to, esp-idf  a few weeks back but still nothing happened the screen thinks it’s still on 4.1.4

**Comment by shing6326** [comment]
you have to use a serial cable to flash it again if you change the framework from arduino to esp-idf.

**Comment by edwardtfn** [comment]
If you cannot flash it via serial ttl right now, please revert it back to arduino adding this to your yaml:

```yaml
esp32:
  framework:
    type: arduino
```

**Comment by edwardtfn** [comment]
- #1821

**Comment by dylanpedro** [comment]
I added the following to the ESPHome YAML file for the particular panel and it works after flashing it so do we still need to flash it with a serial cable?

```
esp32:
  framework:
    type: arduino
```

**Comment by edwardtfn** [comment]
Hey @McMtech, are you still facing this issue or should we close this?

**Comment by McMtech** [comment]
Hello This can be closed now it solved my issue. Thank you. Kind regards Joe Fellows-McMurrayOn 3 Apr 2024, at 9:39 PM, Edward Firmo ***@***.***> wrote:﻿
Hey @McMtech, are you still facing this issue or should we close this?
