### ISSUE TITLE
After Update to 4.3.0 no Version information displayed

### ISSUE THREAD

**Issue by lepatrick** [Blackymas/NSPanel_HA_Blueprint#1898]
### TFT Version

4.3.0

### ESPHome Version

4.3.0

### Blueprint Version

4.3.0

### Panel Model

EU

### What is the bug?

Before update TFT-, Firmware- and Blueprint-Version was shown on every NSPanel device. After update this entries not shown anymore.

**Comment by edwardtfn** [comment]
Do you mean the version sensors on the device's page (under Settings > Devices & Services > ESPHome? Those sensors have been introduced with v4.2, but as they consumed RAM, we decided to remove it.
You still able to see the version on the boot page.

**Comment by lepatrick** [comment]
Exactly, okay I understand the reason.
