### ISSUE TITLE
Display `Bug` 

### ISSUE THREAD

**Issue by gn33** [Blackymas/NSPanel_HA_Blueprint#1902]
### TFT Version

4.3

### ESPHome Version

4.3

### Blueprint Version

4.3

### Panel Model

US (Landscape)

### What is the bug?

Big thanks for this new realese 

- When value is 0 icon is grey
![IMG_20240313_101702](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/37216119/f9cb9efd-edec-4183-8cc8-5e765c3b7745)
- Entity page 3, Row 1 - Icon is not displayed
![IMG_20240313_101723](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/37216119/45cb31b9-d744-49d7-b54a-6f6e02a17ae3)

**Comment by edwardtfn** [comment]
Could you please share the attributes from these two entities from Developer Tools > States tab?

**Comment by gn33** [comment]
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/37216119/4e7fd8c2-16f8-4f5b-8024-bedddc1f7e5f)

**Comment by gn33** [comment]
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/37216119/c8d4baec-b764-4841-87d9-c046ae878edd)
