### ISSUE TITLE
`Enhancement` entity name on advanced settings page. 

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#1909]
### Enhancement Summary

Show entity name in advanced settings page

### Detailed Description

When long pressing to get advanced settings page for light, fan etc. display the name of the entity somewhere on the page. These advanced settings pages are also accessed from home page buttons for supported entities.

**Comment by edwardtfn** [comment]
The logic for the page title includes the `entity_id` as a third option:
1. Name from Blueprint settings
2. Friendly name
3. Entity_id

Do you wanna a way to see both that title and also the `entity_id`?

**Comment by Doughboy68** [comment]
I don’t see a need for entity id. 
Name from blueprint settings - how would this work from the Home Screen buttons - currently there is no way to assign friendly name there unless blueprint is modified to allow it.
Maybe use Name from Blueprint and in case of the home screen buttons either update blueprint, or instead just use Friendly name.

**Comment by edwardtfn** [comment]
Okk for home page custom buttons we don't have that. I got your point.
I Will take a look at that.

**Comment by edwardtfn** [comment]
Is this still an issue with v4.3.2?

**Comment by edwardtfn** [comment]
Still pending some tests, but I've implemented custom names on `dev` and will be included in v4.3.3, but on v4.3.2 the friendly name should already be used.

**Comment by Doughboy68** [comment]
Yes it seems to work thanks.
