### ISSUE TITLE
 Animated pixel for simulating the Energyflow more lighter or in a different color please

### ISSUE THREAD

**Issue by MarkuZP** [Blackymas/NSPanel_HA_Blueprint#1910]
### Enhancement Summary

lighter energyflow pixel

### Detailed Description

 Is there a possibility to get the animated pixel for simulating Energyflow more lighter or in a different color?
It could be  a bit more visible..

**Comment by edwardtfn** [comment]
Solved in `dev` and will be included in the coming release.
You will have a selector on the blueprint for the cursor width. If that is not sufficient, I can add color for the individual lines, so please let me know if the width solved the issue. 😉
