### ISSUE TITLE
`Bug`  Indoor temperatuur switching between own sensor en other semsor

### ISSUE THREAD

**Issue by kroon040** [Blackymas/NSPanel_HA_Blueprint#1911]
### TFT Version

4.3

### ESPHome Version

4.3

### Blueprint Version

4.3

### Panel Model

EU

### What is the bug?

I use for the display an another temperature sensor that is not from the panel itself. That was working ok, bu now often I see on the homepage that the temperature switches between the sensor I set in the blueprint en it's own temperature.

In older versions, it was not happening

### Steps to Reproduce

Use another temperature sensor as the internal, and wait a couple minutes and it will happen

**Comment by edwardtfn** [comment]
The internal sensor was always used as a fallback sensor when the API or WiFi are out.
Can you see other symptoms of a possible communication issue?

**Comment by kroon040** [comment]
If I look in the log of the nspanel, I see no communication issues. I noticed when the device gets the temperature I see it right on the device. When I look in Ha , when I get an update form the other sensor that it's displayed. So it looks like he takes both and displays the latest he received


```
10:07:08 | [D] | [sensor:094] | 'Temperature': Sending state 21.85564 °C with 1 decimals of accuracy
10:07:25 | [D] | [sensor:094] | 'RSSI': Sending state -34.00000 dBm with 0 decimals of accuracy
10:08:08 | [D] | [sensor:094] | 'ntc_source': Sending state 1.66900 V with 2 decimals of accuracy
10:08:08 | [D] | [resistance:039] | 'resistance_sensor' - Resistance 11460.9Ω
10:08:08 | [D] | [sensor:094] | 'resistance_sensor': Sending state 11460.94434 Ω with 1 decimals of accuracy
10:08:08 | [D] | [ntc:026] | 'Temperature' - Temperature: 22.0°C
10:08:08 | [D] | [sensor:094] | 'Temperature': Sending state 21.96252 °C with 1 decimals of accuracy
10:08:25 | [D] | [sensor:094] | 'RSSI': Sending state -34.00000 dBm with 0 decimals of accuracy
10:09:08 | [D] | [sensor:094] | 'ntc_source': Sending state 1.67200 V with 2 decimals of accuracy
10:09:08 | [D] | [resistance:039] | 'resistance_sensor' - Resistance 11502.7Ω
10:09:08 | [D] | [sensor:094] | 'resistance_sensor': Sending state 11502.70410 Ω with 1 decimals of accuracy
10:09:08 | [D] | [ntc:026] | 'Temperature' - Temperature: 21.9°C
10:09:08 | [D] | [sensor:094] | 'Temperature': Sending state 21.88235 °C with 1 decimals of accuracy
```

**Comment by edwardtfn** [comment]
Ok. I could duplicate the issue here.
I will look for a fix.
