### ISSUE TITLE
Homepage Chips appearing shortly after wake up from screensaver or when leaving a Menupage

### ISSUE THREAD

**Issue by MarkuZP** [Blackymas/NSPanel_HA_Blueprint#1915]
### TFT Version

4.3.0

### ESPHome Version

4.3.0

### Blueprint Version

4.3.0

### Panel Model

EU

### What is the bug?

The Homepage  Chips appearing shortly after wake up from screensaver or when leaving a Menupage. Not a big deal but I think its new after the 4.3.0 update. 

See video!

### Steps to Reproduce

1. choose menu page
2. leave it

Uploading IMG_6476.MOV…

**Comment by edwardtfn** [comment]
> See video!

We didn't got the video. 😞

**Comment by MarkuZP** [comment]
https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/109298227/370a33f9-4f41-471d-a78c-a59ea94dee3a


https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/109298227/a251efd8-560d-40b3-9a6a-649910b9c491

Now you got 2 :-)

**Comment by edwardtfn** [comment]
The same happen with notification icon, right?

**Comment by MarkuZP** [comment]
Yes!

**Comment by edwardtfn** [comment]
This is fixed in `dev` and will be part of the next release.

**Comment by MarkuZP** [comment]
Wow Edward, I wish that I would get such a fast response and nice work from these overpriced software companies I work with every day! Thank you so much!
