### ISSUE TITLE
`Bug` Boot page isn't visible long enough to see versions

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1923]
### TFT Version

4.3.0

### ESPHome Version

4.3.0

### Blueprint Version

4.3.0

### Panel Model

US (Landscape)

**Comment by bkbartk** [comment]
I noticed this too, wasn't a real deal breaker for me, but I was actually wondering about the purpose of the boot screen at all.
all relevant info on the bootpage
-ip
-3 version numbers
-boudrate
- framework

could somehow be added to the settingspage. and then directly boot the the set startpage.
that way if you want to see the version or baudrate you don't have to reboot and can just go to the settingspage.

requirement here ofc is that the settingspage works in offline mode, I don't know if it does

**Comment by edwardtfn** [comment]
> could somehow be added to the settingspage. and then directly boot the the set startpage.

In fact, if you long press the area where the reboot text is, it will show the boot page.

**Comment by edwardtfn** [comment]
Fixed in `dev`.
