### ISSUE TITLE
Icon color on inverted chips not working

### ISSUE THREAD

**Issue by chri4chri** [Blackymas/NSPanel_HA_Blueprint#1928]
### TFT Version

4.3.0

### ESPHome Version

2024.2.2

### Blueprint Version

4.3.0

### Panel Model

EU

### What is the bug?

when I use inverted chips functionality, I'm not able to set the colour from the icons, everytime they are in gray

### Steps to Reproduce

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/46874975/2a1e10c1-bf8b-4030-9cb8-ba636787e30e)

**Comment by edwardtfn** [comment]
I believe this is fixed on `dev` and that will be included in the next release.
