### ISSUE TITLE
Mit Befehl spezifische Seite aufrufen.

### ISSUE THREAD

**Issue by T-abr** [Blackymas/NSPanel_HA_Blueprint#193]
Hallo Blackymas, 
das Update auf die 3.0.0 halt super funktioniert. Ich bin begeistert, was für ein tolles Projekt daraus geworden ist.
Ist es Möglich die Seite, die sich z.B. hinter dem Butten01 bei langem Tastendruck befindet, per send_command aus Homeassistant aufzurufen?

Hintergrund ist, Auf der linken Taste des NS Panels befindet sich z.B. das Deckenlicht. Hier kann ich auch noch Helligkeit und Farbtemperatur einstellen. Beim Einschalten des Deckenlichtes wäre es schön, Wenn das Display direkt die passenden Parameter anzeigt wie beim lagen Tastendruck auf Button01 z.b. 

Vielen Dank und Gruß

**Comment by Blackymas** [comment]
Vielen Dank - freut mich zu hören.

Genau das war der Gedanke beim Entwicklen. Es sollte so einfach wie möglich sein und optisch auch gut aussehen, denn das waren beides Punkte die ich so bei keiner anderen version gefunden habe.

Zu deiner frage ja ist machbar. Dazu kannst du folgenden Service benutzen

```yaml
service: esphome.nspanel_dev_send_command_printf
data:
  cmd: page home
```

"Home" kannst du einfach ersetzen durch den Seiten-Name wo du hin willst.

Es gibt aktuell folgende Seiten
![Bildschirmfoto 2023-01-16 um 21 14 16](https://user-images.githubusercontent.com/41958506/212759028-d705aa3b-faaf-4db0-aeb2-1725d97630a0.png)

**Comment by T-abr** [comment]
Hallo Blackymas,

so eine Variante hatte ich mir schon gedacht. Danke dafür. Nun ist es so, dass ich gerne die Seite lightsettings von Button09 aufrufen würde. Quasi der lange Tastendruck von Button09. Ist dies auch möglich. Wenn ich nur die Seite lightsettings Aufrufe fehlt natürlich die Information um welches Gerät es sich handelt richtig ?

viele Grüße und danke !

**Comment by Blackymas** [comment]
Hallo,

das wird schwierig zumindest nicht ohne code Anpassungen.

könnte ich jetzt auch nur testen - aber gerade etwas schwer zwecks zeit

**Comment by T3mplate-wow** [comment]
Ich wollte gerade genau den gleichen/einen ähnlichen Feature Request einstellen.
Ich würde gerne beim Druck auf Taste 2 direkt auf die Detailpage des Rollladen gehen. 
Das ist die häufigste Funktion (neben dem Licht auf Taste 1), die man so viel bequemer erreicht. Oder geht das schon mit dem Aufruf oben von „coversettings“?

**Comment by deejaybeam** [comment]
Du kannst jede page manuell über den service aufrufen, wie oben bereits beschrieben, aber das funktioniert eben nicht für die light/cover - pages, da da im blueprint einiges mehr passiert. Was aber möglich wäre, ist das selbe verhalten wie bei einem long-press auf einen virtuellen button auch auf die physikalischen buttons zu übernehmen -> wäre ein feature request, dafür ist etwas umbau im blueprint und im esphome notwendig.

**Comment by Blackymas** [comment]
nur als kleines Update wir haben es heute im weekly Meeting besprochen - wir werden es prüfen ob es geht.

Das ist aber keine Garantie das wir es umsetzen - aber ein Try versuchen wir ;)

**Comment by Blackymas** [comment]
@T3mplate-wow 

We added your feature in release 3.1.0.

Have fun with it and feel free to leave a donation ;)
