### ISSUE TITLE
Shutter dosen.t work

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1945]
Hello

I successfully updated my NS panel from 4.1.1 to 4.3.
Unfortunately now I have the following problem: my shutter control no longer works.
As soon as I press the Hardbutton and trigger the scene, the Scene will immediately be disabled in HA
I have the same problem when I run this as a soft button
With version 4.1.1 everything worked.
Do you have any idea why an active scene is set to deactivated in HA?

Thank you in advance for the help.

HA Version 
Core 24.3.1
OS 12.1
ESP Home 2024.2.2

_Originally posted by @Maxym1979 in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1942_

**Comment by edwardtfn** [comment]
@Maxym1979, I will need a bit more info here.

How is the entity assigned to the hardware button? Is that a `scene.xxxxx` or an automation?
Could you please go to Developer Tools, tab States and share state and Attributes of this entity?

**Comment by Maxym1979** [comment]
Hi, the entity is an automation.

I hope this is the right one and helps

![IMG_0074](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/134197127/f9743aea-6a2c-4100-90e8-06405a70de0b)

**Comment by edwardtfn** [comment]
Ok, so in the blueprint, what is set for "System settings - Button action for automation entities"?

**Comment by Maxym1979** [comment]
Hm system setting,s…do you mean this?

![IMG_0075](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/134197127/b8f03a9c-4d5b-462f-ae35-ec0af360da17)

**Comment by edwardtfn** [comment]
Go all the way down... It is one of the last inputs.

**Comment by Maxym1979** [comment]
Found it ;-)

![IMG_4528](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/134197127/967c39eb-0c6b-418e-8c0d-918736dc20f1)

I think it must be changed to „Trigger“ !?
I will test it this evening.

**Comment by Maxym1979** [comment]
Hi, thanks a lot for help. Now it works as it should.
Maybe it would be possible to integrate these settings into the Hardware Button menu. In my opinion, it would be possible to rule out this source of error or provide a hint.

Thanks again.

**Comment by edwardtfn** [comment]
We have severe limitation of memory in the ESPHome side, so it’s impossible to have all the controllers there. And a big part of the logic is in the blueprint side, include that one.

But we definitely lack better documentation around all those things.
