### ISSUE TITLE
`Bug` Hardware Buttons - Visibility Pages "Home" dont work

### ISSUE THREAD

**Issue by Lice2** [Blackymas/NSPanel_HA_Blueprint#1948]
### TFT Version

4.3.1

### ESPHome Version

4.3.1

### Blueprint Version

4.3.1

### Panel Model

EU

### What is the bug?

The hardware buttons visibility does not work on the homepage.
They are displayed on all other pages.
![IMG_20240320_164605](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/40924441/4b49d22b-c325-4814-8c36-fe9ed1eef713)
![IMG_20240320_164638](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/40924441/0a411acf-8f30-4abc-ada2-fecfb6023e5a)
![IMG_20240320_164538](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/40924441/722ab55a-c3a0-4853-9ee2-03257674001b)

**Comment by edwardtfn** [comment]
Please clean you build files and flash your device again.

## Clean-up build files

Go to your ESPHome Dashboard, click the 3-dot menu related to your device and then "**Clean Build Files**":

![image](https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/dev/docs/pics/esphome_dashboard_clean_build_files.png)

**Comment by Lice2** [comment]
It workds now .
I flashed the firmware again. And then it went.
Thanks !
