### ISSUE TITLE
`Enhancement` custom binary state entities for each hadware button state display

### ISSUE THREAD

**Issue by lafriks** [Blackymas/NSPanel_HA_Blueprint#1959]
### Enhancement Summary

Allow to specify binary state entity for each hardware button

### Detailed Description

Hardware baby-carriageuttons will be displayed (on/off) only when either relay or specific entity is assigned to it, would be nice if state display could be selected independently of entity button switches on/off

### Additional Context

I'm using trigger events to turn on/off scenes using my own automation.
If assigning specific light or scene entity to hardware button it will not work (will turn on but will not turn of as HA has no scene turnoff functionality).

For detecting if current scene is on/off I have created binary template helper entities that I use in automatons and would be great if I could set them for HW button status display.

Example for binary template helper:

```py
{{ states('light.living_room_light') == 'on'
   and state_attr('light.living_room_light', 'color_temp') == 153
   and state_attr('light.living_room_light', 'brightness') == 254
}}
```

**Comment by edwardtfn** [comment]
Solved in `dev` and will be included in the next release.
