### ISSUE TITLE
Design source files

### ISSUE THREAD

**Issue by X-Ryl669** [Blackymas/NSPanel_HA_Blueprint#196]
Would it be possible to upload the source design files used to make the current interface ?
I'm trying to change the background picture to find out that I have to change many (if not all) icons and so on. But this is very hard to do with Nextion editor, since the icon & picture are already anti-aliased and blended and the position are not precise.

So, I guess you are using something like Adobe Illustrator / Inkscape / Figma to make the design. Can you share these files so it's possible to re-generate them with a different background ?

**Comment by Blackymas** [comment]
Hallo,

ich habe das ganze über Adobe Express gemacht so wie ich gesehen habe kann ich euch auch den Ordner teilen.

Ich schau es mir die Tage an ob das so möglich ist und stelle euch dann die Grafiken zur verfügung

**Comment by X-Ryl669** [comment]
Danke!

**Comment by Blackymas** [comment]
Hallo,

ich werde das design später teilen weil wir in 3.2.0 wahrscheinlich einige Sachen und designs anpassen müssen es mach daher aktuell keinen sinn diese zu teilen.

Wenn wir das redesign gemacht haben werde ich es gleich mit teilen.
