### ISSUE TITLE
Button Page Label not use if only a number

### ISSUE THREAD

**Issue by NikolasRupp** [Blackymas/NSPanel_HA_Blueprint#1961]
### TFT Version

4.3.1

### ESPHome Version

4.3.1

### Blueprint Version

4.3.1

### Panel Model

EU

### What is the bug?

When u use a label with only a number, for example "1" it will always display the normal entity name and not the label
It's possible to use a long space "ㅤ" after the number and then it works

**Comment by edwardtfn** [comment]
Solved in `dev` and will be part of v4.3.2 release
