### ISSUE TITLE
`bug` Maximum number of runs exceeded

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1967]
Hi @edwardtfn,

There is this error ― completely forgot to look here in the beginning 🤦🏼‍♂️

```
Logger: homeassistant.components.automation.nspanel_update
Source: helpers/script.py:1805
integration: Automation (documentation, issues)
First occurred: 16:00:33 (22 occurrences)
Last logged: 16:30:22

NSPanel Update: Maximum number of runs exceeded
```

When I checked first it said 16 occurrences and the last was at 16:00. Went to the panel, opened the Utilities Page, back to the Home Screen and then opened the Utilities Page again. Second time I opened it it took a while to load the "artifacts".
Now its on 22... That would make sense for the 3 lines that aren't moving (opened twice so 6 more occurrences were added)? If I understand it correctly?

<img width="480" alt="Screenshot 2024-03-22 at 16 31 49" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/42886484/9a50857a-b181-4364-b912-1a834062297e">

_Originally posted by @finch6 in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1964#issuecomment-2015241842_

**Comment by edwardtfn** [comment]
I've made some changes on the way the values are updated on the Utilities page and I believe the time an instance of the automation runs will be reduced significantly.
This is still in `dev`, but will be included in the next release.

**Comment by edwardtfn** [comment]
I'm reopening this as the issue persists. 😞

**Comment by Wolf6660** [comment]
i have the same Problem
Logger: homeassistant.components.automation.display_wohnzimmer

`Logger: homeassistant.components.automation.display_wohnzimmer
Quelle: helpers/script.py:1918
Integration: Automatisierung ([Dokumentation](https://www.home-assistant.io/integrations/automation), [Probleme](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
Erstmals aufgetreten: 09:05:01 (2117 Vorkommnisse)
Zuletzt protokolliert: 14:36:26

Display Wohnzimmer: Maximum number of runs exceeded`

Blueprint 4.3.4 is installed

**Comment by edwardtfn** [comment]
@Wolf6660, do you mind reporting as a new bug and providing more details about your system so we can go more on the details.
