### ISSUE TITLE
Display flashen geht nicht bei 3.0

### ISSUE THREAD

**Issue by MarkuZP** [Blackymas/NSPanel_HA_Blueprint#197]
Hallo Zusammen,

ich habe die Vorgängerversioon erfolgreich flashen können  nachdem ich ein blank tft mit tasmota vorher drauf geflasht hatte (es war Lovelace UI vorher drauf).
Bei dem Upgrade auf die neue 3.0 sollte das ja nicht mehr nötig sein dachte ich.
Also nach dem Flashen der 3.0 und dem Blueprint  Import über den Button TFT Flashen in ESP Home versucht.
Das hat zwei Tage gedauert!!! 
Danach weisses Display und dann System data Error.
Hab ich etwas übersehen? Wurde das hier schon behandelt?

Danke!

**Comment by gris74** [comment]
I use to solve this by doing as mention in this thread [https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/166](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/166)

**Comment by MarveyHAB** [comment]
Hi,
Bei mir war es genau so. 
meine Lösung war;
1.  blank tft reinladen via dem neuen Dienst (blank Datei in den config/www Ordner rein). 
2. die „richtige“ tft auch via dem Dienst (und aus dem www Ordner) reinladen. 

Hoffe es ist so verständlich. Wenn nicht mache ich es gerne was ausführlicher. 
LG 
Marvin

**Comment by Blackymas** [comment]
Hallo, nein im Code ist alles ok - wir haben jetzt nach langem suchen noch eine Variante gefunden die wir ändern können.

Solltest du als bis morgen Nachmittag Zeit haben würde ich dich bitte zu warten damit du direkt das neue TFT verwenden kannst.

Stand jetzt sind wir uns nicht 100% sicher woher das Problem kommt.

@deejaybeam hatte aber heute den selben Fehler bei seinem NSpanel gehabt. Bei Ihm scheint es die Strom zufuhr gewesen zu sein. Er wird dir morgen auch hier kurz schreiben.


Sonst wurde ja dank der aktiven Community (danke an alle) schon zwei Lösungen vorgeschlagen.

Vllt zur Info. die Lösung #166 die @gris74 gepostet hat   - ist das letzte mittel wenn garnichts mehr gehen sollte.

Die Lösung von @MarveyHAB wäre auch der erste Ansatz den ich dir empfehlen würde aber eben mit den neuen TFT Dateien die ich dir morgen zur verfügung stellen würde.

Genau aus dem Grund haben wir im Update 3.0.0 den neuen Service eingebaut damit man schnell und einfach lokal ein TFT hochladen kann

**Comment by MarkuZP** [comment]
Prima, dann warte ich lieber auf das neue TFT. Ich hatte schon diverse Varianten probiert hier. Auch mit 9600 Baud. Die von @MarveyHAB natürlich auch schon aber hat leider nicht funktioniert. Beim ersten flashen aus dem Git hat es zwei Tage gedauert bis das TFT drauf war und dann Whitescreen und System Error. Bin sehr gespannt auf die neue Version!

**Comment by Blackymas** [comment]
die neue Version ist im Stabel ob die jetzt direkt das Problem löst weiß ich nicht - zumindest sollte nach erfolgreichen flash dieser Version das Problem mit dem Thema Baud erledigt sein.

die Variante aus #166 funktioniert definitiv wenn man sich an die richtigen Schritt hält.

Das Problem was du hast ist auch keins vom Code irgendwas scheint hier noch fest definiert zu sein von der default Version was wir nicht wissen daher haben wir aus baud nun bauds gemacht mit wir das fest in die Version schreiben.

hier auch nochmal ein Auszug aus Discord Community.

Hi zusammen, da bei mir gar nichts mehr ging und "System Data Error" nicht wegzubekommen war, habe ich nach einigem suchen den Beitrag gefunden: https://community.home-assistant.io/t/sonoff-nspanel-by-itead-smart-scene-wall-switch-based-on-esp32-and-custom-nextion-touch-screen-panel-display-non-pro-variant/332962/801

**Comment by MarkuZP** [comment]
Bis 4% gehts relativ fix aber dann schreibt er sehr langsam die Blöcke weg...
Ich warte mal ab bis er fertig (so bis morgen:-)  )

**Comment by deejaybeam** [comment]
Hi
Ich hatte gestern ein ähnliches Problem.
Bei mir hatte es evtl. damit zu tun, dass ich das Panel selbst über 5v betrieben hatte, statt mit der originalen Backplate.
Steckt bei dir das Display im originalen Sockel?

Bei deinen Logs sieht man, dass das Panel mit ESPHome nicht "spricht":
```
[12:38:07][C][nextion:124]:   Device Model:     
[12:38:07][C][nextion:125]:   Firmware Version: 
[12:38:07][C][nextion:126]:   Serial Number:    
[12:38:07][C][nextion:127]:   Flash Size:       
[12:38:07][C][nextion:128]:   Wake On Touch:    True
```
Bitte nimm das gesamte Panel vom Strom - also entweder das Display rausklipsen, oder überhaupt die 220 weg (FI)...

Nach dem reboot sieh dir die Logs über ESPHome an - da muss UNBEDINGT so was drinnen stehen:
```
[C][nextion:123]: Nextion:
[C][nextion:124]:   Device Model:     NX4832F035_011C
[C][nextion:125]:   Firmware Version: 69
[C][nextion:126]:   Serial Number:    42893401A243C068
[C][nextion:127]:   Flash Size:       16777216
[C][nextion:128]:   Wake On Touch:    True
```
Einfach ein wenig nach oben scrollen nach dem connect.

Wenn das angezeigt wird kann es weitergehen.
Die nextion update url, die oben im Screenshot ist, ist ganz einfach falsch!
Du hast angegeben: "http://192.168.178.81.8123/config/www/nspanel.tft"
Richtig wäre: "http://192.168.178.81.8123/local/nspanel.tft"
Sofern die nspanel.tft direkt im Verzeichnis "www" abgelegt ist.

Du brauchst dafür auch nicht unbedingt esphome neu flashen, kannst aber für die nspanel.tft gerne so machen. Es gibt auch einen Service bei dem du eine url angeben kannst. Den findest du unter den Entwickertools, würde in deinem Fall dann so aussehen:
```
service: esphome.nspanelblacky_upload_tft_url
data:
  url: "http://192.168.178.81.8123/local/nspanel.tft"
```

Damit sollte dann der upload des tft starten - dieser dauert normalerweise ca. 10 Minuten

**Comment by MarkuZP** [comment]
Wow!! Vielen Dank für die ausführliche Antwort. Mega!!! Ich weiß das echt zu schätzen. Ok dann breche ich da mal ab (ist jetzt bei 10%) und versuche über www hochzuladen...

**Comment by MarkuZP** [comment]
Ach so zu Deiner Frage @deejaybeam:
Das panel ist über 220V im Träger. Die Pins für 5V sind mir zu wackelig für längeren Betrieb..
Jetzt nach nem Neustart steht im Log:

14:21:14][C][nextion:124]:   Device Model:     NX4832F035_011C
[14:21:14][C][nextion:125]:   Firmware Version: 69
[14:21:14][C][nextion:126]:   Serial Number:    428934015221F554
[14:21:14][C][nextion:127]:   Flash Size:       16777216
[14:21:14][C][nextion:128]:   Wake On Touch:    True
[14:21:14][C][ntc:014]: NTC Sensor 'nspanelblacky Temperature'
[14:21:14][C][ntc:014]:   Device Class: 'temperature'
[14:21:14][C][ntc:014]:   State Class: 'measurement'
[14:21:14][C][ntc:014]:   Unit of Measurement: '°C'
[14:21:14][C][ntc:014]:   Accuracy Decimals: 1

Aber der Dienst startet zwar ohne Fehler aber das Display zeigt nach wie vor nur "System Data Error!" (90Grad gekippt) an. Also keinen Ladefortschritt!

So sieht die YAML aus.
<img width="733" alt="Bildschirm­foto 2023-01-19 um 14 27 03" src="https://user-images.githubusercontent.com/109298227/213454606-b5eca529-bbf0-4992-bc67-3de6d586e383.png">

**Comment by MarkuZP** [comment]
Dann habe ich noch mal über neu flashen mit dieser YAML in ESPHome

..... Auzug
##### DO NOT CHANGE ANYTHING! #####

  #nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft"
    nextion_update_url: "http://192.168.178.81.8123/local/nspanel.tft"
packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
....


Dann steht im Log:
HTTP Request failed; URL: http://192.168.178.81.8123/local/nspanel.tft; Error: connection refused, retrying (1/5)
Aber das File liegt definitiv im www Ordner:
<img width="596" alt="Bildschirm­foto 2023-01-19 um 14 44 49" src="https://user-images.githubusercontent.com/109298227/213458350-830d3993-975c-4532-9e18-dd4d8ca96ed3.png">

Log
14:41:27][D][switch:013]: 'nspanelblacky Update TFT display' Turning ON.
[14:41:27][D][nextion_upload:169]: Connected
[14:41:27][D][nextion_upload:175]: Requesting URL: http://192.168.178.81.8123/local/nspanel.tft
[14:41:38][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.178.81.8123/local/nspanel.tft; Error: connection refused, retrying (1/5)
[14:41:38][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.178.81.8123/local/nspanel.tft; Error: connection refused, retrying (2/5)
[14:41:38][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.178.81.8123/local/nspanel.tft; Error: connection refused, retrying (3/5)
[14:41:38][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.178.81.8123/local/nspanel.tft; Error: connection refused, retrying (4/5)
[14:41:39][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.178.81.8123/local/nspanel.tft; Error: connection refused, retrying (5/5)
[14:41:39][D][nextion_upload:324]: Restarting Nextion
[14:41:40][D][nextion_upload:327]: Restarting esphome
INFO nspanelblacky.local: Ping timed out!
INFO Disconnected from ESPHome API for nspanelblacky.local
WARNING Disconnected from API
INFO Successfully connected to nspanelblacky.local
[14:41:49][C][ota:093]: Over-The-Air Updates:
[14:41:49][C][ota:094]:   Address: nspanelblacky.local:3232
[14:41:49][C][ota:097]:   Using Password.
[14:41:49][C][api:138]: API Server:
[14:41:49][C][api:139]:   Address: nspanelblacky.local:6053

**Comment by deejaybeam** [comment]
Ich glaube ich hab´s - du hast nach der ip einen punkt statt einem doppelpunkt vor dem Port
Also statt "http://192.168.178.81.8123/local/nspanel.tft" muss das "http://192.168.178.81:8123/local/nspanel.tft" lauten - sorry hatte ich falsch geschickt

**Comment by MarkuZP** [comment]
Oh noooo! Asche auf mein Haupt! Da hätte ich trotzdem selbst merken können. Das mit dem Browser hatte ich auch schon probiert. Irgendwann sieht man den Wald vor lauter Bäumen  nicht mehr:-)

**Comment by MarkuZP** [comment]
1.  blank_tft mit den Diensten in Entwicklerwerkzeuge drauf.
2. neustart
3. dann URL auf nspanel.tft anpassen
4. wieder den Dienst ausführen
5. jetzt geht es viel schneller 10-15 Min
6.Hurra! Es läuft!!!

Danke Euch sehr!

**Comment by Blackymas** [comment]
@MarkuZP 
super das es jetzt geht - ich hoffe das die Änderungen beim nächsten update helfen - sonst weißt du ja jetzt was zu tun ist ;)

**Comment by gebla** [comment]
> 1. blank_tft mit den Diensten in Entwicklerwerkzeuge drauf.
> 2. neustart
> 3. dann URL auf nspanel.tft anpassen
> 4. wieder den Dienst ausführen
> 5. jetzt geht es viel schneller 10-15 Min
>    6.Hurra! Es läuft!!!
> 
> Danke Euch sehr!

I saw a lot off errors in the log and update was extremely slow. I followed the above and it worked perfectly. Thanks!

**Comment by nassermahrous** [comment]
had the same problem with 3 of my Nspanel's. after spending 2 days to fix it, this what worked for me:
1. Flash the NSPanel the stock ESPHome
2. I removed the "_" in the name of the tft file for both the blank and the nspanel tft
3. flash the nspanel again with the nspanel_blackymas code and change the nspanel tft to the blank tft
4. Upload the blank tft
5. flash it again wirelessly and use the nspanel tft file
6. Upload the nspanel tft
I hope this will help
