### ISSUE TITLE
`Enhancement` change weather icon on sunset/dawn

### ISSUE THREAD

**Issue by MichaelHeimann** [Blackymas/NSPanel_HA_Blueprint#1971]
### Enhancement Summary

Change weather icon to day or night mode at sunset/dawn

### Detailed Description

Weather icons exist in day and night mode and which one to display is done right when the weather changes.
Please add a trigger for sunset/dawn

**Comment by MichaelHeimann** [comment]
https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/3189562/83dc08ca-f390-4bd4-922b-117513207b04

**Comment by edwardtfn** [comment]
Solved in `dev` and with be included on v4.3.2 release.
