### ISSUE TITLE
`Enhancement` direct triggering of different beeps

### ISSUE THREAD

**Issue by rosti76** [Blackymas/NSPanel_HA_Blueprint#1979]
### Enhancement Summary

add additional beeping types

### Detailed Description

It would be nice to have not only one beep type, but have some different.
i.e. SOS morsecode beep in case any fire or waterleak alarm or Alarmpanel alarm.
Or tripplebeep in case the Door chime is pressed.

**Comment by edwardtfn** [comment]
You can have an automation calling `rtttl_play` service with any tone you want...

https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/api.md#rtttl-play-service-rtttl_play

**Comment by rosti76** [comment]
Oh, RTFM :-( Sorry, solution is already available :-)

Thank you.
