### ISSUE TITLE
`Enhancement` Swiping of Btn Pages

### ISSUE THREAD

**Issue by Maxsani1990** [Blackymas/NSPanel_HA_Blueprint#1980]
### Enhancement Summary

Restore swiping direction of Btn pages

### Detailed Description

I appreciate the change that empty button pages are hidden now.
But i liked the old behaviour that if you configure a button on the third page that you can swipe from down to up and see the page on the panel. For example i have my robot vacuum controls all on the third page and now in some rooms, where also page 1 and 2 are configured i still can swipe down to up to access it. If one of the other pages is missing i cannot do that in the current version.

**Comment by edwardtfn** [comment]
It should work. I will take a look.

**Comment by edwardtfn** [comment]
What happens now when you swipe up/down from home page?
I’m far from my panel now.

**Comment by Maxsani1990** [comment]
I currently have not configured page 4 at any of my panels. So i cannot tell for sure :-/
Heres what happens when i swipe with configured pages 1 and 3:
Up to down: page 1
Right to left: page 1
Down to up: nothing
Left to rigt: page 3

**Comment by edwardtfn** [comment]
I would expect both up-down and down-up jumping to page 2.
I will take a look.

**Comment by edwardtfn** [comment]
As I understood, you have pages 1 and 3, but not pages 2 and 4, is that correct?
I'm trying to duplicate this here.

**Comment by Maxsani1990** [comment]
Yes exactly.
Also I have one panel with just page 3 configured, where i can only access the page with swiping left or right and not up.

**Comment by edwardtfn** [comment]
> Also I have one panel with just page 3 configured, where i can only access the page with swiping left or right and not up.

What would you expect/wish in this case?

**Comment by Maxsani1990** [comment]
I would also expect if i swipe up on the homepage that i access the configured page. Like it was before hiding empty btn pages.

**Comment by edwardtfn** [comment]
But this is the thing... Before we always had 4 pages, so we had one page always associated to up and another one to down (pages 2 and 3, I don't remember which direction was each one), but now we might not have some of those pages, so I've changed to behave to be:

Left to right -> Previous page (just like before, but now skipping the hidden pages)
Right to left -> Next page
Up to down -> Previous, skipping 1 page
Down to up -> Next, skipping 1 page (this is not working now, I'm looking at that)
The pages are: home > buttonpage01 > buttonpage02 > buttonpage03 > buttonpage04 in a loop (from last page you go to home and vice-versa).
In my understand, that makes more sense, as the pre-defined was moving to the same page where you are in some cases.

But that doesn't means I'm right. 😉 

I think that use case where you have only one page, any direction you swipe should always go to that one page. 😉  And from there, any swipe direction should return to Home.

**Comment by Maxsani1990** [comment]
Sounds good, if you are already located at the btn pages :)
My suggestion as improvement is that if you are on the homepage you directly link the swiping gesture (at least swiping up or down) to a specific page (and not do anything if this page isn't configured).
Because we now have two things to discuss (the bug that swiping up is not working correctly and my improvement for directly linking the pages) i can also open a second ticket if you want to.

**Comment by edwardtfn** [comment]
I believe this is fixed in `dev` and will be included in the next release. I would appreciate your feedback about the new implementation when you have a chance to try it.
