### ISSUE TITLE
more easy to see "X" on the upper right

### ISSUE THREAD

**Issue by Bascht74** [Blackymas/NSPanel_HA_Blueprint#1984]
### Enhancement Summary

use a bigger icon for the "X"

### Detailed Description

Right now the "X" on the upper right is rather small, not easy to see and you have to concentrate to hit it :-)

With my standard configuration of the blueprint it is only white with a black backgroud. 

Could you make the "X" a little bit bigger and add some colors that it looks more like an button to exit the page?
More like the on/off Button you added recently for lights detail page.

more like here, but a little bit bigger:
https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/docs/pics/eu_entities.png

**Comment by edwardtfn** [comment]
I've increased the icon a bit. It still in `dev` and will be included in the coming release.
I will close this for now, but please reopen if it still too small after the release/update.
