### ISSUE TITLE
Cannot delete/remove button icon from home page

### ISSUE THREAD

**Issue by vitalikkh** [Blackymas/NSPanel_HA_Blueprint#1992]
### Panel Model

None

### What is the bug?

After home page button was created the icon for this button cannot be removed when button associated entity is removed.
Button itself becomes non functional but Icon still is visible.
Reassigning new entity actually replaces an icon with a correct one but after entity is remove Icon want not go away.

**Comment by czcrimpy** [comment]
Did you try reboot display? I have same problem with and reboot solved it.

**Comment by vitalikkh** [comment]
Ops, Thank You for the very good hint. And yes, the reboot solves the problem.

**Comment by edwardtfn** [comment]
Solved in `dev` and will be included in the next release.
