### ISSUE TITLE
Resolving IP adress

### ISSUE THREAD

**Issue by kristianolofsson** [Blackymas/NSPanel_HA_Blueprint#1993]
### Panel Model

EU

### What is the bug?

When trying to update the nspanel to the newest version it downloads, compiles but fails in the final step trying to locate ip 

the panel is connected checking the router and the WiFi indicator on the panel shows the same.

**Comment by edwardtfn** [comment]
Are you using manual IP, VLANs, or something different than standard?

**Comment by kristianolofsson** [comment]
No, nothing special. I used to have fixed ip but removed it. Didn’t help

**Comment by kristianolofsson** [comment]
![IMG_1464](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7191232/daa32bf2-cd01-4766-bb13-0f41b592ed6c)

**Comment by kristianolofsson** [comment]
...
Successfully created esp32 image.
esp32_create_combined_bin([".pioenvs/nspanel1/firmware.bin"], [".pioenvs/nspanel1/firmware.elf"])
Wrote 0x12ca20 bytes to file /config/.esphome/build/nspanel1/.pioenvs/nspanel1/firmware-factory.bin, ready to flash to offset 0x0
======================== [SUCCESS] Took 102.67 seconds ========================
INFO Successfully compiled program.
INFO Resolving IP address of nspanel1.local
ERROR Error resolving IP address of nspanel1.local. Is it connected to WiFi?
ERROR (If this error persists, please set a static IP address: https://esphome.io/components/wifi.html#manual-ips)
ERROR Error resolving IP address: Error resolving address with mDNS: Did not respond. Maybe the device is offline., [Errno -2] Name or service not known
============== [ERROR] /config/nspanel1.yaml ==============

**Comment by edwardtfn** [comment]
If you used to have manual ip you should return with that until fix this, as it is easier to have it working using ip than host names. ;)
Have you changed anything else? Device name?
Please try to add this to your substitutions:
```yaml
  name: nspanel1
```

**Comment by kristianolofsson** [comment]
Changed it back and restarted HA so as the NSPanel, still the same error as above. :(

The router shows the IP to the NSpanel, but it seems to be a conflict since the panel it self is not connected.

Can I force the panel it self to a specific IP and not only the router?

**Comment by edwardtfn** [comment]
Yes, you can instruct the panel itself to use a specific IP: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/dev/docs/customization.md#manual-ip

**Comment by kristianolofsson** [comment]
That solved it. Big thank you!
