### ISSUE TITLE
`Bug` Cannot swipe to left

### ISSUE THREAD

**Issue by misery** [Blackymas/NSPanel_HA_Blueprint#1994]
### TFT Version

4.3.1

### ESPHome Version

4.3.1

### Blueprint Version

4.3.1

### Panel Model

EU

### What is the bug?

If I want to swipe with the finger from "left to right" I will see the left button page. That is expected. But if I swipe again the same direction it will jump to home screen. I would expect that it swipes to next page. Any other direction from home screen like "right to left" works as expected.

### Steps to Reproduce

1. Swipe to left page
2. You see left page
3. Swipe to "next" left page
4. You see home screen (instead of next page)

**Comment by ajvdw** [comment]
Swipe up doesn't work anymore in 4.3.1.
Swipe down show the button screen that used to show up at swipe up.

**Comment by leranp** [comment]
> Swipe up doesn't work anymore in 4.3.1.
> Swipe down shows the button screen that used to show up at swipe up.

Same here

**Comment by edwardtfn** [comment]
I believe this is fixed in `dev` and will be included in the next release.
