### ISSUE TITLE
Alarm control with hardware button

### ISSUE THREAD

**Issue by czcrimpy** [Blackymas/NSPanel_HA_Blueprint#1995]
### Enhancement Summary

add this feature, please

### Detailed Description

Hi,

when I add home icon linked to Alarm control panel - this work fine. When I add link to Alarm to hardware button - this do not open alarm control panel - do nothing.

Please add this. Thanks Petr

**Comment by edwardtfn** [comment]
Solved in `dev` and will be included in the next release soon.
