### ISSUE TITLE
ESP Chip Auto-Detection failed

### ISSUE THREAD

**Issue by adamengineering** [Blackymas/NSPanel_HA_Blueprint#1996]
### Panel Model

EU

### What is the bug?

I received a brand-new NSPanel EU this morning. I did connect it to main power bootet it up and linked it to the eWeLink just to make sure it works.

I disassembled the panel attached it to my USB-to-Serial TTL (used many time before for my older Panels). Now when I try to install the firmware i get a connection error with no further details what happened.

I then tried to use esphome-flasher and here i get the following message:

**Using '/dev/cu.usbserial-A50285BI' as serial port.
Connecting......................................
Unexpected error: ESP Chip Auto-Detection failed: Failed to connect to Espressif device: No serial data received.
For troubleshooting steps visit: https://github.com/espressif/esptool#troubleshooting**

I unmounted one of my older Panels, just to see if it has the same problem, but No it did not and it worked as it was intended.

Reattached the 'new' panel to my TTL - back again with the Unexpected error...

Went back to the eWeLink App and checked for informations reported by the device:

- Firmware 1.4.0
- FW-Name: E32-MWS-NX

Can someone point me into the right direction, how to flash this device? Thx

**Comment by edwardtfn** [comment]
I never heard about a non-compatible panel unless you are talking about the NSPANEL Pro model (the one without the physical buttons).

Why don't you send some pictures of your board? I can take a look on my panel and compare chip model, etc.

**Comment by adamengineering** [comment]
Hi Edward, thx for looking into it, here are the images requested.
I did some further digging into my USB Dongle and it delivers 3.148V, although 3.3V are advertised.
My older panels seem to have no problem with the under voltage, the new one might. This is just me making an assumption. I've ordered a few other, just to test if they will deliver better voltage and maybe get the flash going.

![IMG_0815](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/23257336/2d1f1507-fbd8-4705-995f-0f6fdacfce84)
![IMG_0816](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/23257336/54f024e0-e0d9-44c7-b8a1-3e8f11b23d24)

**Comment by edwardtfn** [comment]
I'm not home now, but I see nothing noticible on your board. But I will open my panel when getting home just to double check.
I don't think 3.148V would be an issue...

What if yiu assemble the panel back? Is it still working fine with Sonoff stock firmware?

**Comment by adamengineering** [comment]
It works with the original firmware, no problem there. I compared it to my old panels and couldn't see a difference, besides some missing prints on the ECB

**Comment by adamengineering** [comment]
This is the inside of one of my older panels
![IMG_0817](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/23257336/daaef7ff-a8c3-4137-94f2-475a0a613dc5)

**Comment by edwardtfn** [comment]
I see the PSRAM chip is a diferent one, but with the same capacity (16Mb). That shouldn't be an issue anyways. ESP looks exactly the same.
Which tool are you using to flash it? [ESPHOME Web](https://web.esphome.io/)?

**Comment by MichaelHeimann** [comment]
I also just got some new panels so I was worried a little. 
The side of the PCB you posted looks like the one I have here. Do you maybe have a picture of the other side of the PCB?

This is how the one I got last week looks:
![IMG_20240329_224540](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/3189562/aa55056f-a21e-4b1c-9551-b54da0a695e6)
![IMG_20240329_224552](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/3189562/356ef39c-2d21-4f8b-b07a-098cb1d7a9c9)

I'm kinda worried because I'm just starting to sell prebuilt nspanels. If interested, ping me (email in profile)

**Comment by edwardtfn** [comment]
But did you also got issues flashing your new panel?
From where did you got those panels?

**Comment by MichaelHeimann** [comment]
Sorry, I do NOT have issues. all fine. I hope this is hopefully just a small RX/TX confusion etc..

**Comment by adamengineering** [comment]
The other side of my PCB looks exactly like the one Michael posted.
And NO i don't have RX/TX confused. As I said using the same setup on my old panel works.
Attaching it to the newer one doesn't, it looks to me as if one or more of the pins do not make a proper connection with the PCB, or as guessed the Voltage delivered from my USB-TTL is not enough.

**Comment by MichaelHeimann** [comment]
> The other side of my PCB looks exactly like the one Michael posted.
> And NO i don't have RX/TX confused. As I said using the same setup on my old panel works.
> Attaching it to the newer one doesn't, it looks to me as if one or more of the pins do not make a proper connection with the PCB, or as guessed the Voltage delivered from my USB-TTL is not enough.

Weird that the same serial adapter works with the other panels. But if it only happens on that one panel it could be a hardware issue with that panel.
Maybe really something that makes that specific board use more power.
Did you try without display connected?

**Comment by bkbartk** [comment]
> it looks to me as if one or more of the pins do not make a proper connection with the PCB

If you did not mix up tx/rx then indeed that you’ll be my guess too. 
this could always happen. However I’m not sure if you can claim warranty for this. 

“What’s wrong with it?”
“I’m not able to run custom firmware”

**Comment by adamengineering** [comment]
I stopped counting the number of attempts and assumed that it must be a hardware problem. So I said to myself one last try wouldn't hurt (warranty for what?), soldered the Dupontwires directly to the PCB and lo and behold, flashing worked on the 'first' try. My guess is that when I simply plugged in my adapter, a proper contact was never made and therefore the flashing was never initiated.

Anyway, **thank you** guys for looking at my 'bug' and helping me out with your suggestions. Edward, maybe attach this thread somewhere, where it can easily be found, in case someone else stumbles upon the same problem.

![tempImagezJYcDO](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/23257336/9b3909fd-8032-41b5-8ce7-1ab55a92e4b6)

**Comment by edwardtfn** [comment]
> I'm just starting to sell prebuilt nspanels. If interested, ping me (email in profile)

@MichaelHeimann, I think this is nice and aligned with my goal of [Simplifying User Experience for NSPanel Firmware](https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1602). I've started some work in a prebuilt firmware which woukd be easier for users who don't wanna to compile themselves and this is probably aligned to your idea of selling the devices ready to use.
Perhaps we should open a discussion for this or even you should use that thread to inform people about this option.

**Comment by MichaelHeimann** [comment]
> > I'm just starting to sell prebuilt nspanels. If interested, ping me (email in profile)
> 
> @MichaelHeimann, I think this is nice and aligned with my goal of [Simplifying User Experience for NSPanel Firmware](https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1602). I've started some work in a prebuilt firmware which woukd be easier for users who don't wanna to compile themselves and this is probably aligned to your idea of selling the devices ready to use. Perhaps we should open a discussion for this or even you should use that thread to inform people about this option.

I've used that prebuilt work and am improving it in my repository right now. I run that code here with some test-panels and it seems fine. How can I merge that? Make a PR into dev?

**Comment by sujitrp** [comment]
Please help with soldaring the Pins and correcting the RX TX i am able to get this information but same error 
Using 'COM4' as serial port.
Connecting.....
Detecting chip type... ESP32
Connecting.....
Log on ESP flashere 3.0.3
Chip Info:
 - Chip Family: ESP32
 - Chip Model: ESP32-D0WDQ5-V3 (revision v3.1)
 - Number of Cores: 2
 - Max CPU Frequency: 240MHz
 - Has Bluetooth: YES
 - Has Embedded Flash: NO
 - Has Factory-Calibrated ADC: YES
 - MAC Address: A0:A3:B3:89:A8:34
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 1500000
Changed.
Chip does not support baud rate 1500000, changing to 115200
Connecting......................................
Unexpected error: ESP Chip Auto-Detection failed: Failed to connect to Espressif device: No serial data received.
For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html
****
