### ISSUE TITLE
Feature request : door = wake UP sensor

### ISSUE THREAD

**Issue by NiC1305** [Blackymas/NSPanel_HA_Blueprint#1998]
### Enhancement Summary

Opening door as a wake UP sensor

### Detailed Description

Hello, I would like the screen to turn on when you open a door.  currently only motion detectors seem to be usable.  THANKS

**Comment by edwardtfn** [comment]
Door sensor is currently supported. Are you sure your sensor have device class set to `door`? Is that a binary sensor?

**Comment by NiC1305** [comment]
The device class is "opening"

**Comment by edwardtfn** [comment]
I've added support to a few more devices classes, including opening. It will be in the next release.
