### ISSUE TITLE
Initial Testing

### ISSUE THREAD

**Issue by diginfo** [Blackymas/NSPanel_HA_Blueprint#2]
Hello, 

Firstly thanks, the UI is very nice.

So I have installed & done a little bit of testing, and I fully understand that this is under development and is not complete, but of course everything is in German and it appears that many of the values / weather etc are hard-coded still ?

Also, how do you access the buttons page ? - I tried touching the panel in different places but was not able to bring up the buttons page.

I also translated the day of week in the sensors.yaml but the panel is still showing German :-)

![IMG_5267 Large](https://user-images.githubusercontent.com/6010010/196313746-a662e78b-01d7-442a-9e13-9544ae920d4b.jpeg)

![IMG_5266 Large](https://user-images.githubusercontent.com/6010010/196313756-7c3714d0-cf53-40cc-9d97-a082e13c414f.jpeg)

![IMG_5268 Large](https://user-images.githubusercontent.com/6010010/196313738-a4e1cf6b-ce5a-4e32-b204-fd0ce1a458c1.jpeg)

<img width="1165" alt="Screenshot 2022-10-18 at 9 30 46 AM" src="https://user-images.githubusercontent.com/6010010/196314268-bb51ab0b-ffda-4f8b-ade9-c4b86736be2e.png">

<img width="1078" alt="Screenshot 2022-10-18 at 9 34 52 AM" src="https://user-images.githubusercontent.com/6010010/196314747-406251c8-e325-45de-8625-1ff38502b928.png">

**Comment by Blackymas** [comment]
Hi,

Are you using the versions from the beta folder?

**Comment by Blackymas** [comment]
Done in v2.0.0
