### ISSUE TITLE
Initialization is always  on the screen

### ISSUE THREAD

**Issue by dinamik1488** [Blackymas/NSPanel_HA_Blueprint#200]
Initialization is always  on the screen. reflashing does not help

**Comment by Blackymas** [comment]
Hello,

there are many approaches if I have understood your problem correctly.

1. do you have the current esphome, tft and blueprint file in use?

2. in the name you have a special character or a -.

3. have you already set up a blueprint? without blueprint it stops in boot

**Comment by dinamik1488** [comment]
Thanks. Solved the problem. I have automation.yaml has been rendered to includes.

**Comment by dinamik1488** [comment]
Danke für das coole Projekt

**Comment by Blackymas** [comment]
> 

Danke freut uns wenn es dir gefällt. 
Falls du super happy bist würden wir uns natürlich über eine kleine Donation via Paypal sehr freuen - der Link ist direkt auf der Startseite ;P
