### ISSUE TITLE
Hebrew in the Button Page is missing character 

### ISSUE THREAD

**Issue by leranp** [Blackymas/NSPanel_HA_Blueprint#2000]
### TFT Version

4.3.1

### ESPHome Version

4.3.1

### Blueprint Version

4.3.1

### Panel Model

EU

### What is the bug?

When set a name to the button with more than 5 characters making it appears in wrong way, this is an example, the button is set with string "מסדרון" ,but the "מ" disappear and a character "ס" appear in a new line.
Also the word "ארונות" and "אמבטיה"
![20240329_222214](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/9452319/d3775118-6765-48dc-8ae7-ad2352a9b510)

**Comment by edwardtfn** [comment]
This was partially solved in `dev` and will be part of the next release.
For v4.3.3, you will have to add this to your panel's yaml in the substitutions area:

```yaml
  bytes_per_char: "2"
```

That won't be necessary with v4.4.

None of those versions are available yet. 😉
