### ISSUE TITLE
`Bug` DST issue

### ISSUE THREAD

**Issue by Ulrar** [Blackymas/NSPanel_HA_Blueprint#2005]
### TFT Version

4.3.1

### ESPHome Version

4.3.1

### Blueprint Version

4.3.1

### Panel Model

Arduino

### What is the bug?

DST change not applied

Apologies, was filling this out on my phone and somehow it submitted before I was done so I can't see the drop-downs anymore.

Anyway the issue is my panels didn't change time with everything else yesterday, they're still one hour behind.
Where does the time come from? My HA container has the right timezone in its env var, and in the app all the times look right so presumably the container has it set correctly.
Thanks

**Comment by Ulrar** [comment]
I upgraded recently and hadn't seen this, that did the trick, thanks !

**Comment by Ulrar** [comment]
This is a problem again today. I have the timezone set in the blueprint settings correctly, but it's still showing the time it would have been yesterday before the change. I tried recompiling, no luck.

HA itself shows the right time

**Comment by edwardtfn** [comment]
> not sure why the blueprint setting doesn't work but good with it set right

I will look at that.
