### ISSUE TITLE
Backlight setting not working correctly

### ISSUE THREAD

**Issue by czcrimpy** [Blackymas/NSPanel_HA_Blueprint#2006]
### TFT Version

4.3.1

### ESPHome Version

4.3.1

### Blueprint Version

4.3.1

### Panel Model

EU

### What is the bug?

Hi,

the change of display backlight through home assistant in Dimmed mode is not working correctly. For example, when I have the backlight set to 30% and change it to 90%, the display brightens up, but if I set it back to 30% or 1%, it still shines at 90% until I touch the screen and the timeout elapses.

I'm interested in utilizing automation based on time or other conditions, but in some cases, especially as described above or with repeated changes in backlight value, it stops working until display is touched.

EDIT: Increasing the backlight from 30% to 31%, 35% to 60%, etc. works immediately. The reduction of the backlight from 60% to 50%, 40% to 1%, etc. will take effect only after the display is pressed and the timeout has expired.

Thanks Petr

**Comment by edwardtfn** [comment]
Fixed in `dev` and will be released soon.
