### ISSUE TITLE
`Enhancement` Control of blinds via relay

### ISSUE THREAD

**Issue by czcrimpy** [Blackymas/NSPanel_HA_Blueprint#2016]
### Enhancement Summary

add support for cover/blinds

### Detailed Description

Hi,

what about controls Blinds via relays?

1st relay - blinds up
2nd relay - blinds down

Configuration:
Running time UP (sec)
Running time DOWN (sec)

From running time you can calculate the position of the blind.

Prevent to both relay to "on" concurrently.

In future configuration fot tilt.

Thanks Petr

**Comment by edwardtfn** [comment]
- #1752

**Comment by edwardtfn** [comment]
Simplified version implemented on dev and will be part of the next release.
