### ISSUE TITLE
`Bug`  Switching back to nomal relay control after setting entity not working

### ISSUE THREAD

**Issue by FloFri** [Blackymas/NSPanel_HA_Blueprint#2017]
### TFT Version

4.3.2

### ESPHome Version

2024.3.1

### Blueprint Version

4.3.2

### Panel Model

EU

### What is the bug?

I currently have the following problem. After I have installed the panel the relay was working as expected. Pressing the button toggled it. I then did set an entity for that button in the automation. Also worked as expected (no toggling of relay, but toggling of entity). I then deleted the entity again in the Automation. But after I have removed the entity the normal relay control did not return. The button now does nothing (relay control directly in HA does work).

### Steps to Reproduce

1. Set entity for button
2. Remove entity
3. Button does not work

**Comment by edwardtfn** [comment]
There's an entity related to that relay available under your panel's device in Home Assistant.
Assign that entity to the respective button on the Blueprint settings. This will instruct the panel to control that locally.

**Comment by FloFri** [comment]
Thx for the fast reply. Did not think about that. Works now. Thx!
