### ISSUE TITLE
Entity on Homepage will not clear on screen after removing it from the blueprint

### ISSUE THREAD

**Issue by fbbln** [Blackymas/NSPanel_HA_Blueprint#2018]
### TFT Version

4.3.1

### ESPHome Version

2024.3.0

### Blueprint Version

4.3.1

### Panel Model

EU

### What is the bug?

If an entity on the homepage was once filed it will not clear again.
- Removing it from the Blueprint will not clear the text on the screen
- Having a Sensor that return an Emtpy string in some cases will not show that empty string on the screen but the last filled string.

### Steps to Reproduce

Create a template sensor Helper:
`{% if is_state('binary_sensor.isteinfensteroffen', 'on') %}
{{ (now().timestamp() - as_timestamp(states.binary_sensor.isteinfensteroffen.last_changed) ) | timestamp_custom('%H:%M', False)}}
{% else %}
  
{%endif %}`

Add this sensor as an entity to the homepage.

It shows either an empty String or the time the window is open.
If the rsulting sensor is then added as an entity to the homepage the behaviour above happens. It correctly shows the time but if the windows are closed, the last time will not clear.

BTW, this works nicely with labels on the button pages. There I don’t even need the helpers…you can add the template directly as a label.

### Your Panel's YAML

```yaml
All default.
```

**Comment by edwardtfn** [comment]
- #1992

**Comment by fbbln** [comment]
Same as in the other ticket: a reboot will correct the shown text but if used dynamically that's not a solution ;-)

**Comment by edwardtfn** [comment]
Solved in `dev` and will be included in the next release.
