### ISSUE TITLE
Using mdi:void as icon on homepage does not work

### ISSUE THREAD

**Issue by fbbln** [Blackymas/NSPanel_HA_Blueprint#2019]
### TFT Version

4.3.1

### ESPHome Version

2024.3.0

### Blueprint Version

4.3.1

### Panel Model

EU

### What is the bug?

Using icon mdi:void does not work. It still shows the "eye" icon.

### Steps to Reproduce

Set mdi:void as an icon for an entity on the homepage.

**Comment by edwardtfn** [comment]
`mdi:void` is not officially supported by the Material Design Icons, but in the panel we are even more limited to the icons on this list (which doesn't includes `mdi:void`): https://htmlpreview.github.io/?https://github.com/jobr99/Generate-HASP-Fonts/blob/master/cheatsheet.html

Anyhow, what are you trying to achieve with this? We probably can find an easier way to solve that. 😉

**Comment by fbbln** [comment]
Simply show an Entity without any Icon next to it is the goal.
