### ISSUE TITLE
Philips Hue Centris reagiert weird

### ISSUE THREAD

**Issue by MarkuZP** [Blackymas/NSPanel_HA_Blueprint#202]
Meine Centris wurde von der Vorgängerversion problemlos angesteuert. Jetzt kann ich nicht mehr sauber Dimmen.
Das verhält sich etwas weird. Es wird heller wenn ich den Slider runterschiebe und die Prozentangaben passen nicht.

**Comment by Blackymas** [comment]
ja das kenne ich - das ist ein komischer Fall - das passiert aber nur beim sliden - wenn du beim slider "rein tippst" sollte es gehen.

**Comment by MarkuZP** [comment]
Ja dann geht es besser, stimmt. War aber meine ich mit  der vorherigen Version nicht. Oder hat es evtl. mit der Sync Einstellung im Blueprint zu tun?

**Comment by deejaybeam** [comment]
> Ja dann geht es besser, stimmt. War aber meine ich mit der vorherigen Version nicht. Oder hat es evtl. mit der Sync Einstellung im Blueprint zu tun?

Ja genau dafür ist die Sync-Einstellung.
Das Problem ist einfach wie schnell das Feedback vom Enddevice über HA zurück zum Panel kommt.
Vermutlich ist das ein Zigbee-Device - da ist halt eine Latenz vorhanden.
Für jede kleinste Änderung im Slider am Display wird eine Änderung geschickt - diese werden in parallel laufenden Jobs zum Device Übertragen, welches dann irgendwie/irgendwann die Rückmeldungen ans Display schickt um die Anzeige (den Wert des Sliders) zu aktualisieren - wenn da SYNC aktiviert ist dann kommt es da zu gaaanz vielen Meldungen die eben das Verhalten auslösen.

**Comment by MarkuZP** [comment]
Danke @deejaybeam ! Ich spiele mal mit den Slidern.

**Comment by MarkuZP** [comment]
<img width="1037" alt="Bildschirm­foto 2023-01-20 um 13 16 07" src="https://user-images.githubusercontent.com/109298227/213692942-e54e9c11-c4c4-46c1-bcc2-0f100dcf7ebe.png">
Gemeint ist aber nicht Delay oben sondern die Sync option darunter ne?

**Comment by Blackymas** [comment]
hast du es mal ausprobiert - am besten stelle beides auf no.

Du brauchst das eigentlich nicht bzw siehst du den unterschied vom sync nur wenn du parallel HA offen hast und auf den Helligkeitssteuerung wert schaust.

Die Funktion YES ist nur drin weil ich es bei meinem ersten versuch so programmiert hatte und das selbe problem danach hatte.

Deshalb haben wir es geändert und den wert auf default NO gesetzt, weil essen eigentlich auch keinen Sinn macht ;)
