### ISSUE TITLE
`Bug` Firmware fallback from 4.3.2 to 4.2.6 after power loss

### ISSUE THREAD

**Issue by maxkr2** [Blackymas/NSPanel_HA_Blueprint#2027]
### TFT Version

4.3.2

### ESPHome Version

4.3.2

### Blueprint Version

4.3.2

### Panel Model

EU

### What is the bug?

If I restart device or reconnect to power firmware falls back to 4.2.6. 
Installing new version helps, but how can I solve issue?

### Steps to Reproduce

Find device, click restart: Firmware changes from 4.3.2 to 4.2.6 after reboot.

**Comment by edwardtfn** [comment]
Please take a look at this one:

- #1821

**Comment by maxkr2** [comment]
Thank you Edward,
serial flashing solved the issue!
