### ISSUE TITLE
`Bug`  Internal temperature reporting disappearing for a few seconds when returning from sleep

### ISSUE THREAD

**Issue by bugtoo** [Blackymas/NSPanel_HA_Blueprint#2030]
### TFT Version

4.3.2

### ESPHome Version

4.3.2

### Blueprint Version

4.3.2

### Panel Model

EU

### What is the bug?

If the panel is sleeping (screen is off) and I tap it, the home page is displayed but the internal temperature indicator (which comes from the panel internal sensor in my case) disappear for a few seconds and then appears again.

https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16280306/64c215b4-93bb-478f-89b5-9bd86e4c0bfc

**Comment by edwardtfn** [comment]
This is fixed in `dev` and will be included in the next release.
Thanks for the detailed example. :)
