### ISSUE TITLE
`Bug` I can't go to the climate page when i touch the screen

### ISSUE THREAD

**Issue by gn33** [Blackymas/NSPanel_HA_Blueprint#2040]
### TFT Version

4.3.3

### ESPHome Version

4.3.3

### Blueprint Version

4.3.3

### Panel Model

US (Landscape)

### What is the bug?

- On Home page - Entity  - Icon color, i have all the time a white icon even i set a color
- I can't go to the climate page when i touch the screen ( previously  on 4.3.1 and 4.3.2 it work well)

**Comment by gn33** [comment]
Regarding the first point : "On Home page - Entity - Icon color, i have all the time a white icon even i set a color"  did you see what's append ?

**Comment by edwardtfn** [comment]
I will look at that in this other thread.
- #2043 

I wanna release a fix for this issue with the climate asap, as that will affect many people.

**Comment by gn33** [comment]
I check in dev and climate work well Thanks
