### ISSUE TITLE
On Home page - Entity - Icon color, i have all the time a white icon even i set a color

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#2043]
Regarding the first point : "On Home page - Entity - Icon color, i have all the time a white icon even i set a color"  did you see what's append ?

_Originally posted by @gn33 in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/2040#issuecomment-2047611565_

**Comment by edwardtfn** [comment]
Hey @gn33, do you know if is this a new issue or it was the same with v4.3.2?

**Comment by gn33** [comment]
Yes i have this issue on 4.3.2 but not on 4.3.1

---- Message d'origine ----

**Comment by edwardtfn** [comment]
Fixed in `dev`.
