### ISSUE TITLE
Settings icon missing?

### ISSUE THREAD

**Issue by Protoncek** [Blackymas/NSPanel_HA_Blueprint#2048]
### TFT Version

4.3.4

### ESPHome Version

4.3.4

### Blueprint Version

4.3.4

### Panel Model

US (Landscape)

### What is the bug?

Hi!
I just got my NS panel yesterday and i'm playing with it..
I searched through issues, but i just can't find any info regarding my "problem": icon for settings (brightness etc...)  in lower left corner is missing on my device. Is it just some basic fault on my side? 
Also: is today's menu somewhat different than in youtube's video? I mean - if i swipe from left or from bottom up i always get my buttons 2 page (currently i have only two), while for entities an icon is shown on main panel. Is that ok?
What are purposes of additional line in esphome: "nspanel_esphome_addon_climate_dual.yaml" ? I do have Mitsubishi climate...

Thanks!

**Comment by edwardtfn** [comment]
A long press in the time area will bring you to the settings page.

**Comment by Protoncek** [comment]
Aaaa…hidden gem! Even better solution, now that i know it… thanks!
