### ISSUE TITLE
Momentary Switch option feature

### ISSUE THREAD

**Issue by gris74** [Blackymas/NSPanel_HA_Blueprint#205]
Hello,

Can you add a check box option for light when the nspanl switch is connected to a physical momentary switch.
In my case, I solve this with an automation who is turn off the switch as soon as the switch is turned on, but it is ugly solution and bugs appear if need more automation.

Ref. https://esphome.io/components/switch/gpio.html#momentary-switch

**Comment by deejaybeam** [comment]
If you just want to have the relays (switch.xxx) as a light in HA, then you can use: https://www.home-assistant.io/integrations/switch_as_x/
This hides the origin switch (relay) and creates a light.xxx - then just assign this light for the button - everything happens than in the blueprint.

**Comment by gris74** [comment]
Thanks for you answer and I have done this indeed.

But what I mean by momentary switch is to act as a push button let say.
In my house, I have Latching Relays for some light aera, so when you activate the NPANEL relay he stay close or open, and need 2 push to relase the courent in the Latching Relays of the electrical panel.

[https://hager.com/fr/catalogue/media/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/1/5/152545_41.jpg](this is the Latching Relays)

**Comment by hollabee** [comment]
This might be more of an electrical topic:
Are you using a delay in your automation to turn of the Relay again or is it "instantenous"? 
I would suggest to try and start with a 150-250ms Delay and play around with that, just as described in the link your provided. 500ms seems a bit excessive to me.

**Comment by Blackymas** [comment]
I close the ticket @deejaybeam has already explained it to you as well as @hollabee

**Comment by deejaybeam** [comment]
You could also create a script that does the required "impuls" (on-delay-off) for the relay and assign the script to the HW-Button
