### ISSUE TITLE
Can´t install on new nspanel

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#2052]
Hello
Have 4 panels with
TFT Version
4.3.4
ESPHome Version
4.3.4
Blueprint Version
4.3.4
Panel Model
EU
Works fine.
Now i will install a new nspanel using a serial cable.
My nspanel_esphome.yaml is:

![Picture](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/65901152/af63aedb-c67d-4685-a1ab-63c3bbaf6ae6)

Flashing is going good, no problem
But when i power it on, the screen flash "sonoff" 3 times and no more.
??
What do i do wrong?

_Originally posted by @famviuf in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/2047_

**Comment by edwardtfn** [comment]
You have to upload a new TFT from your device's page under Settings > Devices & Services > ESPHome.
Also, make sure you create a new automation using the Blueprint, but this time pointing to the new panel.

**Comment by famviuf** [comment]
But i can´t see my panel under Settings > Devices & Services > ESPHome. There is no new nspanel.
???

**Comment by edwardtfn** [comment]
🤔
What about on your ESPHOME dashboard? Can you see the panel online there?
If so, could you please capture the log of compiling and flashing (a a few seconds after that)?

**Comment by famviuf** [comment]
No online
I will try again tomorrow (work now)
Strange i have 4 panels with no problems
??

**Comment by famviuf** [comment]
I think i have solved the problem
Low power on usb-hub
Sorry for your time

**Comment by edwardtfn** [comment]
Nice that you found the issue. :)
