### ISSUE TITLE
Webserver no longer working after upgrading to 4.3.4 `Bug` 

### ISSUE THREAD

**Issue by BluThunder2k** [Blackymas/NSPanel_HA_Blueprint#2054]
### TFT Version

4.3.4

### ESPHome Version

4.3.4

### Blueprint Version

4.3.4

### Panel Model

US

### What is the bug?

Upon upgrading my 4 panels to 4.3.4 - the embedded webserver no longer answers to port 80 as the log show it has setup:

```
[16:01:57][C][web_server:169]: Web Server:
[16:01:57][C][web_server:170]:   Address: nsdisplaybr.local:80
```

I have them configured with the following which has worked up till now:

```
web_server:
  port: 80
  auth:
   username: admin
   password: xxxxxxx
```

### Steps to Reproduce

Enable webserver in yaml config, and compile.   Device will come online - be pingable - and connect to HA however not accept any connection on the port defined.

**Comment by edwardtfn** [comment]
- #2050 
This was already fixed in dev and will be released soon.
