### ISSUE TITLE
`Enhancement` Wakeup button or wakeup when set Timeout Sleep to 0

### ISSUE THREAD

**Issue by czcrimpy** [Blackymas/NSPanel_HA_Blueprint#2055]
### Enhancement Summary

Wakeup button or wakeup when set Timeout Sleep to 0

### Detailed Description

Hi,

please add Wake Up button or Wake Up device when Timeout Sleep was set 0 (from 1+).

For example when I set evening to 60 sec, device going to sleep after 60 sec.
Morning set Timeout Sleep to 0, but need to wake up device with touch.

It can be assumed that if someone wants to set sleep to 0 so that they want the display to be awake.

Or add "button" to wake up (similar to restart or update TFT button).

BTW: Please wake up in this case to Dimming mode directly.

**Comment by edwardtfn** [comment]
What about the [Wake-up service](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/api.md#wake-up-service-wake_up)?

**Comment by edwardtfn** [comment]
Solved in `dev` and will be included in the coming release.
