### ISSUE TITLE
`Enhancement` minor delay on homepage weather and climate control

### ISSUE THREAD

**Issue by bkbartk** [Blackymas/NSPanel_HA_Blueprint#2056]
### Enhancement Summary

minor delay on buttons

### Detailed Description

At the moment when swiping from left to right it happens to me a lot that I accidentally open waether or climate.
this is since v 4.3.2 (now on 4.3.4 for all components)
before I had no issues with this.
swiping the other side never accidentally applies to the custom bottons.

is it possible to add a minor delay? I think 50ms should be enough.

**Comment by edwardtfn** [comment]
Solved in `dev`
