### ISSUE TITLE
Swipe up and swipe down on home screen are swapped.

### ISSUE THREAD

**Issue by ajvdw** [Blackymas/NSPanel_HA_Blueprint#2058]
### TFT Version

4.3.2 - 4.3.4

### ESPHome Version

4.3.2 - 4.3.4

### Blueprint Version

4.3.2 - 4.3.4

### Panel Model

EU

### What's the bug?

Swipe up and swipe down on home screen are swapped.

**Comment by edwardtfn** [comment]
How would you expect those swipe movement to do?

**Comment by ajvdw** [comment]
> How would you expect those swipe movement to do?

Swipe up and swipe down are swapped. I'd like to have them changed. I know this happened after introduction of the utility page. At some point in time the swipe down didn't work any more and the swipe up showed the button page that showed the button page belonging to the swipe down.
I know this happened because I configure the swipe up to showed the second floor light switch buttons and the swipe down showed the first floor. Now they are swapped.

**Comment by Opontios** [comment]
How can those setting be changed? I've never seen them.

**Comment by ajvdw** [comment]
this issue can be closed when #1107 is implemented.

**Comment by edwardtfn** [comment]
I will close this then and concentrate the discussions on #1107 

- #1107
