### ISSUE TITLE
Change in screen behaviour, no longer switches off

### ISSUE THREAD

**Issue by indyjonesuk** [Blackymas/NSPanel_HA_Blueprint#2066]
### TFT Version

4.3.4

### ESPHome Version

4.3.4

### Blueprint Version

4.3.4

### Panel Model

EU

### What is the bug?

When the device goes to sleep it no longer turns off the screen, instead a screensaver status on showing the button indicators. I have checked the settings but I can find no option to reverse the behaviour. 

### Steps to Reproduce

![20240419_064904](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/109390376/9d5be783-3159-4a86-80ba-a0a12bc2217b)

Behaviour changed after an update

**Comment by edwardtfn** [comment]
Under the device's page (Settings > Devices and Services > ESPHome), please double check the value for "Brightness Sleep". It should be at 0, otherwise the screen will be like in your picture).

**Comment by edwardtfn** [comment]
Hey @indyjonesuk, have the proposed solution worked for you?

**Comment by indyjonesuk** [comment]
Yes it did, no idea how the setting changed but all fixed now ! Thank you
