### ISSUE TITLE
`Bug` Can not update from 4.2.6 to 4.3.4

### ISSUE THREAD

**Issue by AubreyKloppers** [Blackymas/NSPanel_HA_Blueprint#2068]
### TFT Version

4.2.6

### ESPHome Version

4.2.6

### Blueprint Version

4.2.6

### Panel Model

US

### What is the bug?

Can not update from 4.2.6 to 4.3.4

### Steps to Reproduce

1. Update the NSPanel according to documentation from 4.2.6 to 4.3.4 
2. Clean Build Files - see snapshot, "NSPanel 1"
3. Install wirelessly 100% successful - see LOG
5. NSPanel reboots, but gets stuck on Initializing screen - see "NSPanel Photo"
6. Reset device, but when it comes up it displays ESPHome Release 4.2.6 - see "NSPanel Photo 1"
7. Updating the TFT does not update, when system reboots it is back on 4.2.6
![NSPanel 1](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/14271008/2061edf5-46f2-470f-8aa7-e3e476dc5d1b)
![NSPanel Photo](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/14271008/b84a7352-26fe-42be-a67e-8bc5a8ed308d)
![NSPanel Photo 1](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/14271008/d7fefbc6-135f-46ea-9d4b-0856941095b9)
[logs_nspanel_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/15046969/logs_nspanel_run.txt)

**Comment by edwardtfn** [comment]
Under the device's page (Settings > Devices and Services > ESPHome) you will find the TFT Model selector (US in your case) and the TFT upload button. Please try those.
Also, I believe you have previously used Arduino, so unless you have flashed via serial cable on this update, I will suggest adding this to your panel's yaml (at the very end) and then flash it again (wirelessly is fine).

```yaml
esp32:
  framework:
    type: arduino
```

**Comment by edwardtfn** [comment]
- #1821

**Comment by AubreyKloppers** [comment]
Thank you @edwardtfn your help and assistance is greatly appreciated.  Once I re-flashed, all I had to do was update the TFT and everything worked again, as expected.

Thank you again
Aubrey (From Cape Town, South Africa)
