### ISSUE TITLE
Where is the Fan page ?

### ISSUE THREAD

**Issue by PaulBiod** [Blackymas/NSPanel_HA_Blueprint#2074]
### TFT Version

4.3.4

### ESPHome Version

4.3.4

### Blueprint Version

4.3.4

### Panel Model

EU

### What is the bug?

Hi,
I 'm on arduino side, and I see in the docs that there is a Fan page, but I can't see it, neither on the blueprint side, nor on the panel side. Am I missing something ?
Thanks

**Comment by edwardtfn** [comment]
Assign a fan related entity to any of the buttons. A long click on that button will bring you to the fan page. 😉

**Comment by PaulBiod** [comment]
> Assign a fan related entity to any of the buttons. A long click on that button will bring you to the fan page. 😉

Hi, you mean any virtual button ? cause my fan is assigned to the left phisical button
Thanks

**Comment by edwardtfn** [comment]
It should work with the hardware buttons, unless your fan doesn't supports speed or oscillation control. If none of this is supported, then the button will toggle the fan without opening the screen.

**Comment by PaulBiod** [comment]
It supports speed and oscillation. It s a Xiaomi pedestal  1c

**Comment by edwardtfn** [comment]
I will try to duplicate the issue here. You are using one of the hardware buttons, right?

Could you please go to Developer Tools, tab States, find the entity related to that fan and share here it's attributes? I'm more interested on the value related to `supported_features`.

**Comment by PaulBiod** [comment]
Hi, sorry for the late reply.
Here it is
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/28720176/cedad872-efc3-48c8-a1fa-4f1e53ea858f)

**Comment by PaulBiod** [comment]
> I will try to duplicate the issue here. You are using one of the hardware buttons, right?
> 
> Could you please go to Developer Tools, tab States, find the entity related to that fan and share here it's attributes? I'm more interested on the value related to `supported_features`.

Hi, any news on this ?

**Comment by edwardtfn** [comment]
I cannot duplicate this issue. With a fan assigned to a hardware button, a short click is toggling the fan on/off, and the long press is opening the fan detailed page.
If you are not having this same behavior, could you please take a look on both ESPHome logs or Home Assistant logs for something that could help troubleshooting?

**Comment by PaulBiod** [comment]
Hi,
made some tests, and I understand why the hold button didn't show the fan page : it was set up to run a script (custom action).
So, I selected default behavior for hold button, now it works.
But, the top left icon on the fan page is supposed to toggle oscillation,  but it has no effect, I can just click once, and it goes blue, whithout any effect, and once clicked (and blue), next clicks on it have no effect (it stays blue)

**Comment by edwardtfn** [comment]
Any log related to this? Either Home Assistant logs (Settings > System > Logs) or ESPHome logs?
