### ISSUE TITLE
Indoor Temperature in deg. F not correct. `Bug` 

### ISSUE THREAD

**Issue by jdickensttu** [Blackymas/NSPanel_HA_Blueprint#2079]
### TFT Version

4.3.5

### ESPHome Version

2024.3.2

### Blueprint Version

4.3.5

### Panel Model

US

### What is the bug?

When indoor temperature is checked to display (Home Page - Indoor Temperature Sensor Visibility) and the unit is in deg. F (added to YAML), the display shows temperature in deg. C but with F unit (not converting displayed number).  Outdoor temperature is correct.

### Your Panel's YAML

```yaml
temp_units: °F
```

**Comment by edwardtfn** [comment]
Could you please share the logs from ESPHome?
And do you have the latest ESPHome v4.3.5 installed? That should fix this issue.
