### ISSUE TITLE
[min_version] is an invalid option for [esphome]. Please check the indentation.

### ISSUE THREAD

**Issue by pitoganzado** [Blackymas/NSPanel_HA_Blueprint#208]
Failed config

esphome: None
  name: nspanel
  
  [min_version] is an invalid option for [esphome]. Please check the indentation.
  min_version: 2022.10.2 None
  build_path: .esphome/build/nspanel

Please remove the Line 60: **min_version: 2022.10.2** of the file **nspanel_esphome.yaml**

**Comment by Blackymas** [comment]
this is not a wrong configuration. You are just using an old esphome version. Pls update Esphome.

The project was developed on the basis of 2022.10.2 and earlier versions would not be tested. 

We all use the same configuration ;)

**Comment by pitoganzado** [comment]
you're right :| for some reason HA not update the esphome version.
Thank you!

**Comment by Blackymas** [comment]
Welcome ;)
