### ISSUE TITLE
`Bug` Alarm custom button Home Screen not working

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#2081]
### TFT Version

4.3.5

### ESPHome Version

4.3.5

### Blueprint Version

4.3.5

### Panel Model

US

### What is the bug?

After update custom button for alarm does not bring up alarm screen. Alarm screen still works from a button page entity. 

### Steps to Reproduce

Add alarm to custom button. 
press and nothing happens.

**Comment by edwardtfn** [comment]
Could you please share the ESPHome logs from when you press that button?

**Comment by edwardtfn** [comment]
And can you see any error message on your Home Assistant logs (Settings > System > Logs)?

**Comment by edwardtfn** [comment]
Fixed on `dev`. I will try to release it later today.
