### ISSUE TITLE
FR: Buttons das Relais lokal schalten

### ISSUE THREAD

**Issue by T3mplate-wow** [Blackymas/NSPanel_HA_Blueprint#209]
Vielleicht mache ich auch etwas falsch :)

Ich habe den Button links so konfiguriert, dass er das Relais 1 schaltet. Das funktioniert super und ausgesprochen schnell. Aber leider nur wenn Home Assistant online ist. Das ist hoffentlich nahezu immer der Fall, aber gerade Lichtschalter sollten auch einfach so gehen. 
Lässt es sich lösen, dass die Relais lokal (ohne Kommunikation zu HA) geschaltet werden?

**Comment by Blackymas** [comment]
Hallo,

dann musst du den Button direkt in Esphome fast hinterlegen bzw einrichten.

Bei unsere Version ist das nicht vorgesehen - weil wir das voneinander getrennt habenn - also HW Button und Relay.

Sonst wäre es nicht möglich die tasten frei zu belegen

**Comment by T3mplate-wow** [comment]
Hey,
die Entscheidung kann ich nachvollziehen. Button 2 möchte ich ja auch gerne anders belegen und nicht das Relais verwenden :D
Dennoch halte ich es für notwendig bzw. würde ich es toll finden, dass - falls man mit den Buttons die Relais schalten möchte - dieses auch lokal funktioniert. 
Gibt es eine Möglichkeit das ich das lokal nur für mich ändere?
Also könnte ich das z.B. in der nspanel_esphome.yaml ändern?

**Comment by danwright87** [comment]
Hi,
It looks like we may be adding an advanced mode config to allow local relay toggle either always or only when the nspanel is disconnected (users choice), I'll confirm shortly.

This is via the ESPHome yaml and that is also how you could do it in the mean time if you need it urgently.

**Comment by Blackymas** [comment]
hi jungs 

wie @danwright87 beschrieben hat, haben wir eine schöne option gefunden. Heißt wenn das nspanel nicht mit dem WLAN verbunden ist wird automatisch eine art Fallback aktiviert und die HW tasten schalten die Relais.

Wir müssen das noch testen aber @danwright87 scheint da eine gute Lösung zu haben.

ich schließe das Ticket weil wir bereits hier ein ausführliches Gespräch hatten.

Schaut da einfach vorbei und liked den Post dann sehen wir in Zukunft was die Leute sich wünschen ;)

Danke für den Request!

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/215
