### ISSUE TITLE
Automation does not trigger after update to 4.3.7

### ISSUE THREAD

**Issue by vestaxbham** [Blackymas/NSPanel_HA_Blueprint#2096]
### TFT Version

4.3.7

### ESPHome Version

4.3.7

### Blueprint Version

4.3.7

### Panel Model

EU

### What is the bug?

After update to 4.3.7 Home Assistant automation does not trigger any longer. 
In the HA log there‘s only this error message:

2024-05-01 13:08:12.889 ERROR (MainThread) [homeassistant.components.automation.nspanel_configuration] Error rendering variables: TypeError: unhashable type: 'list'

What is causing this error and how can I fix it?

Thank you!

### Home Assistant Logs

2024-05-01 13:08:12.889 ERROR (MainThread) [homeassistant.components.automation.nspanel_configuration] Error rendering variables: TypeError: unhashable type: 'list'

**Comment by edwardtfn** [comment]
Do you know from which version have you updated?
Do you mind sharing your automation yaml? Please hide any sensitive info before sharing.

**Comment by vestaxbham** [comment]
Hello,
thank you for your quick response.

Yes, I have updated from version 4.0.2 Sorry I should add this information initially.

Please find attached my automation yaml
[automation.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/15180337/automation.txt)

**Comment by edwardtfn** [comment]
Sorry for the delay this time. I'm not at home. 😩
I couldn't see anything wrong with your yaml. Just the qrcode looks different that what is expected, but I wouldn't expect that to break the system. I can try to duplicate that with my panel when I get home and let you know.
Meanwhile, can't you find anything else in your Home Assistant logs? The message you shared is quite limited info and usually an error on the Blueprint will generate a couple of entries in the logs with a bit more info.

**Comment by vestaxbham** [comment]
Hello! 

I have deleted the automation and copied the yaml code from the original one.

Now it is working again!

Thank you for help!
