### ISSUE TITLE
Can not update nspanel.tft to nspanel

### ISSUE THREAD

**Issue by wynies123** [Blackymas/NSPanel_HA_Blueprint#210]
When i try to update TFT on nspanel i get the following message:
 Reading from UART timed out at byte 0!
Reading from UART timed out at byte 0!
Reading from UART timed out at byte 0!
Reading from UART timed out at byte 0!
Reading from UART timed out at byte 0!
Reading from UART timed out at byte 0!
Reading from UART timed out at byte 0!
preparation for tft update failed 0 ""

How do i solve this?

**Comment by BHL-Rick** [comment]
Try the blank TFT first

**Comment by Blackymas** [comment]
Hi pls check all 3 pinned issues

**Comment by wynies123** [comment]
I have tried all the methods, but no luck.
then I flashed tasmota again, and uploaded nspanel_blank, then the white screen with "model does not match"
Does this TFT config work on a US portrait model (NSPanel-US)
flashing nspanel.tft via tasmota also doesn't work

**Comment by rellis-erigon** [comment]
I to get this issue,  I get the white screen and 
"Model dose not match
Device Model:
NX4832F035_011C"

Would love to use. Also found the https a real pain to try and use, ended up hosting it locally....

**Comment by Blackymas** [comment]
@rellis-erigon 

See here
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/166

**Comment by wynies123** [comment]
Does this TFT config work on a US portrait model (NSPanel-US)
![Sonoff-NSPanel-US](https://user-images.githubusercontent.com/76099751/214009162-570185e1-8638-4f9b-8f6b-e264ae6c0184.png)

**Comment by Blackymas** [comment]
think it is solved.

@wynies123 have a look here
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/130
