### ISSUE TITLE
`bug` Nextion is not connected

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#2102]
Hey Guys,
i have a Problem with my NS Panel US, i have flashed it and the Blueprint was alredy running, but not, the "ESP Home" entry is "waiting" - see the image.
The Factory reset button doesent work -- what can i do?

I can use the device in ESP Home, relays can be witchted, the display has a IP adress but in the ESP Home installation comes

"[10:35:48][W][nextion:081]: Nextion is not connected! "

i can't do anything on the Display.

Can you help me?
![IMG_20240505_102740_HDR](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/144523388/0968b0c3-e891-4800-acab-bd6b9c6602fb)

_Originally posted by @Malte1987 in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/685#issuecomment-2094686464_

**Comment by edwardtfn** [comment]
@Malte1987, which version of firmware you have installed?
Could you please share ESPHome yaml used to set your panel and some of the ESPHome logs, please?
Please remove any sensitive info before sharing.

**Comment by Malte1987** [comment]
@edwardtfn thanks for your quick response, but i don't really what i do - but now the NS Panel is running.

i started with the installation with ESPHome in the first Step with the flashing over TTI Adapter and now its okay.

Thanks.
