### ISSUE TITLE
`Enhancement` Larger Alarm Pin Pad on US Panel

### ISSUE THREAD

**Issue by PoopingNow** [Blackymas/NSPanel_HA_Blueprint#2103]
### Enhancement Summary

Make Alarm Pin Pad on US Panel Larger

### Detailed Description

When using the US panel in portrait mode, the layout and size of the alarm numeric pin pad (currently using alarmo) does not take advantage of the available display size. As a result, the digits are small to press and prone to errors, which leads to delay and triggering the alarm.

**Comment by edwardtfn** [comment]
I've improved this a bit on `dev` and would love to get some feedback after the next release.

**Comment by PoopingNow** [comment]
Will do. Looking forward to it.

**Comment by plasterer41** [comment]
Have tried dev and works superb Sent from my iPhoneOn 22 May 2024, at 08:43, Edward Firmo ***@***.***> wrote:﻿
I've improved this a bit on dev and would love to get some feedback after the next release.
