### ISSUE TITLE
When sleeping screen not turning on when notification received

### ISSUE THREAD

**Issue by karli2000** [Blackymas/NSPanel_HA_Blueprint#211]
Hi,

great piece of work!!!
I only have one problem: when the NSpanel is sleeping and i send a notification via "ESPHome: nspanel_notification_show" the notification will be shown but the screen is not turned on. When i touch the screen it stays turned off but when i touch the area where the checkmark from the notification is located (lower left area) to close the notification the screens turns on again (but the notification is gone).
All software (HA, ESphome, etc.) is at the latest version, NSPanel_HA-Blueprint is version 3.0.0.

To reproduce the bug:

- Wait until the NSpanel screen is turned off
- go to "Developer Tools" in Home Assistant
- Call the service "ESPHome: nspanel_notification_show" (when you have notification sound turned on you will hear the sound)
- Look at the display & touch the display
- Touch the display in the lower left area to to get the display turned on again

**Comment by Blackymas** [comment]
Hi - thanks i will check

**Comment by Blackymas** [comment]
recreated - we will look at it.

Thanks for the report!

**Comment by karli2000** [comment]
Hi,

i guess i found the solution for this, in the Nextion-Editor just add the line:
`dim=home.brightness.val`
to the "notification" and the "qrcode" page (which has the same problem) in the "Preinitialize Event", here a screenshot:
![image](https://user-images.githubusercontent.com/675365/218069923-32a69011-f339-4f46-ab8a-a544ee354e71.png)

This fixed the problem for me, now the screen turns on when i send a notification and the Nspanel is in sleep mode.

PS: 3.1.0 is working great, love it!

**Comment by karli2000** [comment]
Works perfect, than you!
