### ISSUE TITLE
`Bug` Alarm page buttons are not centered on the EU display

### ISSUE THREAD

**Issue by denes44** [Blackymas/NSPanel_HA_Blueprint#2110]
### TFT Version

4.3.7

### ESPHome Version

4.3.7

### Blueprint Version

4.3.7

### Panel Model

EU

### What is the bug?

The background used in this picture is the active area of the EU panel, the buttons are aligned slightly to the right:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/60078357/de19beba-5665-4d8b-ba83-b9cb24d6e0da)

**Comment by edwardtfn** [comment]
Solved in `dev` and will be part of the next release.
