### ISSUE TITLE
`Bug` Unknown services found - fan

### ISSUE THREAD

**Issue by Ulrar** [Blackymas/NSPanel_HA_Blueprint#2114]
### TFT Version

4.3.7

### ESPHome Version

4.3.7

### Blueprint Version

4.3.7

### Panel Model

EU

### What is the bug?

Hi,

I have spook running in my HA, and in the latest update this started appearing : 
```
Spook has found a ghost in your automations 👻

While floating around, Spook crossed path with the following automation:

<link to the automations using this blueprint>

This automation references the following services, which are unknown to Home Assistant:

    fan.set_percentage
    fan.oscillate
    fan.turn_on

To fix this error, [edit the automation](...) and remove the use of these non-existing services.

Spook 👻 Your homie.
```

It's not causing any issues or anything of course, I don't use any fans with my nspanel, but it comes up as a warning so wanted to raise it back here in case this needs to be addressed somehow.
Apologies if there's already an issue on this, I didn't see one.

**Comment by edwardtfn** [comment]
This is not really an error. The blueprint is prepared to call those services when your panel request it. If you don't have any fan, the services won't exists, but the panel won't call those services, so it shouldn't be an issue.

**Comment by edwardtfn** [comment]
This was solved in `dev` and will be included with the next release.
