### ISSUE TITLE
Add full climate control (aircon / heatpump) support

### ISSUE THREAD

**Issue by ghost** [Blackymas/NSPanel_HA_Blueprint#213]
Hi, amazing project! 

System modes such as 'auto heat/cool', cool, fan only, dry do not work and unable to set the setpoint

There is also vertical and horizontal vane modes and fan speeds possible on climate. not all systems support all vane types or have different fan speeds etc.

I have made a page for this in the past and the service is 'climate.set_hvac_mode' with 'hvac_mode' data set to heat_cool, heat, cool, dry, fan_only or off

Does read set point and current temp OK.
Toggle works

**Comment by Blackymas** [comment]
hey 
it took a long time but with the next version comes a completely new climate page.

You can already install the DEV version or follow this issue for it

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/848
