### ISSUE TITLE
Allow custom entity icons

### ISSUE THREAD

**Issue by danwright87** [Blackymas/NSPanel_HA_Blueprint#214]
I have a couple of input_boolean helpers for things such as guest in house or individuals in bed. rather than showing the toggle switch is it possible to override with a different icon? Preferably one for person (guest mode), another for asleep / in bed. 

I imagine people are using helpers for a variety of other  purposes and overriding icons would be helpful, just like switch as X in HA itself

Thank you

**Comment by Blackymas** [comment]
we will try to implement with the entity card that will come in the next update. 

We don't know yet if we will do this for the buttons.

But there is already an issue about it - so I close it here


https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/165
