### ISSUE TITLE
Can't import Blueprint

### ISSUE THREAD

**Issue by RoGu777** [Blackymas/NSPanel_HA_Blueprint#2157]
### TFT Version

--

### ESPHome Version

2024.5.5

### Blueprint Version

---

### Panel Model

EU

### What is the bug?

Importing of the blueprint to HomeAssistant (2024.5.2) fails with a  very long error message, see log below

### Steps to Reproduce

1 - Press on "Import Blueprint" button on the page https://github.com/Blackymas/NSPanel_HA_Blueprint
2 - enter HA address and submit
3 - error message is shown

### Home Assistant Logs

Invalid blueprint: extra keys not allowed @ data['blueprint']['input']['advanced_settings']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['advanced_settings']['icon']. Got 'mdi:cogs' extra keys not allowed @ data['blueprint']['input']['advanced_settings']['input']. Got {'icon_color_fallback_on': {'name': 'Icon fallback color when state is "**ON**"', 'description': '*General*\n*Which default color should be used for icons when the state is **ON** while a custom color is not selected and the domain does not provides a state-based color?*\n', 'default': [200, 204, 200], 'selector': {'color_rgb': None}}, 'icon_color_fallback_off': {'name': 'Icon fallback color when state is "**OFF**"', 'description': '*General*\n*Which default color should be used fo icons when... extra keys not allowed @ data['blueprint']['input']['button_page_01']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['button_page_01']['icon']. Got 'mdi:gesture-tap-button' extra keys not allowed @ data['blueprint']['input']['button_page_01']['input']. Got {'button_page01_label': {'name': 'Page title', 'description': 'Please select the label which should be displayed in the top of the page.', 'default': '', 'selector': {'text': None}}, 'entity01': {'name': 'Button page 1, Button 1 - Entity (Optional)', 'description': 'Entity which should toggle.', 'default': [], 'selector': {'entity': {'filter': {'domain': ['alarm_control_panel', 'automation', 'binary_sensor', 'button', 'climate', 'cover', 'fan', 'input_boolean', 'input_button', 'light', 'lock'... extra keys not allowed @ data['blueprint']['input']['button_page_02']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['button_page_02']['icon']. Got 'mdi:gesture-tap-button' extra keys not allowed @ data['blueprint']['input']['button_page_02']['input']. Got {'button_page02_label': {'name': 'Page title', 'description': 'Please select the label which should be displayed in the top of the page.', 'default': '', 'selector': {'text': None}}, 'entity09': {'name': 'Button page 2, Button 1 - Entity (Optional)', 'description': 'Entity to be controlled.', 'default': [], 'selector': {'entity': {'filter': {'domain': ['alarm_control_panel', 'automation', 'binary_sensor', 'button', 'climate', 'cover', 'fan', 'input_boolean', 'input_button', 'light', 'lock', '... extra keys not allowed @ data['blueprint']['input']['button_page_03']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['button_page_03']['icon']. Got 'mdi:gesture-tap-button' extra keys not allowed @ data['blueprint']['input']['button_page_03']['input']. Got {'button_page03_label': {'name': 'Page title', 'description': 'Please select the label which should be displayed in the top of the page.', 'default': '', 'selector': {'text': None}}, 'entity17': {'name': 'Button page 3, Button 1 - Entity (Optional)', 'description': 'Entity to be controlled.', 'default': [], 'selector': {'entity': {'filter': {'domain': ['alarm_control_panel', 'automation', 'binary_sensor', 'button', 'climate', 'cover', 'fan', 'input_boolean', 'input_button', 'light', 'lock', '... extra keys not allowed @ data['blueprint']['input']['button_page_04']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['button_page_04']['icon']. Got 'mdi:gesture-tap-button' extra keys not allowed @ data['blueprint']['input']['button_page_04']['input']. Got {'button_page04_label': {'name': 'Page title', 'description': 'Please select the label which should be displayed in the top of the page.', 'default': '', 'selector': {'text': None}}, 'entity25': {'name': 'Button page 4, Button 1 - Entity (Optional)', 'description': 'Entity to be controlled.', 'default': [], 'selector': {'entity': {'filter': {'domain': ['alarm_control_panel', 'automation', 'binary_sensor', 'button', 'climate', 'cover', 'fan', 'input_boolean', 'input_button', 'light', 'lock', '... extra keys not allowed @ data['blueprint']['input']['button_pages']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['button_pages']['icon']. Got 'mdi:gesture-tap-button' extra keys not allowed @ data['blueprint']['input']['button_pages']['input']. Got {'button_pages_icon_size': {'name': 'Icon size', 'description': 'Please select the size of the icons shown on the button pages.', 'default': '8', 'selector': {'select': {'multiple': False, 'options': [{'label': '24px', 'value': '7'}, {'label': '32px', 'value': '8'}, {'label': '48px', 'value': '10'}]}}}} extra keys not allowed @ data['blueprint']['input']['climate_page_settings']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['climate_page_settings']['icon']. Got 'mdi:thermostat-cog' extra keys not allowed @ data['blueprint']['input']['climate_page_settings']['input']. Got {'climate_button08': {'name': 'Climate page - Custom button 01 - Entity (Optional)', 'description': 'Entity to be controlled.', 'default': [], 'selector': {'entity': {'filter': {'domain': ['automation', 'binary_sensor', 'button', 'cover', 'fan', 'input_boolean', 'input_button', 'light', 'lock', 'person', 'remote', 'scene', 'script', 'switch']}}}}, 'climate_button08_icon': {'name': 'Climate page - Custom button 01 - Icon (Optional)', 'description': '***Icon Display:** If not specified, an attr... extra keys not allowed @ data['blueprint']['input']['climate_settings']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['climate_settings']['icon']. Got 'mdi:thermostat-cog' extra keys not allowed @ data['blueprint']['input']['climate_settings']['input']. Got {'climate': {'name': 'Main climate Entity (Optional)', 'description': "This is used to show the internal temperature in the Home page, with a link to the climate page. If a climate entity is not provided here, the internal temperature sensor will be used, without the link.\n*Refer to add-ons documentation if you want to control the climate system with your panel's relays.*\n", 'default': [], 'selector': {'entity': {'filter': {'domain': 'climate'}}}}, 'climate_chip_always_visible': {'name': 'M... extra keys not allowed @ data['blueprint']['input']['entities_page_01']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['entities_page_01']['icon']. Got 'mdi:format-list-bulleted-square' extra keys not allowed @ data['blueprint']['input']['entities_page_01']['input']. Got {'entity_page01_label': {'name': 'Page title', 'description': 'Please select the label which should be displayed in the top of the page.', 'default': '', 'selector': {'text': None}}, 'entities_entity01': {'name': 'Entity page 1, Row 1 - Entity (Optional)', 'description': 'Choose an entity to display in this position. If left blank, no entity will be shown.', 'default': [], 'selector': {'entity': None}}, 'entities_entity01_name': {'name': 'Entity page 1, Row 1 - Label (Optional)', 'description... extra keys not allowed @ data['blueprint']['input']['entities_page_02']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['entities_page_02']['icon']. Got 'mdi:format-list-bulleted-square' extra keys not allowed @ data['blueprint']['input']['entities_page_02']['input']. Got {'entity_page02_label': {'name': 'Page title', 'description': 'Please select the label which should be displayed in the top of the page.', 'default': '', 'selector': {'text': None}}, 'entities_entity09': {'name': 'Entity page 2, Row 1 - Entity (Optional)', 'description': 'Choose an entity to display in this position. If left blank, no entity will be shown.', 'default': [], 'selector': {'entity': None}}, 'entities_entity09_name': {'name': 'Entity page 2, Row 1 - Label (Optional)', 'description... extra keys not allowed @ data['blueprint']['input']['entities_page_03']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['entities_page_03']['icon']. Got 'mdi:format-list-bulleted-square' extra keys not allowed @ data['blueprint']['input']['entities_page_03']['input']. Got {'entity_page03_label': {'name': 'Page title', 'description': 'Please select the label which should be displayed in the top of the page.', 'default': '', 'selector': {'text': None}}, 'entities_entity17': {'name': 'Entity page 3, Row 1 - Entity (Optional)', 'description': 'Choose an entity to display in this position. If left blank, no entity will be shown.', 'default': [], 'selector': {'entity': None}}, 'entities_entity17_name': {'name': 'Entity page 3, Row 1 - Label (Optional)', 'description... extra keys not allowed @ data['blueprint']['input']['entities_page_04']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['entities_page_04']['icon']. Got 'mdi:format-list-bulleted-square' extra keys not allowed @ data['blueprint']['input']['entities_page_04']['input']. Got {'entity_page04_label': {'name': 'Page title', 'description': 'Please select the label which should be displayed in the top of the page.', 'default': '', 'selector': {'text': None}}, 'entities_entity25': {'name': 'Entity page 4, Row 1 - Entity (Optional)', 'description': 'Choose an entity to display in this position. If left blank, no entity will be shown.', 'default': [], 'selector': {'entity': None}}, 'entities_entity25_name': {'name': 'Entity page 4, Row 1 - Label (Optional)', 'description... extra keys not allowed @ data['blueprint']['input']['entities_pages']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['entities_pages']['icon']. Got 'mdi:format-list-bulleted-square' extra keys not allowed @ data['blueprint']['input']['entities_pages']['input']. Got {'home_button06_icon': {'name': 'Entity page - Icon (Optional)', 'description': '*HOME page*\n*Icon which should be displayed (Default mdi:format-list-bulleted-square)*\n', 'default': 'mdi:format-list-bulleted-square', 'selector': {'icon': None}}, 'home_button06_icon_color': {'name': 'Entity page - Icon color', 'description': 'Icon color which should be displayed.', 'default': [200, 204, 200], 'selector': {'color_rgb': None}}, 'entitypages_value_alignment': {'name': 'Value column alignment', ... extra keys not allowed @ data['blueprint']['input']['hardware_buttons']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['hardware_buttons']['icon']. Got 'mdi:gesture-tap-button' extra keys not allowed @ data['blueprint']['input']['hardware_buttons']['input']. Got {'hw_buttons_bars_pages': {'name': 'Hardware Buttons - Visibility Pages', 'description': 'Choose the pages where the bars, indicating the status of entities linked to hardware buttons, will be displayed.\n***Attention!** Overlapping of button bars with other components may occur on some pages. Please proceed with caution.*\n', 'default': ['2', '61440', '3932160', '65536', '131072', '512', '256', '134217728', '124', '8388608', '128', '2048', '4194304', '1024', '33554432', '67108864', '16777216... extra keys not allowed @ data['blueprint']['input']['home_page_chips']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['home_page_chips']['icon']. Got 'mdi:home' extra keys not allowed @ data['blueprint']['input']['home_page_chips']['input']. Got {'chip_font_size': {'name': "Icon's font size", 'description': 'Please select the size of the icons shown on the chips.', 'default': '7', 'selector': {'select': {'multiple': False, 'options': [{'label': '24px', 'value': '7'}, {'label': '32px', 'value': '8'}]}}}, 'chip01': {'name': 'Home page - Chip 01 - Entity (Optional)', 'description': 'Entity which should be displayed.', 'default': [], 'selector': {'entity': {'filter': {'domain': ['alarm_control_panel', 'binary_sensor', 'climate', 'cover',... extra keys not allowed @ data['blueprint']['input']['home_page_custom_buttons']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['home_page_custom_buttons']['icon']. Got 'mdi:home' extra keys not allowed @ data['blueprint']['input']['home_page_custom_buttons']['input']. Got {'custom_buttons_font_size': {'name': ' ', 'description': '# ✅ HOME PAGE - CUSTOM BUTTONS ✅\nPlease select the size of the icons shown on the custom buttons.\n', 'default': '8', 'selector': {'select': {'multiple': False, 'options': [{'label': '24px', 'value': '7'}, {'label': '32px', 'value': '8'}]}}}, 'home_custom_button01': {'name': 'Home page - Custom button 1 - Entity (Optional)', 'description': "Entity which should be controlled.\n*Entities with supported advanced settings will open it's ... extra keys not allowed @ data['blueprint']['input']['home_page_entites_states']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['home_page_entites_states']['icon']. Got 'mdi:home' extra keys not allowed @ data['blueprint']['input']['home_page_entites_states']['input']. Got {'home_value01': {'name': 'Home page - Entity State 01 - Entity (Optional)', 'description': 'Entity which should be displayed.', 'default': [], 'selector': {'entity': None}}, 'home_value01_label_color': {'name': 'Home page - Entity State 01 - Text color', 'description': "Choose a color for the sensor's display text.", 'default': [200, 204, 200], 'selector': {'color_rgb': None}}, 'home_value01_icon': {'name': 'Home page - Entity State 01 - Icon (Optional)', 'description': '***Icon Display:** I... extra keys not allowed @ data['blueprint']['input']['home_page_general_settings']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['home_page_general_settings']['icon']. Got 'mdi:home' extra keys not allowed @ data['blueprint']['input']['home_page_general_settings']['input']. Got {'relay01_icon': {'name': 'Home page - Relay 01 - Chip Icon (Optional)', 'description': 'Icon which should be displayed (Default mdi:numeric-1-box-outline).', 'default': 'mdi:numeric-1-box-outline', 'selector': {'icon': None}}, 'relay01_icon_color': {'name': 'Home page - Relay 01 - Icon color', 'description': 'Icon color which should be displayed.', 'default': [], 'selector': {'color_rgb': None}}, 'relay02_icon': {'name': 'Home page - Relay 02 - Chip Icon (Optional)', 'description': 'Icon whi... extra keys not allowed @ data['blueprint']['input']['localization']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['localization']['icon']. Got 'mdi:earth' extra keys not allowed @ data['blueprint']['input']['localization']['input']. Got {'language': {'name': 'Language', 'description': 'Select the language for your NSPanel.', 'default': 'en', 'selector': {'language': {'languages': ['en', 'bg', 'hr', 'cs', 'da', 'nl', 'et', 'fi', 'fr', 'de', 'el', 'he', 'hu', 'id', 'it', 'ja', 'ko', 'lv', 'lt', 'nb', 'pl', 'pt', 'ro', 'ru', 'sk', 'sl', 'es', 'sv', 'tr', 'uk', 'zh-tw']}}}, 'date_format': {'name': 'Date Format', 'description': 'Select the format for date to display.', 'default': '%A, %d.%m', 'selector': {'select': {'multiple': F... extra keys not allowed @ data['blueprint']['input']['media_player_settings']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['media_player_settings']['icon']. Got 'mdi:movie-cog' extra keys not allowed @ data['blueprint']['input']['media_player_settings']['input']. Got {'media_player_update_interval': {'name': 'Media player - Update interval', 'description': 'Interval (msec) to call for an update from the media player entity. Lower values will improve the responsiveness, but could spam your Home Assistant with constant requests, while higher values will reduce the load on HA but the Media Player page can be laggy.\n', 'default': 5000, 'selector': {'number': {'min': 500, 'max': 60000, 'unit_of_measurement': 'milliseconds'}}}, 'media_player_update_delay': {'n... extra keys not allowed @ data['blueprint']['input']['notifications']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['notifications']['icon']. Got 'mdi:email' extra keys not allowed @ data['blueprint']['input']['notifications']['input']. Got {'home_button04_icon': {'name': 'Home page - Notification - Icon (Optional)', 'description': 'Icon which should be displayed (Default mdi:email).', 'default': 'mdi:email', 'selector': {'icon': None}}, 'home_button04_icon_color01': {'name': 'Home page - Notification read - Icon color', 'description': 'Icon color which should be displayed.', 'default': [200, 204, 200], 'selector': {'color_rgb': None}}, 'home_button04_icon_color02': {'name': 'Home page - Notification unread - Icon color', 'descr... extra keys not allowed @ data['blueprint']['input']['qrcode_settings']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['qrcode_settings']['icon']. Got 'mdi:qrcode-scan' extra keys not allowed @ data['blueprint']['input']['qrcode_settings']['input']. Got {'qrcode_enabled': {'name': 'Enable QR code?', 'description': 'Activate QR Code page and QR Code Button on the Home page.', 'default': False, 'selector': {'boolean': None}}, 'qrcode_label': {'name': 'QR Code page - Label (Optional)', 'description': 'Label which should be displayed.', 'default': '', 'selector': {'text': None}}, 'qrcode_value': {'name': 'QR Code content - VALUE (Optional)', 'description': 'Value you want to display as QR code.', 'default': '', 'selector': {'text': None}}, 'home... extra keys not allowed @ data['blueprint']['input']['screensaver_settings']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['screensaver_settings']['icon']. Got 'mdi:sleep' extra keys not allowed @ data['blueprint']['input']['screensaver_settings']['input']. Got {'screensaver_display_time': {'name': 'Screen saver - Display time', 'description': 'Enable the display of time while sleeping (screensaver).\n\n**Important!**\n1. *Keeping the display always "on" may increase the temperature on your panel, requiring adjustments on the **Temperature correction** control to keep consistence with the environment temperature.*\n2. *Please set **Display Brightness Sleep** accordingly under the device\'s page (Settings > Devices & Services > ESPHome) to have the t... extra keys not allowed @ data['blueprint']['input']['utitilities_page']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['utitilities_page']['icon']. Got 'mdi:gauge' extra keys not allowed @ data['blueprint']['input']['utitilities_page']['input']. Got {'utilities_enabled': {'name': 'Show utilities icon on Home page', 'description': 'Activate Utilities page and Utilities button on the Home page.', 'default': False, 'selector': {'boolean': None}}, 'home_button08_icon': {'name': 'Home page - Utilities Icon (Optional)', 'description': 'Icon which should be displayed on the Home page (Default mdi:gauge).', 'default': 'mdi:gauge', 'selector': {'icon': None}}, 'home_button08_icon_color': {'name': 'Home page - Utilities Icon color', 'description':... extra keys not allowed @ data['blueprint']['input']['weather_temperature']['collapsed']. Got True extra keys not allowed @ data['blueprint']['input']['weather_temperature']['icon']. Got 'mdi:weather-partly-snowy-rainy' extra keys not allowed @ data['blueprint']['input']['weather_temperature']['input']. Got {'weather_entity': {'name': 'Weather entity from HA', 'description': 'Select your weather entity.\nThis will be used for weather information on Home page and all the weather pages.\n', 'default': [], 'selector': {'entity': {'filter': {'domain': ['weather']}}}}, 'outdoortemp': {'name': 'Home page - Outdoor Temperature Sensor (Optional)', 'description': 'If no outdoor sensor is available, leave the field empty and the value from your selected weather integration will be used automatically.', 'd...

**Comment by edwardtfn** [comment]
Home Assistant v2024.6 is required.
I don't know why you aren't receiving the invalid version message instead.

**Comment by RoGu777** [comment]
thanks, after updating HA import was successful!
