### ISSUE TITLE
Custom 'chips' along top bar

### ISSUE THREAD

**Issue by ghost** [Blackymas/NSPanel_HA_Blueprint#216]
As with Heating and water heater along top bar, please could we have the option to add a couple of custom items? On my current nspanel design I have solar PV watts and home battery charge / discharge status, other people may have other data they may want always on display in a similar fashion so better to not limit to that exact purpose but maybe similar to the top menu 04

**Comment by Blackymas** [comment]
hi -  


at the moment we are working on the Entity Card and this could possibly fit in well.

We will see if it is feasible and how fast it can be done.

**Comment by atamgp** [comment]
**Entity Card** has been added in newest release right?

What kind of entity have you exposed here in your example to list all attributes?
https://user-images.githubusercontent.com/41958506/215906572-a447a81b-179b-4c49-b4e5-9b0b2f594c16.png

In my view it's now whowing it's attributes...

**Comment by Blackymas** [comment]
Is changed in v3.2 
Please update and test :)

https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.2
