### ISSUE TITLE
HMI light settings page goes home even when in use

### ISSUE THREAD

**Issue by ghost** [Blackymas/NSPanel_HA_Blueprint#217]
Hi,
I can add traces / versions etc. but believe this is a simple HMI issue. 

When playing with the light brightness, temperature & colour you get taken back to home page after a while even though you are actively tapping the screen, looks like the timeout needs to be reset on each touch. 

latest HMI file

**Comment by Blackymas** [comment]
Hi,

i will Check

**Comment by Blackymas** [comment]
is solved in Version 3.1.0
