### ISSUE TITLE
Unable to import blueprint yaml`Bug` 

### ISSUE THREAD

**Issue by skippengs** [Blackymas/NSPanel_HA_Blueprint#2171]
### Panel Model

EU

### What is the bug?

When trying to import the configuration blueprint u get a lot of errors. See the screenshot attached.
![Screenshot_20240623_142909_Home Assistant](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7521903/26a1eda8-6662-4173-ae55-5b8190ee8a87)

### Steps to Reproduce

1. Go to homepage of this GitHub project.
2. Click in the blue import to home assistant button to start the process.
3. Click preview
4. A list of errors wil be displayed.

**Comment by edwardtfn** [comment]
Which version of Home Assistant are you running?
This requires Home Assistant v2024.6 or later.

**Comment by skippengs** [comment]
Updating home assistant fixed the importing issue.
