### ISSUE TITLE
`Translation` German translation for "disarm"

### ISSUE THREAD

**Issue by Kaibob2** [Blackymas/NSPanel_HA_Blueprint#2184]
### Enhancement Summary

The word "entwaffnen" is a poor choice :)

### Detailed Description

This is only a little request as the word "entwaffnen" in german means to take a weapon from somebody. Disarm means in fact the same in english, but as far as I know it's widely used in an alarm system context. The alarm armed <-> disarmed wording would be in german Alarmanlage scharf <-> unscharf. But translating that in english makes even less sense (hot <-> mild).
I would suggest changing "Entwaffnen" to "Aus", as "Deaktiviert" has one character too much. 

Btw. great work, and I'm happy I found this project. It comes in handy as I'm currently modernizing a complete house and this project is perfect for my automation plans :)

**Comment by Kaibob2** [comment]
Maybe "Inaktiv" would also be an option...

**Comment by Kaibob2** [comment]
Tricky. Aus can be used for the state (Like on/off) or the process. Aus(schalten) - > switch off

Inaktiv is only the state.
I suppose Aus is the better choice for now.

**Comment by edwardtfn** [comment]
Fixed in `dev`

**Comment by bkbartk** [comment]
I see Dutch has the same grammatical error to it
`disarm: Ontwapenen`
I would suggest to use `Uitschakelen` (turn off) here

**Comment by Kaibob2** [comment]
Just like "deaktiviert", "Uitschakelen" is too long to be displayed. If there is no shorter Version for that I would also suggest "Uit" or, if I correct, the dutch word for "Aus" :)

**Comment by bkbartk** [comment]
yes, "Uit" is the Dutch word for "Aus" / "Off" 
but it's more like an existing state instead of an action.
however HA also says "Uitgeschakeld" (turned off) instead of the actual action.

So I think "Uit" would be best

**Comment by Kaibob2** [comment]
It's the same in german like I explained above. But I suppose everyone will get the meaning ;)

**Comment by edwardtfn** [comment]
Should I change Dutch also?

**Comment by bkbartk** [comment]
> Should I change Dutch also?

Yet please, to "Uit"

"Ontwapenen",  is more like taking away guns and other weapons.
Probably this issue exists for more languages

**Comment by Kaibob2** [comment]
Without me beeing dutch myself I would also suggest to change it to "Uit". German and dutch aren't that far apart and it would correlate to the change to "Aus" for german.
