### ISSUE TITLE
The link from the home page to climate page with embedded thermostat doesn't work without blueprint

### ISSUE THREAD

**Issue by lookasek** [Blackymas/NSPanel_HA_Blueprint#2190]
### TFT Version

4.3.9

### ESPHome Version

4.3.9

### Blueprint Version

4.3.9

### Panel Model

EU

### What is the bug?

In blueprint, the embedded thermostat is set as the main climate entity.

When NSPanel has no communication with blueprint (HA disabled or WiFi disabled), the home page displays the internal temperature, but after pressing it, I cannot go to the climate page.

**Comment by edwardtfn** [comment]
Fixed in `dev`
