### ISSUE TITLE
New feature request: Add a 2nd climate control

### ISSUE THREAD

**Issue by geozogaris** [Blackymas/NSPanel_HA_Blueprint#220]
Thank you for all the hard work put into this project which makes the NSPanel really useful.

In our house we have two heating zones (one to control the temperature Upstairs and one for Downstairs).
With the current configuration of the blueprint we can only control 1 heating entity.
Is there a way to add a 2nd thermostat page in order to control the 2nd heating zone of the house?

Thanks in advance for your reply.

**Comment by Blackymas** [comment]
hi - thanks for the request.

We already have a ticket for this and will look at it.

You are welcome to follow and like this request. Since it's a duplicate request, I'm closing this one.


https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/78
