### ISSUE TITLE
`Bug` Excessive hard drive usage

### ISSUE THREAD

**Issue by illuzn** [Blackymas/NSPanel_HA_Blueprint#2205]
### TFT Version

4.3.9

### ESPHome Version

4.3.9

### Blueprint Version

4.3.9

### Panel Model

US

### What is the bug?

The `/esphome/.esphome/external_components` folder grows very large in size.

This is attributable to the following:
https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/969ff5839fc5f9617dc243631f74f884dbf8460d/esphome/nspanel_esphome_core.yaml#L36-L46

This causes esphome to pull the entire repository every time there is a new release (especially the HMI files which are quite large). It appears that the only needed files are in the `/components` folder of this repository - if only those files were downloaded this would not be an issue (they are less than 1MB).

It's not an issue with one pull, however, if you update with the repo and have 10 versions on your computer it adds up.

Seperately, around 22 May 2024 and 19 June 2024, there may have been a separate configuration issue in the repo which resulted in a 1GB pull for the entire repository (normally this is in the order of 100-200MB).

### Steps to Reproduce

1. Using esphome build the blueprint.
2. It will pull a copy of the entire repo to that external_components folder.

### Your Panel's YAML

```yaml
Not Applicable
```

### ESPHome Logs

Not Applicable

### Home Assistant Logs

Not Applicable

**Comment by edwardtfn** [comment]
This should probably be solved from ESPHome side, so I would suggest you report this issue in their repository ([esphome/issues](https://github.com/esphome/issues/issues)) if you don't mind.
