### ISSUE TITLE
Installations error

### ISSUE THREAD

**Issue by zorrosweden** [Blackymas/NSPanel_HA_Blueprint#221]
I can't get it to work have installed everything as per the instructions
but nspanel only shows this image
i can check the relays in nspanel from HA
I also get the following error in HA
**""nspanel living room uses an unknown service
The automation " nspanellivingroom " (automation.nspanellivingroom) has an action that calls an unknown service: esphome.nspanellivingroom_send_command_printf.
This error prevents the automation from working properly. Maybe this service is no longer available, or maybe a typo caused it.
To fix this error, edit the automat
ion and remove the action that calls this service.
Click Submit below to confirm that you have addressed this automation""**
![nspanel1](https://user-images.githubusercontent.com/65852184/213918003-80630b8d-d78f-43a8-80b1-e976d0d6535f.jpg)

**Comment by zorrosweden** [comment]
![nspanel3](https://user-images.githubusercontent.com/65852184/213918277-81a86a61-403f-4d87-9f9f-5d574d70aefc.jpg)

**Comment by Smart-Techno1ogy** [comment]
Hi - thanks for this. How do you go about editing the automation?

**Comment by Blackymas** [comment]
Hi,

Either Blueprint is not configured properly (without Blueprint it will not go on).

Or you use the wrong name in the Blueprint. Please do not use special characters or -. 
Because - will be converted to _ by HA.

See here:
https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-First-Steps---Installation-and-Setup

**Comment by zorrosweden** [comment]
Blueprint config
id: '1674380317721'
alias: nspanelvardagsrum
description: ''
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    language: SWE
    sync_value_ha: select_yes
    sync_slider_ha: select_yes
    nspanel_name: nspanelvardagsrum
    weather_entity: weather.smhi_hallstavik

**Comment by Blackymas** [comment]
can you share a screen about the config of ESPhome and Blueprint.

Please also a quick look in here
https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#1-how-do-I-create-issues-when-I-have-a-problem

**Comment by zorrosweden** [comment]
Blueprint config
id: '1674380317721'
alias: nspanelvardagsrum
description: ''
use_blueprint:
path: Blackymas/nspanel_blueprint.yaml
input:
language: SWE
sync_value_ha: select_yes
sync_slider_ha: select_yes
nspanel_name: nspanelvardagsrum
weather_entity: weather.smhi_hallstavik

![nspanel4](https://user-images.githubusercontent.com/65852184/213923796-f70d0427-220a-4fa3-8399-676e52b4cf98.jpg)

**Comment by Blackymas** [comment]
You do not use the same names. correctly it should look like this

ESPhome:
device_name: "ns1vardagsrum"

Blueprint:
nspanel_name: ns1vardagsrum


See here
![Bildschirmfoto 2023-01-22 um 16 41 38](https://user-images.githubusercontent.com/41958506/213924794-82af0b67-4216-41e8-b8b3-704f60f42e33.png)


![Bildschirmfoto 2023-01-22 um 16 38 27](https://user-images.githubusercontent.com/41958506/213924760-8caec8f7-2dd9-490a-8d13-da58f31d9963.png)

**Comment by zorrosweden** [comment]
I had entered the wrong picture, so this is what the config looks like
![nspanel5](https://user-images.githubusercontent.com/65852184/213925118-0335c871-a517-45e7-b48f-414295927425.jpg)

**Comment by Blackymas** [comment]
Then we need a screen of the first row and where the orange line stops - otherwise we can't say anything.

Here in the link is a picture which row we need


https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#1-how-do-I-create-issues-when-I-have-a-problem

**Comment by Smart-Techno1ogy** [comment]
many thanks for the support @Blackymas I am now past my problems and have 3 working lightswitches. My main issue appears to have been my naming config and whilst re-naming & flashing the devices I hadn't completely removed them from the ESP integration. Once I cleared everything, deleted the integration and started afresh with the correct naming convention everything works as expected. Thank you for the hard work on this.

**Comment by zorrosweden** [comment]
Now it works
i reinstalled blueprint flash nspanel.tft locally from HA.
when i did according to the manual and in the last step update tft from nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft" then that update took 23 hours and resulted in crc error, local flash took 5 min thanks for all the help

**Comment by Blackymas** [comment]
> many thanks for the support @Blackymas I am now past my problems and have 3 working lightswitches. My main issue appears to have been my naming config and whilst re-naming & flashing the devices I hadn't completely removed them from the ESP integration. Once I cleared everything, deleted the integration and started afresh with the correct naming convention everything works as expected. Thank you for the hard work on this.

glad to hear that it works - have fun with my NSPanel version ;)

**Comment by Blackymas** [comment]
> Now it works
> i reinstalled blueprint flash nspanel.tft locally from HA.
> when i did according to the manual and in the last step update tft from nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft" then that update took 23 hours and resulted in crc error, local flash took 5 min thanks for all the help

Hi;

The problem is your internet or wifi.

Https is a bit slower in donwload anyway normally it takes 5-10 minutes.

But since Esphome loads everything in small packets, your network / internet seems to have a problem.

I have 7 NSpanel and in 5-10 min everything is ready.

The topic was also discussed here.

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/212

**Comment by zorrosweden** [comment]
No
I don't think my wifi is the problem has 500/500 mbit wifi speed

**Comment by Blackymas** [comment]
This has nothing to do with the latencies and then also the router and the WLAN. Everything together causes the problem.

I have 7 NSPanel at home but also a business connection and Bussines Network / Wifi equipment.

Also, many other users have no problem. But there are always people who have the problem and it must therefore be a local component.

That was also the reason why we have built the service for local upload.

Translated with www.DeepL.com/Translator (free version)


A community user has also described this well:


---------------------------
The upload of TFT via ESP Home is slow in general as its over serial and is downloaded in small chunks, with the additional latency of doing that over the internet the the delays become substantial. Outside of this project ive had tft upload from a remote source take 5+ hours down to maybe 10 minutes from a local web server, this is not a issue with with project but a ESP Home trait. Using local source as recommended is the best action if you are struggling with how long upload takes.

Tasmota does seem to handle it much better and has been able to rescue bricked nextion displays for me that ESP Home wouldn't connect to.

**Comment by zorrosweden** [comment]
When it is possible to flash locally, there is no problem I changed the path in esphome from nextion_update_url: **"https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft"** to **nextion_update_url: "https://192.168. 100.30/local/nspanel.tft"** and it worked perfectly

**Comment by Blackymas** [comment]
This was our goal to be able to help all those who have problems.

We are certainly not perfect and if someone should find a better solution we are open to check it.

But currently it is not the code and for the other factors we can only offer help via the local upload.

But I'm glad that it now runs with you so I would then also close the ticket.
