### ISSUE TITLE
Migration from "nspanel-lovelace-ui" by joBr99 problems

### ISSUE THREAD

**Issue by pawellygan** [Blackymas/NSPanel_HA_Blueprint#223]
Hi!

I have "nspanel-lovelace-ui" by joBr99 installed and running just fine. 

From what I have read my steps should be:

0. Generate ESP File in HA (done)
1. download the file "nspanel_blank.tft" from the folder custom_configuration.
**DONE**

2. now upload the TFT file "nspanel_blank.tft" to the folder "www" in Home Assistant
now go to the item "Developer tools --> Services" and search there for the services  
"ESPHome: DEVICE_NAME_upload_tft" --> (esphome.device_name_upload_tft)

**Here is the first problem as the service name should be ESPHome: ns_panel_upload_tft_url instead of mentioned esphome.device_name_upload_tft - only esphome.device_name_upload_tft_url has optyion to provide url** 
**But ok it is done** 

3. under URL you have to enter the path to your file nspanel_blank.tft. This could look like this "http://IP_HOME_ASSISTANT:8123/local/nspanel_blank.tft"

Done

4. now the TFT file should be played on the NSPanel. It may take a moment until it is ready
If everything worked, you should see only a white page on the NSPanel.

And here nothing happens. Got a spinning wheel Waiting for content.

Can't progress as this step is not done. I can add the device under ESP Home integration and I can see it in the system - but the screen itself is not working. Got only a spinning message.
Maybe it will be possible to provide a full guide for "Migration from nspanel-lovelace-ui by joBr99" as the one provided atm is not clear at all. Thanks!

**Comment by zorrosweden** [comment]
You probably have to flash nspanel_blank.tft with Tasmota so that's what I had to do when I had the same problem as you

**Comment by pawellygan** [comment]
> You probably have to flash nspanel_blank.tft with Tasmota so that's what I had to do when I had the same problem as you

from File System console? 

<img width="634" alt="Screenshot 2023-01-22 at 17 56 40" src="https://user-images.githubusercontent.com/45388740/213931912-186d25e1-dc58-4fa6-948f-de5527934844.png">

**Comment by pawellygan** [comment]
ok so did my TFT flash first from tasmota  - OK
flashed with ESp home and trying to flash with tft file and this ends with errors



Time | level | Tag | Message
-- | -- | -- | --
18:30:56 | [D] | [nextion_upload:209] | Updating Nextion NX4832F035_011C...
18:30:56 | [D] | [nextion_upload:235] | Waiting for upgrade response
18:30:56 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:57 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:57 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:57 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:57 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:57 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:57 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:57 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:58 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:58 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:58 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:58 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:58 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:58 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:58 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:58 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:58 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:58 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:58 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:58 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:30:58 | [D] | [nextion_upload:239] | Upgrade response is  20
18:30:58 | [D] | [nextion_upload:242] | Available 0 : 0x00
18:30:58 | [D] | [nextion_upload:242] | Available 1 : 0x00
18:30:58 | [D] | [nextion_upload:242] | Available 2 : 0x00
18:30:58 | [D] | [nextion_upload:242] | Available 3 : 0x00
18:30:58 | [D] | [nextion_upload:242] | Available 3 : 0x00
18:30:58 | [D] | [nextion_upload:242] | Available 4 : 0x00
18:30:58 | [D] | [nextion_upload:242] | Available 5 : 0x00
18:30:58 | [D] | [nextion_upload:242] | Available 6 : 0x00
18:30:58 | [D] | [nextion_upload:242] | Available 6 : 0x00
18:30:58 | [D] | [nextion_upload:242] | Available 7 : 0x00
18:30:58 | [D] | [nextion_upload:242] | Available 8 : 0x00
18:30:58 | [D] | [nextion_upload:242] | Available 9 : 0x00
18:30:58 | [D] | [nextion_upload:242] | Available 10 : 0x00
18:30:58 | [D] | [nextion_upload:242] | Available 11 : 0x00
18:30:58 | [D] | [nextion_upload:242] | Available 11 : 0x00
18:30:58 | [D] | [nextion_upload:242] | Available 12 : 0x00
18:30:58 | [D] | [nextion_upload:242] | Available 13 : 0x00
18:30:59 | [D] | [nextion_upload:242] | Available 14 : 0x00
18:30:59 | [D] | [nextion_upload:242] | Available 15 : 0x00
18:30:59 | [D] | [nextion_upload:242] | Available 16 : 0x00
18:30:59 | [D] | [nextion_upload:242] | Available 17 : 0x00
18:30:59 | [D] | [nextion_upload:242] | Available 18 : 0x00
18:30:59 | [D] | [nextion_upload:242] | Available 19 : 0x00
18:30:59 | [D] | [nextion_upload:248] | preparation for tft update failed 0 ""
18:30:59 | [D] | [nextion_upload:248] | preparation for tft update failed 0 ""
18:30:59 | [D] | [nextion_upload:324] | Restarting Nextion
18:31:00 | [D] | [nextion_upload:327] | Restarting esphome

**Comment by pawellygan** [comment]
18:54:11 | [D] | [nextion_upload:175] | Requesting URL: https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft
-- | -- | -- | --
18:54:12 | [D] | [nextion_upload:209] | Updating Nextion NX4832F035_011C...
18:54:12 | [D] | [nextion_upload:235] | Waiting for upgrade response
18:54:12 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:13 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:13 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:13 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:13 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:13 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:13 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:13 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:13 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:13 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:13 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:14 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:14 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:14 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:14 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:14 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:14 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:14 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:14 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:14 | [E] | [uart:015] | Reading from UART timed out at byte 0!
18:54:14 | [D] | [nextion_upload:239] | Upgrade response is  20
18:54:14 | [D] | [nextion_upload:242] | Available 0 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 1 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 2 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 3 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 4 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 5 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 6 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 7 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 8 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 9 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 10 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 11 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 12 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 13 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 14 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 15 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 16 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 17 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 18 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 18 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 19 : 0x00
18:54:15 | [D] | [nextion_upload:242] | Available 19 : 0x00
18:54:15 | [D] | [nextion_upload:248] | preparation for tft update failed 0 ""
18:54:15 | [D] | [nextion_upload:248] | preparation for tft update failed 0 ""
18:54:15 | [D] | [nextion_upload:324] | Restarting Nextion
18:54:15 | [D] | [nextion_upload:324] | Restarting Nextion

**Comment by Blackymas** [comment]
If I understood your text correctly, you did it in the bottle order.

When lovelace Ui is completely installed the nspanel_blank must be uploaded with the Lovelace update tft function.

Only when this step is done you can flash the Esphome version from me and then my nspanel.tft.

How this works with the tasmota I don't know - but look in the issues there was this topic already there

**Comment by pawellygan** [comment]
> If I understood your text correctly, you did it in the bottle order.
> 
> When lovelace Ui is completely installed the nspanel_blank must be uploaded with the Lovelace update tft function.
> 
> Only when this step is done you can flash the Esphome version from me and then my nspanel.tft.
> 
> How this works with the tasmota I don't know - but look in the issues there was this topic already there

I believe it was done.  I did the step with flashing  nspanel_blank  with the command( Inside tasmota):
`FlashNextion http://local.link.to/nspanel_blank.tft`

and it was successful. Is there any other step between this and flashing with ESPHome bin file?

**Comment by Blackymas** [comment]
nope - when you have a white page at the nspanel you can start to flash the nspanel witch es-home

**Comment by pawellygan** [comment]
> nope - when you have a white page at the nspanel you can start to flash the nspanel witch es-home

Should it be 100% white? Mine is white with an error in top left corner "model does not match"
My panel is EU version (purchased from Amazon)

**Comment by Blackymas** [comment]
white without any error

i thin you have this issue
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/166

follow the steps in this topic

**Comment by pawellygan** [comment]
I did one last try and finally got a white screen - tft update is going VERY slow - like 12h now but no rush ;) it is not fr4ozen so there is a chance it will go through at some point
<img width="519" alt="Screenshot 2023-01-24 at 10 07 37" src="https://user-images.githubusercontent.com/45388740/214264196-ad3371cb-2cc9-43e2-b1eb-dcf130900d4f.png">

**Comment by Blackymas** [comment]
we have also adapted the wiki on the topic of local upload via home assistant.

Otherwise please have a look at this if it does not work

**Comment by pawellygan** [comment]
I left home for now - if it won't be ready in next 7h I will give it a go and report back

**Comment by zorrosweden** [comment]
> I did one last try and finally got a white screen - tft update is going VERY slow - like 12h now but no rush ;) it is not fr4ozen so there is a chance it will go through at some point <img alt="Screenshot 2023-01-24 at 10 07 37" width="519" src="https://user-images.githubusercontent.com/45388740/214264196-ad3371cb-2cc9-43e2-b1eb-dcf130900d4f.png">

it won't work, you probably have to flash locally according to the wiki
I made several attempts in the same way as you and waited for 24 hours until I flashed locally took 5 min and worked immediately
"http://IP_HOME_ASSISTANT:8123/local/nspanel_blank.tft"

**Comment by pawellygan** [comment]
huh, done!
1) locally uploaed blank from tasmota
2) white screen correct
3)  firmware upgrade throught tasmota (generated as legacy ESP Home)
4)  blank again as a HA service (local file)
5) ESP Home update via ESP Home (dropping legacy  mode) 
6) tft update (locally) 

WIN!
Thank you guys
