### ISSUE TITLE
`Bug` RTTTL Beat greater than 255 results in starting at 0 again

### ISSUE THREAD

**Issue by ScottVega** [Blackymas/NSPanel_HA_Blueprint#2232]
### TFT Version

4.3.9

### Firmware Version

4.3.9

### Blueprint Version

4.3.11

### Panel Model

EU

### What is the bug?

When using the rtttl_play function and the RTTTL-Tone has a beat greater than 255 it starts at 0 beats again.
Example:
Cantina Band:d=4,o=5,b=255:a,d6,a,d6,8 etc. plays just fine
but 
Cantina Band:d=4,o=5,b=260:a,d6,a,d6,8 etc.. plays at 10bpm

as the song in the example used has 260bpm it has to be played at  slower speed (255 max) or it will be way too slow.

Here is the full RTTTL I used 

Cantina Band:d=4,o=5,b=260:a,d6,a,d6,8a,d6,8a,8p,8g#,a,8a,8g#,8a,8g,8p,8f#,8g,8f#,f.,8d,2p,a,d6,a,d6,8a,d6,8a,8p,8g#,a,8g,8p,g,8p,8f#,g,8c6,a#,a,g.,a,d6,a,d6,8a,d6,8a,8p,8g#,a,8c6,8p,c6,8p,8a,g,f.,8d,2p,2d,2f,2a,2c6,d#6,d6,8g#,a,8f,1p,a6,8f6,8a6,2p,a6,8f6,8a6,2p,a6,8f6,8g#6,a6,8f6,p.,8d6,2p,a6,8f6,8a6,2p,a6,8f6,8a6,2p,a6,8f6,8g#6,a6,8g6,2p,2c6,8p,a6,8f6,8a6,2p,a6,8f6,8a6,2p,a6,8f6,8g#6,a6,8f6,p.,8d6,2p,8a#,8d6,f6,8b,8d6,f6,8g#6,a6,8d6,2p,8d,8f,8a#,8d6,8g#,a,8f,1p,a,d6,a,d6,8a,d6,8a,8p,8g#,a,8a,8g#,8a,8g,8p,8f#,8g,8f#,f.,8d,2p,a,d6,a,d6,8a,d6,8a,8p,8g#,a,8g,8p,g,8p,8f#,g,8c6,a#,a,g.,a,d6,a,d6,8a,d6,8a,8p,8g#,a,8c6,8p,c6,8p,8a,g,f.,8d,2p,2d,2f,2a,2c6,d#6,d6,8g#,a,8f,1p

**Comment by edwardtfn** [comment]
This is probably a limitation from ESPHome so I would suggest you report this issue in their repository ([esphome/issues](https://github.com/esphome/issues/issues)) if you don't mind.
