### ISSUE TITLE
Document how to open settings page

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#2234]
Wi-Fi got stuck on my panel, and I'd like to reboot it (yes, I can do it by switching off the mains, but that power cycles other things as well what I'd like to avoid). There appears to be that option in the UI:

![Settings EU](https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/docs/pics/eu_settings.png)

But how do I open this page on the panel? It would be useful to mention that at https://github.com/Blackymas/NSPanel_HA_Blueprint?tab=readme-ov-file#display-settings

_Originally posted by @nijel in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/2233_

**Comment by DM2NT** [comment]
You don't like the reset button on the bottom?

**Comment by nijel** [comment]
I forgot about that one. But still, documenting how to get to the settings page is useful.

**Comment by edwardtfn** [comment]
Yeah, this page requires a reorg of things... I wanna have a link to the boot page where some logs are shown and maybe that should be better than a reboot here (as you can reboot from that other page).
Anyhow, I will fix the documentation for now.
I will be happy if we have another entry to discuss about how that page should be. 😉
