### ISSUE TITLE
`Bug` Can not update TFT EU with 4.3.11

### ISSUE THREAD

**Issue by DAVIZINH0** [Blackymas/NSPanel_HA_Blueprint#2235]
### TFT Version

unknown

### Firmware Version

4.3.11

### Blueprint Version

4.3.11

### Panel Model

EU

### What is the bug?

I updated today the esphome and the blueprint to 4.3.11 and all is ok.
But apears a message that i need to update the TFT.
ok. i push the update button, and nothing happends. I can see that the tft updating, but after this in home assistant the version of tft is "unknown"

This is the capture of the message:
![image](https://github.com/user-attachments/assets/372fb806-d7dd-4e2c-8aeb-5c45703b15e2)

And this is the versions of home assistant:
![image](https://github.com/user-attachments/assets/6ef1255e-c4e3-441b-9574-156e12f1a733)

I think this is related with other isue but its closed and maybe its a diferent issue.
thanks!!

**Comment by edwardtfn** [comment]
Could you please share the logs from ESPHome when you press the Upload button?

**Comment by DAVIZINH0** [comment]
> Could you please share the logs from ESPHome when you press the Upload button?

of course!! i attach it
[logs_p0-salon-porche-tecla_logs.txt](https://github.com/user-attachments/files/16698532/logs_p0-salon-porche-tecla_logs.txt)

thanks!!!

**Comment by edwardtfn** [comment]
Do you have any firewall or other restriction preventing your panel to get direct access to the Internet? Or to the dns server?

```log
[22:33:23][D][esp-idf:000]: E (21515947) esp-tls: couldn't get hostname for :raw.githubusercontent.com: getaddrinfo() returns 202, addrinfo=0x0

[22:33:23][D][esp-idf:000]: E (21515950) esp-tls: Failed to open new connection

[22:33:23][D][esp-idf:000]: E (21515953) TRANSPORT_BASE: Failed to open a new connection

[22:33:23][D][esp-idf:000]: E (21515956) HTTP_CLIENT: Connection failed, sock < 0

[22:33:23][E][nextion.upload.idf:220]: HTTP request failed: ESP_ERR_HTTP_CONNECT
[22:33:23][D][nextion.upload.idf:342]: Nextion TFT upload finished: NO
[22:33:23][E][nextion.upload.idf:358]: Nextion TFT upload failed
```

**Comment by DAVIZINH0** [comment]
> Do you have any firewall or other restriction preventing your panel to get direct access to the Internet? Or to the dns server?
> 
> ```
> [22:33:23][D][esp-idf:000]: E (21515947) esp-tls: couldn't get hostname for :raw.githubusercontent.com: getaddrinfo() returns 202, addrinfo=0x0
> 
> [22:33:23][D][esp-idf:000]: E (21515950) esp-tls: Failed to open new connection
> 
> [22:33:23][D][esp-idf:000]: E (21515953) TRANSPORT_BASE: Failed to open a new connection
> 
> [22:33:23][D][esp-idf:000]: E (21515956) HTTP_CLIENT: Connection failed, sock < 0
> 
> [22:33:23][E][nextion.upload.idf:220]: HTTP request failed: ESP_ERR_HTTP_CONNECT
> [22:33:23][D][nextion.upload.idf:342]: Nextion TFT upload finished: NO
> [22:33:23][E][nextion.upload.idf:358]: Nextion TFT upload failed
> ```

NO.
my nspanel conects to the main 2.4ghz wifi of my house. and now im conected to this wifi for replying this message.
Can i make other test? or can i update manually with other url?

**Comment by edwardtfn** [comment]
You can set the `nextion_update_url` substitution in your panel's yaml and then before clicking Upload TFT you select this option in Upload TFT Model drop down.
If you need help with this, please share your panel's yaml, removing any sensitive info before sharing.

**Comment by DAVIZINH0** [comment]
> You can set the `nextion_update_url` substitution in your panel's yaml and then before clicking Upload TFT you select this option in Upload TFT Model drop down. If you need help with this, please share your panel's yaml, removing any sensitive info before sharing.

OK thanks a lot
this confirm that its a strange problem in my side.
I updated by manual method with a local file, and works fine!!!
now the tft its in 4.3.11

thanks a lot again
