### ISSUE TITLE
Change the CLIMATE_MODE_AUTO icon in nspanel_esphome_core.yaml

### ISSUE THREAD

**Issue by rehakf** [Blackymas/NSPanel_HA_Blueprint#2243]
### Enhancement Summary

Change the CLIMATE_MODE_AUTO icon in nspanel_esphome_core.yaml

### Detailed Description

NSpanel in the "Climate page" displays for CLIMATE_MODE_AUTO icon “mdi:calendar-sync” but it should display icon “mdi:thermostat-auto” instead.

`3392                     case 6: //CLIMATE_MODE_AUTO`
`3393                      disp1->set_component_text(component.c_str(), "\uEE8D"); // mdi:calendar-sync`
`3394                      disp1->set_component_font_color(component.c_str(), 35921); // grey (off)`

**Comment by edwardtfn** [comment]
Unfortunately the icon font available for Nextion doesn't includes the `thermostat-auto` icon.
Those are the icons available: https://htmlpreview.github.io/?https://github.com/jobr99/Generate-HASP-Fonts/blob/master/cheatsheet.html

Please let me know if you find some that fits better from that list.

**Comment by rehakf** [comment]
> Please let me know if you find some that fits better from that list.

**I think best suitable icon can be: \uF8F1 mdi:refresh-auto**  

(other suitable icons could be \uEBEB alpha-a-circle  or  \uEBEC alpha-a-circle-outline)

Please change the CLIMATE_MODE_AUTO icon in nspanel_esphome_core.yaml
`3392                     case 6: //CLIMATE_MODE_AUTO`
`3393                      disp1->set_component_text(component.c_str(), "\uEE8D"); // mdi:calendar-sync`
`3394                      disp1->set_component_font_color(component.c_str(), 35921); // grey (off)`

**Comment by edwardtfn** [comment]
I've implemented this in `dev` and will be part of the next release.
