### ISSUE TITLE
`Bug` TFT update failed

### ISSUE THREAD

**Issue by LenoDuan** [Blackymas/NSPanel_HA_Blueprint#2245]
### TFT Version

unknow

### Firmware Version

4.3.1

### Blueprint Version

4.3.1

### Panel Model

EU

### What is the bug?

my panel works ewelink UI,it's failed during upgrade,the screen because blue and display"system data error"

[home-assistant_esphome_2024-08-27T12-21-42.919Z.log](https://github.com/user-attachments/files/16761997/home-assistant_esphome_2024-08-27T12-21-42.919Z.log)
![logbook](https://github.com/user-attachments/assets/66ace9c1-1b89-402b-9ba9-454e54f8a8e3)
[
![diagnostic](https://github.com/user-attachments/assets/92daa23d-411e-4be7-aec0-fefc1ee97757)
](url)

**Comment by edwardtfn** [comment]
Could you please share the logs of ESPHome from the moment you press the upload TFT button to the moment your panel restarts (or even a few seconds after that)?

**Comment by LenoDuan** [comment]
I have attached log in original description



---Original---
From: "Edward ***@***.***&gt;
Date: Tue, Aug 27, 2024 21:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Blackymas/NSPanel_HA_Blueprint] `Bug` TFT update failed (Issue#2245)




 
Could you please share the logs of ESPHome from the moment you press the upload TFT button to the moment your panel restarts (or even a few seconds after that)?

**Comment by edwardtfn** [comment]
That log is from Home Assistant. The one I'm asking for is from ESPHome, as we will be able to see what the device itself is trying to do.
You can collect this thru ESPHome Dashboard, clicking the "Log" button related to your panel.

**Comment by LenoDuan** [comment]
> That log is from Home Assistant. The one I'm asking for is from ESPHome, as we will be able to see what the device itself is trying to do. You can collect this thru ESPHome Dashboard, clicking the "Log" button related to your panel.

It's working properly after I re-flash again,thanks,
btw,may i ask where can I enable the power monitor like this page(https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/pics/eu_entities.png),and how can I add cooler in climate,it seems only heater?

**Comment by edwardtfn** [comment]
> btw,may i ask where can I enable the power monitor like this page (https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/pics/eu_entities.png),

I've used the entities pages with template sensors for each of those values.

![image](https://github.com/user-attachments/assets/56a129a6-0a5e-47ff-8ece-cd4e66b38dfd)

**Comment by edwardtfn** [comment]
> and how can I add cooler in climate, it seems only heater?

Do you mean the Climate add-on (controlled by your panel's relays)? Just replace the "heat" add-on to "cool" or "dual".

Maybe sharing your YAML will help us helping you. 😉
