### ISSUE TITLE
font size clock

### ISSUE THREAD

**Issue by bkbartk** [Blackymas/NSPanel_HA_Blueprint#226]
Hellog,

Is it possible to adjust the font-size of the clock a little bit?
I would like to have it larger, but now by much and can't find a setting for it.
Is there a way to do this or is this one as is?

**Comment by danwright87** [comment]
Hi,
This isn't something that can be easily adjusted as it's hard coded in the screen design and positions of everything would also have to move.

If you look at the screenshots on the front page you will also see a new icons area coming, if the clock size is increased I do not believe this would all fit.

**Comment by Blackymas** [comment]
as @danwright87  has already written, this is not possible via bleuprint.

What you can do is download the nspanel-HMI and change the font in there.

Then export as tft and upload to the nspanel.

There are currently no plans to make the font larger.

**Comment by bkbartk** [comment]
Thanks for the reply,

If I have some time, I will check how to modify and upload an HMI file
