### ISSUE TITLE
`Switch to tasmota (TFT File)`

### ISSUE THREAD

**Issue by Simon99de** [Blackymas/NSPanel_HA_Blueprint#2260]
### Enhancement Summary

Switch to tasmota (TFT File)

### Detailed Description

I was wondering if I switch to tasmota if the custom TFT file could cause problems.

Is there a standard TFT file that I can bottle otherwise?

Why do I want to switch to tasmota?
Weak Nas+ Home Assistant does not work as desired, just like the ns panel and a lamp are the only devices in Home Assistant, but the constant updates also annoy me.

Unfortunately there is no info on this anywhere.

**Comment by edwardtfn** [comment]
The protocols used to control the Nextion display are very diferent between each implementation, so the TFT files aren't compatible.
However, both projects offers a way to upload a TFT file from a custom url, so you can upload their TFT using our engine and then flash the new firmware or install their firmware first and then use their instructions to install the proper TFT file.

**Comment by Simon99de** [comment]
Many thanks for the information,
The question is, where do I get the TFT file now?
As far as I know, tasmota does not flash the standard Sonoff Nextion display firmware.

**Comment by edwardtfn** [comment]
Aha!

Please take a look at this: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/972#issuecomment-1673164989

**Comment by Simon99de** [comment]
> Aha!
> 
> Please take a look at this: [#972 (comment)](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/972#issuecomment-1673164989)

Unfortunately, the TFT file no longer exists

**Comment by edwardtfn** [comment]
[ns-panel.zip](https://github.com/user-attachments/files/16848800/ns-panel.zip)

**Comment by Simon99de** [comment]
> [ns-panel.zip](https://github.com/user-attachments/files/16848800/ns-panel.zip)

Thank you very much, it works.
Could the file possibly be added to blank TFT (just named differently.
