### ISSUE TITLE
`Enhancement` Screensaver tweeks.  

### ISSUE THREAD

**Issue by fordcrews** [Blackymas/NSPanel_HA_Blueprint#2281]
### Enhancement Summary

I'd like the option to put a leading zero on the screensaver, and have it's color change based on temperature.

### Detailed Description

The current large font, shows time like 11/11/AM with AM cut in half on US vertical displays, and if the time is before 10, it gets really odd.   Would love it to put a leading zero on times before 10, and leave off the AM/PM, so the display would always be 2 digits on top row, 2 digits on bottom row.   

Another enhancement I would love was a temperature sensitive mode, where the time is displayed blue if the temperature is 2 degrees below the set point, red if it is 2 degrees above the set point, and green if it is within 1 degree of the set point.    So when my wife wakes up in the middle of the night having a hot flash, she doesn't get up, waking me up to see if it's her or the ac that needs fixing.

**Comment by edwardtfn** [comment]
Do you mean set the color of the time display on the screensaver?

**Comment by fordcrews** [comment]
I was thinking the numbers, currently I have them a nice green, with a black background.   It's nice being able to glance at the time when you wake up in the middle of the night.    I just think it would be cool if it also gave you the status of your heat/cooling at the same time.   Others might like the status of your alarm, like red numbers if it's armed on panels near doors, so you remembered to turn off the alarm before you opened the door and set it off.

**Comment by edwardtfn** [comment]
Ok, but you mean the screensaver page or the home page?

**Comment by fordcrews** [comment]
![IMG_0160](https://github.com/user-attachments/assets/da356173-b328-4cdb-9ea3-43f4d1c6f001)
I mostly wanted the screen savers to not look like this, and while posting that I thought it would be great if it's color indicated some status.  I love the clock I can see from across the room, so most of mine are never on the home screen.

**Comment by fordcrews** [comment]
Cool, I have yet to update my dev blueprint, lazy me.    You are the man.

**Comment by edwardtfn** [comment]
Solved in `DEV`
