### ISSUE TITLE
`Bug` qrcode_value to smal

### ISSUE THREAD

**Issue by tbretz65** [Blackymas/NSPanel_HA_Blueprint#2282]
### TFT Version

4.3.11

### Firmware Version

4.3.11

### Blueprint Version

4.3.11

### Panel Model

EU

### What is the bug?

when I enter my wlan ssid and my passwd, the password is truncated.

### Steps to Reproduce

e.g qrcode_value is like :
_WIFI:T:WPA;S:FritzBox Guest Wlan;P:123456789012345678901234567890;;_
you get:
_WIFI:T:WPA;S:FritzBox Guest Wlan;P:123456789012345_
as qrcode

if the qr code value is smaller: (like without "Wlan" in ssid)
_WIFI:T:WPA;S:FritzBox Guest;P:123456789012345678901234567890;;_
you get:
_WIFI:T:WPA;S:FritzBox Guest;P:12345678901234567890_

**Comment by edwardtfn** [comment]
This is due to a memory limitation on that Nextion display used on NSPanel.
I can take a look later on how to prove this.
How many chars you need in total?

**Comment by tbretz65** [comment]
the entire entry is approximately 80 characters long.
It's about the QR code for a WiFi
like this:
WIFI:T:WPA;S:FritzBox-6591 Gastzugang;P:yBVcuyb3K6Gb4jxyzkXSAxDPayudzh9n;;
that changes daily

Thanks for your help

**Comment by tbretz65** [comment]
Hello,
I tested it myself in the nextion editor.
Unfortunately I can't set 80 characters for the QR code. Text_maxl = 78. It can't do more than that.
but 78 is enough for me too
So if 80 characters isn't possible, then 78 is enough

Thank you

**Comment by edwardtfn** [comment]
I think we can do more with a dynamically plotted QR code. The downside is not having the memory verification upfront, but I will play with this and see how much we can go with this new approach.

**Comment by edwardtfn** [comment]
I rebuild the QRcode engine completely, but looks like the limit is just the same.
I will try reducing other global vars to see if that improves anything, but so far, I couldn't get more than 78 chars. :(

**Comment by edwardtfn** [comment]
By making everything on Home page local, I could get QRcode up to 134 chars. I will have to rebuild page Home to support at least some of those items as local.
I will put myself a goal of 96 chars for the QRcode and hopefully that will attend the majority of the people.

**Comment by edwardtfn** [comment]
Solve in `DEV`

**Comment by luckyzor** [comment]
> the entire entry is approximately 80 characters long. It's about the QR code for a WiFi like this: WIFI:T:WPA;S:FritzBox-6591 Gastzugang;P:yBVcuyb3K6Gb4jxyzkXSAxDPayudzh9n;; that changes daily
> 
> Thanks for your help

Hello, do you update the password manually, or do you use an automation?
thanks
