### ISSUE TITLE
`Enhancement` Seperate thermostat from relays

### ISSUE THREAD

**Issue by scodyw** [Blackymas/NSPanel_HA_Blueprint#2292]
### Enhancement Summary

 Seperate thermostat from relays

### Detailed Description

It would be beneficial if the call for heat and cool had an "Entity to control" selection in the blueprint, instead of being coded to the relays.

I intend to use the relays to control room lighting and the thermostat to control remote relays. 
A lot of the benefit of having a wireless thermostat is lost, if I still need to run wires to the heater.

**Comment by edwardtfn** [comment]
You can go that today. Just don't include any of the climate add-ons on your yaml and then set the climate entity on the Blueprint pointing to any climate entity from Home Assistant.

**Comment by scodyw** [comment]
I am not asking to select a different climate entity, but to be able to use the climate add-ons to control a different relay, instead of requiring " heater_relay: "1" " (or 2). Then the user does to not have to make a climate control entity for the relay they want to control, especially if they do not know how.

**Comment by edwardtfn** [comment]
You mean using the climate add-on to control a relay on Home Assistant (outside the panel)? The [Generic Thermostat](https://www.home-assistant.io/integrations/generic_thermostat/) already covers this need, no?

**Comment by scodyw** [comment]
I see. I did not know that would work. I tried it and you are correct. Thank you for the help, I have it configured correctly now.
