### ISSUE TITLE
Nspanel Config Blueprint not starting new UI. 

### ISSUE THREAD

**Issue by benmartucci** [Blackymas/NSPanel_HA_Blueprint#235]
I've flashed the device and powered it on. EspHome found it, and I configured it. Once I tried to google the TFT display 2 second later it became unavailable. I then get this error in repairs, but do not know hoe to fix it. 

The automation "NSPanel Configuration" (automation.nspanel_configuration) has an action that calls an unknown service: esphome.nspanelv1_send_command_text_printf.

This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](http://homeassistant.local:8123/config/automation/edit/1674521217701) and remove the action that calls this service.

EspHome Version [v2022.12.6](https://www.esphome.io/)

Home Assistant 2023.1.7
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230110.0 - latest

alias: NSPanel Configuration
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: nspanelv1
    language: ENG
    weather: Default
    weather_entity: weather.forecast_home
    humidity: sensor.ble_humidity_a4c138891f90
    climate: climate.living_room
    left_button_entity: switch.sonoff_100156dbc6_2
    left_button_name: Office Light
    right_button_entity: light.office_lamp_switch
    right_button_name: Office Lamp
    button_page01_label: Office
    button_page02_label: Living Room
    button_page03_label: Kitchen
    button_page04_label: Hallway
    outdoortemp: sensor.temperature
    sync_value_ha: select_yes

Trace

Triggered by the time pattern at January 23, 2023 at 9:15:00 PM

Define variables entity_long, entity_long_name, entity_back

Choose: Option 17 executed

Stopped because an error was encountered at January 23, 2023 at 9:15:00 PM (runtime: 0.20 seconds)

Unable to find service esphome.nspanelv1_send_command_text_printf

**Comment by frlessard** [comment]
I have the similar problem!  It look like the problem is the register service in HA, but I don't know where to fix it!
