### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by red-centre** [Blackymas/NSPanel_HA_Blueprint#237]
Hi, I was playing around with the hmi file - trying to adapt to US portrait - and noticed that there is a "notifications" page - I was just wondering how I would go about sending a notification?  (apologies if it is documented somewhere, or if it should be obvious...)

**Comment by Blackymas** [comment]
Hi, sounds great that someone is now trying to convert it for the US version ;)

Am very curious about your version - as soon as you are done I would like to add it to Github :)

Service:
ESPHome: nspanel_dev_notification_show

https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.0.0

**Comment by red-centre** [comment]
Will share when I get it to a shareable stage - currently just getting familiar with Nextion.  It is reasonably easy to make it functional, but need to redo graphics for perspective, and spend some time playing with the layout of buttons etc.  Thanks for the great work on this, though - was especially pleased with the tip on how to get esphome flashed after having put JBro99's work onto it already

**Comment by danwright87** [comment]
@red-centre a hint of you are new to nextion. If you are having to change images like you say for layout, make sure you use the replace function or the image number of everything will change and the code will no longer use the correct images

**Comment by Blackymas** [comment]
v.3.1.0 have full us Version support - have fun ,)
