### ISSUE TITLE
Respect the min_temp of thermostat

### ISSUE THREAD

**Issue by bkbartk** [Blackymas/NSPanel_HA_Blueprint#238]
Hello,

I'm using the home assistant generic_thermostat which has a  min_temp of 7
https://www.home-assistant.io/integrations/generic_thermostat/
this is good for me as my anti-freeze away temp is 8.

however, the thermostat slider won't go lower then 13, and using the arrows I can go way lower then 7.
is it possible to respect this setting?

I think a similar issue will be there for max_temp, but haven't checked than one

**Comment by Blackymas** [comment]
via slider this is not possible but you can still change the temp with the up and down buttons even to 8 degrees

**Comment by bkbartk** [comment]
thnx,

I see this question has already been raised earlier.
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/137
sorry for the duplicate.
