### ISSUE TITLE
`Bug` `Issue` NO IDEA. TASMOTA, Lovelace UI, NSpanel > ESP32 ? 

### ISSUE THREAD

**Issue by SkyTezz** [Blackymas/NSPanel_HA_Blueprint#2382]
### Panel Model

None

### What is the bug?

So. I had working Tasmota 14.xx instaled on my NSPanel EU with LovelaceUi. Everything was working great.

Was following steps from the guide. 

"Upload TFT using NsPanel Lovelace UI tools - Tasmota version"

Done, Blank.tft is on. 

Next step from the guide is:

"Just go to your devices's page (under Settings > Devices & services > ESPHome), select your Upload TFT display - Model and then press Upload TFT display."

What? I can not configure it. 

So I did some research, for about 3 hours, because I am totally not an IT guy, and found that -> 

https://esphome.io/guides/migrate_sonoff_tasmota.html#getting-the-binary

So I managed to, via : /hassio/ingress/5c53de3b_esphome, to create a NEW entity ESP32 named nspanel. The YAML I have kept as it is. When i added the lines:

packages:
core_package: !include esphome/nspanel_esphome_core.yaml
upload_tft_package: !include esphome/nspanel_esphome_addon_upload_tft.yaml

It could not compiled. 

Then I compiled the basic .bin firmware. The "Modern" one wasnt working Via tasmota. Something something "Key" issue. HELL YEAH. So I read in issues that i need to compile the "Legacy one"

Did that and the firmware was finally flashed on NSPanel. 

Now It even showed up in my Integrations, with option to choose it via EPS32.

So that is when it ended. I can not flash it with the current firmware. I can not flash it with the nspanel_eu.bin

I really have NO IDEA. And the tutorial is totally unhelpfull. It skips multiple steps. (For what reason it doesnt mention flashing EPS32 after uploading blank to tasmota? ) 

My logs are currently. 

```log
INFO ESPHome 2024.10.3
INFO Reading configuration /config/esphome/nspanel.yaml...
INFO Starting log output from 192.168.1.223 using esphome API
INFO Successfully connected to nspanel @ 192.168.1.223 in 0.037s
INFO Successful handshake with nspanel @ 192.168.1.223 in 0.126s
[00:30:06][I][app:100]: ESPHome version 2024.10.3 compiled on Nov 19 2024, 00:04:55
[00:30:06][C][wifi:600]: WiFi:
[00:30:06][C][wifi:428]:   Local MAC: E4:65:B8:1C:46:A0
[00:30:06][C][wifi:433]:   SSID: [redacted]
[00:30:06][C][wifi:436]:   IP Address: 192.168.1.223
[00:30:06][C][wifi:440]:   BSSID: [redacted]
[00:30:06][C][wifi:441]:   Hostname: 'nspanel'
[00:30:06][C][wifi:443]:   Signal strength: -55 dB ▂▄▆█
[00:30:06][C][wifi:447]:   Channel: 9
[00:30:06][C][wifi:448]:   Subnet: 255.255.255.0
[00:30:06][C][wifi:449]:   Gateway: 192.168.1.1
[00:30:06][C][wifi:450]:   DNS1: 8.8.8.8
[00:30:06][C][wifi:451]:   DNS2: 8.8.4.4
[00:30:06][C][logger:185]: Logger:
[00:30:06][C][logger:186]:   Level: DEBUG
[00:30:06][C][logger:188]:   Log Baud Rate: 115200
[00:30:06][C][logger:189]:   Hardware UART: UART0
[00:30:06][C][captive_portal:089]: Captive Portal:
[00:30:06][C][mdns:116]: mDNS:
[00:30:06][C][mdns:117]:   Hostname: nspanel
[00:30:06][C][esphome.ota:073]: Over-The-Air updates:
[00:30:06][C][esphome.ota:074]:   Address: nspanel.local:3232
[00:30:06][C][esphome.ota:075]:   Version: 2
[00:30:06][C][esphome.ota:078]:   Password configured
[00:30:06][C][safe_mode:018]: Safe Mode:
[00:30:06][C][safe_mode:020]:   Boot considered successful after 60 seconds
[00:30:06][C][safe_mode:021]:   Invoke after 10 boot attempts
[00:30:06][C][safe_mode:023]:   Remain in safe mode for 300 seconds
[00:30:06][C][api:140]: API Server:
[00:30:06][C][api:141]:   Address: nspanel.local:6053
[00:30:06][C][api:143]:   Using noise encryption: YES
```

So YEAH. The Panel is apparently flashed with ESP32? 
However when i open integrations in HASS the Tasmota integration still pops up with offer to integrate the device.

Did i missed something? Did i need to make changes to the YAML file, compile it as legacy again and upload it again? 
There are over 2 thousand issues and no one brought up that this tutorial for reflashing tasmota doesnt mention how to flash esp32  on it ?

Thanks Guys, I am technically dumb for these things..

**Comment by SkyTezz** [comment]
![image_2024-11-19_005509165](https://github.com/user-attachments/assets/35c8ac6a-1704-4ebc-ab94-4e7720318d19)

Okay, so I have tried to editing the YAML file located in ESP32 addon, the one that I have reflashed the Tasmota with previously. 

![image](https://github.com/user-attachments/assets/0a9167fc-989f-4d51-b709-8962d48d6d44)

I have copied and created the files where they should have been? 

![image](https://github.com/user-attachments/assets/67dfa79a-f170-4f16-8f53-968e89bfc00e)

I have also tried the same not via Studio Code Server but Via. File Editor.

**Comment by edwardtfn** [comment]
> For what reason it doesnt mention flashing EPS32 after uploading blank to tasmota?

That was not needed when that tutorial was made. 😉
You are the first one reporting this issue. I will be happy to improve that tutorial as soon we understand what went wrong.

> I have copied and created the files where they should have been?

No. You don't need any copy of those files locally.

> ![image_2024-11-19_005509165](https://github.com/user-attachments/assets/35c8ac6a-1704-4ebc-ab94-4e7720318d19)

Please replace this **entirely** by the yaml shown on step 8 of this: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/install.md#setting-up-a-device-on-esphome-dashboard

Just change the things under substitutions, nothing else for now.
Flash your device and please share the logs if you have any issue.
After flashing, please go to the device page (Settings > Devices and Services > ESPHome), select the right model under "TFT update - Model" and then press "Update TFT".

**Comment by SkyTezz** [comment]
Thanks.

So I have tried flashing Wirelessly. Wouldn´t work because of some "Password". After a few attemps with different itterations of password provided, I just flashes via USB interface using this guide for [pinout](https://sequr.be/blog/2023/01/flashing-nspanel-with-tasmota-and-nspanel-lovelace-ui/)

With the IO0 going to GND second pin from left on board. Flashes via [Web installer](https://web.esphome.io/?dashboard_install. )

Flash went sucesfull. Display still showing the QR code with blank.tft 

Then went to HASS -> Opened ESPHome integration via. web browser -> Instal via. web. 

Logs are [There](https://drive.google.com/file/d/17J902FaAiCgmXSq0vtPLwGMGPi8DEvCV/view?usp=sharing)

![image](https://github.com/user-attachments/assets/2d2495e2-0d1f-4e43-bf60-50a44f7b8988)

Also I have went for :  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional and put the file there. URL works for download of the said file. Just I am not sure how important is this step.

**Comment by edwardtfn** [comment]
> So I have tried flashing Wirelessly. Wouldn´t work because of some "Password". After a few attemps with different itterations of password provided, I just flashes via USB interface using this guide for [pinout](https://sequr.be/blog/2023/01/flashing-nspanel-with-tasmota-and-nspanel-lovelace-ui/)

I understand you solved this by flashing via cable, which is always the best, but just to leave for others who face this same issue but can os flash via cable:
This issue is caused by a previous firmware installed setting an OTA password or even no password. This project uses the wifi password for OTA also.
I also don't like this, but it was there even before I got to know this project and we cannot change this without breaking to all existing users.
Anyways, if this is the case, you must know the previous OTA password (or in your case you must know it was with no password).
If you previously have an OTA password:
```yaml
ota:
  - id: !extend ota_std
    password: <<you previously used password>>
```
Or if you don't used a password:
```yaml
ota:
  - id: !extend ota_std
    password: !remove
```

**Comment by edwardtfn** [comment]
> Logs are [There](https://drive.google.com/file/d/17J902FaAiCgmXSq0vtPLwGMGPi8DEvCV/view?usp=sharing)

You log shows you still missing the final TFT file and, as I can see, the option to update it is not available in your device's page. This is odd.
I would suggest you removing the integration of this device (also under Settings > Devices and Services > ESPHome, but now expand the list instead of clicking devices) then in the list of integrations (devices) click the 3-dot menu and select "Remove". It shoukd auto-detect your device again in a few seconds, otherwise you can try restarting Home Assistant.

**Comment by SkyTezz** [comment]
So yeah. That was it. Removing and adding it again. 

Thank You Edwardtfn. I suggest just changing the tutorial after steps ->
