### ISSUE TITLE
`Bug` Nextion not connected and screensaver time not working correct

### ISSUE THREAD

**Issue by Mauricewillemstein** [Blackymas/NSPanel_HA_Blueprint#2391]
### TFT Version

v4.4.0.dev7

### Firmware Version

v4.4.0.dev7

### Blueprint Version

v4.4.0.dev7

### Panel Model

EU

### What is the bug?

Hi, i instaled v4.4.0.dev7 and found some bugs.
After upload the esp32, nextion is cot connected.
Upload fails, but workind after setting the baudrate for nextion on 115200.
After a while it's uploading. Then there is no problem setting it to fastest baudrate.
Also the screensaver does not work, only after one time switching the display on and off.
The hardware relays still are pending in the logfile

These issues are fixed this way buy maybe you can take a look whats going on.

Also included the logfile for you.

Regards Maurice

### ESPHome Logs

[logs_zolder_run (1).txt](https://github.com/user-attachments/files/17868738/logs_zolder_run.1.txt)

**Comment by Mauricewillemstein** [comment]
The notification sound also is not working, and using the buzzer-gain does not play sound when sliding.

[13:45:30][D][number:054]: 'Buzzer - Gain' - Setting number value
[13:45:30][D][number:113]:   New number value: 53.000000
[13:45:30][C][rtttl:030]: Rtttl:
[13:45:30][C][rtttl:031]:   Gain: 0.947000
[13:45:30][D][number:012]: 'Buzzer - Gain': Sending state 53.000000

**Comment by edwardtfn** [comment]
> The hardware relays still are pending in the logfile

I don't understand why this is still happening.. I cannot duplicate it here. 😞 
Could you please double check your Home Assistant logs (Settings > System > Logs) for anything that could be related to the Blueprint/Automation for your panel?

**Comment by Mauricewillemstein** [comment]
Here are some logs.
If you need an other specific los or you want me to test something let me know.
I have installed the latest dev and the problem of the HW-relais is still there
[logs_zolder_logs.txt](https://github.com/user-attachments/files/17878916/logs_zolder_logs.txt)
[home-assistant_2024-11-23T07-31-57.596Z.log](https://github.com/user-attachments/files/17878917/home-assistant_2024-11-23T07-31-57.596Z.log)
[5c53de3b_esphome-dev_2024-11-23T07-28-28.746Z.log](https://github.com/user-attachments/files/17878918/5c53de3b_esphome-dev_2024-11-23T07-28-28.746Z.log)

**Comment by edwardtfn** [comment]
I believe the screensaver issue was fixed in `DEV`, but this time you have to update both the Blueprint and ESPHome to test, although I haven't changed the version number.
