### ISSUE TITLE
`Bug` System date error after upgrading to 4.3.12

### ISSUE THREAD

**Issue by rploeg** [Blackymas/NSPanel_HA_Blueprint#2401]
### TFT Version

4.3.12

### Firmware Version

4.3.12

### Blueprint Version

4.3.12

### Panel Model

None

### What is the bug?

After updating to 4.3.12 I receive a System Date Error in my screen. 

[10:23:36][W][component:237]: Component script took a long time for an operation (61 ms).
[10:23:36][W][component:238]: Components should block for at most 30 ms.
[10:23:36][D][sensor:094]: 'ntc_source': Sending state 1.76250 V with 2 decimals of accuracy
[10:23:36][D][resistance:039]: 'resistance_sensor' - Resistance 12839.0Ω
[10:23:36][D][sensor:094]: 'resistance_sensor': Sending state 12839.02441 Ω with 1 decimals of accuracy
[10:23:36][D][ntc:026]: 'Temperature' - Temperature: 19.5°C
[10:23:36][W][nextion:431]: Nextion reported variable name invalid!
[10:23:36][W][nextion:431]: Nextion reported variable name invalid!
[10:23:36][W][nextion:431]: Nextion reported variable name invalid!
[10:23:36][W][nextion:431]: Nextion reported variable name invalid!
[10:23:36][W][nextion:431]: Nextion reported variable name invalid!

If I switch off the device (remove panel) and switch it on. I get the message directly. The interesting thing it shows also the error 90 degrees to the right (look like the screen rotated/ but only see the message)

**Comment by edwardtfn** [comment]
Could you please try to Update TFT again (Settings > Devices & services > ESPHome, you will find this under your panel's page) but this time collecting ESPHome logs from right before you press that until the moment your panel restarts (or even a few seconds after it's back)?

**Comment by rploeg** [comment]
Thanks. That is working - don't know why this happened. I only see this error in the systemlog:

`Logger: homeassistant.components.automation.new_automation_3
Source: helpers/script.py:2032
integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 11:35:45 AM (245 occurrences)
Last logged: 8:48:42 PM

NSpanel ingang naar woonkamer: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: Repeat at step 10: Error executing script. Invalid data for if at pos 1: string value is None for dictionary value @ data['txt']
NSpanel ingang naar woonkamer: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: Error executing script. Invalid data for repeat at pos 10: string value is None for dictionary value @ data['txt']
NSpanel ingang naar woonkamer: Main choices: NSPanel event: Choose at step 2: Page changed: Error executing script. Invalid data for choose at pos 1: string value is None for dictionary value @ data['txt']
NSpanel ingang naar woonkamer: Main choices: NSPanel event: Error executing script. Invalid data for choose at pos 2: string value is None for dictionary value @ data['txt']
NSpanel ingang naar woonkamer: Error executing script. Invalid data for choose at pos 3: string value is None for dictionary value @ data['txt']`

**Comment by edwardtfn** [comment]
Could you please collect ESPHome logs when updating TFT, then share it here?

**Comment by C4ptainMeow** [comment]
i did the logs over the mobile Home Assitant App on iOS and cant seem to download it.. But it said at Blueprint Logs TFT Version unknown and the nextion gave back invalid Data in the logs. After i disabled the Notification Sound it worked fine.

**Comment by edwardtfn** [comment]
Notification sound shouldn't affect this.
Anyways, as I understood, you have your system working properly now, right?

**Comment by Dr-Seltsam** [comment]
Also happend to me some days before. First updating to the "NSPanel Blank" then to the "NSPanel EU" worked for me every time (9 NSPanel on my system).
