### ISSUE TITLE
`Bug` In DEV not able to upload TFT

### ISSUE THREAD

**Issue by Mauricewillemstein** [Blackymas/NSPanel_HA_Blueprint#2407]
### TFT Version

Dev

### Firmware Version

Dev

### Blueprint Version

Dev

### Panel Model

EU

### What is the bug?

In dev version unable to upload tft.
[11:33:19][I][script.report_upload_progress:182]: Setting baud rate
[11:33:19][I][script.set_baud_rate:730]: Baud rate changing from 921600 to 0 bps

ns panel reboots and thats it.

[logs_zolder_logs (1).txt](https://github.com/user-attachments/files/17917951/logs_zolder_logs.1.txt)

**Comment by edwardtfn** [comment]
I'm not at home right now, so I cannot test it. Will take a look at the code and see if it is something easy to fix...

**Comment by edwardtfn** [comment]
Could you please update your ESPHome and try again?

**Comment by Mauricewillemstein** [comment]
Now works as a charm.

Thx

**Comment by Mauricewillemstein** [comment]
Just a note..... i dont want to anoy you but want to help find some issues.
I am nor that much in programming but just want to help to make it as great as possible

**Comment by edwardtfn** [comment]
I'm so happy that someone else is looking at `DEV` and giving feedback. It's much harder when we only find those issues in the days before a release.
Thanks for you support with this. 😉

**Comment by Mauricewillemstein** [comment]
No problem to help.
Every day i look to fimd if there is someting that  is not working.

Keep up the great work

**Comment by Mauricewillemstein** [comment]
Maybe just ignore the hw relay from blueprint?
All seems to working fine.
And it's not from the modification i did with you some time ago for a rfid reader.
That is on a other ns-panel that is still on the main branch.

**Comment by edwardtfn** [comment]
I cannot duplicate that HW Relay thing... I will have to create a version collecting more logs so you can help me troubleshooting this.
But I'm in the middle of an optimization on Button pages now. Let me finish this first, then I come back to this relay thing.

**Comment by edwardtfn** [comment]
The issue with HW Relay's is probably at the blueprint side.

**Comment by Mauricewillemstein** [comment]
ok thats fine. just let me know
