### ISSUE TITLE
Automation from blueprint causes error

### ISSUE THREAD

**Issue by sygad** [Blackymas/NSPanel_HA_Blueprint#241]
Hi

I created an automation from the blueprint, filling in the required details.

After about 1-2mins, I get an error stating the automation is trying to use an unknown service.

![Error](https://user-images.githubusercontent.com/1771605/214390769-27cb6a93-4313-43ff-b4d9-9952a4e6134d.png)

![Error details](https://user-images.githubusercontent.com/1771605/214390839-b6b30e72-9f9e-42af-9a1a-f0027e88c1e6.png)

When asked to edit the automation I cannot find anything more to remove or replace, as stated, the bare essentials have been completed.

When I delete the automation, the error is still there. I have to delete the blueprint to remove the error.

I have tried the following to remedy.

Rolled back HA to an earlier version
Installed an older version of the blueprint
Updated to latest version of HA and bluepring

No matter what combination, as soon as I make an automation from the blueprint, after about 1-2mins I get the error.

**Comment by danwright87** [comment]
Hi, what is the name of the nspanel is ESPHome?

**Comment by MarkuZP** [comment]
underscores are not allowed in the panel name!

**Comment by danwright87** [comment]
> underscores are not allowed in the panel name!

Underscores are allowed, dashes are not. HA replaces dashes with underscores

**Comment by sygad** [comment]
I tried creating the ESPHome part, then using the same name in the blueprint based automation......I got the error

I then tried deleting the ESPHome project and using ONLY the blueprint and the automation..........I got the error

I've literally just now created a brand new ESP project, using the sample code, and a brand new automation.....I got an error

<img width="989" alt="Screenshot 2023-01-24 at 20 28 51" src="https://user-images.githubusercontent.com/1771605/214402084-b9e434bc-614b-4e2a-8638-e21591f1d528.png">

<img width="1222" alt="Screenshot 2023-01-24 at 20 29 27" src="https://user-images.githubusercontent.com/1771605/214402249-5c7127d1-2554-41e2-a4aa-a06879fb8113.png">

<img width="639" alt="Screenshot 2023-01-24 at 20 31 21" src="https://user-images.githubusercontent.com/1771605/214402407-1bedf11e-9c64-4d99-b1a7-375415638c2d.png">

**Comment by sygad** [comment]
I have deleted the NSP Test automation but cannot remove the errors without removing the blueprint.

**Comment by danwright87** [comment]
Have you added ESPHome integration in home assistant for device 'nsp_office'?

**Comment by danwright87** [comment]
On a unrelated note - you need to update the nextion_update_url in you ESPHome config else you won't be able to upload the TFT when you get to that step

**Comment by sygad** [comment]
LOL, I saw the URL and wondered if anyone would comment ;-)

**Comment by sygad** [comment]
Updated the TFT URL _(Im using DuckDNS, hence the https)_

![Screenshot 2023-01-24 at 20 54 41](https://user-images.githubusercontent.com/1771605/214414962-1db42e38-528c-402c-bb70-ff906d6eb091.png)


Just gone through the whole flashing process again.

New device discovered and then added.

![Screenshot 2023-01-24 at 21 01 37](https://user-images.githubusercontent.com/1771605/214415048-7241dd2d-500c-48cc-8168-996f71f3e3cf.png)

Toggling the "update TFT"........does nothing......and I still have the error.

![Screenshot 2023-01-24 at 21 02 07](https://user-images.githubusercontent.com/1771605/214415272-9fd8718d-6a5f-439e-9a59-2bee1ca80b24.png)

**Comment by sygad** [comment]
Interestingly, I just toggled everything off and on and suddenly it looks like the "update TFT" is doing an update......fingers crossed

**Comment by Blackymas** [comment]
pls share a short feedback ;)

**Comment by sygad** [comment]
Since my last update of TFT updating, it's been 3 hours and it's 9% in, something doesn't feel right about that

**Comment by Blackymas** [comment]
then try without https.

but the long upload is dependent or a problem with you 


have a look here (answer from @danwright87 )

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/212

**Comment by sygad** [comment]
I tried http, didn't work at all

Wifi is rock solid (Unifi)

I'm in the process of building a brand new instance of Home Assistant, the only thing I will install is ESPHome and the blueprint.

I really want this to work

**Comment by danwright87** [comment]
Did you reflash ESPHome on the nspanel after changing the nextion URL in the yaml to be local?

**Comment by sygad** [comment]
yes, my long post above where I mentioned updating the URL and then I proceeded to redo the whole thing, probably easier to list the steps I took.

- Deleted the integration of the NSPanel (to start from scratch)
- Updated the URL to my local (https as I use DuckDNS)
- Reflashed the ESPHome to Panel
- HA detected new device, configured and integrated
- Went to the device and toggle update TFT
- 20 or so hours later, white screen followed by "System Data Error"


BTW, thanks for the continued support and helping me try to solve it, it's very much appreciated

**Comment by danwright87** [comment]
Ok, try a plain HTTP local host of the TFT file and see if that works. The way the TFT upload works in ESPHome isn't great and the ESP32 will keep calling to the web server.  The fact you will have a HTTPS cert error too might not help

**Comment by sygad** [comment]
Forgive my ignorance on that one, could you explain a little further about the "plain HTTP local host" - not exactly sure what means or how to proceed

cheers

**Comment by danwright87** [comment]
Hi, you would need to change home assistant from HTTPS to just http or set up a web server on a pc or other device on you LAN to provide the file.

**Comment by sygad** [comment]
Success and a Failure:

**Success steps I followed:**

Using a brand new instance of HA

- Installed ESP Home
- Imported Blueprint
- Uploaded tft file to newly created WWW folder
- Created ESP device (name with no spaces, dashes or underscores "nspoffice")
- Created bin file and uploaded to NSPanel
- HA detected and I integrated new device
- THEN
- Created an automation from the blueprint ensuring espname and automation name was the same
- Went to device and toggle "update TFT"

This got it working ;-)

I now needed to get it working on my main insstance of HA

Following @danwright87 advice I created a simple web server on my Synology NAS and place the NSPanel file in the root folder.

I followed the exact same steps as above making sure this time I changed the nextion URL to point to my HTTP server.

When I toggled the update TFT button 2nd time round, it was almost instantaneous.

There seems to be a very specific sequence that I had to follow to avoid the "unknown service" error I was experiencing.

1. Create, install and integrate the ESP device
2. Create the automation
3. Update the TFT

**Failure**

I still have 1 panel, that despite my success, is still not playing ball, it's currently connected to my brand new HA instance, but the "update TFT" is still taking forever, and it's being uploaded locally from http (not https)

**Comment by sygad** [comment]
Cheers for the help along the way.

Yes, now that you've explained the partial update, it would explain the near instant update when I moved it to my main HA machine.

Is it fair to say that if the TFT update is taking hours, that it is destined to fail?
This 2nd panel has been going for about an hour now and it's on 5%, im wondering if it's worth abandoning and trying to move it to my main HA instance?

ALso, 7 Panels? That is a rather expensive light switch hobby you got going on there ;-)

**Comment by danwright87** [comment]
No problem.

Yes, I've found if it's going painfully slow it always fails and corrupts the screen but in most cases a normal upload again is OK once I moved to a local TFT file. 

Even a full upload having never installed  is maybe 20 mins max for me.

I've got more to do tomorrow 😂 it is, I backed them on Kickstarter and think it's a great product so hot a load of them

**Comment by sygad** [comment]
Yeah, I got my 2 off kickstarter and then waited patiently for some enterprising genius to make them useful.

Massive thanks to all of them, this has been a dream of mine for a VERY long time and i'm SO close to realising it.

**Comment by sygad** [comment]
Moved the 2nd panel over to main HA, followed the steps I tried earlier

It absolutely refuses to bidge from "System Data Error" screen.

Everytime I toggle the update TFT, it flashes white momentarily and then just returns to the error message.

Is it possible i've bricked it?

**Comment by danwright87** [comment]
I've had that and ESPHome wouldn't fix it. I found changing to tasmotta and flashing from there recovered it pretty quickly, tasmotta seems to have better TFT upload them change back to ESPHome

**Comment by sygad** [comment]
Can you recommend a guide to follow for Tasmota?

**Comment by danwright87** [comment]
Afraid not, I'd just look up something on the communities or your search engine of choice, it's been a long time since I touched tasmotta

**Comment by sygad** [comment]
Followed [this guide for flashing Tasmota](https://www.youtube.com/watch?v=sCrdiCzxMOQ&t=712s&ab_channel=EverythingSmartHome), which worked well......right up to the point where I had to upload the nspanel.be

The tasmota UI just kept refusing to let me upload the nspanel.be file.

**Comment by Blackymas** [comment]
thanks @sygad
