### ISSUE TITLE
`Bug` [DEV] panel stuck at Initializing... screen 

### ISSUE THREAD

**Issue by bluefoxlee** [Blackymas/NSPanel_HA_Blueprint#2418]
### TFT Version

4.4.0.dev 7 

### Firmware Version

4.4.0.dev 7 

### Blueprint Version

4.4.0.dev 7 

### Panel Model

US

### What is the bug?

Updated with ESPHome 2024.11.2 yesterday, after finished and reboot. 

The log shows Invalid encryption key like below, how ever the configuration yaml is untouched. And the devices  re-connect to the wifi well.

> INFO ESPHome 2024.11.2
> INFO Reading configuration /config/esphome/nspanel-km.yaml...
> INFO Detected timezone 'Asia/Taipei'
> INFO Starting log output from 192.168.1.4 using esphome API
> INFO Successfully connected to nspanel-km @ 192.168.1.4 in 0.096s
> WARNING nspanel-km @ 192.168.1.4: Connection error occurred: nspanel-km @ 192.168.1.4: Invalid encryption key: received_name=nspanel-km
> WARNING Can't connect to ESPHome API for nspanel-km @ 192.168.1.4: nspanel-km @ 192.168.1.4: Invalid encryption key: received_name=nspanel-km (InvalidEncryptionKeyAPIError)

Screen stuck at Initializing....

![IMG_3025](https://github.com/user-attachments/assets/5603e839-a6fa-43dd-bf4a-a5dadf2b9867)

happen to both of my two panels (us-cjk and us-landscape cjk) after updated. I guess I have no choice but to disassemble it to re-flash them (when I got time).

**Comment by edwardtfn** [comment]
I'm travelling to right now, so cannot look at this until tomorrow.
Do you mind using main version meanwile? I let you know when I find something.

**Comment by edwardtfn** [comment]
For the invalid encryption,removing your panel from Home Assistant integrations (under Settings > Devices and Services >ESPHOME, please don't remove from ESPHome dashboard) should help. Your panel will be detected again in a few seconds and will on-board with the right key.

**Comment by bluefoxlee** [comment]
Ok. After disassemble and re-flash it with USB-to-TTL. It back to normal again. (going to flash another one.)
So I think I am going to close the issue for now although I really don't know what went wrong. 

Thanks for the reply and help. Have a nice trip and happy holiday.  :)

**Comment by bluefoxlee** [comment]
> Haven't you changed your Wi-Fi password (which is also used for OTA)?

Nope. I didn't touch anything but click update from ESPhome panel, same as usually. And after couple hours of debug, I decide to update another one to make a test and got same result.

**Comment by edwardtfn** [comment]
I believe this issue was fixed. Please confirm when you have a chance.

**Comment by bluefoxlee** [comment]
> I believe this issue was fixed. Please confirm when you have a chance.

Can't really understand what case the issue. Try to install it and got few error on compile. 
Will try to fix and test it tomorrow (maybe). Got a travel tomorrow.
