### ISSUE TITLE
Upgrading from v2.1 to v3 fails on TFT upload

### ISSUE THREAD

**Issue by GuySie** [Blackymas/NSPanel_HA_Blueprint#242]
Having succesfully run v2.1 for about a month now, I decided to upgrade to v3 today. I replaced the blueprint, changed to the new esphome yaml, uploaded the new esphome firmware and then triggered the TFT upload.

Something apparently went wrong during upload, because now I'm stuck with a screen that is rotated 90 degrees to the right and doesn't want to upload a TFT anymore. If I trigger a local TFT upload, it goes from 0% to 100% fairly fast (about 5 seconds) and then resets back to 0% 4096:
![IMG_9048](https://user-images.githubusercontent.com/3367490/214429527-4beb4270-3694-4806-b401-fef84e39952b.jpeg)

From that point on it seems to try to upload again, but now it takes a very long time to upload any data. Like, goes up 1% in 20 minutes. This is from the local folder on my Home Assistant server.

Trying to upload the blank TFT gives me the same model error message as in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/166 but rotated 90 degrees. Is there any way out that does not require soldering?

**Comment by Blackymas** [comment]
have you looked at the change in the wiki - for some it is better to do the tft upload locally

**Comment by unl0ck** [comment]
hab das gleiche problem auf 2 displays, hab zuerst remote upload gemacht, 
beim 1. display unterbrochen weil ich ned wusste das dauert so ewig
beim 2. hat es nahezu 24h gebraucht, 
hab dann das ganze lokal versucht auf das gleiche ergebnis nun wie er gestossen bei nem restart hab ich "Error Data Read"

**Comment by Blackymas** [comment]
lade zuerst das nspanel_blank.tft hoch und dann das original am besten beides lokal

schau mal hier

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/197

**Comment by GuySie** [comment]
> have you looked at the change in the wiki - for some it is better to do the tft upload locally

Yes, my problems are with local TFT upload through developer services. I started one this night after posting this issue, it did the same 0 to 100% in 5 seconds and then going back to 0% and uploading slow. It's now at 44%.

**Comment by MarkuZP** [comment]
I had exact same Issue: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/197#issuecomment-1397439284

and...If you had flashed Lovelace on that device, you must flash the blank_tft with tasmota before you flash this version!
That was an Issue with my second panel.

**Comment by unl0ck** [comment]
> lade zuerst das nspanel_blank.tft hoch und dann das original am besten beides lokal
> 
> schau mal hier
> 
> #197

Jau Blackymas mein Tagesheld, 3. Gerät storniert das 2. geht jetzt zurück 
funktioniert, 
bombe, 
vllt kann man da so ne topic mit "häufige fehler" machen 

Danke dir

GEILE ARBEIT!!!! BTW.

**Comment by bgga** [comment]
Hi.
I just have the same issue.
Before flashing esphome i uploaded via tasmota nspanel_blank.tft.
Next, upload esp firmware and strart new tft upload.
It takes lot of time, after 8 hours i had 30% uploaded.

**Comment by MarkuZP** [comment]
> Hi. I just have the same issue. Before flashing esphome i uploaded via tasmota nspanel_blank.tft. Next, upload esp firmware and strart new tft upload. It takes lot of time, after 8 hours i had 30% uploaded.

If you do the uploaad locally from www Folder in HA it takes approx. 10 minutes!

**Comment by GuySie** [comment]
> I had exact same Issue: [#197 (comment)](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/197#issuecomment-1397439284)
> 
> and...If you had flashed Lovelace on that device, you must flash the blank_tft with tasmota before you flash this version! That was an Issue with my second panel.

That's the weird thing, I already had v2.1 of the Blackymas version installed and working perfectly fine. I didn't ever use Lovelace before (I did use Marc Fager's version for the original conversion to ESPHome). For the past month, I had no issue at all using the Blackymas v2.1 version on this panel.

> If you do the uploaad locally from www Folder in HA it takes approx. 10 minutes!

I am uploading locally from the HA www folder, through developer services, and it is not fast. It's currently at 54% after 12 hours.

**Comment by danwright87** [comment]
Are you using HTTPs for your HA server? Have you used DNS name or IP?

**Comment by MarkuZP** [comment]
> > I had exact same Issue: [#197 (comment)](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/197#issuecomment-1397439284)
> > and...If you had flashed Lovelace on that device, you must flash the blank_tft with tasmota before you flash this version! That was an Issue with my second panel.
> 
> That's the weird thing, I already had v2.1 of the Blackymas version installed and working perfectly fine. I didn't ever use Lovelace before (I did use Marc Fager's version for the original conversion to ESPHome). For the past month, I had no issue at all using the Blackymas v2.1 version on this panel.
> 
> > If you do the uploaad locally from www Folder in HA it takes approx. 10 minutes!
> 
> I am uploading locally from the HA www folder, through developer services, and it is not fast. It's currently at 54% after 12 hours.

Hmm.. I had similar problems in the beginning.. I had this 90 degrees rotate Screen (screenshot above) too. Let me remember what I did to fix that....
I think it was this order:

1. blank_tft loaded with Service in developertools from HA
2. Restart the Panel with Power cycle
3.  URL for  nspanel.tft  in the ESP YAML edited to local Folder
....
##### DO NOT CHANGE ANYTHING! #####

  #nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft"
  **nextion_update_url: "http://192.168.178.81:8123/local/nspanel.tft"**

4. flash again with this URL
5. Run Service for updating the TFT

Done!

**Comment by MarkuZP** [comment]
And check in the ESP Logs if you have these UART Errors.
![image](https://user-images.githubusercontent.com/109298227/214556507-ffbd15e1-5e36-46fe-9889-22c31fbdebd2.png)

**Comment by wochen** [comment]
> I had exact same Issue: [#197 (comment)](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/197#issuecomment-1397439284)
> 
> and...If you had flashed Lovelace on that device, you must flash the blank_tft with tasmota before you flash this version! That was an Issue with my second panel.

This solved my problem! Thank you @MarkuZP!

**Comment by GuySie** [comment]
> Are you using HTTPs for your HA server? Have you used DNS name or IP?

HTTP by IP:
<img width="1222" alt="Screenshot 2023-01-25 at 17 35 40" src="https://user-images.githubusercontent.com/3367490/214704418-b7828fbd-783f-4401-9ab5-bfeed26ff912.png">

It has finished uploading the local TFT after about 24 hours, so I'm at least 1 step further, but that hasn't really fixed anything, my screen is still rotated 90 degrees and says "System Data ERROR!"

The UART errors I did have in my esphome log are gone, now instead I get this message:
[W][nextion:341]: Nextion reported page ID invalid!

> Hmm.. I had similar problems in the beginning.. I had this 90 degrees rotate Screen (screenshot above) too. Let me remember what I did to fix that.... I think it was this order:
> 1. blank_tft loaded with Service in developertools from HA

Trying to upload the blank tft from local using developer tools results in a red error message on a white screen, still rotated 90 degrees:
Model does not match
Device Model:
NX4832F035 0110

**Comment by Blackymas** [comment]
strange -  I would try to delete the device from HA, delete Blueprint and delete Esphome and then reflash and test.

Or check here - it is exact your issue
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/166

you do not have to solder it on it is enough to stick it with tape or similar

Please also remember that you don't say save as with the blank TFT but use the download button as described here.

https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-First-Steps---Installation-and-Setup

**Comment by MarkuZP** [comment]
I had an equal behaviour first.
Please do these steps:


1 Edit the ESP Home YAML 
2 Change the path to you local www:
....
DO NOT CHANGE ANYTHING!

#nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft"
nextion_update_url: "http://your_HA_IP:your_port/local/nspanel_blank.tft"

3 flash again with this URL

4 Run Service for updating the"blank" TFT
5. then run service with the newest nspanel.tft from blackymas (with baud)

**Comment by Zylazy** [comment]
I have still the same issue. I have upload the blank tft in about one hour. I get the empty white screen, Than I tried to upload the normal nspanel.tft, It is still running, however I have started 21 hours ago, but only 85% is done.
I am getting also these errors:
[22:46:45][E][uart:015]: Reading from UART timed out at byte 0!
[22:46:45][W][nextion:078]: Nextion is not connected! 
[22:46:46][E][uart:015]: Reading from UART timed out at byte 0!
[22:46:46][W][nextion:078]: Nextion is not connected! 

Question: Is the https supported when using ESPHome: DEVICE_NAME_upload_tft_url service? My HA is available only via ssl.

**Comment by danwright87** [comment]
For some users it works with HTTPS but if you experiencing issues moving to http solves it and is normally the only fix.

Just to be clear, this is an ESPHome behaviour and there is nothing that we can do about it in the project

**Comment by deejaybeam** [comment]
My question is: why is your instance only accesable via https?
Best practice is to have your ha accesable internal via http://IP:8123 and a reverse proxy like nginx (there is also a addon) to make it accesable via httpS - so you have both possibilities and the reverse proxy makes ha more secure if you access it from internet.
https://github.com/home-assistant/addons/tree/master/nginx_proxy

**Comment by GuySie** [comment]
I went over everything again, and I realized my nspanel_blank was older than the one now in github. I think I've been trying to flash with an old version? So that problem was firmly between seat and keyboard. Either way, when I redownloaded it and popped it into the service call, it uploaded just fine, no more error message. And after that, I could start the normal upload of the new TFT - still took a good 15 minutes though, even locally. Considering the much shorter times reported in issues here, and that the same file took 24h to upload a few days ago for me, it does seem that upload speed for the panel is being influenced weirdly by things other than the difference between online from github and local from HA.

So my nspanel is fixed now, thanks! I'll leave the issue open for other people currently talking here.

**Comment by Zylazy** [comment]
> My question is: why is your instance only accesable via https? Best practice is to have your ha accesable internal via http://IP:8123 and a reverse proxy like nginx (there is also a addon) to make it accesable via httpS - so you have both possibilities and the reverse proxy makes ha more secure if you access it from internet. https://github.com/home-assistant/addons/tree/master/nginx_proxy I would recomend using swag: https://hub.docker.com/r/linuxserver/swag

Thank for the advice, I will work on it!

**Comment by Zylazy** [comment]
Thank you for your help. Finally it is working. I had to use http in stead of https.

**Comment by Blackymas** [comment]
I think we can close this issue - all issues are solved ;)

thanks @all
