### ISSUE TITLE
Climate support for hardware buttons

### ISSUE THREAD

**Issue by SirEndii** [Blackymas/NSPanel_HA_Blueprint#2421]
### Enhancement Summary

Turn off climate element/toggle to heating mode with hardware buttons.

### Detailed Description

Greetings

I currently have a climate element using two heaters in a room. For convenience, I wanted to install the ns panel into the wall so the employees can just click the right hardware button to turn off the climate element instead the need of using the app.

But this does not really work, I selected the climate element for the right button but when I click it, nothing happens. I am not sure if this is simply a me issue and I did something wrong or it really does not work with the panel.

I know that there is currently #2394 open, but I would just prefer a simple click to disable heating/enable it for the older/not so techie employees

![Screenshot_20241204-094521](https://github.com/user-attachments/assets/7a02f8b5-ee6f-42da-a09f-7677d4ab2d7f)

### Additional Context

I am not an expert with HA, only used it for some months now. So I am sorry for anything I may didn't know

**Comment by edwardtfn** [comment]
I just realized that no action is executed with a short press in a climate entity:

https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/0c0be2dd26ee12de5d30628c60940976b9ce40f8/nspanel_blueprint.yaml#L10605-L10632

It will just refresh the entity status.

I can easily add an action to this, but I'm unsure if a "toggle" action would be the best here. I'm not 100% sure about this, but I think it was a toggle in the past and we changed that for some reason...

**Comment by edwardtfn** [comment]
I've implemented the toggle on `dev` and it will be included in the next release (hopefully soon). Let's see if someone screams...

I will close this for now, to clean-up my desk, but please feel free to reopen if the issue persists after you test the new version.

**Comment by domasist** [comment]
@edwardtfn  is there a way to change HVAC system fan_modes, swing_modes, preset_modes, so user will see which mode is setup?

**Comment by edwardtfn** [comment]
Unfortunately that was not implemented yet.

**Comment by domasist** [comment]
@edwardtfn thx for the info. Do you consider to implement that? What could be the best way to alternate this in the current setup?
