### ISSUE TITLE
errors while updating tft

### ISSUE THREAD

**Issue by luckyzor** [Blackymas/NSPanel_HA_Blueprint#244]
hello,

i've installed esphome via HA and after the install I clicked on "Update TFT Display":
got this in the logs in a loop
12:08:21 | [W] | [nextion:078] | Nextion is not connected!
12:08:22 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:08:22 | [W] | [nextion:078] | Nextion is not connected!

and in my screen:
it took 3hours for this 10% of instalation:
![image](https://user-images.githubusercontent.com/31155573/214548576-57054194-1740-40ee-b41a-665d2c83a840.png)

should I do anything?

**Comment by GuySie** [comment]
I have the same problem in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/242

**Comment by wochen** [comment]
The same problem.

**Comment by danwright87** [comment]
@luckyzor please could you post your ESPHome yaml file

**Comment by luckyzor** [comment]
after @GuySie posted his issue and read the comments, I saw in the wiki how to update the screen with local.
I started by update the tft with the blank took 3 min after I lauch the update of the tft with the nspanel.tft it took 10/15min and its working.
FYI i used the call service on HA.

**Comment by wochen** [comment]
@luckyzor 
could you please share me the link to Wiki's location where I can find a procedure of updating TTF via Developer's tools?
I can't find it.
Thanks in advance.

**Comment by luckyzor** [comment]
> @luckyzor could you please share me the link to Wiki's location where I can find a procedure of updating TTF via Developer's tools? I can't find it. Thanks in advance.

https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-First-Steps---Installation-and-Setup#2-version-nspanel-lovelace-ui-by-jobr99-was-previously-installed

if you need help, feel free to ask

**Comment by wochen** [comment]
Thank you @luckyzor. It's all sorted. 
Finally I had to install Tasmota, upload blank tft and then install esphome and upload a final tft.

**Comment by Zylazy** [comment]
I have tried to follow the wiki. It says i sould run the "ESPHome: DEVICE_NAME_upload_tft" service, and under URL I have to enter the path.
But my problem is, that this service does not have any attribute!
I think the wiki is wrong, and the "ESPHome: DEVICE_NAME_upload_tft_url" service is what we need.  Am I correct, or I missed something?

**Comment by luckyzor** [comment]
> I have tried to follow the wiki. It says i sould run the "ESPHome: DEVICE_NAME_upload_tft" service, and under URL I have to enter the path. But my problem is, that this service does not have any attribute! I think the wiki is wrong, and the "ESPHome: DEVICE_NAME_upload_tft_url" service is what we need. Am I correct, or I missed something?

Yes you are correct.

**Comment by danwright87** [comment]
Hi
That is not correct. The path goes into your ESPHome yaml. (If you change it you will need to reinstall to the device) so the service doesn't need a URL 

You can use that service if you want to manually state a path so does work on this instance.

**Comment by deejaybeam** [comment]
To clear up there are now two services one without any parameter - that uses the url in your esphome-config.yaml the 2nd service (ends with _url) can alway be used to upload a tft from a custom url.
And YES it is correct the wiki refers to the wrong service!
