### ISSUE TITLE
esptool merge_bin: error: argument <address> <filename>: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by lennartschulte** [Blackymas/NSPanel_HA_Blueprint#249]
Sorry for the second issue but i can't get the build to generate with this error-log

> INFO Reading configuration /config/esphome/nspanelwerkstatt.yaml...
> INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
> WARNING GPIO4 is a Strapping PIN and should be avoided.
> Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
> See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
> INFO Generating C++ source...
> INFO Compiling app...
> Processing nspanelwerkstatt (board: esp32dev; framework: arduino; platform: platformio/espressif32 @ 5.2.0)
> --------------------------------------------------------------------------------
> HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
>  - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
> LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
> Dependency Graph
> |-- AsyncTCP-esphome @ 1.2.2
> |-- WiFi @ 2.0.0
> |-- FS @ 2.0.0
> |-- Update @ 2.0.0
> |-- ESPAsyncWebServer-esphome @ 2.1.0
> |   |-- AsyncTCP-esphome @ 1.2.2
> |-- DNSServer @ 2.0.0
> |-- ESPmDNS @ 2.0.0
> |-- ArduinoJson @ 6.18.5
> |-- WiFiClientSecure @ 2.0.0
> |-- HTTPClient @ 2.0.0
> Compiling /data/nspanelwerkstatt/.pioenvs/nspanelwerkstatt/src/main.cpp.o
> Linking /data/nspanelwerkstatt/.pioenvs/nspanelwerkstatt/firmware.elf
> RAM:   [=         ]  13.3% (used 43676 bytes from 327680 bytes)
> Flash: [======    ]  61.9% (used 1135517 bytes from 1835008 bytes)
> Building /data/nspanelwerkstatt/.pioenvs/nspanelwerkstatt/firmware.bin
> Creating esp32 image...
> Successfully created esp32 image.
> esp32_create_combined_bin(["/data/nspanelwerkstatt/.pioenvs/nspanelwerkstatt/firmware.bin"], ["/data/nspanelwerkstatt/.pioenvs/nspanelwerkstatt/firmware.elf"])
> usage: esptool merge_bin [-h] --output OUTPUT [--format {r,a,w}]
>                          [--flash_freq {keep,80m,60m,48m,40m,30m,26m,24m,20m,16m,15m,12m}]
>                          [--flash_mode {keep,qio,qout,dio,dout}]
>                          [--flash_size {keep,256KB,512KB,1MB,2MB,2MB-c1,4MB,4MB-c1,8MB,16MB,32MB,64MB,128MB}]
>                          [--spi-connection SPI_CONNECTION]
>                          [--target-offset TARGET_OFFSET]
>                          [--fill-flash-size {256KB,512KB,1MB,2MB,4MB,8MB,16MB,32MB,64MB,128MB}]
>                          <address> <filename> [<address> <filename> ...]
> esptool merge_bin: error: argument <address> <filename>: [Errno 2] No such file or directory: '/data/cache/platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin'
> *** [/data/nspanelwerkstatt/.pioenvs/nspanelwerkstatt/firmware.bin] Explicit exit, status 2
> ========================= [FAILED] Took 83.64 seconds =========================
>

**Comment by deejaybeam** [comment]
see: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/121

**Comment by lennartschulte** [comment]
As far as i understand the linked issue has problems during the compilation. In my case it states that the image has successfully been created. Are you sure about the relation bewteen these issues? If so and my RasPi 4 has insufficient resources, how can i generate the image instead? Can i also compile it on my local machine?

```
INFO Reading configuration /config/esphome/nspanelwerkstatt.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Updating https://github.com/esphome/esphome.git@pull/2956/head
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing nspanelwerkstatt (board: esp32dev; framework: arduino; platform: platformio/espressif32 @ 5.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- WiFiClientSecure @ 2.0.0
|-- HTTPClient @ 2.0.0
Compiling /data/nspanelwerkstatt/.pioenvs/nspanelwerkstatt/src/esphome/components/api/api_connection.cpp.o
Compiling /data/nspanelwerkstatt/.pioenvs/nspanelwerkstatt/src/esphome/components/api/api_server.cpp.o
Compiling /data/nspanelwerkstatt/.pioenvs/nspanelwerkstatt/src/esphome/components/mdns/mdns_component.cpp.o
Compiling /data/nspanelwerkstatt/.pioenvs/nspanelwerkstatt/src/esphome/components/version/version_text_sensor.cpp.o
Compiling /data/nspanelwerkstatt/.pioenvs/nspanelwerkstatt/src/esphome/core/application.cpp.o
Compiling /data/nspanelwerkstatt/.pioenvs/nspanelwerkstatt/src/esphome/core/util.cpp.o
Compiling /data/nspanelwerkstatt/.pioenvs/nspanelwerkstatt/src/main.cpp.o
Linking /data/nspanelwerkstatt/.pioenvs/nspanelwerkstatt/firmware.elf
RAM:   [=         ]  13.3% (used 43676 bytes from 327680 bytes)
Flash: [======    ]  61.9% (used 1135549 bytes from 1835008 bytes)
Building /data/nspanelwerkstatt/.pioenvs/nspanelwerkstatt/firmware.bin
Creating esp32 image...
**Successfully created esp32 image.**
esp32_create_combined_bin(["/data/nspanelwerkstatt/.pioenvs/nspanelwerkstatt/firmware.bin"], ["/data/nspanelwerkstatt/.pioenvs/nspanelwerkstatt/firmware.elf"])
usage: esptool merge_bin [-h] --output OUTPUT [--format {r,a,w}]
                         [--flash_freq {keep,80m,60m,48m,40m,30m,26m,24m,20m,16m,15m,12m}]
                         [--flash_mode {keep,qio,qout,dio,dout}]
                         [--flash_size {keep,256KB,512KB,1MB,2MB,2MB-c1,4MB,4MB-c1,8MB,16MB,32MB,64MB,128MB}]
                         [--spi-connection SPI_CONNECTION]
                         [--target-offset TARGET_OFFSET]
                         [--fill-flash-size {256KB,512KB,1MB,2MB,4MB,8MB,16MB,32MB,64MB,128MB}]
                         <address> <filename> [<address> <filename> ...]
**esptool merge_bin: error: argument <address> <filename>: [Errno 2] No such file or directory: '/data/cache/platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin'**
*** [/data/nspanelwerkstatt/.pioenvs/nspanelwerkstatt/firmware.bin] Explicit exit, status 2
========================= [FAILED] Took 88.22 seconds =========================
```

**Comment by deejaybeam** [comment]
Again - see: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/121 this is linked to: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/172 
there is also a link to: https://esphome.io/changelog/2022.11.0.html#running-esphome-on-lower-powered-machines
You can try this, or uninstall/install esphome
