### ISSUE TITLE
Thermostat control does not work properly

### ISSUE THREAD

**Issue by adri123** [Blackymas/NSPanel_HA_Blueprint#251]
Hi,
I have configured my climate integration in the blue print.
I can control the on and off state of the thermostat 
but when I change the temperature on the nspanel its not affected on homeassitant.
I use the "generic_thermostat" integration.

Thanks

**Comment by Blackymas** [comment]
the changes will only take effect when you leave the climate page

have a look here
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/137

**Comment by Blackymas** [comment]
all clear now? can I close the issue?

**Comment by adri123** [comment]
Yes your answer was clear.

Thank you
-- 
adrien clément
