### ISSUE TITLE
Update to ESPHome 2022.12.7 fails

### ISSUE THREAD

**Issue by smartmatic** [Blackymas/NSPanel_HA_Blueprint#255]
I wanted to update the latest ESPHome release 2022.12.7. After compiling the upgrade has not been executed with this error message

```
INFO Reading configuration /config/esphome/nspanelbad.yaml...
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing nspanelbad (board: esp32dev; framework: arduino; platform: platformio/espressif32 @ 5.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- WiFiClientSecure @ 2.0.0
|-- HTTPClient @ 2.0.0
Compiling /data/nspanelbad/.pioenvs/nspanelbad/src/main.cpp.o
Linking /data/nspanelbad/.pioenvs/nspanelbad/firmware.elf
RAM:   [=         ]  13.3% (used 43676 bytes from 327680 bytes)
Flash: [======    ]  61.9% (used 1135285 bytes from 1835008 bytes)
Building /data/nspanelbad/.pioenvs/nspanelbad/firmware.bin
Creating esp32 image...
Successfully created esp32 image.
esp32_create_combined_bin(["/data/nspanelbad/.pioenvs/nspanelbad/firmware.bin"], ["/data/nspanelbad/.pioenvs/nspanelbad/firmware.elf"])
Wrote 0x126940 bytes to file /data/nspanelbad/.pioenvs/nspanelbad/firmware-factory.bin, ready to flash to offset 0x0
========================= [SUCCESS] Took 90.51 seconds =========================
INFO Successfully compiled program.
INFO Resolving IP address of nspanelbad.local
INFO  -> 192.168.178.24
INFO Uploading /data/nspanelbad/.pioenvs/nspanelbad/firmware.bin (1141056 bytes)
Uploading: [                                                            ] 0% 
ERROR Error sending data: [Errno 104] Connection reset by peer
```
I've restarted the panel and tried again but without success. 

Please support

**Comment by danwright87** [comment]
This appears to be an esphome issue rather than something with this project. Only suggestions I can make are:
Upload via the web portal of the device
Or
Upload via serial

**Comment by deejaybeam** [comment]
I know this issue - this happend on poor WLAN - I have exchanged my whole WLAN equipent to UNIFI what makes a big difference, no matter what signal-strength was shown. Also possible could be something you have assigned to a button with high-frequent status-updates.

**Comment by smartmatic** [comment]
> This appears to be an esphome issue rather than something with this project. Only suggestions I can make are:
> Upload via the web portal of the device
> Or
> Upload via serial

How can i login to the web portal?

**Comment by smartmatic** [comment]
> I know this issue - this happend on poor WLAN - I have exchanged my whole WLAN equipent to UNIFI what makes a big difference, no matter what signal-strength was shown. Also possible could be something you have assigned to a button with high-frequent status-updates.

Only lights are assigned to the buttons.

**Comment by danwright87** [comment]
> 

Go to the IP of the nspanel in a browse and use the OTA box at the bottom of the page

**Comment by smartmatic** [comment]
> Go to the IP of the nspanel in a browse and use the OTA box at the bottom of the page

I am asked to provide username and password

**Comment by danwright87** [comment]
User is admin, password is your WiFi password

**Comment by smartmatic** [comment]
> > This appears to be an esphome issue rather than something with this project. Only suggestions I can make are:
> > Upload via the web portal of the device
> > Or
> > Upload via serial
> 
> How can i login to the web portal?

I tried it via Web interface. But when i start the update i get some seconds later this page

![Bildschirm­foto 2023-01-27 um 08 12 29](https://user-images.githubusercontent.com/74932663/215029754-766b819f-c759-4eb4-92b0-98581c3bf478.png)

WiFi RSSI is -63. So not a bad connection.

**Comment by danwright87** [comment]
The only advise I can give is to try flash via serial, this is not an issue with the project but a networking or esphome error if the device is resetting the connection.

**Comment by smartmatic** [comment]
> The only advise I can give is to try flash via serial, this is not an issue with the project but a networking or esphome error if the device is resetting the connection.

hmm...this is not really convenient. ESPHome publishes regularly updates. Should i each time unmount the display from the wall?
And what does flashing via serial mean? After that i need to re-configure the whole device and upload nspanel.tft again?

**Comment by Blackymas** [comment]
Hallo,

auch hier noch einmal die Frage was genau ist das Problem?

Der Screen oben zeigt das es nicht durchgelaufen ist.

Das kann 2 Ursachen haben. 
1. es gab ein Problem im Netzwerk /WLAN 
2. oder das NSpanel /Esphome hatte eine Aussetzer (hatte ich auch einmal)


Man kann danach aber das Update von Esphome direkt neu anschieben.

Was sollte das Esphome Update mit dem NSPanel zu tun haben?

Wenn du die Esphome version vom NSpanel updaten willst gehst du wie folgt vor.

1. HA -> Esphome -> NSPanel Device
2. auf die 3 Punkte
3. Validate -> jetzt wird der Code geprüft. Wenn das fertig ist und alles ok ist dann siehst du über den Code einen grünen Haken. Das ist das Zeichen das der Code passt und keine Probleme im Code zu finden sind

4. du kannst dann im selben Fenster rechts unten auf Install klicken und das OTA Update startet.


Es gibt also garkeine Grund sich auf das Web Interface einloggen zu müssen - auch muss man das NSPanel nicht abbauen.


Nur wenn das NSPanel abgeschossen wurde muss du das Display abnehmen und neu flashen.


Wenn ich deine beiden Probleme so sehe - hab ich das Gefühl du hast irgendwelche Probleme im Netzwerk / WLAN bei dir.
Das kann zb auch passieren, wenn das NSPanel gerade so noch im Empfangsbereich ist. je niedriger der dbm Wert ist desto eher kann es zu einem WLAN Problem kommen.

Noch schlimmer ist es wenn zwischen drin irgendwelche Fritz!Box Repeater sitzen oder Lan via Stromverkabelung


Mit Sicherheit wird auch von uns irgendwo mal ein Bug drin sein - aber bevor das auf irgendeine Stable Version geht sind mindestens 10-12 Nspanel geupdatet wurden

**Comment by smartmatic** [comment]
@Blackymas
Danke für deine sehr ausführliche Antwort. Grundsätzlich mache ich hier keinem einen Vorwurf sondern berichte einfach, was mir passiert ist und bin dankbar, wenn geholfen wird.

Daher stelle ich auch keine Zusammenhänge her, die ich nicht belegen kann. Ich kenne daher auch nicht die optimalen Bedingungen die das NS Panel braucht um sauber zu funktionieren?

Da das NS Panel über ESPHome eingebunden wird muss man eben auch die Version updaten. Ich hatte schon mal Probleme eine zu alte ESP Version auf den neuesten Stand zu bringen. Daher mache ich das immer recht zeitnah und bin eben auf das oben genannte Problem gestoßen. 

Und ja, ich habe aufgrund der Fehlermeldungen auch schon auf WLAN getippt. Der RSSI liegt bei -63 dBm
Und ja, das NS Panel ist über einen Fritz Repeater im WLAN.

**Comment by Blackymas** [comment]
Das war auch kein Vorwurf oder ähnliches.

Es geht ja nur darum das problem mal zu lösen, weil wir ja niemand hier im regen stehen lassen wollen aber unsere zeit auch begrenzt ist ;)

Daher war es nicht böse gemeint ich hab nur mal alles nieder geschrieben.

Wir alle oder zumindest fast alle updaten Esphome - das sollte aber keine Auswirkungen auf die NSPanel oder andere Esphome gerate haben.

Wenn das so wäre würde deejaybeem Amok laufen der hat gefühlt 50 oder 60 Esphome Geräte 

-63 sollte in Ordnung sein - ich hab nur immer Bauchschmerzen mit den repeater XD


Aber zurück zum Thema was genau ist denn jetzt noch offen bzw das Problem?
Wie man die NSpanel updaten sollte hatte ich oben ja erwähnt

**Comment by smartmatic** [comment]
Der Upload bzw. das Update will einfach nicht funktionieren.

![Bildschirm­foto 2023-01-27 um 20 50 54](https://user-images.githubusercontent.com/74932663/215184388-3b17f1c1-f8b6-4c09-bbde-1dd4f19abf6e.png)

Vielleicht noch als Historie:
Ist mein erstes NS Panel und ich hatte direkt Probleme die nspanel.tft über den Weg aus der Doku zu flashen. Daniel hat mir dann im Discord ein paar Tipps gegeben. u.a Tasmota zu flashen, weil ich nicht er einzige wäre, der das Problem hat.

Das habe ich dann auch gemacht
- Tasmota geflasht
- nspanel.tft mithilfe der Tasmota Konsole geflasht 
- Zum Schluss wieder ESPHome über Firmware Update Funktion von Tasmota eingespielt

Da das Panel grundsätzlich funktioniert und konfiguriert werden kann bin ich jetzt davon ausgegangen das der Umweg beim flashen daher auch kein Problem war.

**Comment by danwright87** [comment]
You moved this panel between 2 different home assistant instances right? Can you make sure you have removed it from both home assistants and try flash again, also, if you haven't already, try restart your router / repeater

**Comment by Blackymas** [comment]
ok ich weis nicht ob da ein problem auftreten kann - ich hab noch nie mit tasmota gearbeitet.

Sieht aber fast so aus das OTA nicht geht weil da was nicht stimmt.

Ja das mit dem TFT stimmt - das lag aber an ESPhome und https. Da werden dann viele kleine Pakete geladen und wenn da irgendwas nicht passt internet oder WLAN oder die Latenzen kommt es zu problemen.

Daher hatte ich die Doku vor 3 Tagen oder so angepasst in dem ich den Link zu Github auskommentiert habe und den lokalen Pfad zu HA eingesetzt hatte.

Die Frage ist nur was da jetzt nicht geht - ich kann nur von esphome direkt sprechen.

**Comment by Blackymas** [comment]
hab gerade nochmal mit Daniel gesprochen er meinte es sollte via OTA auch bei tasmota gehen via Web interface

er hat dazu ein video gemacht
https://www.youtube.com/watch?v=6aMtzjz_DLM&list=PLtEjuZQyAkqGAvHjsM6G295CsKXetm-_Z&index=2

das OTA Passwort sollte das Wifi Kennwort sein außer du hast eine version ganz am Anfang gehabt da gab es noch einen extra Punkt für OTA passwort

bin mir jetzt nicht sicher was der beste weg ist - den du gehen solltest.

Ich würde wahrscheinlich nochmal den flash neu machen aber dann alles direkt via esphome (davor nochmal alles löschen Automation, HA device, esphome Device)


und wenn du es nur anlegst dann den neuen Esphome Code nehmen und das TFT File in HA im Ordner www ablegen

**Comment by smartmatic** [comment]
@Blackymas 
Vielen Dank für die ganzen Tipps. Ich versuche die jetzt abzuarbeiten. Schaue beobachte gerade mal das WLAN Verhalten. Ich weiss Fritz ist nicht mehr State-of-the-Art aber komme ich ad-hoc nicht weg von. Es ist leider ein Mega Krampf unter Fritz ein gerät z.b fest dem Router zuzuweisen. Ich sehe schon, dass das Panel zwischen Repeater und Router springt, und das scheinbar sehr oft :-(

**Comment by Blackymas** [comment]
Mach dir kein Kopf wie ich schon gesagt habe es gibt keine doofen Fragen.

Wenn das so springt kann dann durchaus das Problem sein.

**Comment by danielscheidler** [comment]
Das Springen zwischen router und repeater kannst du ganz einfach mit dem parameter "bssid" im esphome code verhindern (Als Wert die Mac des AP wo er drauf connecten soll)

`wifi:
  networks:
    - ssid: !secret WLanSSID
      password: !secret WLanPassword
      bssid: E8:AF:30:22:46:AB`

**Comment by Blackymas** [comment]
Danke Daniel guter Hinweis dann muss er aber den ganzen esphome Code einsetzen - wäre glaub einfacher wenn es die fritzbox könnte

**Comment by smartmatic** [comment]
@

> Das Springen zwischen router und repeater kannst du ganz einfach mit dem parameter "bssid" im esphome code verhindern (Als Wert die Mac des AP wo er drauf connecten soll)
> 
> ```
> wifi:
>   networks:
>     - ssid: !secret WLanSSID
>       password: !secret WLanPassword
>       bssid: E8:AF:30:22:46:AB
> ```

Danke Daniel, guter Tipp. Dazu muss ich aber auch ein Update auf das Panel bekommen woran es gerade hackt. Habe jetzt mal einen Repeater weg genommen sodass das Panel sich hoffentlich mal für eine paar Minuten mit dem Router verbindet.

**Comment by smartmatic** [comment]
Keine Chance, auch jetzt ohne Repeater wo das Panel direkt mit dem Router verbunden ist erhalte ich den obigen Fehler:
Errno 104
RSSI ist bei -78

**Comment by Blackymas** [comment]
Du wirst um das neu flashen noch drum herum kommen

**Comment by danielscheidler** [comment]
> Danke Daniel guter Hinweis dann muss er aber den ganzen esphome Code einsetzen - wäre glaub einfacher wenn es die fritzbox könnte

warum den ganzen code? das wird intern gemerged insofern gilt, lokales überschreibt den inhalt der packages. Rest kommt weiterhin aus dem Package. So hab ich zb auch immer deine ota-Passwortlogik überschrieben weil ich für ota nicht meinen wifi key nutze

**Comment by danielscheidler** [comment]
> Keine Chance, auch jetzt ohne Repeater wo das Panel direkt mit dem Router verbunden ist erhalte ich den obigen Fehler: Errno 104 RSSI ist bei -78

Zur Not halt schnell mal eben den ftdi ans panel und esphome drauf bügeln

**Comment by smartmatic** [comment]
Also einmal alles neu gemacht ohne Repeater und in der ESP YAML nun die bssid konfiguriert damit das Panel sich immer mit dem Router verbindet. Hat im Prinzip alles auf Anhieb geklappt diesmal. 

Wo ich überrascht war, dass der letzte Schritt, das TFT Display zu updaten fast abgeschlossen war als ich den Switch im Device betätigt habe. Da war der Flash Vorgang schon zu 94% abgeschlossen. 
Läuft das automatisch im Hintergrund los?

Vielen Dank euch beiden!

**Comment by danielscheidler** [comment]
Ich dachte die TFT ist drauf? Die musst du dann nicht neu flashen. Wenn er
bei >0% startet hat der upload nicht funktioniert.

smartmatic ***@***.***> schrieb am Fr., 27. Jan. 2023, 23:50:

**Comment by smartmatic** [comment]
Ich hatte alles platte gemacht (erase)

**Comment by danielscheidler** [comment]
> Ich hatte alles platt gemacht (erase)

erase löscht den esp speicher, nicht die tft vom nexion

**Comment by smartmatic** [comment]
ah, stimmt, denkfehler, dann erklärt es das

**Comment by Blackymas** [comment]
genau und ist das TFt einmal drauf beginnt das immer bei 94 oder so - nur wenn wir große änderungen wie Bilder etc hinzufügen Flash es wieder von 0 und dauert dann ca 10 min

heißt also läuft jetzt? Dann mach ich mir ein Bier auf ;)

**Comment by smartmatic** [comment]
Ja schaut gut aus :-) Danke!!! 
Prost...

War das jetzt richtig hier zu besprechen oder ist  Discord doch der bessere Channel?

**Comment by Blackymas** [comment]
nein alles ok - hatte nur Daniel mal angehauen hier Krücken rein zu schauen.

Du kannst aber auch gern discord nutzen - es kommt halt drauf an wenn es so ein langes Thema ist hat man hier den Vorteil das nichts verloren geht aber Discord vom Daniel wird es vllt schneller eine Antwort geben.

Aber @danielscheidler ist ja echt auf zack - war auch mein Lehrer bzw ist es immer noch hahaha.


Gut dann mach ich mir mal ein bier auf und vllt springt ja noch eine Donation von dir raus für den Support und die NSpanel version ;P

viel Spaß damit

**Comment by smartmatic** [comment]
Was ist dir lieber Donation oder ein Youtube Video ;-)

**Comment by Blackymas** [comment]
> Was ist dir lieber Donation oder ein Youtube Video ;-)

haha natürlich beides oder hast du eine andere Antwort erwartet ;P

Past doch auch ;)
support -> Donation
NSPanel Version -> Video

Ne Spaß - deine freie Entscheidung. Wir freuen uns über jede Unterstützung!

ps. hab erst jetzt mitbekommen wer du bist - der man mit dem Hut ;) 
Hab schon paar Video von dir angeschaut. Mir kam auch das Logo bekannt vor - aber der Name nicht ;)

**Comment by Blackymas** [comment]
solltest du ein Video machen was wirklich toll wäre lass es mich wissen - ich pack es mit ins wiki zu unserer Seite "Videos"

das ist ja auch ein nehmen und geben ;) wir verlinken gerne

**Comment by smartmatic** [comment]
Ja, mache ich sehr gerne und unterstütze das Projekt! Auf meinem Blog habe ich gestern auch schon einen Artikel veröffentlicht. Bin aber natürlich vorsichtig mit dem, was ich Poste, weil es schon auf Fakten basieren soll und ich gerade erst Anfange mit den Panel und dem Blueprint Erfahrungen zu sammeln.

Damit sich das Video etwas abhebt von denen die es schon gibt würde ich gerne etwas zeigen, was bisher noch nicht gezeigt wurde. Dann bietet es den Zuschauern einen Mehrwert. Da bietet sich zb die nächste Version mit neuen Features / Funktionen an.

Kannst du sagen, wann die etwa kommen wird? Oder hast du noch eine andere Idee was verfilmt werden sollte?

**Comment by Blackymas** [comment]
wir haben gestern nacht die erste dev version online gebracht für uns intern zum testen sah ganz gut aus müssen das aber auch noch durchtesten vllt 1 wochen ca

**Comment by Blackymas** [comment]
ich würde aber das issue schließen du kannst im Bereich discussion ein Post aufmachen zu dem Thema mit dem Video - da passt es besser rein ;) 

Magier mich dann einfach

**Comment by Blackymas** [comment]
@smartmatic version 3.1.0 ist online 😄

**Comment by smartmatic** [comment]
@Blackymas 👍🏻
Funktioniert der Blueprint auch mit einem NS Panel Pro?

**Comment by Blackymas** [comment]
@smartmatic nein das benutzt android
