### ISSUE TITLE
Light settings card - light capabilities

### ISSUE THREAD

**Issue by ghost** [Blackymas/NSPanel_HA_Blueprint#256]
Light settings shows all capabilities, should hide the ones not supported by the light.

E.g some adjustable temperature while bulbs also show colour palette on page.

**Comment by Blackymas** [comment]
not sure but I think it is not so easy - we will see

**Comment by danwright87** [comment]
We can read that from HA, I've got a few ideas I'll explore that can be done all in blueprint

**Comment by ajvdw** [comment]
Can you also add a grayed out picture when an entity is not available? Now it's hidden. I have some physical light switches that switch smart bulbs......

**Comment by Blackymas** [comment]
> Can you also add a grayed out picture when an entity is not available? Now it's hidden. I have some physical light switches that switch smart bulbs......

like for example in HomeKit with "not available"?

**Comment by ajvdw** [comment]
> > Can you also add a grayed out picture when an entity is not available? Now it's hidden. I have some physical light switches that switch smart bulbs......
> 
> like for example in HomeKit with "not available"?

I wouldn't change the label to not available. I'd like to now which switch is unavailable.

**Comment by Blackymas** [comment]
topic: grayed out

->

Is changed in v3.2 
Please update and test :)

https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.2
