### ISSUE TITLE
Encryption Key to add Integration

### ISSUE THREAD

**Issue by lennartschulte** [Blackymas/NSPanel_HA_Blueprint#257]
Shorted English Version below.

Nachdem es mit meinem Pi4 nicht geklappt hat den Build zu erstellen habe ich mit einer HA-Instanz mit ESPHome in einer VirtualBox schließlich die Firmware erstellen können. Der Upload lief dann mehr oder weniger ohne Probleme. Nach dem Zusammenbau ist das Panel auf als neue ESPHome Integration erkannt worden.

<img width="277" alt="image" src="https://user-images.githubusercontent.com/89683004/215050910-36115695-669c-4099-abc5-623e686946b4.png">

Beim Hinzufügen der Integration wird nun aber leider nach einem Verschlüsselungsschlüssel gefragt. 

<img width="502" alt="image" src="https://user-images.githubusercontent.com/89683004/215050809-4b854215-a453-4163-8fa7-aa7ffa2eb071.png">

Ich habe aber selbst keinen definiert und kann das Panel daher nicht hinzufügen. Weder bei der HA-Instanz auf dem Pi4, noch auf der virtuellen Maschine.

<img width="518" alt="image" src="https://user-images.githubusercontent.com/89683004/215051256-f5fe1431-99cd-4e1e-89da-e4e3c7b8be3c.png">

Ich habe bereits versucht eine neue Firmware mit api encryption key auf das Panel zu spielen, jedoch kann der Adapter jetzt keine Verbindung mehr zum Panel aufbauen. Das könnte aber daran liegen, dass die Kabel nur gesteckt/gehalten werden und nicht gelötet sind.

Muss ich jetzt schauen, dass ich irgendwie eine neue Firmware aufspiele oder kann ich die Abfrage des Keys beim Hinzufügen der Integration irgendwie umgehen? Ich habe auf der virtuellen Umgebung natürlich die gleichen Secrets (inkl. API Passwort) wie auf der Produktiven Instanz.

ESPHome Version: 2022.12.8
Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.4
Frontend 20230110.0 - latest

Vielen Dank vorab für die Hilfe

____________________________
After finally compiling the firmware on a virtual machine, HA now recognizes the panel as new ESPHome integration. When I now try to add the panel to HA it asks me for an encryption key which has not been defined by me in the configuration. What can I do to solve this issue? I'm struggling a bit with the physical connection to the panel when I try to flash a new firmware with a defined encryption key, but I wonder if this is at all necessary.

Thanks in advance.

**Comment by deejaybeam** [comment]
Hi
Wir haben in unserem Projekt keinen encryption-key vorgesehen.
Einzig ein api-passwort kann manuell durch anpassen der esphome.yaml angegeben werden.
Was du versuchen kannst ist im esphome-dashboard beim device auf die drei Punke klicken, dort gibt es dann den Eintrag "Show API Key"
![image](https://user-images.githubusercontent.com/10434729/215054525-237cbd5c-f4cf-4691-9c8b-d97825a1e663.png)

**Comment by lennartschulte** [comment]
Das habe ich so auch im Quellcode gesehen, jedoch hat mich HA dennoch danach gefragt. Kein Plan warum. Vielleicht User-Fehler ;-) Unter "Show API-Key" ist leider nichts passiert. Ich habe jetzt manuell eine Firmware mit API encryption key flashen können. Nach der Eingabe des Key hat es dann geklappt. Bin jetzt bei den nächsten steps im Prozess und hoffe, ich muss dich nicht weiter belästigen. Vielen Dank aber für den Support bisher und die Arbeit in dem Projekt.

**Comment by deejaybeam** [comment]
Zumindest ist es kein Problem in diesem Projekt, sondern scheinbar mit esphome selbst (google-suche):
https://community.home-assistant.io/t/esphome-encryption-key-is-invalid/424757/20
Hier wird unter anderem darauf hingewiesen ggf. das device erneut per "serial" zu flashen über web.esphome (oder sonstigem tool) mit der option/möglichkeit den speicher am device zu löschen

**Comment by lennartschulte** [comment]
Das stimmt. Vielen Dank nochmals. Es funktioniert jetzt alles. Echt eine geile Arbeit vom Team

**Comment by sabixx** [comment]
Hi, @lennartschulte, 

ich habe dasselbe Verhalten. Hast Du das Panel nochmal ausgebaut und seriel geflasht? Wenn möglich würde ich das gefummel gerne vermeiden.

thx

**Comment by lennartschulte** [comment]
Ich bin mir ehrlich nicht sicher. Ist schon so lange her und ich habe damals alles mögliche gemacht. Ich kann dir nur empfehlen ein Ticket zu öffnen. Mir wurde dabei immer schnell und kompetent geholfen.

Letztlich musst du aber natürlich auch selbst Durchhaltevermögen mitbringen. Ist halt ein DIY Projekt.
