### ISSUE TITLE
Accuweather Empty pages

### ISSUE THREAD

**Issue by Churator** [Blackymas/NSPanel_HA_Blueprint#258]
Integration to AccuWeather show the weather for today in main screen, but subpages of forecast are empty.
![image](https://user-images.githubusercontent.com/62523824/215092453-1408db61-3130-4669-bbc4-4f50deb50a8f.png)

**Comment by danwright87** [comment]
Hi, this is a HA / AccuWeather issue. Go into the AccuWeather integration and enable forecasts.

Thanks

**Comment by Churator** [comment]
Enabled already
![image](https://user-images.githubusercontent.com/62523824/215093099-74e8678f-6045-4e8d-843c-792d9b98ddc4.png)


> Hi, this is a HA / AccuWeather issue. Go into the AccuWeather integration and enable forecasts.
> 
> Thanks

**Comment by danwright87** [comment]
Can you post a developer tools entities list for 'weather'

**Comment by Churator** [comment]
Snipping some since its long list (109 entities), enough ?
![image](https://user-images.githubusercontent.com/62523824/215093879-bdebd423-58ac-47a7-981e-a992c97582f2.png)

**Comment by danwright87** [comment]
Can you show your main weather entity too and post the integration config. Thanks

**Comment by Churator** [comment]
![image](https://user-images.githubusercontent.com/62523824/215094958-dc273f36-4755-4db5-b7f9-1a44c99fa8d2.png)



alias: NSPanel Configuration
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: nsplr
    language: ENG
    weather: AccuWeather
    weather_entity: weather.accuweather_accuweather
    outdoortemp: sensor.sensor1_temperature
    indoortemp: sensor.nsplr_temperature
    humidity: sensor.sensor1_humidity
    climate: climate.underfloorlivingroom
    button_page01_label: Lights
    entity01: light.front_outside_lights
    entity02: light.side_outside_lights
    entity01_name: Front
    entity02_name: Sidewalk
    entity03: light.entrance_light
    entity03_name: Enterance
    entity09: cover.roller_shutter_7
    entity09_name: Parents North

**Comment by Churator** [comment]
weather.home works, but it's not based on Accuweather.

**Comment by danwright87** [comment]
Weather.home doesn't contain all the extra details, that only comes in from AccuWeather, the data should be from AccuWeather. I'm not Infront of HA now so can't check

**Comment by Churator** [comment]
So choose AccuWeather in the options but entite weather.home ?
Configured and reboot, same. Just Icon no data in forecast

**Comment by danwright87** [comment]
At the bottom of weather.home in developer tools states  it should say weather data provided by AccuWeather?

**Comment by danwright87** [comment]
Make sure you don't have the default weather integration enabled too in HA

**Comment by Churator** [comment]
I have both now.
Delete the weather.home?

**Comment by danwright87** [comment]
Yes, I'd delete both, re add AccuWeather and enable it's forecasts. Update automation and restart panel

**Comment by Churator** [comment]
> 

Nope. met.no
attribution: Weather forecast from met.no, delivered by the Norwegian Meteorological Institute.

**Comment by Blackymas** [comment]
![Bildschirmfoto 2023-01-27 um 20 02 08](https://user-images.githubusercontent.com/41958506/215173269-a7dae884-d4f8-4c1b-b4e6-b7be48db22d5.png)

The configuration should look like this in the blueprint

After the change you should please restart the NSPanel. Only when restarting all services etc. are restarted.

Only from version 3.1.0 no more reboot is necessary.

If this still does not work, check the trace of the automation directly after you have clicked on the weather icon.

And look for this column.

In the right window you should be able to read something about Weather Forcast.

Check here if all icons are orange - if not, the automation will be aborted before.
![Bildschirmfoto 2023-01-27 um 20 04 43](https://user-images.githubusercontent.com/41958506/215174152-8c0a5fc4-33ae-4804-a60a-5dbe02fbd860.png)

**Comment by Churator** [comment]
You suggestion 

> ![Bildschirmfoto 2023-01-27 um 20 02 08](https://user-images.githubusercontent.com/41958506/215173269-a7dae884-d4f8-4c1b-b4e6-b7be48db22d5.png)
> 
> The configuration should look like this in the blueprint
> 
> After the change you should please restart the NSPanel. Only when restarting all services etc. are restarted.
> 
> Only from version 3.1.0 no more reboot is necessary.
> 
> If this still does not work, check the trace of the automation directly after you have clicked on the weather icon.
> 
> And look for this column.
> 
> In the right window you should be able to read something about Weather Forcast.
> 
> Check here if all icons are orange - if not, the automation will be aborted before. ![Bildschirmfoto 2023-01-27 um 20 04 43](https://user-images.githubusercontent.com/41958506/215174152-8c0a5fc4-33ae-4804-a60a-5dbe02fbd860.png)

Thank you, for the amazing work and the reply.
I tried to restart; it won't solve.
Now, after I deleted the non-accuweather and accuweather, created again named weather.home and now I see
Automation configred as default and not as Accuweather.

**Comment by danwright87** [comment]
If you set the automation to AccuWeather rather then default, that's what solved mine with only having AccuWeather integration. Reboot after changing automation.

**Comment by Churator** [comment]
I just tried that now, default works but with less data. Accuweather works too, very informative. Great.
The same didn't work with both weather configured

**Comment by danwright87** [comment]
So all sorted now?

**Comment by Blackymas** [comment]
> I just tried that now, default works but with less data. Accuweather works too, very informative. Great.
> The same didn't work with both weather configured

what do you mean?

It is important that you do not assign the same names.

But they should run in parallel as they are two different services.

**Comment by Churator** [comment]
> > I just tried that now, default works but with less data. Accuweather works too, very informative. Great.
> > The same didn't work with both weather configured
> 
> what do you mean?
> 
> It is important that you do not assign the same names.
> 
> But they should run in parallel as they are two different services.

Before, when I originally posted here. I had both default original as weather.home and weather.accuweather.
When I configured the panel with Accuweather and weather.accuweather, main screen showed weather but forecast was empty pages (including restart)
After advice here, I've deleted both and created only Accuweather as home.weather.
and now I get full detailed forcast as exptected.

**Comment by danwright87** [comment]
Glad it's sorted, this is one of the guides we will be writing asap
