### ISSUE TITLE
I get errors in my log about automation

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [Blackymas/NSPanel_HA_Blueprint#260]
After doing the installation I get following errors in my log, but the panel itself seems to be fully functional 

Logger: homeassistant.components.automation.nsbathroom_configuration
Source: components/automation/__init__.py:567
Integration: Automation (documentation, issues)
First occurred: 21:28:02 (135 occurrences)
Last logged: 21:33:38

Error while executing automation automation.nsbathroom_configuration: expected int for dictionary value @ data['message']
Error while executing automation automation.nsbathroom_configuration: Template rendered invalid service:

Logger: homeassistant.components.automation.nsbathroom_configuration
Source: helpers/script.py:409
Integration: Automation (documentation, issues)
First occurred: 21:28:02 (276 occurrences)
Last logged: 21:33:38

NSBathroom Configuration: Choose at step 2: choice 7: Error executing script. Invalid data for call_service at pos 4: expected int for dictionary value @ data['message']
NSBathroom Configuration: Error executing script. Invalid data for choose at pos 2: expected int for dictionary value @ data['message']
NSBathroom Configuration: Choose at step 2: choice 8: If at step 3: Error executing script. Error for call_service at pos 1: Template rendered invalid service:
NSBathroom Configuration: Choose at step 2: choice 8: Error executing script. Error for if at pos 3: Template rendered invalid service:
NSBathroom Configuration: Error executing script. Error for choose at pos 2: Template rendered invalid service:

**Comment by danwright87** [comment]
Hi, please post your ESPHome yaml and your automation yaml to. Can you confirm you added the ESPHome automation in home assistant for this device?

**Comment by smarthomefamilyverrips** [comment]
@danwright87 

![Screenshot_20230127_231408_Home Assistant](https://user-images.githubusercontent.com/97987488/215201715-77008249-0d3a-467b-9b6a-fd2fa6dba432.jpg)

alias: NSBathroom Configuration
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: nsbathroom
    language: ENG
    weather_entity: weather.openweathermap
    outdoortemp: sensor.lumi_lumi_weather_temperature
    humidity: sensor.lumi_lumi_weather_humidity
    climate: climate.bathroom
    left_button_name: Ceiling
    right_button_name: Mirror
    right_button_entity: light.bathroom_mirror
    left_button_entity: light.light_bathroom_ceiling_local
    button_page01_label: Bathroom
    button_page02_label: Office
    button_page03_label: Living Room
    button_page04_label: Outside
    entity01: light.light_bathroom_ceiling_local
    entity01_name: Ceiling
    entity02: light.bathroom_mirror
    entity02_name: Mirror
    entity09: light.light_office_space_local
    entity09_name: Ceiling
    entity10: switch.sonoff_100121430c
    entity10_name: PC
    entity11: cover.cover_office_cover
    entity11_name: Cover
    entity17: light.living_room_lights
    entity17_name: Ceiling
    entity25: input_button.lock_front_gate
    entity25_name: Front Gate

**Comment by smarthomefamilyverrips** [comment]
@danwright87 sorry I not understand what you mean with this 
_"Can you confirm you added the ESPHome automation in home assistant for this device"_

**Comment by danwright87** [comment]
Sorry, I meant integration.
 In integrations you have to add one for ESPHome for  your bathroom

**Comment by smarthomefamilyverrips** [comment]
Yes I have the device in ESPhome in HA

![Screenshot_20230128_000849_Home Assistant](https://user-images.githubusercontent.com/97987488/215214117-2f39bbcd-dd3e-4095-be94-11be85bf11fc.jpg)

**Comment by Blackymas** [comment]
STOP XDDD

This can safely be ignored and is already fixed in dev-branch or wait for 3.1.0 stable ;)
Cause is, even if nothing is assigned to a "button-slot" the blueprint tries to execute a toggle for the (not assigned) entity.

**Comment by smarthomefamilyverrips** [comment]
@Blackymas OK danke!
