### ISSUE TITLE
Warning Message on Dev. Version of blueprint.yaml

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [Blackymas/NSPanel_HA_Blueprint#266]
@Blackymas FYI: I get the following warning message while using the dev version of the blueprint

Logger: homeassistant.helpers.service
Source: helpers/service.py:637
First occurred: 21:29:34 (34 occurrences)
Last logged: 21:42:41

Unable to find referenced entities switch.nsbathroom_relay_1_local_fallback or it is/they are currently not available
Unable to find referenced entities switch.nsbathroom_relay_2_local_fallback or it is/they are currently not available

**Comment by danwright87** [comment]
Hi, this will be because those were added in the current Dev version, you would need to update the ESPHome yaml to also be the Dev version to clear those.

**Comment by smarthomefamilyverrips** [comment]
@Blackymas where in my configuration I find the ESPHome yaml?

**Comment by danwright87** [comment]
The config file for the nspanel IN ESPHome

**Comment by smarthomefamilyverrips** [comment]
@danwright87 the one in this folder/directory 

config/esphome/.esphome/packages/566b10a3

**Comment by danwright87** [comment]
I can't speak for your particular install. It's wherever you created the yaml file in ESPHome for the nspanel.

**Comment by smarthomefamilyverrips** [comment]
@danwright87 OK thank you!
