### ISSUE TITLE
Stuck At initializing

### ISSUE THREAD

**Issue by krisztiantoth966** [Blackymas/NSPanel_HA_Blueprint#267]
Hello, i have problem with automatization 
Here is my config
nspanel added to ha 
when i call service "change screen" - its changed but  in the device no entity  
ESPHOME:
![image](https://user-images.githubusercontent.com/63956270/215287961-40a9150c-16c1-49be-969e-85055aebeb98.png)
 Automatization:
![image](https://user-images.githubusercontent.com/63956270/215288022-0ba30466-a7a0-49d3-8a25-8e3ba809a3eb.png)
![image](https://user-images.githubusercontent.com/63956270/215288055-e82623dc-5376-4494-8b88-321bf9624276.png)

**Comment by danwright87** [comment]
Hi, you have a space on the end of the name in the automation, remove that and it will work

**Comment by krisztiantoth966** [comment]
Oh, It work Thanks
