### ISSUE TITLE
Keeping load  for content

### ISSUE THREAD

**Issue by mathgameapi** [Blackymas/NSPanel_HA_Blueprint#268]
The nspanel keep show "Waiting for content". Please help. Thanks.

In esphome , nspanel is showing online status

In blueprint nspanel configuration
ESPhome Node Name : nspanel
Language for NSPanel : English
Weather Integration : AccuWeather
Weather entity from HA: XXXXXX
Left Button (Optional) : XXXXXX
Name "Left Button" (Optional) : A
Right Button (Optional) : XXXXXX
Name "Right Button" (Optional) : B

In intergation - nspanel :
i click Update TFT display. it on a short time then change back to off. the Logbook show "nspanel Update TFT display became unavailable"
 
Esphome config
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel" 
  wifi_ssid: "XXXX"
  wifi_password: "XXXX?"

  #nextion_update_url: "http://192.168.11.113:8123/local/nspanel.tft" # URL to local tft File
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft" # URL to Github

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

**Comment by danw87** [comment]
Pleas can you post a picture of the "waiting for content" message and also the output from the ESPHome log when you try to update. 

The TFT update going back to off and then nspanel disconnecting is normal behaviour for a TFT update.

**Comment by deejaybeam** [comment]
Hi, I´m pretty shure your have previously installeld lovelace-ui.
Waiting for content is a message of the lovelace-ui TFT.
So that means you have not installed the required tft from this project.

**Comment by mathgameapi** [comment]
> Hi, I´m pretty shure your have previously installeld lovelace-ui. Waiting for content is a message of the lovelace-ui TFT. So that means you have not installed the required tft from this project.

Yes, you are right.
I had installed lovelace-ui before.
I follow the following steps. i flashed the nspanel with esphome. then run following command. i got " Reading from UART timed out at byte 0!" and " upgraded failed."

The following steps are necessary:
1. download the file "nspanel_blank.tft" from the folder custom_configuration.
2. now upload the TFT file "nspanel_blank.tft" to the folder "www" in Home Assistant
3. now go to the item "Developer tools --> Services" and search there for the services  
4. "ESPHome: DEVICE_NAME_upload_tft" --> (esphome.device_name_upload_tft)
under URL you have to enter the path to your file nspanel_blank.tft. This could look like this "http://IP_HOME_ASSISTANT:8123/local/nspanel_blank.tft"
5.now the TFT file should be played on the NSPanel. It may take a moment until it is ready
6.If everything worked, you should see only a white page on the NSPanel.
7.now you can continue with the setup and configuration of my version. For this see [Short version of the setup of Esphome and Blueprint](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-First-Steps---Installation-and-Setup#1-short-version-of-the-setup-of-esphome-and-blueprint)

I would like to know which part have some mistrake? Thanks.

**Comment by danw87** [comment]
Please post the log output from ESPHome while trying the upload as previously requested

**Comment by mathgameapi** [comment]
> Please post the log output from ESPHome while trying the upload as previously requested

I would like to confirm the step.

Now the nspanel is flashed in lovelace-ui.
The next step is flash to esphome or run the nspanel_blank.tft in tasmota console.

Thanks

**Comment by Blackymas** [comment]
first blank tft flashes. If you have a white page on the nspanel you can start with the esphome flash

**Comment by mathgameapi** [comment]
> first blank tft flashes. If you have a white page on the nspanel you can start with the esphome flash

Thank for your reply.
I will try again.
Before i flash tft in tasmota console it got white screen say model
Not match.
Then i flash esphome. I got waiting for content. I will try again. Thx

**Comment by mathgameapi** [comment]
> first blank tft flashes. If you have a white page on the nspanel you can start with the esphome flash

Sorry i would like to ask something more.
If i flashed the tasmota with Lovelace ui

i cannot find the "ESPHome: DEVICE_NAME_upload_tft" in developer- services
i can use "FlashNextion http://192.168.11.113/local/nspanel_blank.tft" instead of call "ESPHome: DEVICE_NAME_upload_tft"?

thanks

**Comment by Blackymas** [comment]
than you need to flash blank tft with tasiota or install Lovelace ui esphome

**Comment by Blackymas** [comment]
look at the issues times there are some posts about it.

in the release notes 3.1.0 I have also linked some contributions
