### ISSUE TITLE
Events in logbook

### ISSUE THREAD

**Issue by rploeg** [Blackymas/NSPanel_HA_Blueprint#269]
Hi,

I have 3 devices now connect to my HA. I see in my logbook almost every 2 or 3 seconds a log of the automation of the NSpanel blueprint. Is this needed? 

The software is working great!

**Comment by Blackymas** [comment]
The logbook records everything that happens.

Therefore, the correct is triggered for reason X an automation is displayed in the logbook

you can exclude it - have a look here

https://www.home-assistant.io/integrations/logbook/

**Comment by synack666** [comment]
logbook:
  exclude:
    entities:
      - automation.nspanel_configuration

**Comment by Blackymas** [comment]
perfekt ;)
