### ISSUE TITLE
after NSpanel burn I get "an error occured. Improv WiFi Serial not detected" and no power on

### ISSUE THREAD

**Issue by 6254sagebrush** [Blackymas/NSPanel_HA_Blueprint#274]
I burn the US version of the NSpanel. I get Congratulation and press OK.
after I get "an error occured. Improv WiFi Serial not detected"" message.
I try to connect the 5V+GND and the device does not wake up.

**Comment by danw87** [comment]
Please can you post a screenshot / picture of the error? Thanks

**Comment by deejaybeam** [comment]
improv WiFi Serial is not implementet - so this message is the truth.
The problem is, to use this, you have to power the panel from your ftdi-adapter (or external) with 5v AND keep 3.3 serial-connection and boot up the device. But this was to risky an complex for us, so we decided to not make this - and this is also not neccesary because you have to set Wifi-Credentials in esphome-file.
This option would only make sense if e.g. we would ship a compiled firmware where you have to set your WiFi-Credentials into existing esphome.bin via serial.

**Comment by 6254sagebrush** [comment]
IC. the problem I wrote it. because I follow the guidelines and reched till the part it says "congratulations" and I saw before that the precentage goes up. once I disconnect the dongle and connect only GND+5V it does not come up (power up). could be the US version needs different flashing ?

**Comment by deejaybeam** [comment]
> IC. the problem I wrote it. because I follow the guidelines and reched till the part it says "congratulations" and I saw before that the precentage goes up. once I disconnect the dongle and connect only GND+5V it does not come up (power up). could be the US version needs different flashing ?

Please use the original backplate to power up the device.
Most ftdi adapters don´t have enogh power to operate the display in running mode.
Additional also with 5v power-supply I had issues flashing the display!

**Comment by 6254sagebrush** [comment]
> > IC. the problem I wrote it. because I follow the guidelines and reched till the part it says "congratulations" and I saw before that the precentage goes up. once I disconnect the dongle and connect only GND+5V it does not come up (power up). could be the US version needs different flashing ?
> 
> Please use the original backplate to power up the device. Most ftdi adapters don´t have enogh power to operate the display in running mode. Additional also with 5v power-supply I had issues flashing the display!

OK Thanks will connect to real power and try. thanks

**Comment by 6254sagebrush** [comment]
I tried connecting to the power and it does not wake up.
anyone used the US panel version ? maybe I need different firmware usage ?
