### ISSUE TITLE
Add Chinese support

### ISSUE THREAD

**Issue by nijez** [Blackymas/NSPanel_HA_Blueprint#276]
Monday        =  星期一
Tuesday        =  星期二
Wednesday   =  星期三
Thursday       =  星期四
Friday            =  星期五
Saturday       =  星期六
Sunday         =  星期天
Today            =  今天
Tomorrow     =  明天
in 2 Days      =  在 2 天之内
in 3 Days      =  在 3 天之内
in 4 Days      =  在 4 天之内
on                =  打开
off                =  关闭
heat             =  加热

**Comment by Blackymas** [comment]
Thanks - I need to check if the characters are in the font - or have you already tried?

**Comment by nijez** [comment]
> Thanks - I need to check if the characters are in the font - or have you already tried?

I found that the added Simplified Chinese cannot be displayed

**Comment by Blackymas** [comment]
yes the characters are not in the font - i need to check what i can do and how big the fonts will be then

**Comment by nijez** [comment]
https://github.com/joBr99/nspanel-lovelace-ui 
It seems to have Chinese support

**Comment by Blackymas** [comment]
Is changed in v3.2 
Please update and test :)

**Comment by edwardtfn** [comment]
[Chinese, Japanese and Korean (CJK) languages - We need help with translations · Blackymas/NSPanel_HA_Blueprint · Discussion #1447 (github.com)](https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1447)

**Comment by edwardtfn** [comment]
- #1556
