### ISSUE TITLE
Possible to have buttons show current status of a room's lights or tv's

### ISSUE THREAD

**Issue by larastafarian** [Blackymas/NSPanel_HA_Blueprint#290]
Hi is it possible for buttons to show current status of a room's lights or tv's that may be on for example?

**Comment by larastafarian** [comment]
I should clarify i have some single zigbee sonoff relays controlling 1 room so that showns status as on off. However i have other rooms with multiple philips hue bulbs - i cannot select an item in  the blueprint which gives the option of showing these rooms status with many hue lamps or bulbs

**Comment by deejaybeam** [comment]
Short answer: you can assign all supported "ha-domains" like light, switch, .... to a button - it´s documented in the blueprint where you select you enties.
Long answer; If I understand your question correct, you are talking about groups (of lights?).
In ha you can create a helper entity e.g. for lights, assign all lights to this group and this object is also exposed with the correct "ha-domin" (e.g. light).
BUT if you are talking about zigbee lights, it is highly recomended to create a zigbee group and bind your lamps to this group!
This avoids a "shit-storm" in your zigbee network: if you have e.g. 12 bulbs in a ha-group an turn the light (group) on/off then the command is send to each individual device (12 commands) if you have a zigbee-group and bound your lamps to this group, then only one command is send to the group.
This is at least possible with ZHA - I don´t know the hue integration...

Last but not least you can create a (template) sensor in HA and assign your devices there.
Till now binary_sensors are alredy supported for buttons, but with v3.1.x 32 entities (sensors) can also be assigned to the new entity-pages.

**Comment by larastafarian** [comment]
Hi Thanks,

The helper suggestion works great
