### ISSUE TITLE
I cant update TFT after flashing

### ISSUE THREAD

**Issue by sbminer123** [Blackymas/NSPanel_HA_Blueprint#291]
I have flashed my panel with ESPhome
Most of the functionality is working but when i try and update tft it just crashed? any help would be appreciated!

**Comment by Blackymas** [comment]
hi have a look here pls -you will find a solution

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues?q=is%3Aissue+tft+is%3Aclosed

**Comment by Blackymas** [comment]
Closing the Issue. Because there are enough contributions to it.

In the Release Notes 3.1.0 I have also posted a few links to explanations and help.
