### ISSUE TITLE
Allow play of a RTTTL sound on panel speaker

### ISSUE THREAD

**Issue by lecrams** [Blackymas/NSPanel_HA_Blueprint#292]
Would be nice if a RTTTL file or string can be played on the speaker. There are several use cases for that in combination with the new assist function of HA.

Without knowing the details of assist the use of the microphone could also be useful

**Comment by deejaybeam** [comment]
Playing sound is imlemented since 3.0.0
https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.0.0

But there is no microphone

**Comment by lecrams** [comment]
okay thx for that. 
No microphone, does that mean not supported or not available in the HW

**Comment by Blackymas** [comment]
NSPanel doesn't have a microphone.
