### ISSUE TITLE
Controll screen state

### ISSUE THREAD

**Issue by jjnj023** [Blackymas/NSPanel_HA_Blueprint#296]
Currently you can set the screen brightness and sleep functionality.
However for automation these options seems a little limited.

In my situation I would like to use them as the following:
- During the day I would like to keep te screens on at all time with a reasonable high dim setting.
- During the evening I would like to keep te screen on at all time with a lower dim setting.
- When going to bed I would like to set the sleep mode on.

The next day I would like to follow the pattern again. Currently there is no way to let te screen turn on automatically from sleep. I'm able to disable the sleep state of the screen and screen brightness. However the screen will stay blank (you can actually see the screen light up, but no UI is displayed). The only option I found so far is to reboot the device. This isn't the nicest solution and I hope a solution can be integrated

Edit: I think it currently can be done by sending call page commands.

**Comment by cristiancundari** [comment]
From home assistant you can make an automation that calls the service "ESPHome: nspanel_send_command_printf" with **cmd** "page home" giving the conditions you want.
The sleep mode simply jumps to the "screensaver" page after about one minute from the last touch event. So disabling the sleep mode simply stops the timer but the page will not be changed.
See https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/99#issuecomment-1345538330

**Comment by Blackymas** [comment]
@cristiancundari has described perfectly how you can proceed
