### ISSUE TITLE
Entity card character limit?

### ISSUE THREAD

**Issue by neuhausf** [Blackymas/NSPanel_HA_Blueprint#300]
Thanks for the great blueprint!
In version 3.1.0 there are the entity-cards. I wanted to display temperature and humidity together. There seems to be enough space, but half is cut off. Is there a character limit? Can I configure it?
<img width="494" alt="image" src="https://user-images.githubusercontent.com/7963239/216830974-bbe67925-b534-4ddf-b838-3d4159f61218.png">

**Comment by cristiancundari** [comment]
Yes, on the tft there is a max limit of 10 bytes. You can download _nextion editor_ and edit increase that value to 15, then save the new tft and upload it to the nspanel

**Comment by neuhausf** [comment]
Thank you for the hint! I will try it.
Btw: any reason for the limitation, or could this something for the next release?

**Comment by Blackymas** [comment]
hi,

Yes there is a reason for the limit

1. you do not need more in most cases

2. there is not more space on the display

**Comment by neuhausf** [comment]
@Blackymas so you mean its useless if I try?
What do you mean by „space“? Memory or pixels?

**Comment by Blackymas** [comment]
more character also means that more memory is used.

But the main reason is the space on the page. 

This means that you have to make one field smaller so that another can become larger.

We have decided for the best middle way

<img width="454" alt="Bildschirmfoto 2023-02-05 um 21 10 55" src="https://user-images.githubusercontent.com/41958506/216842416-431d7d85-5ff9-4cba-88de-b384301f4cd3.png">

**Comment by neuhausf** [comment]
I think we could optimize the space a bit:
- center the values
- use 16 chars
- use about 160px for the value

This still leaves plenty of space for the label. What do you think?

<img width="355" alt="image" src="https://user-images.githubusercontent.com/7963239/216910350-a6d63a33-ad54-4a38-bd4c-d335702db56d.png">

**Comment by Blackymas** [comment]
Yes, it just depends with me the cables are usually very long.

Best you created under discussion -> Poll a survey about it. If more people are for it, we build it around 😄
