### ISSUE TITLE
Screen is in Idle Mode while Notification is in Progress

### ISSUE THREAD

**Issue by Tauebenuss** [Blackymas/NSPanel_HA_Blueprint#301]
Version 3.1.0 

If the Screen is in Sleep and a notification comes in, the Screen keep the brightness level from the sleep mode. 

Expected Behaviour: 
Screen Brightness goes to default Value. 

Reproduce: 
- Hands off for a cuple of seconds, 
- Screen goes in Idle Mode
- Send Notification with : ESPHome: xyz_notification_show
- Reproduced. 
-

**Comment by Blackymas** [comment]
Hello,

yes, we know that - currently the sleep mode is a real "sleep mode" it was not the goal now that the display turns on but only wakes up with a touch on the display.

There are several scenarios where it is not desired - we need to see if we can bring both worlds together.

**Comment by Blackymas** [comment]
I close the issue because is duplicate

See here:
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/211
