### ISSUE TITLE
Notification delay

### ISSUE THREAD

**Issue by barbuuu** [Blackymas/NSPanel_HA_Blueprint#302]
Hi guys,

Once again amazing job with this last version made!!!
Based on my needs to send custom notification from HA to NSPanel, I duplicate on HMI the notification page, I added a new button on between Accept and Clear as global with Send component ID on touch, I added additional service called notification_show2 and below code into ESPHome yaml under the binary_sensor statement:
  - platform: nextion
    page_id: 22 #new page created as copy of notification page
    component_id: 14 #id of the added button
    id: b0 #HMI name of the button
    on_press:
      then:
        - homeassistant.service:
            service: switch.toggle
            data:
              entity_id: switch.entry #existing switch that open the entry door

So with my code based on some simple automation (when someone ring at the entry door) , HA is sending message to NSPanel via notification_show2 giving me the option to unlock the door by pressing b0 and it WORKS.

Now the problem: Notification stay on the screen only for 10 seconds and then go as notification unread with the red icon on home screen. If I check back the notification, I do not have any more the button b0 because this time the panel is calling "notification" page instead my custom page. This is super OK avoiding to unlock the door after too long. My only problem is that I want the notification to be displayed for more than 10 seconds.... like 60 seconds. Where should I change the code for the time that the notification remain on screen? I suppose into blueprint code but there I did not find the right one.... Can you please help me?

P.S. If you are interested I can share more details regarding my "invented" "feature" #125 

Thanks once again!
Dan

**Comment by Blackymas** [comment]
Best way is create a new page in hmi with the name door.

then you add the page name here at the exceptions


```
### Script for page_timer
script:
  - id: page_timer
    mode: restart
    parameters:
      delay: int
    then:
      - lambda: ESP_LOGD("nspanel", "start page-timer delay %i", int(id(page_timeout).state));
      - delay: !lambda return delay *1000;
      - lambda: |-
          if (id(disp1_currentpage).state == "home" or id(disp1_currentpage).state == "screensaver" or id(disp1_currentpage).state == "boot" or int(id(page_timeout).state) == 0) {
            ESP_LOGD("nspanel", "no page-jump");
          } else {
            ESP_LOGD("nspanel", "timer->home");
            id(disp1).send_command_printf("page 0");
          }
```
 
 
 important is to rename the value in the fields
 currentpage
 touchevent
 page -> preinitialize, touchpress, touchrelease
 
 
![Bildschirmfoto 2023-02-05 um 22 45 35](https://user-images.githubusercontent.com/41958506/216847901-5d215bdc-cdb6-4b05-8de4-59d46a404d07.png)

**Comment by deejaybeam** [comment]
or, you can just simpy change the page-timout in the device settings from (default 10s) to 60s

**Comment by barbuuu** [comment]
Thanks guys for help! @deejaybeam is funny how simple could be some time...I totaly ignored the page timeout setting on device page....

**Comment by Blackymas** [comment]
In assumed that you have done that and want it only for a specific page.
Page timeout affects all pages but that's what we built it for.

Anyway you got a solution for both issues 😄
