### ISSUE TITLE
QR for WiFi - How to do it - NOT AN ISSUE :)

### ISSUE THREAD

**Issue by barbuuu** [Blackymas/NSPanel_HA_Blueprint#303]
If you want to display QR code representing your WiFi credentials for visitors, then you have to add this line into blueprint "QR Code content" field:
WIFI:S:{yourssid};T:{encriptiontype};P:{yourwifipass};;

example: for SSID: DAN with Encription Type: WPA2 with Wifi password: secret123
WIFI:S:DAN;T:WPA2;P:secret123;;

Enjoy! and don't forgot to Activate the QR Code on the Blueprint :)

**Comment by Blackymas** [comment]
@barbuuu 
thanks for sharing the information.

The perfect place would be under discussions and maybe under show and tell

https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions

**Comment by MarkuZP** [comment]
Is it possible that some characters are not allowed or lenght of the SSID is limited?
My guest WLAN has a longer name with an ! in the middle and its not working
SSID: FRITZ! the cat Gastzugang

**Comment by smarthomefamilyverrips** [comment]
> If you want to display QR code representing your WiFi credentials for visitors, then you have to add this line into blueprint "QR Code content" field: WIFI:S:{yourssid};T:{encriptiontype};P:{yourwifipass};;
> 
> example: for SSID: DAN with Encription Type: WPA2 with Wifi password: secret123 WIFI:S:DAN;T:WPA2;P:secret123;;
> 
> Enjoy! and don't forgot to Activate the QR Code on the Blueprint :)

Where to add this?

**Comment by Blackymas** [comment]
> > If you want to display QR code representing your WiFi credentials for visitors, then you have to add this line into blueprint "QR Code content" field: WIFI:S:{yourssid};T:{encriptiontype};P:{yourwifipass};;
> > example: for SSID: DAN with Encription Type: WPA2 with Wifi password: secret123 WIFI:S:DAN;T:WPA2;P:secret123;;
> > Enjoy! and don't forgot to Activate the QR Code on the Blueprint :)
> 
> Where to add this? Where I find QR code content field?

in blueprint and as HA Service

have a look here:
https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.1.0

**Comment by smarthomefamilyverrips** [comment]
@Blackymas I did not realize that it was a feature in last update, I did do the update and all works like a charm 😍 ..... Great Job!!!! 👍🏻

**Comment by Dermaschinistas** [comment]
Good day to All,

I have a question regaring special Characters like ! or space in SSID is there any limit?

I did set up the QR Code for WIFI as discribed but all the time it fails. If I enter the same values to qrcode-generator.de and scan the code it works instantly.

The SSID has 17 Characters incl. ! and two space, the PW has 20 Characters.

Is there any special requirement for fritzbox needed? 

The Blueprint Version I use is 3.4 / ESP Home 2023.8.3

**Comment by Dermaschinistas** [comment]
@edwardtfn 
thanks for quick respond, I did a test with the GuestWIFI and set it up like 10 Characters for PW and 10 for SSID and success. 

However is the limitation by HA or the Blueprint? As mentioned with an online QR code creator it works also with the long SSID and PW.
Could we add this to an future request if this is the case?

Thanks anyway

**Comment by edwardtfn** [comment]
> However is the limitation by HA or the Blueprint?

Neither. 😂
We have a limit in the Nextion display, per page, but the global variables will count to the limit of every page, so we have to compromise somewhere.
I believe that QRcode field could be made a bit longer, but we put restrictions on ourselves for future new features.
One option is to reduce the global variables, and we probably have some space for that, but not using globals will require some values being loaded when the page is shown, which could be visible by users.

> As mentioned with an online QR code creator it works also with the long SSID and PW.

Exactly, this is not a limitation from the standard.


> Could we add this to an future request if this is the case?

Sure! May I ask you to create another issue (feature request) to make easier managing this?

**Comment by edwardtfn** [comment]
> Could we add this to an future request if this is the case?

How many chars you need?

**Comment by truwer** [comment]
I am dealing with the same limitation. I was first wondering why the QR code did not work. It shows the correct string after reading the QR code, but it is not complete. 

I would need 36 chars (ssid + password). What can I do to change the limit?

**Comment by PedroKTFC** [comment]
Could the format - WIFI:S:{yourssid};T:{encriptiontype};P:{yourwifipass};; - be added to the blueprint? It would save a lot of Googling and server energy! :)
