### ISSUE TITLE
Help with Bricked device - Error on uploading TFT

### ISSUE THREAD

**Issue by dudu631** [Blackymas/NSPanel_HA_Blueprint#308]
I have flashed a unit successfully. 

On the second one, during the update TFT phase I accidentally disconnected from power, which left me with an black screen with "Invalid data" on it. 

Already tried uploading the blank tft first and then updating to the actual TFT but no luck so far. 

What happens is when you're uploading the second TFT it takes forever (even on local www), which doesn't happens for other devices - so, no that's not an internet connectivity problem.

Any thoughts?

**Comment by dudu631** [comment]
It seems that #224 solved my issue. Uploading the correct TFT right now without problems.

I'll close this when it's confirmed.

**Comment by palitu** [comment]
how did you change the baud rate through esphome (the online one, in Home Assistant?).
cheers
