### ISSUE TITLE
Response error 500

### ISSUE THREAD

**Issue by eddcole** [Blackymas/NSPanel_HA_Blueprint#310]
Hi there, could you tell me what i am doing wrong as everytime i try to save my config i get the response error 500

Thank  you

**Comment by Blackymas** [comment]
Blueprint?

**Comment by deejaybeam** [comment]
Esphome?

**Comment by eddcole** [comment]
sorry this is in the blueprint

**Comment by deejaybeam** [comment]
New installation or update?

**Comment by eddcole** [comment]
hi this is a new install, its the first panel i have used

**Comment by Blackymas** [comment]
we don't follow you at all where exactly is your problem now?

You are editing the Blueprint and can't save it because you get an error 500?

maybe you can describe it in more detail or post a screen

**Comment by eddcole** [comment]
Good Morning

Sorry, I have installed your blueprint into HA so that i can modify a Nspanel, the panel flashed fine but when i use the blueprint to update the panel I fill in all the boxes and click save but it then returns with a response error 500 and does not save or update. 

HA is installed on a PI4 and finds the panel no problem in ESP home  and comes up in the integration with everything working, its just i cannot modify it with the blueprint without getting the error. I have restarted the system to no avail. Am i missing something in config or something. I have a lightwave automation running in the background for info

**Comment by eddcole** [comment]
I think i have sussed it, your automation has to be the only one in the automation yaml for it to save

**Comment by deejaybeam** [comment]
> I think i have sussed it, your automation has to be the only one in the automation yaml for it to save

This is not correct!

**Comment by Blackymas** [comment]
@eddcole is your problem solved?

**Comment by eddcole** [comment]
yes i believe i have sorted it, thank you
