### ISSUE TITLE
QR code

### ISSUE THREAD

**Issue by Doser86** [Blackymas/NSPanel_HA_Blueprint#313]
I have generated a QR code for my WiFi information.
This works when i scan it from my browser on computer, but not when i display it on my NsPanel.

**Comment by hollabee** [comment]
Can you be a bit more specific? What does not work - is your phone picking up a wrong QR code, meaning, the one on the panel is different from the one on the pc?

**Comment by Doser86** [comment]
Yes. It looks like the panel changes some details in the QR and making it useless. 
I have stored the file inn my "www" folder, and linking the Blueprint to this adress. 
Wen I open the file on my computer the phone ask if I want to connect to the WiFi when i scan it from my computer screen. On NsPanel it says that there is no information on the QR

**Comment by hollabee** [comment]
Strange. Can you share the qr code here? Maybe with removed login
credentials, I would try on my nspanel later.

Doser86 ***@***.***> schrieb am Mi. 8. Feb. 2023 um 14:22:

**Comment by Doser86** [comment]
![wifiqr](https://user-images.githubusercontent.com/100235266/217543444-ddac0334-c8dd-445e-9f53-bac58023dfdc.png)

No problem with the login credentials. I live in a safe space ;)

**Comment by hollabee** [comment]
Perfect, will let you know. I can try this later today 👍

Doser86 ***@***.***> schrieb am Mi. 8. Feb. 2023 um 14:29:

**Comment by Doser86** [comment]
Thankyou 😊

**Comment by MarkuZP** [comment]
I had same problem. In my case it was a problem with a "!" or blank space in the SSID. I removed them and it worked.

**Comment by MarkuZP** [comment]
Ah ok, mein was muchlonger with "! " and blank spaces.

**Comment by smarthomefamilyverrips** [comment]
I have the problem that the icon dissappear from my home  page on the nspanel after restart, only when toggle it off/on in blueprint or push any action on nspanel then it reappears again

**Comment by deejaybeam** [comment]
> I have the problem that the icon dissappear from my home page on the nspanel after restart, only when toggle it off/on in blueprint or push any action on nspanel then it reappears again
> 
> There are no related events in logs

Also boot problem - you alredy have opened a issue to this (Error-Messages on HA-Restart #314 )
Quick "fix" is to swipe to any other page than home and then go back - this reloads the home-page

**Comment by deejaybeam** [comment]
> Yes. It looks like the panel changes some details in the QR and making it useless. I have stored the file inn my "www" folder, and linking the Blueprint to this adress. Wen I open the file on my computer the phone ask if I want to connect to the WiFi when i scan it from my computer screen. On NsPanel it says that there is no information on the QR

I don´t know what you are doing here - what do you safe in www-folder? the pic?
Than you have totaly missunderstood how this works!

You can send any STRING (max 50 chars) to the display - this generates a QR-Code from the string itself.

So if you want to share WLAN-Information see here for the correct syntax:
https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/305

**Comment by smarthomefamilyverrips** [comment]
> 

@deejaybeam OK thanks for clearing this up, now you say it it sounds logical indeed that is related, and yes any action on touch panel indeed make it reappear.... Thanks again!

**Comment by Blackymas** [comment]
so all is solved?

**Comment by deejaybeam** [comment]
> so all is solved?

Not jet, waiting for answer regarding to the real question - ha-reboot is another topic

**Comment by Doser86** [comment]
Mine got solved with the code, so thankyou :)
