### ISSUE TITLE
Still receiving error at restart HA with version 3.1.0

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [Blackymas/NSPanel_HA_Blueprint#314]
I am still receiving similar error as in issue #260 

@Blackymas FYI you did say this would be fixed in version 3.1.0 stable

Logger: homeassistant.components.automation.nsbathroom_configuration
Source: components/esphome/__init__.py:513
Integration: Automation (documentation, issues)
First occurred: 17:17:34 (6 occurrences)
Last logged: 17:17:35

NSBathroom Configuration: Choose at step 2: choice 29: Error executing script. Unexpected error for call_service at pos 2: Connection not done for 192.168.0.102; current state is ConnectionState.SOCKET_OPENED!
NSBathroom Configuration: Choose at step 2: choice 30: Error executing script. Unexpected error for call_service at pos 2: Connection not done for 192.168.0.102; current state is ConnectionState.SOCKET_OPENED!
NSBathroom Configuration: Error executing script. Unexpected error for choose at pos 2: Connection not done for 192.168.0.102; current state is ConnectionState.SOCKET_OPENED!
While executing automation automation.nsbathroom_configuration
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 513, in execute_service
    await entry_data.client.execute_service(service, call.data)
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/client.py", line 1084, in execute_service
    self._check_authenticated()
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/client.py", line 281, in _check_authenticated
    self._check_connected()
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/client.py", line 275, in _check_connected
    raise APIConnectionError(
aioesphomeapi.core.APIConnectionError: Connection not done for 192.168.0.102; current state is ConnectionState.SOCKET_OPENED!

Logger: homeassistant.components.automation.nsbathroom_configuration
Source: components/esphome/__init__.py:513
Integration: Automation (documentation, issues)
First occurred: 17:17:33 (12 occurrences)
Last logged: 17:17:34

NSBathroom Configuration: Choose at step 2: choice 29: Error executing script. Unexpected error for call_service at pos 2: Not connected to nsbathroom @ 192.168.0.102!
NSBathroom Configuration: Choose at step 2: choice 30: Error executing script. Unexpected error for call_service at pos 2: Not connected to nsbathroom @ 192.168.0.102!
NSBathroom Configuration: Error executing script. Unexpected error for choose at pos 2: Not connected to nsbathroom @ 192.168.0.102!
While executing automation automation.nsbathroom_configuration
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 513, in execute_service
    await entry_data.client.execute_service(service, call.data)
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/client.py", line 1084, in execute_service
    self._check_authenticated()
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/client.py", line 281, in _check_authenticated
    self._check_connected()
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/client.py", line 273, in _check_connected
    raise APIConnectionError(f"Not connected to {self._log_name}!")
aioesphomeapi.core.APIConnectionError: Not connected to nsbathroom @ 192.168.0.102!

**Comment by deejaybeam** [comment]
This is a totaly different error (if you read the content of the message).
I´m afraid this has something to do with the with the latest home assistant core version (2023.2).
https://www.home-assistant.io/blog/2023/02/01/release-20232/#now-even-tighter-integrated-with-esphome
What version do you have installed?
Maybe we will find a way to fix that.
Looks like ha has no connection to the panel - from your log:
```NSBathroom Configuration: Choose at step 2: choice 29: Error executing script. Unexpected error for call_service at pos 2: Not connected to nsbathroom @ 192.168.0.102!```
But HA want´s to execute a service-call from the blueprint to esphome which is not possible, because in this state it is not connected jet.
If this is the problem, this is nothing what we could fix because this is a problem how HA (re)start-process executes.
Anyways I will try to find the root cause of this problem and try to find a solution.
For now, this is nothing that belongs to your configuration, it´s a general problem but only happens on ha-restart.

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam I did read first part and seem similar to me 🙈 sorry for this wrong assumption.... I am on HA 2023.2.3 at the moment. So probably the issue is like you did explain.... I hope it is possible to find a solution for this, I will keep a eye on this issue.... please in the worst case if there is no solution could you also please let me know, in this case will exclude this error message from logger to at least not see it at startup

**Comment by deejaybeam** [comment]
I have pushed an update to dev-branch: https://github.com/Blackymas/NSPanel_HA_Blueprint/commit/5ba5d2fb08ee871a35397f093fff9d1ab0bec459
This solves missing buttons on home-page, it also helps to reduce the errors on ha-restart but not always 100%
If you want to try it you just have to exchange the blueprint and reload the automations.

**Comment by smarthomefamilyverrips** [comment]
Sounds good @deejaybeam I will try tomorrow, now is almost midnight here, will keep you posted 👍🏻

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam I did copy the dev nspanel_blueprint.yaml in the blueprint folder and after did try 4 HA restarts, conclusion:

1. At none of the 4 restarts I did get the error message anymore, so looks like your adjustment did solve this for me.
2. At the first 2 restarts after copying the dev file I lost almost all information on homepage of display, but this happened after about 10-15 seconds after the restart sequence finished ("home assistant has started" message) see also pictures
![1675939611864](https://user-images.githubusercontent.com/97987488/217793874-6368eef2-d408-44eb-aa31-681f2d996cb6.JPEG)
![1675939611906](https://user-images.githubusercontent.com/97987488/217793972-51c29bb4-4a1c-4a30-935a-427b2572856c.JPEG)
3. At restart 3 and 4 the issue described at point 2 not occured anymore.

I will keep the dev version for now to test it longer and will keep you updated if it all stays stable :)

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam I had to do a other HA restart, still no error message in logs but again did happen same as in issue point 2 described in my previous comment..... to make infromation appear again on home screen I need to do a action on the nspanel ( go to button page and back for example)

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam I also got these errors now in my logs without any restart

Logger: homeassistant.components.automation.nsbathroom_configuration
Source: helpers/script.py:409
Integration: Automation (documentation, issues)
First occurred: 16:59:20 (260 occurrences)
Last logged: 17:27:34

NSBathroom Configuration: Choose at step 2: choice 9: Error executing script. Invalid data for call_service at pos 4: expected int for dictionary value @ data['message']
NSBathroom Configuration: Error executing script. Invalid data for choose at pos 2: expected int for dictionary value @ data['message']

Logger: homeassistant.components.automation.nsbathroom_configuration
Source: helpers/script.py:409
Integration: Automation (documentation, issues)
First occurred: 16:59:20 (260 occurrences)
Last logged: 17:27:34

NSBathroom Configuration: Choose at step 2: choice 9: Error executing script. Invalid data for call_service at pos 4: expected int for dictionary value @ data['message']
NSBathroom Configuration: Error executing script. Invalid data for choose at pos 2: expected int for dictionary value @ data['message']

**Comment by deejaybeam** [comment]
This is again another cause.
Looks like the roller-shutter sends status-updates of how wide it is between opened and closed (0-100%) but the value is not correct read from the shutter to send it to the display.
I don´t have that kind of shutters, but @Blackymas.
Can you send a pic of the shutter-attributes from developement tools?
From script/blueprint perspective this is the same as the "brightness" attribute of a dimmable lamp:
![image](https://user-images.githubusercontent.com/10434729/217866822-de341121-feff-4b2d-9e20-b048516db0dd.png)
And also a a pic of the trace from the blueprint->automation?
Here you should see whats happening

**Comment by deejaybeam** [comment]
Initial problem may be related to:
https://github.com/home-assistant/core/issues/87625

**Comment by smarthomefamilyverrips** [comment]
> Initial problem may be related to: [home-assistant/core#87625](https://github.com/home-assistant/core/issues/87625)

@deejaybeam maybe will be solved with the upcoming new esphome version???

**Comment by deejaybeam** [comment]
Maybe, I don´t now what´s change in the new esphome version, but I´m not sure if esphome is the root cause.
Till update to ha-core 2023.2 this also works with current esphome-version.
I think that somethin in ha-startup has changed.
From my point of view, the problem is that in our project the panel turns on the switch "....nextion_inited" after the panel has finished init.
So this value is on. Till now on HA restart it "sees" that the old value was also "on" and the automation does not trigger.
But now, maybe because of the double connect - the first connect does not trigger the automation, but then a reconnect changes the state an brings back again "on" what triggers the automation like a boot of the panel happens...
You can simulate the behaviour if you turn the switch "Nextion inited" off and on again in the device settings.
This should not happen!
2nd problem is that the automation is running (because device is connectet) but disconnects in between.

Currently I have done a lot of testing and maybe have found some kind of workaround, but currently do huge changes on blueprint and also on esphome I hope I´m able to push an update soon - stay tuned...

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam I will keep a eye on this post, just take your time and thanks for all the effort you did put in so far 👍🏻

**Comment by deejaybeam** [comment]
See: https://github.com/Blackymas/NSPanel_HA_Blueprint/pull/321
This should be a running version with many updates/fixes/changes, if you want try it.
You have only to update esphome and blueprint, tft stays the same.

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam how should I update esphome, copy the nspanel_esphome.yaml to www folder and change the remote url to a local url to file in www folder within the esphome device configuration?

![Screenshot_20230210_233211_Home Assistant](https://user-images.githubusercontent.com/97987488/218203157-8d2b188e-4c0b-4471-a2da-361cca47682b.jpg)

**Comment by deejaybeam** [comment]
You could change the line ```ref: main``` to ```ref: dev```.
This changes the source of the code to the dev-branch.
BUT if you compile later again, than the code in dev may be changed in the meanwhile and will create this time version.
To be sure what´s the content it´s the best to have the files located locally.

If you want to work with esphom I recommend to read the docs how esphome works.
In short two other possibilities:
 - copy paste the whole code from github into the editor and adjust your needs (name, WIFI)
 - use an editor to copy the nspanel_esphome.yaml file from the repo into the esphome-folder inside your config-directory.

The "packages" instruction does nothing other than merge your configuration with the git resource while validate/compile.
But this works only with git-repos, you can´t use your www-folder!

If you know how to edit files in home-assistant (and you talk about place in www-folder), your current config file is located at:
/config/esphome/nsbathroom.yaml

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam 

"use an editor to copy the nspanel_esphome.yaml file from the repo into the esphome-folder inside your config-directory"

The only nspanel_esphome.yaml file I can find is within config/esphome/.esphome/packages/566b10a3 folder.... is that the one I should replace? 

![Screenshot_20230211_001143_Home Assistant](https://user-images.githubusercontent.com/97987488/218208782-4faa7efa-434e-4ad1-9009-ac3d910aa053.jpg)

**Comment by deejaybeam** [comment]
NO!
As I have written your esp-home-config file is:
/config/esphome/nsbathroom.yaml

This is the content of what you see in the editor.
You can rename the existing to something else, and place the downloaded file into the same folder.
Than, if you want, or if you have multiple NSPanels, you can give the downloaded file the name of you existing one.
Each file without a dot "." as prefix or .yaml as suffix is shown in your esphome-dashboard.

The current one has just the content you see in the esphome-editor but downloads the rest from git (content of nspanel_esphome.yaml) while compiling. That results in the same as you copy the content into that file (or replace it)...

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam HA OK! now I get it, being that the downloaded nspanel_esphome.yaml file is full of information and my nsbathroom.yaml not it was not clear these are actually the same files, but I get it now... I will copy the file in the esphome folder fill out my wifi credentials and nspanel name to be the same as my existing nsbathroom.yaml, remove the current nsbathroom.yaml and rename downloaded to nsbathroom.yaml and then restart HA.... this is correct way to proceed, right?

**Comment by deejaybeam** [comment]
Again - no!
Esphome is Independent from HA.
If you have changed the contenent, keep/Set the upper Part of the config-file correct (substitutions Part)
Than you Just have to validate/compile/Install the new esphome Firmware with esphome.
What should ha-restart do?

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam sorry for being slow of understanding, I am not all new to this but for sure no expert 🙈

So I can just copy/paste all content in my existing file using the editor di

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam sorry for being slow of understanding, I am not all new to this but for sure no expert 🙈

So I can just copy/paste all content of nspanel_esphome.yaml in my existing file using the editor directly under the line #### CHANGE ME END #### then save and install

![Screenshot_20230211_103044_Home Assistant](https://user-images.githubusercontent.com/97987488/218248750-5df5338c-54d0-4729-afc6-c402ce10d1a2.jpg)

**Comment by deejaybeam** [comment]
YES - this was already said ~11h ago...

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam sorry for being slow of understanding 🙈🙈🙈 I will try this in about one hour when I am home again.... thanks for you patience with me and explaining and make me understand. 👍🏻

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam I did do the changes, now me bootup screen did say esphome 3.1.1 and blueprint 3.1.1 so I assume this means did do the update succesful

**Comment by deejaybeam** [comment]
YES - that´s the reason why this appears on the screen...

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam Ok a update of what is hapening now at restart of HA (did try twice)

1. I get this warning message in my logs, not know if is related but i never did see it before

Logger: homeassistant.helpers.template
Source: helpers/template.py:156
First occurred: 13:58:27 (4 occurrences)
Last logged: 13:58:27

Template variable warning: list object has no element 2 when rendering '{%- if settings_entity_value != "unknown" -%} {{ settings_entity_value.split(',')[2] }} {%- else -%} unknown {%- endif -%}'
Template variable warning: list object has no element 1 when rendering '{%- if settings_entity_value != "unknown" -%} {{ settings_entity_value.split(',')[1] }} {%- else -%} unknown {%- endif -%}'

2. within a few seconds after i get the message "home assistant has started" the display mimics physical button 1 hold it looks like and shows me controls for my bathroom ceiling light (as it would do when I hold the physical button) going back to home page after page timeout time have passed....after this happens the home screen shows all information it should show

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam also this looks not right?

![1676117335654](https://user-images.githubusercontent.com/97987488/218257216-9f0780ed-241c-4177-a00e-ef530d491729.JPEG)

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam also this not looks like is right?

![1676117552434](https://user-images.githubusercontent.com/97987488/218257343-b02aa015-8fc8-46d1-8a03-196da9906021.JPEG)

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam I am also still receiving the error when I operate my IKEA cover/blind and did notice while it is operated it show this in the esphome logs of the device nsbathroom

[13:55:43][W][nextion:318]: Nextion reported invalid instruction!
[13:55:44][W][nextion:318]: Nextion reported invalid instruction!
[13:55:44][W][nextion:318]: Nextion reported invalid instruction!
[13:55:44][W][nextion:318]: Nextion reported invalid instruction!
[13:55:44][W][nextion:318]: Nextion reported invalid instruction!
 .......... continuing till the cover/blind stops moving

**Comment by deejaybeam** [comment]
> @deejaybeam Ok a update of what is hapening now at restart of HA (did try three times)
> 
> 1. I get this warning message in my logs, not know if is related but i never did see it before doing this dev update
> 
> Logger: homeassistant.helpers.template Source: helpers/template.py:156 First occurred: 13:58:27 (4 occurrences) Last logged: 13:58:27
> 
> Template variable warning: list object has no element 2 when rendering '{%- if settings_entity_value != "unknown" -%} {{ settings_entity_value.split(',')[2] }} {%- else -%} unknown {%- endif -%}' Template variable warning: list object has no element 1 when rendering '{%- if settings_entity_value != "unknown" -%} {{ settings_entity_value.split(',')[1] }} {%- else -%} unknown {%- endif -%}'
> 
> 2. within a few seconds after i get the message "home assistant has started" the display mimics physical button 1 hold it looks like and shows me controls for my bathroom ceiling light (as it would do when I hold the physical button) going back to home page after page timeout time have passed....after this happens the home screen shows all information it should show

Work in progress... this is dev-version - please ignore this. Should not have any impact

**Comment by deejaybeam** [comment]
> @deejaybeam also this looks not right?
> 
> ![1676117335654](https://user-images.githubusercontent.com/97987488/218257216-9f0780ed-241c-4177-a00e-ef530d491729.JPEG)

The value is correct, but HA renders a "long" text wrong - nothing I can change - if you want, you can open a issue on ha-core.
Doesn´t affect functionality.

**Comment by deejaybeam** [comment]
> @deejaybeam I am also still receiving the error when I operate my IKEA cover/blind and did notice while it is operated it show this in the esphome logs of the device nsbathroom
> 
> [13:55:43][W][nextion:318]: Nextion reported invalid instruction! [13:55:44][W][nextion:318]: Nextion reported invalid instruction! [13:55:44][W][nextion:318]: Nextion reported invalid instruction! [13:55:44][W][nextion:318]: Nextion reported invalid instruction! [13:55:44][W][nextion:318]: Nextion reported invalid instruction! .......... continuing till the cover/blind stops moving

Interesting - I haven´t change the cover-code, but it looks like another/related error than before.
Maybe we found the issue to be able to fix that.

**Comment by smarthomefamilyverrips** [comment]
> > @deejaybeam Ok a update of what is hapening now at restart of HA (did try three times)
> > 
> > 1. I get this warning message in my logs, not know if is related but i never did see it before doing this dev update
> > 
> > Logger: homeassistant.helpers.template Source: helpers/template.py:156 First occurred: 13:58:27 (4 occurrences) Last logged: 13:58:27
> > Template variable warning: list object has no element 2 when rendering '{%- if settings_entity_value != "unknown" -%} {{ settings_entity_value.split(',')[2] }} {%- else -%} unknown {%- endif -%}' Template variable warning: list object has no element 1 when rendering '{%- if settings_entity_value != "unknown" -%} {{ settings_entity_value.split(',')[1] }} {%- else -%} unknown {%- endif -%}'
> > 
> > 2. within a few seconds after i get the message "home assistant has started" the display mimics physical button 1 hold it looks like and shows me controls for my bathroom ceiling light (as it would do when I hold the physical button) going back to home page after page timeout time have passed....after this happens the home screen shows all information it should show
> 
> Work in progress... this is dev-version - please ignore this. Should not have any impact

@deejaybeam Ok i will ignore it for now

**Comment by smarthomefamilyverrips** [comment]
> > @deejaybeam also this looks not right?
> > ![1676117335654](https://user-images.githubusercontent.com/97987488/218257216-9f0780ed-241c-4177-a00e-ef530d491729.JPEG)
> 
> The value is correct, but HA renders a "long" text wrong - nothing I can change - if you want, you can open a issue on ha-core. Doesn´t affect functionality.

@deejaybeam for now i just did disable the entity so it not shows in the dashboard

**Comment by smarthomefamilyverrips** [comment]
> > @deejaybeam I am also still receiving the error when I operate my IKEA cover/blind and did notice while it is operated it show this in the esphome logs of the device nsbathroom
> > [13:55:43][W][nextion:318]: Nextion reported invalid instruction! [13:55:44][W][nextion:318]: Nextion reported invalid instruction! [13:55:44][W][nextion:318]: Nextion reported invalid instruction! [13:55:44][W][nextion:318]: Nextion reported invalid instruction! [13:55:44][W][nextion:318]: Nextion reported invalid instruction! .......... continuing till the cover/blind stops moving
> 
> Interesting - I haven´t change the cover-code, but it looks like another/related error than before. Maybe we found the issue to be able to fix that.

I hope you guys do as this is the most "anoying" for me as it pops up as a error in HA logs everytime I operate the blind/cover, the other logs are/where only on start-up so less noticable..... thanks so for for all!!!

**Comment by deejaybeam** [comment]
> 

Im not sure if disabling the entity is a good idea - this could brake the functionality.
Just try if "hold" works if this is disabled.

I don´t understand why this is on your dashboard?
This is only in the settings of the device - if you have added it to the dashboard, then just remove it from there...

**Comment by smarthomefamilyverrips** [comment]
> > 
> 
> Im not sure if disabling the entity is a good idea - this could brake the functionality. Just try if "hold" works if this is disabled.
> 
> I don´t understand why this is on your dashboard? This is only in the settings of the device - if you have added it to the dashboard, then just remove it from there...

@deejaybeam I kind of said it wrong, it is not on my dashboard it shows like this at device info of device "nsbathroom" within the esphome integration.

I did enable it again for now, is not that I look that often at the device info anyway, but one question/remark, was this entity not showing  before because is the first time I see it showing with such a long description.... so that is why I did think it have to do with the dev. update

**Comment by deejaybeam** [comment]
Yes - this is a new component.
Needed for the new hold funcionality, code rework and prep for multiple climates

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam but is it necessary to show all the available sensors in device info within esphome integration? To me personal it not have any value of seeing most of sensor states, is it not possible to hide sensors within the esphome configuration of the device?

![Screenshot_20230211_171235_Home Assistant](https://user-images.githubusercontent.com/97987488/218266215-86c8c9b8-ca1d-4460-9c68-a6fd83ea7c21.jpg)

**Comment by deejaybeam** [comment]
As far as I know: NO if it´s active you see it.
If I would use an internal variable inside ESPHome, than an additional service would be required to get the values from the display itself. This way its transfered to HA via the api and can be accessed from HA more efficient.
The only other possibility would be to ask the users to create manualy helpers in ha wich makes this all much more complicate to install and would be very error prone.
This pic is something you see only if you go down deep inside the rabbit hole of ha itself, but never seen on normal usage.
And I think no need of additional components than ESPHome, TFT and Blueprint is a main reason why many peoble like this solution.
That´s the price for it...
The other thing is, YOU have a better possibility to see whats happen in background, or help troubleshooting.

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam  "This pic is something you see only if you go down deep inside the rabbit hole of ha itself, but never seen on normal usage" 

I think you are right here, and I let it "bother" me for nothing 🙈

And indeed you are right the simplicity of using this blueprint you guys created is the beauty of it 👍🏻

And yes more information never hurts in case of trouble shooting. 

Sorry for bothering you with this none noteworthy thing 🙏

The dev version is running good so far 👌 will let you know if something comes up. Thanks!!!

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam I now noticed that holding the left physical button not always brings me to option screen of my light, I hold it but nothing happens, if I check if button is triggered it says on in device info for as long I hold the button and single push also tur  on/off light... the hold on right button all the time does work and I also noticed if I try hold on left button after I first hold right button then hold on left button also works again, but if I try again a few moments later then again holding left button not brings me to option menu

**Comment by deejaybeam** [comment]
this is already changed in latest dev-version of the blueprint.
You can install it.
Also the split error should not came up anymore.

**Comment by smarthomefamilyverrips** [comment]
> this is already changed in latest dev-version of the blueprint. You can install it. Also the split error should not came up anymore.

@deejaybeam I only need to replace the blueprint.yaml or also esphome?

**Comment by deejaybeam** [comment]
only the blueprint in this case

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam yes it works now, also the "Setting Entity" switch back to unknown now as soon as option screen closes..... so this also solves the text coming outside borders continously ..... 👍 

Now I hope you guys also will find a solution for my IKEA blind/cover causing errors in HA and ESPhome device logs ...... Thanks again so far!!!

**Comment by Blackymas** [comment]
Ikea blinds via z2m?

**Comment by smarthomefamilyverrips** [comment]
> Ikea blinds via z2m?

@Blackymas no via ZHA

**Comment by edwardtfn** [comment]
This issue related to Ikea covers should be in another thread. 😉
I had the same issue that was the original reported here, but it is a bit confusing to understand what is related to that and what is not, as there are a couple of other issues being discussed here and in the end I have to go thru all the discussions not related to the original problem reported.

**Comment by smarthomefamilyverrips** [comment]
@edwardtfn the solution is replace blueprint and esphome config for the dev version

**Comment by edwardtfn** [comment]
Yeah, I got that and already implemented with good results.
My point is more related to taking the other topics in the same thread as this makes a bit more cumbersome, but also prevents people with the other issues to easily find the discussion about that.
Am I been too picky? Sorry for that, it was not my intention.

**Comment by smarthomefamilyverrips** [comment]
@edwardtfn no no I understand what you are saying, just did try to help by pointing out the solution.... if @deejaybeam or @Blackymas want me to make a new issue report for the IKEA blinds/covers I can do so 😊

**Comment by Blackymas** [comment]
@smarthomefamilyverrips 

yes pls create new issue, because it is another topic

thanks!
