### ISSUE TITLE
Outdoor temperature sensor precision

### ISSUE THREAD

**Issue by Achronite** [Blackymas/NSPanel_HA_Blueprint#316]
I have a sensor value which I am using for the outdoor temperature which operates with 1 decimal point precision.

When this is displayed on the NS panel using the blueprint setting 'Outdoor Temperature Sensor' it only shows the full whole number.

e.g 9.4° or 8.6 is shown as 9°

Can this be changed to show the precision as recorded in HA?

**Comment by Blackymas** [comment]
technically possible i have to check if the space is enough for it.

You can create a poll under discussions. 

Then we see how many want that too or rather not.

**Comment by Achronite** [comment]
All good thanks for adding @Blackymas
