### ISSUE TITLE
how to enable nspanel psram

### ISSUE THREAD

**Issue by cyberumut** [Blackymas/NSPanel_HA_Blueprint#319]
how to enable nspanel psram ? 
i have a 16mb psram but not active on circuit how activated?

**Comment by deejaybeam** [comment]
Do you have an example of what you want to achive?
From my knowledge the psram is used internaly.

**Comment by cyberumut** [comment]
> 
i install different software on nspanel esp32 but not working psram 
how can i enabled psram

**Comment by deejaybeam** [comment]
Different Software on nspanel?
This project just uses the existing esphome-integration for nextion display.
Maybe you can find something on esphome, but now I´m not sure if you use esphome.
I´m afraid we can´t help you.
If you want to run something other than the esphome (not from our side) config (for esphome) from this project, than you ask the wrong "team"

**Comment by cyberumut** [comment]
> Different Software on nspanel? This project just uses the existing esphome-integration for nextion display. Maybe you can find something on esphome, but now I´m not sure if you use esphome. I´m afraid we can´t help you. If you want to run something other than the esphome (not from our side) config (for esphome) from this project, than you ask the wrong "team"

I have nspanel but psram is not working.
psram available on circuit 16mb 
how can i run it via tasmota?
![image](https://user-images.githubusercontent.com/105754498/218284006-7589d696-8312-4aae-b505-0fd32c129225.png)

**Comment by Blackymas** [comment]
sry but what is this how do you think it must be done by us?

I hear the first time and do not know what this has to do with our project.

**Comment by bkbartk** [comment]
This would be interesting. But I think the question should be asked at the esphome team first. If esphome supports this it might can be integrated in other projects

**Comment by edwardtfn** [comment]
We are introducing PSRAM on v4.3.3. Please take a look on our implementation and let me know if you still needing help to enable this.

**Comment by edwardtfn** [comment]
- #1983
