### ISSUE TITLE
Hardware Button 1 & 2

### ISSUE THREAD

**Issue by larastafarian** [Blackymas/NSPanel_HA_Blueprint#320]
Hi when I select a hardware button Left or Right to run an automation via the blueprint nothing happens.
If I setup an automation with the L or R hardware button outside of the blueprint & physically press the buttons the automations don't run. However if I go into devices & select the esphome device & flick the relay 1&2 controls the automations run?

**Comment by deejaybeam** [comment]
This is per design. A button press turns an automation on/off (enable/disable) but does not trigger the execution of the automation. What you want is to run a script - pack your automation-code into a script and assign that.

**Comment by larastafarian** [comment]
Hi Thanks that work’s perfect….

I’m still learning the in’s & out’s of HA

**Comment by edwardtfn** [comment]
Let's discuss about this issue on https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/810#discussioncomment-7596539
