### ISSUE TITLE
Error after TFT upload

### ISSUE THREAD

**Issue by sparkydave1981** [Blackymas/NSPanel_HA_Blueprint#329]
I successfully flashed a new NS panel with the ESPhome code as per the docs but after triggering the TFT upload and waiting for completion I now have 'System Data ERROR!' shown on the screen and nothing else.  The TFT upload was done from my local HA machine and appearing to finish without any issues (it went all the way to 100%).  I've since flashed the NS panel again with the same ESPhome code but swapping out the TFT address to use the 'blank' file, no change.  The error comes up immediately when the the panel is powered up.

Any tips for how to fix this?  I bought 3 NS panels but done want to brick them so I haven't touched the other yet.

**Comment by Blackymas** [comment]
use the issue search - this topic has already been edited and solved.

**Comment by sparkydave1981** [comment]
> this topic has already been edited and solved.

I tried but didn't find it.  I'll have another hunt.

**Comment by piotrvvilk** [comment]
Probably #224 is the answer. But...
1. Can I use local https instead of http in nextion_update_url?
2. When and how I should make this command: 
"esphome: on_boot: priority: 601 then: - lambda: id(disp1).send_command_printf("DRAKJHSUYDGBNCJHGJKSHBDN");" ?

**Comment by Blackymas** [comment]
it is no longer necessary to change the baud and therefore you do not need the command.

The important thing is to download the blank TFT and upload it to your HA server.

Then use the http and not https path. If you can't use http via HA you have to use another server like NAS.

Alternative would be the upload via Tasmota (never done it myself) but there are some posts about it.

If this is not possible, the direct upload via Nextion Editor is still available (has also been described here).

for very hard cases there was also here a very interesaante solution.
PS. you do not have to solder with adhesive tape vestkleben also works

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/166

**Comment by sparkydave1981** [comment]
I'm trying to get it working following the second post in [Issue#265](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/265) but so far I have not had any luck.  I flashed the NS Panel with copy of the 'advanced config' ESPhome code and swapped the required sections for wifi credentials but it won't even connect to my network.  Not sure why it isn't working.

**Comment by sotatech** [comment]
As my HA uses https, I ran into the same problem as you. How I solved it was to setup a second basic HA install on a spare Raspberry Pi and load the .tft files there. Then I pointed the ESPhome config at the IP address of the Pi. Worked immediately.

**Comment by piotrvvilk** [comment]
I uploaded tft firmware by wire finally and my NSPanel work fine with Blueprint project :). Don't forget unmount serial resisotrs between tft panel and esp32 chip when tou are going to use this method. After download firmware mount it back on place :)

**Comment by sparkydave1981** [comment]
Why is this issue now closed?  What is the solution for fixing a NS Panel which has the error as per my initial post?

**Comment by Blackymas** [comment]
because alsor in the post was called the same solutions as in all the other contribute.

There is no other solution and you have to look for the problem locally.
