### ISSUE TITLE
Steuerung Lüftungsanlage

### ISSUE THREAD

**Issue by romeox44** [Blackymas/NSPanel_HA_Blueprint#333]
Erstmal schließe ich mich den anderen an und muss das bis jetzt umgesetzte loben! Weiter so! 
Wir haben in unserem Haus eine Lüftungsanlage welche ich bereits aus dem Homeassistent steuern kann. 
Wäre es möglich eine Karte einzufügen in der ich die Lüfterstufen auswählen und die aktuell laufenden angezeigt bekomme.
Das Ansteuern der Stufen habe ich aktuell über Schalter umgesetzt. Eine Möglichkeit zur Anzeige der Lüfterstufe habe ich nicht gefunden.

Von der Lüftungsanlage kommen noch weitere Infos wie Temperaturen, Lüfterdrehzahlen, Bypass Ansteuerung, Standleitung Filter usw.

Würde mich freuen wenn ihr da etwas integrieren könntet.

Beste Grüße

**Comment by Blackymas** [comment]
Hallo,

mach dazu mal ein Screen von den Attribute.

die Werte wie temp etc ist das ein eigener Sensor? Oder in der Entität als Attribute hinterlegt?

**Comment by romeox44** [comment]
Guten Morgen,

mit der Lüftungsanlage wird über Modbus kommuniziert.

Weiter unten zwei Bilder aus der config. 
Im Anschluss hat jedes Merkmal in meinen Augen eine eigene Entität. 
Das mit den Schaltern ist noch nicht ganz optimal gelöst. 
Zum Wechseln der Lüftschufe wird nur ein Impulse über einen Taster benötigt.

So sehen aktuell die Entitäten aus.
![image](https://user-images.githubusercontent.com/93425764/219272920-9d8c0cbd-3e28-4e3d-80b8-683987787a79.jpeg)

die config:

![image](https://user-images.githubusercontent.com/93425764/219273010-5e2b87e9-34fe-490c-98a3-f992f2ced4a1.jpeg)

![image](https://user-images.githubusercontent.com/93425764/219273045-09b67963-8830-400a-b079-011051c93f53.png)

Ich würde es super finden, wenn die aktuelle Lüfterstufe auf der ersten Seite des nspanel zu sehen wäre und wenn man auf diese klickt, analog dem Thermostat auf die Seite mit den Einstellungen gelangt.

Im App des Herstellers wird der Luftstrom und die Temperaturen wie folgt dargestellt.
![image](https://user-images.githubusercontent.com/93425764/219273696-cb23d310-244f-49c4-9a30-20c5a32784f2.jpeg)

Vielleicht besteht ja auch eine Möglichkeit sowas zu integrieren.

Grüße

**Comment by Blackymas** [comment]
naja generell sind das ja einzelne Switch die du ja auf die buttons legen kannst.

Ob wir eine komplett neue seite dafür bauen weiß ich nicht, weil das doch sehr speziell ist.

**Comment by romeox44** [comment]
Hallo,
über einen Button habe ich das aktuell auch getan, eine Anzeige welche Lüfterstufe läuft habe ich aber nicht umsetzen können. 
Wenn man umschalten möchte, weiß man leider nicht, welche Stufe aktuell angewählt ist oder ob das umschalten funktioniert hat.

Ich würde mich freuen wenn ihr da etwas bauen könntet.
Ich vermute das viele einen Anwendungsfall haben, da die neueren Häuser zum großen Teil Lüftungsanlagen besitzen. 

Grüße

**Comment by deejaybeam** [comment]
Rückfrage:
Wie stellst du dir vor, dass das NSPanel eine Information anzeigen soll, die von HA nicht geliefert wird?
Das NSPanel ist eben nur eine "Fernbedienung" für Homeassistant.
Wenn die eingerichteten Switches die aktuell eingestellte Stufe anzeigen - sprich, wenn Stufe 2 an (aktiv) ist, dann ist auch Switch2 an - dann wird das auch "richtig" am NSPanel angezeigt (und eben auch in HA).
Die einzige Lösung dafür ist eben, dass du beim Template Switch eben auch den "State" setzt, sofern du den vom Modbus auch bekommst - alles andere ist "raten"

**Comment by romeox44** [comment]
Hallo,
von der Lüftungsanlage wird die Information der Lüfterstufe bereitgestellt und diese ist in Homeassistent als Sensor verfügbar. Ich habe nur keine Funktion gefunden, diesen Sensor auf dem NSPanel einzubinden, so das mir der Wert angezeigt wird.
Schön würde ich es finden, dass diese Information gleich auf Seite 1 zu sehen wäre.

Grüße

**Comment by Blackymas** [comment]
Es gibt doch mit Update 3.1.0 mehrer Entity page - reicht das nicht?

**Comment by romeox44** [comment]
Guten Morgen,

wenn ich dann die Lüfterstufe sehen kann. Wäre es super. 
Gibt es dann auch die Möglichkeit auf der ersten Seite noch eine Entität darstellen zu lassen.
Grüße

**Comment by Blackymas** [comment]
Kommt mit dem nächsten Update ja 🤩

**Comment by Blackymas** [comment]
kann ich das Ticket schließen sollte aj soweit alles geklärt sein ;)
