### ISSUE TITLE
How to set date and time format?

### ISSUE THREAD

**Issue by trhessel** [Blackymas/NSPanel_HA_Blueprint#338]
After a few flashing issues I was able to my nspanels flashed with esphome and using this blueprint, and love it, thank you so much. One question is how can I set the date and time format? Currently time is in 24hr time and date is Day of week, Day and Month. Would like to set time to 12hr and date format to Day of week, month and date.

**Comment by Blackymas** [comment]
changing the date is only possible if you change it in the blueprint code.
we get the time stamp from ha itself

timestamp_custom('%a %d.%m')
