### ISSUE TITLE
NSPanel bleibt hängen

### ISSUE THREAD

**Issue by LutzAndreas** [Blackymas/NSPanel_HA_Blueprint#347]
Hallo erstmal Gratulation zu diesem Blueprint.
lch habe eigentlich zwei Probleme.
Problem 1 ist das einer meiner Panels hängt, dh. auf dem Bildschirm ist zu lesen "Waiting for content..." dieser Bildschirm lässt sich nicht mehr abschalten. Habe alles versucht, selbst auf Tasmota geflashed und wieder auf ESP zurück, der Bildschirm bleibt da hängen. Der ESP wurde ordnungsgemäß geflashed und ist im Netzwerk auffindbar und alle Funktionen werden in Home Assistant angezeigt - leider lässt sich weder ein tft Datei darauf spielen oder andere Sachen machen. - was ich kann ich tun?
Problem 2 nach dem neusten Update zeigen die Buttons nicht den jeweiligen Namen an die im Blueprint eingetragen wurden - und die Entity-Seiten tauchen nicht auf dem Display auf, obwohl ebenfalls im Blueprint eingetragen - die Aktivierung der Entity-Seite habe ich gemachrt.- anderes NSPanel
Hat jemand ein Idee
Für Eure Hilfe schon im voraus vielen Dank.
Lutz

**Comment by pimp1310** [comment]
zu Problem 1 
du musst eine leere tft hochladen wenn du zuvor die lovelace-ui version von jobraun benutzt hast da auf dem Panel nicht genug Speicher vorhanden ist. das kannst du am besten auch mit tasmota machen bevor du zu esphome wechselst.
und dann die richtige tft von blacky hochladen.

das wäre die blank tft
https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/custom_configuration/nspanel_blank.tft

**Comment by deejaybeam** [comment]
Hi - zuerst einmal: Dankeschön!

Problem1:
Wenn du am Display "Waiting for content..." stehen hast, dann ist (noch) nicht das TFT von diesem Projekt installiert, sondern von die lovelace-ui - dafür gibt es, wie oben bereits erwähnt, eine eigene Anleitung, und auch bereits einige issues hier, was da zu tun ist. Das hat nichts mit ESPHome oder Tasmota zu tun, das Nextion-Display hat einen eigenen Microcontroller mit eigenständiger Firmware (TFT) die nur vom ESPHome "gesteuert" wird.
https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(DE)-Erste-Schritte---Installation-und-Einrichtung#2-version-nspanel-lovelace-ui-von-jobr99-wurde-vorher-installiert

Problem2:
Das klingt danach, als wäre in der, aus dem Blueprint erstellten Automatisierung, irgendwo ein Fehler drinnen.
Das kann ein ungültiger Wert, gelöschte entity, ..... sein.
Manchmal kommt es vor das Einträge nicht vollständig aus der Automatisierung gelöscht werden - das ist ein Problem von Homeassistant.
Versuch einfach einmal die bestehende Automatisierung zu löschen und neu anzulegen. Aber nur mal mit einer minimalen Konfiguration. Dann Stück für Stück zu erweitern - evtl. gibt es auch mit einer entity ein Problem bei der Abfrage, dann bricht die Automatisierung an dieser Stelle ab.
Dann sollte aber auch ein Eintrag im Log sein bzw. bei den Traces von der Automatisierung zu sehen sein.
