### ISSUE TITLE
Feature request: locally (esphome lambda) managed climate control, switching physical relays

### ISSUE THREAD

**Issue by chris24walsh** [Blackymas/NSPanel_HA_Blueprint#349]
What would it take to get a climate control that does not depend on Home Assistant to perform the logic? Ideally I would imagine this to operate using lambdas running on esphome itself, but taking a HA sensor to read temperature (so I can average several sensors for a more representative house temperature) and defaulting to NSPanel's local thermometer if HA is offline. Then this would switch the physical relays as heating/cooling inputs to my heat pump, thus it would be the most reliable climate control possible.

**Comment by nitruxa** [comment]
I think I'll take this as my next project. In certain cases I'd like to have a totally independent from HA NSPanel. which could just control two relays as light switches with phisical buttons, or use one relay to control the heating valves.

Can you describe your thoughts in a bit more details? Especially this part:
> Then this would switch the physical relays as heating/cooling inputs to my heat pump

**Comment by chris24walsh** [comment]
Thanks for your interest! For my use case, I would still want the NSPanel to operate as it does, allowing interaction with HA entities etc. But I would like to make specifically the climate logic happen only on ESPHome, for maximum reliability.
As for your use case, I believe there is already a feature in the latest version which allows 'fallback' to physical button control of the relays directly in the ESPHome image, in the situation where HA goes offline. Whether or not this button -> relay control should default to being managed via Home Assistant while it is online, I think makes no difference, no? Should be the same result.

> Can you describe your thoughts in a bit more details? Especially this part:

 >>   Then this would switch the physical relays as heating/cooling inputs to my heat pump

I would like ESPHome to control the relays, using lambdas, based on the value of either 1) a HA sensor (e.g. average house temp.), or default to 2) NSPanel's temperature sensor.

I plan to connect the relays to a pair of octocoupler-relays, with which I can control dry-contact (volt-free) inputs on my heat pump. I need both relays (rather than doing a dry-contact hack such as [this](https://github.com/sballano/nspanel_thermostat/blob/main/hardware_mods.md#user-content-relay-modification)), since my heat pump can do both heating and cooling, and I therefore I need to switch two octocouplers to be able to activate either mode.

**Comment by nitruxa** [comment]
for my certain use cases I would like not to have HA at all. and currently NSPanel can't work independently without HA, cause it has to receive its config from HA Blueprint.

just curious... isn't heating / cooling is the logic of the heatpump itself? For example my heatpump is configured the way so that it automatically turns heating / cooling according to the temperatures set on heatpump itself, and it has nothing to do with the "thermostat - NSPanel". And thermostat on NSPanel would only control valves on the floor collector. 🤔

**Comment by chris24walsh** [comment]
> just curious... isn't heating / cooling is the logic of the heatpump itself? For example my heatpump is configured the way so that it automatically turns heating / cooling according to the temperatures set on heatpump itself, and it has nothing to do with the "thermostat - NSPanel". And thermostat on NSPanel would only control valves on the floor collector. 🤔

I use an external, wired 'smart' thermostat to control my heatpump, which connects to a pair of dry-contacts on the heatpump indoor unit. It works, and offers the benefit of operating via my home network, or locally using the built-in UI. However, it's not ideal since the network connectivity requires internet, and I need 2 inputs for my heat pump to switch between heating and cooling modes. Right now, I'm stuck with either heating mode or off. 

> for my certain use cases I would like not to have HA at all. and currently NSPanel can't work independently without HA, cause it has to receive its config from HA Blueprint.

What then do you want to use the NSPanel for, apart from switching relays? Do you mean you want to display sensor data from HA on the screen but actuate the relays only via the physical buttons? It seems a waste to not use the NSPanel as an interface for actuating (albeit virtually) many different HA devices & routines.

**Comment by nitruxa** [comment]
some users just need it to be a simple thermostat. which in their case they could just use the default nspanel software with ewelink, but it would be a first step before the HA integration. nspanel could work independently without HA - measuring temperature, switching heating valves, and in addition switching one additional relay.

when HA would be available - then it could be easily updated to use all the other features offered by HA and the blueprint.

**Comment by nitruxa** [comment]
regarding your setup, I think its a very "your" case 🤔 and it would have to be customized only for your needs. I think you could easily achieve this by just copying the whole https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/nspanel_esphome.yaml config and updating the stuff you need to match your needs.

**Comment by chris24walsh** [comment]
> some users just need it to be a simple thermostat. which in their case they could just use the default nspanel software with ewelink, but it would be a first step before the HA integration. nspanel could work independently without HA - measuring temperature, switching heating valves, and in addition switching one additional relay.

> when HA would be available - then it could be easily updated to use all the other features offered by HA and the blueprint.

I agree that another firmware other than this would probably be best for this use case, either the native NSPanel Ewelink FW or another Tasmota/ESPhome FW. The major value in this repo's FW is that it works really easily with HA. There are other FW's I have tried that more easily allowed to do what I am requesting, but I would prefer to use this FW and add that functionality.

> regarding your setup, I think its a very "your" case 🤔 and it would have to be customized only for your needs. I think you could easily achieve this by just copying the whole https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/nspanel_esphome.yaml config and updating the stuff you need to match your needs.

I don't think it's that unusual, probably with underfloor you set a steady setpoint for your flow temp? In my case, the heat pump was a retrofit with existing radiators (and in the future, I will replace some of these with fan convectors). I need to be able to switch between either heating/cooling/off since there is obviously a different very flow temperature for either heating or cooling. This requires two pairs of contacts.

There is a HA integration for my heat pump where I could set the mode, but it relies on the cloud, so the only fully local option is to use the two pairs of contacts, as I mentioned.

**Comment by nitruxa** [comment]
got it. so IMO they way to make it work for your use case is to get the full `nspanel_esphome.yaml` config and adjust it to suit your needs. 🤷‍♂️

**Comment by deejaybeam** [comment]
> got it. so IMO the way to make it work for your use case is to get the full `nspanel_esphome.yaml` config and adjust it to suit your needs. 🤷‍♂️

Totaly agree.
But you can have a look at this esphome-components:
https://esphome.io/components/climate/index.html
https://esphome.io/components/climate/bang_bang.html
https://esphome.io/components/climate/thermostat.html

**Comment by chris24walsh** [comment]
> > got it. so IMO the way to make it work for your use case is to get the full  `nspanel_esphome.yaml` config and adjust it to suit your needs.  🤷‍♂️
> 
> Totaly agree. But you can have a look at this esphome-components: [https://esphome.io/components/climate/index.html ](https://esphome.io/components/climate/index.html) [https://esphome.io/components/climate/bang_bang.html ](https://esphome.io/components/climate/bang_bang.html) [https://esphome.io/components/climate/thermostat.html ](https://esphome.io/components/climate/thermostat.html)

Very nice, I will use these thanks!
