### ISSUE TITLE
Button icons feature request

### ISSUE THREAD

**Issue by haywiremk** [Blackymas/NSPanel_HA_Blueprint#351]
It would be nice if button icons could be specified like the active entities.  For example instead of every light being a light bulb allow light type icons.  Even better would be if this could be automatically pulled from the entity specified icon but that may need mapping to the Unicode.

**Comment by Blackymas** [comment]
We are currently working on this ;)

**Comment by roblamoreaux** [comment]
In relationship to this it would be nice to be able to use the Icon Selector in HA to select the icon. 
It looks like it may be possible if there is a way to go from "mdi:lightbulb" to the character code, but I haven't found that yet.

**Comment by albinmedoc** [comment]
I don't know if this is something for rendering the icons?

https://docs.nspanel.pky.eu/icon-cheatsheet.html

**Comment by Blackymas** [comment]
it will be released with v3.2

**Comment by Blackymas** [comment]
Is changed in v3.2 
Please update and test :)

https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.2
