### ISSUE TITLE
3.1.0 display slow to show entities

### ISSUE THREAD

**Issue by chris24walsh** [Blackymas/NSPanel_HA_Blueprint#355]
Since upgrading to 3.1.0 from 3.0.0, I've found that whenever a page is refreshed/loaded - any entities in that page are very slow to load (4-8 seconds!). I didn't notice any delay with the previous version. Is there an issue here, perhaps due to more MQTT entities or something? I've no idea, just trying to imagine what could be the cause. Please explain how I can debug this, or provide more information.

**Comment by deejaybeam** [comment]
You may have (accidentally) changed the "Delay to avoid synchronization problem" in the blueprint/automation?
Try to set this to a low value (0-5).

This project has nothing to do with MQTT.

**Comment by plasterer41** [comment]
My entities are disappearing also. Very regularly they disappear for minutes (not seconds). This is happening on both nspanels that I have installed 3.1.0 onto.

**Comment by chris24walsh** [comment]
@deejaybeam I checked and I haven't set that delay. Also, it's not as bad as @plasterer41 but it's worse than I orginally said - about 30seconds for many entities to appear after change, sometimes they seem to never appear.

**Comment by plasterer41** [comment]
The thermostat also breaks and reverts to German (ein) when entities disappear.

**Comment by chris24walsh** [comment]
I also see this

**Comment by Blackymas** [comment]
yes it is a bug

**Comment by Blackymas** [comment]
> The thermostat also breaks and reverts to German (ein) when entities disappear.

yes it is a bug

**Comment by Blackymas** [comment]
I close the ticket because the topic was "display slow to show entities"
