### ISSUE TITLE
QR code generator appears to truncate string

### ISSUE THREAD

**Issue by GuySie** [Blackymas/NSPanel_HA_Blueprint#356]
I want to use the new QR code functionality in 3.1.0 to create an easy-access QR to let people scan and log onto our Wifi without having to explain which SSID and password to fill in.

However, the QR fails to work when scanned. If I parse the nspanel's QR to show the entire string that was encoded, it's being truncated to 50 characters and does not contain my full password. The blueprint automation does contain the entire string. I'm using the wifi config string as detailed here:
https://github.com/zxing/zxing/wiki/Barcode-Contents#wi-fi-network-config-android-ios-11
`WIFI:S:FILL_IN_YOUR_SSID;T:WPA;P:FILL_IN_YOUR_PASSWORD;;`
The same string works when the QR is generated via https://qifi.org/ for example.

Am I right that there is a 50 char limit? Is there a reason for that?

Edit: Ah, I see in the release notes that the 50 char limit is confirmed there:
"For the QR Code Content you have 50 characters at your disposal which you can use freely."
Is it possible to extend that char limit?

**Comment by deejaybeam** [comment]
Hi
currently - NO - the qrcode consumes a very high amount of memory (for each character).
This requires already a very huge re-design of the tft to allow 50 chars. (with more than 32 chars tft does not compile anymore with v3.0 tft)

**Comment by GuySie** [comment]
Ah, too bad, but I understand! Thanks for your reply.
