### ISSUE TITLE
24 hours to update Update TFT display and then error

### ISSUE THREAD

**Issue by maxtrin87** [Blackymas/NSPanel_HA_Blueprint#359]
Hello i am new to this just got myself a nspanel eu and followd marks guide on yt but i get stuck on Update TFT display it tock 24 hours to do and now all it says is system data error, i have read and read but i dont get what i am doing wrong?
Please can someone help me?

**Comment by Blackymas** [comment]
hey,

it is also with you the same error you can only try the following

download nspanel_blank.tft and upload it to your ha

1. use only http instead of https

2. if nothing works try tasmota

**Comment by Blackymas** [comment]
or try this 
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/332

**Comment by romeox44** [comment]
Hallo,

bei mir hat geholfen die blank und die neue TFT Datei local in Home Assistent abzulegen und dann erst die blank aufzuspielen. 
Im Anschluss lies sich die neue TFT Datei innerhalb von ca.5min aufspielen. 

Grüße

**Comment by maxtrin87** [comment]
Thank you all for your answers! I’ve tried loading a blank tft and only “http” with the same results. 

I’ve read that for some changing the baud rate might fix the issue? If someone could point me to the file where I change it I will try again.

again, thanks! 😊

**Comment by maxtrin87** [comment]
God news for me i manage to flash in the blank tft and then the normal file and it worked idk what i did wrong before or what i did different now. thank you all for all the help let the smart home adventure continue.
