### ISSUE TITLE
relays and pages not working

### ISSUE THREAD

**Issue by nassermahrous** [Blackymas/NSPanel_HA_Blueprint#360]
I have several NS panels EU and US all working fine, one US panel has a problem that I can't swipe to open the pages and the settings gear is not working, also the relays are not working, can you pls tell me what to do

**Comment by Blackymas** [comment]
Hello,

it sounds like you are using a wrong name in the blueprint. Please remember that you cannot use a "-" and preferably no special characters.

**Comment by nassermahrous** [comment]
Thank you. I uploaded a blank tft to solve the problem. Thank you

Best regards
Nasser Mahrous

On 21 Feb 2023, at 02:11, Blackymas ***@***.***> wrote:

﻿

Hello,

it sounds like you are using a wrong name in the blueprint. Please remember that you cannot use a "-" and preferably no special characters.
