### ISSUE TITLE
Home screen button status not correct after returning from swiping to another page

### ISSUE THREAD

**Issue by ks7p** [Blackymas/NSPanel_HA_Blueprint#362]
1. Press one of the physical buttons to turn on a light (not using relays, just HA automation).
2. The button status on the home screen changes to show the light is on. 
3. Swipe to any other screen.
4. Return to home screen by any available means. 
5. The button status on the home screen is turned off.  Light is still on.  
6. I also loose the QR code icon.

What am I doing wrong?  

HA: 2023.2.5
ESPHome: 2023.2.3
NSPanel: USW
no mods to *.tft; no mods to nspanel_esphome.yaml;
device configuration: 
![image](https://user-images.githubusercontent.com/60589833/220196452-12d7826d-abdb-4343-ba35-69965f6a5717.png)

**Comment by Blackymas** [comment]
Hello,

I can not reproduce this

**Comment by ks7p** [comment]
Hello,

ESPHome: 3.1.0
TFT: 3.1.0
Blueprint:  

Thanks for trying to replicate my issue.  I will dig deeper into the trace and report back with what I find.

**Comment by Blackymas** [comment]
Hi,
You have the wrong blueprint otherwise it would also say 3.1.1

**Comment by ks7p** [comment]
Nope, just manually checked the blueprint.  It is in fact 3.1.0, the same as the other components.   I will be analysing the trace tomorrow (Wed) when I have more time.  Will post what I find.  

Just realized that in addition to the version of the Blueprint not showing on boot page, the names of the buttons are also not showing on the home page.  Seems like something is not updating/refreshing correctly.  Will be interesting to understand what is happening.  The time, date, temperature, etc. update just fine.

**Comment by rtenklooster** [comment]
The same issues here. QR code shows only one time, after clicking on it, it won't come back.
3.1.0, fresh install. The same behaviour on two devices (brand new)

**Comment by Krissz55555** [comment]
I have the same problem since the update.  I can't find the solution.

**Comment by ks7p** [comment]
Ok...now I am really confused.  Came in this morning to trace the problem.  It is all working just fine now.  I did nothing.  It has NOT been working for over a week now.  In fact, this is the first time I have seen the button labels ever.  I wonder if there is a timing issue somewhere - my home is quiet right now (electronically).  hmm.

**Comment by Krissz55555** [comment]
I found out what caused this error!  My external thermometer is displayed, but the battery ran out and its status became "unknown".  I replaced the battery and when its status returned to a numerical number, both my panels were immediately restored and are working flawlessly!  So the texts and icons disappear when inappropriate data goes to nspanel.

**Comment by Blackymas** [comment]
as already described, the problem is only present when something cannot be loaded properly.

If some entity or status is not correct, the script does not run to the end.

you can find such problems via your automation and then traces.

some adjustments will also come with v.3.2.

But the general problem is the configuration of your blueprint.
