### ISSUE TITLE
Version "nspanel-lovelace-ui" from joBr99 - Instructions Clarification

### ISSUE THREAD

**Issue by sembeeuk** [Blackymas/NSPanel_HA_Blueprint#363]
I am trying to follow the instructions to correct when "Version "nspanel-lovelace-ui" from joBr99" is already installed, but the ESPHome Binary has already been uploaded. The panel is stuck on the "Waiting for content... "screen. 

1. In the instructions it says to "ESPHome: DEVICE_NAME_upload_tft" and enter a URL. However the service doesn't have a URL entry.
There is a service called ESPHome: DEVICE_NAME_upload_tft_url" - is that the correct one to use, and the instructions need to be adjusted? 

2. If not, what it the correct format of the data field of the original service, as I cannot get the panel to turn white as per the instructions. 

3. How long should it take? Do I need to reboot the panel, or should I just see the screen change?

Kicking myself, as I hadn't touched the panel for months and completely forgot that I had tried to use the other project with little success - didn't recognise the name or anything, so now I am stuck. 

Many thanks.

**Comment by chris24walsh** [comment]
@sembeeuk Yes, there are two services, one with a url parameter and one without. The one without will attempt to use the url defined in the esphome.yaml config. But you can just use the ESPHome: DEVICE_NAME_upload_tft_url service to specify a location pointing to the nspanel_blank.tft (ideally a local url). Btw, you may have to power cycle the nspanel before it will allow the service to update the tft file.
