### ISSUE TITLE
The thermostat also breaks and reverts to German (ein) when entities disappear.

### ISSUE THREAD

**Issue by plasterer41** [Blackymas/NSPanel_HA_Blueprint#364]
The thermostat also breaks and reverts to German (ein) when entities disappear.

_Originally posted by @plasterer41 in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/355#issuecomment-1439759635_

**Comment by Blackymas** [comment]
thanks - we will check

**Comment by Blackymas** [comment]
Is changed in v3.2 
Please update and test :)

https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.2
