### ISSUE TITLE
After Update to ESPHome 2023.2.4 displays stucks in boot screen

### ISSUE THREAD

**Issue by smartmatic** [Blackymas/NSPanel_HA_Blueprint#366]
Hi,

i‘ve updated ESPHome to the latest release 2023.2.4. Now the display is stucking in boot screen.
Restart does not help and Update TFT driver does also not help.

What can i do to solve the issue?

**Comment by thuetti1** [comment]
Habe das gleiche Problem

**Comment by Blackymas** [comment]
Hast du die Beta Version schon probiert? Blueprint, esphome, tft

**Comment by smartmatic** [comment]
Wo liegen die Beta Files?

**Comment by Blackymas** [comment]
im bete repo auf der start seite kannst du oben von main auf beta wechseln

**Comment by intersector** [comment]
I can confirm that i have the same issue but only after the last update of Home Assistant VM

**Comment by smartmatic** [comment]
I have changed some entity IDs but forgot to update the blueprint. After correcting this the panel booted as usual to the home screen. So it would be nice when the blueprint ignore this changes although the entity could not find during startup to prevent a stucking screen.

**Comment by intersector** [comment]
> I have changed some entity IDs but forgot to update the blueprint. After correcting this the panel booted as usual to the home screen. So it would be nice when the blueprint ignore this changes although the entity could not find during startup to prevent a stucking screen.

Saviour thanks! I ifind it a bit of strange because never has been occurred before..
Thanks again. I think that should boot even an entity is offline or changed..

**Comment by thuetti1** [comment]
hab jetzt alles gelöscht nachdem ich bei der Beta nicht mehr auf das Panel kam. Hab die falschen Wlan einstellungen eingetragen und bin dann nicht mehr drauf gekommen. Jetzt läuft alles wieder. beim nächsten Update lese ich erst mal was ich machen muss . Man lernt nie aus. Vielen Dank für die geile Arbeit
Gruß Tobias

**Comment by Blackymas** [comment]
Schön zu hören dass alle ihr Probleme lösen konnten ;)
