### ISSUE TITLE
utf8 text cuts from right side

### ISSUE THREAD

**Issue by mikeS7** [Blackymas/NSPanel_HA_Blueprint#369]
utf8 symbol requires 2 bytes, I've got an issue with truncated text in date field on home page of nextion. For example Monday in Russian is Понедельник which takes 22 bytes.
Is it possible to extend field size? Another solution can be different translation in short form.

**Comment by Blackymas** [comment]
Hi, i will Check 👍

**Comment by Blackymas** [comment]
I have now adjusted the fields so that the maximum number fits with the size of the field.

If this does not fit you will have to adjust it individually via nextion editor.
