### ISSUE TITLE
Update TFT

### ISSUE THREAD

**Issue by IversenT** [Blackymas/NSPanel_HA_Blueprint#370]
### Discussed in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/367

<div type='discussions-op-text'>

<sup>Originally posted by **IversenT** February 23, 2023</sup>
How long time should the update of the tft-display be?
Just got two new white NSpanel and having trouble getting theese updated. 
One EU and one US panel - Updating with the blank TFT file takes about 1-3 min and nspanel_eu/us takes 24+h..
When done is still does not work. 

Have one Grey unit, and this unit is much faster. </div>

**Comment by Blackymas** [comment]
Hi, 10-20 min

**Comment by IversenT** [comment]
Seems like something is happening during uploading of the TFT.

![image](https://user-images.githubusercontent.com/76644450/221236583-83d93d87-ba66-4a68-beb8-abf620d7dfe1.png)

**Comment by IversenT** [comment]
Could there be a firmware issue with the display. The one that works fine is on firmware 69 and the two that are causing trouble is at v. 72.

**Comment by Blackymas** [comment]
you can try to flash the tft with Tasmota

**Comment by TanPau1412** [comment]
> you can try to flash the tft with Tasmota

Hi, I seem to be having the same issue. Not familiar with Tasmota at all though. Could you possibly point me to a link that could show me how to flash the tft file this way?

**Comment by IversenT** [comment]
> you can try to flash the tft with Tasmota

Flashed with nspanel_eu and is (two different panels) using tasmota. No problem.

Still some bug with esphome and flashing the tft. 
Still gets error when trying to “reflash” when back on esphome.
Could be trouble when upgrading to 3.2 etc.

**Comment by Blackymas** [comment]
not sure have never heard or seen this bug before

**Comment by DiggaTS** [comment]
The same problem here. But on the display counts up ... ill wait ... 

![Screenshot 2023-02-28 185443](https://user-images.githubusercontent.com/63748159/221938038-fa47f42e-433b-48e9-83a4-ff22fdd3e20f.png)

**Comment by IversenT** [comment]
> The same problem here. But on the display counts up ... ill wait ...
> 
> Its a fresh new device.
> 
> ![Screenshot 2023-02-28 185443](https://user-images.githubusercontent.com/63748159/221938038-fa47f42e-433b-48e9-83a4-ff22fdd3e20f.png)

If it takes any longer then 2h it will fail regarding if it’s goes all the way. I have tried it 5 times - waiting the full 24h.

**Comment by andersagerskov** [comment]
> > The same problem here. But on the display counts up ... ill wait ...
> > Its a fresh new device.
> > ![Screenshot 2023-02-28 185443](https://user-images.githubusercontent.com/63748159/221938038-fa47f42e-433b-48e9-83a4-ff22fdd3e20f.png)
> 
> If it takes any longer then 2h it will fail regarding if it’s goes all the way. I have tried it 5 times - waiting the full 24h.

Initially you probably need to change the name as per documentation:
https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-Stuck-on-Initializing#2-esphome-name

**Comment by DiggaTS** [comment]
Same issue ... after 5 time hit the Update TFT display it worked. On the display it counts up and after 20min it done ... 

I have try it without - and with ... Same Problem. 

![Screenshot 2023-02-28 185458](https://user-images.githubusercontent.com/63748159/221957262-12349aeb-72cc-4c50-86d0-eb246c08834c.png)

**Comment by Blackymas** [comment]
try with nspanel_blank tft

Tft upload via HA and http and not https?

**Comment by hardusmaritz** [comment]
Same issue as well, tried with http and https (my default).

Is it possible to add the TFT directly onto the nspanel? (Like Tasmota)

**Comment by Blackymas** [comment]
I am closing the ticket as this topic has been discussed many times.

Please use the issue search then you will find some posts and solutions.

The problem here is not the project but how Esphome works.

If you have really big problems you can upload the TFT via Tasmota or directly via Nextion Editor.

There were also already some contributions. A few are also pinned here
