### ISSUE TITLE
Napanel lost qrcode and button name

### ISSUE THREAD

**Issue by mathgameapi** [Blackymas/NSPanel_HA_Blueprint#371]
![B7C9DBB2-2AE4-467A-A725-26E2AFDA0952](https://user-images.githubusercontent.com/703211/221329014-b626035b-cf81-48cb-931f-501e27df72e6.jpeg)
![F1DC0560-C668-4B9E-9F8F-3BF456E9DA25](https://user-images.githubusercontent.com/703211/221329023-74f07e17-bd38-4e14-8e8c-713582e90749.jpeg)

normal case has qrcode and button name 
But sometime those are lost . I swipe to other page and back to front page will become normal

**Comment by Blackymas** [comment]
Which versions do you have installed? It's on the boot page.

Your problem seems to be a local problem.

You can use the automations trace to find your problem

**Comment by mathgameapi** [comment]
> Which versions do you have installed? It's on the boot page.
> 
> Your problem seems to be a local problem.
> 
> You can use the automations trace to find your problem

I am using version 3.1

**Comment by acbone710** [comment]
I am seeing the same exact behavior on both of my NSPanels. US version 3.1.0.

**Comment by Blackymas** [comment]
have you try to install beta repo.

This isnd adjustments in it for the last HA and esphome update which in combination with certain blueprint configurations leads to problems.

**Comment by chris24walsh** [comment]
This is related to the issues I see, not just these buttons but other items on the home page and other pages, #355

**Comment by Blackymas** [comment]
with version 3.2 the problem should be solved.

Version 3.2 will be released soon
