### ISSUE TITLE
Wifi QR encodes only 49 characters

### ISSUE THREAD

**Issue by jichef** [Blackymas/NSPanel_HA_Blueprint#377]
Hi! Sorry if you don't understand my English as I would like. First of all congrats for this project, it's really easy. Anyway, Im trying to put my wifi as a QR code, but it is a little more larger than the QR code can be generated. 

In my case, needed up to 63 characters. This is the "text" to encode:
WIFI:T:WPA;S: -15 characters of SSID- ;P: -22 characters of password- ;H:false;;

Only encodes 49 characters. 
Thank you so much!!

**Comment by Blackymas** [comment]
Hello and thanks ;)

You can use 50 characters - more characters always has an effect on the memory and this is a problem for other functions

Currently it is not intended to enable more characters.

Please create a poll request under disscussions. If many have the wish we have to see what is technically possible.

thx ;)
