### ISSUE TITLE
Show custom information in home page

### ISSUE THREAD

**Issue by atamgp** [Blackymas/NSPanel_HA_Blueprint#379]
First of all, great project!

In the **home page**, by default there are 2 placeholders for :
- temperature
- humidity

Both are not relevant for me and possibly other because I have a thermostat for that next to it :)
I can assume everyone has different products in use which they want to see in home e.g.:

- current power generated by solar panels
- my lg water boiler: current temp, target tempt + mode in 1 string: icon  42 °C/ °45 C (turbo)
- by lg heat pump: incoming water temp/ outgoing in 1 string: icon In 42 °C - Out °45 C
etc etc

Could this made possible/configurable?
Entity page is different as I want more control in the home page.

**Comment by Blackymas** [comment]
I have already built and comes with version 3.2

**Comment by plasterer41** [comment]
> I have already built and comes with version 3.2

Looking forward to it 👍🏼 ETA?

**Comment by Blackymas** [comment]
Is changed in v3.2 
Please update and test :)

https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.2
