### ISSUE TITLE
Ns panel flashed but blue display does not update with blueprint

### ISSUE THREAD

**Issue by hkr086** [Blackymas/NSPanel_HA_Blueprint#381]
Is it possible i get some assistance? I have used your instructions and I can see the ns panel under the esp32, I can also use the relays from HA. But for some reason the UI is not updating. If I configure one of the buttons on the ns panel to switch on a light from the blueprint it works, but if I try to update the display then it reboots and the sonoff software re appears. Am I doing something wrong?

**Comment by Blackymas** [comment]
the flash from the TFT was not successful.

Look again in the docu you seem to have forgotten one point

**Comment by hkr086** [comment]
Thanks man that was it! The video I was looking at was slight differnt then
the current version!
Thank you

**Comment by ltdhoffman** [comment]
What did you miss?  I am having the same issue.
