### ISSUE TITLE
Thermostat turns on AC weather when HA is restarted

### ISSUE THREAD

**Issue by Roger4R** [Blackymas/NSPanel_HA_Blueprint#388]
I've 3 NSPanels model US and use the Climate platform with different Broadlink each.

But every time that HA is restarted some AC is turned On.

Parameters:
Climate to control  = climate.gourmet_ac
Climate control optimistic mode = On

==============
Configuration.yaml 
...

climate:
  - platform: smartir
    name: Gourmet AC
    unique_id: gourmet_ac
    device_code: 1400
    controller_data: remote.broadlink_remote
    temperature_sensor: sensor.broadlink_temperature
    humidity_sensor: sensor.broadlink_temperature

**Comment by Blackymas** [comment]
This is not a problem of the NSPanel but of HA.

Even with a disconnected NSPanel, the climate goes to heat after an HA reboot.

There is also nothing in our programming with which we would turn on heat. we pull the information only from ha.

So it is a general HA problem - I have tested it several times in different combinations.
