### ISSUE TITLE
feature request : US version landscape display orientation

### ISSUE THREAD

**Issue by eknower** [Blackymas/NSPanel_HA_Blueprint#390]
Hi,
I know that you did a lot of work converting the US layout to portrait - but my use case is with US version in landscape mode (actually it's because we use Italian style boxes, so I imagine other people might use this this way as well).

Any chance you can upload the version for US in landscape?

**Comment by Blackymas** [comment]
hi have a look here:

https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/386
