### ISSUE TITLE
HA command to wake-up screen

### ISSUE THREAD

**Issue by pietro4711** [Blackymas/NSPanel_HA_Blueprint#391]
Is there any way to wake up the screen via ha?
Didn’t find any solution…I want to Wakeup the display via a motion sensor without a reload.

and please don’t forget the alarmo panel!

**Comment by Blackymas** [comment]
sure ;)

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/99#issuecomment-1345538330
