### ISSUE TITLE
nswhite uses an unknown service

### ISSUE THREAD

**Issue by backnblack69** [Blackymas/NSPanel_HA_Blueprint#392]
I'm calling it nswhite, i get the following error and it won't add the device.   esphome sees it online and i can see in the logs the buttons, etc work.     

Home Assistant 2023.3.1
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230302.0 - latest

nswhite uses an unknown service
The automation "nswhite" (automation.nswhite) has an action that calls an unknown service: esphome.nswhite_send_command_printf.

This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](https://ha.local.harristree.net:8123/config/automation/edit/1677962376033) and remove the action that calls this service.

Click on SUBMIT below to confirm you have fixed this automation.

**Comment by backnblack69** [comment]
I went back into the automation and updated buttons and ran it again, i had to manually discover the device again and it seems to work.  I don't see that error again at least.  I now have the devices shown.

**Comment by Blackymas** [comment]
thanks for your update ;)
