### ISSUE TITLE
Validation im ESPHome fehlerhaft

### ISSUE THREAD

**Issue by papadiddl1** [Blackymas/NSPanel_HA_Blueprint#396]
Hi,
ich bin nach Anleitung vorgegangen. Blueprint installiert, eine paar Sachen darin konfiguriert und als "NSPanel01 Configuration" Automation gespreichert, im ESPHome dann einen ESP32 (nspanel01) hinzugefügt und alles rein kopiert. Dann kommt schon mal regelmäßig eine Fehlermeldung:
---
NSPanel01 Configuration verwendet einen unbekannten Dienst
Die Automatisierung "NSPanel01 Configuration" (automation.nspanel01_configuration) hat eine Aktion, die einen unbekannten Dienst aufruft: esphome.nspanel01_send_command_text_printf.

Dieser Fehler verhindert, dass die Automatisierung ordnungsgemäß ausgeführt wird. Vielleicht ist dieser Dienst nicht mehr verfügbar oder vielleicht hat ein Tippfehler ihn verursacht.

Um diesen Fehler zu beheben, [bearbeite die Automatisierung](https://192.168.0.10:8123/config/automation/edit/1678102252457) und entferne die Aktion, die diesen Dienst aufruft.

Drücke unten auf SENDEN, um zu bestätigen, dass du diese Automatisierung korrigiert hast.
---
Wenn ich im ESPHome dann das Programm validiere bekomme ich nur Fehlermeldungen.
---
INFO Reading configuration /config/esphome/nspanel01.yaml...
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

esphome: None
  name: nspanel01
  
  [min_version] is an invalid option for [esphome]. Please check the indentation.
  min_version: 2022.10.2 None
  build_path: .esphome/build/nspanel01
script: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:977]
  
  'id' is a required option for [script].
  - [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:977]
    
    Unable to find action with the name 'id'.
    id: page_timer [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:977]
    mode: restart
    parameters: 
      delay: int
    then: 
      - lambda: ESP_LOGD("nspanel", "start page-timer delay %i", int(id(page_timeout).state));
      - delay: !lambda |-
          return delay *1000;
      - lambda: |-
          if (id(disp1_currentpage).state == "home" or id(disp1_currentpage).state == "screensaver" or id(disp1_currentpage).state == "boot" or int(id(page_timeout).state) == 0) {
            ESP_LOGD("nspanel", "no page-jump");
          } else {
            ESP_LOGD("nspanel", "timer->home");
            id(disp1).send_command_printf("page 0");
          }
---
das ist die NSPanel01 Configuration:
---
alias: NSPanel01 Configuration
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: nspanel01
    language: DEU
    weather_entity: weather.home
    outdoortemp: sensor.aussentemperatur
    button_page01_label: ArbZi
    entity01_name: Arbeitszimmer
    entity01: light.arbeitszimmer_licht
---
Versionen:
Home Assistant 2023.3.1
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230302.0 - latest

ESPHome by Nabu Casa | [Fund development](https://esphome.io/guides/supporters.html) | [v2022.3.1 Documentation]

bitte um Hilfe
lg
Dietmar

**Comment by papadiddl1** [comment]
Logfile habe ich auch noch:
Logger: homeassistant.components.automation.nspanel01_configuration
Source: helpers/script.py:409
Integration: Automatisierung (documentation, issues)
First occurred: 12:29:31 (518 occurrences)
Last logged: 15:15:00

NSPanel01 Configuration: Error executing script. Service not found for choose at pos 2: Unable to find service esphome.nspanel01_send_command_printf
NSPanel01 Configuration: Choose at step 2: choice 22: Error executing script. Service not found for call_service at pos 1: Unable to find service esphome.nspanel01_send_command_text_printf
NSPanel01 Configuration: Error executing script. Service not found for choose at pos 2: Unable to find service esphome.nspanel01_send_command_text_printf
NSPanel01 Configuration: Choose at step 2: choice 19: Error executing script. Service not found for call_service at pos 1: Unable to find service esphome.nspanel01_send_command_text_printf
NSPanel01 Configuration: Choose at step 2: choice 25: Error executing script. Service not found for call_service at pos 3: Unable to find service esphome.nspanel01_send_command_printf

**Comment by abidullah** [comment]
ur code has error

esphome:
  name: ${device_name}
  min_version: 2022.10.2

use this format

**Comment by papadiddl1** [comment]
in the file "/config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml" the entry seems correct
##### ESPHOME CONFIGURATION #####
esphome:
  name: ${device_name}
  min_version: 2022.10.2

now i made a fresh install of the blueprint and the panel in esphome. (uninstall and deleting everything that remained) the problem still exists. i have no idea. the "nspanel_esphome.yaml" looks perfectly correct.

**Comment by papadiddl1** [comment]
I found something strange now. when I open the nspanel_xx.tft files in the folder "/config/esphome/.esphome/packages/566b10a3/", than these files are not readable. 

"'utf-8' codec can't decode byte 0xe0 in position 12: invalid continuation byte"

could this be the problem? but they are downloaded during validation.

**Comment by papadiddl1** [comment]
in the trace I have an orange line. 

TRACE TIMELINE:
Triggered by the time pattern at 7. März 2023 um 08:40:00
Define variables entity_long, entity_long_name, entity_back
Choose: Option 19 executed
Stopped because an error was encountered at 7. März 2023 um 08:40:00 (runtime: 0.04 seconds)

Unable to find service esphome.nspanel01_send_command_text_printf

STEP DETAILS:
Executed: 7. März 2023 um 08:40:00
Result:
params:
  domain: esphome
  service: nspanel01_send_command_text_printf
  service_data:
    component: home.time
    message: '08:40'
  target: {}
running_script: false
limit: 10

STEP CONFIG:
service: '{{ command_text_printf }}'
data:
  component: home.time
  message: '{{ time }}'

I hope this helps?

**Comment by janoschpch** [comment]
I'm experiencing this validation issue as well. I think this will be fixed in an upcoming esphome release because the dev version of esphome works just fine.

**Comment by abidullah** [comment]
before u make a install try to clean the build folder 
and make sure u dont have any - in the name , it will sometimes create problems.
and finally after the install is done make sure u have created automations and then use the device name as u mentioned in the yml file and after all done restart the homeassistant.

**Comment by abidullah** [comment]
> ## Hi,
> ich bin nach Anleitung vorgegangen. Blueprint installiert, eine paar Sachen darin konfiguriert und als "NSPanel01 Configuration" Automation gespreichert, im ESPHome dann einen ESP32 (nspanel01) hinzugefügt und alles rein kopiert. Dann kommt schon mal regelmäßig eine Fehlermeldung:
> NSPanel01 Configuration verwendet einen unbekannten Dienst Die Automatisierung "NSPanel01 Configuration" (automation.nspanel01_configuration) hat eine Aktion, die einen unbekannten Dienst aufruft: esphome.nspanel01_send_command_text_printf.
> 
> Dieser Fehler verhindert, dass die Automatisierung ordnungsgemäß ausgeführt wird. Vielleicht ist dieser Dienst nicht mehr verfügbar oder vielleicht hat ein Tippfehler ihn verursacht.
> 
> Um diesen Fehler zu beheben, [bearbeite die Automatisierung](https://192.168.0.10:8123/config/automation/edit/1678102252457) und entferne die Aktion, die diesen Dienst aufruft.
> 
> ## Drücke unten auf SENDEN, um zu bestätigen, dass du diese Automatisierung korrigiert hast.
> ## Wenn ich im ESPHome dann das Programm validiere bekomme ich nur Fehlermeldungen.
> INFO Reading configuration /config/esphome/nspanel01.yaml... WARNING GPIO4 is a Strapping PIN and should be avoided. Attaching external pullup/down resistors to strapping pins can cause unexpected failures. See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins Failed config
> 
> esphome: None name: nspanel01
> 
> [min_version] is an invalid option for [esphome]. Please check the indentation. min_version: 2022.10.2 None build_path: .esphome/build/nspanel01 script: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:977]
> 
> 'id' is a required option for [script].
> 
> * [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:977]
>   Unable to find action with the name 'id'.
>   id: page_timer [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:977]
>   mode: restart
>   parameters:
>   delay: int
>   then:
>   
>   * lambda: ESP_LOGD("nspanel", "start page-timer delay %i", int(id(page_timeout).state));
>   * delay: !lambda |-
>     return delay *1000;
>   * lambda: |-
>     if (id(disp1_currentpage).state == "home" or id(disp1_currentpage).state == "screensaver" or id(disp1_currentpage).state == "boot" or int(id(page_timeout).state) == 0) {
>     ESP_LOGD("nspanel", "no page-jump");
>     } else {
>     ESP_LOGD("nspanel", "timer->home");
>     id(disp1).send_command_printf("page 0");
>     }
> 
> ## das ist die NSPanel01 Configuration:
> ## alias: NSPanel01 Configuration
> description: ""
> use_blueprint:
> path: Blackymas/nspanel_blueprint.yaml
> input:
> **_nspanel_name: nspanel01_**
> language: DEU
> weather_entity: weather.home
> outdoortemp: sensor.aussentemperatur
> button_page01_label: ArbZi
> entity01_name: Arbeitszimmer
> entity01: light.arbeitszimmer_licht
> Versionen: Home Assistant 2023.3.1 Supervisor 2023.01.1 Operating System 9.5 Frontend 20230302.0 - latest
> 
> ESPHome by Nabu Casa | [Fund development](https://esphome.io/guides/supporters.html) | [v2022.3.1 Documentation]
> 
> bitte um Hilfe lg Dietmar

ur code is

lambda: ESP_LOGD("**_nspanel_**", "start page-timer delay %i", int(id(page_timeout).state));
delay: !lambda |-
return delay *1000;
lambda: |-
if (id(disp1_currentpage).state == "home" or id(disp1_currentpage).state == "screensaver" or id(disp1_currentpage).state == "boot" or int(id(page_timeout).state) == 0) {
ESP_LOGD("nspanel", "no page-jump");
} else {
ESP_LOGD("nspanel", "timer->home");
id(disp1).send_command_printf("page 0");
}

where ur device name is nspanel01 but in ur code u have written nspanel

**Comment by abidullah** [comment]
> in the trace I have an orange line.
> 
> TRACE TIMELINE: Triggered by the time pattern at 7. März 2023 um 08:40:00 Define variables entity_long, entity_long_name, entity_back Choose: Option 19 executed Stopped because an error was encountered at 7. März 2023 um 08:40:00 (runtime: 0.04 seconds)
> 
> Unable to find service esphome.nspanel01_send_command_text_printf
> 
> STEP DETAILS: Executed: 7. März 2023 um 08:40:00 Result: params: domain: esphome service: nspanel01_send_command_text_printf service_data: component: home.time message: '08:40' target: {} running_script: false limit: 10
> 
> STEP CONFIG: service: '{{ command_text_printf }}' data: component: home.time message: '{{ time }}'
> 
> I hope this helps?



clean ur build folder by pressing the 3 dots on the device yml file and choose clean build folder

![image](https://user-images.githubusercontent.com/2981996/223556935-02bb3629-4b9e-46d7-9fcc-179c02dee0fe.png)

sometimes it will read the cached compile if there is no changes done to the code and will build the firmware
to avoid this its better to always clean the build folder so the compiler will create new files even if there is no code changes

**Comment by papadiddl1** [comment]
reading your comments, I found the solution: I deinstalled ESPHome AddOn und installed the new version. My version was out of date and did not make an update. Now everything works fine. thank you!

**Comment by lloydbayley** [comment]
Nice one! Well-done! I think I've solved mine too. Mine was more of a segue kind of problem. I was following a guide which linked to another guide for one particular step, however they didn't indicate this, so I continued following it and it wasn't the right way.
I'd uploaded a different firmware. Along the same lines but wrong for this. Once I followed THIS one in full without deviation, it is working perfectly. I can't remember which guide the deviation took me to but I know his way of speaking was painful. Glad you got yours working.

**Comment by abidullah** [comment]
Glad to know that it works.. @Blackymas one more problem solved 👍

**Comment by papadiddl1** [comment]
yeah. but I got another problem. I think I have to make a new issue? i cannot upload the file "nspanel_eu.tft". some errors occure and a message on the panel: model does not match

**Comment by abidullah** [comment]
can you share the screenshot of the error please

**Comment by papadiddl1** [comment]
[11:52:25][D][switch:013]: 'nspanel01 Update TFT display' Turning ON.
[11:52:25][D][nextion_upload:169]: Connected
[11:52:25][D][nextion_upload:175]: Requesting URL: https://192.168.0.10:8123/local/nspanel_eu.tft
[11:52:28][D][nextion_upload:209]: Updating Nextion NX4832F035_011C...
[11:52:28][D][nextion_upload:235]: Waiting for upgrade response
[11:52:28][E][uart:015]: Reading from UART timed out at byte 0!
[11:52:28][E][uart:015]: Reading from UART timed out at byte 0!
[11:52:28][E][uart:015]: Reading from UART timed out at byte 0!
[11:52:29][D][nextion_upload:239]: Upgrade response is  4
[11:52:29][D][nextion_upload:242]: Available 0 : 0x00
[11:52:29][D][nextion_upload:242]: Available 1 : 0x00
[11:52:29][D][nextion_upload:242]: Available 2 : 0x00
[11:52:29][D][nextion_upload:242]: Available 3 : 0x05
[11:52:29][D][nextion_upload:246]: preparation for tft update done
[11:52:29][D][nextion_upload:283]: Allocating buffer size 65536, Heap size is 119284
[11:52:29][D][nextion_upload:305]: Updating tft from "https://192.168.0.10:8123/local/nspanel_eu.tft" with a file size of 212005 using 65536 chunksize, Heap Size 59548
[11:52:29][D][nextion_upload:044]: Requesting range: bytes=0-16383
[11:52:30][E][uart:015]: Reading from UART timed out at byte 0!
[11:52:30][E][uart:015]: Reading from UART timed out at byte 0!
[11:52:39][E][uart:015]: Reading from UART timed out at byte 0!
[11:52:39][E][uart:015]: Reading from UART timed out at byte 0!
[11:52:39][E][uart:015]: Reading from UART timed out at byte 0!
[11:52:39][D][nextion_upload:316]: Heap Size 54700, Bytes left 195621
[11:52:39][D][nextion_upload:044]: Requesting range: bytes=16384-81919
WARNING nspanel01.local: Connection error occurred: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 520, in send_message_await_response_complex
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 520, in send_message_await_response_complex
    await fut
  File "/usr/local/lib/python3.9/dist-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/dist-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 303, in _keep_alive_loop
    await self._ping()
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 628, in _ping
    await self.send_message_await_response(PingRequest(), PingResponse)
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 537, in send_message_await_response
    res = await self.send_message_await_response_complex(
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 522, in send_message_await_response_complex
    raise TimeoutAPIError(
aioesphomeapi.core.TimeoutAPIError: Timeout waiting for response for <class 'api_pb2.PingRequest'> after 10.0s
INFO Disconnected from ESPHome API for nspanel01.local
WARNING Disconnected from API
INFO Successfully connected to nspanel01.local
[11:52:59][E][uart:015]: Reading from UART timed out at byte 0!
[11:52:59][W][nextion:078]: Nextion is not connected! 
[11:53:00][E][uart:015]: Reading from UART timed out at byte 0!
[11:53:00][W][nextion:078]: Nextion is not connected! 
[11:53:00][E][uart:015]: Reading from UART timed out at byte 0!

**Comment by abidullah** [comment]
https://192.168.0.10:8123/local/nspanel_eu.tft is the error

don't use https. try using http

to confirm if the link is valid. open the same link in the browser and if you get the download file then the link part is ok

**Comment by papadiddl1** [comment]
i tried http. but than i get an empty download. i think home assistant disables http.

**Comment by abidullah** [comment]
does it work with the browser if you paste the same link
I mean when you open the same url on the browser , it should download the file

**Comment by abidullah** [comment]
does it work when you use  https

try these links and let me know when one downloads the file


https://192.168.0.10:8123/local/nspanel_eu.tft

http://192.168.0.10:8123/local/nspanel_eu.tft

**Comment by papadiddl1** [comment]
https is okay. http says ERR_EMPTY_RESPONSE

**Comment by abidullah** [comment]
try restarting the HA

**Comment by papadiddl1** [comment]
do i have a problem with HA? when I connect via http://<ipadress> i do not get a response. connecting via https:// works, but says that the website is unsecure (certificate is invalid). but that's my default way of connecting :)

**Comment by abidullah** [comment]
its ok, just to make sure all the services work fine, its better to restart the HA.

**Comment by abidullah** [comment]
> do i have a problem with HA? when I connect via http:// i do not get a response. connecting via https:// works, but says that the website is unsecure (certificate is invalid). but that's my default way of connecting :)

yes the certificates have expired, you need to recreate them.

**Comment by papadiddl1** [comment]
yeah i have restartet HA. no change.
12:22:01][D][nextion_upload:175]: Requesting URL: http://192.168.0.10:8123/local/nspanel_eu.tft
[12:22:01][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.0.10:8123/local/nspanel_eu.tft; Error: connection lost, retrying (1/5)
[12:22:01][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.0.10:8123/local/nspanel_eu.tft; Error: connection lost, retrying (2/5)
[12:22:02][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.0.10:8123/local/nspanel_eu.tft; Error: connection lost, retrying (3/5)
[12:22:02][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.0.10:8123/local/nspanel_eu.tft; Error: connection lost, retrying (4/5)
[12:22:02][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.0.10:8123/local/nspanel_eu.tft; Error: connection lost, retrying (5/5)
[12:22:03][D][nextion_upload:324]: Restarting Nextion

**Comment by papadiddl1** [comment]
> > do i have a problem with HA? when I connect via http:// i do not get a response. connecting via https:// works, but says that the website is unsecure (certificate is invalid). but that's my default way of connecting :)
> 
> yes the certificates have expired, you need to recreate them.

they are recreated automatically and should be okay. 
Ausgestellt am	Dienstag, 31. Januar 2023 um 18:51:58
Gültig bis	Montag, 1. Mai 2023 um 19:51:57

**Comment by abidullah** [comment]
which browser do you use

try clearing the cache of the browser
don't use ingnitio mode
try disabling the firewall if there is any

**Comment by papadiddl1** [comment]
it is chrome. i reset it an try again

**Comment by papadiddl1** [comment]
no change. error still exists. with https HA tries to load it and the panel display "wrong model". I have also tried https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft
same result.

**Comment by papadiddl1** [comment]
okay. i try with nextion editor. thanks for your patience

**Comment by abidullah** [comment]
or you can do this

1. Set baud_rate: 9600 in the esphome-yml file and flash it
2. Upload a tft-file
3. Set baud_rate: 115200 back to original-value in the esphome-yml file and flash it.

The installation of the tft with 115200 tooks very long, because of the low baud-setting and the new tft with support for all the required charakters to support the new languages has a size of 8MB.
