### ISSUE TITLE
Weather displays mix of imperial and metric

### ISSUE THREAD

**Issue by kchiem** [Blackymas/NSPanel_HA_Blueprint#397]
Temperature is displayed in F
Wind speed in km/h
Rain amounts in mm

**Comment by Blackymas** [comment]
?

**Comment by kchiem** [comment]
In the weather forecast when you click on the weather icon on the home page:

![IMG_0247](https://user-images.githubusercontent.com/17679003/223325760-4ce90f6b-fcf5-4760-8bf4-306da338cead.jpg)

It should be using this weather entity from WeatherFlow:

![ScreenClip](https://user-images.githubusercontent.com/17679003/223325722-374e5405-c8cd-4dd5-a40d-1062c9c28c18.png)

It seems to be off by one as well.  What it's showing as tomorrow is actually for today.

**Comment by Blackymas** [comment]
I'll see how I can convert it

**Comment by roblamoreaux** [comment]
In the Blueprint the units are hardcoded. Like:
 '{{state_attr(weather_entity,"wind_speed") | round(0)}} km/h'
Changing them to 
'{{state_attr(weather_entity,"wind_speed") | round(0)}} {{state_attr(weather_entity,"wind_speed_unit")}}'

Makes it display the correct units 
Similarly
  '{{state_attr(weather_entity,"forecast")[0].precipitation| round(1)}} mm'
can become
'{{state_attr(weather_entity,"forecast")[0].precipitation| round(1)}} {{state_attr(weather_entity,"precipitation_unit")}}'

**Comment by Blackymas** [comment]
yes we know we will try to improve it with a hotfix after the 3.2 release
