### ISSUE TITLE
Feature request: support for hourly weather forecast

### ISSUE THREAD

**Issue by kchiem** [Blackymas/NSPanel_HA_Blueprint#399]
Can the weather forecast support showing an hourly forecast?  I find knowing the weather for the day to be more useful at the start of the day, than a forecast for future days.  Weatherflow has an hourly forecast entity that looks like this:

![ScreenClip](https://user-images.githubusercontent.com/17679003/223329350-0bb65463-6591-4728-b5af-bc1a94a1f6cc.png)

![ScreenClip](https://user-images.githubusercontent.com/17679003/223329369-66e78787-b734-4499-b9a8-ca5420453822.png)

**Comment by kchiem** [comment]
I think there's room on a page for 8-12 lines of:

[weather-icon] [hour] [wind speed] [rain total if non-zero]

**Comment by kchiem** [comment]
> What you can do is use the entity page for this and store the sensors there.

What do you mean by the entity page?  Do you mean one of the four available with 8 buttons each?  The only sensors those buttons accept are binary sensors.

**Comment by Blackymas** [comment]
I mean entity card page

See here:
https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.1.0

**Comment by kchiem** [comment]
It doesn't seem to be working very well there..

![IMG_0249](https://user-images.githubusercontent.com/17679003/223568563-e4f76ae4-76dc-4707-b58e-78dfdb2ee3ab.jpg)

**Comment by Blackymas** [comment]
mh - with the length of the text it will be difficult anyway

because already 8 fields in the size as you use it now is the display full. You simply do not have more space

**Comment by Blackymas** [comment]
at the moment i don't see a solution for this.

But you can create a poll under discussions. If more people have this wish, I'll see what is possible.

**Comment by edwardtfn** [comment]
- #399 
- #426 
- #831 
- #1228
