### ISSUE TITLE
Right button triggers on reboot

### ISSUE THREAD

**Issue by deejaybeam** [Blackymas/NSPanel_HA_Blueprint#4]
Hi
First of all I would like to say that this is an awesome project and I love it!

Configuration of the BETA Blueprint has an issue on reboot, because the trigger ```id: right_button_press``` is set to off, it toggles a light assigned to the right button on a reboot. 
I recomend to set this to ```value_template: '{{ states(right_button) is match "on" }}'``` like it is for the left button

**Comment by Blackymas** [comment]
hi yes I know - I work on it

**Comment by Blackymas** [comment]
Done in v2.0.0
