### ISSUE TITLE
Service to play rtttl melody

### ISSUE THREAD

**Issue by tbemindt** [Blackymas/NSPanel_HA_Blueprint#403]
I have a custom esphome running on my nspanel at the moment, but I don’t find the time to create all the things I want. I think this project might actually fit perfectly for all my needs. One thing I could not find anything about, but I use at the moment, is a service to play an rtttl ‘ringtone’ on the panel. I use it to give audible feedback (like a tritone), also for actions triggered by another button. Should be fairly easy to implement and use I think. What do you think?

**Comment by Blackymas** [comment]
the service has been around for a long time 

https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.0.0

**Comment by tbemindt** [comment]
Happy to hear. Sorry, did not find it in the features at first.
Will try to install it today. Thank you for all the good work!
