### ISSUE TITLE
FR  Fan speed control popup

### ISSUE THREAD

**Issue by sparkydave1981** [Blackymas/NSPanel_HA_Blueprint#404]
Unless I'm doing something wrong, I can only turn my fans on/off.  It would be great if there was a popup for speed setting similar to how light brightness can be controlled.

**Comment by Blackymas** [comment]
is not available at the moment - we will check what we can do

**Comment by bajangti** [comment]
I am interested in this FR too. I have a number of ceiling fans that I can turn on/off and would love to have the long press/popup which adjusts speed.

**Comment by edwardtfn** [comment]
Similar requests:
- #791
- https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/718#discussioncomment-5786106

**Comment by edwardtfn** [comment]
I've just submitted #897 which will add a fan speed control page. Hopefully this gets all the way to the next release to `main`.

**Comment by edwardtfn** [comment]
Solved on `dev`.
Will be available with the next release.
