### ISSUE TITLE
FR Provide support for calling services

### ISSUE THREAD

**Issue by sparkydave1981** [Blackymas/NSPanel_HA_Blueprint#406]
It would be great if the HA call_service was an option for either the physical buttons or the TFT displayed buttons.  This way we could directly code the service_call into the action via the Blueprint rather than having to create a script in HA and then assigning the button to that script.

eg: I would like to use the two physical buttons to provide fan speed up and down control using the existing HA service_calls fan.increase_speed / fan.decrease_speed

Similarly it would be good to use the two buttons for light dimming up/down.

**Comment by Blackymas** [comment]
this function will come for the hardware buttons with version 3.2.

But we will probably only bring it for the two HArdware buttons and not for all other buttons.

Wait for version 3.2 should not take much longer
