### ISSUE TITLE
thermostat control non-responsive

### ISSUE THREAD

**Issue by jaredgudnason** [Blackymas/NSPanel_HA_Blueprint#412]
I've set the thermostat control to control my hot tub, which exposes a climate device.
the screen shows the current_temperature, and the state (off - when not heating), but the up / down arrows are unresponsive to changing the set temperature.
![Screenshot 2023-03-09 164700](https://user-images.githubusercontent.com/34224320/224186121-8007bb2f-c56d-4384-82dd-6bb024d6ffef.png)

![Screenshot 2023-03-09 164545](https://user-images.githubusercontent.com/34224320/224185969-5154a966-a9cf-4337-bfad-d84d247ba438.png)

Climate to control setting is pointing at the Spa Thermostat.
the Indoor temperature sensor is pointing at a template sensor which is reading the spa current_temperature value.

**Comment by Blackymas** [comment]
when the thermostat is off we also do not respond to up and down.

Turn on the Climate via the on button and you can use the buttons.

**Comment by jaredgudnason** [comment]
the on/off button is also non-responsive /  doesn't work

and the way this particular climate control works, when you change the set
temperature, it will then turn on.  ON=heat being supplied. OFF = no heat.
the only writable value is the set temp.

**Comment by Blackymas** [comment]
in dev version you will find the new climate version

or follow this issue
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/848
