### ISSUE TITLE
Date/time formats

### ISSUE THREAD

**Issue by armandom123** [Blackymas/NSPanel_HA_Blueprint#415]
First off, thank you.  Love the work that's been put into this project!

I was hoping to find a way to change the date and time format to a more "North American" setup.  i.e. Month/Day and 12-hour clock.

Please let me know if I've missed something in the settings, and if not, whether this is something that could be added in the future.

Thanks again!

**Comment by armandom123** [comment]
Should've checked closed issues… I see the response: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/338

**Comment by Blackymas** [comment]
can you send me an exact example of how you want it?

Then I can see if I can build something

**Comment by armandom123** [comment]
For sure. Something like
March 3 for date and 9:52pm for time. 
3/12/23 would also work.  

Thanks!

**Comment by Blackymas** [comment]
we will check

**Comment by edwardtfn** [comment]
So, on this main screen (just as an example) you would like to see the time as "10:21AM" and the next line with the date would be "Sunday, 03/19", is that correct?

![image](https://user-images.githubusercontent.com/94725493/226758232-84a78b13-8fb4-4c71-95f4-e54a6ffe4dab.png)

**Comment by Blackymas** [comment]
@edwardtfn 
I think we should refer only to official formats

https://www.datumsformat.de

**Comment by edwardtfn** [comment]
> @edwardtfn I think we should refer only to official formats
> 
> https://www.datumsformat.de

Sure!

**Comment by Blackymas** [comment]
yes then we have

DE/EU: DD.MM + HH:MM

US: M/D + H:MM AM/PM

EN: DD/MM + HH:MM

**Comment by kmullins10923** [comment]
I would also like to see this as a feature if it is at all possible. It would make the experience for guests and people not used to a 24hr clock much better.

**Comment by edwardtfn** [comment]
> I was able to get the time set to 12hr by editing the blueprint yaml with the edits I found in this pull.
> 
> [acbb4ab](https://github.com/Blackymas/NSPanel_HA_Blueprint/commit/acbb4abe9e27873ff01792f7adce8fd2f2752646)

It's great that you already mapped all the points needing to be changed and it's not that much changes. Thanks for that!!
I will wait for the evaluation of PR #498 first, as we are changing the very same lines of code for diferent purposes, so we make easier merging the time/date format.

**Comment by Blackymas** [comment]
jetzt verfügbar in v3.2.1

https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v3.2.1
