### ISSUE TITLE
Screen revert

### ISSUE THREAD

**Issue by kristianolofsson** [Blackymas/NSPanel_HA_Blueprint#417]
For some strange reason my screen is tilted 45d right. The physical buttons are labeled on the right side and time/temp is also rotated. How come this happened? I do not see any rotate option.

![13FD645D-E0E2-4900-98EF-4FFEE6BEF00B](https://user-images.githubusercontent.com/7191232/224468875-2994c0cf-8014-4538-862b-213fe248f884.jpeg)

**Comment by Blackymas** [comment]
Looks like you uploaded the us tft version.

But for your display you need the eu tft

**Comment by kristianolofsson** [comment]
Thanks!
