### ISSUE TITLE
Home screen empty after scrolling through entity list

### ISSUE THREAD

**Issue by andytuinman3** [Blackymas/NSPanel_HA_Blueprint#421]
Sometimes when I scroll through the entity list it loads very slow. But after that when I go back to the homescreen it's all empty. I cannot get back to QR and entity list. I can go to the buttons on all 4 pages. But no QR and entity list. Also all weather and thermostat info is gone. 

I have to reboot to get everything working again. 

Before: 
![1678556460603](https://user-images.githubusercontent.com/4999564/224503573-71c92e1f-8c31-4bb3-b4bd-d15187235a89.jpg)

After:
![1678556460570](https://user-images.githubusercontent.com/4999564/224503580-54e531ac-afab-4a0d-967c-a2abcee91558.jpg)

**Comment by Blackymas** [comment]
Hello,
Here you probably have a problem with some entity you selected in the blueprint or similar. You can look at the traces under automations to see what is wrong or check your blueprint again.

Alternatively please use the search function at the issues the topic was already there once

**Comment by andytuinman3** [comment]
My apologies. I have scrolled through the issues and couldn't find it. Probably didn't look hard enough. I'll check the traces.

**Comment by andytuinman3** [comment]
I have removed some entities and now it works fine. It's strange that the problem was my 2 door contact sensors which just state on or off that gave the problems. It just hangs and cannot show them.

Traces are not generating during this error. They are just blank. Every other trace works fine.
