### ISSUE TITLE
Unable to find service esphome.${device_name}_send_command_text_printf

### ISSUE THREAD

**Issue by giannoug** [Blackymas/NSPanel_HA_Blueprint#425]
I'm trying to install NSPanel_HA_Blueprint but I'm stuck at the following issue:

```
Logger: homeassistant.components.automation.nspanel_bath_configuration
Source: helpers/script.py:409
Integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 11:09:36 PM (2 occurrences)
Last logged: 11:09:36 PM

NSPanel bath Configuration: Choose at step 2: choice 2: Error executing script. Service not found for call_service at pos 2: Unable to find service esphome.${device_name}_send_command_text_printf
NSPanel bath Configuration: Error executing script. Service not found for choose at pos 2: Unable to find service esphome.${device_name}_send_command_text_printf
```

(I've replaced my device's name with ${device_name}).

I tried both `main` and `beta` branches. Any ideas?

**Comment by Blackymas** [comment]
if you change your name to esphome you need to reflash your display best and add in ha nue.

I am not quite clear what you have done

**Comment by giannoug** [comment]
I believe that the blueprint (or ESPHome? even though all my devices use dashes) has issues with hostnames that use dashes. The hostname of my device is nspanel-bathroom

**Comment by Blackymas** [comment]
please don't get me wrong but it is all documented and also that you should not use "-".

Please read the documentation again or watch the videos that other Youtuber have created, there you see step by step what to do.

https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki
