### ISSUE TITLE
BLE proxy support

### ISSUE THREAD

**Issue by onsmam** [Blackymas/NSPanel_HA_Blueprint#429]
Hi,

is it possible to add BLE proxy support?

i think some things need to be removed, ive tried to add BLE proxy to the yaml but then the file img is to large.. by 0.08%...

**Comment by Blackymas** [comment]
yes this is also you're problem and the reason why we remove BLE Proxy

**Comment by deejaybeam** [comment]
see also here: https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/206
