### ISSUE TITLE
Rotating Screen US Version

### ISSUE THREAD

**Issue by techunleadit** [Blackymas/NSPanel_HA_Blueprint#432]
Hi,
my warmest congratulations for this beautiful edition! I wanted to ask, I live in Italy, but I'm using the US version due to the fact that it fits in the box (called 503). 
Unfortunately by inserting the tft us, I noticed that the screen is for the portrait version while I need it to be in landscape. Is there any way to do this or do I have to use the EU version of the tft file? 

Thank you

**Comment by Blackymas** [comment]
you can use eu version - but I think not all fields are fit perfect. 

But try and let me know

**Comment by techunleadit** [comment]
@Blackymas If I make a landscape version of the US model is it ok for you? I will use the hmi file.

Thanks

**Comment by tomkolp** [comment]
I also use the us version horizontally.  I uploaded tft eu, but I have the impression that the touch works slowly.  This is my first nspanel and I have no comparison.

**Comment by Blackymas** [comment]
when touch works incorrectly then you have a problem with your WiFi

**Comment by tomkolp** [comment]
![Screenshot_20230403_220834_Home Assistant](https://user-images.githubusercontent.com/39633242/229616274-0b9c72f9-9160-4a0a-b156-df0a2403dd4e.jpg)
That would fit.

**Comment by Blackymas** [comment]
> @Blackymas If I make a landscape version of the US model is it ok for you? I will use the hmi file.
> 
> Thanks

Sure, that should work very well. Please wait until v3.2.2 is released, which should be online tomorrow or the day after.

You can then send it to me.

**Comment by v0ltage120** [comment]
Hello! Have you been able to create a US landscape version ? can we have that feature in 3.3 (blueprint option?)
Thank you

**Comment by Scannow** [comment]
Hello, first of all thank you for this amazing project!
I'm interested to the landscape mode too, Is It already available? Otherwise, how can I build It? Thanks.

**Comment by edwardtfn** [comment]
A new TFT for US panel in landscape position was created in `dev` and will be available with the next release.
