### ISSUE TITLE
NSPanel won't initialize, stuck on init screen and when it did work, button titles not displaying

### ISSUE THREAD

**Issue by livlif2dfullest** [Blackymas/NSPanel_HA_Blueprint#435]
ESPHome version: 3.1.0
HA version: 2023.3.3

I boot my NSPanel and I get an IP address on the init screen and the blueprint version (3.1.0), however, it never moves on to the display of the panels.  It was working, however, I wanted it to use a hidden SSID, so I downloaded the [nspanel_esphome.yaml](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/nspanel_esphome.yaml) file and pasted that into ESPHome for my NSPanel configuration, updated the substitutions and added the fast_connect: true under the wifi section. Installed that to the NSPanel and then switched over to the 5v, NSPanel booted up showed the IP address, so I know it's connecting to WiFi, showed the blueprint version so I'm assuming that the blueprint partially ran, however, in the init of the blueprint I get an "expected int for dictionary value @ data['message']" in the init trigger, unsure if this is the cause of the hang or not.  I can run the service "ESPHome: kitchen_nspanel_send_command_printf" with the cmd "page 0" and it shows what I expect, but just won't get there on its own.  And with this same configuration prior to me making the changes for the hidden SSID, the physical button titles don't display.  They're supposed to be 'Counter' and 'Food Prep', but they don't show up, just the line below where the title is supposed to be.  I did modify the blueprint to display the full USA time HH:mm AM/PM as well as changed to show the abbreviated days instead of the full day
 
Configuration: [kitchen_nspanel.yaml.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10961992/kitchen_nspanel.yaml.txt)
Blueprint: [nspanel_blueprint.yaml.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10962046/nspanel_blueprint.yaml.txt)
Blueprint entries: [KitchenNSPanelAutomation.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10961893/KitchenNSPanelAutomation.txt)
TFT (in case someone wants the full USA view of date/time): [nspanel_us.zip](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10971658/nspanel_us.zip).
Trace: [trace automation.kitchen_nspanel_configuration 2023-03-13T20_29_06.080247+00_00.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10961889/trace.automation.kitchen_nspanel_configuration.2023-03-13T20_29_06.080247%2B00_00.txt)
![nspanel_us](https://user-images.githubusercontent.com/94875936/225083785-da7675d4-9a3c-41ca-8f27-ee50b99f17d4.jpg)

**Comment by livlif2dfullest** [comment]
I called the service "ESPHome: kitchen_nspanel_send_command_printf" with the cmd "page 0" a couple times and now it's displaying the home page, so hopefully the trace and information above will help you figure out why it doesn't work the first time it's loaded.  But now that it works as I expect, the button texts on the home page; home.left_bt_text and home.right_bt_text aren't being set, they're blank and I believe that the lines under the text are supposed to change color or something when they're "on", but it's not.  So those are the 2 issues I'm having right now, let me know if there's anything you want me to do to help troubleshoot further.

**Comment by charlyschulte** [comment]
i have the same problem @livlif2dfullest thanks for the temp fix, it helped me a lot

**Comment by Blackymas** [comment]
unfortunately, this is the wrong approach.

If the display does not jump to the home page, something is wrong when loading the blueprint.

Did not fix the problem.

As I see you have also written in the Config. Surely something went wrong or you did not configure the blueprint properly.

Another issue could be that something is wrong with an entity or similar / is not accessible.

In your case restart the nspanel and check first if all 3 versions are shown on the boot page.

If new go to traces in your automation. After that look for the right timestamp and see where the orange line runs and where it stops.

The orange line in the trace must run to the end only then it jumps to Home Page.

You can see here what I mean
1. How to create "issues" when I have a problem
https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know

**Comment by livlif2dfullest** [comment]
The only thing I wrote in the config was the fast_connect: true under wifi. It's booted to the home page everytime without error in the trace since I called the page 0 cmd a couple times. Same thing happened to me previously before I switched to the fast_connect. It's booted 3 times now w/o issue, other than the text not displaying for the 2 physical buttons. I see in the blueprint where they are set but when I look at the trace, the calls aren't there so I'm a bit confused why I can't find them in the trace and there's no longer errors in the init trace so I'm unsure why they would be excluded.

**Comment by haywiremk** [comment]
I have as similar issue I am not debugging.  I have one panel that will just hang on the boot screen with all three lower items loaded.  Sometime just a reboot fixes it.  Just started randomly in the last week.  Fine before then.  Looking in traces I see on the init flow this error

4
Executed: March 14, 2023 at 2:17:52 PM
Error: expected int for dictionary value @ data['message']

Not sure exactly how to correlate this but seems it fails in the button iteration.  Now need to figure out what device.  Right now it is 100% but has been hit or miss all week.  Before never had an issue.

**Comment by haywiremk** [comment]
OK for my case finally get more familiar with traces.  It has to do with cover.  I have a group helper.  It has 3 blinds.  1 is in a weird state and reporting state as opening.  This state is not in the btn_pic.  Only open and closed.  I think you should add opening and closing in there as well.  As far as I can tell there is not "else" catch all for the button.

**Comment by livlif2dfullest** [comment]
Figured out my issue, it was a wrong sensor for the outdoortemp, was using weather so it was trying to cast 'sunny' to an int which was causing an error preventing the automation from continuing.  Once I switched it to a sensor that returned the numeric temperature for the state everything is working as expected now, the text above the physical buttons and the init logic.
