### ISSUE TITLE
Call a service with left or right hardware button

### ISSUE THREAD

**Issue by geni0602** [Blackymas/NSPanel_HA_Blueprint#436]
Hi, 

Is it possible to configure call a service for the NSPanel left and right buttons? 
 
For example, with toggle.light I can define the brightness, when I turn on the light. I use this with my bedroom light. When I turn it on from the bed button it goes to 10% brightness and when I press the main switch it is always restored back to 100% brightness.
Currently when I turn on the light from the NSpanel it stays dimmed, if that was the last state.  

Thx

**Comment by Blackymas** [comment]
with version 3.2 there will be a custom action field for the HW buttons.

with it you can then deposit programming as you like

**Comment by geni0602** [comment]
@Blackymas thanks for your replay. That's really nice to hear.
