### ISSUE TITLE
Display won't connected unless I change baud rate to 9600

### ISSUE THREAD

**Issue by asperkins** [Blackymas/NSPanel_HA_Blueprint#439]
I'm seeing "Reading from UART timed out at byte 0!" and the display fails to connect.

I had to fork and update the yaml to set baud_rate: 9600 to get past it.

##### UART FOR NEXTION DISPLAY #####
uart:
  tx_pin: 16
  rx_pin: 17
  baud_rate: 9600
  id: tf_uart

**Comment by Blackymas** [comment]
Should actually no longer be necessary

**Comment by asperkins** [comment]
Funny thing is... I had to set it to 9600 but after waiting forever for the tft file to upload I had to change it back to the higher speed for it to work. Regardless, it seems to be good now.

**Comment by deejaybeam** [comment]
Hi
This sometimes happens when (first) installing this project on new devices.
In our tft (full-version or blank) we set the nextion display to 115200, so after installing one of these tft´s the display should work with 115200. To faster install tft with 9600, it is also possible to install the smaller blank.tft, change esphome to 115200 and then install the "full" tft with the higher speed.

**Comment by asperkins** [comment]
I wish I'd figured out the "blank" tft route, cuz uploading the full tft at 9600 took a loooooong time. :)

**Comment by Blackymas** [comment]
https://github.com/Blackymas/NSPanel_HA_Blueprint/tree/main/custom_configuration

**Comment by TanPau1412** [comment]
> Hi This sometimes happens when (first) installing this project on new devices. In our tft (full-version or blank) we set the nextion display to 115200, so after installing one of these tft´s the display should work with 115200. To faster install tft with 9600, it is also possible to install the smaller blank.tft, change esphome to 115200 and then install the "full" tft with the higher speed.

Hi, I am really stuck here for days now :(
If I change the baud rate to 9600 I am able to upload the blank tft, but as soon as I change the baud rate back to 11520, it get this :
[09:35:05][W][nextion:078]: Nextion is not connected! 
[09:35:05][E][uart:015]: Reading from UART timed out at byte 0!
when I change it back to 9600 it then connects but I am not able to upload the tft(full). It takes +- 3 hours and then fails afterwards. @deejaybeam Please can you help me. I have 2 panels (exactly the same US versions) The one updated perfectly, but the second on is giving me this problem.

**Comment by deejaybeam** [comment]
Hi
What you could try:
1. Set baud to 9600 in esphome: required to establish communication beteween esp and nextion
2. flash blank.tft
3. power-cycle the panel
4. check logs in esphome: nextion should NOT be connected, this indicates that nextion is on 11520 and esp on 9600
4a if not try to flash blank.tft again
5. set esphom-config baud-rate to 115200 back again -> now connection esp->nextion should work

If this all does not help, you may try to install full tft via ttl-converter (https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/166)

Good luck!

**Comment by TanPau1412** [comment]
> Hi What you could try:
> 
> 1. Set baud to 9600 in esphome: required to establish communication beteween esp and nextion
> 2. flash blank.tft
> 3. power-cycle the panel
> 4. check logs in esphome: nextion should NOT be connected, this indicates that nextion is on 11520 and esp on 9600
>    4a if not try to flash blank.tft again
> 5. set esphom-config baud-rate to 115200 back again -> now connection esp->nextion should work
> 
> If this all does not help, you may try to install full tft via ttl-converter (#166)
> 
> Good luck!

@deejaybeam - thanks for the swift reply and detailed steps. I am going to try exactly as set out above and will revert.

**Comment by deejaybeam** [comment]
strange...
In the blank.tft bauds - (not baud) should be set to 115200, this "should" store the nextion baud to boot-resistant baud-rate
but in your case it looks like nextion switches back to 9600 after reboot...
try to download this one (new compiled):
https://github.com/deejaybeam/NSPanel_HA_Blueprint/raw/dev/custom_configuration/nspanel_blank.tft

**Comment by TanPau1412** [comment]
> strange... In the blank.tft bauds - (not baud) should be set to 115200, this "should" store the nextion baud to boot-resistant baud-rate but in your case it looks like nextion switches back to 9600 after reboot... try to download this one (new compiled): https://github.com/deejaybeam/NSPanel_HA_Blueprint/raw/dev/custom_configuration/nspanel_blank.tft

@deejaybeam No luck here :( Still the same issue after rebooting where it only connects with 9600 baud rate on ESP. Will a copy of the log file maybe give some more insight?
