### ISSUE TITLE
Support for the nspanel relays for shutters

### ISSUE THREAD

**Issue by kroon040** [Blackymas/NSPanel_HA_Blueprint#442]
Hi,

I want to use the 2 relays also for controlling the motors of my shutters. I see that something is already possible in esphome, could this also be supported in the HA_Blueprint?

https://esphome.io/cookbook/dual-r2-cover.html

**Comment by deejaybeam** [comment]
Not in the blueprint, but you can create e.g. a template cover in HA and assign the relays here:
https://www.home-assistant.io/integrations/cover.template/

**Comment by kroon040** [comment]
Yes, that I know. But I also want to use the blueprint voor display is that than possible?

**Comment by Blackymas** [comment]
have a look here 

https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.2

now you have a custom action for HW Buttons
