### ISSUE TITLE
Notification in 3.2 cannot be acknowledged

### ISSUE THREAD

**Issue by Floppe** [Blackymas/NSPanel_HA_Blueprint#447]
Hi,

I'm not 100% sure about this as I have modified the HMI and blueprints, but I have not touched the notification section. So could it be that the notifications cannot be acked by the TFT screen. Only by the service call?

**Comment by Floppe** [comment]
Ok, thanks, I missed checking V3.0 release notes. I removed the logic for my display so the buttons work, as I think they should do.

https://github.com/Floppe/NSPanel_HA_Blueprint/commit/54dce74027b40f4f51e426c321904937e2c299ab

**Comment by deejaybeam** [comment]
The reason for this is, that we use the same notification-page also to confirm actions of buttons.
