### ISSUE TITLE
Chinese Fonts Support

### ISSUE THREAD

**Issue by lingxide** [Blackymas/NSPanel_HA_Blueprint#449]
Dear Team, 

Much appreciated for your hardwork on this firmware that makes NSPanel from useless to super powerful. As its original firmware supports Chinese display, I wonder if it possible we also add such support back in this f/w, it's still a little bit unconvenient for my family to use who barely knows English. 

Considering Chinese fonts may require extra space size, I am not very certain if it can still integrate a standard font library. If not possible, please also let me know I will try to find out some solution that only contains basic Chinese texts. 

Thanks again.

**Comment by Blackymas** [comment]
In version 3.2 I have unlocked some chinese characters.

Version 3.2 is in beta repo nd I think in the next days in stable :)
