### ISSUE TITLE
Dynamic QR Code

### ISSUE THREAD

**Issue by robsonfelix** [Blackymas/NSPanel_HA_Blueprint#452]
Users who have dynamic QR Codes such as WiFi passwords, for example, would greatly benefit from such capability.

**Comment by Blackymas** [comment]
what exactly do you mean by that?

Isn't it enough to send the QR code to the panel via HA Servcie?

**Comment by Blackymas** [comment]
We will not develop this further for the time being, as we do not see any added value in it at the moment.
