### ISSUE TITLE
FR Bluetooth proxy 

### ISSUE THREAD

**Issue by alexisml** [Blackymas/NSPanel_HA_Blueprint#453]
It would be really nice adding support to Bluetooth proxy for the nspanel. I believe it is supported by the device, but I'm unaware if anybody has tried to set it up in esphome.

**Comment by weinic** [comment]
I tried to activate Bluetooth Proxy.
But failed because esphome said that there is not enough memory on the esp.

I have already disabled everything possible, logger, AP, Webpage, 
But the project did not fit on the flash memory.

**Comment by Blackymas** [comment]
yes not possible at the moment

https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/206

**Comment by kchiem** [comment]
> yes not possible at the moment
> 
> #206

Someone in the discussion you linked seems to say it's possible: https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/206#discussioncomment-5501212

1. Will this stuff work on the esp-idf platform?
2. Is the web_server component needed by this blueprint?

**Comment by edwardtfn** [comment]
> 1. Will this stuff work on the esp-idf platform?

I'm pretty sure we are using some features that will fail with `esp-idf`.

> 2. Is the web_server component needed by this blueprint?

I'm pretty sure it is required and it will fail compiling if you remove `web_server`.

> Someone in the discussion you linked seems to say it's possible: https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/206#discussioncomment-5501212

Look, maybe you will find a way to enable Bluetooth proxy by disabling some functionality you are not using (captive portal, some sensors, some services, etc), and please share here if you find so, however, I bet you will end up very close to 100% (it is already not far from that) memory consumption and most likely your solution will require you doing all the investigation again everytime we release some new functionality and unfortunately we won't be able to support you with this.
And we want to keep this space for future features as they will come. 😉

**Comment by edwardtfn** [comment]
> 1. Will this stuff work on the esp-idf platform?

v4.1 (to be released soon) will be compatible with esp-idf. 🙂

> 2. Is the web_server component needed by this blueprint?

v4.1 removes all the dependancies to `web_server`. 😉
