### ISSUE TITLE
Show versions and information in UI

### ISSUE THREAD

**Issue by albinmedoc** [Blackymas/NSPanel_HA_Blueprint#454]
Currently we show the  Blueprint, Esphome and TFT version as well as the IP address of the NSPanel in Boot Page.

It would be great to have this information available even after boot, for example in the settings page.

**Comment by Blackymas** [comment]
not so easy because the space is already very tight. we will see what is possible

**Comment by edwardtfn** [comment]
Do you want to have this info in the panel itself or will be OK to have the info in Home Assistant? What is the use case for this?

**Comment by edwardtfn** [comment]
> Could also be useful to write an automation in home assistant to alert when a new blueprint version is available

There is a Feature Request for this on the Home Assistant forum, maybe you can give one more vote: https://community.home-assistant.io/t/allow-blueprint-upgrades/366939

If you down in the discussions you will also find some work arounds developed by the community to allow automatically downloads of blueprints.
