### ISSUE TITLE
Expose versions to HA

### ISSUE THREAD

**Issue by albinmedoc** [Blackymas/NSPanel_HA_Blueprint#455]
I would be great to have the versions for Blueprint, Esphome and TFT available as entities in HA.

**Comment by Blackymas** [comment]
this will not work because the versions are loaded and passed in the individual files. In addition, you would have to set this up in ESPhome.

Even if it doesn't need much memory we have to take care of the memory in the Esphome code which is already very tight

**Comment by Blackymas** [comment]
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/454
