### ISSUE TITLE
Installed, configured, working but firmware updates don't seem to install

### ISSUE THREAD

**Issue by unruly1** [Blackymas/NSPanel_HA_Blueprint#460]
<img width="393" alt="chrome_FF2UtdNHzO" src="https://user-images.githubusercontent.com/7098244/226074485-9e95b0cb-e726-448d-987d-f52bfba075cd.png">
I click "Install" and Home Assistant is non-responsive, no automations work, nspanel displays initializing screen.
Wake up the next morning, 7 hours later.  
<img width="403" alt="chrome_ONjImGWExA" src="https://user-images.githubusercontent.com/7098244/226110852-666004e5-213b-420b-bc7f-f5fd36da0faf.png">

Any help is appreciated.

**Comment by Blackymas** [comment]
This esphome and not our project
