### ISSUE TITLE
Stuck in boot screen

### ISSUE THREAD

**Issue by Doser86** [Blackymas/NSPanel_HA_Blueprint#461]
One of my panels just suddenly got stuck in boot screen

**Comment by Doser86** [comment]
[16:45:12][D][nspanel:986]: no page-jump
[16:45:12][W][nextion:318]: Nextion reported invalid instruction!

**Comment by Blackymas** [comment]
Please upgrade to version 3.2 there were a few adjustments here

If the problem still exists, something was not configured correctly in your blueprint or an entity cannot be read or has a wrong state.

You can use the issue search.
