### ISSUE TITLE
Button Namen werden nicht angezeigt 

### ISSUE THREAD

**Issue by ghostridernrw40** [Blackymas/NSPanel_HA_Blueprint#463]
Hi,

habe die aktueller Version installiert und Namen vergeben für L1 und L2. Diese werden jedoch nicht angezeigt. Ist dies bekannt?

Viele Grüße und besten Dank für die super Arbeit. Anbei ein Foto, wie man sieht keine Namen.
![signal-2023-03-18-12-47-13-420](https://user-images.githubusercontent.com/117640399/226118654-b7021e53-7cc5-486f-888a-e8b487cfc2f8.jpg)

**Comment by ghostridernrw40** [comment]
Mit 3.2 klappt Alles

**Comment by Blackymas** [comment]
super ;)
