### ISSUE TITLE
Cannot be flashed

### ISSUE THREAD

**Issue by legi1** [Blackymas/NSPanel_HA_Blueprint#465]
Good day. I have a problem at the very beginning. I use the same DSD Tech adapter. I  connected the wires the right way as shown in the video. Including th black from 100 to the ground like demonstrated.
If I start, it sends me to WebEsp. then I tried both "prepare for first use and install. I always get the message:
_Failed to initialize. Try resetting your device or holding the BOOT button while selecting your serial port until it starts preparing the installation_

The TX LED is flashing for some 30-40 seconds before the above message is displayed.

Thanks for any help as I'm not the big crack...

**Comment by Blackymas** [comment]
Then something seems to be wrong with your wiring or with your adapter. 

I can't tell you anything here other than what is shown in the video.

**Comment by legi1** [comment]
Thanks for the feedback, then I have to dig and double check. Is there another possibility to bring the Panel in Boot Mode or to reset it?

**Comment by Blackymas** [comment]
nope

**Comment by lloydbayley** [comment]
Make sure you are getting a good connection with IO0 to GND. That's what tells it to go into programming mode. If that connection is a bit dodgy, it will do as you mentioned. Happened to me first time. Hope that helps.

**Comment by Blackymas** [comment]
so we have no feedback - now I will close the issue :)
