### ISSUE TITLE
v3.2 Strangeness (Fremdheit)

### ISSUE THREAD

**Issue by lloydbayley** [Blackymas/NSPanel_HA_Blueprint#471]
Just upgraded to the new version. Works very nicely on both eu and us panels.
Strange thing, which I am not sure if it's by design or not, when I save the automation now, BOTH panels reboot and the changes are applied to the panel I was working on.
Should the panel reboot and why do BOTH reboot?

**Comment by TanPau1412** [comment]
I am having the same issue. My one panel is stuck on a white screen and when I try and change the automation for it, the other panel (which updated successfully to v3.2) reboots

**Comment by lloydbayley** [comment]
Okay. Understood. Thanks for the explanation. Curiously, it didn't happen in v3.1 for me.

**Comment by Blackymas** [comment]
we have implemented a small workaround with version 3.2.1 you should not see the reboot anymore ;)

**Comment by lloydbayley** [comment]
Indeed! It's absolutely wonderful!
