### ISSUE TITLE
v3.2 tagged to the same commit as v3.1.0

### ISSUE THREAD

**Issue by Omar007** [Blackymas/NSPanel_HA_Blueprint#472]
The recently tagged v3.2 is tagged to the same commit as the previously existing v3.1.0 tag from February. I suspect that v3.2 was supposed to be tagged on one of the latest merge commits on the main branch. The main branch is currently 84 commits ahead of the tag.

**Comment by Rep-Hueman** [comment]
When I download the zip file at the bottom of 3.2 --  (NSPanel_HA_Blueprint-v.3.2.zip) it is the old code from 3.1.0. 
I have now used the files from main (NSPanel_HA_Blueprint-main.zip) this is version 3.2.

**Comment by sveba** [comment]
@Blackymas I can confirm that the git tag is wrong.

**Comment by Blackymas** [comment]
sry ... what do you mean?

**Comment by Omar007** [comment]
I'm not sure what your confusion is. As explained, the tag for 3.2 is pointing to the same commit as the 3.1.0 tag. In other words, 3.2 is the same as 3.1.0, or in other other words, the 3.2 release is just the 3.1.0 release.  
![screenshot_2023-03-19T20:16:49](https://user-images.githubusercontent.com/5380079/226206593-0f5509d4-cefb-4262-b41f-18a75ca48ec1.png)
![screenshot_2023-03-19T20:16:39](https://user-images.githubusercontent.com/5380079/226206594-29bb1102-bc0a-4933-9d4d-fec73a9dee76.png)

**Comment by Blackymas** [comment]
ah..... I see it but I don't know how to change it yet

**Comment by sveba** [comment]
delete tag and tag again?

**Comment by Blackymas** [comment]
think now it should fit

**Comment by Omar007** [comment]
Yup tag is pointing to the latest commit now and no longer to the 3.1.0 commit  :+1: 

Closing issue.
