### ISSUE TITLE
Configuration switch.nspanel_update_tft_display  -- entity is unavailable

### ISSUE THREAD

**Issue by Rep-Hueman** [Blackymas/NSPanel_HA_Blueprint#477]
NSpanel - Version V3.2

Configuration entity double

1 x button.nspanel_update_tft_display  -- no problem

1 x switch.nspanel_update_tft_display  -- entity is unavailable

<img width="500" alt="nspanel-control" src="https://user-images.githubusercontent.com/28707705/226205323-968b9156-550b-4ac4-bcc9-2aaf269a3ab8.png">

**Comment by Blackymas** [comment]
you have to delete the entity manually in HA.

This happens when we make a change in esphome and the old service is no longer available.

It is the same for all of them and only manual deletion in HA helps because it is not possible via esphome.
