### ISSUE TITLE
Allow input_boolean for "chips"

### ISSUE THREAD

**Issue by axute** [Blackymas/NSPanel_HA_Blueprint#479]
Hello everyone, thank you for the latest update.
I imported it right away and wanted to use the new "chips" feature. Now my helper was not available.
I use these boolean helpers "input_boolean" in many scripts, so I wanted to use them. 
However, they are not approved for this (although it is actually not that much different than a binary_sensor or a switch), would it be possible to include them in the next update?

Thank you for the time you have invested.

**Comment by Blackymas** [comment]
It is possible I am just not sure if all input_boolean can only on and off

**Comment by axute** [comment]
It is a helper, I use it a lot and can only have on and off.
You can try self by create a helper 😉

**Comment by jfrancais** [comment]
I had a need for this as well.  Pretty easy to do, just need to add the appropriate domains the the selectors in the input section.  I added input_boolean selectors to allt he chip entities.  For example, after line 311 add the following line:

- input_boolean

Then you can use input_booleans for the chips as well.

**Comment by edwardtfn** [comment]
I've added a PR to support `input_boolean` and tested, so let's see if that gets all the way to the release.

**Comment by edwardtfn** [comment]
> I had a need for this as well. Pretty easy to do, just need to add the appropriate domains to the selectors in the input section. I added input_boolean selectors to all the chip entities. For example, after line 311 add the following line:
> 
> * input_boolean
> 
> Then you can use input_booleans for the chips as well.

Thanks for giving the directions.
Next time, fell free to create your own PW... 😉
