### ISSUE TITLE
Add HA color picker in blueprint

### ISSUE THREAD

**Issue by lloydbayley** [Blackymas/NSPanel_HA_Blueprint#480]
Hallo,

I accidentally pasted a HEX value into the following field:

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/21309308/226323465-09585695-6220-4a47-9d13-a4273df92db9.png">

and without checking, I clicked save. Then the NSPanel was stuck on loading....
I corrected the value to the proper one and the panel is now fine.

I'm not sure if there is anything you can include in the code to validate colour-codes but I thought I would let you know.
It's very hard to find all the things that people can do to your programming! I know, I am also a programmer and have trouble, what I call, idiot-proofing inputs. :)

**Comment by Blackymas** [comment]
thanks for the tip.

but currently there is no change foreseen to filter that.

But in the future we want to use the color picker directly from HA to avoid problems.

**Comment by lloydbayley** [comment]
Not a problem. Just wanted to let you know.
I know it would be very difficult to achieve and I think you're right that the HA colour-picker would be an excellent idea.

**Comment by deejaybeam** [comment]
https://github.com/Blackymas/NSPanel_HA_Blueprint/pull/516

**Comment by Floppe** [comment]
Head up notice. PR #516 breaks my NSPanel automation. Same with other PR's like icon selectors.

`TypeError: unsupported operand type(s) for //: 'str' and 'int'`

Deleting the automation and starting over from scratch fixes it. Although that is a **lot** of work selecting all entities, colors, icons.

**Comment by edwardtfn** [comment]
> Head up notice. PR #516 breaks my NSPanel automation. Same with other PR's like icon selectors.

PR #521 should fix that
