### ISSUE TITLE
Bug: notifications buttons not working on 3.2

### ISSUE THREAD

**Issue by zimjjan** [Blackymas/NSPanel_HA_Blueprint#483]
The accept decline buttons do not work on notifications as of 3.2.

Only upper right (x) is working.

**Comment by Blackymas** [comment]
Reduced and solution found.

Fix is on the way ;)

Thanks!

**Comment by Blackymas** [comment]
Can you copy the blueprint code from beta and test it? 

Should everything fit I push it into the stable

**Comment by Floppe** [comment]
Works for me. Are you sure the blueprint from beta branch is used.

**Comment by Blackymas** [comment]
ok is now in stable - thanks @ all
