### ISSUE TITLE
NSpanel uses an unknown service 

### ISSUE THREAD

**Issue by 86Justdave** [Blackymas/NSPanel_HA_Blueprint#487]
HI,
i've just updated to blueprint 3.2 and keep having this error come up. previous versions of the blueprint has been fine. 
I am able to use the manual buttons but don't get anything on the screen.
![Screenshot 2023-03-20 180404](https://user-images.githubusercontent.com/123274014/226444267-4a7a9646-e35e-4013-90e8-27ad33235929.jpg)

![20230320_182603](https://user-images.githubusercontent.com/123274014/226444677-1bf5ab86-747a-44e9-a193-151741686ae7.jpg)

I'm quite new to home assistant so any help will be much appreciated as I'm currently at a loss.

Thanks

**Comment by Blackymas** [comment]
I close the ticket because it should be the same problem as here

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/485
