### ISSUE TITLE
Slow interface. Loading...

### ISSUE THREAD

**Issue by geekyclarkey** [Blackymas/NSPanel_HA_Blueprint#493]
Hello, 
This latest update has somehow made the user interface slow and clunky. the tap to wake takes multiple taps to wake the screen and swiping between pages takes a few seconds with a loading message. I know a few seconds isn't the end of the world but it used to be instant. Can this be looked at?
![IMG_2517](https://user-images.githubusercontent.com/54781483/226541460-7b6fc751-f7ba-4c42-8d81-9945e9512f09.JPG)

**Comment by SasMoe** [comment]
The same error also occurs with me.

Blueprint: 3.2
TFT: 3.2
nspanel: 3.2

**Comment by quenthal** [comment]
For some reason after update I had duplicate automation for my slow NSPanel. After deleting the duplicate, UI was much snappier.

Have to agree though that new version is slower than previous, as already stated in release notes. What bugs me a bit is that waking from sleep feels even slower, than swiping from screen to screen.

**Comment by Blackymas** [comment]
This is normal so I have also describe
https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.2

point 2

**Comment by Blackymas** [comment]
sleep feels even slower - true but not sure why 
 we will check

**Comment by bkbartk** [comment]
point 2 mentions
"Currently, the page takes a few milliseconds longer to load than before."
but probably that depends on the configuration, because for me now it takes a full second to load.
also @geekyclarkey is talking about a couple of seconds

the reason why this is done make a lot of sense but some improvement would be nice.
I don't have any xp with the nextion editor, but is it possible to maybe cache icons once they are loaded once?

and or course, thank you for this great release.

**Comment by quenthal** [comment]
I've noticed that wakign from sleep is not that much slower, but requires more than single tap to wake up. Previously I think single swipe or tap was enough. If I double tap quickly, it wakes up almost instantly.

**Comment by bkbartk** [comment]
this fix makes it a little faster,
actually in my case workable and acceptable again, thank you for that.
but still not as rapid as it was before.

**Comment by quenthal** [comment]
Screen is little faster, but is it still by design, that waking from sleep now requires double tap instead of single touch?

**Comment by geekyclarkey** [comment]
> Screen is little faster, although I may have to go back 3.1 with some of my devices since my wife hasn't the same patience like me when it comes to switches (maybe some light weight fork from 3.1  without bigger graphics, QR-code would be in order..?).
> 
> 
> 
> But my main question - is it still by design that waking from sleep now requires double tap, instead of single touch?

I agree, It is ever so slightly faster but still more than some people in my house are prepared to wait lol. And yes I have to double tap the screen to wake it too. A single tap like in older versions is better. Im considering downgrading too. I do appreciate all your hard work. I'm sure you will get it working as it once was.

**Comment by Blackymas** [comment]
The double tap wake on screen should not be a bug and I have already commented in the issues.

Back to the old button design is not possible

1. is not enough space on the memory available
2. there were some minor bugs in certain combinations.


We will of course now see if we can speed it up. But the page build takes me 3-5 seconds. If I have all 8 buttons occupied

**Comment by bkbartk** [comment]
Question about the performance. 
Is this because of WiFi quality, or because of a slow connection between the esp and hmi?
Or something completely different?
