### ISSUE TITLE
At restart of HA nspanel stays on loading with V3.2

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [Blackymas/NSPanel_HA_Blueprint#497]
After update to version 3.2 every time when I restart HA my nspanel stays on loading screen instead of showing homepage, only after I swipe to move to one of the button screens and then close button screen it loads the home screen, if i not do this action it stays on "loading" for infinity. I not had this issue on version 3.1.

Any idea why this happens @Blackymas?

P.S. on pluspoint, on the new version is that i not get errors anymore in the HA logs if i operate my cover/blind

**Comment by Blackymas** [comment]
Hi pls use the issue search

have a look here:
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/485

**Comment by smarthomefamilyverrips** [comment]
@Blackymas I did already see  and search for the other posted, but this is nor related, please READ my issue, I only have this at restart of HA, everything works for me and if I swipe to button screen and back it also loads home screen again, only as long I not do any action the screen stays on loading, I not see why it would help me to delete everything if all works, this is just a issu happening at HA restart, also had similar issue at version 3.1 at HA restart until did update to a dev version. So please re-open and look into this issue

**Comment by smarthomefamilyverrips** [comment]
@Blackymas thank you for looking into it 🙏

**Comment by deejaybeam** [comment]
https://github.com/Blackymas/NSPanel_HA_Blueprint/pull/518

**Comment by deejaybeam** [comment]
> @deejaybeam Hi Chris, using the blueprint.yaml in the dev version should solve my issue?

yes. but there are other changes too

**Comment by smarthomefamilyverrips** [comment]
@deejaybeam @Blackymas update the blueprint.yaml with the dev version did solve the issue for me..... Thanks!
