### ISSUE TITLE
Feature request - label for the HW-Buttons

### ISSUE THREAD

**Issue by deejaybeam** [Blackymas/NSPanel_HA_Blueprint#5]
The Beta-Version allows to set labels for each SW-Button - awesome, but because it is possible to set individual entities for the HW-Buttons it would be nice to have also a label on the bottom of the display direct over the HW-Buttons to label them also.

**Comment by Blackymas** [comment]
is on the roadmap

**Comment by Blackymas** [comment]
Done in v2.0.0
