### ISSUE TITLE
icon missing on api disconnect

### ISSUE THREAD

**Issue by bkbartk** [Blackymas/NSPanel_HA_Blueprint#511]
Hello,

I have 2 strange behaviors.
1 is the icon missing on api disconnected while fall back is enabled.
![image](https://user-images.githubusercontent.com/17070805/227152720-aa1c099d-3845-42db-9045-a8eff3b1b5b9.png)
see right bottom corner.
this probably is because the icons aren't included anymore

the next on is that the hot water temp in the thermostat page now shows the value of sensor 3
![image](https://user-images.githubusercontent.com/17070805/227153052-899441d3-40f7-4f58-af89-140fead0e826.png)
not a big issue, but a little strange

**Comment by deejaybeam** [comment]
> 1, this will fix the issue, only still using default images.
> 
> ```
>   - platform: gpio
>     name: ${device_name} Right Button
>     id: right_button
>     pin:
>       number: 27
>       inverted: true
>     on_press:
>       then:
>         - if:
>             condition:
>               and:
>                   - switch.is_on: relay2_fallback
>                   - not:
>                       api.connected:
>             then:
>               - switch.toggle: relay_2
>               # - lambda: id(disp1).send_command_printf("home.icon_top_02.pic=51");
>               # - lambda: id(disp1).send_command_printf("home.right_bt_pic.pic=98");
>               - if: 
>                   condition:
>                     switch.is_on: relay_2
>                   then:
>                     - lambda: id(disp1).send_command_printf("home.right_bt_pic.pic=78");
>                     - lambda: id(disp1).send_command_printf("home.icon_top_02","");
>                   else:
>                     - lambda: id(disp1).send_command_printf("home.right_bt_pic.pic=77");
>                     - lambda: id(disp1).send_command_printf("home.icon_top_02","\U0000FFFF");
> ```
> 
> maybe a solution for would be to make the images variable in esphome and set this variable using the blueprint, but I haven't had time to dive into the project like that. 2. your fully correct,

will have a look!
You are right - many symbols/icons have changed in the meanwhile

**Comment by Blackymas** [comment]
fixed in v3.2.2
