### ISSUE TITLE
3.2. Thermostat not working

### ISSUE THREAD

**Issue by diddy990** [Blackymas/NSPanel_HA_Blueprint#515]
I have everything updated to 3.2 but the problem is that the thermostat side no longer works. Only "unknown" is displayed and the close button no longer works either. Does anyone else have the same Problem?

![image](https://user-images.githubusercontent.com/124179861/227203091-272882fb-fca6-4a17-b5b6-38f678e05ad7.jpeg)

**Comment by lloydbayley** [comment]
I know this isn't very helpful but mine is working fine on both the EU and US version, so I'm thinking it's not directly a bug in the blueprint, although I could be wrong. Just wanted to let you know that mine works and perhaps it might give you some clues as where to look locally.

**Comment by lloydbayley** [comment]
That's really weird! So if it was fine in 3.1 and you didn't make any changes between then it's even MORE weird.
The only thing I can think of trying is to remove the Climate entity in the automation, save it, let it update and then try putting it back again. If it's of any help, mine is also in Optimistic mode...but i don't see how that would affect it in your case. Best of luck with finding the culprit!

**Comment by deejaybeam** [comment]
but you have updated:
- tft
- blueprint (and reloaded automations in ha to apply)
- esphome

check versions on boot-screen?

**Comment by diddy990** [comment]
Of course all three on 3.2

**Comment by edwardtfn** [comment]
Do you have any error message in you HA logs? If so, could you please share?

**Comment by diddy990** [comment]
Removing the device from esphome and adding again fixed the problem. Now works fine
