### ISSUE TITLE
Screen not loading

### ISSUE THREAD

**Issue by dfurnell** [Blackymas/NSPanel_HA_Blueprint#520]
Hi Guys, 

I updated to HA 2023.3.6 last night and the screens are stuck on loading, anybody else had the same issue?

**Comment by dfurnell** [comment]
![image](https://user-images.githubusercontent.com/52839232/227462905-1ea80bf2-1a7c-4c50-ac84-4bc74da97b6c.png)

back online by enabling Synchronization of all values (Optional) & Synchronization of all Sliders (Optional).

**Comment by summongod** [comment]
I have the same issue now. Restore to HA 2023.5 did not resolve the issue and changing the synchronisation values you have suggested didn't work either. I have re-done the upgrade to HA 2023.3.6 with the synch settings and that also doesn't work.
The buttons on other screens work, just not the main screen.
Any suggestions?

**Comment by deejaybeam** [comment]
have you tried to swipe from home to any other page and back to home?
This may this issue: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/497
It´s already fixed in dev.

**Comment by summongod** [comment]
So that didn't work. However the issue was an entity that had failed during the upgrade to HA. I deleted entities in the Blueprint until the screen loaded. So it seems that unknown entities will stall loading. Good to know in case of future issues.

**Comment by mgithens1** [comment]
HA threw an error for me, complaining about the Blueprint.  I was sitting stuck on "loading...".

I tried removing the "send_command_text_printf" line from the blueprint, but now the screen is stuck on the "Please wait..." screen.

**Comment by edwardtfn** [comment]
> HA threw an error for me, complaining about the Blueprint. I was sitting stuck on "loading...".

Could you please share that error message or inform where (in which panel component) whe entity was assigned to?

**Comment by edwardtfn** [comment]
> So that didn't work. However the issue was an entity that had failed during the upgrade to HA. I deleted entities in the Blueprint until the screen loaded. So it seems that unknown entities will stall loading. Good to know in case of future issues.

Could you please share in which fields of the Blueprint you used those entities when it was broken?

**Comment by summongod** [comment]
Hi, it was the the heating flame one.

**Comment by deejaybeam** [comment]
https://github.com/Blackymas/NSPanel_HA_Blueprint/pull/541
