### ISSUE TITLE
ESP Flash Poroblem

### ISSUE THREAD

**Issue by V6baja** [Blackymas/NSPanel_HA_Blueprint#526]
I get this far flashing and get this
INFO Successfully compiled program.
esptool.py v4.5.1
Serial port /dev/ttyUSB2
Connecting......................................
ERROR Running command failed: Failed to connect to ESP32: No serial data received.
For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html
ERROR Please try running esptool.py --before default_reset --after hard_reset --baud 460800 --port /dev/ttyUSB2 --chip esp32 write_flash -z --flash_size detect 0x10000 /data/nskitchen/.pioenvs/nskitchen/firmware.bin 0x1000 /data/nskitchen/.pioenvs/nskitchen/bootloader.bin 0x8000 /data/nskitchen/.pioenvs/nskitchen/partitions.bin 0xe000 /data/cache/platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin locally.
INFO Upload with baud rate 460800 failed. Trying again with baud rate 115200.
esptool.py v4.5.1
Serial port /dev/ttyUSB2
Connecting......................................
ERROR Running command failed: Failed to connect to ESP32: No serial data received.
For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html
ERROR Please try running esptool.py --before default_reset --after hard_reset --baud 115200 --port /dev/ttyUSB2 --chip esp32 write_flash -z --flash_size detect 0x10000 /data/nskitchen/.pioenvs/nskitchen/firmware.bin 0x1000 /data/nskitchen/.pioenvs/nskitchen/bootloader.bin 0x8000 /data/nskitchen/.pioenvs/nskitchen/partitions.bin 0xe000 /data/cache/platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin locally.

**Comment by lloydbayley** [comment]
Sounds like it could be wiring. Make sure the IO0 pin is connected to GND as this is the way that the board is prepared for flashing. The other possibility is that you have the TX/RX pins reversed. Check those two things and hopefully you'll be back in action!

**Comment by V6baja** [comment]
Solved Had RX to RX and TX to TX
