### ISSUE TITLE
Error in ESPhome device logs

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [Blackymas/NSPanel_HA_Blueprint#547]
I have the following error in the device logs within esphome

[10:07:05][W][nextion:318]: Nextion reported invalid instruction!

Any idea what is causing this, my nspanel seems to work correctly so not looks like the error in the logs impact anything

**Comment by edwardtfn** [comment]
When you boot up your panel, which versions are shown for the TFT, ESPHome and the Blueprint in the boot screen?

**Comment by smarthomefamilyverrips** [comment]
@edwardtfn all 3.2

**Comment by deejaybeam** [comment]
ignore it.
This message appears on init of nextion-component while (re)starting esphome only.
We want to change the version of the nextion-component in one of the next releases

**Comment by smarthomefamilyverrips** [comment]
Ok thanks @deejaybeam!
