### ISSUE TITLE
NSPanel US Type Sleep Toggle

### ISSUE THREAD

**Issue by lloydbayley** [Blackymas/NSPanel_HA_Blueprint#549]
Hi! 
Firstly, EXCELLENT updates. Thank you. Have had no major problems with the new versions and the functionailty added is wonderful!

Noticed (by accident) that when long-pressing the time on the US type panel, the sleep toggle contained within does not reflect the state of the sleep mode. I can see it is actually changing the state of the sleep mode, however, the toggle stays on.

Just letting you know! :)

**Comment by Blackymas** [comment]
Thanks ;)
 problem found.

I push it today in the DEV will then be present in the next update ;)
