### ISSUE TITLE
3.2 Multi-Climate issues

### ISSUE THREAD

**Issue by Xmister** [Blackymas/NSPanel_HA_Blueprint#550]
Thanks for your great work, however I have some issues with the multi-climate page.
* The on-off button doesn't reflect on the UI, however it works underneath as after turning on a climate I can use the buttons to change the target temp.
* After a while (about 30 seconds), the data (current and target temps) on an additional climate device page will be replaced by the data from the "main" climate device. I have a 60 seconds page timeout set.

**Comment by Blackymas** [comment]
climate is revised and comes soon

**Comment by plasterer41** [comment]
Looking forward to it. Well done 👍🏼 Sent from my iPadOn 20 May 2023, at 21:05, Blackymas ***@***.***> wrote:﻿
climate is revised and comes soon
