### ISSUE TITLE
QR code display time

### ISSUE THREAD

**Issue by artem82** [Blackymas/NSPanel_HA_Blueprint#555]
Hello!
Add a time setting for displaying the QR code, it disappears very quickly to the main page. You need to have time to open the camera to point and so on. Parents don't have enough time.

**Comment by deejaybeam** [comment]
you have two possible solutions:
1. Press QR again when camera is ready
2. set the page timeout in your device configuration
![image](https://user-images.githubusercontent.com/10434729/228313567-2995d2bb-f46e-41fb-85d3-d60b0a2c9406.png)
