### ISSUE TITLE
long_press does not wake up the screen

### ISSUE THREAD

**Issue by bkbartk** [Blackymas/NSPanel_HA_Blueprint#558]
when  de device is in sleepmode and I longpress a button
the screen stays black,
when touching the screen it still stays black.
however, the dimmer control seems to work so to goes to the correct page, only I cannot see this.
Now I have to wait X seconds, then only when the page is back to home screen I can wake up the device.

**Comment by Blackymas** [comment]
Touch screen is fixed in v.3.2.2 for hardware long press we will look

**Comment by edwardtfn** [comment]
Is it expected that the screen should wake up with a button press?

**Comment by bkbartk** [comment]
I would for long press. 
but now you cannot use the screen at all. 
try this. 
- put the screen in sleep mode
- Long press a button with a dimmer attached. 
- Touch the screen. 

It stays black. However dimming is applied. 
so at that point you don’t have a clue what you are doing.

**Comment by edwardtfn** [comment]
> I would for long press.

And why not for short press?

**Comment by bkbartk** [comment]
Because long press leads me to a page with additional settings. Where short press only toggles a device. 
At least. I assume this always works the same.

**Comment by bkbartk** [comment]
I made a small video showing the issue,
I will send you a pm with the link
as you can see based on the backlight, the dimmer is responding, however, you cannot see anyting on the screen.

**Comment by Blackymas** [comment]
try version 3.3

**Comment by bkbartk** [comment]
The video is v3.3

**Comment by edwardtfn** [comment]
I will investigate this.

**Comment by edwardtfn** [comment]
This will be fixed with v3.4, which is currently in `dev` and should be released quite soon.
