### ISSUE TITLE
notification_unread as binary_sensor

### ISSUE THREAD

**Issue by albinmedoc** [Blackymas/NSPanel_HA_Blueprint#560]
Currently notification_unread is a switch representing if there is a unread notification. This is better represented by a binary_sensor.

**Comment by deejaybeam** [comment]
That´s right, BUT, the problem is, that we need to change the state from the blueprint.
If we change this to a binary sensor, than we also need an additional service on the esphome-device, which "costs" extra memory - and this is already on the "limit"...
