### ISSUE TITLE
Hability to enable direct control of relays

### ISSUE THREAD

**Issue by EvertonCa** [Blackymas/NSPanel_HA_Blueprint#570]
I find that sometimes the time it takes for me to click the button and the light that is directly connected to that relay to turn on or off is much larger than when the button controls the relay directly. 

That being said it would be nice to have a toggle that would make the button press directly control the correspondent relay, removing this processing delay.

**Comment by Blackymas** [comment]
Hello I have on 1 nspanel exactly this case and control with it the relays

I have no delay.
It switches almost exactly the same speed as direct.

We will not change it for now also for technical reasons
