### ISSUE TITLE
The function Activate relay local fallback - TRUE/FALSE does not work

### ISSUE THREAD

**Issue by elemarek** [Blackymas/NSPanel_HA_Blueprint#573]
The function Activate relay local fallback - TRUE/FALSE does not work completely. If NSpanel is connected to wifi but does not have a connection to HA, it does not work. It only works when I lose the wifi connection. The WiFi icon lights up even when it is not connected to HA.

**Comment by elemarek** [comment]
I came to the conclusion that it takes a long time until it detects that it does not have a connection with HA and only then does this function work.

**Comment by Blackymas** [comment]
It is normal that it takes a moment
