### ISSUE TITLE
new feature request: choice of home screen

### ISSUE THREAD

**Issue by sdoualle** [Blackymas/NSPanel_HA_Blueprint#576]
Dear all
would it be possible in a next version to choose the home screen?
I explain: for my daily use, I don't need to have weather info as home screen. I would prefer to have the BUTTON PAGE 01.
Thank you in advance if it's possible!
SD

**Comment by deejaybeam** [comment]
for now as an workaround, you could set the page-timeout on the device setting to 0
then open the page you want - it will stay there

**Comment by Blackymas** [comment]
we will check it but it is not planned at the moment

**Comment by mrtramplefoot** [comment]
Hello!  I just wanted to add my support for this feature!  Previously I was using two hacked wink relays, but recently they stopped wanting to load HA and being that you can't update chrome on them anymore, I started looking for a different solution.  While the weather is cool, I don't really find it useful and want the screen to be more of a dashboard of buttons.

Use case 1, Kitchen Lights.  I have 6 lights in my kitchen, a main ceiling light, a light over the kitchen table, a light over the sink, and under cabinet light bars plugged into 3 smart plugs.  At the main switch area there is a switch (well the two ns panel relays now) for the main light and the table light.  I would like the screen to default to buttons to control all the lights at once (Kitchen Lights group), the 3 under cabinet lights (cabinet lights group), and a button to ignore the motion/presence sensors in the kitchen for an hour .

Use case 2, patio controls.  I have two lights in the backyard, deck lights and a higher backyard light.  I would like these on the relays and then backyard controls on the screen.  The dashboard I use to run on the wink was 3 buttons, one to turn on the deck speakers and then volume up and down buttons.

The ability to set a default screen (in my case Button Page 1) would work or even the ability to just select the screens you want.  In my case I only want 1 page of buttons, that's all I ever want on the screens, but the ability to toggle each section on and off would be cool.


Thanks for all your hard work!

**Comment by aceindy** [comment]
I'd vote for this feature too.

Plan is to have one in each room, and home page should be landing on that room's equipment. and certainly not the same 🤔

Having 10 weather forecasts is a bit overkill (in fact, i use a AI randomized spoken weather forecast)

**Comment by edwardtfn** [comment]
One idea would be to select a wake-up page, so every time someone touches the screen, it will go directly to that page (let's say buttons page 1), however if someone closes that page (buttons page X), it will return to the home page.
Would that be an improve to the current behaviour?
I can make some tests around that and if that works it's probably an easy change and only on the Blueprint side (which makes much easier).

**Comment by mrtramplefoot** [comment]
Yeah, that would work for me!

**Comment by edwardtfn** [comment]
This was solved in `dev` and may be included in the next release.
