### ISSUE TITLE
3.2.2 hangs on "loading..." after reboot

### ISSUE THREAD

**Issue by mikeS7** [Blackymas/NSPanel_HA_Blueprint#596]
3.2.2 hangs on loading after nspanel reboot. Automation reload is required to start normal operation.

To reproduce: reboot nspanel from configuration on device page in Home Assistant or directly from hardware.

Back to normal after automations restart or swipe to button page and return to Home

**Comment by Blackymas** [comment]
have tried it several times I can not reproduce.

Have you really updated TFT, esphome and blueprint to 3.2.2

**Comment by mikeS7** [comment]
> Have you really updated TFT, esphome and blueprint to 3.2.2

Yes, esphome first then TFT and blueprint

**Comment by mikeS7** [comment]
Can't reproduce after power cycle ... closing for now
