### ISSUE TITLE
Can't acces the Display Settings on the nspanel

### ISSUE THREAD

**Issue by tomvhoogmoed** [Blackymas/NSPanel_HA_Blueprint#597]
I have a issue that i can not see the Gear icon on the home screen. So i can't reboot or change the brichtniss.

**Comment by lloydbayley** [comment]
It moved a version or two ago. You need to press and hold on the time.

**Comment by lloydbayley** [comment]
Oooh....it would appear that it's not working in the new version...
Anyone else can verify this?

**Comment by mhxsol** [comment]
I had the same issue (not see the gear icon) on the NSPanel home screen.
So i installed the latest ESPHome version and update the nspanel_eu.tft file.
Now after reboot the display shows loading... but will not start further.
Any idea how to solve this issue?

**Comment by Blackymas** [comment]
it works only sometimes you have to do it twice long press.

Why is still unclear to me

**Comment by lloydbayley** [comment]
Wow! That's weird isn't it. Can confirm same behaviour here too on both models.

**Comment by rleongcs** [comment]
@lloydbayley I am seeing the same behavior.
For the back to main screen, I usually short press once and then long press to get around the issue. Would be nice if this can be fixed.

**Comment by lloydbayley** [comment]
Oh I'm sure @Blackymas is on the case already! These things are usually fixed up quick-smart.

**Comment by tomvhoogmoed** [comment]
Hi all i can confirm that is works if you press and hold the time you come in in the settings menu. Thanks
