### ISSUE TITLE
SW-Button press (short-press) executes twice

### ISSUE THREAD

**Issue by deejaybeam** [Blackymas/NSPanel_HA_Blueprint#6]
The trigger for short-press of SW-Button in the BETA version executes twice, on 'press' and on 'release' event, but the first has an template-error 'Template rendered invalid service' so it is´n executed.

**Comment by Blackymas** [comment]
yes this is still an alt-load from my first version with dual state buttons - thanks

**Comment by Blackymas** [comment]
Done in v2.0.0
