### ISSUE TITLE
FR: Bigger Thermostate Buttons

### ISSUE THREAD

**Issue by T3mplate-wow** [Blackymas/NSPanel_HA_Blueprint#604]
Hey, 
most of the panel works perfectly. So thank you for your great work!
The only page I don’t like in handling is the thermostat page. 

Normally I need several tries to push the up or down arrow or a point on the temperature „half arch“.
Because of all other pages are working perfectly (the gear on the main screen, the entities, etc), I believe that the touch fields are too small here. Or am I the only person having problems with this?
On every other button I only need to push once to get what I want :-D

**Comment by Blackymas** [comment]
yes this Is true - we will rework the complete climate page

**Comment by Blackymas** [comment]
hey
it took a long time but with the next version comes a completely new climate page.

You can already install the DEV version or follow this issue for it

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/848
