### ISSUE TITLE
Feature Request: lock possible in buttons

### ISSUE THREAD

**Issue by kroon040** [Blackymas/NSPanel_HA_Blueprint#606]
Hi,

Is it possible to add lock feature into the buttons panel to lock and unlock my door

https://www.home-assistant.io/integrations/lock/

**Comment by edwardtfn** [comment]
In my view, the lock integration can be a bit tricky to be in a button for some reasons:

1. Although `lock` only have two possible states (`locked` and `unlocked`), there are 3 possible service calls (`lock.lock`, `lock.unlock` and `lock.open`) and which service to be used probably will change based on the integration and custom implementations.
In top of that, there is an active discussion about adding more possible states: https://github.com/home-assistant/architecture/discussions/774

2. Locks may require a pin code to unlock, and then this would require an entirely new UI component for this, which perhaps will be the same required for an alarm panel support, already requested on #66 (so perhaps those two features could be implemented together if other problems are solved).

3. When should the button shows the `lock` as `on`? When it is `locked` (it's main function) or when it is `unlocked`?

**Comment by kroon040** [comment]
Hi,

I just need a simple implementation (locked and unlocked state). A pin code is not required. I'm using an elektronic lock in my sched and my nspanel is in my home. I want to do when I go to bed do the lights out in living room and lock my sched from the panel.

I think that HA in is unlocked as on and locked as off, and that is the same as an shutter also I think.

**Comment by deejaybeam** [comment]
> Hi,
> 
> I just need a simple implementation (locked and unlocked state). A pin code is not required. I'm using an elektronic lock in my sched and my nspanel is in my home. I want to do when I go to bed do the lights out in living room and lock my sched from the panel.
> 
> I think that HA in is unlocked as on and locked as off, and that is the same as an shutter also I think.

If we would add a LOCK than this has to be handled as a lock.
Nice that YOU have just this simple use-case, but any other needs/wants than a full implemention that works in all situations.

In your case, why don´t you just create e.g.:
- a boolean_input and an automation
- or a template - switch

Both variants reflect the current state of your lock to a supported domain, that can be assigned to the panel and also displays the current state.
This way you can also handle e.g. that only locking is allowed, maybe makes sense for your case, but not for a lock-implemention.

If you don´t have the skills to create your own template-switch, a simple solution would be to just create a dummy input_boolean (helper) and assign any sequence as custom hold function direct in the blueprint.

**Comment by kroon040** [comment]
I have no idea how to create it with template switch of boolean_input and automation.

Hopefully it could be just a simple implementation of lock in the blueprint

**Comment by edwardtfn** [comment]
Take a look at this discussion: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/649#issuecomment-1501717990

Try to adapt that solution for your locker. Please let me know if you get stuck and I can try to take a look at your yaml.

**Comment by kroon040** [comment]
I made extra switches with mqtt and that works for the panel.

**Comment by edwardtfn** [comment]
#1178

**Comment by edwardtfn** [comment]
I've implemented this in `dev`, however I cannot test it.
If someone can test it and everything goes well this should be part of v4.3 to be released very soon.
I will close this for now, to make easier managing the backlog, but please feel free to add comments here or reopen-it if it isn't solved.
