### ISSUE TITLE
Bug: 3.2.2 TFT Update shows new notification every time

### ISSUE THREAD

**Issue by T3mplate-wow** [Blackymas/NSPanel_HA_Blueprint#607]
Hey,
everytime I update the tft with the HA button, a unknown message appear on the ns panel.
This happens, even if I don’t change anything in the blueprint.

<img width="608" alt="Bildschirmfoto 2023-04-05 um 08 38 15" src="https://user-images.githubusercontent.com/122491946/230000689-6f91a8e8-72d3-46e1-906e-315e954751c2.png">
<img width="608" alt="Bildschirmfoto 2023-04-05 um 08 38 39" src="https://user-images.githubusercontent.com/122491946/230000728-b7e7b579-1f5f-4ff0-9953-9baa95bddef1.png">

**Comment by rleongcs** [comment]
I noticed the same icon when I updated the tft file to 3.2.2 ealier. Once I completed the update for esphome file and blueprint to 3.2.2, the icon disappeared.

@T3mplate-wow You can try updating the other 2 files if you have not already done so.

**Comment by Blackymas** [comment]
yes once it is deleted it does not reappear even with a reboot.

We will watch it

**Comment by geni0602** [comment]
Have two NSpanels. The one is working just fine after the update to 3.2.2 and the second is having the issue with mail icon and loading... screen after restart #596 . Unfortunately it happens everytime after reboot.

**Comment by smarthomefamilyverrips** [comment]
> Have two NSpanels. The one is working just fine after the update to 3.2.2 and the second is having the issue with mail icon and loading... screen after restart #596 . Unfortunately it happens everytime after reboot.

I have exactly the same evrytime after restart get stuck on loading and get the notification envelope

**Comment by geni0602** [comment]
> > Have two NSpanels. The one is working just fine after the update to 3.2.2 and the second is having the issue with mail icon and loading... screen after restart #596 . Unfortunately it happens everytime after reboot.
> 
> @Blackymas and @deejaybeam I have exactly the same everytime after restart get stuck on loading and get the notification envelope ALSO it randomly goes to loading screen after some time and stay there until I restart out of HA or reboot on NSpanel...... Is it possible to role back to 3.2.1?

Roll back should work. You have to take the files from tag v3.2.1. As I said, only one device is having the issue and my second one is just fine. I also flashed back to esphome 3.2 and back to 3.2.2, but still the same: red Mail icon and loading... Screen after reboot. I can rid of the loading screen, when I swipe right or left after couple of seconds, or if I reload/change the automation. 

If I am not rebooting the panel, then everything is functioning properly. Sometimes the red mail icon is coming back after automation change.

**Comment by smarthomefamilyverrips** [comment]
@geni0602 if you did try rollback then not will make much of a difference for me also I geuss.... will await if @Blackymas find a solution for our issue 🙂
