### ISSUE TITLE
FR: improve loading time of home screen

### ISSUE THREAD

**Issue by zimjjan** [Blackymas/NSPanel_HA_Blueprint#611]
Very impresssive update in terms of loading time of the button pages! Is it possible, to also get these loadingtimes to the home screen?
(I'd guess, that if its linear in the number of queried entities, then not, right? 7 chips, 4 sensors, weather and both button entities and noftification are basically double the amount of the button screens)

**Comment by zimjjan** [comment]
Okay, then my brain-timer (:D) measured the performance improvement in the morning:
button pages loaded around 3 seconds on 3.2.1
now they load <1 second
 
note that I have climates, covers, lights and mixed entities on all pages
all pages load similarly fast
all pages are populated with 8 entities each

**Comment by edwardtfn** [comment]
These differences on loading time are probably related to your network load at the moment you are running the tests.
Anyways, have you tried v3.2.2? There are some improvements on the loading of button pages and I believe on v3.2.3 we will be able to reduce that traffic a bit more, so it should get less affected by your network performance.

**Comment by zimjjan** [comment]
You got me wrong, the performance increased vastly with 3.2.2, which is awesome. Those values were just for reference.

**Comment by deejaybeam** [comment]
> You got me wrong, the performance increased vastly with 3.2.2, which is awesome. Those values were just for reference.

Many thanks for your replay - this let us know it was the right decision.
Already said, we also plan to implement this on parts of the code as well.
