### ISSUE TITLE
Error message in HA

### ISSUE THREAD

**Issue by sdoualle** [Blackymas/NSPanel_HA_Blueprint#614]
Hi 
Since this morning, after a restart of HA, I have this message.
Maybe linked to blueprint
It doesn't seem to cause nspanel not working...
for info.

![image](https://user-images.githubusercontent.com/65171614/230056342-9d72c55f-0153-4d70-b361-941c366af84f.png)

**Comment by lloydbayley** [comment]
I am experiencing this too. I was going to look into it later on but it's nice to know it's not just me. I'll wait for an update. :)

**Comment by edwardtfn** [comment]
Have you updated the ESPHome also? You need TFT and ESPHome updated in order to use the latest blueprint.

**Comment by lloydbayley** [comment]
Yep, all updated here. I do it every time.

**Comment by sdoualle** [comment]
the same for me. All updated

**Comment by lloydbayley** [comment]
Strangely-enough, I haven't had the message today. I won't say it too loudly in case it comes back again...

**Comment by edwardtfn** [comment]
This was probably due to the blueprint trying to call that service before the new ESPHome has registered the new service into Home Assistant.

Let's see if @sdoualle still having that issue, otherwise I think we should close this.

**Comment by lloydbayley** [comment]
Agreed. Patience IS a virtue after all! :)

**Comment by deejaybeam** [comment]
> This was probably due to the blueprint trying to call that service before the new ESPHome has registered the new service into Home Assistant.
> 
> Let's see if @sdoualle still having that issue, otherwise I think we should close this.

This is exactly what happens here.
E.g. if you update the blueprint at first, it tries to call the new service from esphome, but if you haven´t installed the new esphome this service does not exist.
The new "problem/repair" option in HA stores the message until you click on "solve(ed)"
