### ISSUE TITLE
Alignment off for weather temp main screen

### ISSUE THREAD

**Issue by rleongcs** [Blackymas/NSPanel_HA_Blueprint#617]
Just updated two NSPanels to ver3.2.2 and noticed that the "C" for the weather temp is out of alignment.

![IMG_1488](https://user-images.githubusercontent.com/61628312/230083253-a4ff1383-f4cd-444f-b1c3-9f17804a3d38.jpg)
![IMG_1489](https://user-images.githubusercontent.com/61628312/230083309-775391ae-d95e-473d-8277-1bdc972d3ec4.jpg)

**Comment by sdoualle** [comment]
hi
I have the same on my panels.

**Comment by Blackymas** [comment]
I will check - thanks
