### ISSUE TITLE
Wrong date format

### ISSUE THREAD

**Issue by rogerjak** [Blackymas/NSPanel_HA_Blueprint#621]
I have the display set to Swedish and date format to DD/MM.
Currently it shows "Onsdag, 05/04", Onsdag being Wednesday.
In the best of worlds it should show "Onsdag 5:e april", but at least it should skip the leading zeros and show "Onsdag, 5/4".

**Comment by Blackymas** [comment]
I don't know if we'll change that. We will look at it
@edwardtfn

**Comment by edwardtfn** [comment]
This is already available on DEV:

![IMG_3154](https://user-images.githubusercontent.com/94725493/230201167-9194472c-4288-43a9-83aa-7ce53f3a9f47.jpeg)

**Comment by Blackymas** [comment]
Is in DEV and will be fixed in the next stabel version
