### ISSUE TITLE
[Question] What's the new "mail icon"?

### ISSUE THREAD

**Issue by rogerjak** [Blackymas/NSPanel_HA_Blueprint#622]
After (some struggeling) upgradring from 3.2.1 to 3.2.2 there's a new red icon looking like email.
When clicking on it I get a screen with "unkown" text and icons.
What is this for? Can't see anything in the blueprint where to configure this.

**Comment by hkr086** [comment]
It happened to me as well.. It's a notification nothing to configure in the blueprint. I cleared it and did not show again

**Comment by Blackymas** [comment]
Mail icon is a hint for notification.

But this should not appear on reboot - we check it

**Comment by Blackymas** [comment]
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/607
