### ISSUE TITLE
Feature request: Add croatian to the list of supported languages

### ISSUE THREAD

**Issue by ajghor** [Blackymas/NSPanel_HA_Blueprint#628]
Hi,
Can you please add croatian to the list of supported languages.
Here is what I have tried:

            - label: 'Croatian'
              value: HRV
and in the selector:

    HRV:
      weekdays:
        mon: Ponedjeljak
        tue: Utorak
        wed: Srijeda
        thu: Četvrtak
        fri: Petak
        sat: Subota
        sun: Nedjelja
      relative_day:
        today: Danas
        tomorrow: Sutra
        in_2_days: za 2 dana
        in_3_days: za 3 dana
        in_4_days: za 4 dana
      climate:
        states:
          "on": uključeno
          "off": isključeno
        heat: toplina
      please_confirm: Molim potvrdite

Thanks,
Igor

**Comment by edwardtfn** [comment]
Could you please also translate those?
- "Unavailable" - For the situation some info is not avaliable to be displayed.
- "No name" - when an entity don't have a name

**Comment by edwardtfn** [comment]
By the way, on the relative days, you used caption first letter for "Danas" and "Sutra", but lower case for "za X dana". Is that correct?

![image](https://user-images.githubusercontent.com/94725493/230431505-3a1518b9-8bfc-44d7-bf01-321dd3cd1362.jpeg)![image](https://user-images.githubusercontent.com/94725493/230431547-2ec47bf5-d7c5-4e69-b119-4bbfff2617fb.jpeg)

What about the two states for the climate page? Shouldn't have the first letter in uppercase?
![image](https://user-images.githubusercontent.com/94725493/230431717-34d521b0-00fc-4622-9de4-075b636ce2d7.jpeg)

**Comment by edwardtfn** [comment]
It is fixed in DEV and will be fixed in the next stable version.

**Comment by ajghor** [comment]
Hi Edward,  

 

„Unavailable“ – nedostupno

„No name“- bez imena

 

Best regards,

Igor

 



Igor Ivanović, Owner

Inventa IR2 d.o.o.

Marjanovićev prilaz 7

10010 Zagreb

Croatia

Tel:       +385 1 7000 211

Mobile:  +385 98 279 795

Email:    ***@***.*** ***@***.***>

**Comment by ajghor** [comment]
Hi Edward,

 

In croatian only the names must have capital letters.

But there are exceptions, for example the first word in a sentence.

Also, if you want to emphasize something it can be with a first capital letter.

 

In this case it can be both, it can be „Danas“ or „danas“, but in the case of “za 2 dana”, no.

The same goes for “Uključeno” and “uključeno”, “Isključeno” and “isključeno”.

For the sake of been consistent you could correct it in the blueprint.

 

I am not a linguist, but even our linguists disagree over things like this.

 

For me it simply looks better in this case on the screen.

 

Cheers,

Igor

 



Igor Ivanović, Owner

Inventa IR2 d.o.o.

Marjanovićev prilaz 7

10010 Zagreb

Croatia

Tel:       +385 1 7000 211

Mobile:  +385 98 279 795

Email:    ***@***.*** ***@***.***>
