### ISSUE TITLE
"Home" page space issues

### ISSUE THREAD

**Issue by thesebastianf** [Blackymas/NSPanel_HA_Blueprint#630]
see picture ... the space for the layout seems to little and e.g. C° is cut off 

![image](https://user-images.githubusercontent.com/13987575/230415964-ab66e0be-b84d-4d46-83f7-68bc6dd2bc60.png)

**Comment by edwardtfn** [comment]
We are aware of that and a fix is coming soon:

#625

**Comment by edwardtfn** [comment]
It is fixed in DEV and will be fixed in the next stable version.
