### ISSUE TITLE
DHW not showing water temp with latest version

### ISSUE THREAD

**Issue by Kepro** [Blackymas/NSPanel_HA_Blueprint#631]
my setup
![image](https://user-images.githubusercontent.com/1714370/230418965-55bb6173-e4a3-44a7-9140-7faf8eedf1b3.png)

there was icon in top right corner with hot water temp, now it's missing

<img src="https://user-images.githubusercontent.com/1714370/230419142-00767ea7-c079-42a7-a857-c62669f430a1.jpeg" height=250>

**Comment by bkbartk** [comment]
![image](https://user-images.githubusercontent.com/17070805/230480405-0f199747-7cbb-4a83-a412-2be7eae76daa.png)
https://github.com/Blackymas/NSPanel_HA_Blueprint/releases

**Comment by deejaybeam** [comment]
you can set this now as "Sensor 03" in the blueprint
![image](https://user-images.githubusercontent.com/10434729/230494476-f9d5f2b9-eec9-4c09-9b58-5ac716d73907.png)

**Comment by Kepro** [comment]
@deejaybeam oh 🤦
