### ISSUE TITLE
Wrong icon description in the blueprint under entity section 

### ISSUE THREAD

**Issue by rleongcs** [Blackymas/NSPanel_HA_Blueprint#633]
In the Blueprint, the Entity section is referencing "BUTTONPAGE0X" under the Icon section for each of the entities. No functionality issues...just my OCD. 😆 

![image](https://user-images.githubusercontent.com/61628312/230573734-7edb86a0-498e-4ad7-9cc8-d400471cbb29.png)

**Comment by edwardtfn** [comment]
Thanks for the catch.
It is fixed in DEV and will be included in the next public release.
