### ISSUE TITLE
FR: Buttons just with the feature-set, they really offer

### ISSUE THREAD

**Issue by T3mplate-wow** [Blackymas/NSPanel_HA_Blueprint#635]
Hey, 

so far I haven’t noticed it at all, but the buttons (especially Cover and Light) always support all the features of the class instead of just the ones that are actually present for the entity. I noticed this because I have now integrated my garage as a cover. The garage can only be “open”, “closed” and “stop”. But I am offered all 0-100 steps. I thought it was different with the lights and only the existing features were active there. But I didn’t notice it because my classic lights are integrated as switches and not as lights. Even lights always have RGB and dimming and white tone, even if they only dim, dim and white tone or only have on/off.

The current behavior is absolutely fine! I'm very happy with the status of the project! Basically, a workaround is not to go into the detail settings. 

I just wanted to write it down once.

**Comment by edwardtfn** [comment]
So, you are saying that even when your light doesn't support some feature, like adjust brightness or color, those options are shown in the panel.
Is that a correct understanding from my side?

**Comment by T3mplate-wow** [comment]
Yes. Completely right.

**Comment by MYeager1967** [comment]
I have the same question as I have a dimmer that I'd like to be able to control with just the dimmer slider. The color control appears to be part of the current setup regardless. Wonderful project and I'd never have gotten where I am without!!!

**Comment by edwardtfn** [comment]
Let's take this example about the 2 state cover... should that just behave like a switch? I mean, when you click in a button related to a 2-state cover, it should just toggle the cover and never open the cover settings page for that cover?

**Comment by T3mplate-wow** [comment]
So my garage (and all other garage motors I have seen so far) in real is just a switch and the motor itself decide what to do when the switch is pushed.
Stopped and last movement was up -> down
Stopped and last movement was down -> up
Moving -> stop.

But this shouldn’t be the „problem“ for this project. I converted via HASS Cover Template the switch into a garage cover. And this cover offers „up“, „down“ and „stop“. So the best solution I believe would be, that there is just a arrow up, down and a stop button after the long press to the device.

**Comment by edwardtfn** [comment]
I think showing the cover settings page without the slider will look odd.

The same for lights page, but at least in the lights I can select to show the temperature or color selector buttons. If a light only supports on/off, then there's no point for showing the light settings page, but if the light supports at least brightness, than that page should be shown with the supported controls.

**Comment by T3mplate-wow** [comment]
Thank you for that! Thats great.

Just my point of view to that:
„ I think showing the cover settings page without the slider will look odd.“
You are right. If you take the current cover page and just remove the slider, I would agree. For me your solution is totally fine.
But I believe a lot of the cover (real cover. For example a beamer screen or ikea roller shutter) out there don‘t support position. And if you don‘t have a position, you need stop to reach specific positions. And in addition on sunny days you want to go down more and more over the day. So I believe a specific good looking page for cover without positioning and just up, down and stop would be the right solution.
But may I am wrong and this is just a edge case. 
I am happy with your solution. Thank you
