### ISSUE TITLE
Screen does not always wake on touch (panel still responsive)

### ISSUE THREAD

**Issue by jpettitt** [Blackymas/NSPanel_HA_Blueprint#636]
I have sleep enabled becasue the dimmest screen setting is still too bright for night.  However if the screen hasn't been touched for some time it often does not wake on touch.   The device is working, I can swipe to a menu and touch where I know a button it and it responds but the screen is still blank.   Occasionally a second touch ~30 seconds after the first will wake the screen.

**Comment by edwardtfn** [comment]
Which version are you using?

This looks like #554, but that was fixed with TFT file v3.2.2.
