### ISSUE TITLE
Trying to set a lower or higher temperature is very unresponsive

### ISSUE THREAD

**Issue by hkr086** [Blackymas/NSPanel_HA_Blueprint#637]
Hi all, are there any issues with the built in thermostat controller? My device is a gree AC and following the 3.2.1 the controls work very slow. It switches the AC with no issues but trying to set a lower or higher temperature is very unresponsive.Thank you

**Comment by hkr086** [comment]
Thank you for changing the description.anyone with this issu?

**Comment by juan11perez** [comment]
Good day, first thank you for this component.

I report the same issue. 
I have thermostats integrated into ha via esphome and mqtt.

In both instances the nspanel reads the data i.e state and temperature.
If I modify the required temp in the ha webui, the panel will track it; however, if i try to modify from the nspanel it doesnt modify in ha. (one way communication effectively)

**Comment by Blackymas** [comment]
will be fixed in the next version.

You can try to install the dev version or follow this issue :)
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/848
