### ISSUE TITLE
Does downloading tft file over wget cause issues?

### ISSUE THREAD

**Issue by Azimuth0r** [Blackymas/NSPanel_HA_Blueprint#643]
Does anyone know whether pulling the tft with a standard wget command results in a bad tft file? I've been trying to flash both the blank and us version of the tft file with no success.

I'm running supervised OS in an esxi vm so the easiest method for me is via the ssh plugin and a wget command.

**Comment by deejaybeam** [comment]
Using "git" is way better

**Comment by edwardtfn** [comment]
Don't you have any other http/www server in your network which could be used to make the files available to your panel?

**Comment by edwardtfn** [comment]
Take a look at this post: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/619#issuecomment-1501606719
