### ISSUE TITLE
Installation Issue (ESPHome flash)

### ISSUE THREAD

**Issue by Sliver88** [Blackymas/NSPanel_HA_Blueprint#645]
I have been trying to flash the NSPanel based on the instructions (both written and on the video of @MarkWattTech) but i keep getting this issue:

INFO Reading configuration /config/esphome/nspanel.yaml...
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing nspanel (board: esp32dev; framework: arduino; platform: platformio/espressif32 @ 5.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- WiFiClientSecure @ 2.0.0
|-- HTTPClient @ 2.0.0
Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/adc/adc_sensor.cpp.o
sh: 1: xtensa-esp32-elf-g++: not found
Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_connection.cpp.o
sh: 1: xtensa-esp32-elf-g++: not found
Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_frame_helper.cpp.o
sh: 1: xtensa-esp32-elf-g++: not found
Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_pb2.cpp.o
*** [/data/nspanel/.pioenvs/nspanel/src/esphome/components/adc/adc_sensor.cpp.o] Error 127
*** [/data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_connection.cpp.o] Error 127
*** [/data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_frame_helper.cpp.o] Error 127
sh: 1: xtensa-esp32-elf-g++: not found
*** [/data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_pb2.cpp.o] Error 127
========================== [FAILED] Took 5.32 seconds ==========================

After a day of searching i keep finding 2 possible reasons. 1st the host architecture (x86 instead of x64). I tried to directly flash via ESPHome Web but although i get the Success the panel doesnt open at all when connecting on its base. Cabling is correct and i never plugged 5V to 3.3V (i was extremely careful on that). So on hand i suspect i fried somehow the device itself but on the other i think that at the moment it is a hardware with no software for it to be able to open.

Another approach was to download the ESPHome to the host itself (Pi4) via `sudo pip3 install esphone` but still can't get around the problem.
While i was searching i found that the path /data/nspanel/.pioenvs/nspanel/src/esphome/components/adc/ is pointing to the NSPanel itself instead of Home Assistant.

I rarely open Issues but at this point i think i run out of ideas and search terms on google and i am really afraid i might completely damage the device.
Can i please have someones insight?

Thank you in advance!!!!

**Comment by edwardtfn** [comment]
> I rarely open Issues but at this point i think i run out of ideas and search terms on google and i am really afraid i might completely damage the device.

Based on the info you gave, I don't think this is the case.
If you assemble your panel back and powers it, what can you see?

Do you mind sharing your ESPHome settings used for setup your panel (the one resulting in the compiling error you shared)? Please make sure to hide your Wi-Fi password or any other private info before sharing.

**Comment by Sliver88** [comment]
Sure and i am really thankful!!

`substitutions:

###### CHANGE ME START ######

  device_name: "nspanel" 
  wifi_ssid: "xxxx"
  wifi_password: "xxxxxxxxx"

  nextion_update_url: "http://192.168.1.9:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####`

On additional search i found this which might be related. 
https://github.com/esphome/issues/issues/3904

So i am in the process of setting up another Pi4 i have with x64 and try to restore a backup of the current installation (if it works it works :D )

**Comment by edwardtfn** [comment]
Yeah, it looks very similar to the problem described there.
Please let me know how the new RPi works for you, otherwise I can try creating a redistributable package for you. You will have some limitations, but at least might give you a chance to play with your panel until you fix your ESPHome compiler in a new RPi x64.

**Comment by Sliver88** [comment]
Unfortunately i installed a fresh x64 Rasbian installed Home Assistant from scratch, added ESPHome and still the same issue. I think it has to do with some version of something. 
I am trying to find another compiler so i can upload the file directly via web.esphome.io but i wasn't able to find one. Is there any option? Using the esphome web on my tries works fine so i only need the file that is created from the .yaml file. I think it just adds the wifi settings and then runs but the .tft is not editable.

Please if you be so kind i would like to have that package. At least to have the switch working because i replaced it already and it is located in the Bath. I took a shower with a candle today (it is Sunday so i couldn't get another switch :D)

Thank you extremely much for helping me out!!!

**Comment by edwardtfn** [comment]
There are:
- [nspanel.bin](https://github.com/edwardtfn/NSPanel_HA_Blueprint/blob/main/custom_configuration/nspanel.bin)
- [nspanel-factory.bin](https://github.com/edwardtfn/NSPanel_HA_Blueprint/blob/main/custom_configuration/nspanel-factory.bin)
- [nspanel_esphome_redistributable.yaml](https://github.com/edwardtfn/NSPanel_HA_Blueprint/blob/main/custom_configuration/nspanel_esphome_redistributable.yaml)

The two .bin files are the same. I've compiled that yaml both on the new format and the legacy format (I don't remember which is what), but one of those might work for you.

After installing in your panel (you can use the [ESPHome Web](https://web.esphome.io/)) you will have to reboot (power cycle?) your panel, then you use a device (phone, desktop, etc.) to look for a WiFi network called nspanel-xxxxxx (please take note of that name). The password for that network is `12345678`.
After connecting to that network, try to access the ip `192.168.4.1` with a browser. The credentials are `admin`/`admin`, select your network, save and then reboot your panel again.
It should be detected automatically by Home Assistant, otherwise add a new ESPHome integration and look for the name of your panel like nspanel-xxxxxx.local.

**Comment by Sliver88** [comment]
Hey!! Thx for the files. At least now i know i didn't fry the panel.
I followed your instructions, panel was recognized by home assistant but i can't do Wireless update due to the below error:
![image](https://user-images.githubusercontent.com/23452507/230804194-e833d4e0-1b89-4abd-baeb-8fbf8f813a39.png)
![image](https://user-images.githubusercontent.com/23452507/230804279-b6e09783-fd6e-4482-a340-2cf1f0008ce9.png)
    
The weird part is that i get the current temperature of the panel, so some functionality is there.
Afterwards i logged in using the IP. I pressed the "nspanel Update TFT display" and now it is stuck to Requesting URL: http://homeassistant.local:8123/local/nspanel/nspanel_eu.tft which address is hardcoded to the file you created and it is not able to find it. I also tried the OTA by setting the .tft but that didn't work either. Finally i can control the switch from HomeAssistant but i can't via the buttons themselves (weird actually)

![image](https://user-images.githubusercontent.com/23452507/230803953-af0e3b43-6b1a-4b07-8b60-e1814ab96f77.png)

Is there any chance you can point me (briefly) how to create .tft files so i can mess around and not have you losing time from your life? Which i appreciate a lot!!!!

**Comment by edwardtfn** [comment]
In your Home Assistant, go to Developer Tools, select the tab Services and look for nspanel_xxxxxx_upload_tft_url:

![image](https://user-images.githubusercontent.com/94725493/230805523-177efb62-e76d-4163-a7e4-37664c0f08e8.jpeg)

Select that, then type the address of your TFT file in a server and click on "Call service".

![image](https://user-images.githubusercontent.com/94725493/230805594-ec17b399-736c-438c-be17-8dc10b804c5d.jpeg)

**Comment by Sliver88** [comment]
No problem... Whenever you have the time, For now i get the 
`Failed to call service esphome.nspanel_c4f23c_upload_tft_url. Unknown error` on the Developer Tools
If nothing works is there any way i can find the original firmware from sonoff so i revert it to "out of the box" and try once in a while if when a Home Assistant update is rolled out?
I will call it a day as i am trying for 14 hours and i will resume once you upload the new file.
Have a good morning evening or night as well!!

**Comment by edwardtfn** [comment]
So, I've uploaded all the files again. Please try to download again and upload to your panel.

**Comment by edwardtfn** [comment]
> `Failed to call service esphome.nspanel_c4f23c_upload_tft_url. Unknown error` on the Developer Tools

Could you please send a screenshot?
Are you sure you have typed the url correctly and a tft file is there?

Anyways, I've updated the link to the file on GitHub on that last build. You can try that one, although I really don't link this about uploading the file directly from GitHub as you are too vulnerable to network issues.

**Comment by Sliver88** [comment]
> Could you please send a screenshot?
Are you sure you have typed the url correctly and a tft file is there?

![image](https://user-images.githubusercontent.com/23452507/230807214-aa9007ee-804f-47e5-86ab-c0d4ddd2fae6.png)

It does that immediately so i dont think it is a network issue.

**Comment by edwardtfn** [comment]
Try this link instead: https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft

**Comment by Sliver88** [comment]
> Try this link instead: https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft

Same. Instant error message. No time to consider it a network problem.
![image](https://user-images.githubusercontent.com/23452507/230807419-60ab6dee-a53f-4f24-b843-f9032782aa7b.png)

**Comment by Sliver88** [comment]
> Anyways, I've updated the link to the file on GitHub on that last build. You can try that one, although I really don't link this about uploading the file directly from GitHub as you are too vulnerable to network issues.

You mean to download those from your previous reply again?
![image](https://user-images.githubusercontent.com/23452507/230807755-b96fc524-76c6-445b-a638-d26c5ed02d18.png)

**Comment by edwardtfn** [comment]
Exactly!

**Comment by Sliver88** [comment]
Hi again.
Did everything again had some progress but we end up on the initial issue:
Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/adc/adc_sensor.cpp.o
sh: 1: xtensa-esp32-elf-g++: not found
Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_connection.cpp.o
sh: 1: xtensa-esp32-elf-g++: not found
Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_frame_helper.cpp.o
sh: 1: xtensa-esp32-elf-g++: not found
Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_pb2.cpp.o
*** [/data/nspanel/.pioenvs/nspanel/src/esphome/components/adc/adc_sensor.cpp.o] Error 127
*** [/data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_connection.cpp.o] Error 127
*** [/data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_frame_helper.cpp.o] Error 127
sh: 1: xtensa-esp32-elf-g++: not found
*** [/data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_pb2.cpp.o] Error 127

At the moment though i see this:
![image](https://user-images.githubusercontent.com/23452507/230900786-f3ad9269-7d68-4b13-86c9-a14bd7a2556c.png)
And i can at least use the buttons from the Home Assistant (hardware buttons still not responding with the switch but send the state to HA). So i can bypass with an automation for now.

Also you can find attached the log from the OTA ESPHome try of installing.


[logs_nspanel-c4f23c_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/11190437/logs_nspanel-c4f23c_run.txt)

**Comment by edwardtfn** [comment]
You are trying to on-board it on ESPHome, but that will probably have the same compiling issue you had before.
You don't have to onboard the device on ESPHOME or, if you do you don't have to update it.

You can go in Home Assistant, under Settings > Devices and Services, add a new ESPHome device and look for nspanel-c4f23c.local or the IP address of your panel.
That will allow you to add the device to HA and then setup the Blueprint (probably using `nspanel_c4f23c` as device name).

**Comment by Sliver88** [comment]
Yes did that already, sorry didnt mention it here.
![image](https://user-images.githubusercontent.com/23452507/230926985-e2287d00-26d0-46b0-9d37-cdd29d9b02c6.png)

Deleting it and adding it via new ESPHome device doesn't show any .local only asking me to add IP. When i add it the above (picture) device is shown

**Comment by edwardtfn** [comment]
> And here is the panel's image:
> 
> ![IMG_20230410_180020](https://user-images.githubusercontent.com/23452507/230927843-1d067ec5-72ef-4bf9-837a-4571aa73a22d.jpg)

This is not the image from this Blueprint. You have to upload the TFT file, either by pressing the button `Update TFT file` in your device in Home Assistant (which will try to upload th TFT from GitHub) or going to Developer Tools > Services and calling the service nspanel_c4f2c3_upload_tft_url and use a locally hosted TFT file (recommended).
![IMG_6165](https://user-images.githubusercontent.com/94725493/230932653-048ffb62-e1b5-40cb-9c6a-e9d2cf618bc1.jpeg)

**Comment by edwardtfn** [comment]
> And the blueprint (including the name which i think is correct):
> 
> ![image](https://user-images.githubusercontent.com/23452507/230928215-d06a3ca0-26dd-42a4-96fc-74ad12fc83b0.png)

No, the name is not correct.
At this screen you have to use `nspanel_c4f23c`, with underscore, just like it is in your service name. `-` is not a valid char for entities and services names, although it's fine to use as friendly names.

**Comment by Sliver88** [comment]
Well yes i am dumb :( sorry

Fixed this:
![image](https://user-images.githubusercontent.com/23452507/230965545-e204bff6-1f52-4d70-81e4-5987b3a2dea9.png)

Tried to re upload the .tft file, now i am able to do it via the services locally:
![image](https://user-images.githubusercontent.com/23452507/230965656-2db4f89f-2209-4f83-adbb-31bbdfccb7a9.png)

But it stucks here:
![image](https://user-images.githubusercontent.com/23452507/230965728-d3490639-af4d-47ba-a4db-1cfaaae4c1ce.png)

**Comment by edwardtfn** [comment]
> OTA update from the device's webpage (bottom left) ends to:
> Update Failed: Wrong Magic Byte

OTA update is not for TFT file. You have to do that thru the service call.

What happens if you type that address in your browser (using your computer)?

http://192.168.1.9:8123/local/nspanel_eu.tft

Do you have the file downloaded to your computer? Could you please check if the file have the same size as the one from GitHub?

**Comment by edwardtfn** [comment]
If you still having problems with this Web server embedded to Home Assistant you can try this solution: 
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/619#issuecomment-1501606719

**Comment by Sliver88** [comment]
> OTA update is not for TFT file. You have to do that thru the service call.
Oh! Ok. My bad. I thought just to play around as well to understand more about the procedure.

> What happens if you type that address in your browser (using your computer)?
It Downloads the file to my PC

> Do you have the file downloaded to your computer? Could you please check if the file have the same size as the one from GitHub? 
Yes, it is the same in terms of size. I redownloaded and tried it again.

> If you still having problems with this Web server embedded to Home Assistant you can try this solution:
Set up and nginx server in another Linux pc and tried. same error message

Also i see that the file is being downloaded and then an error 20 appears on the panel
![image](https://user-images.githubusercontent.com/23452507/231017232-1c0f5fb8-c8de-4075-b5f2-01e740798aa4.png)

**Comment by edwardtfn** [comment]
But based on the picture you shared it is using the GitHub repository for download:
![IMG_6168](https://user-images.githubusercontent.com/94725493/231017702-5ca3d204-948a-43ea-93d4-f08fa9d834a1.jpeg)

Could you please double check it is having the same error when using a local server?

**Comment by Sliver88** [comment]
Yes same exact error in both cases

**Comment by edwardtfn** [comment]
Have you tried [nspanel_blank.tft](https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/custom_configuration/nspanel_blank.tft)?

**Comment by Sliver88** [comment]
Yes i did. I tried every file just in case. some issue. It is like there is an issue with the .tft itself (on my panel).
Is there any chance i could create another .tft file with the full config inside (to avoid the factory version and then the change via tft upload) so i could initiate it in the HomeAssistant mode? 
In my searches this can be caused by wrong config, network (not my case the file is being uploaded ), free space issue (i even deleted in my host pi files to make it more), but i cant mess with the panel itself in case there is some space issue due to my limited knowledge.

Can you please create an ESPHome .bin file for my case using as wifi: Guest and password: 123guest so i can try it?
The issue is caused because there is `sh: 1: xtensa-esp32-elf-g++: not found` error. So by having the outcome of this procedure might be what i want. 
I might be saying nonsense here but i have tried everything i could and with your priceless help even more than i thought i could test.

**Comment by doron1** [comment]
@Sliver88 - you may want to take a look at [this](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/641#issuecomment-1502280139), it contains a usable workaround that solved this for me.

**Comment by edwardtfn** [comment]
@Sliver88, based on this suggestion from @doron1, I've compiled a new firmware reverting back one of the changes from v3.2.2, so could you please try to use one of those to upload the nspanel_blank.tft to your panel and if you succeed could you please go back to the other one you have used before and then try to upload the nspanel_eu.tft with that one?

- https://github.com/edwardtfn/NSPanel_HA_Blueprint/raw/main/custom_configuration/nspanel_nextion_pr2956-factory.bin
- https://github.com/edwardtfn/NSPanel_HA_Blueprint/raw/main/custom_configuration/nspanel_nextion_pr2956.bin

**Comment by Sliver88** [comment]
I am working on that from the moment i saw the comment from doron1. I wanted to reply once i was successful. 
I installed esphome on my 2nd x64 rasberry and compiled the code. I was going to create a new .bin to test and then you sent!

So i flashed the xxxx-factory.bin (the other one isnt working) and i have 90% functionality. I can even control the DIM.
But once i upload the npanel-blank.tft i get the below:
![image](https://user-images.githubusercontent.com/23452507/231282745-25cfd125-9559-48e9-8548-7fbcd820d61f.png)

But the panel restarts

**Comment by edwardtfn** [comment]
This is some error on your url. Are you sure you don't forgot to add the port 8123 in the url?

**Comment by Sliver88** [comment]
Oh my god!! I think i got a bit tired and i am losing the basics.
Yes the blank worked (:8123) of course.



> This is some error on your url. Are you sure you don't forgot to add the port 8123 in the url? So, http://192.168.1.9:8123/local/nspanel_blank.tft
> 
> By the way, please let me know if you can successfully compile your ESPHome in the new device. That will make our life much easier. 🙂

Yes i was able to create the .bin. So using another x64 pi (or linux) you do the following (i write it if someone has the same issue)

`sudo apt-get install python3 python3-pip`
`sudo apt-get install libssl-dev libffi-dev python3-dev`
`sudo pip3 install esphome`  *If you need a specific version `sudo pip3 install esphome==x.y.z`

And then test if it was successful by:
`esphome version`

Afterwards move the initial .yaml file after you have entered the name your wifi and password 
'substitutions:
  device_name: "nspanel-c4f23c" 
  wifi_ssid: "xxxx"
  wifi_password: "xxxxxxx"
.................... and everything else'

When you have the yaml file on the Desktop of the pi/linux:
`esphome my_device.yaml compile` <- Where my_device.yaml is the file on the Desktop

Then after 3-5 minutes you ll have a hidden folder on the Desktop `.esphome`
Find via the File Explorer after you check "Show Hidden Folders" or by 'sudo mv /home/<system_name>/Desktop/.esphone home/<system_name>/Desktop/esphone' so it is now a non-hidden file.
Navigate to "/home/<system_name>/Desktop/.esphome/build/nspanel/.pioenvs/nspanel/firmware-factory.bin"
and copy the .bin file wherever you have Google Chrome and use https://web.esphome.io/ to upload it to the panel

**Comment by edwardtfn** [comment]
So, as I understood you successfully uploaded the nspanel_blank.tft, is that right? So you have the blank screen now?
If that is the case, you should then try to upload the file nspanel_eu.tft

**Comment by Sliver88** [comment]
> So, as I understood you successfully uploaded the nspanel_blank.tft, is that right? So you have the blank screen now? If that is the case, you should then try to upload the file nspanel_eu.tft

Yes done that, seen the Home Assistant logo and now i am here
![image](https://user-images.githubusercontent.com/23452507/231303025-a32ff818-2d6d-43b2-a6d3-3f82dc6c4c3a.png)

**Comment by edwardtfn** [comment]
Let's go...

1. Could you please check on the boot screen if TFT, ESPHome and Blueprint are all with the same version? Is that v3.2.2?
2. Could you please take a look for an error message in the Home Assistant logs?
3. Could you please share the yaml of the automation which set the parameters of your blueprint?
4. Any error message on ESPHome logs?

**Comment by Sliver88** [comment]
Gladly!!!

1.
![image](https://user-images.githubusercontent.com/23452507/231304356-0086dbac-9a4b-4c4c-b455-9f68e1450564.png)

>2. Could you please take a look for an error message in the Home Assistant logs?

```
Logger: aioesphomeapi.reconnect_logic
Source: runner.py:179
First occurred: April 11, 2023 at 3:17:01 AM (5 occurrences)
Last logged: 1:09:15 AM

Can't connect to ESPHome API for nspanel-c4f23c @ 192.168.1.29: Error connecting to ('192.168.1.29', 6053): [Errno 111] Connect call failed ('192.168.1.29', 6053)
Can't connect to ESPHome API for nspanel-c4f23c @ 192.168.1.29: Error connecting to ('192.168.1.29', 6053): [Errno 113] Connect call failed ('192.168.1.29', 6053)
Can't connect to ESPHome API for nspanel @ 192.168.1.29: Error connecting to ('192.168.1.29', 6053): [Errno 113] Connect call failed ('192.168.1.29', 6053)
Can't connect to ESPHome API for nspanel-c4f23c @ 192.168.1.29: Hello timed out
```
>3.Could you please share the yaml of the automation which set the parameters of your blueprint?

I think i have something wrong here. :(
```
alias: NSPanel
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    language: ENG
    nspanel_name: nspanel_c4f23c
    date_format: "%d/%m"
    weather_entity: weather.openweathermap
    outdoortemp: sensor.temperature_sensor_out
    indoortemp: sensor.sonoff_1001886d4f_temperature
    home_value01: sensor.sonoff_1000f85cde_energy
    climate: climate.air_condition
    hotwatercharge: switch.sonoff_1000f85cde
    left_button_entity: switch.nspanel_relay_1
    left_button_name: Water Heater Off
    left_button_hold_custom_action:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.sonoff_1000f85cde
    right_button_entity: switch.nspanel_relay_2
    right_button_name: Light
    right_button_hold_custom_action:
      - service: switch.toggle
        data: {}
        target:
          entity_id: switch.nspanel_relay_2
    button_page01_label: Kitchen Lights
    entity01: light.kitchen_lights
    button_page02_label: Living Room Lights
    entity02: light.living_room_lights
    delay: 10
    chip01: sensor.temperature_sensor_cr```

> 4. Any error message on ESPHome logs?

No Everything is green
![image](https://user-images.githubusercontent.com/23452507/231304519-21ab588e-9899-486c-b0bf-6d983a471a0f.png)

**Comment by edwardtfn** [comment]
Is this entity part of the same panel you are trying to setup?
```
switch.nspanel_relay_1
```

**Comment by edwardtfn** [comment]
Shouldn't the name be `switch.nspanel_c4f23c_relay_1`?

**Comment by Sliver88** [comment]
switch.nspanel_relay_1 is the left hardware button.


> Shouldn't the name be `switch.nspanel_c4f23c_relay_1`?

Indeed but if i go to create a button only these options are here
![image](https://user-images.githubusercontent.com/23452507/231306180-ab043c83-2707-4d51-b072-e8ed10714a52.png)

if i try with _c4
![image](https://user-images.githubusercontent.com/23452507/231306222-059bde8f-c26e-4985-a865-3d760df85f74.png)

And the button works 
![image](https://user-images.githubusercontent.com/23452507/231306280-76dbc912-ba60-4648-913a-484118ee8da0.png)

**Comment by edwardtfn** [comment]
When you go to Developer Tools > Services and type nspanel you will get the list of services related to your panel. How is the name of those services? Are the names including the `c4f23c`?

**Comment by Sliver88** [comment]
Both. There are some left overs 
![image](https://user-images.githubusercontent.com/23452507/231306679-838ccbee-b86d-4f99-a003-3d1a6b7ab381.png)

**Comment by edwardtfn** [comment]
Mmmm
You have a mix of names...

What if you go to your blueprint setting and change the panel name from `nspanel_c4f23c` to `nspanel`?

**Comment by Sliver88** [comment]
> What if you go to your blueprint settings and change the panel name from `nspanel_c4f23c` to `nspanel`?

Its already nspanel. There is no _c4 option there.
![image](https://user-images.githubusercontent.com/23452507/231307332-1e6e7dd1-dc0e-4029-b410-c46b3c379d73.png)


> By the way, if you go Settings > Devices and Services > ESPHome, do you have only one entry for the panel or do you have more than one? How is the name of the integration related to the panel that it is working (if you go into the device and see the entities)?

Only 1
![image](https://user-images.githubusercontent.com/23452507/231307431-6b0eab5e-3272-4366-89d6-a6718c218173.png)
![image](https://user-images.githubusercontent.com/23452507/231307458-2777bfb4-d3b2-4576-ad78-b9181bb5b424.png)

**Comment by edwardtfn** [comment]
> Its already nspanel. There is no _c4 option there. ![image](https://user-images.githubusercontent.com/23452507/231307332-1e6e7dd1-dc0e-4029-b410-c46b3c379d73.png)
> 

Not in the button settings, change the name on the field "ESPHome node name". Change that to `nsphome`.
![IMG_6170](https://user-images.githubusercontent.com/94725493/231308530-6d24c8f6-7dba-446e-8bfe-96ac1d44449b.jpeg)

**Comment by Sliver88** [comment]
Damn it's like the hydra. We resolve one issue another one pops up
On the initialization after reboot i still dont see a blueprint version or name. it is blank

![image](https://user-images.githubusercontent.com/23452507/231309367-66b98bae-eafa-4fbf-9fc3-0d34e7022104.png)

**Comment by edwardtfn** [comment]
Still "Loading..." screen?

**Comment by Sliver88** [comment]
> Still "Loading..." screen?

Yes

**Comment by edwardtfn** [comment]
Ok, let's try something different...

1. Go to Settings > Devices and Services > ESPHome and remove the panel integration (3-dots menu, then Delete).
2. Then go to services and look for any service named nspanel_xxxxxx. It shouldn't exist.
3. Restart Home Assistant 
4. Go to Settings > Devices and Services > Add integration, select ESPHome, type `nspanel-c4f23c.local` and foll9the steps to add your panel back.
5. Go to Developer Tools > Services and check for the name of nspanel services. Use that name for "ESPHome Node Name" in your Blueprint settings.
6. 6. Go to that button settings and double check the name of the entity now.

**Comment by Sliver88** [comment]
After removing the panel from the Integrations and restart HA everything disappeared luckily from the services.
But i dont have to choose any .local
![image](https://user-images.githubusercontent.com/23452507/231311701-6c63d64d-3e2a-48c8-8e55-6e0bfff75c14.png)

**Comment by edwardtfn** [comment]
If you go to services now, how are the nspanel services named?

**Comment by edwardtfn** [comment]
Great.
Now on the Blueprint settings, on the field "ESPHome Node Name" change the name back to `nspanel_c4f23c'.

**Comment by Sliver88** [comment]
Done
![image](https://user-images.githubusercontent.com/23452507/231312579-9fa84e73-f374-44b6-b8a6-8fb98228a3a4.png)

**Comment by edwardtfn** [comment]
Now go to the left button settings and try to set the relay again. How is the name of that entity now?

**Comment by edwardtfn** [comment]
By the way, still "Loading..." screen?

**Comment by Sliver88** [comment]
> By the way, still "Loading..." screen?

Yes



> Now go to the left button settings and try to set the relay again. How is the name of that entity now?
![image](https://user-images.githubusercontent.com/23452507/231312805-f3e8eac3-0836-459d-80fa-f51276f3d7dd.png)

**Comment by edwardtfn** [comment]
🤬

**Comment by Sliver88** [comment]
I have an idea. i will restore my Home Assistant to a backup previous to my nspanel.
Be right back!! It will take some time to redo everything Hass side :D

**Comment by edwardtfn** [comment]
Rename the device to `nspanel` and click yes to rename the entities. Then rename it back to `nspanel_c4f23c` and again accept to change name of entities.

**Comment by Sliver88** [comment]
![image](https://user-images.githubusercontent.com/23452507/231313296-51885919-ef6d-4b30-aa95-aa87a602bcc5.png)

**Comment by edwardtfn** [comment]
> I have an idea. i will restore my Home Assistant to a backup previous to my nspanel.
> Be right back!! It will take some time to redo everything Hass side :D

That sounds too radical, try to rename the device first. Worst case you go entity by entity and rename `nspanel` to `nspanel_c4f23c`.

**Comment by Sliver88** [comment]
> Basically, the services and the entities must have the same pattern for the panel name used in the Blueprint settings. You can change all the entity_id's manually or try to rename your integration under esphome in a try to rename the services. When everything is using the same pattern, it should work.

I am doing this at the moment.

> Sorry, I have to rest a bit. I come back to this tomorrow.

Ofc. And thank you sooooo much for your assistance. I would have tossed in in the garbage if it wasn't you to help me!! :D
I ll let you know what happened after i change all the entities. Have a great night!!!


> About the error messages related to service names, you can just click one by one and flag as fixed.

I know i just thought it might be something helpful as feedback to you.

**Comment by Sliver88** [comment]
Yeeeeeeeeeey!!!! Success!!!!!!!!

I can't thank you enough. Really if you have [buymeacoffee](https://www.buymeacoffee.com) i would more than happy to buy you more than one!!!!!
Many many thanks for your support all those days and your resilience to resolve it. Extremely appreciated!!

**Comment by edwardtfn** [comment]
I'm happy to hear that. This worth more than a coffee or an ice-cream. 😉

How you did to solve it in the end? So others could take benefit of your painful journey.

**Comment by deejaybeam** [comment]
Pretty sure your inital-problem is: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/121, https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/172, https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/249

**Comment by Sliver88** [comment]
> Pretty sure your inital-problem is: #121, #172, #249

Very similar indeed.

> edwardtfn: How you did to solve it in the end? So others could take benefit of your painful journey.

Well, with your valuable help (mostly your input is described below) i installed:
1. via web.esphome.io the xxxx-factory.bin in the nspanel
2. I connected to panel's wifi and set up my Wifi.
3. Since there was a misnaming between Home Assistant and NSPanel itself causing the screen to freeze at `loading....`, i renamed every entity to my panel's name
   To verify the name look in Services
   
![image](https://user-images.githubusercontent.com/23452507/231447320-3fcc31b2-ed32-44b0-96f9-40be50941be1.png)

4. Then connected to the panel via IP (I think it is a good practice to assign static IP via router settings) i restarted the device 
![image](https://user-images.githubusercontent.com/23452507/231447993-dec0cc68-9d0c-4321-ac15-905bcee17b91.png)
and after the reboot the Home screen was there.


> @Sliver88 - you may want to take a look at [this](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/641#issuecomment-1502280139), it contains a usable workaround that solved this for me.

Thank you very much as well for pointing to additional source of troubleshooting.


In conclusion the main issue here is the ESPHome version in combination with a x32 installed host and Home Assistant.
In another x64 pi while i was trying things i was able to bypass the main error `xtensa-esp32-elf-g++: error trying to exec 'cc1plus': execvp: No such file or directory`.
Also setting up a new Home Assistant on a x64 system and loading a backup from your previous installation will not resolve the issue. You need to redo everything from scratch. The backup transfers files that are causing the issue (i guess). I was able to continue without the issue only on a clean installation.

All and all everything is resolved now.

Thank you @edwardtfn once more and everyone bothered to read my case!!!

**Comment by Sliver88** [comment]
> I'm happy to hear that. This worth more than a coffee or an ice-cream. 😉

I am in on-site support so i know that feeling when your resolve something 😉. Others working in other sectors don't understand that!!
