### ISSUE TITLE
Integration of Xiaomi controls (roborock)

### ISSUE THREAD

**Issue by malonip** [Blackymas/NSPanel_HA_Blueprint#649]
Hello,
I haven't be able to add a button to control my Xiaomi roborock device (cleaning robot). Would it be possible to add this possibility in the future, and even have more control on the robot (long press on the button to pause/resume, go back to dock, etc.) ? The idea is to "mimic" the Tile feature of Home Assistant.

Here are some screenshots of roborock controls in Home Assistant :

![2023-04-10_13-08-49](https://user-images.githubusercontent.com/113780852/230891636-e970c99f-40f3-4f1c-af26-71d021a453dd.png)
![2023-04-10_13-09-48](https://user-images.githubusercontent.com/113780852/230891663-37be2325-8896-4138-8123-01d22ae4d9d6.png)
![2023-04-10_13-10-57](https://user-images.githubusercontent.com/113780852/230891674-a55e4d81-a4d8-4249-8a70-5c24d2a7c1bf.png)

Thanks and congratulations for this wonderful project !

**Comment by edwardtfn** [comment]
You know that even with the current solution you could set a [Template Switch](https://www.home-assistant.io/integrations/switch.template/) or maybe use some button helpers to have a way to control your vacuum robot from the panel, right?

I think a simple template switch where when it turns on it will send a command for your robot to start cleaning and when turn off it will send a pause (or go home) and you probably will cover a big part of your needs.

**Comment by malonip** [comment]
Oh, thanks a lot for that solution. Will try it immediately ! Thanks again !

**Comment by Blackymas** [comment]
@edwardtfn has given you a solution something else is not currently planned :)
