### ISSUE TITLE
new feature : thermostat : support for presets

### ISSUE THREAD

**Issue by moustic999** [Blackymas/NSPanel_HA_Blueprint#65]
many thermostat works with presets instead of changing temp directly. It could be really nice to have possibility to change preset mode via the thermostat card on the panel

**Comment by Blackymas** [comment]
thank you we will check it. 
Unfortunately the topic of climate is a hard nut to crack XD

**Comment by Blackymas** [comment]
can you explain in more detail what you are doing with it or what function you are using here. Our Climate devices do not have this function

**Comment by Rainerlan** [comment]
Imho what is meant is schedules - like weekday/weekend schedules.
This can be solved currently though automations (and probably though addons as "SimpleScheduler") - but it would be nicer to have the schedules changeable via the panel (This is what I think was ment).

Also an "away"/"holiday" mode is usually supported in thermostats (where eg in away-mode, temperature is lowered to a defined/fixed temperature and schedules being disregarded). 
Some thermostats also have a "party" mode - where the temperature is raised to a defined/fixed temperature and schedules being disregarded, too).
A UI-lock is another nice thing (for kids not to play with the settings)

**Comment by Blackymas** [comment]
hi is in the roadmap


https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/119
