### ISSUE TITLE
[Feature Request] Option for larger button icons

### ISSUE THREAD

**Issue by soeren-a** [Blackymas/NSPanel_HA_Blueprint#654]
Currently the button icons are placed in the upper left corner with a size of 10x10 px.
Would be great to have an option, that a larger icon can be used instead (e.g. 80x80px, centered)
This UI would be similar to the one [marcfager](https://github.com/marcfager/nspanel-mf/blob/main/photo-lights.png) has used.

**Comment by Blackymas** [comment]
which buttons do you mean?

**Comment by soeren-a** [comment]
I was referring to the buttons on the button pages (buttonpage01 - 04)

**Comment by itsolon** [comment]
i personally prefer blackymas solution

**Comment by soeren-a** [comment]
That's the good thing with options. You can use the layout that you prefer. Unfortunately, these options do not exist at the moment, that's why I created this feature request.

**Comment by Blackymas** [comment]
different layouts are not possible
