### ISSUE TITLE
cannot rename esphome device

### ISSUE THREAD

**Issue by itsolon** [Blackymas/NSPanel_HA_Blueprint#656]
I wanted to respect your recommendation NOT use "-" and "_" in device name
in some manuals i read the use óf - is forbidden i used _ instead
but now i want to use only small characters a to z without - or _ anymore

issue: renaming of complex yaml files not possible

how do i rename it?

the second question is: 
i wanted to flash a standard image but the ota password is wrong i cannot flash another thing again

and additionally i even cannot flash tasmota back to repeat that 

i can not login to the garage_panel.local because i have no user and no password  for the ota web flash webpage..

can you give me a hint how to solve that?

**Comment by itsolon** [comment]
UPDATE: found out by myself.
i was able to login via username: admin password: wifi password
then ther is ota and there you can flash with tasmota
and then backward i will flash Blackymas again the right way
i have used following name
formerly: 
garage_panel
now i have
garagenpanel which is best way for me to have grammatics correct and no - no _ no special character

**Comment by Blackymas** [comment]
Thanks for Feedback!
