### ISSUE TITLE
New feature : Alarm panel

### ISSUE THREAD

**Issue by deku-m** [Blackymas/NSPanel_HA_Blueprint#66]
Hi, 

Nice job creating this thank you.

I wonder if you also have on your roadmap like the alarm panel for arm/disarm, code etc.
Lock garage, camera?

Is there a list of future features / roadmap?

**Comment by Blackymas** [comment]
yes some of this is on the roadmap - which we will implement in the next few days weeks. :)

There is no exact schedule yet.

**Comment by fastender** [comment]
Great!

**Comment by quikote** [comment]
I think an alarm page would be very usefull. This is the right form factor screen to implement a arm/disarm panel and your project the best way to do it simple and fast.
Please, include it in the roadmap... and compatible with alarmo addon :-)
Have a nice year!

**Comment by oliveramays** [comment]
Also leaving my support for this feature.
An alarm page to Arm/Disarm/Code an alarm integration would be awesome!


Glad to see this is already on the roadmap.

**Comment by deku-m** [comment]
@Blackymas doesnt this need the roadmap tag ?

**Comment by Blackymas** [comment]
the tag roadmap I will add as soon as we work on it.

Until then, the ticket remains open with the note "new feature request" :)

**Comment by pwirkus** [comment]
Hello, will the alarm panel card be available? and a card with the ability to control the volume of the google speaker? or other equipment? thank you for the opportunity to use your knowledge.

**Comment by Blackymas** [comment]
hi we work on it ;)

**Comment by ondras76** [comment]
Thank you, that would be very helpful. Nice job!

**Comment by doron1** [comment]
Strong support for this feature req - for me this is the single thing missing from this otherwise fabulous project.

**Comment by paddenstoeltje** [comment]
Second that. Waiting for the alarm panel to be implemented to make the switch from nspanel-lovelace-ui.

**Comment by NickLewanowicz** [comment]
Considering a simple alarm code panel that integrates with HA can cost as much or more then the NSPanel I think this feature would make the NSPanel blueprint an no brainer for anyone trying to add security system functionality to their home.

**Comment by bajangti** [comment]
This would be great. I use an Abode security gateway but have integrated into HA. I did a workaround using a toggle for alarm state that I use as chip on the home page for the alarm status (on for armed home or away, off for disarmed). Also, I added some buttons on a security page that does disarm, arm away and arm home. A bit crude but it works for now.

**Comment by cjeanne-code** [comment]
@Blackymas are you close to deliver the feature? :)

**Comment by Blackymas** [comment]
we work on climate rework. I think after this we will find time for alarm panel :)

**Comment by edwardtfn** [comment]
I need your help with translations for the supported languages: https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/940

**Comment by edwardtfn** [comment]
It's out for `beta` now: #1046
