### ISSUE TITLE
Use attribute in weather fields

### ISSUE THREAD

**Issue by doron1** [Blackymas/NSPanel_HA_Blueprint#663]
Is there a way to use sensor attributes in (some of) the fields in the automation?

I'm using the met.no integration for weather. Turns out it creates one sensor, that has all the different weather info as "attributes". So for example I have a sensor "weather.xxxx", and all of temperature, humidity, wind and whatnot are attributes of that sensor.

How can I use such an attribute in the fields for weather info in the home screen? Couldn't find a way to tell the automation to use it.

**Comment by doron1** [comment]
Closing issue - apologies for the noise.

For posterity - solution is to create a template sensor using the attribute. Example can be found [here](https://community.home-assistant.io/t/accuweather-integration-add-humidity-sensor/250775/4?u=doron).

**Comment by edwardtfn** [comment]
Just to add to that, have you seen the weather pages when you click on the weather picture?
On the weather pages you can see some of those attributes.
I've tested this with met.no and worked fine.

**Comment by doron1** [comment]
@edwardtfn yes I have, thanks! They don't seem to include humidity, which is what I was looking for... :-)
btw thank you so much for all your help here - it's really priceless.
