### ISSUE TITLE
Button text fields too short for non-latin UTF8 text

### ISSUE THREAD

**Issue by doron1** [Blackymas/NSPanel_HA_Blueprint#664]
The text fields for buttons in the Nextion HMI are 10 byte long. Now, if all (or, most) of your chars are from the ASCII set, then there's no problem. However if your chars are from a different script, a 6-char UTF8 string ends up being e.g. a 12-byte string. This will be truncated by the TFT.
In other words, if using a non-latin language, the fields can accommodate at most 5 _characters_.

Suggest all these fields changed to be 20 _byte_ long in the TFT. 
(If we want to be extra careful, we can perhaps use something like utf8strlen that returns the number of actual characters in the string.)

**Comment by leranp** [comment]
Same here with Hebrew language

**Comment by edwardtfn** [comment]
Could you please provide a few names that are failing (in your language, please don't translate those back to English) so I can try to reproduce this issue?

**Comment by leranp** [comment]
> Could you please provide a few names that are failing (in your language, please don't translate those back to English) so I can try to reproduce this issue?

For example :
מסדרון
משחקים

**Comment by edwardtfn** [comment]
Does this works when you have shorter strings?
I've tried with a longer string field, but looks like the panel is using a different char set.
![IMG_3361](https://user-images.githubusercontent.com/94725493/235102973-99cfcf75-2d31-4f82-928d-02778e1d603f.jpeg)

**Comment by leranp** [comment]
> Does this works when you have shorter strings?
> I've tried with a longer string field, but looks like the panel is using a different char set or maybe writing backwards.
> ![IMG_3361](https://user-images.githubusercontent.com/94725493/235102973-99cfcf75-2d31-4f82-928d-02778e1d603f.jpeg)
> 

It is looking good, but the Hebrew has a Right to Left problem, so we need to flip the characters in this case, this is the reason that you see it different
![20230428_120946.jpg](https://user-images.githubusercontent.com/9452319/235106464-1616047d-7996-420b-bd97-858578c72456.jpg)

**Comment by edwardtfn** [comment]
> It is looking good, but the Hebrew has a Right to Left problem, so we need to flip the characters in this case, this is the reason that you see it different

Ok, so you already have this issue, right?

By the way, how dates are displayed then? In the right position or you see backwards in the panel?

**Comment by leranp** [comment]
Yes, the only request is to add more bytes in this fields
The dates are fine, because they are numbers and not Hebrew characters.
About the translation, i translate all the words in backwards to let the
screen show the words in the correct way

**Comment by edwardtfn** [comment]
> About the translation, i translate all the words in backwards to let the
screen show the words in the correct way

Oh no! This should be easier for users and sending the strings backwards should be managed by the Blueprint...

But now I understand how it is. I will think about this for future improvements.

> Yes, the only request is to add more bytes in this fields

I believe #740 will help with that. Let's see if that PR can make all its way to a release...

**Comment by leranp** [comment]
Thank you for your time,
Maybe a function in the blueprint that will backwards the characters if
Hebrew is the language

**Comment by edwardtfn** [comment]
> Yes, the only request is to add more bytes in this fields

PR #740 have a different goal, but in the end is allowing more bytes on that string.

> Maybe a function in the blueprint that will backwards the characters if Hebrew is the language

I think that is totally viable, but still have to think a little bit more about this.

**Comment by doron1** [comment]
OP here. One small comment - string flipping (reversing) in the blueprint, if implemented, should be for all RTL scripts/languages. Hebrew (also my language) is one, but Arabic, Farsi and quite a few other scripts are also written RTL so such function will be quite useful to all of those.

If one aims for crazy completeness, can just implement [Unicode bidirectional rendering algorithm](https://unicode.org/reports/tr9/), on all strings... Latin strings will not be reversed, RTL scripts will. There are multiple library functions for that.

**Comment by denes44** [comment]
> > Yes, the only request is to add more bytes in this fields
> 
> PR #740 have a different goal, but in the end is allowing more bytes on that string.

We can increase the length more if needed, even if we set the length to 40, we will be well under the memory limits.
If we implement the multiline support, 22 characters will only be enough for latin characters.

**Comment by edwardtfn** [comment]
> There are multiple library functions for that.

Unfortunately with the blueprints in Home Assistant we don't have that much flexibility to use external functions and typically we have to put a ton of code every time we need to use that (it was like that to support the new color picker).
But I will take a look at that and see what I can do.

**Comment by doron1** [comment]
Folks, this was marked as completed but I'm not sure it is - even 4.0dev elements, which are said to be limited to 10 characters, are actually limited to 10 **bytes** which in many non-Latin scripts may mean as little as 5 characters. This makes it hard to use these scripts.

**Comment by leranp** [comment]
Same here, 
In my case I edit the GUI file and update the values

**Comment by edwardtfn** [comment]
I've applied a change to `dev` that might help with this. I couldn't test today, but will appreciate if someone can give a feedback.
#988

**Comment by doron1** [comment]
Umm, I just re-applied dev to test your fix, and something weird happened: My nspanel does not connect to HA anymore. In fact it doesn't even connect to WiFi to get an IP address. It stays on "Initializing...", no IP address is shown, on the "Blueprint:" line I'm seeing "Retry: 3", and I can't ping it from the outside. 
I have not seen anything like that in the past. It might be that my panel is "soft bricked" :-)

**Comment by edwardtfn** [comment]
Can you Reboot using the button in the boot page?

**Comment by doron1** [comment]
I can reboot as many times as I want... I can also power cycle etc. It just goes back to the same funny state.
It seems like a funny corruption of the firmware. I managed to get into the captive portal. Giving it the correct WiFi creds, doesn't help... Very weird.

**Comment by doron1** [comment]
I managed to salvage it via the captive portal, giving it _different_ wifi creds (different network). It connects.
After quite a few attempts, it appears as if this version suddenly can't connect to my _hidden_ SSID. It connects to a regular SSID with no issue. My IOT network is hidden; up to this version, nspanel had no issue connecting to it. Now, it seems not to be able to. Does this make any sense to you?

**Comment by edwardtfn** [comment]
I've uploaded the latest code to my panel and it is operational. I couldn't test the longer string as I'm far from the panel, but I can see the panel itself is working properly.

**Comment by doron1** [comment]
Oh! And also importantly - your fix seems to be working! I got a 7-char UTF8 label to display on the button. Thanks!!

But why won't my nspanel connect to the hidden SSID anymore? Could I have broken anything?...

**Comment by edwardtfn** [comment]
> But why won't my nspanel connect to the hidden SSID anymore? Could I have broken anything?...

That was due to a change from a few hours ago.
Please add `fast_connect: true` to your Wi-Fi settings.

**Comment by doron1** [comment]
> That was due to a change from a few hours ago. Please add `fast_connect: true` to your Wi-Fi settings:

Oh wow. Indeed. My panel is alive again. Thanks.

As I said, my test (that went sideways for a while) shows that your fix works well, I can use UTF8 strings are longer than 10 _bytes_ and they show up properly.
