### ISSUE TITLE
swipe on sleep

### ISSUE THREAD

**Issue by bkbartk** [Blackymas/NSPanel_HA_Blueprint#665]
Hello,

Can it be possible to swipe on the sleep screen?
On of my devices is in sleep mode most of the time, but one swipe to the left brings me 4 buttons I want to control.
now when the screen is a sleep and I swipe, it says loading, and then shows the home screen, then I need to swipe again for those buttons.
So is it possible to allow swipe on the sleep screen?

**Comment by edwardtfn** [comment]
This issue has been solved in the `dev` branch and will be included in the next release.

**Comment by edwardtfn** [comment]
- #1556
