### ISSUE TITLE
Incorrect Nextion variable updated when "sleep" button in settings is pushed

### ISSUE THREAD

**Issue by doron1** [Blackymas/NSPanel_HA_Blueprint#668]
This issue has two phenomena:
(1) The setting of "sleep" may go "out of sync" with ESPHOME, so that when it shows on it is actually off and vice versa;
(2) Message "Nextion reported variable name invalid!" logged whenever that button is pushed.

I created a [PR](https://github.com/Blackymas/NSPanel_HA_Blueprint/pull/667) with the fix. Once merged, this can be closed.

**Comment by edwardtfn** [comment]
#667 was merged. :)

**Comment by doron1** [comment]
Yep! Thanks @deejaybeam and @edwardtfn . Closing.
