### ISSUE TITLE
No Update after blueprint execution

### ISSUE THREAD

**Issue by carfnann** [Blackymas/NSPanel_HA_Blueprint#67]
Hi

1st, thanks a lot for your great job!

I've updated my nspanel with your esphome code, update the TFT, import the blueprint and execute the blueprint, but there is no update on my nspanel.
I've double check the ESPhome Node Name, but still not.

do i have missed a step?

thx

**Comment by carfnann** [comment]
Found the issue : 
in ESPHome
device_name: "nspanel-1" 

but in the integration all my entities are named as "sensor.nspanel_1_last_click"
no "-" in HA entities

**Comment by Blackymas** [comment]
Hello,

great that it works now. but this is not a mistake from us and is also in the wiki what you can and should use ;)

But thanks for your feedback
