### ISSUE TITLE
Alarm panel

### ISSUE THREAD

**Issue by Ma-Maison-Intelligente** [Blackymas/NSPanel_HA_Blueprint#672]
First THANK YOU !!! It's already a very nice job.

In 99,99% of cases, home automation includ alarm. Is it possible to have a numeric keybord in NSPanel to stop the alarm when we we come back to home.
I see in your presentation a picture showing an icon but I don't find how to have it 
![image](https://user-images.githubusercontent.com/122357036/231876846-9fece9dc-b914-4c3e-8f55-495f084a6b33.png)

Thank you again.

**Comment by edwardtfn** [comment]
I'm totally in favor for having Alarm panel included in this project, and there are a couple of other requests for the same, however, I don't think this is for "99,99% of cases", as Home Assistant statistics shows that "Alarm Panel" is used by "only" 62% of users, while "Manual Alarm Panel" accounts for other 3.4%... Probably there are some usage not visible here, but I would say it is probably closer to 2/3 than 99.99%. ;)

![image](https://user-images.githubusercontent.com/94725493/231881530-fb0967bc-a116-4666-a494-6c7307514b68.png)

**Comment by Ma-Maison-Intelligente** [comment]
You are right but some peoples (like me) are using Alarmo instead of standart Home Assistant Alarm Control Panel. 
If you can alos consider Alarmo in your futur update it will be greate.
Thank you again for your job.

**Comment by itsolon** [comment]
im team alarmo 

> You are right but some peoples (like me) are using Alarmo instead of standart Home Assistant Alarm Control Panel. If you can alos consider Alarmo in your futur update it will be greate. Thank you again for your job.

im also team alarmo and you can count me on top of the 2/3 using alarm panel in my case with code

**Comment by robgough1970** [comment]
would love to see alarmo integrated to. I have a panel installed in anticipation that this will become available one day.

**Comment by sparkydave1981** [comment]
+1

**Comment by itsolon** [comment]
i have seen on the roadmap there are other features they want to realize first, and i can not really estimate what effort it is to add functionalities like the alarmocard.

whats missing for me is for sure the alarmo card, but there are other things i do not really understand so far.

the best thing on that integration compared to joBr99 napanel lovelace ui is the swiping function, (you can swipe the screens easily) 
thats really smart !! Thumbs up

What is unclear for me:

- where is this little gear symbol for settings, i cannot find it on my display

- is it possible to adjust the number of pages, (i do not need so much buttons and want to show only 2 or 3 pages)

- i have light entities they have only on or off no color no dimmer, but if i press hold i can adjust those things!

- this little envelope shows a message that i do not understand

**Comment by edwardtfn** [comment]
> * where is this little gear symbol for settings, i cannot find it on my display

There's no icon anymore. If you long press on the time in home page you will get to the settings page. ;)

> is it possible to adjust the number of pages, (i do not need so much buttons and want to show only 2 or 3 pages)

I don't think it is possible to hide buttons pages today. I'd love to see that also.

> i have light entities they have only on or off no color no dimmer, but if i press hold i can adjust those things!

That is a bit challenging. Lights should have an attribute `supported_features` which indicates its capabilities, so we could easily use that for deciding when to show the light settings page or not, however that `supported_features` is not very well used by many integrations and I'm afraid this could cause a lot of people to loose functionality instead.
Also, some lights have dimming support, but no color support, and at least for now the light settings page always shows all the options... it's probably a bit harder to hide features from that screen. :(

> this little envelope shows a message that i do not understand

That is a bug and I believe it was resolved in the version currently on `dev`, so it might be available on the next release.
Are you having that all the time? It should show up only when you have a new notification and the bug is that it is showing also when you update TFT or ESPHome (it's not on top of my mind), but it shouldn't be all the time even now.


I think there are lots of good ideas here, but it might be confusing to be discussing all these things in a topic about Alarm Control Panel, so why not discuss this in #718 instead?

**Comment by formatBCE** [comment]
Can't wait for Alarmo here. I use my NSPanel exclusively for alarm panel now, with self-made TFT and couple of automations. Would be cool to use something more robust and customizable, especially with dropping prices for NSPanel now.

**Comment by simonepittis** [comment]
> Can't wait for Alarmo here. I use my NSPanel exclusively for alarm panel now, with self-made TFT and couple of automations. Would be cool to use something more robust and customizable, especially with dropping prices for NSPanel now.

I agree with you. I add myself Alarmo Panell on NSPanell. I made the new TFT/HMI, and modified the blueprint :-)

If I have time next week I will push the code

**Comment by formatBCE** [comment]
> @formatBCE is your code available online ? :pray: 

Not really. It's pretty ugly, but I can try putting it somewhere, if you really-really need it and have US version (layout is for US).

**Comment by primeroz** [comment]
I could use it as inspiration :)

**Comment by formatBCE** [comment]
> I could use it as inspiration :) 

Alright, will do :)

**Comment by formatBCE** [comment]
> I could use it as inspiration :)

https://github.com/formatBCE/NSPanel-simple-alarm/tree/main

**Comment by primeroz** [comment]
@formatBCE Thanks for it and sorry to be a pain 

any chance you could upload the HMI file as well ?

**Comment by formatBCE** [comment]
> @formatBCE Thanks for it and sorry to be a pain 
> 
> any chance you could upload the HMI file as well ? 

Oh sorry, sure. Will upload it to same repo today.

**Comment by SunilKhusal** [comment]
+1

**Comment by edwardtfn** [comment]
For your info, we are planning to work on an Alarm Panel in the coming weeks. I will let you know when we have something to start testing and would love if you can provide some feedback and ideas.

**Comment by sparkydave1981** [comment]
I'd be happy to test

**Comment by Ma-Maison-Intelligente** [comment]
I'd be happy to test too. For your information I'm using Alarmo for my alarm managment.

**Comment by itsolon** [comment]
Im in for tests

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by doron1** [comment]
+1 wrt testing!

**Comment by primeroz** [comment]
I know `alarmo` is great :+1: but would be great to support `standard alarm panel` as well, in particular because of the recently merged `alarm_panel` in [esphome](https://www.esphome.io/components/alarm_control_panel/index.html) which maps to a standard alarm panel in home assistant ( i think )

**Comment by edwardtfn** [comment]
I need your help with translations for the supported languages: https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/940

**Comment by fzambroni** [comment]
Is the alarm page available in dev?
I made all the installations available in DEV, and the icon appears available, but when I click, the page does not open.
I'm using Ring Alarm (no password) using Ring-Mqtt integration. I have the Alarm Panel available on my dashboard.
I am looking forward to testing this feature.

**Comment by edwardtfn** [comment]
It's out for `beta` now: #1046
