### ISSUE TITLE
No label for HW-Buttons showing

### ISSUE THREAD

**Issue by MarcelW85** [Blackymas/NSPanel_HA_Blueprint#68]
The labels for HW-Buttons dosn't show up

**Comment by Blackymas** [comment]
Hello,

after changing the blueprint - did you restart your nspnael?

Left down on the "gear wheel" -> Reboot

Button labels for HW are read in and displayed only once after reboot

**Comment by MarcelW85** [comment]
> Hello,
> 
> after changing the blueprint - did you restart your nspnael?   **Yes**
> 
> Left down on the "gear wheel" -> Reboot
> 
> Button labels for HW are read in and displayed only once after reboot.
> 
> If this does not help, please restart the Automations via Developer Tools -> Yaml -> Automation.     **It doesn't help**

**Comment by Blackymas** [comment]
Just tried it several times it cannot be reproduced.

Have you done a reboot via NSPanel?

<img width="296" alt="Bildschirmfoto 2022-11-27 um 11 10 06" src="https://user-images.githubusercontent.com/41958506/204129778-ed6d96b4-e9a4-4a4a-b36e-895b1a4a6e3d.png">

**Comment by Blackymas** [comment]
If the problem persists after that, please see the following Wiki entry. There you will find the information we need to help you

**Comment by seemarkus** [comment]
I've the same problem.
My blueprint config looks like this.
id: '1669646511430'
alias: nspanel02
description: ''
use_blueprint:
  path: Blackymas/nspnael_blueprint.yaml
  input:
    nspanel_name: nspanel02
    language: DE
    left_button_entity: switch.nspanel02_relay_1
    right_button_entity: switch.nspanel02_relay_2
    left_button_name: Left
    right_button_name: Right

**Comment by deejaybeam** [comment]
do you have an entity: "weather.home"?
If this entity does not exist, this may cause problems while init of display

**Comment by deejaybeam** [comment]
found some missing checks - please try blueprint from dev-branch:
https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/dev/nspnael_blueprint.yaml

**Comment by seemarkus** [comment]
Thanks, the dev-branch blueprint works for me.

**Comment by MarcelW85** [comment]
I found the mistake. It was due to an unknown entity. (hotwater_temp)
In the log you could see that he had problems rendering.

**Comment by Blackymas** [comment]
bug fix is now in stable v2.01. 
Thanks for the report :)
