### ISSUE TITLE
Nextion not connected

### ISSUE THREAD

**Issue by 0x414c49** [Blackymas/NSPanel_HA_Blueprint#683]
Long story short, I tried to upgrade from "nspanel lovelace ui" to this firmware, everything worked fine but every time I tried to flash the display for **blank.tft** didn't work. I tried every mentioned workarounds in this repo and none worked, to be able to update the display I installed tasmota again, and I flashed the display with it to nspanel_eu.tft

Flashed ESPHome and restarted: The screen now stuck on "Please wait" and in the logs it still says nextion not connected.

**Comment by 0x414c49** [comment]
lol, apparently I had to cut the power off (taking out from the wall and connecting it again). Now stuck on loading.

**Comment by 0x414c49** [comment]
Fixed.

**Comment by edwardtfn** [comment]
How you fixed the loading thing?

**Comment by 0x414c49** [comment]
I used Tasmota to flash the Nextion. Then Installed ESPHome. Then I detached it from power and connected it again. This solved that.Sent from my iPhoneOn 15 Apr 2023, at 21:13, Edward Firmo ***@***.***> wrote:﻿
How you fixed the loading thing?

**Comment by 0x414c49** [comment]
> How you fixed the loading thing?

Sorry, I didn't see your comment perfectly on my phone, the loading part was my mistake, I didn't configure the automation correctly.

**Comment by edwardtfn** [comment]
Do you know what was wrong with the automation settings? If we know which field was failing we can try to make it more robust or maybe improve the docs.

**Comment by 0x414c49** [comment]
Actually it was in the docs, there is setting (I think the first input) you need to set for the espdevice name, I forgot to set that.

**Comment by edwardtfn** [comment]
On v3.2.3 we have change that for a device selection and added a text "(REQUIRED)" on it'd description. Hopefully that will make easier for users to do not miss that. There are too many fields to set, so it's not hard to miss one.

Again, thanks for sharing your experience.
