### ISSUE TITLE
Temperature not showing

### ISSUE THREAD

**Issue by borisz73** [Blackymas/NSPanel_HA_Blueprint#69]
On my nspanel the weather is not showing properly and does not show the outside temperature , I've tried to restart and to reinstall it but it did nothing to it. If you have any fix to this please let me know

**Comment by Blackymas** [comment]
do you have pictures of what exactly is not working

Have you looked into the autmation trace?

**Comment by Blackymas** [comment]
If the problem persists after that, please see the following Wiki entry. There you will find the information we need to help you

https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(DE)-HowTo-%7C-Alle-wichtigen-Dinge-die-man-wissen-sollte

**Comment by borisz73** [comment]
I got it eventually to work and it is good now and everything is fine, there was missing something from the initial install. Thank you anyway, very good blueprint 10/10.

**Comment by Blackymas** [comment]
thank you very much glad to hear :)
