### ISSUE TITLE
UI bugs

### ISSUE THREAD

**Issue by rleongcs** [Blackymas/NSPanel_HA_Blueprint#692]
Found a few more bugs on the UI. Again no functionality issues.

In the Blueprint under...
1. Hardware Buttons section,
    - Right `hardware` button hold assignment is missing "hardware".
    - Right `hardware` button custom hold action is missing "hardware".

![image](https://user-images.githubusercontent.com/61628312/233017656-016d44bb-42e1-4d4d-b88b-4c7543e795c2.png)

2. Custom Configuration section,
    - Relay `02` - ICON COLOR is missing "02".

![image](https://user-images.githubusercontent.com/61628312/233005616-a0d09dc5-de0a-4518-9f94-ebfb7c9758bb.png)

On the panel display under...
1. Weather forecast section,
    - Lowercase characters get chopped off.
 
![IMG_1557](https://user-images.githubusercontent.com/61628312/233021048-6e26f381-1e3e-4732-a0b9-6fd86dbdb2a1.jpg)

2. Home page section,
    - Sensor 03 Icon gets chopped off.
![image](https://user-images.githubusercontent.com/61628312/233110452-1b40c250-34b9-4378-8bcc-2f6c399ef2de.png)
![IMG_1559](https://user-images.githubusercontent.com/61628312/233110156-a5218eff-9d98-4fb2-88db-93f26854aa87.jpg)
![image](https://user-images.githubusercontent.com/61628312/233110673-ec91d7e9-e682-4686-93ce-c863b528fc06.png)
![IMG_1561](https://user-images.githubusercontent.com/61628312/233110240-61386e52-8c65-49ed-bb10-c812454d5f6f.jpg)

**Comment by edwardtfn** [comment]
Nice catch, thanks!

I've just fixed items 1 & 2 in the Blueprint in the DEV environment, so this will be included in the next release.

About the weather page, I will wait for @Blackymas as he was already looking at other things to change in the weather pages.

**Comment by rleongcs** [comment]
@edwardtfn I just found a new one. Added to #2 under panel display. Not sure if it is due to the moving down of the icons from the initial screenshot of NSPanel Blueprint as below. You can see the icons are higher up and near the top of the screen.

![image](https://user-images.githubusercontent.com/61628312/233112594-831138ab-44ae-4cc9-84ca-c9915d811f1b.png)

**Comment by edwardtfn** [comment]
> You can see the icons are higher up and near the top of the screen.

You see this as a problem? I understand about the icon's size, but are the icons position also an issue for you? What would you expect in this case?

**Comment by rleongcs** [comment]
I have no issue with the icons being lower so long they can be bigger. The icon for Sensor 03 on the other hand is big enough but is truncated and I was just wondering if it was due to it being pulled lower?

**Comment by edwardtfn** [comment]
Same with the icon for sensor 03 in the home page:
![IMG_3337](https://user-images.githubusercontent.com/94725493/235067057-f63eb4f1-04fc-40a4-8a23-e13e64fc091f.jpeg)

**Comment by edwardtfn** [comment]
And now I've added translations to all date related strings:
![IMG_3351](https://user-images.githubusercontent.com/94725493/235073591-32defc2c-e873-4569-92c0-bc62551aef74.jpeg)
![IMG_3352](https://user-images.githubusercontent.com/94725493/235073597-167cb50e-7456-4a28-baa6-3ca7ce526a92.jpeg)
![IMG_3353](https://user-images.githubusercontent.com/94725493/235073600-f82d4946-5aad-484e-9a41-018231f40daa.jpeg)
![IMG_3354](https://user-images.githubusercontent.com/94725493/235073603-cb7d5f16-16ea-4339-aa85-455544f57e8b.jpeg)
![IMG_3355](https://user-images.githubusercontent.com/94725493/235073606-0af7f7b4-2d61-4cbc-a9fd-e2e9d3144dce.jpeg)
![IMG_3356](https://user-images.githubusercontent.com/94725493/235073607-c403b3e9-d7f9-4b48-88cf-4e5a2521c2d1.jpeg)
![IMG_3357](https://user-images.githubusercontent.com/94725493/235073609-f0ed2991-a453-4448-999f-14b0bced9393.jpeg)
![IMG_3358](https://user-images.githubusercontent.com/94725493/235073610-f64ef5ef-f129-491d-b61f-6a9989510b1c.jpeg)

**Comment by Roger4R** [comment]
I no longer have a configuration icon on the US version home screen to configure the  turn off the display.

**Comment by Blackymas** [comment]
pls read release notes -> long press on time

**Comment by Roger4R** [comment]
> pls read release notes -> long press on time

Tks

**Comment by Blackymas** [comment]
Design Ui issue is fixed in Version 3.4 :)
