### ISSUE TITLE
Turn on display when sleep mode is disabled

### ISSUE THREAD

**Issue by moita420** [Blackymas/NSPanel_HA_Blueprint#696]
Hi, it would be cool if the Display turns on when we disable sleep mode 
Right now i need to phisicaly touch the display to turn it on after disabling sleep mode 
By the way great project!! Thank you for all the hard work!!

**Comment by niallperks** [comment]
I'm using the workaround to call the printf service to set the current page to "home"

`service: esphome.hallwaynspanel_send_command_printf
data:
  cmd: page home`

Works for now, but I agree that waking the screen when disabling sleep mode is cleaner.

**Comment by moita420** [comment]
Thank you guys! Both answers made it work. Thanks!!
