### ISSUE TITLE
Nextion reported variable name invalid! - loop

### ISSUE THREAD

**Issue by Jens-Wymeersch** [Blackymas/NSPanel_HA_Blueprint#707]
Dear,

I've running my panel flawlessly till today. I did an update of the panel today  (ESP version 2023.4.0) and since then I'm getting constantly the following statement into my logs. I've restarted the panel and tft without success.

The following is popping up all the time : `[W][nextion:396]: Nextion reported variable name invalid!`

What can be done to get ride of the warning ?

**Comment by edwardtfn** [comment]
We have a know error giving exactly this message, so I believe you had this even before the update.
That issue was already fixed in the version currently in `dev` and hopefully should be part of a release soon.

By the way, other than the error message in your logs, is there any bad behaviour from the panel?

**Comment by GinAndBacon** [comment]
I have this and the only thing I noticed was the nspanel stopped sleeping (screen going off completely) and I can't reboot from settings on the NSPanel although if I go to the device in Home Assistant, I can enable sleep and reboot the device. I can't say exactly "when" this started happening but it did seem like after the latest ESPHome update but there was also the HA 10.0 update and some HA core updates around the same time. I didn't update on of my other NSPanel's and it can reboot and sleep from the panel itself and from HA under the device in ESPHome. About the only annoying this is sleep gets toggled off after I reboot HA, not a big issue though. Will just wait for the fix.
