### ISSUE TITLE
Loading... panel.

### ISSUE THREAD

**Issue by cr4shydlo** [Blackymas/NSPanel_HA_Blueprint#709]
Unfortunately, I'm stuck again. I did everything according to your instructions. After restarting, a blue screen appears, but there is no number listed next to Blueprint. On the display, I only see the message "loading...". I have tried removing and re-adding ESPHome, Blueprint, and flash ESP multiple times, but the issue persists. The name in ESPHome is "nspanelsalon" and it has been entered correctly in Blueprint.

**Comment by edwardtfn** [comment]
Please take a look at this and let me know if you still having issues:
https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/671

**Comment by edwardtfn** [comment]
Make sure you have TFT, ESPHome and Blueprint all with the same version.

"Loading..." screen means your panel is waiting for something from your blueprint. Either the Blueprint is not working (it could be a crash) or it is trying to use a name that is not the one used by the services and entities related to your panel.

1. Take a look at the log of your Home Assistant.
2. Go to Developer Tools > Services and look for services with "nspanelsalon" in the name. Take note of the name of one of those services. Then go to Settings > Devices and Services, look for your panel in the list of ESPHome integrations and see the entities. Make sure the panel, the entities and the services all follow the same pattern to reverence to your panel.

**Comment by GinAndBacon** [comment]
I had this issue last night also and it was right after the latest HA core update. After doing a restore as I did a partial backup before the update the issue went away immediately so I am pretty sure it is related to the latest HA Core update. I have not tried updating again to verify though but it was right after I did the update last night for the latest HA Core update.

I was messing with some of the Blueprint settings during the HA Core update, which may have been part of the issue also so I will not be messing with the blueprint during an HA Core update (or ESPHome update) in the future. I didn't grab any log messages last night before the restore although I wish I had now to post them here.

**Comment by BluThunder2k** [comment]
I as well never had this issue till the core update I installed today.      All my versions are the same.   I can GET around this, but going into the automation - changing something - pressing save - wha-la, my panel pops up and works perfect from that point on.    But a power cycle/reset of the NSPanel and i'm back to loading.... ....
