### ISSUE TITLE
Latency problems...

### ISSUE THREAD

**Issue by CaioSilveira63** [Blackymas/NSPanel_HA_Blueprint#712]
Hi, i'm having some problems with latency between i've pressed a phisical button, and the action actualy happen.

before i flashed the custom firmware, i used my nspanel connected to HA with the [SonoffLAN addon](https://github.com/AlexxIT/SonoffLAN), and i had an automation that toggled my lights based on the state of the nspanel relays state, and it was virtualy instant, the lights switched on at the exact time that you hear the relay switching

but now with the custom firmware i'm facing a 2 to 3 seconds of latency, i've done some trouble shooting and used a [custom code](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/215#issuecomment-1402429360) for controlling the relays direclty with the buttons, but the latency continues.

i've noticed that the action shows up on the ESPHome log instanlty, so my only conclusion is that we have some kind of bottleneck between the ESPHome and the HA.

i doubt that the problem is related to my wifi connection, because i didn't had that problem with the original firmware (wich i saddly lost because i didn't made a backup when flashing the custom firmware).

(Sorry if i said something wrong, i'm a developer but i'm relatively new to home automation, esp hacking, etc...)

**Comment by edwardtfn** [comment]
Bom dia, Caio,

There are some things you can do to help identifying where the issue could be:
1. On the device screen related to your panel in Home Assistant (Settings > Devices and Services > ESPHome and then the device related to your panel), you have a binary sensor which shows when the button was pressed. Do you see a delay between pressing the button and that sensor detecting?
This sensor is I depending of the Blueprint itself, it's only using ESPHome components (and your Wi-Fi network), so if you see some delay at that point, we can exclude the Blueprint as a possible source of this delay.
1. Do you see this same latency when you click in the same lights in a dashboard in Home Assistant? I'm again trying to exclude the Blueprint from the picture.
1. If you cannot see any latency on the options above, then it is probably some delay during the execution of the Blueprint. The code for executing this task is quite simple, but the whole blueprint is not small, so maybe we could be facing some performance issues there still.

I will wait for your reply so I can think better about the possibilities.

**Comment by rikmos** [comment]
I might have some insight on this. My new install, I switched to docker for esphome AND homeassistant (hasos no more), after getting past a number of hurdles, Ive discovered that HA, w/no ipv6/host is bored (cpu/mem/io) is reducing the tcp request sizing for some reason.

The host where my nspanel_us.tft is hosted, the logs indicated 200 AND thousands of 206 (continue downloading) once
it got past the initial tft, the updated hmi file has taken 16 hours so far (41%) from the HA update tft button. 
I can confirm that there is 0 or less then 1ms latency in the wired network and -68db in 2.4ghz so its not the network, switches, hardware or anything else. 
from the ESPhome console, the tft update takes seconds...

HA has dome something weird. 

Iperf3 stats from HA/espH/docker host, Ill continue testing, once I find the hole Ill likely open a git issue in ha
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  3.12 GBytes   892 Mbits/sec    0             sender
[  5]   0.00-30.01  sec  3.11 GBytes   891 Mbits/sec                  receiver

**Comment by bkbartk** [comment]
the .yaml does the action on_click,
this sometimes can give the feeling of a slight delay because it's fired when you release the button. 
if you change this to on_press, the action will be triggerd as soon as you touch the button.

Also I had some issues with delays in the past, not sure if it was HA or not.
but for that reason(and some others) I made a few changes so the HW button triggers the relay directly in esphome without using the blueprint. but this is only possible if you want to use the relays of the ns panel.

**Comment by bkbartk** [comment]
> 

You are right. I forgot the part that some people use the long press.
But still. This could be why default firmware redd add ponds faster.

**Comment by Blackymas** [comment]
Hey, thanks for your feedback.

But we really have a lot of installations online now and almost no one has a problem with it.

If we went from on_release to on_press, that wouldn't be 2 milliseconds you would save. But I don't know how long you click on the button 😂

But fun aside if you have such a big delay, something else is wrong.

Nevertheless, thank you very much for your feedback 👍
