### ISSUE TITLE
Paypal button does not work

### ISSUE THREAD

**Issue by kcossabo** [Blackymas/NSPanel_HA_Blueprint#716]
I wanted to send some money, but the paypal button does BAD things. It hammers PayPal and then PayPal locks me out 'too many tries'.

**Comment by kcossabo** [comment]
the one on the 3.2.2 update works, it is just the one on the main screen....

TIP sent - Thank You for all the hard work on this.

**Comment by Blackymas** [comment]
Hello and thank you,

Which link should not go I have tested them all. Do you have a picture?

**Comment by kcossabo** [comment]
No pictures. 

The link I used is the paypal button on 

https://github.com/Blackymas/NSPanel_HA_Blueprint

This took me to the 'amount' page, I then hit submit, and eventually, an error that something went wrong, contact admin (or something) if it continued. At that point, Paypal.com could not be reached. Reloading eventually came back with "too many attempts.

Waited 20 min and repeated the same results.

Waited 20 min, logged into PayPal, and everything is good, then pushed the button, and even the tab with the open page was locked.

Waited, and tried this link https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/595 and pushed that PayPal, and could donate.

Once again Thank You for the great project.
