### ISSUE TITLE
Confused on YAML to use 

### ISSUE THREAD

**Issue by MuppetRus** [Blackymas/NSPanel_HA_Blueprint#717]
Hi
On Marks original video to flash the NSPANEL I copied and replaced the original YAML code with the one Mark had in his link to Github and his second video it shows a YAML with only a small amount of code and I checked out the links in the video and none of them match what was shown in the video. The current situation is I have added the device to HA and imported the Blueprint and I just need to flash a new YAML code onto the NSPANEL so it will make use of the Blueprint I just want to make sure I am selecting the correct YAML code to replace Mark's original one.

Kind regards
Bruce

**Comment by edwardtfn** [comment]
The code keeps evolving, so it's normal that it will be a bit different from the one in the video.

The updated instruction is this one from the wiki: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-First-Steps---Installation-and-Setup#code

But of course, if you face some issues we might be proposing some changes, depending on the issue. 😉

**Comment by MuppetRus** [comment]
Thank you and I resolved the issue and its working very well :)
