### ISSUE TITLE
Add greek language support

### ISSUE THREAD

**Issue by stratogk** [Blackymas/NSPanel_HA_Blueprint#72]
Υou could add other languages too

**Comment by Blackymas** [comment]
Yes you can translate everything except the settings page (maybe in the future)

I can offer to send you all the words and you translate them for me and I will add it to the blueprint.

Let me know if this is ok

**Comment by stratogk** [comment]
Appropriate changes should be made to the tft file so that it supports Greek characters.
And I can certainly do this translation with pleasure

**Comment by Blackymas** [comment]
hi - wee need
we need

Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
Today
Tomorrow
in 2 Days
in 3 Days
in 4 Days
on
off
heat

**Comment by w00ter** [comment]
Dutch/Nederlands: 

Maandag
Dinsdag
Woensdag
Donderdag
Vrijdag
Zaterdag
Zondag
Vandaag
Morgen
in 2 Dagen
in 3 Dagen
in 4 Dagen
aan
uit
verwarm

**Comment by Blackymas** [comment]
hi @ all

done in v2.2.0 https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.2.2.0
