### ISSUE TITLE
Not an issue - Just want to a way to say Thanks

### ISSUE THREAD

**Issue by MuppetRus** [Blackymas/NSPanel_HA_Blueprint#723]
Hi to All,
A very big thank you to everyone that made and contributed and assisted to make this NSPanel and Blueprint documentation, project and videos, whilst it took me a little bit of time to get my head around Home Assistant & the NSPANEL its the best move I have ever made as I was using Fibaro with a Home Centre 2 and it got to the stage where there were no updates and it was not doing the job.

I finally have everything in the house automated and I now have control  over my JVC projector which I could never do with Fibaro, though I still have a bug turning it off which I am still trying to solve with HA 

LG OLED TV
LG Soundbar
Samsung Soundbar
100 x LED lights
Fireplace fan
Dehumidifier
Smart Kettle
Sub Bass Amplifier
Integra Receiver
Apple TV's
Wii Console
Multiple Ceiling Fans 
Flood Sensor 
Daikin A/C's
Fibaro Motion Sensors
Google Nest Protect Smoke Detectors - Not working in HA yet
Unifi G4 Cameras
Unifi Dream Machine Pro
Wyze Cameras
Lockwood Lock 
WiFi Power Points
Automated Shopping list 

A special shout to Mark for his very entertaining and educational videos and to Blackymas for the excellent Blueprint

I could be not more happier with the NSPANEL and the Blueprint project, whilst I only have one so far it has inspired me to purchase more.

Looking forward to more updates 

Kind regards
Bruce.

**Comment by Blackymas** [comment]
thanks for the feedback <3

Feel free to leave us a donation for the project ;)
