### ISSUE TITLE
3.2.2: Entites Page value alignment

### ISSUE THREAD

**Issue by bommel947** [Blackymas/NSPanel_HA_Blueprint#732]
Hi,

I am just wondering if the values of an entity page can be configured to be right aligned.

![image](https://user-images.githubusercontent.com/45903971/234625124-3984a56a-b899-4af9-9251-a41617ee1ff7.png)

**Comment by edwardtfn** [comment]
What about entities returning text? Should that stay aligned to the center as it is today?

**Comment by bommel947** [comment]
IMHO all entities return types would need to be right aligned

**Comment by bommel947** [comment]
Hi,

Thank you very much for providing a fix!
Unfortunately I don't find the alignment settings in the blueprint.

Didnt find it within 3.2.2. nor 3.3

Please explain!

best regards
Manfred


Am Mi., 7. Juni 2023 um 23:42 Uhr schrieb Blackymas <
***@***.***>:

**Comment by edwardtfn** [comment]
It will be included on v3.4 which will be released soon.
