### ISSUE TITLE
Entity name on cover settings page instead of label/friendly name

### ISSUE THREAD

**Issue by denes44** [Blackymas/NSPanel_HA_Blueprint#739]
I'm using the dev branch now, and I noticed that in the cover settings page, the entity name is displayed instead of the label I specified for the button. The label is shown fine on the button before opening the settings page for the cover.

I think this is the corresponding code from the blueprint:
https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/7677934244237dceb6b17d060a42ddc0d20751f0/nspanel_blueprint.yaml#L5924-L5928

**Comment by edwardtfn** [comment]
Good catch!
It's always good when we have someone testing with the latest code. Bugs will always happens and the earlier we find those the easier is to fix.
And thanks also for pointing the area in the code responsible for that. It was exactly there. :)
It's already fixed in `dev`.

**Comment by denes44** [comment]
Thanks, I updated my PR (#740) that affected this code.
