### ISSUE TITLE
Temperature display on the home page

### ISSUE THREAD

**Issue by denes44** [Blackymas/NSPanel_HA_Blueprint#755]
I use the sensor1-2 display as temperatures on the home page, and the display is not so good now, because the indoor temp is displayed with unit `°` and the two sensor with `°C`, and this is not looks very good. I think we should stick with the unit of measurement supplied from Home Assistant.
![nspanel_temp](https://user-images.githubusercontent.com/60078357/235323163-035c5bb6-6392-49a1-a85e-515615387942.jpg)

**Comment by edwardtfn** [comment]
We have changed on v3.2.2 t9 use units from Home Assistant everywhere, but then we got an issue with the limited space in the screen for some of those, then we reverted back.
Maybe outdoor temperature will be the only one limited, so we should have everything else following Home Assistant, but will still inconsistencies.

**Comment by edwardtfn** [comment]
Space on the scree is the biggest challenge in this project.

**Comment by edwardtfn** [comment]
Fixed in `dev`.
