### ISSUE TITLE
Settings icon disappeared (when trying to update to fix the sleep issue)

### ISSUE THREAD

**Issue by Levanterman** [Blackymas/NSPanel_HA_Blueprint#756]
Hi

I noticed the screens were not sleeping and came here to read the closed/issues about the sleep so thought i would update the firmware. And also noticed theres a new automation blueprint (nice work!) , so updated that too. 

But now they screens still dont sleep and the settings icon has gone (maybe this is by design, not sure).

I used the 'Update TFT Display' . Everything is still working fine, but no settings icon and teh screen never sleeps.

Thanks :-)

**Comment by edwardtfn** [comment]
There was a breaking change in ESPHome 2023.4 which changes the default mode for saving switch settings in the flash memory (to be remembered after a restart).
On v3.3 we have changed the ESPHome file to support this new format. That still in `dev` but hopefully will be released very soon.

**Comment by edwardtfn** [comment]
About the settings page, it's now hidden, but you can still get there with a long press on the time in the home page.

**Comment by Levanterman** [comment]
Hey thanks @edwardtfn for the super quick reply. 
I couldnt find any details about the settings page, so thats awesome.
Also i saw some updated files in the repo that mentioned the sleep , so i thought it was an old issue , and the update just wasnt working for me, thanks for the extra info. 
Happy Sunday.
