### ISSUE TITLE
don't have esphome.device_name_upload_tft

### ISSUE THREAD

**Issue by bluemaster27** [Blackymas/NSPanel_HA_Blueprint#76]
I have the joBr99 nspanel-lovelace-ui installed, and following the guide to replace the tft file.
I don't have the upload tft service in developer tools. Am i looking in the wrong place?

**Comment by wendtc** [comment]
I have found this on the esp home Doku - Lovelace ui
![image](https://user-images.githubusercontent.com/50050028/204397639-837a4154-e0fd-47c1-abf8-bf6cef5d2001.jpeg)

![image](https://user-images.githubusercontent.com/50050028/204397652-7621cdcb-a220-470f-96d7-f26d09e6ddc9.jpeg)

Christian

**Comment by bluemaster27** [comment]
Where do I put this api ?

**Comment by moustic999** [comment]
are you using espHome or Tasmota ?

**Comment by bluemaster27** [comment]
> are you using espHome or Tasmota ?

I use both in my HA. The nspanel now ofcourse runs Tasmota, because of the  joBr99 integration.

**Comment by Blackymas** [comment]
then you should be able to upload the tftf manually via tasmota or similar. i think jobro99 mentioned this somewhere.

In general there should be a function because he has the option to use the beta

Unfortunately I don't use Tasmota. But on the Internet should be able to find something

**Comment by bluemaster27** [comment]
on the prepare nspanel page of jobro99 it say this:

**Flash Firmware to Nextion Screen**[¶](https://docs.nspanel.pky.eu/prepare_nspanel/#flash-firmware-to-nextion-screen)
Due the limitations of Berry, it's not possible to download the tft file directly from github, so I'm also renting a small server where you can download the file via HTTP.

Use the one following commands in the tasmota console (not berry console) to flash the latest release from this repository:

EU Version: **FlashNextion http://nspanel.pky.eu/lui-release.tft**

So, if I'm correct,in my case, I should put this in the Tasmota console?

FlashNextion /local/nspanel_blank.tft

**Comment by Blackymas** [comment]
yes exactly that looks good - please let me know if it worked. Is certainly also interesting for others.

If it works you can also post here a short description of how you did it step by step - so that others then know what they have to do.

Thanks for your feedback

**Comment by krachlatte** [comment]
receivng this error with FlashNextion http://ip-address-of-your-homeassistant:8123/local/nspanel.tft

Model does not match Device NX4832F035_011C

any idea

**Comment by Blackymas** [comment]
I close the issue because no feedback
