### ISSUE TITLE
3.3: Showing "None" for sensors without units

### ISSUE THREAD

**Issue by Pomezny** [Blackymas/NSPanel_HA_Blueprint#766]
When using sensor with unit_of_measurement set to "None" (for instance number of events) on home screen, "None" is displayed after the number.  I suggest units be omitted in this case. 
Screenshot of current behaviour:
![image](https://user-images.githubusercontent.com/4263174/235528973-97e2c989-abf5-41d8-b98c-442a5196576d.png)

**Comment by edwardtfn** [comment]
Yeah, that shouldn't be visible.
I will take a look at this tomorrow.

**Comment by Pomezny** [comment]
Everything(TFT, BP, ESPHome) is 3.3 as stated in title.

**Comment by Blackymas** [comment]
solved :)
