### ISSUE TITLE
[nextion:396]: Nextion reported variable name invalid!

### ISSUE THREAD

**Issue by finalbillybong** [Blackymas/NSPanel_HA_Blueprint#768]
Just installed the latest ESPHome update (2023.4.3) and update all my devices. My NSPanel is no stuck on the boot screen and showing [nextion:396]: Nextion reported variable name invalid! in the logs. 

Any ideas?

**Comment by edwardtfn** [comment]
I'm gonna update my testing panel and try it... Just a minute.
By the way, which version of TFT, ESPHome and Blueprint are you using?

**Comment by finalbillybong** [comment]
Sure.

I am using 3.1.0 of the blueprint, 2023.4.3 of ESP and I'm not sure on the TFT version, how can I find that info?

**Comment by finalbillybong** [comment]
I didn't know 3.3 was available is all. I will update now.....

**Comment by finalbillybong** [comment]
OK I have updated blueprint to 3.3 and pressed TFT update button in HA. This is how my panel looks now.

![IMG_0567](https://user-images.githubusercontent.com/24855560/235632369-907b7454-c8da-4401-b91b-3840847efa98.jpg)

**Comment by edwardtfn** [comment]
Ok. When updating ESPHome it automatically used the latest code from GitHub to update your firmware, but now you have a version mismatch.

Please take a look at this link to update your TFT and Blueprint: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#2-update-blueprint

And let us know if you get stuck.

**Comment by finalbillybong** [comment]
OK so I have updated the blueprint and reloaded my automations, the panel will now boot to the Home Screen but with no temp info. The buttons work but that's it. The update TFT button will make the panel go through the motions of updating but when it has finished it is still on TFT version 3.1

**Comment by edwardtfn** [comment]
Your ESPHome settings are probably pointing to a local copy of TFT which still in v3.1.

If you go in your ESPHome yaml settings, there's the url for your TFT file.
What is there?

**Comment by finalbillybong** [comment]
You're absolutely right! It's a local URL. I'll grab the latest TFT and put it at that location. 

Thanks for your help.

**Comment by edwardtfn** [comment]
This is the link for downloading the TFT file: https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/nspanel_eu.tft

You have to download that and then update it in your local server. You probably have done that before when installing v3.1.

**Comment by edwardtfn** [comment]
Is your panel working fine now?

**Comment by ondras76** [comment]
hello, I hade the same problem. I just fix the versions, but I have now blank page on the tft.![image](https://user-images.githubusercontent.com/115325615/235654313-d89313c2-a73f-4561-a3cf-be3e4eba1df6.jpeg)

**Comment by finalbillybong** [comment]
> Is your panel working fine now?

Yes all sorted. Sorry for the slow reply. I had to nip out. Thanks for your help!
