### ISSUE TITLE
Missing info on screen after update

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#769]
From @ondras76 in another issue:

Hello, I hade the same problem. I just fix the versions, but I have now blank page on the tft. Thank you for your help!

![image](https://user-images.githubusercontent.com/115325615/235654313-d89313c2-a73f-4561-a3cf-be3e4eba1df6.jpeg)

_Originally posted by @ondras76 in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/768#issuecomment-1531309703_

**Comment by edwardtfn** [comment]
@ondras76, cult you please take a look at your Home Assistant logs (Settings > System > Logs) and look for any message related to this panel?

Also, please double check at the boot page if everything (blueprint, esphome and TFT) are with the same version.

**Comment by ondras76** [comment]
@edwardtfn first thank you for yor help! You right, I just see, is still old version of tft. I don't understand. I was download new file and copy to my www folder
![IMG_2119](https://user-images.githubusercontent.com/115325615/235681114-8572f175-badf-430e-8c3f-aed46eb34805.jpg)

**Comment by edwardtfn** [comment]
Try pressing the button "Upload TFT" in your device page (Settings > Devices and Services > ESPHOME).

**Comment by ondras76** [comment]
> @edwardtfn first thank you for yor help! You right, I just see, is still old version of tft. I don't understand. I was download new file and copy to my www folder ![IMG_2119](https://user-images.githubusercontent.com/115325615/235681114-8572f175-badf-430e-8c3f-aed46eb34805.jpg)

also log from esp 
![Snímek obrazovky (2)](https://user-images.githubusercontent.com/115325615/235685612-67c21106-03df-434a-893b-554ff3f424d3.png)

**Comment by ondras76** [comment]
> Try pressing the button "Upload TFT" in your device page (Settings > Devices and Services > ESPHOME).

all is fine, the error was in the wrong url address in esp config. Thank you!

**Comment by edwardtfn** [comment]
So, is your panel working fine now?
