### ISSUE TITLE
Loading problem

### ISSUE THREAD

**Issue by xpsst** [Blackymas/NSPanel_HA_Blueprint#771]
Hey alle zusammen - nachdem Update ein komisches Problem. 
Update läuft ohne Probleme. Blueprint / ESPHome / tft geupdatet. Danach steht auf dem Display nur „loading“ die Hardware Buttons gehen. Jemand n Idee?

![IMG_2301](https://user-images.githubusercontent.com/107148542/235851981-65fc8b5d-7a27-4069-96f1-38493e318c13.jpeg)

**Comment by Blackymas** [comment]
Im blueprint alles ausgewählt? Hast du aktuelle ha Version am laufen?

**Comment by xpsst** [comment]
Ja beides Aktuell - die Hardware Buttons reagieren auch auf die Blueprint.

**Comment by smartmatic** [comment]
Über Loading bin ich bisher auch nicht hinaus gekommen. Schaffe es auch nicht die aktuelle ESPHome Version zu installieren. Dann kommt dieser Error

`xtensa-esp32-elf-g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
*** [/data/nspanelbad/.pioenvs/nspanelbad/src/esphome/components/web_server/web_server.cpp.o] Error 1
========================= [FAILED] Took 217.75 seconds =========================`

**Comment by smartmatic** [comment]
Dafür hängt das Panel nun im Boot Screen

![IMG_0634](https://user-images.githubusercontent.com/74932663/235905612-8fc199b5-abd0-4f3b-a02d-b98ad6bc49b9.jpeg)

**Comment by seagull2000** [comment]
Hi, It looks like I have a loading issue too after the update. My error is different though and from what I can tell this is due to a depreciated command?

[W][nextion:396]: Nextion reported variable name invalid!

I have tried limiting the compile process limit just in case it helped but it hasn't resolved


![20230503_124231](https://user-images.githubusercontent.com/64470552/235908381-2ee329bc-6b96-4f9e-90d5-2f489bccb1fd.jpg)

**Comment by edwardtfn** [comment]
You have different versions between TFT and esphome.
You have to update your TFT and make sure everything is in the same version.

You can find update instructions here: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#2-update-blueprint

**Comment by xpsst** [comment]
@smartmatic 
Sah bei mir auch erst so aus - musste das alte Blueprint löschen - HA Rebooten - dann das neue drauf, sonst hat er das irgendwie nicht überschrieben.

Problem erledigt, hatte die 3.2.2 TFT Version, irgendwie die falsche geladen - nun läuft alles. Vielen Dank!

**Comment by smartmatic** [comment]
> @smartmatic Sah bei mir auch erst so aus - musste das alte Blueprint löschen - HA Rebooten - dann das neue drauf, sonst hat er das irgendwie nicht überschrieben.
> 

Danke, das hat geholfen, wenn auch umständlich. Hatte nicht nur den Blueprint sondern auch die Automation gelöscht. (vorher ein Backup des YAML Code gemacht). Leider war es nach neu anlegen des Blueprint und neu erstellen der Automation nicht möglich den alten Code wieder rein zu kopieren. So musste ich den alle Entitäten manuell neu auswählen, was etwas mühselig war. Es ist einfach kein speichern Button im YAML Editor aufgepoppt.

Lässt sich das ändern / Konfigurieren, dass auch speichern über den YAML Editor möglich ist?

**Comment by deejaybeam** [comment]
Aus meiner Sicht der einfachste Weg ist der folgende:
Austauschen des Blueprints (entweder die gesamte Datei, oder einfach nur den Inhalt), danach einfach in den Entwickler-Tools die Automatisierungen neu laden - fertig
![image](https://user-images.githubusercontent.com/10434729/236178288-57252fcf-4339-4514-961c-a741ae06be07.png)

**Comment by DiggaTS** [comment]
Ich hatte das gleiche Problem. Austausch des Inhalts der Blueprint ist fehlgeschlagen. 

-Alte Blueprint löschen
-Restart Home Assistant
-Neue in den Ordner kopieren
-Neustart HA. Danach sofort alle NS Panels wieder da. 

Danke für die Arbeit!

**Comment by Blackymas** [comment]
da alle Probleme gelöst sind schließe ich das ticket
