### ISSUE TITLE
Restore Original NSPanel Firmware

### ISSUE THREAD

**Issue by pitoganzado** [Blackymas/NSPanel_HA_Blueprint#773]
Hi to all,
how can i restore to the original firmware?
thank you!

**Comment by edwardtfn** [comment]
You mean the original firmware from Sonoff?

**Comment by pitoganzado** [comment]
> You mean the original firmware from Sonoff?

Yes

**Comment by Blackymas** [comment]
the same way you can install your version - pls try to use google ;)

**Comment by edwardtfn** [comment]
For reference: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/972#issuecomment-1673164989
