### ISSUE TITLE
ns panel not working

### ISSUE THREAD

**Issue by pabloMG85** [Blackymas/NSPanel_HA_Blueprint#775]
today y update de nspanel and now is not working
![IMG_20230503_205052_862](https://user-images.githubusercontent.com/10106604/236027625-793c710f-d72f-4f26-b615-69145866476c.jpg)
y can see the nspanel on integration section y can control it but dont have the gome menu on display only loding logo,tnx

**Comment by edwardtfn** [comment]
Your TFT file is on v3.1 while ESPHome is 3.3. In order for this to work you need all (TFT, ESPHome and Blueprint) with the same version.

**Comment by dfurnell** [comment]
Thanks Edwardtfn, I have the same issue but I cant see how to locate the file mentioned in file editor: 



 
![HA](https://user-images.githubusercontent.com/52839232/236050643-3ddc2290-61ee-4688-94f8-a1362c2ce7f0.JPG)

**Comment by edwardtfn** [comment]
Let's try something different then... Could you please share your ESPHome yaml settings? Please make sure to remove any private info (Wifi credentials, etc.).

**Comment by dfurnell** [comment]
![HA1](https://user-images.githubusercontent.com/52839232/236054254-7c30f94f-654d-42f9-bf7a-d71fad8c5e1f.JPG)

I have been looking the local file but can't seem to locate via file editor.

**Comment by dfurnell** [comment]
I restarted file editor which then gave me access to the above stated file location.
I have copied in and updated the nspanel_blueprint.yaml file which now has the nspanel moving onto the homepage with loading visible. I'm guessing there is a config now in the new template that it isnt happy with.

Previously I have been through the template removing one item at a time until the nspanel correctly loaded is there a better way to do workout blueprint issues?

**Comment by edwardtfn** [comment]
Could you please double check the versions on the boot page?
Which versions you have for TFT and Blueprint?

**Comment by dfurnell** [comment]
TFT=3.2 and blueprint =3.3

**Comment by edwardtfn** [comment]
You have to update TFT to v3.3.

Download the file from GitHub:
- [EU version](https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/nspanel_eu.tft)
- [US version](https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/nspanel_us.tft)

Then upload it to your local www server in Home Assistant using the File Editor (browse to the folder www, delete the old TFT from there and then upload the new one).
Then go to your device page (Settings > Devices and Services > ESPHome) and press `Upload TFT`.

**Comment by haywiremk** [comment]
I think this issue is that 3.3 is now published.  If you did not update the automation and TFT then there was a recent update to ESP Home.  That like recompiled from

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint

And this borks everyone's setup who has not updated the other files.  I had this occur right after a ESP Home update.  In the process now of getting the automation YAML and TFT file updated.  Not sure if there is a way to specify a specific release in this ESP home config file url

**Comment by dfurnell** [comment]
Thanks @edwardtfn

All backup line, although it looks like some of the icons may need reassigning as i'm getting explanation marks on a lot of the screens but can do that later.

**Comment by edwardtfn** [comment]
@pabloMG85, is your panel working properly now?

**Comment by pabloMG85** [comment]
yes after y update to 3.3 is ok the only thing is now y have on every scroll of the pages the loading lag for 0.5 seconds

**Comment by edwardtfn** [comment]
I believe next release will improve the loading speed a lot... 😉
