### ISSUE TITLE
NSPanel TFT Upload

### ISSUE THREAD

**Issue by Tag1975** [Blackymas/NSPanel_HA_Blueprint#780]
Hallo,
ich versuche schon Stundenlang mein neues Panel installiert zu bekommen. ESP Home ist aktuell, Blueprint ist aktuell, TFT ist geflasht und trotzdem erscheint nicht der Button "Update TFT Display" in der Integration. Kann mir einer Erklären an was dies liegen könnte? Danke schon einmal. 

PS: Es ist mein 2. Panel. Erstes Panel hat komischerweise 39 Entitäten und das neue nur 31.

Hello,
I have been trying for hours to get my new panel installed. ESP Home is up to date, Blueprint is up to date, TFT is flashed and still the button "Update TFT Display" does not appear in the integration. Can anyone explain to me what this could be? Thanks already once.

PS: It is my 2nd panel. First panel has strangely 39 entities and the new only 31.

![Bildschirmfoto 2023-05-04 um 17 12 08](https://user-images.githubusercontent.com/123659634/236251597-76ffa4f4-3fb2-4a68-b85b-8cadf3cc7cfe.png)

**Comment by edwardtfn** [comment]
I would try removing this panel from your integrations and adding again.

To remove:
1. Go to Settings > Devices and Services > ESPHome 
2. Select the integration related to the panel missing entities
3. Click on the 3-dot menu and select "Delete"

To add it back (if not detected automatically after a few seconds):
1. Go to Settings > Devices and Services and then Click Add integration
2. Select ESPHome 
3. Add the name of your panel in the network (or it's IP address)
4. Follow the steps from ESPHome integration

**Comment by Tag1975** [comment]
INFO Resolving IP address of nspanelflur.local
INFO  -> 192.168.178.92
NFO Resolving IP address of nspanelk.local
INFO  -> 192.168.178.98

Sorry only for my understanding. Can it be that two panels can have the same IP address?
