### ISSUE TITLE
Unformatted values - Json view

### ISSUE THREAD

**Issue by simonepittis** [Blackymas/NSPanel_HA_Blueprint#782]
TFT: 3.3
ESPHome: 3.3
Blueprint: 3.3

Home Assistant 2023.4.6
Supervisor 2023.04.1
Operating System 10.0.dev20230423
Frontend 20230411.1 - latest

I want to report that some values arrive unformatted, it stays in JSON format
![image](https://user-images.githubusercontent.com/92569194/236245993-dfcf178f-557e-42c6-9078-2b05e9380b82.png)

![image](https://user-images.githubusercontent.com/92569194/236246038-2528445a-3002-4659-894e-8f483f2c3c1a.png)

...and others are disabled. with version 3.2 everything works

![image](https://user-images.githubusercontent.com/92569194/236246401-c88236dd-0e33-48ff-b7bf-df5e6617675b.png)
![image](https://user-images.githubusercontent.com/92569194/236246448-43dc86bf-c417-49cc-89d8-82d29a3adcd0.png)

**Comment by simonepittis** [comment]
ok, then I disable them because I don't like seeing data like that ;-)

Thanks

**Comment by edwardtfn** [comment]
Your blueprint won't work if you disable `sensor.xxxxx_nspanel_event` and/or `sensor.xxxxx_settings_entity`.
You can remove the other already disabled sensors, but not disable those two as they are key for the logic between the Blueprint and the panel communication.
