### ISSUE TITLE
Failed config

### ISSUE THREAD

**Issue by beachie13** [Blackymas/NSPanel_HA_Blueprint#787]
Hi I have been struggling to get my NSPanel working. Today I thought I world start from the beginning again. I create a new ESPhome device and when I tried to manual download the config to upload to the device, I get a config failed error: 

INFO Reading configuration /config/esphome/nspanel-office.yaml...
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:725]
  name: nspaneloffice Notification sound
  platform: template
  id: notification_sound
  entity_category: config
  restore_state: True
  optimistic: True
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:769]
  name: nspaneloffice Sleep mode
  platform: template
  device_class: switch
  id: sleep_mode
  entity_category: config
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF
  restore_state: True
  optimistic: False
  turn_on_action: 
    - logger.log: Sleep mode - Turn on
    - lambda: id(disp1).send_command_printf("home.sleepmodus.val=1");
    - lambda: id(disp1).set_component_value("settings.bt1",1);
    - switch.template.publish: 
        id: sleep_mode
        state: True
  turn_off_action: 
    - logger.log: Sleep mode - Turn off
    - lambda: id(disp1).send_command_printf("home.sleepmodus.val=0");
    - lambda: id(disp1).set_component_value("settings.bt1",0);
    - switch.template.publish: 
        id: sleep_mode
        state: False
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:793]
  name: nspaneloffice Relay 1 Local Fallback
  platform: template
  id: relay1_fallback
  entity_category: config
  restore_state: True
  optimistic: True
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:801]
  name: nspaneloffice Relay 2 Local Fallback
  platform: template
  id: relay2_fallback
  entity_category: config
  restore_state: True
  optimistic: True
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF

**Comment by edwardtfn** [comment]
Which version of ESPHome are you using?

**Comment by beachie13** [comment]
2022.11.5

**Comment by beachie13** [comment]
Thank you, fixed

**Comment by edwardtfn** [comment]
How have you fixed that?
