### ISSUE TITLE
Chips not showing up on the top panel

### ISSUE THREAD

**Issue by primeroz** [Blackymas/NSPanel_HA_Blueprint#790]
First of all , thanks for this ! 

I have a NSPANEL EU white i just flashed and started to play with. 

the `chips` panel at the top does not seem to be working for me, the space is just empty but is there, i can see the gap 

![PXL_20230505_153910916](https://user-images.githubusercontent.com/2085772/236504181-b46addd6-2879-4a96-9542-ddaa2d80fabe.jpg)

I was trying to add a couple of `binary sensors` which i confirmed are outputting `on/off` 

![image](https://user-images.githubusercontent.com/2085772/236503898-ec8d6898-9218-41bc-a913-20422ee28cf5.png)

when compare to the release notes of 3.2 where this picture is from , none of the other icons are there as well for me 

![226168209-42358090-d0fb-4e88-8d17-63893e51ac95](https://user-images.githubusercontent.com/2085772/236504293-10ba596c-b716-4c06-bca1-f1afb8b00e02.png)

What am i doing wrong ? 

Running on version 3.3

**Comment by rleongcs** [comment]
The icons will only be visible if the status is on for those sensors. Another important thing to note is the icons used must be in the [HASP ](https://htmlpreview.github.io/?https://github.com/jobr99/Generate-HASP-Fonts/blob/master/cheatsheet.html)list and not the overall HA icons list.

**Comment by primeroz** [comment]
ah that make so much sense :+1: 

thank you
