### ISSUE TITLE
Upload TFT

### ISSUE THREAD

**Issue by atvecko** [Blackymas/NSPanel_HA_Blueprint#794]
Uploading the TFT file slowed down after reaching 48%, (now 1% in 20 minutes). Can I stop it and start it again?

**Comment by atvecko** [comment]
01:01:22	[D]	[main:790] 			Nextion start - Inform Home Assistant display is ready
01:01:22	[D]	[binary_sensor:036]	        'nspanel01 Nextion display': Sending state ON
01:01:22	[D]	[main:795]			Nextion start - Done!
01:02:03	[W]	[nextion:396]		        Nextion reported variable name invalid!
01:02:03	[W]	[nextion:396]		        Nextion reported variable name invalid!
01:03:52	[D]	[button:010]		        'nspanel01 Update TFT display' Pressed.
01:03:52	[D]	[binary_sensor:036]	        'nspanel01 Nextion display': Sending state OFF
01:03:52	[D]	[nextion_upload:169]	Connected
01:03:52	[D]	[nextion_upload:175]	Requesting URL: http://192.168.0.251:8123/local/nspanel_eu.tft
01:03:52	[D]	[nextion_upload:209]	Updating Nextion NX4832F035_011C...
01:03:53	[D]	[nextion_upload:235]	Waiting for upgrade response
01:03:53	[E]	[uart:015]			        Reading from UART timed out at byte 0!
01:03:53	[E]	[uart:015]			        Reading from UART timed out at byte 0!
01:03:53	[E]	[uart:015]			        Reading from UART timed out at byte 0!
01:03:53	[D]	[nextion_upload:239]	Upgrade response is  4
01:03:53	[D]	[nextion_upload:242]	Available 0 : 0x00
01:03:53	[D]	[nextion_upload:242]	Available 1 : 0x00
01:03:53	[D]	[nextion_upload:242]	Available 1 : 0x00
01:03:53	[D]	[nextion_upload:242]	Available 2 : 0x00
01:03:53	[D]	[nextion_upload:242]	Available 3 : 0x05
01:03:53	[D]	[nextion_upload:242]	Available 3 : 0x05
01:03:53	[D]	[nextion_upload:246]	preparation for tft update done
01:03:53	[D]	[nextion_upload:274]	Allocating buffer size 65536, Heap size is 173360
01:03:53	[D]	[nextion_upload:274]	Allocating buffer size 65536, Heap size is 173360
01:03:53	[D]	[nextion_upload:291]	Updating tft from "http://192.168.0.251:8123/local/nspanel_eu.tft" with a file size of 6432100 using 65536 chunksize, Heap Size 111528
[D]	[nextion_upload:048]	                Requesting range: bytes=0-16383
[D]	[nextion_upload:048]	                Requesting range: bytes=0-16383
[E]	[uart:015]			                        Reading from UART timed out at byte 0!
[E]	[uart:015]			                        Reading from UART timed out at byte 0!
[E]	[uart:015]			                        Reading from UART timed out at byte 0!
[E]	[uart:015]			                        Reading from UART timed out at byte 0!
[E]	[uart:015]			                        Reading from UART timed out at byte 0!
[E]	[uart:015]			                        Reading from UART timed out at byte 0!
[E]	[uart:015]			                        Reading from UART timed out at byte 0!
[E]	[uart:015]			                        Reading from UART timed out at byte 0!
[D]	[nextion_upload:121]	                Nextion reported new range 134744072
[D]	[nextion_upload:302]	                Heap Size 109460, Bytes left -128311972
[D]	[nextion_upload:304]	                Successfully updated Nextion!
[D]	[nextion_upload:304]	                Successfully updated Nextion!
[D]	[nextion_upload:310]	                Restarting Nextion
[D]	[nextion_upload:313]	                Restarting esphome

[E]	[uart:015]		                                Reading from UART timed out at byte 0!
[W]	[nextion:072] 	                                Nextion is not connected! 
[E]	[uart:015]		                                Reading from UART timed out at byte 0!
[W]	[nextion:072]	                                Nextion is not connected!

**Comment by edwardtfn** [comment]
> Uploading the TFT file slowed down after reaching 48%, (now 1% in 20 minutes).

The total time for uploading the TFT shouldn't take more than 20min, so, something went wrong with this try.

> Can I stop it and start it again?

Yes, you should do that.

**Comment by atvecko** [comment]
After restart, ESP reports "Nextion reported variable name invalid!"
When trying to upload TFT: "Reading from UART timed out at byte 0!" and then the module freezes.

I'm done with this project, it's the second destroyed NS Panel out of three attempts.

**Comment by edwardtfn** [comment]
> After restart, ESP reports "Nextion reported variable name invalid!"

This happens when ESP is trying to send a command to the display setting a value, but the display is not using the right TFT. Don't worry about this message for now.

> When trying to upload TFT: "Reading from UART timed out at byte 0!" and then the module freezes.

Give a bit more of details and I'm sure we will be able to help you.
1. Which version are you installing?
2. Is this the first time you are installing a TFT other than Sonoff in this panel? What can you see in the screen? (A picture might help here)
3. Have you tried the "Exit reparse" button (instructions on the release notes)?
4. Can you share your ESPHome yaml settings? Please make sure you have removed any private info like wifi credentials.

> it's the second destroyed NS Panel out of three attempts.

I don't see any reason to think your panels are "destroyed".

**Comment by edwardtfn** [comment]
&nbsp;
### 3. "Exit reparse" button
One of the biggest challenges to a new user is to upload the TFT file for the first time. This is due to Sonoff using the [Protocol Reparse Mode](https://nextion.tech/instruction-set/#:~:text=20-,Advanced.,the%20serial%20buffer%20for%20processing) to control the communication with the Nextion display. This prevents ESPHome to communicate with the display using its default libraries and therefore prevents installing the new TFT.
With this version you will have a new button named "Exit reparse", which will send a command to the Nextion to exit that mode for a few seconds, giving to the use a chance to then upload the TFT file without the need to change your ESPHome settings or using older Nextion libraries.
![image](https://user-images.githubusercontent.com/94725493/235167581-50070e44-fff8-46b9-a036-c6b60b278d77.png)
Once you have successfully uploaded any of the TFT files from this project (`nspanel_blank.tft`, `nspanel_eu.tft` or `nspanel_us.tft`), the reparse mode will be permanently disabled and this button is not needed anymore.

If you have your panel displaying the Sonoff original screen, please follow the following steps to install your TFT file:
1. Go to the front of your panel with a portable device with access to Home Assistant
2. Open the device related to your panel under Settings > Device & Services > ESPHome
3. Press the new button "Exit reparse" and wait for your panel to change it's screen to another page (which will take around 10s)
4. While the new page is shown (it will be there for just a couple of seconds), press the button "Upload TFT"
5. You should then see the progress bar in your display and after no more than 20 minutes the new TFT will be displayed._

**Comment by atvecko** [comment]
ESP configuration is default, only wifi is set. ESP is functional. I am installing version 3.3. Version 3.0.3 was installed on the panel, which stopped working after the HA update. The display now shows the message "System Data Error"

**Comment by atvecko** [comment]
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel01" 
  wifi_ssid: .....
  wifi_password: ......

  nextion_update_url: "http://192.168.0.251:8123/local/nspanel_eu.tft"  

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

**Comment by atvecko** [comment]
'nspanel01 Exit reparse' Pressed.
Nextion reported variable name invalid!
Nextion queue is empty!

**Comment by atvecko** [comment]
Solved :
Hard reset (disconnect from power)
Upload blank.tft
Hard reset (disconnect from power)
Upload nspanel_eu.tft

Thanks for your time and advice even though it's Sunday morning :-)

**Comment by edwardtfn** [comment]
I'm glad to hear that.

**Comment by madasus** [comment]
i'm struggling with this also.  

My panel has the default screens still from the manufacturer.  I can see it fine in HA and in the logs i see button presses and the HA connection but when I hit the "Exit Reparse" it doesn't ever show anything on the screen.

Continue to get this whether I push the full or blank TFT.  Any additional thoughts?

I did another one of these panels a few months ago back on v3.1 and that worked fine and has continued to work after updating it to 3.3.

2:51:55 | [D] | [binary_sensor:036] | 'nsgarage Nextion display': Sending state OFF
-- | -- | -- | --
12:51:55 | [D] | [nextion_upload:169] | Connected
12:51:55 | [D] | [nextion_upload:175] | Requesting URL: http://1XXX:8123/local/nspanel_blank.tft
12:51:56 | [D] | [nextion_upload:209] | Updating Nextion ...
12:51:56 | [D] | [nextion_upload:235] | Waiting for upgrade response
12:51:56 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:51:56 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:51:56 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:51:56 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:51:56 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:51:56 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:51:57 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:51:57 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:51:57 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:51:57 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:51:57 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:51:57 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:51:57 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:51:57 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:51:57 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:51:58 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:51:58 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:51:58 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:51:58 | [E] | [uart:015] | Reading from UART timed out at byte 0!
12:51:58 | [D] | [nextion_upload:239] | Upgrade response is  19
12:51:58 | [D] | [nextion_upload:242] | Available 0 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 1 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 2 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 3 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 4 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 5 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 6 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 7 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 8 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 9 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 9 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 10 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 11 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 12 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 13 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 14 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 15 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 16 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 17 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 17 : 0x00
12:51:58 | [D] | [nextion_upload:242] | Available 18 : 0x00
12:51:58 | [D] | [nextion_upload:248] | preparation for tft update failed 0 ""
12:51:58 | [D] | [nextion_upload:324] | Restarting Nextion
12:51:59 | [D] | [nextion_upload:327] | Restarting esphome

**Comment by bhuebschen** [comment]
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/166

**Comment by edwardtfn** [comment]
I would suggest one last thing before you go to the hardware as suggested on #166.

Just a moment I will write here another link.

**Comment by madasus** [comment]
Hi - this is actually what I have already as I tried most of the obvious things I could find.  Did I miss anything from above?

substitutions:

###### CHANGE ME START ######
  
  device_name: "nsgarage" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
 # ota_password: !secret ota_password

  ip: "yyy"
  gw: "yyy.1"
  subnet: "255.255.255.0"
  dns: "yyy.1"

  baud_rate: "9600"
  nextion_update_url: "http://xxx:8123/local/nspanel_us.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h

ota:
  password: !secret ota_password

##### CHANGE ME END #####

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

**Comment by edwardtfn** [comment]
Try `baud_rate: "115200"` (or just remove that line completely).

Which error you have now?

**Comment by madasus** [comment]
Hi,

For some reason it just started working again today - with the above config still in place.  No clue why.

I have a couple more on order so i'll see what happens when they arrive!.  Thank you for the help

M

**Comment by LeFlairGoD** [comment]
> ### 3. Schaltfläche „Reparse beenden“.
> Eine der größten Herausforderungen für einen neuen Benutzer besteht darin, die TFT-Datei zum ersten Mal hochzuladen. Dies liegt daran, dass Sonoff den [Protocol Reparse Mode](https://nextion.tech/instruction-set/#:~:text=20-,Advanced.,the%20serial%20buffer%20for%20processing) verwendet , um die Kommunikation mit dem Nextion-Display zu steuern. Dies verhindert, dass ESPHome über seine Standardbibliotheken mit dem Display kommuniziert, und verhindert daher die Installation des neuen TFT. Mit dieser Version verfügen Sie über eine neue Schaltfläche mit dem Namen „Reparse beenden“, die einen Befehl an Nextion sendet, diesen Modus für einige Sekunden zu verlassen, sodass der Benutzer die Möglichkeit hat, die TFT-Datei dann hochzuladen, ohne Ihre Datei ändern zu müssen ESPHome-Einstellungen oder Verwendung älterer Nextion-Bibliotheken. Sobald Sie eine der TFT-Dateien aus diesem Projekt erfolgreich hochgeladen haben ( , oder ![Bild](https://user-images.githubusercontent.com/94725493/235167581-50070e44-fff8-46b9-a036-c6b60b278d77.png)`nspanel_blank.tft``nspanel_eu.tft``nspanel_us.tft`), wird der Analysemodus dauerhaft deaktiviert und diese Schaltfläche wird nicht mehr benötigt.
> 
> Wenn Ihr Panel den Sonoff-Originalbildschirm anzeigt, befolgen Sie bitte die folgenden Schritte, um Ihre TFT-Datei zu installieren:
> 
> 1. Gehen Sie mit einem tragbaren Gerät mit Zugriff auf Home Assistant an die Vorderseite Ihres Panels
> 2. Öffnen Sie das zu Ihrem Panel gehörende Gerät unter Einstellungen > Gerät & Dienste > ESPHome
> 3. Klicken Sie auf die neue Schaltfläche „Reparse beenden“ und warten Sie, bis Ihr Panel den Bildschirm auf eine andere Seite wechselt (was etwa 10 Sekunden dauern wird).
> 4. Während die neue Seite angezeigt wird (sie wird nur für ein paar Sekunden angezeigt), drücken Sie die Schaltfläche „TFT hochladen“.
> 5. Anschließend sollten Sie den Fortschrittsbalken in Ihrem Display sehen und nach spätestens 20 Minuten wird das neue TFT angezeigt.

Thanks a lot for that!!! It Works

**Comment by weberjam007** [comment]
> Solved : Hard reset (disconnect from power) Upload blank.tft Hard reset (disconnect from power) Upload nspanel_eu.tft
> 
> Thanks for your time and advice even though it's Sunday morning :-)

Thank you for posting this. I borked my first tft update and ended up with the black screen that said, "System data ERROR!" I found the blank tft in the custom configuration folder and uploaded that (did a Reparse and Update). After the blank update it showed a QR code (no mor black screen). Then I was able to use the correct tft (nspanel_us for me) and was able to update the tft without an issue.

**Comment by robbiedehand** [comment]
and what if i dont see the reparse button? i have the same here, my config looks like this
`###### CHANGE ME START ######
  device_name: "nspanel01" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "https://homeassistant.local:8123/local/nspanel_eu.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####
##### My customization - End #####`

**Comment by edwardtfn** [comment]
@robbiedehand, please [create a new issue](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/new) explaining what is the problem you are facing and sharing as much info as possible (like the yaml above, but also logs, photos of the screen, if you are updating from a previous version or if this is a new panel, etc).
I will be happy to help.
