### ISSUE TITLE
Upload updated NSPanel file fail !

### ISSUE THREAD

**Issue by andriuszvirblis** [Blackymas/NSPanel_HA_Blueprint#798]
Tried to upload newest NSPanel tft but it failed, showing this kind of error as per preview picture.
![PXL_20230508_151633077](https://user-images.githubusercontent.com/127489722/236863219-88970cf8-d549-4c4b-b763-da12e122a876.jpg)

**Comment by edwardtfn** [comment]
Double check your `nspanel_eu.tft` file. You can use your browser, in your laptop, to download the file using the same url you are providing to your panel, then double check the file size compared to when you download from GitHub (latest version is around 6.13Mb).
If everything is fine, just try again, as it could be some temporary issue ij your Wi-Fi network.

**Comment by andriuszvirblis** [comment]
Hi,

I have downloaded newest version from your depository and uploaded to my HA
Samba share, path is local and before everything worked fine, except this
time when I tried to update to newest version of it and it showed this
error message.

Andrius

**Comment by andriuszvirblis** [comment]
And sorry but i don't want to get back to soldering and connecting wires to NSPanel, is there a way for a less complicated way to update this tft file ?

**Comment by edwardtfn** [comment]
When you click Upload TFT button, do you see anything happening in your panel?

**Comment by andriuszvirblis** [comment]
Yes it starts uploading and shows upload process with % as usual, but then
after 5 second or so, stops and shows this error message.

Andrius

**Comment by edwardtfn** [comment]
So, I don't think you need soldering... Looks like the transfer starts, but it interrupt by an unexpected end of file or some interruption in the network.
Again, take a look at your file size. I would again suggest to download the file from your local server using your browser (in your computer) to double check your local server and the file size. If you can fully download the file with your laptop using the same url as your panel is trying and the file is downloaded correctly, then you focus on the Wi-Fi signal. But test your local server and file first.

**Comment by andriuszvirblis** [comment]
Indeed, you are right, my file was only 170 kb size, i dont know why, uploaded a new one and uploaded it successfully.

**Comment by edwardtfn** [comment]
Is everything working fine now?

**Comment by andriuszvirblis** [comment]
Yes, it is working. Thanks for the help.

Andrius
