### ISSUE TITLE
Blueprint update failure 3.2 - 3.3

### ISSUE THREAD

**Issue by jshep321** [Blackymas/NSPanel_HA_Blueprint#799]
Hi,
I updated my esphome and noticed my nspanel was stuck on the boot screen ("please wait").  After some digging, I see I needed to manually update the blueprint.  This failed.  

 Failed to load blueprint: mapping values are not allowed here in "/config/blueprints/automation/Blackymas/nspanel_blueprint.yaml", line 28, column 66 

HA is fully up to date - 2023.5.2, ESPHome - 2023.4.4

Thanks!

<img width="1473" alt="image" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/12618683/da847ddf-d1a8-4431-ad20-cf273ee4958c">

**Comment by lloydbayley** [comment]
What I always do when updates is to upload the relevant tft, update the blueprint and open each automation using the blueprint to check if any changes are needed. Even if not, I always save the automation again to implement the blueprint in the automation. I've not had any problems with these steps in mind.

**Comment by jshep321** [comment]
Thanks for the comments, but this error is in the Settings->Blueprints  screen.  Doesn't that mean that the blueprint itself is the issue and not the downstream automation, tft, etc?
<img width="1528" alt="image" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/12618683/63f98cf3-7c42-4975-9897-f9db6c8e76f5">

**Comment by edwardtfn** [comment]
The error message isn't very useful, as line 28 is just text.
When you click the log message (Settings > System > Logs) can you see more details? Do you have other messages?

Try to copy the content of the Blueprint from GitHub again ([this link](https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/nspanel_blueprint.yaml)) and paste on your local file. It should have 7416 lines.
Reload your automations or restart Home Assistant after this.

If the error persists and you cannot have more info to share here, try to delete any automation previously created using this Blueprint and then try to create a new one.

Please let me know more details and I will try to help.

**Comment by jshep321** [comment]
Well I feel stupid....  Thanks @edwardtfn!  The 7416 line count was the key information to me.  Somehow my blueprint download was corrupted.  I used wget (instead of a copy/paste) so I would think it was bit-exact/perfect.  Perhaps I fat fingered in the editor after downloading....  

A new wget and all is well.
