### ISSUE TITLE
Support more domains to be assignable to buttons

### ISSUE THREAD

**Issue by deejaybeam** [Blackymas/NSPanel_HA_Blueprint#8]
Maybe it would be possible to support more domains for assigning to a button in addition to switch, cover, light, input_boolean as a "read-only" component. This way it would be possible to have e.g. one page with an overview of persons at home.
- [x] button-entities
- [x] person-entities
- [x] scene-entities
- [x] automation-entities

**Comment by Blackymas** [comment]
I would have to think about when the rest is ready currently I still have some construction sites

**Comment by GuySie** [comment]
Would love to have scenes supported in buttons. I rarely control a single light and far more often use a preset scene.

**Comment by Blackymas** [comment]
> Would love to have scenes supported in buttons. I rarely control a single light and far more often use a preset scene.

I use Light Groups for this. But yes we will implement that because it is also important to the developer deejaybeam ;)

**Comment by deejaybeam** [comment]
merged into dev:
https://github.com/Blackymas/NSPanel_HA_Blueprint/commit/592200e7d67081a516c17feda2af6c25ee8c1d74

**Comment by Blackymas** [comment]
Published in v2.1.o

https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v2.1.0
