### ISSUE TITLE
Sleep on Buttonpage

### ISSUE THREAD

**Issue by ghostridernrw40** [Blackymas/NSPanel_HA_Blueprint#801]
Hi,

ich habe wie im folgenden Artikel beschrieben die Buttonpage01 gesetzt, jedoch funktioniert der Sleep nur auf dem Homescreen.

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/576

Da ebenfalls im Artikel https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/576 die Auswahl des Homescreen diskutiert wird, sollte dabei der Sleep mit bedacht werden.

Viele Grüße

**Comment by Blackymas** [comment]
Hallo,

ja der Sleep modus geht nur über die Homepage.

Eine andere Page als Start Seite zu machen war auch nie beabsichtigt zum aktuellen Zeitpunkt. Es funktioniert nur auch den Workaround aus #576 


Ob wir den aufwand betreiben werden alles umzuschreiben, weiß ich noch nicht.
