### ISSUE TITLE
Chips not displayed on the nspanel (EU)

### ISSUE THREAD

**Issue by rbr101** [Blackymas/NSPanel_HA_Blueprint#808]
I'm using the EU version of nspanel and when i define the chips in the blueprint nothing is displayed on the screen.
Everything else seems to work fine. 

I'm using blueprint v3.3

**Comment by rleongcs** [comment]
Have you refered to #790 to see if your issue is similar?

**Comment by Blackymas** [comment]
chips if only displayed when the value is on - as has already been linked

**Comment by rbr101** [comment]
Thanks, didn't know this. 
I can see the icons in the top left screen when state is on.
