### ISSUE TITLE
ENTITY PAGE SETTINGS question

### ISSUE THREAD

**Issue by pbranly** [Blackymas/NSPanel_HA_Blueprint#809]
Hi
In the menu, it is written that it is possible to activate that option for "entity page and **entity page Button** on the home page"
I can find only "entities"
My understanding was that it could provide a quick access to either entity status "cover is open ou close, or light is on or off" or (and) buttons to control that entity
but it seems that this gives information only
Is this the normal behavior ?
Thanks
Phil
![2023-05-11_17-30](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/22018509/e293f729-5811-4735-b488-e02da85a37f4)

**Comment by rleongcs** [comment]
Yes, that is normal. It only shows the status and DOES NOT control the entity.

**Comment by pbranly** [comment]
You should remove «  and entity page button » from the text 
Phil

**Comment by Blackymas** [comment]
no why only if you activate this you get a button on the home page and only through this button you come to entity page.

so all is fine
