### ISSUE TITLE
compilation terminated

### ISSUE THREAD

**Issue by KarlKaracho** [Blackymas/NSPanel_HA_Blueprint#812]
Hello together,

I have the following problem during installation.
When installing the ESP project, I receive the following error message:

INFO Reading configuration /config/esphome/nspanel.yaml...
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing nspanel (board: esp32dev; framework: arduino; platform: platformio/espressif32 @ 5.3.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- WiFiClientSecure @ 2.0.0
|-- HTTPClient @ 2.0.0
Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/api/api_server.cpp.o
Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/api/subscribe_state.cpp.o
Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/api/user_services.cpp.o
Compiling /data/nspanel/.pioenvs/nspanel/src/esphome/components/binary_sensor/automation.cpp.o
xtensa-esp32-elf-g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
*** [/data/nspanel/.pioenvs/nspanel/src/esphome/components/api/subscribe_state.cpp.o] Error 1
========================= [FAILED] Took 29.41 seconds =========================

I have installed ESP Home and connected the panel as described in the "Smart Home Yourself" video.

However, I am receiving the same error message with various flash options. This occurs both when flashing via USB and FTDI adapter to the Home Assistant Raspberry Pi, as well as when creating a .bin file in the normal manner.

Can someone help me with this issue?

**Comment by deejaybeam** [comment]
No - to clear something up:
ESPhome (the Platform/Addon) is just a piece o software, that makes it possible to define a (complex) source-code with the goal to compile a firmware, that can be installed/running on the esp32 microcontroller.
The code (the definition) describes what the microcontroller should do.
But first of all the definition (nspanel_esphome.yaml) has to be compiled (with your definitions like hostname, ...) to a binary executable (firmware -> this is something like a mix of operatingsystem and installed software).
AFTER a successful compilation (at your error shows that this fails on your system), this binary has to be installed on the esp-chip itself (like installing the operating-system).
When this was successful, HA-Integration needs to find/connect to your device (this is independent to the ESP-Home Platform), after that the device can tell your HA-Instance what it is, and what services it has.

you shuld also have a look here https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/671 to understand the background

I think you may have a problem like that: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/249
Or one of the linked topics

**Comment by KarlKaracho** [comment]
Hey,
thank you for your response.

Unfortunately, I'm still not making much progress.
Here's what I've done:

In the meantime, I installed joBr99's version. It worked to some extent, but I haven't given up on the goal of this version.

The regular process doesn't work because I still get the message "compilation terminated." I'm using a Raspberry Pi 4. Could it be too weak?

With the help of #645, I was able to flash the .bin file, but I haven't reached my goal yet.
With the original version of #645, I get the error "Nextion is not connected."
When I try to update the TFT, I get the error "Reading from UART timed out at byte 0!"
I've searched for a solution here as well, but either I'm too dumb for the answers or I can't find a suitable one.
I found the hint about the baud rate, but how do I change it if I can't use ESP Home as usual... :-)
I don't understand the hint with "Exit reparse" because where can I find this button?!

My TFT file is located here and is accessible: "http://192.168.178.40:8123/local/nspanel_eu.tft"
ESP Home is installed and, as far as I know, working fine.
The panel is recognized under devices once I flash the .bin file.
The display currently only shows "waiting for content..."

Can you help me get on track with this?

**Comment by Blackymas** [comment]
Hallo,

du kannst nur versuchen die version "nspanel_blank.tft zu installieren.

ich gehe davon aus du hast auch das nicht gesehen oder?
https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(DE)-Erste-Schritte---Installation-und-Einrichtung#2-version-nspanel-lovelace-ui-von-jobr99-wurde-vorher-installiert

Wenn du vorher die Version von jobr99 installiert hast gibt es probleme mit dem upload vom TFT.

das "waiting for content" kommt vom tft Version von jobr99 und hat nichts mit unserer Version zu tun.

Du kannst auch mal in den issues danach suchen, da wirst du etwas finden

**Comment by Blackymas** [comment]
close no feedback
