### ISSUE TITLE
Thermostat view for by pool

### ISSUE THREAD

**Issue by swemaverick** [Blackymas/NSPanel_HA_Blueprint#814]
Hi! I have a balboa pool heater that is connected via BWA Link. I get all the data into HA, can modify the temperature from my app to the entity "Target temperature for pool". This entity is of the format number. I'd like to be able to modify this via the Thermostat view example in the awesome NSPanel Blueprint solution. 
Does anyone know how to "fool" this around? I tested with the generic thermostat but that is setting a value true/false until a temperature is reached. I'd just like to set the value choosen in the NSPanel to a fixed value of let say 37 degrees Celsius.

**Comment by edwardtfn** [comment]
You probably can create a Generic Thermostat, which will create a climate entity which can be used in the panel.

https://www.home-assistant.io/integrations/generic_thermostat/

**Comment by edwardtfn** [comment]
Aha! I think I got your point...

You can try something like this: https://github.com/jcwillox/hass-template-climate

**Comment by swemaverick** [comment]
Tested that but not really working either. What I'm after is to have the nice looking dial to set the value and that an entity should use that value that I set. I solved it for now with two automations, one for 37 degrees and one for 30 degrees and those sets the entity as such. But from a bling-bling perspective to impress on friends the dial should be nice to have in the nspanel instead of two (automation) buttons.

**Comment by Blackymas** [comment]
we work on big redesign for climate. So please wait for the next update ;)

**Comment by Blackymas** [comment]
In the DEV version is already the new version of the Climate, if you want to test it.

Otherwise you can also follow this issue where you can see all the changes and the current status.

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/848
