### ISSUE TITLE
Button Page 04 - Button 32 - Cosmetic BUG

### ISSUE THREAD

**Issue by sfaragdas** [Blackymas/NSPanel_HA_Blueprint#815]
Hi I saw that on Button 32 name - LABEL (Optional) - is dropbox from Button 32 - ICON (Optional) and revers ;-)

**Comment by sfaragdas** [comment]
Thank you so much, I apologize, I just noticed that the first paragraph got cut off, so here it is again:
Thank you so much, you did a great job ;-)

**Comment by Blackymas** [comment]
Fixed will be available with the next version so we close the ticket.
