### ISSUE TITLE
Blueprint 3.3.1 issue 

### ISSUE THREAD

**Issue by pbranly** [Blackymas/NSPanel_HA_Blueprint#821]
Hi
I know that I should use esphome, blueprint and tft with the same version but could not find esphome and tft.
I have version 3.3 for esphome and tft and I tried the last 3.3.1 blueprint available in the dev branch.
I see the version 3.3.1 I the start menu of the screen then it is stuck in a “loading” page .
I have reverted to blueprint 3.3 and it work again .
Is it normal ? Do Ihqve to wait or find esphome and tft in version 3.3.1 ?
Thanks per advance
Phil

**Comment by edwardtfn** [comment]
> Is it normal ?

Don't expect "normal" in dev environment... 😂
Right now, v3.3.1 (DEV) contains only TFT in EU mode and the Blueprint, the other parts will come later.

**Comment by pbranly** [comment]
Ok as I have the us version ….. error in correct …
I close the ticket
Good job …. Congratulation 
Phil
