### ISSUE TITLE
nspanel_us.tft latest update crashing NSPanel

### ISSUE THREAD

**Issue by MedvedAM** [Blackymas/NSPanel_HA_Blueprint#822]
After the latest update, copied locally nspanel_us.tft update takes 4-5 hours to complete and after completion it starts reboot loop with system error. ESP part works fine and I still can control the panel through Home Assistant.

Nextion display - Unknown
NSPanel Hall - Home
RSSI - -53 dBm

**Comment by edwardtfn** [comment]
The TFT update shouldn't take more than 15 to 20min. If it is taking more than 30min you probably have an issue and I would suggest you cancel and start over.
Please make sure you have the right file, with the right size.

**Comment by MedvedAM** [comment]
> The TFT update shouldn't take more than 15 to 20min. If it is taking more than 30min you probably have an issue and I would suggest you cancel and start over. Please make sure you have the right file, with the right size. The file nspanel_us.tft v3.3 should be around 7.6Mb. Installing nspanel_blank.tft before nspanel_us.tft is also a good idea.

Thanks a lot, new rephrase button worked and I flashed it with blank then us and now it's all showing fine.
