### ISSUE TITLE
Stuck on Please wait

### ISSUE THREAD

**Issue by kristianolofsson** [Blackymas/NSPanel_HA_Blueprint#823]
Just did an upgrade to 3.3 and got stuck. The screen stays at "Please Wait" and show the local IP on top.

- ESP Home is online and no errors in the log (No red lines). 
- Nothing strange in the Blueprint trace (as far as I can see)
- NSPanel device shows as online with IP and shows "Connected"

I have tried to Exit reparse, restart and update the TFT display but it keeps going to the same.
I even tried to cut power and reboot. but no.

Im stuck. How to proceed?

**Comment by rleongcs** [comment]
Please check the automation as in 3.3, some changes were made and you have to select your NSPanel from a dropdown now. Also the icons if you have setup will need to be selected from dropdown also.

**Comment by Blackymas** [comment]
After each update, at least a blueprint should be looked at.

Things keep changing because we want to keep improving the nspanel version

**Comment by kristianolofsson** [comment]
Panel name selected both in esphome yaml and in automation. Don’t know if required. If only selected in blueprint I get error during install. Despite reload of automation. Name is set to “nspanel1” in both places.

I checked the blueprint but can’t find anything wrong. 

I did a reboot of HA and now it works. I thought reload of automations was enough. 

Sorry guys!

**Comment by Blackymas** [comment]
welcome ;)
