### ISSUE TITLE
Hardware buttons not working as expected

### ISSUE THREAD

**Issue by rbr101** [Blackymas/NSPanel_HA_Blueprint#826]
Hi, 

I have 4 nspanels and 3 of them work fine, on one of the nspanels the hardware buttons don't work as it should:

Left button does trigger a configured light, but long press doesn't show the brightness settings
Right button does nothing.

I f i look at the esphome sensors (Left button/Right button), i do see a button press for both switches.
Already tried with a new blueprint config and restarting the device but without any luck.

Any idea how to fix this?

**Comment by edwardtfn** [comment]
Anything in your Home Assistant log?
Settings > System > Logs

**Comment by Blackymas** [comment]
what makes you think it's a code problem when running 3 NSPanels?

**Comment by rbr101** [comment]
Nothing in the log, the ESPHome config seems to work fine.
Looks like some configuration thing?

**Comment by edwardtfn** [comment]
What can you see in the panel's screen?
Which versions of TFT, ESPHome and Blueprint are shown on the boot screen?

**Comment by rbr101** [comment]
I just removed the device (devices -> esphome) and re-added it again.
Now it seems to works fine.
