### ISSUE TITLE
Trouble to install nspanel to esphome

### ISSUE THREAD

**Issue by jsaurila** [Blackymas/NSPanel_HA_Blueprint#828]
Hi,
I pretty new in using home assistant and now i trying to something new to uppgrade my system.
I trying to install nspanel with your code to esphome and i get error messages like in logs files.
Home assisatant version is 2023.5.3
Esp home version is 2023.5.1

Can you help , am i doing something wrong or what ? 

//Jouni from Finland

[logs_olohuone_compile.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/11523193/logs_olohuone_compile.txt)

**Comment by Blackymas** [comment]
pls try to use the issue search - we have often discussed this topic
