### ISSUE TITLE
Button icons always red

### ISSUE THREAD

**Issue by jfrancais** [Blackymas/NSPanel_HA_Blueprint#843]
Having this issue on both of my nspanels.  recently upgraded blueprint and us.tft to be at newest from main branh.  Since the upgrade all my button icons are red.  Colors are set for each in the automation but are ignored in favour of red.  Icons themselves are using what is set in the automation, but color is not.  Is this a known issue?  Any recommendations to assist?

**Comment by edwardtfn** [comment]
Could you please share your automation yaml?

**Comment by lloydbayley** [comment]
Just a note here, I had a problem the other day where a colour wouldn't set. It turned out to be a weird (possibly caching) browser problem. I can't remember whether I closed the browser and re-opened it, or shift-refresh'ed the page but one of those cured it. 
This may or may not be helpful in your case but I thought I'd point it out on the off-chance.

**Comment by edwardtfn** [comment]
@jfrancais , could you please share a picture of that screen with the red icons so we can try to understand what is happening?

**Comment by jfrancais** [comment]
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/18350834/e9f9de06-161e-4ddd-95a9-edfed859fc86)

**Comment by jfrancais** [comment]
I'll pull the yaml later tonight.

**Comment by jfrancais** [comment]
> I have seen one of the icon turned RED the other day. Turns out to be an entity that is not available anymore which I added some time back. That was on the EU panel.

Not the case here, all the entities worked.  I was able to turn them on/off with the buttons.

I ended up deleting my automation and recreating it and it worked, so something funky must have been lingering around it didn't like. All Good now.
