### ISSUE TITLE
Dev branch: Climate page

### ISSUE THREAD

**Issue by rleongcs** [Blackymas/NSPanel_HA_Blueprint#848]
Things I noticed...Item 1 and 2 is more of a UX issue. Item 3 is system.

1. Temperature does not seem to be centered. They are right aligned and looks a little weird.
2. The power icon should ideally be at either left end or right end so as not to accidentally pressed in it.
3. Seems to be missing one other dry icon which the HA climate card provides.

NSPanel
![IMG_1755](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/61628312/d726efcd-814f-4150-b968-507228a65c6b)

HA Climate card
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/61628312/44345453-1708-46a8-9a8f-a775476bb97d)

**Comment by edwardtfn** [comment]
Thanks for the feedback.

> 1. Temperature does not seem to be centered. They are right aligned and looks a little weird.

This will be a bit challenging as the "°" signal on the target temperature have a fix position. Current temperature will be much easier to centrilize. For target_temp I've just change that to a float field, so it will be challenging to centrilize without disconnected it from the units.
@Blackymas, could please take a look at this.

> 2. The power icon should ideally be at either left end or right end so as not to accidentally pressed in it.

Indeed. I will change that to have off but always on the most right position.

> 3. Seems to be missing one other dry icon which the HA climate card provides.

Could you please share here the content of the attribute `hvac_modes` on this climate entity?

**Comment by rleongcs** [comment]
> This will be a bit challenging as the "°" signal on the target temperature have a fix position. Current temperature will be much easier to centrilize. For target_temp I've just change that to a float field, so it will be challenging to centrilize without disconnected it from the units.

Maybe that's why the HA card does not have the "°" symbol on the target temperature 🤔 

> Could you please share here the content of the attribute hvac_modes on this climate entity?

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/61628312/7109eb58-85b8-40cd-99b7-462055361d92)

**Comment by edwardtfn** [comment]
@rleongcs,could you please try the buttons again?

**Comment by Blackymas** [comment]
@rleongcs 
just as a hint the design is not finished it is a DEV to test the functions etc

That's why it's called DEV :)
If we push it into beta then it will be the final version if nothing else is found in bugs :)

**Comment by rleongcs** [comment]
@Blackymas Yes, I know it is `Dev`. I was only giving my feedback as @edwardtfn has asked me to so hopefully the end product will be better. 😉

@edwardtfn The other button is now reflecting. I am not sure if there are other buttons on the left side as they would look a lot better if moved towards the left as shown in photo 2. The other issue I found was setting the target temperature (circled in red in photo 1) using the "+" or "-" button increases or decreases the temp by "0.1" instead of "0.5". In HA, the climate card only does "0.5" and my aircon also does not take anything lower than 0.5. Not sure if other climate device can go below 0.5. If they can, suggest if there is a way for user to define the minimal.

Photo 1:
![IMG_1769_1](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/61628312/a8b4fa29-6941-426c-be76-124f47ec4a3c)

Photo 2:
![IMG_1769_2](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/61628312/9a2a24ad-3178-476b-a9af-d1f7ce627100)

**Comment by edwardtfn** [comment]
> @edwardtfn The other button is now reflecting. I am not sure if there are other buttons on the left side as they would look a lot better if moved towards the left as shown in photo 2.

Right now the buttons have a fix position (like "auto" will always be in the first slot at the left side - button01, "off" will be in the most right - button07), but the idea is to build those from the center. Or at least try to do as much from the center as possible, as the buttons have fix positions and some cases could be challenging.



> The other issue I found was setting the target temperature (circled in red in photo 1) using the "+" or "-" button increases or decreases the temp by "0.1" instead of "0.5". In HA, the climate card only does "0.5" and my aircon also does not take anything lower than 0.5. Not sure if other climate device can go below 0.5. If they can, suggest if there is a way for user to define the minimal.

This is where I'm working right now. The Nextion doesn't support float natively, so I have to play with it. I've just change the steps from 1 to 0.1, but my goal is to have 0.5 in the end.

**Comment by rleongcs** [comment]
> Right now the buttons have a fix position (like "auto" will always be in the first slot at the left side - button01, "off" will be in the most right - button07), but the idea is to build those from the center. Or at least try to do as much from the center as possible, as the buttons have fix positions and some cases could be challenging. As the first one ("Auto") is not supported by your climate, it looks misaligned.

Now it makes sense. 😄 Having said that, if 7 is the max you can have, then it will still be slightly to the right instead of actually in the center. Depending on how you see it, it is indeed in the center if you look at the icons row by itself. If you compare to the slider and also temp display then it is not as those are slightly aligned to the left.

**Comment by Blackymas** [comment]
@rleongcs 
The positions are not yet 100% aligned. But as edward said the 7 buttons are under the slider with a fixed position. 

We can't change this because we have to define a fixed position in the HMI.

There is only the possibility to say what should be at which position like for example

4,5,3,6,2,7,1 (as currently used)

Or

1,2,3,4,5,6,7 - would be all right aligned or if something is missing then 1,2,3 and 7 

That alls centered in the middle is I still adjust

**Comment by rleongcs** [comment]
Yes...I understand the limitation that @edwardtfn described.

> That alls centered in the middle is I still adjust

Hopefully you are able to achieve this as it would look a lot nicer 😉

**Comment by edwardtfn** [comment]
I think if we go 4,5,3,6,2,7,1 it will be centralized sometimes, but not always, so users might complaing.
If we align 1,2,3,...,7 (with off always at position 7) it will be obviously not centralized, which might reduce user's complains... I always tell my wife if it's hard to centralize something, just put it obviously misaligned, so people don't feel something is wrong.   😆 
But I'm open to any case... I will play around later and share with you, so it would be easier to give a suggestion after seen the different options live.

We also have to think how this will be in the US version, where those buttons most likely will be in a vertical line.

**Comment by edwardtfn** [comment]
So, I've followed another suggestion from @deejaybeam where all the icons are always shown.
I would appreciate if you guys try the code currently on `dev` and give me feedback about the new climate page.
You have to update TFT, ESPHome and Blueprint.

**Comment by rleongcs** [comment]
I have tested it and it looks great. I like that it is showing all icons but grey off those that are not applicable to the climate device thus not messing with the positioning. I also noticed that you managed to get the 0.5 steps working! 🎉

Only thing (purely cosmetic) if you could adjust for the final release is either having the top green portion aligned to center of the screen like the bottom red row. Or the bottom red row to follow the alignment of the top green portion which is slightly off center due to the top right "X" button.
![IMG_1772](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/61628312/f1a0d59c-c6fb-4349-9652-a90e1754e2fc)

**Comment by edwardtfn** [comment]
Thanks for the feedback.
I'm fact, the step will follow the `target_temp_step` attribute from your climate entity, if available, otherwise it will be 0.5.

About the page layout, @Blackymas is working on this.

**Comment by Blackymas** [comment]
@rleongcs you can try the new Design

**Comment by rleongcs** [comment]
@Blackymas Tried it and the new design definitely looks a lot better. Great job!

Just trying to nitpick here...the 4 entity fields circled in red are slighly to the right. Not sure if it is something that can even be fixed as I believed they will move about depending on the decimals?

Old design:
![IMG_1773](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/61628312/77702773-522f-4feb-9511-8cc7401951aa)

New design:
![IMG_1774](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/61628312/5a6310cb-86d2-4b19-87ff-9dd7ff25ee6b)

**Comment by edwardtfn** [comment]
US version is now updated and also some improvement on the EU version.
You have to update the 3 parts (TFT, ESPHome and Blueprint), which is now v3.4 (but still `dev`, so, not final).

I'm working now on the two custom buttons on that page.

Please share your feedback.

**Comment by pbranly** [comment]
hi with us version:
esphome 3.4 ok
blueprint 3.4 ok
tft 3.4 ok
now I have to play with it !
Phil

Le lun. 5 juin 2023 à 12:03, Edward Firmo ***@***.***> a
écrit :

**Comment by rleongcs** [comment]
@edwardtfn I have updated to the lastest yesterday to test the EU version and I am seeing something weird. I guessed the custom buttons are not quite ready yet as I saw you have #862.

Issues:
1. Custom button 01 is appearing on the same position where Climate entity On/Off button is.
2. Custom button 02 when on does not show the icon. Not sure if #862 solves that?

![IMG_1780](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/61628312/e4d1984a-e4fb-4626-9281-38ac4d158f9d)

**Comment by edwardtfn** [comment]
Custom buttons have been fixed a couple of hours ago. Could you please download again?
I think I only the Blueprint have to be update this time.

**Comment by rleongcs** [comment]
Tested out the new blueprint and icons position is now alright.

Issue:
1. Not able to toggle the Custom button 02 without first toggling Custom button 01.

![IMG_1782](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/61628312/060d667a-ec92-4f83-8041-8a255ae53509)

**Comment by edwardtfn** [comment]
Mmmm
I will take a look at this tomorrow.

**Comment by Blackymas** [comment]
@rleongcs 

changed it again because I also had to make the fields bigger.

But it is generally difficult to find a perfect position because there are not 4 fields but 8 and it always depends on what the value in the field is.

I have also adjusted these design issues
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/692

**Comment by rleongcs** [comment]
@edwardtfn Tested and now the 2 issues are fixed! 🎉 

@Blackymas
> But it is generally difficult to find a perfect position because there are not 4 fields but 8 and it always depends on what the value in the field is.

Agree...There are more space now between the entities which is great except there is more space on the left (Photo1). I guessed it will not ever be really centered as it depends on the entities value length. For example, if you allocate equal space to each entity (Photo 2), they will look not aligned as well (Photo 3). 😆 With Photo 2 implementation, at least each entity will have equal space to expand into if the value is long (Just my suggestion).
> I have also adjusted these design issues
> #692

Yes, it is fixed and looks nicer now (Photo 4). 👍 

Photo 1:
![IMG_1786](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/61628312/1332ed53-2136-4b64-ac4b-23af62dd1bfc)

Photo 2:
![IMG_1786b-2](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/61628312/a5a2025c-4cfa-4aaa-9a8c-b2f1fa558a0d)

Photo 3:
![IMG_1786b-1](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/61628312/aa405daf-8d58-401f-a1ed-ae2a6c11383d)

Photo 4:
![IMG_1784](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/61628312/902b4be3-6d29-488c-906e-2afaf71ab788)

**Comment by Blackymas** [comment]
@rleongcs 
Photo 1 and Photo 3 describe exactly the problem.

In photo 1 it is too far to the left and in photo 3 it is too far to the right.

So if I change it the way you show it in photo 2, the next one with photo 3 comes and says it's not centered.

Making it centered would only work if I would make the value in the field right-aligned. But then there would be a big column between icon and value.

There are not only 4 fields but 8 fields -> 4 fields for icon and 4 fields for the value.

Example:
<img width="765" alt="Bildschirmfoto_2023-06-02_um_23 37 35" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/41958506/615dcdf4-6d3c-4bb3-bb08-33d361b9f42c">

**Comment by rleongcs** [comment]
@Blackymas I did not see any issues systematically so far. So you should be good to go in my opinion. 😄

**Comment by Blackymas** [comment]
@rleongcs thanks for sharing your feedback :)
