### ISSUE TITLE
Long loading times when changing displays

### ISSUE THREAD

**Issue by patzaa** [Blackymas/NSPanel_HA_Blueprint#852]
Hello people, 

I did setup the Ui. However, I have long delays (3s) when switching from the home screen to button page. There is even a tiny loading.. screen in between. Does anybody know how to mitigate that issue?

**Comment by wickedmkpl** [comment]
I have the same on my panel.

TFT 3.3
Blueprint  3.3

**Comment by patzaa** [comment]
same versions here

**Comment by edwardtfn** [comment]
What do you have as delay in your automation settings?
![IMG_6248](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/4caa0cdf-f537-4b35-a2e7-57e4a4603f5a)

**Comment by wickedmkpl** [comment]
same as picture, 1.

in my case, it's a fresh install.

![IMG_20230601_182538](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/121253092/e25ce18d-9364-4d02-86a9-8e848255fda9)

**Comment by edwardtfn** [comment]
Do you have any error message in the Home Assistant logs (Settings > System > Logs) related to this automation?

**Comment by edwardtfn** [comment]
On your blueprint settings, at the very end, you have an option to show the pages while loading. Please enable that and let me know the results.

![IMG_6251](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/63ce65b6-136f-4414-8335-87629539f526)

**Comment by Blackymas** [comment]
I have tested it again several times. Edward has shared some possibilities. Additionally, it may be a HA or network problem that is taking longer to load the pages.

Here we have no influence currently

**Comment by ForceFedDSM** [comment]
I am having the same issue.  I have tried all the suggestions above with no change.  Buttons are also delayed when touched.  This is a new install.

**Comment by Blackymas** [comment]
But this can't be a problem of the project - somehow you have a problem with HA or your network.

**Comment by edwardtfn** [comment]
> I am having the same issue.

What do you mean by "same issue"? It is slow on changing pages or to react to commands? How long? Are you seen the "Loading" message even when "Show pages while loading" is enabled? What do you have set ad "Delay to avoid sync problems"?

**Comment by ForceFedDSM** [comment]
I know my network is good.  What could be happening with HA?  I don't see any error logs, is it a performance issue?  I use a raspberry pi3b.  Cpu and ram are not maxed out with just a few simple automations that rarely get called.

**Comment by edwardtfn** [comment]
What about the [questions from my previous post](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/852#issuecomment-1582010109)?

**Comment by ForceFedDSM** [comment]
When I swipe from Home Screen it shows loading for ~3 seconds before page is displayed. This happens every time I swipe from one screen to another. Also, once on a screen, when I touch a light to turn it on, it takes anywhere from 4-6 seconds before I get a response. By response I am referring to seeing the light icon turn on on the NSPanel. This happens for light on and light off.  It also has a long delay to activate the long touch to change a lights color.

**Comment by edwardtfn** [comment]
Could you please run some tests to help understanding where the slowness is?

1. When you go to the device page (Settings > Devices and Services > ESPHome), you will see a sensor for each of the physical buttons. When you press the button physically, how long it takes for that press be detected on Home Assistant?
2. At that same page, you have two switches related to the physical relays. When you change that relay on Home Assistant, how long it takes for the relay to change in your panel (you probably can hear the sound of it changing physically if you are close to your panel or see a light turn off if a light is controlled by that).

**Comment by ForceFedDSM** [comment]
1. It’s almost instant for both buttons. Less than a second delay.  
2. relays also activate almost right away. Less than second delay.

**Comment by edwardtfn** [comment]
On your blueprint settings (the automation you created using the Blueprint), there is a field named something like "Delay to avoid synchronisation problem". What do you have set there? Could you please try to reduce to the minimum?

**Comment by ForceFedDSM** [comment]
1. It has been set to 1 since install
2. I have also enabled this previously
3. After swipe from home screen, I still get loading for ~3 seconds, then page starts drawing.  It draws quickly once it starts drawing, maybe 1-1.5 seconds. The delay seems to be before it starts to draw the page.  Of course I still have the delay for the touch buttons once page loads.

**Comment by edwardtfn** [comment]
On the same screen where you set the automation, please click in the 3-dot menu in the top right and select "Edit yaml", then copy the full content and share here, please? Make sure you hide any private info before sharing.
I will try to reproduce similar settings, but it looks like it is slow for loading the automation. We probably have some space for improvement in the code, but would be much better if we know what is causing most of the delays, so we can focus in the issue with better chances to get a significant improvement.

**Comment by ForceFedDSM** [comment]
Is this what you are looking for?  I can't get the formatting to stay.  Thanks for the help

`alias: ParkerNSPanel Configuration
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: ae44965a63aa6b35db158b01ad9cb361
    weather_entity: weather.kewb_daynight
    button_page01_label: Parkers Room
    entity01: light.parkerslight1
    entity01_name: Light 1
    entity04: light.parkerslight2
    entity04_name: Light 2
    entity05: light.parkerslight3
    entity05_name: Light 3
    entity08: light.parkerslight4
    entity08_name: Light 4
    entity02: light.parkers_room
    entity02_name: Parkers Room
    left_button_hold_select: Custom Action
    left_button_hold_custom_action:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.parkers_room
    show_while_loading: true
    delay: 1`

**Comment by ForceFedDSM** [comment]
This is cleaner but still won't keep the formatting.

alias: ParkerNSPanel Configuration
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: ae44965a63aa6b35db158b01ad9cb361
    weather_entity: weather.kewb_daynight
    button_page01_label: Parkers Room
    entity01: light.parkerslight1
    entity01_name: Light 1
    entity04: light.parkerslight2
    entity04_name: Light 2
    entity05: light.parkerslight3
    entity05_name: Light 3
    entity08: light.parkerslight4
    entity08_name: Light 4
    entity02: light.parkers_room
    entity02_name: Parkers Room
    left_button_hold_select: Custom Action
    left_button_hold_custom_action:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.parkers_room
    show_while_loading: true
    delay: 1

**Comment by edwardtfn** [comment]
It's fine, I can get the info I need.

**Comment by edwardtfn** [comment]
Which weather integration are you using?

**Comment by ForceFedDSM** [comment]
National Weather Service 
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16230698/f6a695ee-dee4-47ab-a3d1-6b2b64467e29)
