### ISSUE TITLE
unknown tag !<!lambda> (301:46)

### ISSUE THREAD

**Issue by vingores** [Blackymas/NSPanel_HA_Blueprint#863]
unknown tag !<!lambda> (301:46)

 298 |  ... r: string
 299 |  ... 
 300 |  ... .play:
 301 |  ... tl: !lambda 'return song_str;'
------------------------------------------^
 302 |  ... 
 303 |  ... o show a QR code on the display (ex. for WiFi password)

**Comment by vingores** [comment]
when compiling the firmware in esphhome, a bunch of errors pour in.
yaml complains about esphhome_nspanel.yaml file

**Comment by edwardtfn** [comment]
Could you please share your ESPHome settings yaml? Please make sure to hide any private info before sharing.

We don´t got this feedback from other people, so it is probably related to something in your setting or your ESPHome environment, so it would be nice if you can share more info... which version you are running, how if the host of your HA & ESPHome system, ,etc.

**Comment by Blackymas** [comment]
close no feedback
