### ISSUE TITLE
screen not loading

### ISSUE THREAD

**Issue by red-centre** [Blackymas/NSPanel_HA_Blueprint#867]
Hi, I'm having trouble following some updates,  The panel seems to boot fine, and all of the entities are visible, but the screen on the nspanel doesn't load, and the log has this error code in it:
11:23:13][W][nextion:396]: Nextion reported variable name invalid!

Could anyone point me in the right direction to troubleshoot?

Thanks

**Comment by edwardtfn** [comment]
1. Is this the first time you are installing the filas from this project on this panel or are you just upgrading from a previous installed version?
2. What do you see in your panel's screen?
3. When you click on the "Restart" button (Settings > Devices and Services > ESPHome > your panel), can you see the boot screen in your panel after a few seconds? If so, which version is it showing for TFT, ESPHome and Blueprint?

Some pictures of your panel might help us to understand where you are.

**Comment by red-centre** [comment]
Thanks very much @edwardtfn for the response!
I'm updating, but after a considerable while (about 5 months)
On the screen I see the "please wait" blue and white screen, and yes I can see that after I restart, and it is showing TFT 3.3, ESPHOME 3.3 Blueprint:  (nothing)

Attempting to attach an image - guessing this suggests a Blueprint issue?

![IMG_8321](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/91818884/61ef0b88-06b3-4a1b-ae71-f9cbb5909fda)

**Comment by red-centre** [comment]
Hey, just wanted to say a big "thanks" @edwardtfn .seems like an obvious thing, but just noticing there was no Blueprint version number led me to deleting the blueprint, and reinstalling the blueprint yaml, which, as it turns out, was all  I needed to do.
Really appreciate you taking the time out to help.

**Comment by edwardtfn** [comment]
As some of the fields changed format in the recent versions, I would suggest you double check your automation settings in Home Assistant (Settings > Automation and Scenes) and make sure your panel name is correctly shown (I think this is the very first field) as that is one of the fields changing format. I would expect exactly the behaviour you described if that field is not set properly.
Icons and colors selections also change and might require your action also, but I doubt that is sufficient to break it's basic functionalities.

**Comment by edwardtfn** [comment]
Also, take a look at Home Assistant logs (Settings > System > Logs) for anything related to this automation. Any message from the logs can help.

**Comment by edwardtfn** [comment]
Oh! Just realized you already solved the issue. Nice!
