### ISSUE TITLE
Feature request: Turn off individual pages.

### ISSUE THREAD

**Issue by MYeager1967** [Blackymas/NSPanel_HA_Blueprint#868]
There are currently four button pages. There's a selection dot in between each page in the configuration section, but it doesn't do anything. Is it on the roadmap to be able to only have 1 or two instead of all 4? Is there a way I can edit a file for each device if that's what it takes?

**Comment by Blackymas** [comment]
the button means nothing and has no function.

Unfortunately there is no kind of headline in the Blueprint. 

To make the blueprint clearer we had to choose this selection because there is no other solution.

**Comment by MYeager1967** [comment]
Would it be possible to select the number of pages? I saw somewhere that it said more was possible, how about less? Not massively important, but it would be nice.

**Comment by edwardtfn** [comment]
Hide pages without buttons assigned (or based on a control) is feasible. Probably the hardest are those page indicators in the bottom, as that is part of the page background and would have to be replaced for something more dynamic.

**Comment by MYeager1967** [comment]
I'm clueless on what is what with these things. Just got one a few days ago and put it into service this morning with the blueprint. I may look into actually coding for them at a later date, but this is an impressive project. Made putting it to use extremely easy.
