### ISSUE TITLE
new feature: confirmable button actions

### ISSUE THREAD

**Issue by deejaybeam** [Blackymas/NSPanel_HA_Blueprint#87]
Possibility to additional confirm an action of a button before execution. E.g. if you assign a button to open the garage-door and someone hits the button by mistake, for such an entity, it would be nice to have the possibility to approve the action.

**Comment by Blackymas** [comment]
added in https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v.3.0.0
