### ISSUE TITLE
Feature Request: RTSP Video

### ISSUE THREAD

**Issue by jmicks8** [Blackymas/NSPanel_HA_Blueprint#873]
Thanks for all the work on this! This is one of the best integrations in Home Assistant. 

It would be great if there was a way to see a RTSP video feed.

**Comment by rleongcs** [comment]
This has already been discussed in the following [post](https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/718#discussioncomment-5723476). Unfortunately, it is not possible with the NSPanel.

**Comment by edwardtfn** [comment]
The Nextion display used in this model of NSPanel does not support video, unfortunately.
