### ISSUE TITLE
[V3.4] Icons on Sensor Home Page not shown

### ISSUE THREAD

**Issue by bommel947** [Blackymas/NSPanel_HA_Blueprint#878]
Version: 3.4
Since I have updated to the most recent version the icons on the sensor home page disappeared

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/45903971/7e81b10f-c2e0-4996-aed1-fc326cf8de10)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/45903971/ff4c0ba0-b92c-4d47-a834-83992392865d)

Any** help is very much appreciated!

P.S.: 1000x thank you for your great project!!

**Comment by Blackymas** [comment]
Hallo,

hast du alle 3 Versionen wirklich auf Version 3.4? hab es gerade bei mir probiert und hier passt alles.

Hast du auch mal ein anderes Icon probiert

**Comment by edwardtfn** [comment]
What about other pages? Or is this issue on Home page only?

**Comment by bommel947** [comment]
Hallo,
Ich hab verschiedene andere Icons probiert.
Hab auch im Nextion Editor die Felder größer gemacht und einen kleineren
Font verwendet.
Nix davon hat die Icons zur Anzeige gebracht...


Am Mo., 19. Juni 2023 um 21:24 Uhr schrieb Blackymas <
***@***.***>:

**Comment by Blackymas** [comment]
hab es gerade an einem anderen Panel versucht ich kann das nicht reproduzieren

**Comment by bommel947** [comment]
Hallo,

Ich hab das Problem auf den Font zurückführen können.
Das hat mit v3.3 noch funktioniert.

Nichtsdestotrotz: vielen Dank für deinen Support!

LG
Manfred


[image: image.png]

Am Di., 20. Juni 2023 um 13:00 Uhr schrieb Blackymas <
***@***.***>:

**Comment by edwardtfn** [comment]
What was the problem?
If you can share you may help other users with the same problem in the future.

**Comment by bommel947** [comment]
Hi Edward,

The problem was that I have assigned the icons to a bigger font (Font 4 -
the same font as the neighboring value)
But that font obviously does not contain the icons.

Only font 7 seems to contain them...
[image: image.png]

Am Mi., 21. Juni 2023 um 09:20 Uhr schrieb Edward Firmo <
***@***.***>:
