### ISSUE TITLE
Button confirmation page not working correctly

### ISSUE THREAD

**Issue by denes44** [Blackymas/NSPanel_HA_Blueprint#883]
When I click on a button on which the execution confirmation is turned on, it displays the correct information on the notification page for maybe half a second, but then it gets overridden with "unknown", because the change to the notification trigger runs, and overrides the text with the notification text, which is unknown. Probably because the only condition for sending the notification text to the display is if the current page is the notification page:
https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/a47d8c3fbb9c8aeca1161cdecf47d8f917554f2f/nspanel_blueprint.yaml#L8113-L8126

I'm using version 3.4

**Comment by edwardtfn** [comment]
I couldn't duplicate this issue. I have the confirmation message shown with no issues.
Could you please provide more details? Is this happening with any type (lights, covers, etc.)? Etc.

**Comment by edwardtfn** [comment]
Thanks again for coming with a solution. I've applied your solution to `dev`.
I know you had a particular experience with creating your own PRs before, but I can assure this is a nice team to work with and would like to invite you to come back with your PRs when you have a solution or an idea. :)
By the way, I've start working on the thing about time on the ESPHome side, based on the solution you proposed earlier.
