### ISSUE TITLE
Best practice for updating ESPHome?

### ISSUE THREAD

**Issue by KoalaWerewolf** [Blackymas/NSPanel_HA_Blueprint#886]
What is the best practice for updating ESPHome for the NSPanel? Is it safe to install new ESPHome releases between NSPanel_HA_Blueprint releases or should the NSPanel be left alone until there is a new NSPanel_HA_Blueprint release?

**Comment by bkbartk** [comment]
It’s a matter of opinion really. 
frequently updating might wear out flash. 
also. An update might not affect any of the used components except version number. 
people might arguea don’t update if everything is working. Because the only thing ehich can change is you break something. 
on the other hand the ha team encourages you to update. 
I personally only update if I have an issue or a change. 
disable the update entities in ha to get rid of the notifications.

**Comment by edwardtfn** [comment]
I'm on the side of always keeping with the latest version, so I have a routine to update everything automatically when a new version is available and it runs every night.
Of course I have some risk of a new versions breaking something I'm using, but at least I know it would be easier to find support and 7 will minimize the know bugs.

However, automatic updates brings some issues, like in this project, where only the ESPHome part can be automatically updated and when that happens it will use the latest version of this project, requiring some manual work for updating the Blueprint and TFT, and sometimes (rarely) some changes on settings are required. And I just live with that.
Maybe it would be possible to automate those remaining parts, but as this is not a big issue now days, I keep as it is.

**Comment by bkbartk** [comment]
> I'm on the side of always keeping with the latest version, so I have a routine to update everything automatically when a new version is available and it runs every night.

So you updated everything last night, and today you will do this again?

for esp32 is might not be a big issue, but for esp86xx I have had a lot of issues with the updates. Including devices dying and need to serial flash again, so for that reason only I won't auto update.

(the issue I have is related to esp86xx not working well with openwrt ath10 drivers, this specific combination gives connection issues and can brick stuff)
I'm planning to replace my AP, but still should there be an issue it can brick your device.

anyway, it's a matter of preferences.
the point where small updates you know at least when it broke is also valid.

**Comment by edwardtfn** [comment]
> So you updated everything last night, and today you will do this again?

Yes! It was automated, so I haven't done anything, but the updated ran both days and everything went smoothly.

> (the issue I have is related to esp86xx not working well with openwrt ath10 drivers, this specific combination gives connection issues and can brick stuff)
> I'm planning to replace my AP, but still should there be an issue it can brick your device.

I only have a couple of devices running ESPHome over ESP86xx a d I never got any issue with auto-update.

> anyway, it's a matter of preferences.

I like the word "strategy" more than "preference" in this case, as it is a decision based on the Criticality of each device in your environment, your availability, etc...
My update automation won't run when my home is set to "Travelling mode", as an example.

> the point where small updates you know at least when it broke is also valid.

Exactly. The chances of breaking are higher, but it is easier to find support and fix when it happens.
You get better "protected" from know vulnerabilities, but more exposed to the unknown.
There's no right or wrong here.

**Comment by edwardtfn** [comment]
I'm an active contributor to this repository and I can tell you it is a quite active project. We don't push things to `main` all the time, but `dev` have updates almost every day and frequently many times a day.
We try to fix bugs as soon we know about those, however if it's not critical, it may take a few days or even weeks to go into `main` even when it is fixed in `dev` quite quickly.
I'm sure if some update brings a break to many users, we will use a fast track, but that never happened since I started participating in this project.

I have 3 panels myself. One on my office desk, running `dev` and other two on other rooms, running `main`. I use the same strategy where ESPHome is automatically updated on the 3 panels when a new version is available.

**Comment by rleongcs** [comment]
Same here for me. Always updating to the latest except I am still manually doing it. Prior to updating, I will create a snapshot of HA in my Proxmox first in case something goes wrong. So far nothing major has gone wrong.

**Comment by edwardtfn** [comment]
I have a daily backup with upload to the cloud running at 01:00, then the updates starting at 03:00.
A couple of times per year I restore my backup to a VM I'm order to make sure everything is working fine.

**Comment by MYeager1967** [comment]
What is the current version of the blueprint and is there any kind of timeline on when the next version might be released? I believe I'm on 3.3....

**Comment by edwardtfn** [comment]
> What is the current version of the blueprint

v3.4 -> https://github.com/Blackymas/NSPanel_HA_Blueprint/releases



> is there any kind of timeline on when the next version might be released?

Nope. This is something we work on during our free time, so depending on the load from work, family, friends, the weather, etc, it could take longer or shorter.
Are you expecting for some specific functionality from the next one?



> I believe I'm on 3.3....

You can double check your version by restarting your panel and looking the versions on the left bottom of the boot screen.

**Comment by MYeager1967** [comment]
I knew it was a project that got worked on when it got worked on. Just
looking forward to the changes I've been reading about. 😃

**Comment by MYeager1967** [comment]
Yep, 3.3 for TFT and blueprint, 3.4 for ESPHome.

**Comment by edwardtfn** [comment]
You should either upgrade TFT and ESPHome to v3.4 or downgrade the Blueprint to v3.3. Working with inconsistent versions will drive to unknown results.

**Comment by MYeager1967** [comment]
Might look into upgrading the TFT and blueprint to 3.4....

**Comment by MYeager1967** [comment]
Updating the blueprint was easy enough but had to roll back because I
couldn't get the tft file to update. Put the new version in the www folder
and used the update tft helper but no joy....

**Comment by edwardtfn** [comment]
Hi @MYeager1967, how was that in the end?
Should we close this or are you still facing this issue?

**Comment by MYeager1967** [comment]
I'll look at it again tonight and see if it works.
