### ISSUE TITLE
Updating v3.4 is not working

### ISSUE THREAD

**Issue by rploeg** [Blackymas/NSPanel_HA_Blueprint#892]
Hi,

I am trying to update to version 3.4. I have done

- Uploaded the new TFT file to my server  (and validate the download by myself) 
- updated yaml ESP
- updated automation (also I see v 3.4 back in the automation)

When I hit (I have a press button, not a slider) the TFT update button, the progress starts on my panel. The strange thing it start at 80% directly (so, not starting at 0). Then it says after 100% that it is successfully updated, but after the reboot I see still v3.2.2 on the screen - and off course nothing works anymore because the HA side is updated to 3.4.

One other weird thing is, when I set the baudrate to 9600, to do the TFT update, I still see on the top 115200 on the panel screen. So it looks like it doesn't pick the baudrate for the ESP config file. 

I am running ESPhome 6.2 (that was updated today before I did the upgrade of this great add on!), so maybe that is an issue? 
Running also the latest updates on HA

**Comment by edwardtfn** [comment]
> The strange thing it start at 80% directly (so, not starting at 0).

This is not a problem. Nextion manages this in a way that many times its not necessarily to transfer the file entirely.

> Then it says after 100% that it is successfully updated, but after the reboot I see still v3.2.2 on the screen.

Do you see 3.2.2 for TFT only? What about ESPHome and Blueprint? What is shown in the panel's screen?

**Comment by edwardtfn** [comment]
> * Uploaded the new TFT file to my server  (and validate the download by myself)

Are you sure the url into esphome settings is exactly the same you used to validate?

Based on what you just described, looks like your panel is getting the TFT v3.2

**Comment by rploeg** [comment]
Yes, one of three panels are updated with 3.4. So can confirm that I use the latest tft

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by edwardtfn** [comment]
But what about the panel where you see the issue? Are you sure it is flashed with the right url?

You can instead use Developer Tools > Services and then select the service esphome.xxxxx_upload_tft_url and then paste there the same url you know is valid, then press "Call service".

![IMG_6289](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/25b4210a-5cfc-4ad1-960c-10d0b3f3f8ce)

**Comment by edwardtfn** [comment]
But back to my first question, what do you see in your panel's screen from ESPHome version and for Blueprint version?

**Comment by rploeg** [comment]
3.2.2 for tft
Esp 3.4

And panel hangs. I cannot click on reboot button  - when I remove power from the panel it reboots and hangs again.

Panel was working great with 3.2.2

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by edwardtfn** [comment]
And what about calling the service esphome.xxxxx_upload_tft_ur?

**Comment by Aiberkh** [comment]
Hello I have a Problem with the update too. I have two displays one eu and one us. The eu worcks fine after the update, the us shows only the "loading" - view. But i can swipe to the entieties. Then it switches back to loading.

TFT is 3.3
ESP Hpme 3.4
Blueprint 3.4

If press the TFT update button ist starts at 90% and says everyting is ok

**Comment by Aiberkh** [comment]
Everything OK.... i loaded an old EU TFT Version to the US Display 🤦‍♂️

**Comment by T3mplate-wow** [comment]
The problem I had most of the time: 
It stuck loading the blueprint. The display has an IP, the correct TFT version and the correct ESP version, but don‘t get the blueprint.
The problem (or the solution) is that I don‘t reload the automations in Home Assistant (or restart HA). 
May this helps to other.

**Comment by edwardtfn** [comment]
It's quite hard to replicate that one, so it's hard to find a fix.
I'm trying a timer to shake the blueprint every minute. This was introduced with [#3a95d59](https://github.com/Blackymas/NSPanel_HA_Blueprint/commit/3a95d5916e9a3b68f52500432d06552bf6cdb784) and it is already in `dev`.

**Comment by T3mplate-wow** [comment]
> It's quite hard to replicate that one, so it's hard to find a fix.
> I'm trying a timer to shake the blueprint every minute. This was introduced with [#3a95d59](https://github.com/Blackymas/NSPanel_HA_Blueprint/commit/3a95d5916e9a3b68f52500432d06552bf6cdb784) and it is already in `dev`.

Is this comment regarding to me? 
this happens in my setup every time when I update, because:
* I have 3 NS Panel
* so I am not migrating all of them on the same time
* because of this I am not overwriting the existing blueprint.yaml (this would update all 3 of them). 
* I create a blueprint_3_4.yaml just for the device I want to update first
* the older automatisation will be disabled or deleted for this device 

 But in my opinion you don’t have to find a fix for this. I do it against the manual (because I don’t want to upgrade all of them). I just wanted to mention the problem to help people with the same issue.

**Comment by edwardtfn** [comment]
> Is this comment regarding to me?

It was. 😀
