### ISSUE TITLE
Things dosn't work after 3.4 update

### ISSUE THREAD

**Issue by adri123** [Blackymas/NSPanel_HA_Blueprint#893]
Hello and thanks for the amazing work out there,
I have upgraded to 3.4 but now, I notice few things that doen't work anymore :
- My panel does not go to sleep mode anymore (the screen stay "on" all the time)
- I cannot access to the config menu on the panel because the icon of the screen dosn't show anymore;
- The weather forecast show empty pages.
I precise that I update the blueprint and the tft.
What did I miss ?
Thank you for your answers!

**Comment by edwardtfn** [comment]
> * I cannot access to the config menu on the panel because the icon of the screen dosn't show anymore;

It's now shown with a long press on the time on the page home.



> * The weather forecast show empty pages.

Which weather integration are you using?

**Comment by adri123** [comment]
* About config menu and sleep mode: Thanks you for the trick, I can now configure the sleep mode. I guess I miss that part in the change log.
* For the weather page : I use the "Météo-France" set up in daily forecast. It was working before Maybe I miss a part here too.
Thank you

**Comment by edwardtfn** [comment]
I have installed the Météo-France and could duplicate the issue you described.

I see an error on HA logs. Could you please confirm you have something similar from your logs?
```txt
Logger: homeassistant.components.automation.office_workstation_panel_configuration
Source: helpers/script.py:410
Integration: Automation (documentation, issues)
First occurred: 17:08:54 (24 occurrences)
Last logged: 17:09:01

Office - Workstation - Panel - Configuration: Main choices: NSPanel Event: NSPanel Event component changed: Page changed: Choose at step 1: Weather pages: Error executing script. Error rendering template for variables at pos 6: TypeError: '>=' not supported between instances of 'datetime.datetime' and 'str'
Office - Workstation - Panel - Configuration: Main choices: NSPanel Event: NSPanel Event component changed: Page changed: Error executing script. Error rendering template for choose at pos 1: TypeError: '>=' not supported between instances of 'datetime.datetime' and 'str'
Office - Workstation - Panel - Configuration: Main choices: NSPanel Event: Error executing script. Error rendering template for choose at pos 1: TypeError: '>=' not supported between instances of 'datetime.datetime' and 'str'
Office - Workstation - Panel - Configuration: Error executing script. Error rendering template for choose at pos 1: TypeError: '>=' not supported between instances of 'datetime.datetime' and 'str'
```

**Comment by adri123** [comment]
I confirm that I found this error too :
`Logger: homeassistant.components.automation.nspanel_configuration
Source: helpers/script.py:410
Integration: Automatisation (documentation, issues)
First occurred: 25 juin 2023 à 18:55:32 (40 occurrences)
Last logged: 20:13:57

NSPanel Configuration: Main choices: NSPanel Event: NSPanel Event component changed: Page changed: Choose at step 1: Weather pages: Error executing script. Error rendering template for variables at pos 6: TypeError: '>=' not supported between instances of 'datetime.datetime' and 'str'
NSPanel Configuration: Main choices: NSPanel Event: NSPanel Event component changed: Page changed: Error executing script. Error rendering template for choose at pos 1: TypeError: '>=' not supported between instances of 'datetime.datetime' and 'str'
NSPanel Configuration: Main choices: NSPanel Event: Error executing script. Error rendering template for choose at pos 1: TypeError: '>=' not supported between instances of 'datetime.datetime' and 'str'
NSPanel Configuration: Error executing script. Error rendering template for choose at pos 1: TypeError: '>=' not supported between instances of 'datetime.datetime' and 'str'`
Does it come from Nspanel or the Météofrance integration ?

**Comment by edwardtfn** [comment]
Météo-France integration provides the date and time as a datetime field, which makes sense, but is different than any other weather integration we tested for (a lot) which always send this info as a text.
I know where in the Blueprint the comparison is failing and tomorrow I can take a look for a solution which most likely will be included in the next release.

**Comment by edwardtfn** [comment]
I've fixed this in `dev` and it will be available in the next release.

**Comment by adri123** [comment]
Thats great ! Thank you.
And if the media player comes also in this release it will be my favorite =D
