### ISSUE TITLE
Sensors on (button) pages

### ISSUE THREAD

**Issue by RienduPre** [Blackymas/NSPanel_HA_Blueprint#901]
Hi,

I have a feature request.

I like to see sensors on the (button) pages.
For example:
I want to use the NSpanel for my pool control.
Besides the fact to control the pump, heater, lights etc, I aslo want to see mij water temperature, ph, orp, water level, electricity usage etc.

Is this possible ?

Thanks,
Rien

**Comment by edwardtfn** [comment]
This is not possible, it is too hard to implement or is not aligned to the future plans for this project.
If this changes in the future we will be happy to reopen it.
