### ISSUE TITLE
Support for non NSPanels

### ISSUE THREAD

**Issue by DerPicknicker** [Blackymas/NSPanel_HA_Blueprint#902]
Hi,

first of all great software and the good documentation. It would be great if this piece of software would get support for different displays which aren't NSPanels. Here is a Link to a display which looks much cleaner than the NS one : https://www.aliexpress.com/item/1005005188547984.html

As I can see this is currently not supported by ESPHOME but in the ArduinoGFX the DisplayIC (GC9503V) .. 

What do you think about the display and the idea? Hope to hear from you and your opinions.

Best regards

**Comment by edwardtfn** [comment]
I use to say that in software development nothing is impossible, and what you are asking for is basically a software development. 😜
This is not a small effort, as everything would have to be rebuild from scratch. Even if we manage to install ESPHome on that device, the code will need a total rebuild as the communication to the screen is a totally new protocol.

It looks nice, I want to have one when it is a final product (the link you provided is for a development version without 220VAC power supply or physical relays, as I understood).
Also, the documentation is a bit poor (https://github.com/icbbuy/ESP32-S3-4-inch-IPS-LCD-development-board/blob/main/Document/QSZX3D954848-doc.pdf) and will require lots of investigation, which 8 personally cannot do right now.

**Comment by DerPicknicker** [comment]
Hello @edwardtfn ... 

yeah I got your point. It seems it uses a complete different structure. NsPanel UI is stored on the display and not on the esp32 .. And here the gui is stored on the esp32 (16MB flash) . I read that it support LVGL, which is nice. I will check how LVGL is compatible with esphome. It seems that lvgl is quite popular with some nice GUI builder.
