### ISSUE TITLE
nspanel NSPanel event & nspanel Settings Entity showing wrong value

### ISSUE THREAD

**Issue by stingone** [Blackymas/NSPanel_HA_Blueprint#903]
After update to 3.4 

The nspanel NSPanel event & nspanel Settings Entity showing value below:

{"page": "home", "component": "currentpage", "value": "pagechange"}

**Comment by edwardtfn** [comment]
This is what is expected for those entities and is not a problem.
They are now json-like strings so we can transfer more info between the panel and the Blueprint and between concurrent instances of the Blueprint with a reduced number of sensors.
And most likely the "Settings entity" will disappear in the coming release.
