### ISSUE TITLE
ns panel error climate

### ISSUE THREAD

**Issue by vingores** [Blackymas/NSPanel_HA_Blueprint#904]
NSPanel Configuration uses unknown service
The "NSPanel Configuration" automation ( automation.nspanel_configuration) uses an action that invokes an unknown service: esphome.nspanel_send_thermostat_cycle_state.

This can prevent the automation from performing correctly. This service may no longer be available, or it may be due to a typo.

To fix this error, [edit the automation](http://192.168.2.11:8123/config/automation/edit/1686062832649) or remove the action that calls this service.

**Comment by edwardtfn** [comment]
Have you recently updated or renamed your panel?
Try to restart Home Assistant.

**Comment by vingores** [comment]
Yes I updated esphome and nspanel and also updated home assistant.

**Comment by vingores** [comment]
![IMG_20230701_163355](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/69748637/ef0401ef-a6bd-4760-b275-5b03c93e93b2)
yes tft version is different from blueprint version!

**Comment by edwardtfn** [comment]
This error is usually related to a mismatch between ESPHome and Blueprint, so you probably still have to update the Blueprint also.
Anyway, start with the TFT...

You will find the instruction here: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#2-update-blueprint

**Comment by vingores** [comment]
![IMG_20230701_170503](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/69748637/edd8f9e2-9e0c-4286-8f7f-9a4d0b155214)
I tried to update TFT and everything broke, the screen turned on its side and there is no download.

**Comment by edwardtfn** [comment]
Just cancel and try again. ;)
It shouldn't take more than 20 to 30min.

**Comment by vingores** [comment]
![IMG_20230701_174917](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/69748637/08e0d7de-1fc4-48d4-9e21-2266423a1201)
I flashed the panel with a key fob, everything worked, I updated the blueprint
but the panel doesn't show the blueprint version so FYI

**Comment by vingores** [comment]
Thanks everyone for the help!

**Comment by edwardtfn** [comment]
Open the Blueprint settings and make sure the NSPanel is selected properly.
Take a look at other fields also.
Restarting Home Assistant could help with this.
And maybe some logs from Home Assistant (Settings > System > Logs) will help to identify where the problem is.
