### ISSUE TITLE
Feature request (for hidden wifi ssids)

### ISSUE THREAD

**Issue by bartbakels** [Blackymas/NSPanel_HA_Blueprint#906]
Please create a flag in the config to enable the usage of hidden ssids. This is now not possible without changing the esp config hosted in this git.

thanks

bart bakels

**Comment by edwardtfn** [comment]
You can use the "Advanced mode". Just copy the content of the file `nspanel_esphome.yaml` into your device's ESPHome yaml and you edit what you want. 😉

**Comment by bartbakels** [comment]
I know and that is what i did, but if something changes. I need to update the code and set a notification on new commits ;)

**Comment by edwardtfn** [comment]
I'm closing this as there are instruction to solve this with customizations on v4.0: #1057
