### ISSUE TITLE
Confirm Execution Buttons are too small

### ISSUE THREAD

**Issue by T3mplate-wow** [Blackymas/NSPanel_HA_Blueprint#907]
I use the confirm function for several entities. 
For most buttons I need just one press to get it done.
But the confirmation buttons (green and red) are too small and not that responsive as all the other. 
I believe there is enough space on that site. May they can sized bigger or the area for the click can be bigger.

**Comment by edwardtfn** [comment]
I've made the clickable are a bit bigger.
This was already merged to `dev` and will be included in the next release.

**Comment by T3mplate-wow** [comment]
Thank you
