### ISSUE TITLE
clarification of the code - failed confg

### ISSUE THREAD

**Issue by stingone** [Blackymas/NSPanel_HA_Blueprint#91]
just a check about your code, do the double quotes have to stay? i use !secret

```

  device_name: "YOUR NSPANEL_NAME" 
  wifi_ssid: "YOUR WIFI SSID"
  wifi_password: "YOUR WIFI PASSWORD"
```

changing it to the code below gives me the error please use min of 8 characters

```
` device_name: "nspanel" 
  wifi_ssid: "!secret"
  wifi_password: "!secret"
```

```
`Failed config

wifi: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:36]
  ssid: !secret
  
  WPA password must be at least 8 characters long.
  password: !secret
  power_save_mode: none
  ap: 
    ssid: nspanel
    
    WPA password must be at least 8 characters long.
    password: !secret`
```

**Comment by deejaybeam** [comment]
Hi
This follows the default behaviour of (ESPHome) yaml - syntax.
If you use secrets you have to do remove the quotes, if not it´s recommendet to use quotes to surround strings, depends on the used characters inside the string.
See https://esphome.io/guides/configuration-types.html#local-packages for some exambles

**Comment by deejaybeam** [comment]
What you are doing (trying?) here is to set the WIFI-Password to the password "!secret" which is not allowed by esphome, because it is too short - this is no limitation of the project

**Comment by deejaybeam** [comment]
If you want to use the esphome secrets-file, than you have to create named entries into secrets.yaml and refer to them like this:
```
substitutions: 
  device_name: "nspanel01"
  wifi_ssid: !secret nspanel_wifi_ssid
  wifi_password: !secret nspanel_wifi_password
```
Or, without secrets.yaml, write your SSID and PASSWORD between the quotes direct into the nspanel_esphome.yaml

**Comment by stingone** [comment]
> wifi_password

never mind i had a huge brain fart ;)... to less sleep. thanks for your clarrification. works now.
