### ISSUE TITLE
Feature request: add option for Hardware buttons to always control relays

### ISSUE THREAD

**Issue by roblamoreaux** [Blackymas/NSPanel_HA_Blueprint#910]
With the current relay local fallback setting pushing a button has an almost instantaneous response when not connected to HA. 
When it has to go through HA to change there is a noticeable delay. It would be nicer if there was an option for it to always be local so the user doesn't notice delays and complain that it is slow.

**Comment by edwardtfn** [comment]
This was solved in `dev` and may be part of the next release.
