### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by lennartschulte** [Blackymas/NSPanel_HA_Blueprint#912]
For some time now my Buttons stopped working. They are displayed but i can't touch them or at least nothing happens. The screen itself works as intended. I can slide the pages and wake it up via touch, open settings and change brightness. So it's not a hardware defect of the panel but has something to do with the software i think.

ESP Home Firmware is 2023.6.3

**Comment by rleongcs** [comment]
What is the version for Blueprint, ESPHome and TFT shown on your panel?

**Comment by edwardtfn** [comment]
In addition to @rleongcs question, I have a few more:
When you say buttons not working, you mean the physical buttons or the button pages? Or both?
Any error message on your Home Assistant logs (Settings > System > Logs)?
Have you recently changed something in your panel? An update, or renaming some entity?

**Comment by Blackymas** [comment]
i also run ESP Home 2023.6.3 and for me all works fine

**Comment by edwardtfn** [comment]
@lennartschulte, any update on this? Are you still facing this issue or should we close this thread?

**Comment by lennartschulte** [comment]
@edwardtfn it's just the buttons on the touchscreen. everything else on the touchscreen works as intended (e.g. settings screen with brightness etc.). 
i can't tell you what i changed to be honest as i don't use the buttons that often and they could be broken for over a month now. it's just a panel in my workshop i don't really use that much in terms of touch buttons.

ESPHome Version now is: 2023.6.4
[01:13:38][C][nextion:118]:   Device Model:     NX4832F035_011C
[01:13:38][C][nextion:119]:   Firmware Version: 69
[01:13:38][C][nextion:120]:   Serial Number:    ***************
[01:13:38][C][nextion:121]:   Flash Size:       16777216
[01:13:38][C][nextion:122]:   Wake On Touch:    True

tft version should be the current one as i have:
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft" #
in my config

**Comment by lennartschulte** [comment]
System Log:
Logger: homeassistant.components.automation.nspanelwerkstatt_konfiguration
Source: components/esphome/__init__.py:622
Integration: Automatisierung (documentation, issues)
First occurred: 6. Juli 2023 um 05:02:43 (9 occurrences)
Last logged: 6. Juli 2023 um 05:02:43

NSPanelWerkstatt Konfiguration: Choose at step 2: choice 27: Error executing script. Unexpected error for call_service at pos 2: Connection not done for nspanelworkshop @ 192.168.178.123; current state is ConnectionState.SOCKET_OPENED!
NSPanelWerkstatt Konfiguration: Choose at step 2: choice 14: Error executing script. Unexpected error for call_service at pos 2: Connection not done for nspanelworkshop @ 192.168.178.123; current state is ConnectionState.SOCKET_OPENED!
NSPanelWerkstatt Konfiguration: Choose at step 2: choice 28: Error executing script. Unexpected error for call_service at pos 2: Connection not done for nspanelworkshop @ 192.168.178.123; current state is ConnectionState.SOCKET_OPENED!
NSPanelWerkstatt Konfiguration: Error executing script. Unexpected error for choose at pos 2: Connection not done for nspanelworkshop @ 192.168.178.123; current state is ConnectionState.SOCKET_OPENED!
While executing automation automation.nspanelwerkstatt_konfiguration
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1957, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1997, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 622, in execute_service
    await entry_data.client.execute_service(service, call.data)
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 1260, in execute_service
    self._check_authenticated()
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 328, in _check_authenticated
    self._check_connected()
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 322, in _check_connected
    raise APIConnectionError(
aioesphomeapi.core.APIConnectionError: Connection not done for nspanelworkshop @ 192.168.178.123; current state is ConnectionState.SOCKET_OPENED!


and this one:


Logger: homeassistant.components.automation.nspanelwerkstatt_konfiguration
Source: components/esphome/__init__.py:622
Integration: Automatisierung (documentation, issues)
First occurred: 6. Juli 2023 um 05:02:39 (12 occurrences)
Last logged: 6. Juli 2023 um 05:02:42

NSPanelWerkstatt Konfiguration: Choose at step 2: choice 27: Error executing script. Unexpected error for call_service at pos 2: Not connected to nspanelworkshop @ 192.168.178.123!
NSPanelWerkstatt Konfiguration: Choose at step 2: choice 14: Error executing script. Unexpected error for call_service at pos 2: Not connected to nspanelworkshop @ 192.168.178.123!
NSPanelWerkstatt Konfiguration: Choose at step 2: choice 28: Error executing script. Unexpected error for call_service at pos 2: Not connected to nspanelworkshop @ 192.168.178.123!
NSPanelWerkstatt Konfiguration: Error executing script. Unexpected error for choose at pos 2: Not connected to nspanelworkshop @ 192.168.178.123!
While executing automation automation.nspanelwerkstatt_konfiguration
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1957, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1997, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 622, in execute_service
    await entry_data.client.execute_service(service, call.data)
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 1260, in execute_service
    self._check_authenticated()
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 328, in _check_authenticated
    self._check_connected()
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 320, in _check_connected
    raise APIConnectionError(f"Not connected to {self._log_name}!")
aioesphomeapi.core.APIConnectionError: Not connected to nspanelworkshop @ 192.168.178.123!

**Comment by edwardtfn** [comment]
This last log shows your panel disconnecting from Home Assistant, which could be related to a poor wifi signal.

**Comment by edwardtfn** [comment]
About the versions, could you please do the following?
1. On your panel, home screen, long press (hold for 1s) over the time info. This will open the settings page.
2. On the settings page, press the restart icon.
3. When restarting, your panel will show a blue screen, with Home Assistant picture. On the screen, in the bottom left corner, there is info about versions.
4. Please let me know what is shown in that screen for TFT, ESPHome and Blueprint. Or send a picture of that screen.

**Comment by edwardtfn** [comment]
By the way, which buttons are you talking about?

**Comment by edwardtfn** [comment]
The video and picture helped a lot.

The picture shows you are using a quite early version of the TFT. Since a few releases ago that blue screen should be showing the versions I was looking for.
I guess you have ESPHome firmware in a more recent version compared to the other parts, so my recommendation is to update everything.


> tft version should be the current one as i have:
> nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft" #
> in my config

As you are pointing directly to the GitHub repository in your config (which is not the most reliable way, by the way), you just need to press the button "Upload TFT" in your device page under Settings > Devices and Services > ESPHome.
It probably will take like half an hour with your panel unavailable, just showing the download progress bar, but then it will restart with the new boot screen where you will be able to see the versions.
The Blueprint is probably in an older version also. Here you will find some instructions to update that: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#2-update-blueprint

And here you will find the release notes. We are currently on v3.4 and the new boot screen was released on v3.1: https://github.com/Blackymas/NSPanel_HA_Blueprint/releases

You can update directly to the latest version.
After updating, please open your automations using this Blueprint and make sure all required fields have been filled out.

**Comment by lennartschulte** [comment]
I'll check the links and instructions but for now this is my ESPhome config for the panel:

esphome:
  compile_process_limit: 1
api:
  encryption:
    key: "*************************"
substitutions:

###### CHANGE ME START ######

  device_name: "nspanelworkshop" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

#  nextion_update_url: "http://http://homeassistant:8123/local/nspanel.tft" # URL to local tft File
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

**Comment by edwardtfn** [comment]
Your settings are pointing to an old url in GitHub. That URL won't work anymore, as we now have different versions of that TFT.

If you still want to use GitHub, you should replace that URL by this one: https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/nspanel_eu.tft

However, it's recommended to copy the file to a local http server as you reduces a lot the chances for errors on this transferring process. You will find details on the links I've shared earlier.

**Comment by lennartschulte** [comment]
i'll check them but if i'm correct my esp home config should be [this ](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/nspanel_esphome.yaml) one and i need to adjust it to my system accordingly and looks extremly different than my curren one ;-)
it will take me some time to work through it. for now i just replaced the github url and see what happens

**Comment by edwardtfn** [comment]
Your ESPHome settings should look like this one: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-First-Steps---Installation-and-Setup#code

That will instruct your ESPHome compiler to use your custom settings but with the latest `nspanel_esphome.yaml` from GitHub.

**Comment by lennartschulte** [comment]
i have no luck when compiling the code with my RaspberryPi 4 HA Installation. any idea on the issue?

Compiling /data/nspanelworkshop/.pioenvs/nspanelworkshop/src/main.cpp.o
Linking /data/nspanelworkshop/.pioenvs/nspanelworkshop/firmware.elf
RAM:   [=         ]  13.5% (used 44124 bytes from 327680 bytes)
Flash: [=======   ]  67.3% (used 1234565 bytes from 1835008 bytes)
Building /data/nspanelworkshop/.pioenvs/nspanelworkshop/firmware.bin
Creating esp32 image...
Successfully created esp32 image.
esp32_create_combined_bin(["/data/nspanelworkshop/.pioenvs/nspanelworkshop/firmware.bin"], ["/data/nspanelworkshop/.pioenvs/nspanelworkshop/firmware.elf"])
usage: esptool merge_bin [-h] --output OUTPUT [--format {r,a,w}]
                         [--flash_freq {keep,80m,60m,48m,40m,30m,26m,24m,20m,16m,15m,12m}]
                         [--flash_mode {keep,qio,qout,dio,dout}]
                         [--flash_size {keep,256KB,512KB,1MB,2MB,2MB-c1,4MB,4MB-c1,8MB,16MB,32MB,64MB,128MB}]
                         [--spi-connection SPI_CONNECTION]
                         [--target-offset TARGET_OFFSET]
                         [--fill-flash-size {256KB,512KB,1MB,2MB,4MB,8MB,16MB,32MB,64MB,128MB}]
                         <address> <filename> [<address> <filename> ...]
esptool merge_bin: error: argument <address> <filename>: [Errno 2] No such file or directory: '/data/cache/platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin'
*** [/data/nspanelworkshop/.pioenvs/nspanelworkshop/firmware.bin] Explicit exit, status 2
========================= [FAILED] Took 127.64 seconds =========================

**Comment by edwardtfn** [comment]
I would try to clean the build files and then try to compile again.

![IMG_6304](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/1bae324a-1d87-448c-8fd3-b49a71dcc100)

**Comment by lennartschulte** [comment]
Sadly did not help, same error just takes longer ;-)
ChatGPT told me to add this:
  platformio_options:
    board_build.partitions: default
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/89683004/c4999092-6c68-4828-8770-785e34952b73)
it got rid of the error but produced a new one
*** [/data/nspanelworkshop/.pioenvs/nspanelworkshop/partitions.bin] Source `default' not found, needed by target `/data/nspanelworkshop/.pioenvs/nspanelworkshop/partitions.bin'.

I know I had struggles when setting up the initial installation of the panel, but can't remember how I got around the compiling struggles.

**Comment by edwardtfn** [comment]
Could you please share your ESPHome setting again, but now selecting the code area and set it as code by using this button in the top?

![Uploading IMG_6305.jpeg…]()

**Comment by edwardtfn** [comment]
By the way, this solution from ChatGPT won't work for your panel as it is ESP32.

**Comment by lennartschulte** [comment]
`esphome:
  compile_process_limit: 1
api:
  encryption:
    key: "***********CENSORED****************"
substitutions:

###### CHANGE ME START ######

  device_name: "nspanelworkshop" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://http://homeassistant:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####`

**Comment by lennartschulte** [comment]
it seems not to work. perhaps there are the same characters in the config

`esphome:
  compile_process_limit: 1
api:
  encryption:
    key: "***********CENSORED****************"
substitutions:

###### CHANGE ME START ######

  device_name: "nspanelworkshop" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://http://homeassistant:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####`

**Comment by edwardtfn** [comment]
Any reason for you to be using this?

```yaml 
esphome:
  compile_process_limit: 1
```
You are running in a RPi 4, right? That should work without this.

**Comment by lennartschulte** [comment]
I know but perhaps that was due to my problems with the initial compiling of the firmware. Even without this declaration i get the same error.
[logs_nspanelworkshop_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/11998975/logs_nspanelworkshop_run.txt)

**Comment by lennartschulte** [comment]
What's strange: now there was an update for ESPHome and I was successfully able to perform the upgrade to 2023.6.5 but the normal "install" of the firmware throws the reported error.

**Comment by edwardtfn** [comment]
Well, at least you are one step ahead now.
I would suggest you update the TFT and Blueprint to make sure everything is at the same version.

**Comment by edwardtfn** [comment]
If you have the url like this in your settings the TFT update will fail:

```yaml
  nextion_update_url: "http://http://homeassistant:8123/local/nspanel_eu.tft"
```

You can still call the update by calling the service `esphome.xxxxx_upload_tft_url` and using the right url (probably http://homeassistant.local:8123/local/nspanel_eu.tft).

**Comment by lennartschulte** [comment]
let's close this issue as the initial reported bug is obviously a side-effect of my old version and the fact that it can't be updated seems not to be solveable for me. perhaps i need to try a diffenrent approach or change the panel
