### ISSUE TITLE
Feature Request: entity/button page instead of buttons/entities group page

### ISSUE THREAD

**Issue by krz2348** [Blackymas/NSPanel_HA_Blueprint#915]
Hi
great job with this blueprint project - THANKS GUYS!!!

I want ask for possibility to have a page only with entity/button options like Lightsettings page or Thermostat page or Coversettings page .. I know I can go in to this pages after long press the button, but I use NSPanels as climate control  and/or  lightscenes panels at every room and I use max 2-3 buttons on each panel , so it could be perfect option for me to have those pages after swipe homescreen  
e.g.
swipe up - thermostat
swipe down - lightsetting
swipe right - coversetting

thanks
Bartek

**Comment by edwardtfn** [comment]
You can have a button page with only those 3 buttons, then you will be a (long) click only to your detailed pages.
Hopefully in the coming release you will be able to select a button page as your wake-up page (#898) and you probably can play with timeout and sleep time to never see other pages. 😉

**Comment by krz2348** [comment]
Yes, I understand I can enter with a long press and that's what I have and use now, but my "dream" is to have detail pages instead of button pages - that would be awesome :)

**Comment by Blackymas** [comment]
Unfortunately, this is not possible, you would have to lend a hand to the HMI yourself.
