### ISSUE TITLE
Blueprint device selection is broken

### ISSUE THREAD

**Issue by thenoid** [Blackymas/NSPanel_HA_Blueprint#923]
Is anyone else having trouble with the device selection in the blueprint?  Every time i select something it clears the drop-down and then won't let me select anything. It also appears to save completely blank. 

Deleted the blueprint, re-imported, and validated i can select devices in other blueprints.

Home Assistant 2023.7.1
Frontend 20230705.1 - latest

https://youtu.be/IFtFY5gFSxs

**Comment by rleongcs** [comment]
I am not sure if clearing browser cache can help?

**Comment by edwardtfn** [comment]
Is this a recently created automation or are you migrating from a previous version? And in this case, which version? Have you tried restarting Home Assistant or reloading automations?

 If you are updating from a previous version, try this:
1. Go to `automations.yaml`
2. Find the automation connected to this Blueprint in this specific device
3. Find the line with `nspanel_name: xxxxxx`
4. Remove that line
5. Save your change
6. Reload automations (Developer Tools > yaml > Automations)
7. Then try to select the device again

**Comment by thenoid** [comment]
Cleared cache, different browser, even different computer even didn't make a difference.

brand new automation too.

I did find if i did the above behavior, let it freak out, and then click the device selector and use the keyboard to scroll to the entity i wanted and hit enter it would select it and be saveable.

dunno maybe it hates chrome/brave on linux secretly.

**Comment by edwardtfn** [comment]
Try this:

1. Go to Developer Tools > Template and then paste this (please replace `xxxxx` by your device's name):
```yaml
{{ device_id('sensor.xxxxx_nspanel_event') }}
```

2. Copy the string from the results box:
![IMG_6317](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/6843bb82-747a-4e6c-add0-18fc7b8ed300)

3. Find your automation related to this panel/blueprint in your `automations.yaml`
4. Add a line like this on the parameters of that automation (if you already have a line with `nspanel_name` you should just edit that one):
```yaml 
    nspanel_name: << the string you copied on step 2 >>
```
![IMG_6318](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/894ca04d-ff6d-4cc5-95c2-7bba706c72e6)

5. Reload your automations (or restart Home assistant)

Your automation should be working now. You have done the panel selection directly on the yaml.

**Comment by thenoid** [comment]
Sorry about that - i just did this:

>I did find if i did the above behavior, let it freak out, and then click the device selector and use the keyboard to scroll to the entity i wanted and hit enter it would select it and be saveable.

It was only 3 panels, so not a huge inconvenience once I figured it out.

**Comment by edwardtfn** [comment]
But is your panel working fine now?

**Comment by edwardtfn** [comment]
I'm closing this as we don't have any update since a while.
