### ISSUE TITLE
Home Assistent DB V2 growing 300mb/24h

### ISSUE THREAD

**Issue by tech2mar** [Blackymas/NSPanel_HA_Blueprint#924]
Hey friends,

Found that my DB is growing like crazy because of this automation, the entry's of the nspanel in my db is just crazy high.

Is that just me?

Thanks for the good work

**Comment by edwardtfn** [comment]
Which version are you using?
Do you have any value which very frequent update showing on Home page?

**Comment by edwardtfn** [comment]
This is probably related to #269

**Comment by tech2mar** [comment]
That sounds like the problem that I have, the problem is that I have Hass on Proxmox my problem is not the space.. And hardware, I only noticed that the backups that I have are growing to fast and my test restores are not even possible.

**Comment by tech2mar** [comment]
How can I remove that all from my db?

**Comment by edwardtfn** [comment]
I think the immediate thing you should do is trying to stop the problem by stopping new entries in your Logbook by adding something like this in your `configuration.yaml`:

```yaml
logbook:
  exclude:
    entities:
      - automation.xxxxx
```

* replace xxxxx by the entity_id of your automation controlling your panel and please restart Home Assistant.

**Comment by edwardtfn** [comment]
I will need some info from you, like the ones [here](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/924#issuecomment-1627010924) so I can understand the root and then propose something.

**Comment by tech2mar** [comment]
I will send you all information I have today so that a fix or maybe a fix on my side can be done. Thanks again for the fast answer

**Comment by edwardtfn** [comment]
Commit https://github.com/Blackymas/NSPanel_HA_Blueprint/pull/1012/commits/45eef605ae6b1e606bfa2fb0043d72afcc39a059 changes how the values on page Home are updated and will reduce significantly the number of executions of the automation when a frequently update sensor is used.
This is already in `dev` and will be included in the coming release.
