### ISSUE TITLE
Weather showing night time icon during daytime

### ISSUE THREAD

**Issue by hapklaar** [Blackymas/NSPanel_HA_Blueprint#931]
Very often the panel is showing nighttime weather icons during the day. 
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7703320/240fedfa-3d44-45cf-a135-f5ba0338c6a6)

I tried multiple weather providers in the configuration, but this makes no difference other than that it changes to a different nighttime icon.

**Comment by edwardtfn** [comment]
When that happens, could you please go to Developer Tools > Template and paste this?

`{{ is_state("sun.sun", "above_horizon") }}`

And let me know the result?

**Comment by edwardtfn** [comment]
By the way, which weather integration are you using by default? As you mentioned about your experience, I wouldn't expect this changing based on the weather integration, but I'd like to test for anything different that could be coming from your weather sensor.

**Comment by hapklaar** [comment]
@edwardtfn it's actually false
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7703320/d73bf6f6-fb16-4e93-9fa9-f9dfb3938f38)

**Comment by hapklaar** [comment]
I think I found it, you guided me in the right direction!

I previously disabled the `default:` entry in configuration.yaml. This also disabled the `sun:` integration. So after adding that back I now see above_horizon true and the icon changed to a bright sun on my panel :)

**Comment by edwardtfn** [comment]
Good to hear that it is working fine now. 🙂
