### ISSUE TITLE
`Feature Request` Support covers in chips

### ISSUE THREAD

**Issue by thenoid** [Blackymas/NSPanel_HA_Blueprint#932]
While covers have more state than just on/off - they do have an eventual state of open/closed which are corollaries.

**Comment by thenoid** [comment]
Could it show one for each state? different icon for open/closed?

**Comment by edwardtfn** [comment]
Everything is possible, but as the concept of the chips as they are now is about showing when is on/true and hiding when is off/false.
Again, it is feasible to change that to be 2 icons instead, it's just a bit more work as the logic have to be rebuild.
I will see if I can find some time to look at that.

**Comment by edwardtfn** [comment]
It is on `dev` and should be included in the next release.

**Comment by edwardtfn** [comment]
- #1556
