### ISSUE TITLE
Cannot upload HA blueprint to the NS panel

### ISSUE THREAD

**Issue by Larthienn-mobile** [Blackymas/NSPanel_HA_Blueprint#936]
The upload is stuck. It takes ages to begin with and then it's stuck on the blue screen asking to wait.
![IMG-20230717-WA0009](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/6196963/a4606041-999d-4dc9-92e7-417ca6056d5a)

**Comment by edwardtfn** [comment]
You have installed a development version of TFT file and ESPHome. Was that intentional?

You are stuck on this screen due to the Blueprint not responding to the panel.
1. Please make sure you have the Blueprint with the same version and there is an automation set. Also, make sure the panel is selected properly on your automation.
2. Have you renamed your panel after installing into Home Assistant?
3. Have you tried restarting your panel and Home Assistant?
4. Do you have any error message in your logs? (Settings > System > Logs)

**Comment by iJuiceman** [comment]
I have the same issue, except I am on 3.4.
The whole flashing process worked fine, but once the GUI comes up on the screen it just hangs.
I have reflashed the NSP with the blank TFT and then the EU one, with the same result.  Looking at the logs, I see:

Logger: homeassistant.components.automation.bed_ns_panel
Source: components/esphome/__init__.py:623
Integration: Automation (documentation, issues)
First occurred: July 20, 2023 at 2:57:25 PM (254 occurrences)
Last logged: 9:46:50 AM

Bed NS Panel: Choose at step 2: choice 29: Error executing script. Unexpected error for call_service at pos 2: Connection not done for bednspanel @ 192.168.107.147; current state is ConnectionState.INITIALIZED!
Bed NS Panel: Choose at step 2: choice 30: Error executing script. Unexpected error for call_service at pos 2: Connection not done for bednspanel @ 192.168.107.147; current state is ConnectionState.INITIALIZED!
Bed NS Panel: Error executing script. Unexpected error for choose at pos 2: Connection not done for bednspanel @ 192.168.107.147; current state is ConnectionState.INITIALIZED!
While executing automation automation.bed_ns_panel
Bed NS Panel: Choose at step 2: choice 19: Error executing script. Unexpected error for call_service at pos 1: Connection not done for bednspanel @ 192.168.107.147; current state is ConnectionState.INITIALIZED!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 623, in execute_service
    await entry_data.client.execute_service(service, call.data)
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 1260, in execute_service
    self._check_authenticated()
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 328, in _check_authenticated
    self._check_connected()
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 322, in _check_connected
    raise APIConnectionError(
aioesphomeapi.core.APIConnectionError: Connection not done for bednspanel @ 192.168.107.147; current state is ConnectionState.INITIALIZED!

**Comment by edwardtfn** [comment]
I’ve created #950 for this as this issue here is about a `dev` environment.
