### ISSUE TITLE
Multiple climate controls

### ISSUE THREAD

**Issue by hapklaar** [Blackymas/NSPanel_HA_Blueprint#938]
Is it possible to add controls for multiple rooms to the panel, or is just one supported?

**Comment by hapklaar** [comment]
Nevermind, found my answer just below!

**Comment by baloo2** [comment]
Can you please direct me to the right answer? I want to add multiple climate controls to my NSPanel as well. Thanks.

**Comment by thromera** [comment]
Same ! :)

**Comment by edwardtfn** [comment]
You can have only one climate controlled by the panel's relays, and this could use either the panel's embedded temperatura sensor so after set it will work independently of Wi-Fi or Home Assistant availability.
However, you can assign other climate entities available on Home Assistant to any of the buttons (hardware, button pages or custom buttons on Home page) and this will allow controlling the climate entity from your panel, even entities related to other rooms.
