### ISSUE TITLE
ESPHome 2023.7.0 doesn’t compile. 

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#939]
Not a major issue with existing panels but trying to update them I get several errors.   

The restore_state option has been removed in 2023.7.0. Use the restore_mode option instead.

**Comment by willemumbrio** [comment]
Copy of the log file:
Failed config

switch.template: [source /config/esphome/.esphome/packages/b62d81b2/nspanel_esphome.yaml:735]
  name: nspanel Notification unread
  platform: template
  id: notification_unread
  entity_category: config
  
  The restore_state option has been removed in 2023.7.0. Use the restore_mode option instead.
  restore_state: True
  optimistic: True
switch.template: [source /config/esphome/.esphome/packages/b62d81b2/nspanel_esphome.yaml:743]
  name: nspanel Notification sound
  platform: template
  id: notification_sound
  entity_category: config
  
  The restore_state option has been removed in 2023.7.0. Use the restore_mode option instead.
  restore_state: True
  optimistic: True
  restore_mode: RESTORE_DEFAULT_OFF
switch.template: [source /config/esphome/.esphome/packages/b62d81b2/nspanel_esphome.yaml:752]
  name: nspanel Confirmation Message
  platform: template
  id: confirmation_message
  entity_category: config
  
  The restore_state option has been removed in 2023.7.0. Use the restore_mode option instead.
  restore_state: False
  optimistic: True
switch.template: [source /config/esphome/.esphome/packages/b62d81b2/nspanel_esphome.yaml:787]
  name: nspanel Sleep mode
  platform: template
  device_class: switch
  id: sleep_mode
  entity_category: config
  restore_mode: RESTORE_DEFAULT_OFF
  
  The restore_state option has been removed in 2023.7.0. Use the restore_mode option instead.
  restore_state: True
  optimistic: False
  turn_on_action: 
    - logger.log: Sleep mode - Turn on
    - lambda: id(disp1).send_command_printf("home.sleepmodus.val=1");
    - lambda: id(disp1).set_component_value("settings.bt1",1);
    - switch.template.publish: 
        id: sleep_mode
        state: True
  turn_off_action: 
    - logger.log: Sleep mode - Turn off
    - lambda: id(disp1).send_command_printf("home.sleepmodus.val=0");
    - lambda: id(disp1).set_component_value("settings.bt1",0);
    - switch.template.publish: 
        id: sleep_mode
        state: False
switch.template: [source /config/esphome/.esphome/packages/b62d81b2/nspanel_esphome.yaml:811]
  name: nspanel Relay 1 Local Fallback
  platform: template
  id: relay1_fallback
  entity_category: config
  
  The restore_state option has been removed in 2023.7.0. Use the restore_mode option instead.
  restore_state: True
  optimistic: True
  restore_mode: RESTORE_DEFAULT_OFF
switch.template: [source /config/esphome/.esphome/packages/b62d81b2/nspanel_esphome.yaml:819]
  name: nspanel Relay 2 Local Fallback
  platform: template
  id: relay2_fallback
  entity_category: config
  
  The restore_state option has been removed in 2023.7.0. Use the restore_mode option instead.
  restore_state: True
  optimistic: True
  restore_mode: RESTORE_DEFAULT_OFF

**Comment by PaulBiod** [comment]
The same here

**Comment by smarthomefamilyverrips** [comment]
same here

**Comment by lloydbayley** [comment]
Yep. Can report the same behaviour here too. Ain't bugs wonderful! :)

**Comment by edwardtfn** [comment]
Could any of you try the fix on beta?

**Comment by lloydbayley** [comment]
It VERKS!! It VERKS!!! Tested fine here!

**Comment by synack666** [comment]
@edwardtfn  works, no problems

**Comment by ianmen** [comment]
Beta is also working here for me.

**Comment by Doughboy68** [comment]
Yes works for me. Thanks!

**Comment by adamengineering** [comment]
Works, Thx a lot for the quick patch. I assume we can revert back, to the 'main' branch after the update.

**Comment by RIKWEBB** [comment]
Beta working here too 👍

**Comment by KoKolaj** [comment]
Yes works for me. Thanks!

**Comment by edwardtfn** [comment]
I just got back home. Will try to release to `main`.
