### ISSUE TITLE
Removing not required Button and Entity pages from display

### ISSUE THREAD

**Issue by tgessendorfer** [Blackymas/NSPanel_HA_Blueprint#946]
It would be great if one could en- and disable Entity and Button pages to be shown on the display.
Mostly I only use a sub portion of the 4 possible pages but the dots on the screen for any non-used pages is still shown with empty pages. It would be great to have a possibilty to remove or disable non used pages.

**Comment by deejaybeam** [comment]
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/868

**Comment by edwardtfn** [comment]
I've played a bit with this and as I mentioned in #868, the hardest was to find a replacement for those page indicators. I've tried with other circles, but it didn't looked that good, but I'm sure we can find a nice solution for that.
I will see if I can find some time for this after the next release (already quite big). But any help will be welcome. 😉

**Comment by edwardtfn** [comment]
I was thinking more about using circle shaped chars (https://commons.m.wikimedia.org/wiki/Unicode_circle_shaped_symbols). That could be a simple string quite easy to create based on the number of pages and the current page.
I wanna avoid numbers as that could mean additional localization needs.

**Comment by edwardtfn** [comment]
It is still pending more tests, but this is implemented in `dev´ and hopefully will be released with v4.3 soon.
I've implemented only for button pages and for entities pages for now, as I wanna review the whole weather pages in the near future.

I'm closing this for now to clean-up my backlog, but please feel free to add comments or to reopen-it if the new solution is not solving the issue.

**Comment by edwardtfn** [comment]
Hi, have you got a chance to try the solution for this currently in beta? If so, please let me know if that was effective.
