### ISSUE TITLE
TFT Display bleibt nach dem Flashen das original

### ISSUE THREAD

**Issue by AFid08** [Blackymas/NSPanel_HA_Blueprint#947]
Eine tolle Lösung und eine super Anleitung. Respekt und vielen Dank.
Ich habe aber leider noch ein Problem nach dem flashen.
Das Panel wurde in ESP32 als Gerät gefunden und hat eine IP und scheint online zu sein.
Leider ist aber die Anzeige auf dem Display noch die alte von Sonoff. Die TFT Datei ist im www Verzeichnis.
Sollte eigentlich so funktionieren......was hab falsch gemacht?

Unter Diagnose findet sich, dass das Nextion display getrennt sei.....?
`Diagnose
 
NSPanel-Original
Zu Hause
 
IP
192.168.177.93
 
Nextion display
Getrennt
 
RSSI
-66 dBm
 
Status
Verbunden`
Viele Grüße, AndiFidi

**Comment by jessevd** [comment]
I seem to have the same problem! Flashing went fine, the ns panel works in HA, I can control the buttons and see the temp, but press the update tft display button doesn't do anything.

**Comment by AFid08** [comment]
Es funktioniert:

Ich habe versucht mit dem AddOn ESPHome zu flashen. Das sieht auch zunächst ganz gut aus, aber
das Panel übernimmt es nicht korrekt. Und hier war es bei mir egal, ob über den Intel NUC oder über den Mac mit dem Plugin geflasht wurde. Es kam ständig der Fehler “Nextion display ‘not connected’”.

Dann habe ich in einen anderen Video ([https://haus-automatisierung.com](https://www.youtube.com/watch?v=uqPz08ZpFW8) beschrieben) den Tipp zur Nutzung des [Jason2866](https://github.com/Jason2866)/[ESP_Flasher](https://github.com/Jason2866/ESP_Flasher) gefunden. Hier gibt es unter [Releases · Jason2866/ESP_Flasher · GitHub](https://github.com/Jason2866/ESP_Flasher/releases) Programme für Windows und Mac. Ich habe mit einem Windows PC geflasht. Vorher unter ESP32 Home die BIN-Datei erstellt mit Manual Download/Legacy Format.

Nach dem Flashen alles wieder zusammengebaut und siehe da…es funktioniert.

Geflasht habe ich mit einem [CP2102](https://www.amazon.de/dp/B0773G2K92?ref=ppx_pop_mob_ap_share)

**Comment by edwardtfn** [comment]
@AFid08, as I understood, you got the system to work in the end, right?
Should we close this issue?

**Comment by Razsmithii** [comment]
@AFid08 It seems that it´s normal, the old Sonoff screen is shown after flashing ESPHome. So it´s not a problem which can be solved by flashing a new firmware with another flashing tool.
I had the same problem and this worked for me:

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/539#issuecomment-1530957392

**Comment by Rob65** [comment]
I had limited success with the reparse button. It worked on one screen, not on the other one.
But for that display, using the older Nextion library worked.
This is documented on: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload#10-use-an-older-nextion-library-for-esphome
