### ISSUE TITLE
Hot Water Temperature & Charge no longer available in the automation template?

### ISSUE THREAD

**Issue by itslennie** [Blackymas/NSPanel_HA_Blueprint#948]
Was this functionality removed in v3.4 or is it a bug?  The setup instructions still refer to this functionality in v3.3, and it was something I liked and often used.  

Below are the settings that no longer appear in v3.4.

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/42844738/3eae5af2-ecce-4290-b23a-9aaa45869119)

**Comment by deejaybeam** [comment]
This has been more generalized:
Hot Water Temperature Sensor -> SENSOR HOME PAGE - Sensor 03 (ENTITY/ICON/ICON COLOR/LABEL COLOR)
Hot Water Charge -> CLIMATE - Custom button(s)
Top Menu 04 -> CHIPS - Chip 01 (ENTITY/ICON/ICON COLOR)

**Comment by itslennie** [comment]
Thanks for the information
