### ISSUE TITLE
Blueprint automation radio buttons don’t allow to disable to prevent a blank page

### ISSUE THREAD

**Issue by jdmevo123** [Blackymas/NSPanel_HA_Blueprint#949]
I’ve setup the nspanel and blueprint configuration. On my screen I have a number of blank pages, however the blueprint does not allow you to deselect the radio button. I have tried multiple clicks, single click, and even trying by inserting in the html and nothing allows me to prevent the page from showing on the panel.

**Comment by edwardtfn** [comment]
Unfortunately at this point the empty pages cannot be hidden.

**Comment by jdmevo123** [comment]
Ok thanks, and is there a way to make the climate come up as a page, or is it only when you click on the temp on the Home Screen?

**Comment by edwardtfn** [comment]
If you add a climate entity to any of the button pages, a long press on that will show the climate page.

**Comment by deejaybeam** [comment]
> If you add a climate entity to any of the button pages, a long press on that will show the climate page.

Short press works also for climate to open the climate-page

**Comment by jdmevo123** [comment]
Great thanks
