### ISSUE TITLE
Error after upload TFT file

### ISSUE THREAD

**Issue by tvgnl** [Blackymas/NSPanel_HA_Blueprint#953]
Hi!

When I update TFT display it takes almost 24 hours before it is ready. Then it gives the following error message:
![Scherm­afbeelding 2023-07-29 om 08 53 28](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/56624255/9be482ce-50b9-4f54-a725-965eb6bab941)
After restarting it gives the message System Data ERROR!

When i check the log a see only this error: [W][nextion:402]: Nextion reported variable name invalid!

I need some help ;)

**Comment by edwardtfn** [comment]
I would recommend to just try again.
It shouldn't take more than 15 to 20min to transfer the file, so if it is taking more than 30min I would always recommend to cancel and try again, as I never seen a case where those super long transfer finished without an error.

**Comment by edwardtfn** [comment]
> When i check the log a see only this error: [W][nextion:402]: Nextion reported variable name invalid!

This error message is expected when you don't have the right TFT installed.

**Comment by tvgnl** [comment]
> https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload

Thanks! Point 7. "Exit reparse" button was the sollution.
