### ISSUE TITLE
Dev Branch - climate page not updating changes.

### ISSUE THREAD

**Issue by Doughboy68** [Blackymas/NSPanel_HA_Blueprint#957]
Testing Dev and noticed it does not update changes back to my ecobee thermostat when I exit the page.
Eg. if I adjust temperature using slider or plus/minus it updates on screen, but does not update the actual thermostat.

**Comment by edwardtfn** [comment]
I could duplicate this. Will take a look.

**Comment by edwardtfn** [comment]
Fixed!
Please flash your device again and it should work fine.

**Comment by Doughboy68** [comment]
Confirmed is working now.
