### ISSUE TITLE
Error: NSPANEL using unknown service.... - caused by double device_name in blueprint/automation -  result: stuck in startup screen

### ISSUE THREAD

**Issue by trondtorsoe** [Blackymas/NSPanel_HA_Blueprint#958]
Hi

When setting up several nspanels today - I got the same error on all of them.
The panels are from the same batch as others installed earlier - and working fine.

Reporting nspanel using an unknown service. The text (see picture) showing the device_name DOUBLE in the printf.

When testing the printf service without the double name in Developer Tool (see picture) - the panel respond normal.

The result is a panel stuck in startup screen.....

TFT: 3.4
ESPHOME: 3.4.1
Blueprint: From today

![double decice_name](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/50380501/6d2d68fb-ada0-4dd1-9f82-2bd0db772caa)
![developer tool](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/50380501/65bf55e1-b8f4-421e-bda6-a8560bf8d76d)

![settings](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/50380501/ab11b921-5098-4939-84e1-9105d014ffbd)
60-7233caecea73)
![prinf](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/50380501/3c5da91d-7325-4f98-ae83-59a609bc77c6)

**Comment by edwardtfn** [comment]
Have you added a `friendly_name` in your ESPHome yaml? If so, please remove that. Or have you renamed your panel after adding to Home Assistant.

Otherwise, could you please share your Yaml?

Looks like the problem is a mismatch between the name pattern in the entities and the services in the same panel.
