### ISSUE TITLE
Flashing succeeded but... 

### ISSUE THREAD

**Issue by jacky-coke** [Blackymas/NSPanel_HA_Blueprint#964]
After having had some troubles flashing yesterday, after some sleep, flashing worked fine. 

My "nik.yaml" looks as follows, afterward I downloaded the legacy mode-version and flashed using [this](https://github.com/Jason2866/ESP_Flasher/releases), really easy to use, piece of software as suggested within another thread.

`
substitutions:

###### CHANGE ME START ######

  device_name: "nspanelegflur" 
  wifi_ssid: "HA-TEST"
  wifi_password: "password"

  nextion_update_url: "http://192.168.0.56:8123/local/nspanel_eu.tft" # URL to local tft File
  #nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
`

Home-Assistant connects to the device successfully, I can control the devices relays and they work.
<img width="340" alt="image" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/80129168/ca4136da-e4a3-49ac-b9f0-680593480a45">

Short question at this point: 
What should the device show now? I still get the Sonoff-Look and Feel but clock, temperatures, etc. are missing values: 
<img width="361" alt="image" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/80129168/eb035aa7-a64b-4c18-a6d2-5256b5e1b930">
Is this correct? 

The "nspanel_eu.tft" file is available and accesable using the link from the YAML-File. 

When hitting the "Exit reparse"-button, I don't get any kind of feedback, the device simply does nothing. 
After pressing "Update TFT display", the device reboots (still the fancy Sonoff-animation) and that's it.

Any idea what's wrong? 

Many thanks in advance, 
Nik

**Comment by robgough1970** [comment]
try flashing the 'blank' tft file first and then the nspanel_eu.tft

**Comment by jacky-coke** [comment]
Good hint, will give it a try tomorrow when I‘m back home: Shall I reboot the device in between or just flash one after the other?

Von meinem iPhone gesendet

Am 04.08.2023 um 18:58 schrieb robgough1970 ***@***.***>:

﻿

try flashing the 'blank' tft file first and then the nspanel_eu.tft

**Comment by edwardtfn** [comment]
There's no need to reboot, however, unless you install it calling the service `esphome.xxxxx_upload_tft_url`, you will have to reflash your panel with the other file, which will force a reboot anyways.

**Comment by jacky-coke** [comment]
> There's no need to reboot, however, unless you install it calling the service `esphome.xxxxx_upload_tft_url`, you will have to reflash your panel with the other file, which will force a reboot anyways.

Um, I‘m afraid I don‘t understand what you‘re suggesting:
The device gets the path to the correct .tft from the YAML file I created within ESPhome on HA, right? 

This is the ‚configuration‘ of the compiled firmware, that is created during the ‚install‘ process on ESPhome, correct? 

So when I want to flash the device first with the blac-config, I dismount the display, connect the FTDI card, flash using the tool: But what then? Put everything back together and fire up the panel or shall I flash the other file immediately afterwards?

Sorry, I‘m new to this kind of works and don‘t understand the procedure exactly and don‘t understand when and how I should do the step you describe…

Thanks a lot for your help and sorry for my poor qualifications…!

**Comment by edwardtfn** [comment]
> The device gets the path to the correct .tft from the YAML file I created within ESPhome on HA, right?

Right

> This is the ‚configuration‘ of the compiled firmware, that is created during the ‚install‘ process on ESPhome, correct?

Yeap.

> So when I want to flash the device first with the blac-config, I dismount the display, connect the FTDI card, flash using the tool:

If this is the first time you are installing ESPHome on this device, this is correct.

> But what then? Put everything back together and fire up the panel or shall I flash the other file immediately afterwards?

1. Put everything together and fire up the panel. At this moment, you will be running ESPHome from this project, but your panel's display (which is an independent processor) will still using the original TFT from Sonoff. You don't have to dismount your panel again after installing ESPHome for the first time. The next step will all be possible to run over Wi-Fi.
2. Your panel will be discovered in Home Assistant.
3. You will have to follow [these steps](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload#7-exit-reparse-button) to update the TFT with the file indicated in your yaml (recommended to use `nspanel_blank.tft`).
4. After `nspanel_blank.tft' is uploaded, your panel will automatically restart and then you will se a QR code in the screen. That's a good signal.
5. You will have to change your yaml to point to `nspanel_eu.tft` or `nspanel_us.tft`, and then install (flash) that again in your device, but now you can flash it wirelessly, without the need to disassemble.
6. Your panel will restart again, but still showing the QR code on the screen.
7. You open your device page (Settings > Devices and Services > ESPHome) and press the button "Upload TFT" again. The new TFT will be uploaded in 15 to 20min (if it takes more than 30min I recommend you stop the process and try this step again.
8. Your device will automatically restart again, and now will come back with a blue screen with Home Assistant logo. We call this "Boot page".
9. You setup your blueprint as a new automation (please be sure you selected your panel there) and everything should start working.

> Sorry, I‘m new to this kind of works and don‘t understand the procedure exactly and don‘t understand when and how I should do the step you describe…
>
> Thanks a lot for your help and sorry for my poor qualifications…!

No need to apologise. We all started from the same point. 😉
Feel free to ask for help.

**Comment by jacky-coke** [comment]
Thanks a lot for your detailed instructions and explanations! 
It helps a lot to understand the processes behind. 

Unfortunately, I couldn't make it yet, to get this running:
I don't understand how to change the path to another TFT file without flashing a new firmware (with the disassembled device, FTDI adapter, etc.). So I didn't but did a little workaround:
I renamed the nspanel_blank.tft to nspanel_eu.tft and replaced the original file on my /config/www folder and follow the steps described above but still get the valueless-Sonoff screen instead of any QR-codes or HA-logo. 

Any idea?

**Comment by edwardtfn** [comment]
Focus on installing `nspanel_blank.tft` first. It's much smaller and then it will make easier to install for the first time (as the Sonoff TFT imposes some restrictions).
`nspanel_blank.tft` will replace the Sonoff screen by a QR code, so while you don't get that QR code on your screen, don't try to move ahead to `nspanel_eu.tft` yet.

So, if you are having issue with installing `nspanel_blank.tft`, I will ask you to look again at this wiki: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload
I believe items 7 and 8 will be sokvind the issue in your case, but take a look at item 5 and then in the entire page in case you are stuck.

**Comment by edwardtfn** [comment]
> I don't understand how to change the path to another TFT file without flashing a new firmware (with the disassembled device, FTDI adapter, etc.).

With ESPHome, you only have to disassemble your device (and use FTDI adapter, etc) for the first time you flash the device. Since ESPHome is flashed, you can edit the yaml and flash it wirelessly:

![IMG_6356](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/0c2566b2-6bb9-486e-9774-b0681a9ba835)
![IMG_6357](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/c16ef934-b804-43da-806d-b1465cee8581)

**Comment by jacky-coke** [comment]
Oh... didn't recognize this yet: Thanks for the hint! 

But still not making any progress:
Please find the log attached as a file; a repeating error here as a screenshot:

<img width="789" alt="image" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/80129168/2e880a25-6905-43cc-81ae-884ebaa5d054">

[logs_nik_run (2).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/12267596/logs_nik_run.2.txt)

**Comment by edwardtfn** [comment]
Could you please share your ESPHome yaml? Please remove any sensitive information before sharing.

**Comment by edwardtfn** [comment]
On your log I cannot find any instance of you pressing either "Exit reparse" or "Upload TFT" buttons.
What happens when you use those as described on the previous wiki I've pointed you to?

**Comment by jacky-coke** [comment]
> Could you please share your ESPHome yaml? Please remove any sensitive information before sharing.

'substitutions:

###### CHANGE ME START ######

  device_name: "nspanelegflur" 
  wifi_ssid: "NIK-NET"
  wifi_password: "halloD05"

  #nextion_update_url: "http://192.168.0.56:8123/local/nspanel_blank.tft" # URL to local blank tft File
  nextion_update_url: "http://192.168.0.56:8123/local/nspanel_eu.tft" # URL to local tft File
  #nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####'

**Comment by jacky-coke** [comment]
> On your log I cannot find any instance of you pressing either "Exit reparse" or "Upload TFT" buttons. What happens when you use those as described on the previous wiki I've pointed you to?

The log is the output from the appearing window after I did what you described within the above screenshots (Install -> Wireless....). The interruption I did before I started the installation. Is that wrong? At what time do I have to interrupt?

**Comment by jacky-coke** [comment]
Okay....
I played a little bit around, rebooted both, Display and HA (fully) and after the installation of the YAML was at its end, I hit the "Exit parse" button followed by "Update display TFT" and got a first time a reaction to the "Exit parse" command (progress circle followed by a blue check. 
After the "Update display TFT" button the screen turned white and ended up like this: 

<img width="589" alt="image" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/80129168/c5cf1d36-231a-476d-87d4-93f198e86639">

Logs: 
[logs_nik_run (3).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/12267685/logs_nik_run.3.txt)
 
YAML-Config: 
<img width="1069" alt="image" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/80129168/c85d360f-a5c7-4758-968b-a0518dff0661">

**Comment by edwardtfn** [comment]
Just press the "Upload TFT" button again and it should restart.

**Comment by edwardtfn** [comment]
Are you sure you have the file with right size in your server?

Have you looked at item 5?
https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload#5-check-the-file-size-by-downloading-to-your-computer

**Comment by jacky-coke** [comment]
> Just press the "Upload TFT" button again and it should restart.

No, device was stuck but after powering off twice (1st attempt just got a white screen with noting on it) I was able to reach it again.

**Comment by jacky-coke** [comment]
> Are you sure you have the file with right size in your server?
> 
> Have you looked at item 5? https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload#5-check-the-file-size-by-downloading-to-your-computer

It wasn't - for whatever reason... 
Just downloaded the raw file of the blank-file and finally got the long awaited QR code 😎

**Comment by edwardtfn** [comment]
Now you can repeat the same process with `nspanel_eu.tft`.

**Comment by jacky-coke** [comment]
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/80129168/7274a323-5e8b-4c71-b591-523c883ccacb)

Yeppah 😎🥳
Thank you so much for your assistance, things worked great! 

Now I need to get used to the Blueprint and see about the possibilities to add some functionality (intention is to control the alarm-system and some other Homematic Stuff)...

Thanks again for your support - also from my wife, I really started driving her mad... 🙈

**Comment by edwardtfn** [comment]
Alarm control panel is coming in the next release. 😉
