### ISSUE TITLE
Updateproblem 3.41

### ISSUE THREAD

**Issue by AFid08** [Blackymas/NSPanel_HA_Blueprint#966]
Hallo,
ein Update auf Version 3.41 funktioniert leider nicht wie in Deiner [Beschreibung](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(DE)-HowTo---Alle-wichtigen-Dinge-die-man-wissen-sollte#2-update-blueprint). 
ESPHome ist 3.4.1 geupdatet worden. Leider die TFT Datei auch nicht. Es stockt nach der Validierung in ESP32 (Homeassistant).
Eine Installation via WLan ist nicht möglich, natürlich auch das update der TFT Datei.

Ansonsten funktioniert alles bestens.....aber mich würde interessieren was ich falsch mache :-)

**Comment by edwardtfn** [comment]
1. What can you see in your panel's screen?
2. From which version are you updating from?

**Comment by edwardtfn** [comment]
Looks all rightm0. You have all the latest versions. The bug fix implemented with v3.4.1 was on ESPHome only, so the Blueprint and TFT remains v3.4.
