### ISSUE TITLE
Icons on First Screen

### ISSUE THREAD

**Issue by AFid08** [Blackymas/NSPanel_HA_Blueprint#970]
Hi, how can i get the marked Icons? (s. Picture) I can't find a possibility to do this.
Kind Regards 

![PanelStart](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/123198927/eaf3f7ef-f68a-4270-bcc6-b8601b604bf4)

**Comment by tarnix** [comment]
I have not found that yet either. can anyone help? 

Thanks

**Comment by edwardtfn** [comment]
1. Some of the icons will be shown based on your configuration:
- QR code 
- Entities pages
2. Notifications icon will be shown when you call the service to notify
3. Some are not yet implemented
- Alarm control panel is coming on v3.5

**Comment by edwardtfn** [comment]
The value in the top right corner is one of the sensors defined for page home. I'm sorry, but it isn't on top of my mind which one and I don't have my panel now.

![IMG_6371](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/b1f7f550-0a92-462c-af24-8952f861e7ef)

**Comment by edwardtfn** [comment]
If you are looking for some feature that is not available yet, please let us know.

**Comment by tarnix** [comment]
Hi Edwardt,

I did not understand when the icons appear under the clock. I thought that when I click on the solar panel, for example, that the data would then be displayed.

regards Dom

**Comment by edwardtfn** [comment]
Those are buttons. And t are the buttons currently implemented:

## QR code
When you set a QR code in your Bluetooth settings and save it, a QR code icon will be shown on your panel's Home page. By clicking on that icon, you will get a screen with the QR code only.

![IMG_6374](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/90f37a4a-f797-462a-8ec6-728e80ab5d34)

&nbsp;
## Entities pages
This one is also enabled on your Bluetooth settings, but requires an active selection, which will enable the icon on the screen and, again, when on click on that icon the Entities pages will be shown with a list of selected entities and it's values:
![IMG_6375](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/19a6c25b-83d4-4a16-bbda-b561b1f836e3)

&nbsp;
## Notifications
This one is shown when a notification is available and, with a click, will show the notification page.
The notification is created by a service call (`esphome.xxxxx_notification_show`):
![IMG_6376](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/a39bb4d8-61b0-4363-9735-b3987e23b8b8)

**Comment by tarnix** [comment]
Ok thanks, I will try it.

**Comment by AFid08** [comment]
> If you are looking for some feature that is not available yet, please let us know.

Hi @edwardtfn 
Thank you very much. Yes, I actually have a few suggestions: 

1. In the automation for programming the Panel, a drop-down menu would be good, where I can choose which section to jump to edit. Scrolling in automation is currently very slow. 

2. Make the timeout to jump back to the main menu adjustable. E.g. button menu 1 - if not selected - jump back after xx seconds. 

Regards
AFid08

**Comment by edwardtfn** [comment]
> 1. In the automation for programming the Panel, a drop-down menu would be good, where I can choose which section to jump to edit. Scrolling in automation is currently very slow.

Unfortunately that is a limitation from Home Assistant and I cannot hide part of the settings based on user's selection.

> 2\. Make the timeout to jump back to the main menu adjustable. E.g. button menu 1 - if not selected - jump back after xx seconds.

That is available. Go to your device settings (Settings > Devices and Services > ESPHome) and just the "Page timeout":
![IMG_6377](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/fbf1a433-535b-4837-8152-d93479aeeca6)
