### ISSUE TITLE
Error after update to v3.4

### ISSUE THREAD

**Issue by robsonfelix** [Blackymas/NSPanel_HA_Blueprint#971]
After updating everything to v3.4 I get a never ending "loading" message on all my NS Panels.

![WhatsApp Image 2023-08-07 at 20 39 02](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/9100568/203642e4-f1cb-4c87-bee4-0232647e098c)

**Comment by DerBo19** [comment]
Just updated the panel and can confirm the same issue with EU-Version...

**Comment by DerBo19** [comment]
Just found out, that you have to update the tft file manually via HA! Somebody wrote this in here:[https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/877](url)

**Comment by DerBo19** [comment]
So that one worked for me:

1. Download latest nspanel_us.tft/nspanel_eu.tft on github
2. Replace the old file in your www folder in HA
3. Update tft file with the upload switch in your devices configuration at Devices & Services --> Integrations (this step may take a while)
4. Have fun with the new appearance!

**Comment by edwardtfn** [comment]
@robsonfelix, could you please confirm you have updated all the 3 parts (blueprint, ESPHome and TFT)? You will be able to see all the version numbers at the boot page after restarting your panel.

Latest versions are:
TFT: v3.4
ESPHome: v3.4.1
Blueprint: v3.4

**Comment by robsonfelix** [comment]
- the blueprint is up to date;
- the TFT file is up to date
- the ESP home file is downloading directly from github on build, so I assume it's downloading the right version

now, when I press the 'update tftt display' button on the device within Home Assistant, the NSpanel is now showing an error message like this:

"Model does not match
Device Model:
NX4832F035_011C"

**Comment by robsonfelix** [comment]
Folks, it was a mistake on my part. I have downloaded the files incorrectly from GitHub. I fixed my update script, proceeded with the ESPhome update (once again), and used the "Update TFT display" and now everything is working as expected. 

Thank you.
