### ISSUE TITLE
Received unknown event from nextion: 0x55

### ISSUE THREAD

**Issue by Mithrox** [Blackymas/NSPanel_HA_Blueprint#973]
Hello.

I am a new user of the NSpanel and I have followed the recommended videos to setup and install it correctly. I did straight away run into the problem with Nextion disconnected, and I have such attempted the different suggestions around.

I first started with the short config, referring to the nspanel_eu.tftp file, both on Github and locally. I have verified that both URLs are correct and through the browser I can download directly, so there is nothing wrong with the URLs. I then proceeded to try the complete configuration as per this URL:

https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/nspanel_esphome.yaml

I changed the top sections to look like this:

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/58890682/276483aa-652f-436c-8220-c34eafe5f80b)

I could still not use the Exit Reparse button to any success, so I also uncommented this section:

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/58890682/5d49d71b-5439-4164-9ab2-245ea77b0caa)

Now I get a bit further, but the upload of the TFTP does not work. I have attached the log file with all messages to it in this post.

[nspanel_log.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/12293957/nspanel_log.txt)

I am a bit at wits end right now, I cannot understand what is still wrong, and I am hoping this would make sense and so there could be a solution. I have bought several panels and have use cases for them all, but I want to have the first one working properly before I move on to next one.

**Comment by Mithrox** [comment]
I waited about 5 minutes while writing this post, and then just pressed the Exit Reparse button (should not have any effect with the setting), and then right after I pressed Update TFTP Display... and lo and behold, it actually updated. I have not let it stay for a few minutes at all since I started the process, but I did not think that would be necessary. Is there some weird timer or timeout I have to wait for before updating it?

I will close this issue, but just want to see if there is some input that can shed light on this behavior first.

**Comment by edwardtfn** [comment]
I don't know from where you found the instructions, but looks a bit old.

I would suggest to use the instructions from the wiki: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload

"Exit reparse" is item 7 there.

**Comment by Mithrox** [comment]
I followed the recent information for the default installation, but when it did not work, I had to get creative and look through different Github threads and forum posts. The changes I did to the full config was from this Github page, and it was the thing that resolved it, but since it did not work after boot, but after a while waiting, I am not certain it will work on the next one. I will modify and test the next one tomorrow, right now I am trying to work out the configuration and make it useful.

**Comment by Mithrox** [comment]
After a couple reboots the first panel is now stuck on the boot screen, where it says IP and Please Wait, as well as the reboot button. I have reinstalled (wirelessly) and booted, but it still stops at the same place every time. Is there a caveat or something I should check when that's where it stops?

**Comment by edwardtfn** [comment]
Which versions are shown for TFT, ESPHome and Blueprint on that boot screen?

**Comment by Mithrox** [comment]
> Which versions are shown for TFT, ESPHome and Blueprint on that boot screen?

TFT: 3.4
ESPHome:
Blueprint:

For some reason it looks like it's not picking up the rest, only shows the TFTP version.

**Comment by edwardtfn** [comment]
Please try pressing the restart button under the device page (Home Assistant > Devices and Services > ESPHome).

**Comment by Mithrox** [comment]
> Please try pressing the restart button under the device page (Settings > Devices and Services > ESPHome).
> 
> ![IMG_6368](https://user-images.githubusercontent.com/94725493/259226731-e845c42d-6976-40e5-bd9a-c0cc9ca868f5.jpeg)

Yes, I used it earlier, but when I did it now it got a bit further. It now shows the IP address, as well as the ESPHome: 3.4.1 version. But still not showing the blueprint, and it seems stuck.

I am considering deleting everything and then flashing it over again with a new name in ESPhome/config/HA, and then see if I can get it back up and running.

**Comment by edwardtfn** [comment]
There's no need to flash again or upload TFT, as that part looks fine.

**Comment by edwardtfn** [comment]
Please take a look for any error message related to your panel under System > Logs.

**Comment by edwardtfn** [comment]
Have you renamed any entity from this device after it was detected by Home Assistant?

**Comment by Mithrox** [comment]
> Have you renamed any entity from this device after it was detected by Home Assistant?

No, none of the entities has changed names. But I do think I know one problem. When I flashed the second, I used the bin file from the first as I first thought they were the same. When I found out, I changed to the correct one (downloaded from the nspanel02 created device) and then it came up as the standard Sonoff software but with ESPHome connection. From another post I found I saw that it was ticklish with naming, so I may have screwed it up due to it.

I think best option is to start from scratch to make sure there is no issue with naming anywhere now in ESPhome or HA, and then hope I can get it back up either by the normal defined way, or by the way I did it first time.

What I find problematic though is that I followed the instructions (from Github) to the tee on the first one, and the Exit Reparse did not show the change on screen as the documentation shows, that's why I had to find the alternative file and config edits.

**Comment by edwardtfn** [comment]
Yeah, reflashing ESP might be better in your case. You don't have to upload TFT again on the panel where it is already done. On Home assistant side, I would recommend removing it from Devices and Services, no need to create the Blueprint again (just double check if the panel select is right after the reflash).

**Comment by edwardtfn** [comment]
When "Exit reparse" isn't working, you can use the reference for pr#5016, but there's no need to edit it on the big nspanek_esphome.yaml file, as you can do in your local file just adding the reference as on the last item on the wiki: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload#8-use-an-older-nextion-library-for-esphome

**Comment by Mithrox** [comment]
> Yeah, reflashing ESP might be better in your case. You don't have to upload TFT again on the panel where it is already done. On Home assistant side, I would recommend removing it from Devices and Services, no need to create the Blueprint again (just double check if the panel select is right after the reflash).

Ok, the panel has been reflashed, with a new name, and I started it again. It comes up with the same screen, IP on top, TFT: 3.4 and ESPHome 3.4.1, but nothing on Blueprint. I have the blueprint created with only the right device added (nsp01) and the forecast entity on the weather setting, that's all I have done with the blueprint.

You say it's not necessary to Upload TFT again, I'll probably look stupid now but that's not necessary when you do changes to the blueprint, or in this case created a new one? Will it automatically pickup the blueprint without doing anything?

**Comment by Mithrox** [comment]
Well, I now waited a bit, then I pressed Exit Reparse, and waited 10-12 seconds and pressed Update TFT display, and after a while on the boot-screen, it came up as it should. Feels somewhat random when things happen, I'll now try to get the second up as well. I won't use the big config then, I can test with the small unless I can make it work this time according to the guide.

**Comment by Mithrox** [comment]
They are now up and running both, with the minimal config and functioning blueprints. I will chalk it up to some solarwinds or other mysterious gremlins, but for now I will close this and thank you so much for all your input @edwardtfn, I really appreciate your help.

**Comment by edwardtfn** [comment]
> You say it's not necessary to Upload TFT again, I'll probably look stupid now but that's not necessary when you do changes to the blueprint

No. You only have to update the TFT when you update ESPHome and Blueprint to a new version. ESPHome only contains a few settings (from your substitutions) and the TFT file have all it's setting hard coded. The Blueprint is the one responsible for updating the screen every time a new page is opened or a value changes.
