### ISSUE TITLE
Screen Backlight Turns on in Sleep Mode 

### ISSUE THREAD

**Issue by ianmen** [Blackymas/NSPanel_HA_Blueprint#975]
Issue:
The screen backlight turns on with a blank screen (so no information / elements / screen is shown) if we change the display_brightness value while the sleep mode is on.

Expected behaviour:
In sleep mode I would not expect the screen backligth to turn on. Only if there is a touch on the touchscreen.

Steps to repeat:
1. - Make sure to be in a room with no or limited light for it to be visible.
2. - Turn NSpanel into sleep mode
3. - Wait till screen turns completely off
4. - Change vlaue of display_brightness
5. - Oberserve that screen backlight turns back on, and it is not turning off.

Example:
![IMG_6051](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/2535012/4c47c055-e4bb-4e21-bacf-ecc3bc8ac835)

**Comment by edwardtfn** [comment]
It's fixed in `dev` and will be available with the next release.
