### ISSUE TITLE
Problem with creating ESPhome file

### ISSUE THREAD

**Issue by plhy** [Blackymas/NSPanel_HA_Blueprint#976]
The problem started with NSpanel flashing at a friend with my wifi name and password. After turning on the panel, the panel failed to connect to wifi.Remained in loading state (blue screen with reboot button)
I decided to flash esp again according to the video instructions.

When I create a new item in esphome and copy the code into the new item, I can't compile the code and it writes an error, see below.

Code in ESPhome yaml:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/72349207/30d57dc2-a714-4d31-8556-59ca35fd0575)

Error log in ESPhome:
INFO Reading configuration /config/esphome/nsobyvak.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

esphome: None
  name: nsobyvak
  
  [min_version] is an invalid option for [esphome]. Please check the indentation.
  min_version: 2022.10.2 None
  build_path: .esphome/build/nsobyvak
binary_sensor.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:568]
  name: nsobyvak Nextion display
  id: nextion_init
  platform: template
  device_class: connectivity
  
  [publish_initial_state] is an invalid option for [binary_sensor.template]. Please check the indentation.
  publish_initial_state: True [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:572]
  entity_category: diagnostic
  icon: mdi:tablet-dashboard
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:735]
  name: nsobyvak Notification unread
  platform: template
  id: notification_unread
  entity_category: config
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:739]
  optimistic: True
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:743]
  name: nsobyvak Notification sound
  platform: template
  id: notification_sound
  entity_category: config
  optimistic: True
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:748]
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:751]
  name: nsobyvak Confirmation Message
  platform: template
  id: confirmation_message
  entity_category: config
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:755]
  optimistic: True
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:786]
  name: nsobyvak Sleep mode
  platform: template
  device_class: switch
  id: sleep_mode
  entity_category: config
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:791]
  optimistic: False
  turn_on_action: 
    - logger.log: Sleep mode - Turn on
    - lambda: id(disp1).send_command_printf("home.sleepmodus.val=1");
    - lambda: id(disp1).set_component_value("settings.bt1",1);
    - switch.template.publish: 
        id: sleep_mode
        state: True
  turn_off_action: 
    - logger.log: Sleep mode - Turn off
    - lambda: id(disp1).send_command_printf("home.sleepmodus.val=0");
    - lambda: id(disp1).set_component_value("settings.bt1",0);
    - switch.template.publish: 
        id: sleep_mode
        state: False
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:809]
  name: nsobyvak Relay 1 Local Fallback
  platform: template
  id: relay1_fallback
  entity_category: config
  optimistic: True
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:814]
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:816]
  name: nsobyvak Relay 2 Local Fallback
  platform: template
  id: relay2_fallback
  entity_category: config
  optimistic: True
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:821]
script: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:937]
  
  'id' is a required option for [script].
  - [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:937]
    
    Unable to find action with the name 'id'.
    id: page_timer [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:937]
    mode: restart
    parameters: 
      delay: int
    then: 
      - lambda: ESP_LOGD("nspanel", "start page-timer delay %i", int(id(page_timeout).state));
      - delay: !lambda |-
          return delay *1000;
      - lambda: |-
          DynamicJsonDocument doc(1024);
          deserializeJson(doc, id(disp1_nspanel_event).state);
          std::string page = doc["page"];
          if (page == "home" or page == "screensaver" or page == "boot" or int(id(page_timeout).state) == 0) {
            ESP_LOGD("nspanel", "no page-jump");
          } else {
            ESP_LOGD("nspanel", "timer->home");
            id(disp1).send_command_printf("page 0");
          }

I have the blueprint added in HA. However, the name of the panel cannot be selected in the automation settings (it is not visible). I have tried various things, but I have not been able to solve anything and I am at a loss.

I have ESP home updated, HA is updated.
Can you help me please? Thank you

**Comment by edwardtfn** [comment]
Some of the error messages points to an outdated ESPHome, but as you said it is updated, I would suggest cleaning the build files and trying again.

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/b1eb2f0b-0384-4cfc-972a-cd65e15a0269)

**Comment by plhy** [comment]
Thanks for your reply. When I click on "clean build files" an error appears:

INFO Reading configuration /config/esphome/nsobyvak.yaml...
WARNING Found '${nextion_update_url}' (see display->0->tft_url) which looks like a substitution, but 'nextion_update_url' was not declared
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

esphome: None
  name: nsobyvak
  
  [min_version] is an invalid option for [esphome]. Please check the indentation.
  min_version: 2022.10.2 None
  build_path: .esphome/build/nsobyvak
binary_sensor.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:568]
  name: nsobyvak Nextion display
  id: nextion_init
  platform: template
  device_class: connectivity
  
  [publish_initial_state] is an invalid option for [binary_sensor.template]. Please check the indentation.
  publish_initial_state: True [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:572]
  entity_category: diagnostic
  icon: mdi:tablet-dashboard
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:735]
  name: nsobyvak Notification unread
  platform: template
  id: notification_unread
  entity_category: config
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:739]
  optimistic: True
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:743]
  name: nsobyvak Notification sound
  platform: template
  id: notification_sound
  entity_category: config
  optimistic: True
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:748]
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:751]
  name: nsobyvak Confirmation Message
  platform: template
  id: confirmation_message
  entity_category: config
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:755]
  optimistic: True
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:786]
  name: nsobyvak Sleep mode
  platform: template
  device_class: switch
  id: sleep_mode
  entity_category: config
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:791]
  optimistic: False
  turn_on_action: 
    - logger.log: Sleep mode - Turn on
    - lambda: id(disp1).send_command_printf("home.sleepmodus.val=1");
    - lambda: id(disp1).set_component_value("settings.bt1",1);
    - switch.template.publish: 
        id: sleep_mode
        state: True
  turn_off_action: 
    - logger.log: Sleep mode - Turn off
    - lambda: id(disp1).send_command_printf("home.sleepmodus.val=0");
    - lambda: id(disp1).set_component_value("settings.bt1",0);
    - switch.template.publish: 
        id: sleep_mode
        state: False
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:809]
  name: nsobyvak Relay 1 Local Fallback
  platform: template
  id: relay1_fallback
  entity_category: config
  optimistic: True
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:814]
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:816]
  name: nsobyvak Relay 2 Local Fallback
  platform: template
  id: relay2_fallback
  entity_category: config
  optimistic: True
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:821]
script: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:937]
  
  'id' is a required option for [script].
  - [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:937]
    
    Unable to find action with the name 'id'.
    id: page_timer [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:937]
    mode: restart
    parameters: 
      delay: int
    then: 
      - lambda: ESP_LOGD("nspanel", "start page-timer delay %i", int(id(page_timeout).state));
      - delay: !lambda |-
          return delay *1000;
      - lambda: |-
          DynamicJsonDocument doc(1024);
          deserializeJson(doc, id(disp1_nspanel_event).state);
          std::string page = doc["page"];
          if (page == "home" or page == "screensaver" or page == "boot" or int(id(page_timeout).state) == 0) {
            ESP_LOGD("nspanel", "no page-jump");
          } else {
            ESP_LOGD("nspanel", "timer->home");
            id(disp1).send_command_printf("page 0");
          }

**Comment by edwardtfn** [comment]
Could you please share your ESPHome yaml settings again? The error message says `nextion_update_url` is missing.

**Comment by plhy** [comment]
You're right. I had a "#" before this line in the esp yaml.
I'm attaching the esp yaml just to be sure:

substitutions:

###### CHANGE ME START ######

  device_name: "nsobyvak" 
  wifi_ssid: "xxx"
  wifi_password: "xxx"

  nextion_update_url: "http://192.xxx.x.xxx:8123/local/nspanel_eu.tft" # URL to local tft File /config/www/nspanel_eu.tft            http://192.xxx.x.xxx:8123/local/nspanel_eu.tft
#    nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####


Now when I click on "clean build files" I get the following error:

INFO Reading configuration /config/esphome/nsobyvak.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

esphome: None
  name: nsobyvak
  
  [min_version] is an invalid option for [esphome]. Please check the indentation.
  min_version: 2022.10.2 None
  build_path: .esphome/build/nsobyvak
binary_sensor.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:568]
  name: nsobyvak Nextion display
  id: nextion_init
  platform: template
  device_class: connectivity
  
  [publish_initial_state] is an invalid option for [binary_sensor.template]. Please check the indentation.
  publish_initial_state: True [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:572]
  entity_category: diagnostic
  icon: mdi:tablet-dashboard
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:735]
  name: nsobyvak Notification unread
  platform: template
  id: notification_unread
  entity_category: config
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:739]
  optimistic: True
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:743]
  name: nsobyvak Notification sound
  platform: template
  id: notification_sound
  entity_category: config
  optimistic: True
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:748]
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:751]
  name: nsobyvak Confirmation Message
  platform: template
  id: confirmation_message
  entity_category: config
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:755]
  optimistic: True
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:786]
  name: nsobyvak Sleep mode
  platform: template
  device_class: switch
  id: sleep_mode
  entity_category: config
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:791]
  optimistic: False
  turn_on_action: 
    - logger.log: Sleep mode - Turn on
    - lambda: id(disp1).send_command_printf("home.sleepmodus.val=1");
    - lambda: id(disp1).set_component_value("settings.bt1",1);
    - switch.template.publish: 
        id: sleep_mode
        state: True
  turn_off_action: 
    - logger.log: Sleep mode - Turn off
    - lambda: id(disp1).send_command_printf("home.sleepmodus.val=0");
    - lambda: id(disp1).set_component_value("settings.bt1",0);
    - switch.template.publish: 
        id: sleep_mode
        state: False
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:809]
  name: nsobyvak Relay 1 Local Fallback
  platform: template
  id: relay1_fallback
  entity_category: config
  optimistic: True
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:814]
switch.template: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:816]
  name: nsobyvak Relay 2 Local Fallback
  platform: template
  id: relay2_fallback
  entity_category: config
  optimistic: True
  
  [restore_mode] is an invalid option for [switch.template]. Did you mean [restore_state]?
  restore_mode: RESTORE_DEFAULT_OFF [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:821]
script: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:937]
  
  'id' is a required option for [script].
  - [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:937]
    
    Unable to find action with the name 'id'.
    id: page_timer [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:937]
    mode: restart
    parameters: 
      delay: int
    then: 
      - lambda: ESP_LOGD("nspanel", "start page-timer delay %i", int(id(page_timeout).state));
      - delay: !lambda |-
          return delay *1000;
      - lambda: |-
          DynamicJsonDocument doc(1024);
          deserializeJson(doc, id(disp1_nspanel_event).state);
          std::string page = doc["page"];
          if (page == "home" or page == "screensaver" or page == "boot" or int(id(page_timeout).state) == 0) {
            ESP_LOGD("nspanel", "no page-jump");
          } else {
            ESP_LOGD("nspanel", "timer->home");
            id(disp1).send_command_printf("page 0");
          }

Alternatively, if it helps I could give you access to my HA. Because I really don't know what to do next.

**Comment by edwardtfn** [comment]
When sharing code, please select the whole code and press this "Add code" button in the top of the editing box:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/8dff7323-e3ba-428c-97bd-8e2b8edcd0cc)

So it is readable and instead of looking like this:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/81f005e6-4af7-470b-bfb5-45693cdff442)

It will look like this:

```
substitutions:

###### CHANGE ME START ######

  device_name: "nsobyvak" 
  wifi_ssid: "xxx"
  wifi_password: "xxx"

  nextion_update_url: "nextion_update_url: "http://192.xxx.x.xxx:8123/local/nspanel_eu.tft" # URL to local tft File /config/www/nspanel_eu.tft
##### CHANGE ME END #####

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```

;)

Could you please try to share it again, now properly formatted? :)

**Comment by plhy** [comment]
Sorry my bad.

Here:
`
substitutions:

###### CHANGE ME START ######

  device_name: "nsobyvak" 
  wifi_ssid: "Plhal"
  wifi_password: "Mi456chal"

  nextion_update_url: "http://192.168.1.251:8123/local/nspanel_eu.tft" # URL to local tft File /config/www/nspanel_eu.tft            http://192.168.1.251:8123/local/nspanel_eu.tft
#    nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
`

**Comment by plhy** [comment]
`substitutions:

###### CHANGE ME START ######

  device_name: "nsobyvak" 
  wifi_ssid: "XXX"
  wifi_password: "XXX"

  nextion_update_url: "http://192.xxx.x.xxx:8123/local/nspanel_eu.tft" # URL to local tft File /config/www/nspanel_eu.tft            `http://192.xxx.x.xxx:8123/local/nspanel_eu.tft`
#    nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####`

**Comment by plhy** [comment]
```
substitutions:

###### CHANGE ME START ######

  device_name: "nsobyvak" 
  wifi_ssid: "XXX"
  wifi_password: "XXX"

  nextion_update_url: "http://192.xxx.x.xxx:8123/local/nspanel_eu.tft" # URL to local tft File /config/www/nspanel_eu.tft            http://192.xxx.x.xxx:8123/local/nspanel_eu.tft
#    nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```

**Comment by Doughboy68** [comment]
> The problem started with NSpanel flashing at a friend with my wifi name and password. After turning on the panel, the panel failed to connect to wifi.Remained in loading state (blue screen with reboot button) I decided to flash esp again according to the video instructions.
> 
> When I create a new item in esphome and copy the code into the new item, I can't compile the code and it writes an error, see below.

Can you please clarify what you did here?
It sounds like you took your NSpanel to a friend's place and used your friend's home assistant to flash a panel with your wifi info, which then did not work taking back to your place, and your Home Assistant setup will not compile, but your friend's did?

From the errors, it seems you are using an older version of ESPHome. Confirm your version of ESPHome here (current version is 2023.7.1). 

Do you have any other ESPHome devices that are working on your system?
What if you just make a new test device and install, manual download and see if it compiles.
On mine, the version number appears as first line in all my output, but the logs  your post do not show that... maybe old version does not display or you are not copying the first line?

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16811687/1aa3be98-e723-42a8-8f1c-b186c63208b5)

**Comment by plhy** [comment]
A friend used to use Nspanel (with a blueprint) but he bought a black one and gave me this one. In his Homeassistant, the panel would air flash to my wifi data. When I turned on the panel at home, it remained in the blue boot screen and offered only reboot, which did not work.
I decided to flash it in my HA where I ran into this problem that the ESP configuration could not be installed. Several devices like ESP32, wemos d1 mini, quin led, etc. work for me on esp. When I create a new one, e.g. ESP32, it works normally. I have updated ESP home (HA does not offer updating ESPhome). But when I make a new esp, it doesn't show me the ESP version during installation like you show. Could this not be the problem?

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/72349207/8e9336a6-4cf7-4206-b2da-58ba8f40df03)

**Comment by deejaybeam** [comment]
> A friend used to use Nspanel (with a blueprint) but he bought a black one and gave me this one. In his Homeassistant, the panel would air flash to my wifi data. When I turned on the panel at home, it remained in the blue boot screen and offered only reboot, which did not work. I decided to flash it in my HA where I ran into this problem that the ESP configuration could not be installed. Several devices like ESP32, wemos d1 mini, quin led, etc. work for me on esp. When I create a new one, e.g. ESP32, it works normally. I have updated ESP home (HA does not offer updating ESPhome). But when I make a new esp, it doesn't show me the ESP version during installation like you show. Could this not be the problem?
> 
> ![image](https://user-images.githubusercontent.com/72349207/260288938-8e9336a6-4cf7-4206-b2da-58ba8f40df03.png)

NO, this could not be a problem - otherwise it would fail to compile.

Why don´t you just re-install esphome via TTL-Converter?

**Comment by Doughboy68** [comment]
Still did not confirm the version of ESPHome. If running HasOS then go to settings, addons, ESPHome and see what version it is.

**Comment by plhy** [comment]
I found the problem. For some reason, I used the old version of ESPhome integration, see the first photo.
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/72349207/4b0da04d-4d71-4cdc-b460-f81e19ec75af)

Now I have it flashed, but I have another problem :-D
Loading still lights up on NSpanel.
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/72349207/0e21235a-c8f2-4e35-a78e-574dd73d0dd3)

When I select my NSpanel in the blueprint, I have a big letter there, but everywhere I have small letters, which is weird.
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/72349207/db09fbc8-780f-4e2f-92df-25c5d057214a)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/72349207/def78293-418b-49ed-aeab-2375ff0ff0b6)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/72349207/8f91aa9e-737b-4044-a784-3992fdeea524)
Could this be a problem?

**Comment by plhy** [comment]
I fixed the large letter, but the loading problem persists.

**Comment by edwardtfn** [comment]
Great, you are a step ahead.

Can you see anything in Home Assistant logs (Settings > System > Logs)?

Have you tried restarting everything (your panel and Home Assistant)?

**Comment by edwardtfn** [comment]
I don't think the big letter would be a problem. That is only a front end thing.

**Comment by plhy** [comment]
Yes,I restarted everything.
Errors in log:
`Logger: homeassistant.components.automation.nspanel_configuration
Source: components/esphome/manager.py:649
Integration: Automation (documentation, issues)
First occurred: 14:41:00 (12 occurrences)
Last logged: 15:18:01

NSPanel Configuration: Main choices: Date & Time: If at step 1: Error executing script. Unexpected error for call_service at pos 5: Authenticated connection not ready yet for nsobyvak @ 192.168.1.55; current state is ConnectionState.INITIALIZED!
NSPanel Configuration: Main choices: Date & Time: Error executing script. Unexpected error for if at pos 1: Authenticated connection not ready yet for nsobyvak @ 192.168.1.55; current state is ConnectionState.INITIALIZED!
NSPanel Configuration: Error executing script. Unexpected error for choose at pos 1: Authenticated connection not ready yet for nsobyvak @ 192.168.1.55; current state is ConnectionState.INITIALIZED!
While executing automation automation.nspanel_configuration
NSPanel Configuration: Main choices: Date & Time: If at step 1: Error executing script. Unexpected error for call_service at pos 7: Authenticated connection not ready yet for nsobyvak @ 192.168.1.55; current state is ConnectionState.INITIALIZED!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/esphome/manager.py", line 649, in execute_service
    await entry_data.client.execute_service(service, call.data)
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 1287, in execute_service
    self._check_authenticated()
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 307, in _check_authenticated
    raise APIConnectionError(
aioesphomeapi.core.APIConnectionError: Authenticated connection not ready yet for nsobyvak @ 192.168.1.55; current state is ConnectionState.INITIALIZED!
`


`Logger: aioesphomeapi.connection
Source: runner.py:179
First occurred: 14:14:45 (8 occurrences)
Last logged: 15:18:00

nsobyvak @ 192.168.1.55: Connection error occurred: [Errno 104] Connection reset by peer`

**Comment by edwardtfn** [comment]
Mmmmm
Looks like your panel is reseting the connection to Home Assistant... I have no idea why this is happening.

When you go to the panel's device page (Settings > Devices and Services > ESPHome), can you control your device from there? Toggle relays, restart, etc)?
Can you see anything in ESPHome logs (ESPHome dashboard > your device > Logs)?

**Comment by plhy** [comment]
I can control from the panel's device page. Restart, Update TFT display, everything works.
There is no error in the ESPHome logs. Everything looks good. The second nspanel photo shows the entity, but it has no data loaded and is not responding.
I'm already very sad about it.

**Comment by plhy** [comment]
The original problem is solved. I'll close the thread and create a new one.
