### ISSUE TITLE
New Feature Request :)

### ISSUE THREAD

**Issue by AFid08** [Blackymas/NSPanel_HA_Blueprint#979]
#Hi @edwardtfn
I actually have a few suggestions:

In the automation for programming the Panel, a drop-down menu would be good, where I can choose which section to jump to edit. Scrolling in automation is currently very slow.

Make the timeout to jump back to the main menu adjustable. E.g. button menu 1 - if not selected - jump back after xx seconds.

Regards
AFid08

**Comment by edwardtfn** [comment]
> In the automation for programming the Panel, a drop-down menu would be good, where I can choose which section to jump to edit. Scrolling in automation is currently very slow.

Unfortunately this is a limitation from Home Assistant which doesn't have any grouping capabilities for blueprint inputs.



> Make the timeout to jump back to the main menu adjustable. E.g. button menu 1 - if not selected - jump back after xx seconds.

It is already adjustable by users.
Go to your device page (Settings > Devices and Services > ESPHome) and play with "Page timeout".
![IMG_6385](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/1c5402a6-faaa-494b-a47c-5f2f0390002b)
