### ISSUE TITLE
Nspanel won’t connect to flash with esphome

### ISSUE THREAD

**Issue by jdmevo123** [Blackymas/NSPanel_HA_Blueprint#981]
Looking for some advice here, I’m at my wits end trying to flash the binary.

so far I have tried two different usb flashers, I’ve tried holding the reset button, and still nothing. I’ve tried different flash tools like esp-flasher, and nothing is working.

![AF98B2AF-F232-49BB-92EB-ABE5D45D8EFD](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/6053506/282eaa59-a583-4e90-b627-7f2fa71d007a)

I constantly get told it can’t connect. Is there anything else I can try? Or does this mean the panel is faulty?

I should note that I can pull the logs from the device which is seen here:

**Comment by jdmevo123** [comment]
![Uploading IMG_7027.jpeg…]()

**Comment by edwardtfn** [comment]
> I’ve tried holding the reset button

Which reset button?
Could you please share a picture of your wiring?

**Comment by jdmevo123** [comment]
The one on the nspanel.

here are some photos, it worked perfectly for my first ma panel, but now nothing for this one.

![Uploading IMG_7031.jpeg…]()

**Comment by edwardtfn** [comment]
I didn't got any picture of your wiring/board. Could you please share again?

**Comment by jdmevo123** [comment]
![IMG_7031](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/6053506/b8778cee-5ccd-4236-b34e-338b3a8d4f1b)
![IMG_7029](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/6053506/4da6c275-a117-4d8a-a7bf-74a3e2295fe3)

**Comment by edwardtfn** [comment]
Ok.
I cannot see exactly how the grey and red(?) wires are connected to your adapter, but it is important to make sure `rx` from your adapter must be connected to `tx` in the panel and `tx` from né adapter to `rx` in the panel. From your pictures I got an impressions that you have connected `rx` to `rx`.

**Comment by edwardtfn** [comment]
Also, to make your life a bit easier, although this is not gonna solve the problem you described, you can connect the yellow wire from `IO0` to another `GND` pin in your panel's board (there's a place with multiple pins where its pretty easy to connect) so you don't have to split the `GND` pin from your adapter.
![IMG_6388](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/5e582971-f3ab-4c23-93d3-0c8c113bde01)

**Comment by trinitrion** [comment]
Timing is also important and can be tricky. 

You need to connect the IO0 and one of the GND pins to force the NSPanel to boot in flash mode, as said above. 

In my experience it can help if you connect either the serial adapter or the board right before you hit the flashing button or shortly after.

**Comment by edwardtfn** [comment]
Hi  @jdmevo123, are you still having trouble with this or should we close this issue?
