### ISSUE TITLE
Wake up the screen

### ISSUE THREAD

**Issue by drbiosignals** [Blackymas/NSPanel_HA_Blueprint#99]
Thank you for this great job! Is there a way to remotely wake up the screen after deactivating sleep mode? Like lovelace I am trying to create an automation in order to automatically turn off and on the sceeen for instance at night.
Thank you!

**Comment by drbiosignals** [comment]
Thank you. This command worked great!

**Comment by Blackymas** [comment]
perfect and have fun ;)
