### ISSUE TITLE
Settings button/icon and other stuff missing

### ISSUE THREAD

**Issue by trinitrion** [Blackymas/NSPanel_HA_Blueprint#996]
Hi,

when I discovered this aweome project I knew right away that this is the thing I want to do with the Sonoff NSPanel. Thanks for the excellent work!

_I recently flashed my second NSPanel as the first one obviously bricked the TFT. Will certainly open another issue at some time to work this out if anyone feels inclined to help. ;) but that's for another time._ 

Anyways, setting up the new NSPanel went fine so far and I opted right away for the Tasmota method, i.e. I first flashed Tasmota, flashed via tasmota the nspanel_blank.tft and then nspanel_eu.tft with tasmota and then flashed this project with ESPHome in Home Assistant. This finally worked.

However, there is "the problem" - see below. Hope you can help me out.

#### HomeAssistant
Home Assistant 2023.8.4
Supervisor 2023.08.1
Operating System 10.5
Frontend 20230802.1 - latest

####  ESPHome
Firmware: 2023.8.2 (Aug 24 2023, 20:51:52)

#### Panel

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/105319980/e8148257-8422-4ef9-b164-cd03d81cb15c)

### The problem:

I can set up buttons, sensors and stuff in the blueprint but then some icons do not appear at the panel where they should.

- Foremost the settings icon is missing and I am not even getting to the settings menu by pressing the area where the I suppose the settings wheel should sit. No joy.
- The room temperature occasionally disappears. When I delete and reassign the sensor in the blueprint, it does work again.
- I can only access lights and whether forecast. Nothing else.

### Here is how the screen looks like:

![IMG_8712](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/105319980/fd0f1fdc-cbd9-49f9-91eb-2980ec217e2e)

### What I tried

I completely deleted the blueprints and set them up again. No joy.

**Comment by edwardtfn** [comment]
> I recently flashed my second NSPanel as the first one obviously bricked the TFT. Will certainly open another issue at some time to work this out if anyone feels inclined to help. ;)

Send a picture of that screen when opening another ticket. It always helps.

> Foremost the settings icon is missing and I am not even getting to the settings menu by pressing the area where the I suppose the settings wheel should sit. No joy.

The settings icon was gone a while ago. Now you open the settings screen with a long press on the time area.

By the way, as you are going there, try pressing the Reset button and then share with us the versions you see on the blue boot screen for TFT, ESPHome and Blueprint. That info helps a lot.

> I can only access lights and whether forecast. Nothing else.

What happens when you swipe the screen?
What else are you expecting?

**Comment by trinitrion** [comment]
Hi @edwardtfn , thanks for your reply.

I feel really stupid, the settings menu is all there when long pressing the time area. 💯 

Let me observe the rest of my points, looks like I need to get used to working the this for a while. Will then open another issue or reopen this one, if necessary. ;)


>By the way, as you are going there, try pressing the Reset button and then share with us the versions you see on the blue boot screen for TFT, ESPHome and Blueprint. That info helps a lot.

Added to initial post. It does not show blueprint version, is this expected?

**Comment by edwardtfn** [comment]
> Added to initial post. It does not show blueprint version, is this expected?

Sorry, I've missed that.
It should show the Blueprint version for couple of seconds before switching to the home page.

**Comment by trinitrion** [comment]
You didn't miss it, just added upon your hint. Now inlcuding BP version. 

I think we can close this matter. I might have been to nervous because if the missing "settings" button. 

Thanks for your swift help.
