### ISSUE TITLE
Feature Request: disable empty pages

### ISSUE THREAD

**Issue by aep** [Blackymas/NSPanel_HA_Blueprint#999]
i find the sliding motion a bit fiddly. i have to do it correctly or it will end up on the second page which is empty for me.
this makes it rather hard to use when you just want to come home and switch on lights.

would be nice if the pages that dont contain buttons could be disabled

i'd even prefer having no home screen, just buttons

**Comment by edwardtfn** [comment]
Hide empty pages is something we have on mind. It will require a bit of redesign, as those bullets in the bottom indicating current page are part of the page background, but nothing that is not possible. Just need to be done.

v4.0 is coming very soon and that will introduce the capability to set your wake up page, which means you will be able to set your panel to wake up directly to the buttons page of your choice. Your panel will still falling back to the Home page after the timeout, but if you follow the suggestion from @Rob65, that will never happens in an automated way (it still going there when you click the close page button).

**Comment by edwardtfn** [comment]
Similar to:
#868 
#946

**Comment by aep** [comment]
> > For me, sliding up/down always gives me page 2 while a right/left slide gives me the 1st button page.

> Are you sure your panel is doing something different than that?

no its working correctly, i just dont like it, hence the feature request :D

> If you set the timeout on the ESPHome device page in HA to 0, your panel will stay on the button page and not switch back to home.

woa nice trick! thanks.
this is sufficient for me.

**Comment by aep** [comment]
aaah too early. now when setting timeout to 0 it also wont dim anymore. apparantly it will only dim when you're on home.

**Comment by edwardtfn** [comment]
That’s true. The sleep routine is on ESPHome, but the dimming is on the TFT and is Home page only.
Maybe that should be moved to ESPHome now that we can choose the wake-up page... I will take a look at that.

**Comment by aep** [comment]
thanks so much for all of this. i'm using the buttons on the homescreen for now and its already amazing.

**Comment by edwardtfn** [comment]
It is still pending more tests, but this is implemented in `dev´ and hopefully will be released with v4.3 soon.
I've implemented only for button pages and for entities pages for now, as I wanna review the whole weather pages in the near future.

I'm closing this for now to clean-up my backlog, but please feel free to add comments or to reopen-it if the new solution is not solving the issue.

**Comment by edwardtfn** [comment]
Hi, have you got a chance to try the solution for this currently in beta? If so, please let me know if that was effective.
